### ISSUE TITLE
[Platform] [docdb] Validate gflags and raise error if any are invalid

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#6952] opened 2021-01-21 19:19 UTC
Jira Link: [DB-4733](https://yugabyte.atlassian.net/browse/DB-4733)
If the admin is setting gflags, an error should be raised if any of the entered gflags are invalid (like a typo in the gflag name). I guess the validation needs to be done by docdb and the error propagated to YW

**Comment by streddy-yb** [comment] 2021-03-15 01:03
Currently there is no metadata associated with the gflags (ex: valid gflag names, expected types, valid ranges, etc), so it is hard to provide client side checking on the Platform side. However, providing pre-checks for most commonly used gflags is still quite valuable.

**Comment by iSignal** [comment] 2021-05-19 20:47
The list of available gflags, gflag types and default values can be summarized in an XML file by running `bin/yb-master --helpxml`. If we package this with the db release, we would be able to provide validation and a browsable list of gflags in Platform UI.

**Comment by ymahajan** [comment] 2021-08-10 05:10
I know, we plan to target the gold-plated solution in the next release, but we should fix the low-hanging issues immediately.
We can’t punt down the whole bucket of issues for the next release. ltrim, rtrim should be enforced, check for double quotes, single quotes validation for GFlags wherever applicable. allowed values should be validated, min max should be shown so that users know what to enter. We should fix these low-hanging things, which will fix 80% of the problems reported. 
The simple validations in GFlags will avoid the nightmare of debuting complex issues caused by incorrect GFlags getting applied on Database nodes.

**Comment by bmatican** [comment] 2023-01-10 21:39
Since now we have the xml file generated at build time and handled in YBA, closing this.

**Closed by bmatican** 2023-01-10 21:39 UTC
Labels: kind/enhancement, area/docdb, priority/high, status/awaiting-triage
