### ISSUE TITLE
[YSQL] Master UI: Users should be able to find the tablegroup ID from the tablegroup name

### ISSUE THREAD

**Issue by lnguyen-yugabyte** [yugabyte/yugabyte-db#11597] opened 2022-02-25 18:25 UTC
Jira Link: [DB-988](https://yugabyte.atlassian.net/browse/DB-988)
### Description

Currently the tablegroup name is displayed as following on the UI / queried via yb-admin: `[000033e1000030008000000000004101.tablegroup.parent.tablename]`

Instead, we should be able to show the tablegroup name as created by user.

(Note that currently it's _possible_ to look up the tablegroup ID from name in an indirect way: look up the YSQL OID associated with the table, and look up on the UI the tablegroup ID with the given OID. However we should not have to resort through YSQL OID for this.)

**Comment by frozenspider** [comment] 2022-03-11 12:56
Technical details: ID `000033e1000030008000000000004101` can be parsed to get database OID and table OID (which is actually a tablegroup OID). We can then do a lookup in `pg_yb_tablegroup` table by OID to get the actual group name.

**Comment by tverona1** [comment] 2022-09-29 21:52
Closing this as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/5086. We won't show tablegroup name as part of colocation GA.

**Closed by tverona1** 2022-09-29 21:52 UTC
Labels: kind/bug, area/ysql, priority/medium
