### ISSUE TITLE
[YSQL] IN query should use index

### ISSUE THREAD

**Issue by frozenspider** [YugaByte/yugabyte-db#1554] opened 2019-06-17 17:12 UTC
Given the schema:
```sql
CREATE TABLE elements (id int PRIMARY KEY, val int, grp int);
CREATE INDEX elements_idx ON elements (grp) INCLUDE (val);
```
`EXPLAIN` shows that only the first of the following cases involves index:
```
postgres=# EXPLAIN SELECT val FROM elements WHERE grp = 3;
                                    QUERY PLAN
----------------------------------------------------------------------------------
 Index Only Scan using elements_idx on elements  (cost=0.00..4.11 rows=1 width=4)
   Index Cond: (grp = 3)
```
```
postgres=# EXPLAIN SELECT val FROM elements WHERE grp IN (1,2,3);
                           QUERY PLAN
-----------------------------------------------------------------
 Foreign Scan on elements  (cost=0.00..103.75 rows=1000 width=4)
   Filter: (grp = ANY ('{1,2,3}'::integer[]))
```
```
postgres=# EXPLAIN SELECT val FROM elements WHERE grp > 1 AND grp < 2;
                           QUERY PLAN
-----------------------------------------------------------------
 Foreign Scan on elements  (cost=0.00..105.00 rows=1000 width=4)
   Filter: ((grp > 1) AND (grp < 2))
```
(`BETWEEN`, etc. are also worth checking)

For reference, in Postgres they all have plans like this:
```
fs=# EXPLAIN SELECT val FROM elements WHERE grp IN (1,2,3);
                                 QUERY PLAN
----------------------------------------------------------------------------
 Bitmap Heap Scan on elements  (cost=4.69..15.12 rows=31 width=4)
   Recheck Cond: (grp = ANY ('{1,2,3}'::integer[]))
   ->  Bitmap Index Scan on elements_idx  (cost=0.00..4.68 rows=31 width=0)
         Index Cond: (grp = ANY ('{1,2,3}'::integer[]))
```

**Comment by frozenspider** [comment] 2019-06-17 17:12
Possibly related to #1531

**Comment by frozenspider** [comment] 2019-06-17 17:18
Related issue: 995

**Comment by ndeodhar** [comment] 2019-06-17 17:18
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/1223 and https://github.com/YugaByte/yugabyte-db/issues/995

**Comment by bmatican** [comment] 2019-06-20 21:58
Talked to @m-iancu earlier, maybe let's hold on this for a while @JDNdeveloper, until we realize if there's a bottleneck on being able to have more folks working on these types of optimizations.

**Closed** 2019-08-23 19:12 UTC
Labels: kind/enhancement
