### ISSUE TITLE
[YSQL] Restore a backup of a colocated database from old release to new release ignores data

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#14785] opened 2022-11-01 22:05 UTC
Jira Link: [DB-4103](https://yugabyte.atlassian.net/browse/DB-4103)
### Description

The reason we exported `with (table_oid = ...)` in ysql_dump in the past was that we included table ID in the row key (table ID is stored in tablets' sst file). Later on, we switched to including colocation id in the row keys of users' colocated tables and exported `with (colocation_id = ...)` in ysql_dump.
No matter what we export in ysql_dump, import_snapshot can match tables successfully by UUIDs or names. yb_backup.py simply uses the output of import_snapshot.
However, if we restore a backup of a colocated database with an old release version where table oid is in the row key and ysql_dump dumpfile contains `with (table_oid = ...)` syntax to a cluster running on a new release version where colocation id is in the row key, then the restore possibly still succeed, but SELECTs on the restored colocated table can return wrong results because of unmatched row key prefix value.

Example:
One table on a old release can have the following DocKey format:
DocKey(TableId=<table_id>, [], ["p`5\xf3\xd8xE\xba\xa8f\x9d\xa0[\x9c\xa2\xee"])
After a restore re-creates the table on a new release, its DocKey contains the generated colocation id instead of table id:
DocKey(ColocationID=3379400959, [], ["p`5\xf3\xd8xE\xba\xa8f\x9d\xa0[\x9c\xa2\xee"])

In https://github.com/yugabyte/yugabyte-db/commit/71d527c69554e5380788b3b20b20aa2b35d23bb2, Alex has added backward compatibility to treat TableID as ColocationID in `catalog_loader`.
One potential solution is to change the underlying behavior of `with (table_oid = ...)` syntax to the same as `with (colocation_id = ...)`.

**Comment by tverona1** [comment] 2022-12-12 22:43
Triage - resolving as won't fix for now. The issue is unlikely to be hit by a user. Also, the fix is on the restore side.

If a user attempts to restore an old colocated database (> 9 months ago) and runs into this issue, we can fix it at that time.

**Closed** 2022-12-12 22:43 UTC
Labels: kind/bug, area/ysql, priority/medium
