### ISSUE TITLE
[YSQL] Restore can fail if target cluster's num-tablets defaults differ from the source

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#9663] opened 2021-08-11 07:31 UTC
Generally,`ysql_dump` output (which is used internally for backup) will include the number tablets for each table/index as part of the output syntax.
This ensures that tables/indexes get re-created with the "correct" number of tablets, matching the ones from the snapshot.
However, if tables/indexes are created _implicitly_, we don't have syntactic annotations for number of tablets, so the default config will be used to pick.
That can be different from the ones is the data snapshot, leading restore to fail.
Some known examples for these are:
* indexes created by unique constraints 
* tables/indexes created by "CREATE EXTENSION" commands

**Comment by jaki** [comment] 2021-08-25 01:46
Isn't this a duplicate of issue #8229?

**Closed by jaki** 2021-08-25 01:46 UTC
Labels: area/ysql
