### ISSUE TITLE
[Platform] Metrics page for Tables is not rendering 

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5480] opened 2020-08-25 00:13 UTC
In YW Tables page, click on any table, then click on Metrics.
I see this is broken in 2.1.10, 2.2.2 and latest

**Comment by streddy-yb** [comment] 2020-09-15 21:06
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/5582

**Closed by streddy-yb** 2020-09-15 21:06 UTC
Labels: kind/bug, priority/high
