### ISSUE TITLE
[YSQL] Maximum number of connections got reduced after 2.17.3.0-b92 build

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#16567] opened 2023-03-27 15:22 UTC
Jira Link: [DB-5971](https://yugabyte.atlassian.net/browse/DB-5971)
### Description

We might have a regression in connection scaling stress tests - in 2.17.3.0-b91 we allow to have 600+ connections, while after build 92 we got failed on only 400.

All related flags are explicitly enabled:
```
"tserver_gflags": {
    "ysql_max_connections": MAX_CONNECTIONS,
    "ysql_enable_read_request_caching": "true",
    "ysql_catalog_preload_additional_tables": "true",
},
"master_gflags": {
    "ysql_max_connections": MAX_CONNECTIONS,
    "ysql_enable_read_request_caching": "true",
    "ysql_catalog_preload_additional_tables": "true",
}
```

[DB-5971]: https://yugabyte.atlassian.net/browse/DB-5971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment] 2023-03-27 16:04
Based on initial look at the logs, it looks like t-server on 172.151.30.246 failed over:

PG hitting timeouts:
`W0327 14:06:21.494319 23437 yb_rpc.cc:495] Connection (0x000055a4ab96d578) client 172.151.30.246:59534 => 172.151.30.246:9100: Network error (yb/rpc/yb_rpc.cc:494): Rpc timeout, passed: 15.092s, timeout: 15.000s, now: 2165.252s, last_read_time_: 2150.160s`

Failover detected of leader for tablet 95aec905d2c14160b5b12dd91245939f (which is 172.151.30.246):
```
I0327 14:06:09.943619 12246 raft_consensus.cc:1029] T 54602aa0dd2b4b808b5443dadc40b12f P 6520034099964675b1e058b87fe57a83 [term 1 FOLLOWER]: ReportFailDetected: Starting NORMAL_ELECTION...
I0327 14:06:09.943639 12246 raft_consensus.cc:622] T 54602aa0dd2b4b808b5443dadc40b12f P 6520034099964675b1e058b87fe57a83 [term 1 FOLLOWER]: Fail of leader 95aec905d2c14160b5b12dd91245939f detected. Triggering leader pre-election, mode=NORMAL_ELECTION
```

Around the same time, we see free memory for 172.151.30.246 is quite low, so perhaps this is due to OOM:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/10568693/227997186-2511f777-c60a-40cd-b97a-94a0910794ba.png">

**Comment by kai-franz** [comment] 2023-10-23 19:18
This issue was caused by [D22407](https://phorge.dev.yugabyte.com/D22407) introducing behavior that unconditionally preloads certain system tables when `ysql_enable_read_request_caching` is enabled, which can significantly increase PG backend process memory usage. It has been resolved in [D28071](https://phorge.dev.yugabyte.com/D28071), which reverts those changes.

**Closed by kai-franz** 2023-10-23 19:18 UTC
Labels: kind/bug, area/ysql, priority/high
