### ISSUE TITLE
[DocDB][TSAN Unit Test Failure][2.8] BackupTxnTest.DeleteTable

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#14061] opened 2022-09-19 16:03 UTC
Jira Link: [DB-3555](https://yugabyte.atlassian.net/browse/DB-3555)
### Description

On 2.8.10.0-b6 there is a data race in BackupTxnTest.DeleteTable:
```
WARNING: ThreadSanitizer: data race (pid=23346)
  Write of size 8 at 0x7b6c000d1eb0 by thread T250:
    #0 yb::rpc::Poller::Start(yb::rpc::Scheduler*, yb::MonoDelta) /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rpc/poller.cc:31:14 (libyrpc.so+0x1af644)
    #1 yb::tablet::TransactionParticipant::Impl::LoadFinished(std::__1::unordered_map<yb::StronglyTypedUuid<yb::TransactionId_Tag>, yb::tablet::ApplyStateWithCommitHt, boost::hash<yb::StronglyTypedUuid<yb::TransactionId_Tag> >, std::__1::equal_to<yb::StronglyTypedUuid<yb::TransactionId_Tag> >, std::__1::allocator<std::__1::pair<yb::StronglyTypedUuid<yb::TransactionId_Tag> const, yb::tablet::ApplyStateWithCommitHt> > > const&) /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/tablet/transaction_participant.cc:1029:13 (libtablet.so+0x3145c1)
    #2 non-virtual thunk to yb::tablet::TransactionParticipant::Impl::LoadFinished(std::__1::unordered_map<yb::StronglyTypedUuid<yb::TransactionId_Tag>, yb::tablet::ApplyStateWithCommitHt, boost::hash<yb::StronglyTypedUuid<yb::TransactionId_Tag> >, std::__1::equal_to<yb::StronglyTypedUuid<yb::TransactionId_Tag> >, std::__1::allocator<std::__1::pair<yb::StronglyTypedUuid<yb::TransactionId_Tag> const, yb::tablet::ApplyStateWithCommitHt> > > const&) /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/tablet/transaction_participant.cc (libtablet.so+0x314cf7)
    #3 yb::tablet::TransactionLoader::Executor::Execute()::'lambda'()::operator()() const /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/tablet/transaction_loader.cc:86:15 (libtablet.so+0x30c305)
    #4 yb::ScopeExitLambda<yb::tablet::TransactionLoader::Executor::Execute()::'lambda'()>::~ScopeExitLambda() /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/util/scope_exit.h:34:7 (libtablet.so+0x307fc8)
    #5 yb::tablet::TransactionLoader::Executor::Execute() /nfusr/centos-gcp-cloud/jenkins-worker-6z3dwe/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-466/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/tablet/transaction_loader.cc:93:3 (libtablet.so+0x306ae9)
    #6 decltype(*(std::__1::forward<yb::tablet::TransactionLoader::Executor*>(fp0)).*fp()) std::__1::__invoke<void (yb::tablet::TransactionLoader::Executor::*)(), yb::tablet::TransactionLoader::Executor*, void>(void (yb::tablet::TransactionLoader::Executor::*&&)(), yb::tablet::TransactionLoader::Executor*&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/libcxx/include/c++/v1/type_traits:4286:1 (libtablet.so+0x30c673)
    #7 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (yb::tablet::TransactionLoader::Executor::*)(), yb::tablet::TransactionLoader::Executor*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (yb::tablet::TransactionLoader::Executor::*)(), yb::tablet::TransactionLoader::Executor*>&, std::__1::__tuple_indices<2ul>) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/libcxx/include/c++/v1/thread:342 (libtablet.so+0x30c673)
    #8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (yb::tablet::TransactionLoader::Executor::*)(), yb::tablet::TransactionLoader::Executor*> >(void*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/libcxx/include/c++/v1/thread:352 (libtablet.so+0x30c673)
```
https://gist.github.com/def-/6a8da2db9c5e94aef9fa3c65cd0b16c7
Most of the stacks look like productive code, so I'm assuming this is a product issue, not just test.

**Comment by bmatican** [comment] 2022-10-06 01:18
Duplicate of #10735
Will fix that and backport.

**Closed by bmatican** 2022-10-06 01:18 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/medium
