### ISSUE TITLE
[DocDB] Delete Snapshot keeps on retrying indefinitely after master failover

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#16367] opened 2023-03-09 21:27 UTC
Jira Link: [DB-5784](https://yugabyte.atlassian.net/browse/DB-5784)
### Description

Observed this in the latest master. Steps to repro:
1. Create a database snapshot on a table (or multiple tables)
2. Split one of the tablets and wait for the parent tablet to be deleted
3. Perform a master leader failover - the new master will not have any state for this deleted parent tablet
4. Delete the snapshot created in (1). The snapshot rpc to delete the parent tablet will keep on retrying indefinitely since it won't find a leader for this tablet. The snapshot entry in syscatalog persists the list of tablets and after a split - parent tablet is deleted, so deleting the snapshot attempts to send rpcs to a non-existent tablet

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5784]: https://yugabyte.atlassian.net/browse/DB-5784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by datavisorzhizhu** [comment] 2023-05-21 09:45
Any fix for this？

**Comment by yamen-haddad** [comment] 2023-05-22 17:12
The issue is fixed with this [commit](https://github.com/yugabyte/yugabyte-db/commit/2ad4b721d29e88b80f6c4888df79ed5b7f24286b).
The ticket is still open is backporting the fix to stable releases is required.

**Comment by datavisorzhizhu** [comment] 2023-05-22 22:56
@yamen-haddad thanks for update.
if possible, could you list stable releases containing the fix and the time for them?

thanks again

**Comment by yamen-haddad** [comment] 2023-05-24 17:15
The fix is currently on master.
It will be backported to 2.18, 2.16, 2.14. This should happen within this week and the next week as the fix is waiting on the review of another fix.
I can comment again when the fix has been successfully backported.

**Comment by datavisorzhizhu** [comment] 2023-05-24 23:35
@yamen-haddad thanks. please comment here when backporting is done

**Comment by datavisorzhizhu** [comment] 2023-06-01 06:26
@yamen-haddad  docker image yugabytedb/yugabyte:2.14.10.0-b23 is generated two days ago, does it contain above fix?

**Comment by yamen-haddad** [comment] 2023-06-02 01:06
@datavisorzhizhu  The fix is waiting for review so it did not make it yet to 2.14.
I will update here once the fix is landed.

**Comment by yamen-haddad** [comment] 2023-06-02 20:29
@datavisorzhizhu The fix is now backported and will be in [2.18.1.0], [2.16.6.0], [2.19.0.0]. A backport to 2.14 is till in review.
Any specific reason you are interested in this fix specifically?

**Comment by datavisorzhizhu** [comment] 2023-06-02 22:17
@yamen-haddad  [2.16.6.0] is also acceptable to me. thanks

**Comment by rthallamko3** [comment] 2023-06-08 15:23
@yamen-haddad , Looks like this can be closed now?

**Comment by yamen-haddad** [comment] 2023-06-08 21:47
@datavisorzhizhu Just to let you know that the fix will be available in 2.14.11.0.

**Comment by yamen-haddad** [comment] 2023-06-08 21:47
@rthallamko3 Yes. Thanks.

**Closed by yamen-haddad** 2023-06-08 21:47 UTC
Labels: kind/bug, area/docdb, priority/medium, 2.14 Backport Required, 2.16 Backport Required, 2.18 Backport Required

**Comment by datavisorzhizhu** [comment] 2023-06-09 07:02
@yamen-haddad thanks for recent update
