### ISSUE TITLE
[Phase 2][colocation] Tserver should be able to handle duplicate AddTableToTablet rpc requests

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#3687] opened 2020-02-19 18:27 UTC
Jira Link: [DB-622](https://yugabyte.atlassian.net/browse/DB-622)
It seems like the TServer would DFATAL if the AddTableToTablet gets called twice. 

master -> TS rpc's retry based on a timeout, and given that 2 machines can have clocks at different speed, we should be able to handle duplicate rpc's at the receiver gracefully.

[DB-622]: https://yugabyte.atlassian.net/browse/DB-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by frozenspider** [comment] 2023-01-17 11:05
Confirmed that this still happens on a latest master- if you duplicate this block in `catalog_manager.cc`
```
  if (joining_colocation_group) {
    auto call =
        std::make_shared<AsyncAddTableToTablet>(master_, AsyncTaskPool(), tablets[0], table);
    table->AddTask(call);
    WARN_NOT_OK(ScheduleTask(call), "Failed to send AddTableToTablet request");
  }
  ```
  ...then tserver fails with
```
F0117 16:03:09.507750 1794109440 tablet_metadata.cc:1048] T 1a612f65d3e54592bdb5dfd453a793b8 P 4a7aa9d7bf074d8eb180186bdc1c8bc7: Table 00004004000030008000000000004005 already exists. New table info: table_id: "00004004000030008000000000004005" table_name: "whatever" table_type: PGSQL_TABLE_TYPE schema { columns { id: 10 name: "ybrowid" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: -100 pg_type_oid: 20 } columns { id: 11 name: "id" type { main: INT32 } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 1 pg_type_oid: 23 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false is_ysql_catalog_table: false retain_delete_markers: false partitioning_version: 1 } colocated_table_id { colocation_id: 3821714537 } pgschema_name: "public" } schema_version: 0 partition_schema { range_schema { columns { id: 10 } } } namespace_name: "" wal_retention_secs: 0 namespace_id: "", old table info: table_id: "00004004000030008000000000004005" table_name: "whatever" table_type: PGSQL_TABLE_TYPE schema { columns { id: 10 name: "ybrowid" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: -100 pg_type_oid: 20 } columns { id: 11 name: "id" type { main: INT32 } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 1 pg_type_oid: 23 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false is_ysql_catalog_table: false retain_delete_markers: false partitioning_version: 1 } colocated_table_id { colocation_id: 3821714537 } pgschema_name: "public" } schema_version: 0 partition_schema { range_schema { columns { id: 10 } } } namespace_name: "" wal_retention_secs: 0 namespace_id: ""
```

**Comment by druzac** [comment] 2023-02-15 15:23
Duplicate of #3681

**Closed** 2023-02-21 07:39 UTC
Labels: kind/bug, area/ysql, priority/medium
