### ISSUE TITLE
[YSQL] [Read Committed]: Query cancelling due to statement timeout issue

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18281] opened 2023-07-18 08:59 UTC
Jira Link: [DB-7277](https://yugabyte.atlassian.net/browse/DB-7277)
### Description

`testreadcommittedbasicfunctionality-aws-rf3` has started failing for recent builds of 2.14 and 2.16 with following error:
```
(   882.479s) Attempting Contentious transactions on read_committed_il_table table : >>> Integration Test Failed <<< 
canceling statement due to statement timeout
```
The test started failing from 2.14.11.0-b28 for 2.14 branch and is 100% reproducible.
Test/failure details: https://jenkins.dev.yugabyte.com/job/itest-system-developer/7398/

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7277]: https://yugabyte.atlassian.net/browse/DB-7277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Karvy-yb** [comment] 2023-07-20 06:16
On investigating the issue only seems to occur with multi-part primary keys.

**Comment by shishir2001-yb** [comment] 2023-07-27 07:53
Recently we have added multi-part PRIMARY KEY as part of the automation, the above test started failing just after that.

Also, in a ne read-committed test, I am seeing the above issue and it's on 2.19.1 
cc: @Karvy-yb

**Comment by pkj415** [comment] 2023-08-09 22:54
Root cause: This is happening because the retry logic for kReadRestart error in read committed isolation is partially incorrect right now (this doesn't break safety, but can lead to repeated read restart errors internally and hence indefinite amount of waiting until the write workload stops/ slows down).

To be precise, when a kReadRestart is seen by the query layer for read committed, it has to issue a retry with a `restarted` read point. However, due to a bug, the retry ends `resetting` the read point like any new read committed statement instead of `restarting` it. This is because after `tserver::ReadTimeManipulation::RESTART` is set for the read time manipulation in the next retry via `YBCPgRestartReadPoint()`, it is overwritten by `tserver::ReadTimeManipulation::RESET` via `YBCPgResetTransactionReadPoint()` in `GetTransactionSnapshot()` that is called for each new read committed statement attempt. And each time we reset the read point with current time, we face a read restart error again if there is ongoing write workload.

**Comment by shishir2001-yb** [comment] 2023-08-28 07:59
Can be reproduced in master

**Comment by pkj415** [comment] 2023-08-29 18:46
The latest repro had the same symptom of statement timeout but a different root cause, created #18896 to track that.

**Closed by pkj415** 2023-08-29 18:46 UTC
Labels: kind/bug, area/ysql, priority/high, QA, qa_automation
