### ISSUE TITLE
[YCQL] Yugabyte's Spark Cassandra Connector doesn't support JSONB column type.

### ISSUE THREAD

**Issue by abhinavswami** [yugabyte/yugabyte-db#3953] opened 2020-03-13 18:52 UTC
I am trying to read data from Yugabyte table (schema defined below), but the Yugabyte's spark connector driver is not able to recognize JSONB data type.

Yugabyte Driver Used:
```
<dependency>
       <groupId>com.yugabyte.spark</groupId>
       <artifactId>spark-cassandra-connector_2.11</artifactId>
       <version>2.0.5-yb-7</version>
</dependency>
```

Sample Schema:
```
CREATE TABLE keyspace.sample (
    id text PRIMARY KEY, 
    name text,
    address text,
    modified_at timeuuid,
    phone jsonb
);
```

StackTrace:
```
Exception in thread "main" java.util.NoSuchElementException: key not found: json
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.datastax.spark.connector.types.ColumnType$$anonfun$1.applyOrElse(ColumnType.scala:119)
	at com.datastax.spark.connector.types.ColumnType$$anonfun$1.applyOrElse(ColumnType.scala:113)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at com.datastax.spark.connector.types.ColumnType$.fromDriverType(ColumnType.scala:124)
	at com.datastax.spark.connector.cql.ColumnDef$.apply(Schema.scala:130)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchRegularColumns$1.apply(Schema.scala:262)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchRegularColumns$1.apply(Schema.scala:258)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchRegularColumns(Schema.scala:258)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchTables$1$2.apply(Schema.scala:293)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchTables$1$2.apply(Schema.scala:289)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:200)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchTables$1(Schema.scala:289)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1$2.apply(Schema.scala:313)
	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1$2.apply(Schema.scala:312)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1(Schema.scala:312)
	at com.datastax.spark.connector.cql.Schema$$anonfun$fromCassandra$1.apply(Schema.scala:333)
	at com.datastax.spark.connector.cql.Schema$$anonfun$fromCassandra$1.apply(Schema.scala:330)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withClusterDo$1.apply(CassandraConnector.scala:123)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withClusterDo$1.apply(CassandraConnector.scala:122)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:112)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:111)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:122)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:330)
	at com.datastax.spark.connector.cql.Schema$.tableFromCassandra(Schema.scala:350)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation.<init>(CassandraSourceRelation.scala:46)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:287)
	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
	at migrate.ReadFromYuga$.main(ReadFromYuga.scala:25)
	at migrate.ReadFromYuga.main(ReadFromYuga.scala)
```
CC: @ameyb , @m-iancu

**Comment by m-iancu** [comment] 2020-04-22 18:02
This is now fixed in the [latest version of the Spark connector](https://search.maven.org/search?q=g:com.yugabyte.spark%20AND%20a:spark-cassandra-connector_2.11).

For Maven the following `pom.xml` entry should work:
```
<dependency>
  <groupId>com.yugabyte.spark</groupId>
  <artifactId>spark-cassandra-connector_2.11</artifactId>
  <version>2.4-yb-2</version>
</dependency>
```

**Comment by atulsinghrajpoot** [comment] 2020-12-01 11:56
Hi Tried use both below version

**Comment by atulsinghrajpoot** [comment] 2020-12-01 12:10
Hi, Tried with the below Yugabyte connector :

`<dependency>
  <groupId>com.yugabyte.spark</groupId>
  <artifactId>spark-cassandra-connector_2.11</artifactId>
  <version>2.4-yb-2</version>
</dependency>`

also tried with

`<dependency>
  <groupId>com.yugabyte.spark</groupId>
  <artifactId>spark-cassandra-connector_2.11</artifactId>
  <version>2.4-yb-3</version>
</dependency>`

Getting below StackTrace:

`java.util.NoSuchElementException: key not found: JsonType
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.apache.spark.sql.cassandra.DataTypeConverter$.primitiveCatalystDataType(DataTypeConverter.scala:64)
	at org.apache.spark.sql.cassandra.DataTypeConverter$.catalystDataType(DataTypeConverter.scala:58)
	at org.apache.spark.sql.cassandra.DataTypeConverter$.toStructField(DataTypeConverter.scala:75)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1$$anonfun$apply$1.apply(CassandraSourceRelation.scala:56)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1$$anonfun$apply$1.apply(CassandraSourceRelation.scala:56)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1.apply(CassandraSourceRelation.scala:56)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1.apply(CassandraSourceRelation.scala:56)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation.schema(CassandraSourceRelation.scala:56)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
	at com.asr.sample.App.test2(App.java:79)
	at com.asr.sample.App.main(App.java:24)`

**Comment by atulsinghrajpoot** [comment] 2020-12-01 12:13
> I am trying to read data from Yugabyte table (schema defined below), but the Yugabyte's spark connector driver is not able to recognize JSONB data type.
> 
> Yugabyte Driver Used:
> 
> ```
> <dependency>
>        <groupId>com.yugabyte.spark</groupId>
>        <artifactId>spark-cassandra-connector_2.11</artifactId>
>        <version>2.0.5-yb-7</version>
> </dependency>
> ```
> 
> Sample Schema:
> 
> ```
> CREATE TABLE keyspace.sample (
>     id text PRIMARY KEY, 
>     name text,
>     address text,
>     modified_at timeuuid,
>     phone jsonb
> );
> ```
> 
> StackTrace:
> 
> ```
> Exception in thread "main" java.util.NoSuchElementException: key not found: json
> 	at scala.collection.MapLike$class.default(MapLike.scala:228)
> 	at scala.collection.AbstractMap.default(Map.scala:59)
> 	at scala.collection.MapLike$class.apply(MapLike.scala:141)
> 	at scala.collection.AbstractMap.apply(Map.scala:59)
> 	at com.datastax.spark.connector.types.ColumnType$$anonfun$1.applyOrElse(ColumnType.scala:119)
> 	at com.datastax.spark.connector.types.ColumnType$$anonfun$1.applyOrElse(ColumnType.scala:113)
> 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
> 	at com.datastax.spark.connector.types.ColumnType$.fromDriverType(ColumnType.scala:124)
> 	at com.datastax.spark.connector.cql.ColumnDef$.apply(Schema.scala:130)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchRegularColumns$1.apply(Schema.scala:262)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchRegularColumns$1.apply(Schema.scala:258)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchRegularColumns(Schema.scala:258)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchTables$1$2.apply(Schema.scala:293)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchTables$1$2.apply(Schema.scala:289)
> 	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
> 	at scala.collection.immutable.Set$Set4.foreach(Set.scala:200)
> 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
> 	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchTables$1(Schema.scala:289)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1$2.apply(Schema.scala:313)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1$2.apply(Schema.scala:312)
> 	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
> 	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
> 	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
> 	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
> 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
> 	at com.datastax.spark.connector.cql.Schema$.com$datastax$spark$connector$cql$Schema$$fetchKeyspaces$1(Schema.scala:312)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$fromCassandra$1.apply(Schema.scala:333)
> 	at com.datastax.spark.connector.cql.Schema$$anonfun$fromCassandra$1.apply(Schema.scala:330)
> 	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withClusterDo$1.apply(CassandraConnector.scala:123)
> 	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withClusterDo$1.apply(CassandraConnector.scala:122)
> 	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:112)
> 	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:111)
> 	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145)
> 	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
> 	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:122)
> 	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:330)
> 	at com.datastax.spark.connector.cql.Schema$.tableFromCassandra(Schema.scala:350)
> 	at org.apache.spark.sql.cassandra.CassandraSourceRelation.<init>(CassandraSourceRelation.scala:46)
> 	at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:287)
> 	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:307)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
> 	at migrate.ReadFromYuga$.main(ReadFromYuga.scala:25)
> 	at migrate.ReadFromYuga.main(ReadFromYuga.scala)
> ```
> 
> CC: @ameyb , @m-iancu

Sorry if I'm doing some thing, please suggest if this has been already fixed

Thanks in advance

**Comment by tedyu** [comment] 2020-12-01 17:07
It seems the driver you're using didn't have this:
```
commit c0456f23b23d40c901911211d27b5cd5fe854421
Author: Mihnea Iancu <m-iancu@users.noreply.github.com>
Date:   Mon Apr 20 21:51:56 2020 -0700

    Support YCQL's JSONB column type yugabyte/yugabyte-db#3953
```
Do you mind upgrading to the latest connector ?

java/pom.xml:    <spark-cassandra-connector.version>2.4-yb-3</spark-cassandra-connector.version>

**Comment by atulsinghrajpoot** [comment] 2020-12-02 11:44
Thanks, @tedyu  for your response

**Comment by m-iancu** [comment] 2020-12-02 19:21
Hi @atulsinghrajpoot, the `2.4-yb-3` driver does indeed support JSONB but it needs the corresponding (Y)CQL driver with JSONB support to be used in the project.

Spark should include that driver itself, but if you are also including a vanilla Cassandra driver from another source it may override it and cause this issue.

A simple way to debug is to run `mvn dependency:tree` in your project root and confirm that the correct version of the cassandra-driver-core is included.
Specifically, for Spark `2.4-yb-3` it should be
```
com.yugabyte:cassandra-driver-core:jar:3.2.0-yb-19
```
If instead (or in addition) you see the vanilla driver (e.g. the datastax one) that might override the classes and cause the json error because the vanilla drivers will not support our json type.

**Comment by atulsinghrajpoot** [comment] 2020-12-04 11:56
Hi @m-iancu,

Thanks for the update 

Verified everything is same as you suggested but getting the same issue, for your reference attached sample project that I'm using for testing 
[yugabyte-spark-connector-sample.zip](https://github.com/yugabyte/yugabyte-db/files/5642527/yugabyte-spark-connector-sample.zip)

Please let me know if I'm doing something wrong

Yugabyte Driver Used:
```
<dependency>
<groupId>com.yugabyte</groupId>
<artifactId>cassandra-driver-core</artifactId>
<version>3.2.0-yb-19</version>
</dependency>

```
Yugabyte Connector Used:
```
<dependency>
<groupId>com.yugabyte.spark</groupId>
<artifactId>spark-cassandra-connector_2.11</artifactId>
<version>2.4-yb-3</version>
</dependency>

```
Stacktrace:
```
20/12/04 17:00:51 ERROR App: Error in reading data: scala.collection.MapLike$class.default(MapLike.scala:228)
java.util.NoSuchElementException: key not found: JsonType
at scala.collection.MapLike$class.default(MapLike.scala:228)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.MapLike$class.apply(MapLike.scala:141)
at scala.collection.AbstractMap.apply(Map.scala:59)
at org.apache.spark.sql.cassandra.DataTypeConverter$.primitiveCatalystDataType(DataTypeConverter.scala:64)
at org.apache.spark.sql.cassandra.DataTypeConverter$.catalystDataType(DataTypeConverter.scala:58)
at org.apache.spark.sql.cassandra.DataTypeConverter$.toStructField(DataTypeConverter.scala:75)
at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1$$anonfun$apply$1.apply(CassandraSourceRelation.scala:56)
at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1$$anonfun$apply$1.apply(CassandraSourceRelation.scala:56)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.Iterator$class.foreach(Iterator.scala:891)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1.apply(CassandraSourceRelation.scala:56)
at org.apache.spark.sql.cassandra.CassandraSourceRelation$$anonfun$schema$1.apply(CassandraSourceRelation.scala:56)
at scala.Option.getOrElse(Option.scala:121)
at org.apache.spark.sql.cassandra.CassandraSourceRelation.schema(CassandraSourceRelation.scala:56)
at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
at com.asr.sample.App.run(App.java:40)
at com.asr.sample.App.main(App.java:19)
```

**Comment by tedyu** [comment] 2020-12-04 17:48
From the stack trace, it seems primitiveTypeMap in spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DataTypeConverter.scala was queried for JsonType.
However, there is no entry mapping JsonType to catalystType. Hence the NoSuchElementException.

**Comment by tedyu** [comment] 2020-12-04 19:57
I have verified Mihnea's change by running the above sample app locally.
```
+---+----------------------+-----+---------------------------+
|id |address               |name |phone                      |
+---+----------------------+-----+---------------------------+
|1  |Hammersmith London, UK|John |{"code":"+44","phone":1000}|
|2  |Acton London, UK      |Nick |{"code":"+44","phone":1200}|
|3  |11 Acton London, UK   |Smith|{"code":"+44","phone":1400}|
+---+----------------------+-----+---------------------------+
```
2.4-yb-4 release with the fix would appear in mvn central later.

**Comment by tedyu** [comment] 2020-12-05 05:20
2.4-yb-4 has shown up in mvn central.

You can try it to see if your app works.

**Comment by m-iancu** [comment] 2020-12-07 22:48
@atulsinghrajpoot Let us know if the new driver version (`2.4-yb-4`) works. 
Both @tedyu and I have tested the app you shared above locally and confirmed it works for us.

**Comment by atulsinghrajpoot** [comment] 2020-12-18 08:43
Hi, 

Thanks for the update, I have tested with the updated driver
This fix is working only to read complete Json column as string but not specific keys. As per requirement from this feature (suggested solution in YB document https://docs.yugabyte.com/latest/explore/json-support/jsonb-ycql/#using-and), 
requirement is to read only specific keys from Json column, i.e, even if Json column contains ~1K keys, Spark SQL should be able to read only specific select keys for its processing, example need similar support to below queries:
```

SELECT id, details->>'name' as book_title, details->>'description' as book_description FROM store.books;
SELECT * FROM store.books WHERE details->'author'->>'first_name' = 'William';

```
I tried the below option its working, but only problem with the solution is(this is my assumption)this will load all selected data in spark's driver memory which my cause memory issue

```
val select_with_jsonb_columns = """
SELECT id, details->>'name', details->>'description'
FROM store.books
WHERE id = <your value>
"""
val rows_with_jsonb_columns = session.execute(select_with_jsonb_columns).all
```

**Comment by tedyu** [comment] 2020-12-18 17:25
@atulsinghrajpoot 
Since you confirmed the above formation works for you, can this issue be closed ?

**Comment by atulsinghrajpoot** [comment] 2020-12-21 07:51
Thank you @tedyu, Yes this can be closed
To read only specific keys from Json column,  I'll request on another thread

**Closed** 2020-12-21 08:45 UTC
Labels: community/request

**Comment by m-iancu** [comment] 2020-12-23 04:18
@atulsinghrajpoot Just fyi, I opened https://github.com/yugabyte/yugabyte-db/issues/6738 to track the follow-up issue about `->` and `->>` operators.

**Comment by atulsinghrajpoot** [comment] 2020-12-30 15:31
Hi @m-iancu,  Thanks for adding me in the loop
