### ISSUE TITLE
[DocDB][Read Committed] Transaction Aborted: Deadlock with 'Cached Table Partition List Version Obsolete, Refresh Required'

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20014] opened 2023-11-22 17:53 UTC
Jira Link: [DB-8981](https://yugabyte.atlassian.net/browse/DB-8981)
### Description

Tried on version: **2.21.0.0-b238**

While running a Read Committed + Geo-partition + Wait on conflict test, one of the transactions got aborted with the following error. The deadlock part of the error is expected, but should the second part of the error message (`...failed: Cached table partition list version is obsolete, refresh required......`) shown to the user?

`
DETAIL:  Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Operation expired (yb/docdb/deadlock_detector.cc:636): Transaction 9dc3ecb5-d6af-4c9a-be3f-a5b1a9e77ed8 aborted due to a deadlock.
9dc3ecb5-d6af-4c9a-be3f-a5b1a9e77ed8 -> e43f273c-4def-4ed3-8fd9-298c72e207d8 -> 9dc3ecb5-d6af-4c9a-be3f-a5b1a9e77ed8 : kDeadlock (transaction error 6), Operation failed. Try again (yb/client/meta_cache.cc:1584): GetTableLocations { table_name: test_read_committed_db_1.transactions_db_1_3_name_age_created_at_geo_partition_idx, table_id: 000040000000300080000000000041d8, partition_start_key: string name=, int32 age=-2147483648, int64 created_at=-9223372036854775808, string geo_partition=, binary ybuniqueidxkeysuffix=, partition_list_version: 28, request_no: 390, num_attempts: 1 } failed: Cached table partition list version is obsolete, refresh required. RPC: GetTableLocations { table_name: test_read_committed_db_1.transactions_db_1_3_name_age_created_at_geo_partition_idx, table_id: 000040000000300080000000000041d8, partition_start_key: string name=, int32 age=-2147483648, int64 created_at=-9223372036854775808, string geo_partition=, binary ybuniqueidxkeysuffix=, partition_list_version: 28, request_no: 390, num_attempts: 1 }, response partition_list_version: 30: kTablePartitionListIsStale (client error 1)]
`
**Note**: Aggressive Tablet Splitting is enabled

Test details:
```
- Create a cluster with required g-flags
- Create 2 database
- Create both colocated and non-colocated tables
- Create all types of indexes
- Start a thread which will execute flush and compaction on all the tables
    after every 5 mins.
- Start 8 threads and perform the following operation for 40 mins
                (There maybe some conflicts in DMLs)
                a. Insert 10 rows in all the tables
                b. Add a savepoint S1
                c. Update 1 row in all the tables
                d. Add a savepoint S2
                e. Select 1 row(FOR (UPDATE, SHARE, NO KEY UPDATE, KEY SHARE, "")) in all the tables
                f. Add a savepoint S3
                g. Delete some rows in all the tables
                h. Add a savepoint S4
                i. Rollback to any savepoint
                j. Increase age column of a constant PK
                k. Commit both the transaction
```

G-flags
```
t_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_num_shards_per_tserver": 1,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "scheduled_full_compaction_frequency_hours": "12",
                "scheduled_full_compaction_jitter_factor_percentage": "100",
                "scheduled_full_compaction_check_interval_min": "5",
                "yb_enable_read_committed_isolation": "true",
                "consistent_restore": "true"
            })
            m_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "yb_enable_read_committed_isolation": "true",
                "enable_automatic_tablet_splitting": "true",
                "tablet_split_high_phase_shard_count_per_node": 200,
                "tablet_split_low_phase_shard_count_per_node": 16,
                # high_phase_size 2MB
                "tablet_split_high_phase_size_threshold_bytes": 2097152,
                # low_phase_size 100KB
                "tablet_split_low_phase_size_threshold_bytes": 102400,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "consistent_restore": "true"
            })
```
[Logs https://drive.google.com/file/d/19YZgpY3GIA5FS0Ui_1syWcP2uxFRTTLT/view?usp=sharing](https://drive.google.com/file/d/19YZgpY3GIA5FS0Ui_1syWcP2uxFRTTLT/view?usp=sharing)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8981]: https://yugabyte.atlassian.net/browse/DB-8981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment] 2023-11-27 17:10
in such a case, we should *only* report the deadlock error, since the retryable error would usually be transparent to the user but the query layer cannot retry due to the deadlock error

closing as dupe of https://github.com/yugabyte/yugabyte-db/issues/18611

**Closed by robertsami** 2023-11-27 17:10 UTC
Labels: kind/bug, area/docdb, priority/medium, QA, qa_automation
