### ISSUE TITLE
[Docs] DROP INDEX missing in documentation and SQL feature support

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#14483] opened 2022-10-15 16:15 UTC
### Description

The [doc](https://docs.yugabyte.com/preview/explore/ysql-language-features/sql-feature-support/#schema-operations) says:
| Operation | Supported | Documentation |
| :-------- | :-------: | :------------ |
| Removing indexes | ✗ | |

However, DROP INDEX is supported. 
```
yugabyte=# CREATE TABLE t (c int);
CREATE TABLE
yugabyte=# CREATE INDEX i on t (c);
CREATE INDEX
yugabyte=# DROP INDEX i;
DROP INDEX
yugabyte=#
```
But I also can't find it in the YSQL documentation

**Comment by ddorian** [comment] 2023-05-10 11:34
The table has already been updated.

Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/9951

**Closed by ddorian** 2023-05-10 11:34 UTC
Labels: area/documentation, status/awaiting-triage, temp/docs-migration
