### ISSUE TITLE
[Docs] Missing icons In backup and restore docs page

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#7285] opened 2021-02-18 16:17 UTC
![Screenshot 2021-02-18 at 8 15 25 AM](https://user-images.githubusercontent.com/12711838/108386534-59499f00-71d2-11eb-8777-244ce0e2bac4.png)

Added a screenshot above. Also, note that the webpage had fully loaded, and I am using Chrome.

**Comment by polarweasel** [comment] 2021-02-18 21:57
What's the URL of the page you're looking at? Want to make sure we're looking at the same thing.

**Comment by pkj415** [comment] 2021-02-18 21:59
https://docs.yugabyte.com/latest/manage/backup-restore/

**Comment by polarweasel** [comment] 2021-02-18 22:07
@pkj415 and I have both confirmed it's working now. The missing icon was likely a cache issue on Netlify's end due to their outage this morning.

Closing for now, but please continue to report stuff like this!

**Closed** 2021-02-18 22:07 UTC
