### ISSUE TITLE
[YSQL] Minor Pg compatibility difference when conflict occurs twice for one row using ON CONFLICT DO UPDATE 

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#16372] opened 2023-03-09 23:35 UTC
Jira Link: [DB-5789](https://yugabyte.atlassian.net/browse/DB-5789)
### Description

The following difference between PG and YB appears to be intended:

PG:
```
postgres=# \i selfconflict.sql 
create table selfconflict (f1 int primary key, f2 int);
CREATE TABLE
insert into selfconflict values (4,1), (4,2) on conflict(f1) do update set f2 = 0;
psql:selfconflict.sql:2: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
select * from selfconflict;
 f1 | f2 
----+----
(0 rows)
```

YB:
```
yugabyte=# \i selfconflict.sql 
create table selfconflict (f1 int primary key, f2 int);
CREATE TABLE
insert into selfconflict values (4,1), (4,2) on conflict(f1) do update set f2 = 0;
INSERT 0 2
select * from selfconflict;
 f1 | f2 
----+----
  4 |  0
(1 row)
```

Thanks to @myang2021 for catching this!

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5789]: https://yugabyte.atlassian.net/browse/DB-5789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SteveXiSong** [comment] 2023-05-11 23:27
Thanks for confirming the PG/YB imparity. This can be fixed along with the `INSERT ON CONFLICT` project(#4275).

**Comment by SteveXiSong** [comment] 2023-05-24 23:26
Original PG code uses a "buffer" for read rows during conflict check to determine the "multiple row update in one insert statement" issue. For us, we don't have such a buffer and were intentionally bypassing such PG code as of today due to loading the row by row and managing txn remotely. 

With "Batched Inserts", we will introduce an insertion buffer, which might be used the similar functionality as the "buffer" in PG to do check "multiple modified row" check, which achieves the PG parity. But this will need some more study on how the "buffer" works and implement a similar mechanism in the "insertion buffer". However, considering the original PG's code was related to txn visibility, we had to carefully evaluate it and I don't have 100% confidence to solve it with such a new implementation.

**Comment by jasonyb** [comment] 2024-08-06 22:51
marking as duplicate of more detailed #18895

**Closed by jasonyb** 2024-08-06 22:51 UTC
Labels: kind/bug, area/ysql, priority/medium
