### ISSUE TITLE
[DocDB] flaky test failures "Namespace Create Failed"

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#18593] opened 2023-08-07 22:36 UTC
Jira Link: [DB-7524](https://yugabyte.atlassian.net/browse/DB-7524)
### Description

centos-clang16-debug these days has flaky failures with the following error message:

```
Bad status: Network error (yb/yql/pgwrapper/libpq_utils.cc:337): Execute of 'CREATE DATABASE my_keyspace WITH COLOCATION=TRUE' failed: 7, message: ERROR:  Namespace Create Failed: The namespace is in process of deletion due to internal error. (pgsql error XX000) (aux msg ERROR:  Namespace Create Failed: The namespace is in process of deletion due to internal error.)
```

It only seems to be that build type, from what I've seen in the last 4-5 test runs on master.  On a feature branch test run (https://detective-gcp.dev.yugabyte.com/D27551/), it failed a lot with that error (again, all on centos-clang16-debug):

```
CDCSDKStreamTest.CreateMultipleStreams
CDCSDKYsqlTest.TestArrayCompositeType
CDCSDKYsqlTest.TestCDCSDKAddColumnsWithImplictTransactionWithPackedRow
CDCSDKYsqlTest.TestCDCSDKDropColumnsWithExplictTransactionWithOutPackedRow
CDCSDKYsqlTest.TestCDCSDKTrafficSentMetric
CDCSDKYsqlTest.TestCDCStateTableAfterTabletSplit
CDCSDKYsqlTest.TestCleanupSingleStreamMultiTserver
CDCSDKYsqlTest.TestEnableTruncateTable
CDCSDKYsqlTest.TestExpiredStreamWithCompaction
CDCSDKYsqlTest.TestGetChangesReportsTabletSplitErrorOnRetries
CDCSDKYsqlTest.TestLoadInsertionOnly
CDCSDKYsqlTest.TestNeedSchemaInfoFlag
CDCSDKYsqlTest.TestSingleMultiShardUpdateBeforeImage
CDCSDKYsqlTest.TestTabletSplitOnAddedTableForCDC
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlDropCheckConstraint/1
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceUndoDropSequence/0
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceUndoInsertedData/0
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequencePartialCleanupAfterRestore/2
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceVerifyPartialRestore/1
Colocation/YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSetDefault/0
XClusterYSqlTestConsistentTransactionsTest.LargeTransaction
XClusterYSqlTestConsistentTransactionsTest.RestartServer
XClusterYsqlTest.TablegroupReplicationMismatch
XClusterYsqlTest.XClusterWithCDCSDKExplictTranPackedRows
YbAdminSnapshotScheduleTest.PgsqlAddColumnCompactWithPackedRow
YbAdminSnapshotScheduleTest.PgsqlPreventTablespaceDrop
YbAdminSnapshotScheduleTest.ReadsAfterRestoreWithSplit
YbAdminSnapshotScheduleTest.SysCatalogRetention
org.yb.pgsql.TestPgAuthorization.testGrantAttributesMidSession
org.yb.pgsql.TestPgYbStat.testYBDBFiltering
org.yb.pgsql.TestYbBackup.testLegacyColocatedMateralizedViewBackup
org.yb.pgsql.TestYbBackup.testOnlyColocatedMateralizedViewBackup
org.yb.pgsql.TestYsqlUpgrade.migrationInGeoPartitionedSetup
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7524]: https://yugabyte.atlassian.net/browse/DB-7524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment] 2023-08-08 01:45
Some potentially relevant snippets of logs:
```
[ts-1] I0805 00:47:58.478492 24177 transaction_coordinator.cc:1690] T {transactions_tablet_id3} P {ts1_peer_id}: Request to unknown transaction ec99c549-5666-46fa-9318-4312e49d0dbf: transaction_id: "EC99C549566646FA93184312E49D0DBF" status: PENDING host_node_uuid: "{ts1_peer_id}"
[ts-1] I0805 00:47:58.478698 23960 transaction_coordinator.cc:1690] T {transactions_tablet_id3} P {ts1_peer_id}: Request to unknown transaction 5e1bd65d-02aa-4b1d-9896-080fc6e6a5e1: transaction_id: "5E1BD65D02AA4B1D9896080FC6E6A5E1" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691196471797718 host_node_uuid: "{ts1_peer_id}"
[ts-1] I0805 00:47:58.480011 24177 tablet_rpc.cc:462] Operation expired (yb/tablet/transaction_coordinator.cc:1695): Failed UpdateTransaction: tablet_id: "{transactions_tablet_id3}" state { transaction_id: "\354\231\305IVfF\372\223\030C\022\344\235\r\277" status: PENDING host_node_uuid: "{ts1_peer_id}" } propagated_hybrid_time: 6927140775846195200, retrier: { task_id: -1 state: kIdle deadline: 12358.199s } to tablet {transactions_tablet_id3} on tablet server { uuid: {ts1_peer_id} private: [host: "127.0.0.2" port: 29284] public: [host: "127.0.0.3.ip.yugabyte" port: 29284] cloud_info: placement_cloud: "cloud1" placement_region: "rack1" placement_zone: "zone" after 1 attempt(s): Transaction ec99c549-5666-46fa-9318-4312e49d0dbf expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)
[ts-1] W0805 00:47:58.480038 24102 transaction.cc:1832] 5e1bd65d-02aa-4b1d-9896-080fc6e6a5e1 [Session 1]: Send heartbeat failed: Operation expired (yb/tablet/transaction_coordinator.cc:1695): Transaction 5e1bd65d-02aa-4b1d-9896-080fc6e6a5e1 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1), txn state: kRunning
[ts-1] W0805 00:47:58.480122 24177 transaction.cc:1832] ec99c549-5666-46fa-9318-4312e49d0dbf: Send heartbeat failed: Operation expired (yb/tablet/transaction_coordinator.cc:1695): Transaction ec99c549-5666-46fa-9318-4312e49d0dbf expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1), txn state: kRunning
```
From another test:

```
[ts-2] W0805 00:49:04.784281 30715 transaction.cc:1832] 740e094b-d3be-4520-ba74-b161ac50317d [Session 1]: Send heartbeat failed: Timed out (yb/rpc/rpc.cc:220): UpdateTransaction: tablet_id: "{transactions_tablet_id2}" state { transaction_id: "t\016\tK\323\276E \272t\261a\254P1}" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691196535217293 host_node_uuid: "{ts2_peer_id}" } propagated_hybrid_time: 6927141014465720320, retrier: { task_id: -1 state: kRunning deadline: 3696.391s } passed its deadline 3696.391s (passed: 8.048s): Aborted (yb/consensus/replica_state.cc:632): Operation aborted by new leader, txn state: kRunning
```

**Comment by druzac** [comment] 2023-08-08 19:36
The error message was introduced in 5061fc04e1f0f0b497ad143ed352726bac9f18a5. I think that message is a red herring. The only prod change in that diff is `IsCreateNamespaceDone` returns an error if the status of the namespace is `DELETING` or `DELETED`. Formerly that RPC would return `OK`. The namespace creation logic in the pg session client is:
1. Issue `CreateNamespaceRPC` to `CatalogManager`
2. Loop issuing `IsCreateNamespaceDoneRPC` to `CatalogManager` until response indicates creation is complete

Before 5061fc04e1f0f0b497ad143ed352726bac9f18a5 in the case of a transaction failure, the `PgSessionClient` would complete these steps successfully. As the namespace is deleted, though, the test would presumably still fail with a different error message when it later tried to use the newly created database, unless there's more robust retry logic for using a namespace than for creating a namespace.

There's two things we could do here:
1. Retry namespace creation in tests
2. Change the text of this error message so it doesn't suggest an error to be investigated and instead a transient issue a retry should solve

Logs for an example test failure:
```
XClusterYsqlTest.SetupUniverseReplicationWithYbAdmin:

[P-ts-3] W0807 21:19:53.586506 19054 transaction.cc:1832] 813c293d-77df-47c4-baca-bb98f131a5a2 [Session 1]: Send heartbeat failed: Timed out (yb/rpc/rpc.cc:220): UpdateTransaction: tablet_id: "{transactions_tablet_id2}" state { transaction_id: "\201<)=w\337G\304\272\312\273\230\3611\245\242" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691443187071463 host_node_uuid: "{Pts3_peer_id}" } propagated_hybrid_time: 6928151302604664832, retrier: { task_id: -1 state: kRunning deadline: 1050.804s } passed its deadline 1050.804s (passed: 4.474s): Aborted (yb/consensus/replica_state.cc:632): Operation aborted by new leader, txn state: kRunning
[P-ts-3] W0807 21:19:54.097175 19056 transaction.cc:1832] 813c293d-77df-47c4-baca-bb98f131a5a2 [Session 1]: Send heartbeat failed: Timed out (yb/rpc/rpc.cc:220): UpdateTransaction: tablet_id: "{transactions_tablet_id2}" state { transaction_id: "\201<)=w\337G\304\272\312\273\230\3611\245\242" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691443187071463 host_node_uuid: "{Pts3_peer_id}" } propagated_hybrid_time: 6928151320930476032, retrier: { task_id: -1 state: kRunning deadline: 1055.278s } passed its deadline 1055.278s (passed: 0.510s): Leader not ready to serve requests (yb/consensus/consensus.cc:165): Leader not yet replicated NoOp to be ready to serve requests (tablet server error 24), txn state: kRunning
[P-ts-3] I0807 21:19:54.107748 19074 transaction_coordinator.cc:1690] T {transactions_tablet_id2} P {Pts3_peer_id}: Request to unknown transaction 813c293d-77df-47c4-baca-bb98f131a5a2: transaction_id: "813C293D77DF47C4BACABB98F131A5A2" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691443187071463 host_node_uuid: "{Pts3_peer_id}"
[P-ts-3] I0807 21:19:54.108039 19074 tablet_rpc.cc:462] Operation expired (yb/tablet/transaction_coordinator.cc:1695): Failed UpdateTransaction: tablet_id: "{transactions_tablet_id2}" state { transaction_id: "\201<)=w\337G\304\272\312\273\230\3611\245\242" status: PENDING tablets: "{sys_catalog_tablet_id}" start_time: 1691443187071463 host_node_uuid: "{Pts3_peer_id}" } propagated_hybrid_time: 6928151323022209024, retrier: { task_id: -1 state: kIdle deadline: 1055.788s } to tablet {transactions_tablet_id2} on tablet server { uuid: {Pts3_peer_id} private: [host: "127.0.0.6" port: 21954] public: [host: "127.0.0.7.ip.yugabyte" port: 21954] cloud_info: placement_cloud: "cloud2" placement_region: "rack3" placement_zone: "zone" after 2 attempt(s): Transaction 813c293d-77df-47c4-baca-bb98f131a5a2 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1)
[P-ts-3] W0807 21:19:54.108119 19074 transaction.cc:1832] 813c293d-77df-47c4-baca-bb98f131a5a2 [Session 1]: Send heartbeat failed: Operation expired (yb/tablet/transaction_coordinator.cc:1695): Transaction 813c293d-77df-47c4-baca-bb98f131a5a2 expired or aborted by a conflict: 40001 (pgsql error 40001) (transaction error 1), txn state: kRunning

[P-m-1] I0807 21:20:04.566174 19593 ysql_transaction_ddl.cc:181] Verifying Transaction { transaction_id: 813c293d-77df-47c4-baca-bb98f131a5a2 isolation: SNAPSHOT_ISOLATION status_tablet: {transactions_tablet_id2} priority: 11808486933278955252 start_time: { days: 19576 time: 21:19:47.071456 } locality: GLOBAL old_status_tablet: }
[P-m-1] I0807 21:20:04.577085 18903 ysql_transaction_ddl.cc:251] Got Response for { transaction_id: 813c293d-77df-47c4-baca-bb98f131a5a2 isolation: SNAPSHOT_ISOLATION status_tablet: {transactions_tablet_id2} priority: 11808486933278955252 start_time: { days: 19576 time: 21:19:47.071456 } locality: GLOBAL old_status_tablet: }, resp: status: ABORTED status_hybrid_time: 18446744073709551615 propagated_hybrid_time: 6928151365946089472 coordinator_safe_time: 6928151365945614336 aborted_subtxn_set { } deadlock_reason { code: OK source_file: "" }
[P-m-1] I0807 21:20:04.577898 19475 catalog_manager.cc:8793] Namespace transaction failed, deleting: test_namespace [id=00004000000030008000000000000000]
```

**Comment by druzac** [comment] 2023-08-08 19:57
Assigning to @deeps1991 to confirm the transactional DDL code is working as intended.

**Comment by druzac** [comment] 2023-09-13 15:03
We're no longer seeing these failures. It was most likely a test infrastructure problem.

**Closed by druzac** 2023-09-13 15:03 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/high
