### ISSUE TITLE
[YSQL] Avoid creating useless docdb table for partitioned relations

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#17278] opened 2023-05-11 01:35 UTC
Jira Link: [DB-6508](https://yugabyte.atlassian.net/browse/DB-6508)
### Description

Partitioned tables are not expected to have storage because it is the underlying partitions that have storage.  However, I notice docdb tables are created for partitioned tables and indexes, even if data cannot be written to them.  Such tables/tablets are wasteful when they are unusable, so this should be avoided.

The following is just proving that partitioned tables have no data.

```sh
bin/yb-ctl create --tserver_flags ysql_enable_packed_row=false # packed rows + sst_dump is currently buggy
```

```sql
CREATE TABLE part (i int, UNIQUE (i)) PARTITION BY RANGE (i);
CREATE TABLE part10 PARTITION OF part FOR VALUES FROM (0) to (10);
INSERT INTO part VALUES (5);
```

```sh
for tab in part part_i_key; do
  build/latest/bin/yb-admin flush_table ysql.yugabyte $tab
  build/latest/bin/yb-admin list_tablets ysql.yugabyte $tab | tail -n +2 | awk '{print $1}' | while read -r line; do build/latest/bin/sst_dump --command=scan --output_format=decoded_regulardb --file=~/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-$(build/latest/bin/yb-admin list_tables include_table_id | grep yugabyte.$tab\  | awk '{print$2}')/tablet-$line/; done
done
```

```
Flushed [yugabyte.part] tables.
from [] to []
from [] to []
from [] to []
Flushed [yugabyte.part_i_key] tables.
from [] to []
from [] to []
from [] to []
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6508]: https://yugabyte.atlassian.net/browse/DB-6508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by deeps1991** [comment] 2023-05-11 01:40
Duplicate of #6525

**Closed by deeps1991** 2023-05-11 01:40 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
