### ISSUE TITLE
[xCluster] Investingate setup_universe_replication Performance for many Tables

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10975] opened 2022-01-03 22:12 UTC
### Description

Currently, users are recommended to setup tables ~10 at a time to prevent overloading the cluster. We need to investigate what exactly is hogging resources (possibly RPCs to the master) so we can setup all tables at once.

**Comment by bmatican** [comment] 2022-03-23 22:54
Duplicate of #10611

**Closed by bmatican** 2022-03-23 22:54 UTC
Labels: duplicate, area/docdb, priority/medium
