### ISSUE TITLE
[yugaware] Add gflag change mode where we can skip restarting the servers

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1869] opened 2019-07-22 22:18 UTC
Based on recent experience of tuning flags on various deployments, an interesting option we might want to put into YW would be to be able to:
- go into the machines and modify the conf files (this should guarantee persistence in case of sudden restarts)
- use the `SetFlag` RPCuse to set the gflags in memory (this should kick in instantly)

Note, this will only work for the type of gflags that can actually be modified at runtime!

cc @spolitov @ttyusupov @rao-vasireddy @kmuthukk

**Comment by rahuldesirazu** [comment] 2020-06-08 22:41
Duplicate of closed issue https://github.com/yugabyte/yugabyte-db/issues/4433.

**Closed by rahuldesirazu** 2020-06-08 22:41 UTC
Labels: area/ui, kind/enhancement
