### ISSUE TITLE
[YSQL] Tablet servers page shows incorrect tablet count for colocated tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4290] opened 2020-04-23 22:48 UTC
Tablet servers page (http://127.0.0.1:7000/tablet-servers) shows incorrect count for user tablets while using colocated tables - it's counting the same tablet for every table that's colocated.

**Comment by kmuthukk** [comment] 2020-05-07 03:31
Is this a duplicate of #3674?

**Comment by jaki** [comment] 2020-05-07 17:58
Looks like it.  Thanks, @kmuthukk.

**Closed by jaki** 2020-05-07 17:58 UTC
Labels: area/sql, duplicate
