### ISSUE TITLE
[Tablet-Splitting][Materialized Views] Enabling tablet splitting on an already loaded cluster with mat views causes tserver crash, generates core files

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#13111] opened 2022-06-30 11:29 UTC
Jira Link: [DB-2819](https://yugabyte.atlassian.net/browse/DB-2819)
### Description

- Create a table and a materialised view with lots of data(executed with 9 million rows of data in my run) on a cluster with no tablet splitting.
- Enable tablet splitting with the following gflags: 
```
 Master:
enable_automatic_tablet_splitting = true
tablet_split_low_phase_size_threshold_bytes = 13421       
tablet_split_low_phase_shard_count_per_node = 16
* Tserver:
enable_automatic_tablet_splitting = true
yb_num_shards_per_tserver=1
ysql_num_shards_per_tserver=1
```
- As soon as tablet splitting is enabled , aggressive splitting starts
- Wait for the splitting to complete. Give it a 30 minutes to an hour of bake time.
- Load more data into the table(Another 3 million rows) and Refresh the materialized view
**Issue:**
i) Tserver goes down in the cluster
ii.) Reads fail with rpc timeout
iii.) Core files are generated
iv.) Splitting also stops for the materialized view(Upon refresh, the mat view is recreated and starts splitting from scratch. Pre-refresh the mat veiw had 49 tablets, so one would expect at least 49 tablets post refresh if not more. Upon refresh, it gets stuck after 7 tablets are created.)

[stacktrace.log](https://github.com/yugabyte/yugabyte-db/files/9025288/stacktrace.log)

**Note:**
Consistently reproducible.

**Version:** 2.15.1.0-b88
CC: @rthallamko3

**Comment by arybochkin** [comment] 2022-07-05 15:23
@kripasreenivasan there're a couple of questions:
1) Was restart applied after the gflags were changed to enable automatic tablet splitting at step "Enable tablet splitting with the following gflags:"?
2) What type of refresh was executed, concurrent or non-concurrent?

**Comment by kripasreenivasan** [comment] 2022-07-06 06:25
Hi @arybochkin ,

> Was restart applied after the gflags were changed to enable automatic tablet splitting at step "Enable tablet splitting with the following gflags:"?
Yes

> What type of refresh was executed, concurrent or non-concurrent?
Non-concurrennt refresh.

**Comment by rthallamko3** [comment] 2022-09-12 17:47
This is not a GA blocker for tablet-splitting because of the following:
1. If and when the tserver crash happens, the materialized view refresh command would fail (No corruption etc). The app can retry the materialized view refresh command.
2. The cause of the crash is incorrect in-memory state for SST file user frontiers, this gets fixed once the tserver process restarts (after the crash).

**Comment by rthallamko3** [comment] 2022-10-10 16:24
[GH14391](https://github.com/yugabyte/yugabyte-db/issues/14391) tracks the necessary unit test change needed to repro this in-house.

**Closed by rthallamko3** 2022-10-10 16:24 UTC
Labels: kind/bug, area/docdb, priority/medium, tablet-splitting
