### ISSUE TITLE
[YCQL] Prepared Statement cache is not updated when table schema changes.

### ISSUE THREAD

**Issue by Tasneem9879** [yugabyte/yugabyte-db#11334] opened 2022-02-02 17:13 UTC
Jira Link: [DB-700](https://yugabyte.atlassian.net/browse/DB-700)
### Description

If the Table Schema is changed the Tservers are not notified (by design for now). That's why the Prepared Statement cache is not updated.

GH issue: https://github.com/yugabyte/yugabyte-db/issues/10774
Note, this issue has not been fixed yet.
Workarounds:
- restart all TSes (to clean Prepared Statement cache in memory)
- make a dummy change in the statement text (such as adding a space) so that the old entries in the prepared statement cache is not reused

The similar issue is fixed in ycqlsh tool. It's https://github.com/yugabyte/yugabyte-db/issues/9683
But it affects only ycqlsh tool.

This request is for fix for Java driver.
Customer is using below
```

 "com.datastax.dse" "dse-java-driver-core"  "1.4.0"

Generally for Scala builds it's either Datastax driver or "com.yugabyte"  "cassandra-driver-core"
```

**Comment by OlegLoginov** [comment] 2022-10-07 18:25
It looks like a duplicate of https://github.com/yugabyte/yugabyte-db/issues/10774

**Closed** 2022-10-07 18:30 UTC
Labels: kind/enhancement, priority/high, area/ycql, area/ecosystem
