### ISSUE TITLE
[YSQL][Upgrade] Internal error: Flush: Invalid serialized Postgres expression: 4 vs 1: . Errors from tablet servers: [Internal error (yb/docdb/doc_pg_expr.cc:116): Flush: Invalid serialized Postgres expression: 4 vs 1]

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#15186] opened 2022-11-30 22:55 UTC
Jira Link: [DB-4375](https://yugabyte.atlassian.net/browse/DB-4375)
### Description

I am in the process of improving verification of objects during an ongoing upgrade: https://phabricator.dev.yugabyte.com/D20539

Some tests are failing with this error during upgrade to 2.17.1.0-b259:
```
testupgrade-k8s-rf3-upgrade-2.12.10.0_41: Start
	(     0.682s) User Login : Success
	(     0.325s) Refresh YB Version : Success
	(    90.727s) Setup Provider : Success
	(     0.115s) Updating Health Check Interval to 60000 sec : Success
	(   452.124s) Create universe dfel-isd2335-9967c3d3dc-20221129-085612 : Success
	(    38.048s) Start sample workloads : Success
	(   890.776s) Creating V2 backups in S3 : Success
	(   461.755s) Verify geo-partitioned objects : Success
	(   471.926s) Executing yb-admin upgrade_ysql : Success
	(     0.001s) Executing yb-admin upgrade_ysql : >>> Integration Test Failed <<< 
Verifying during upgrade failed:
Internal error: Flush: Invalid serialized Postgres expression: 4 vs 1: . Errors from tablet servers: [Internal error (yb/docdb/doc_pg_expr.cc:116): Flush: Invalid serialized Postgres expression: 4 vs 1]

	(    22.716s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.17.1.0_testupgrade-k8s-rf3-upgrade-2.12.10.0_41_20221129_134308 : Success
	(    96.005s) Destroy universe : Success
	(     0.347s) Check and stop workloads : Success
testupgrade-k8s-rf3-upgrade-2.12.10.0_41: End
```
Also happens on `testupgrade-aws-rf3-upgrade-2.12.10.0_41`, so this seems to be a deterministic problem during upgrade from 2.12 to master.
Related master logging:
```
I1129 09:33:16.731261 57793 ysql_transaction_ddl.cc:126] Verifying Transaction { transaction_id: 1ce43060-a89c-4e5c-9cbc-d4d1d661eb30 isolation: SNAPSHOT_ISOLATION status_tablet: 02ea380238d34cb68a0d8076d87e0ef0 priority: 16941835591537085165 start_time: { physical: 1669714396379687 } locality: GLOBAL old_status_tablet:  external_transaction: }
I1129 09:33:16.732386 57689 ysql_transaction_ddl.cc:193] Got Response for { transaction_id: 1ce43060-a89c-4e5c-9cbc-d4d1d661eb30 isolation: SNAPSHOT_ISOLATION status_tablet: 02ea380238d34cb68a0d8076d87e0ef0 priority: 16941835591537085165 start_time: { physical: 1669714396379687 } locality: GLOBAL old_status_tablet:  external_transaction: }, resp: status: PENDING status_hybrid_time: 6839150169013637119 propagated_hybrid_time: 6839150169013653504 aborted_subtxn_set { }
I1129 09:33:16.768287 57686 catalog_manager.cc:6245] T 00000000000000000000000000000000 P 603e2aca7d7145e8966b9af0ba687186: Servicing AlterTable request from 10.9.105.163:35533: table { table_id: "000040200000300080000000000040c2" } new_table_name: "mat_view_nc" new_namespace { name: "mv_upgrade_db2_12_10_0" } transaction { transaction_id: "\034\3440`\250\234N\\\234\274\324\321\326a\3530" isolation: SNAPSHOT_ISOLATION status_tablet: "02ea380238d34cb68a0d8076d87e0ef0" priority: 16941835591537085165 start_hybrid_time: 6839150167571197952 locality: GLOBAL }
I1129 09:33:16.770421 57686 catalog_manager.cc:9997] Persist transaction metadata into SysTableEntryPB for table ID 000040200000300080000000000040c2
I1129 09:33:16.770536 57686 catalog_manager.cc:6490] Successfully initiated ALTER TABLE (pending tablet schema updates) for mat_view_nc [id=000040200000300080000000000040c2] per request from 10.9.105.163:35533
I1129 09:33:16.780130 57794 backfill_index.cc:267] mat_view_nc [id=000040200000300080000000000040c2] - Alter table completed version=1, state: RUNNING
I1129 09:33:16.828274 56979 tablet_service.cc:346] T 00000000000000000000000000000000 P 603e2aca7d7145e8966b9af0ba687186 [state=RUNNING]: Write failed: Internal error (yb/docdb/doc_pg_expr.cc:116): Invalid serialized Postgres expression: 4 vs 1
I1129 09:33:16.933879 57793 catalog_manager.cc:4202] Table transaction failed, deleting: mat_view_nc [id=000040200000300080000000000040c2]
I1129 09:33:16.934170 57793 catalog_manager.cc:5578] Servicing DeleteTable request from internal request: table { table_id: "000040200000300080000000000040c2" table_name: "mat_view_nc" } is_index_table: false
I1129 09:33:16.937139 57793 catalog_manager_ent.cc:3349] Deleting CDC streams for tables: 000040200000300080000000000040c2
I1129 09:33:16.937165 57793 catalog_manager.cc:5751] Deleting table: mat_view_nc, retained by: []
I1129 09:33:16.937223 57793 catalog_manager.cc:10181] Deleting tablet 1bd7f87daef44deb89ebe3c6a8b4f7ee
I1129 09:33:16.937232 57793 catalog_manager.cc:10181] Deleting tablet 1e9d6a9d0d4b42fa8a4863637beec7cd
I1129 09:33:16.937239 57793 catalog_manager.cc:10181] Deleting tablet 34f8d27f6f6c4919807434e1617747c2
I1129 09:33:16.937268 57793 catalog_manager.cc:10181] Deleting tablet 45234c70db954a258e34db69a1db08cb
I1129 09:33:16.937274 57793 catalog_manager.cc:10181] Deleting tablet c95b94251d0545fd89a2d3d97a27d4ef
I1129 09:33:16.937280 57793 catalog_manager.cc:10181] Deleting tablet dbc1538f96cb44ecb9558f6874e89aab
I1129 09:33:16.942265 57793 catalog_manager.cc:10200] Deleted tablet 1bd7f87daef44deb89ebe3c6a8b4f7ee
I1129 09:33:16.942287 57793 catalog_manager.cc:10057] Sending DeleteTablet for 3 replicas of tablet 1bd7f87daef44deb89ebe3c6a8b4f7ee
```
Postgres logging:
```
W1129 09:33:16.829005 57789 tablet_rpc.cc:475] Internal error (yb/docdb/doc_pg_expr.cc:116): Failed Write(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 1, txn: 1ce43060-a89c-4e5c-9cbc-d4d1d661eb30, subtxn: [none]) to tablet 00000000000000000000000000000000 on tablet server { uuid: 603e2aca7d7145e8966b9af0ba687186 private: [host: "10.9.105.163" port: 7100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" after 1 attempt(s): Invalid serialized Postgres expression: 4 vs 1
2022-11-29 09:33:16.830 UTC [57779] ERROR:  Internal error: Flush: Invalid serialized Postgres expression: 4 vs 1: . Errors from tablet servers: [Internal error (yb/docdb/doc_pg_expr.cc:116): Flush: Invalid serialized Postgres expression: 4 vs 1]
2022-11-29 09:33:16.830 UTC [57779] STATEMENT:  REFRESH MATERIALIZED VIEW mat_view_nc
```
So this is related to materialized views. CC @fizaaluthra 
Full logs: https://drive.google.com/file/d/1jhjHSDHJigd_4z6WBpyj3oZVaxrPK8jI/view?usp=share_link

**Comment by andrei-mart** [comment] 2023-02-16 18:32
@m-iancu I guess we need a confirmation from the QA team that they can no longer reproduce the issue to close it.

**Comment by rajapriya371** [comment] 2023-05-30 05:27
@m-iancu @OlegLoginov  The above fix is not back-ported to other version like 2.8, 2.12, 2.14, 2.16, so users finding issues while upgrading from those version especially since 2.14 in LTS.

**Comment by andrei-mart** [comment] 2023-06-02 20:30
Backported to 2.14 and 2.16.

**Closed by andrei-mart** 2023-06-02 20:30 UTC
Labels: kind/bug, area/ysql, priority/medium, qa_automation
