### ISSUE TITLE
UNIQUE constraint error when using sequelize ORM

### ISSUE THREAD

**Issue by syedshah12tech** [YugaByte/yugabyte-db#1234] opened 2019-04-21 17:51 UTC
Hi,

I am seeing the following error in the logs when using sequelize ORM with YugaByte:
`
sequelize:sql:pg Executing (default): CREATE TABLE IF NOT EXISTS "orderlines" ("id"   SERIAL , "orderId" UUID NOT NULL, "productId" INTEGER NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("orderId", "productId"), PRIMARY KEY ("id")); +3ms
Executing (default): CREATE TABLE IF NOT EXISTS "orderlines" ("id"   SERIAL , "orderId" UUID NOT NULL, "productId" INTEGER NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("orderId", "productId"), PRIMARY KEY ("id"));
  sequelize:pool connection released +2ms
Unhandled rejection SequelizeDatabaseError: UNIQUE constraint not supported yet
    at Query.formatError (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/sequelize/lib/dialects/postgres/query.js:354:16)
    at query.catch.err (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
    at tryCatcher (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/syedshah/Documents/dev/orm-examples/node/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
`

My orderline model definition is as follows:

`module.exports = (sequelize, DataTypes) => {
  const OrderLine = sequelize.define('orderlines', {
    orderId: {
			type: DataTypes.UUID,
			unique: 'compositeKey',
			allowNull: false
		},
    productId:{
			type: DataTypes.INTEGER,
			unique: 'compositeKey',
			allowNull: false
		}
  }, {});
  OrderLine.associate = function(models) {
    // associations can be defined here
  };
  return OrderLine;
};`

thanks

**Comment by ndeodhar** [comment] 2019-04-22 01:28
Thanks for reporting @syedshah12tech. Marking this as duplicate of https://github.com/YugaByte/yugabyte-db/issues/1022. Please use #1022 to track progress of this feature.

**Closed by ndeodhar** 2019-04-22 01:28 UTC
