### ISSUE TITLE
[DocDB][Read Committed]Transaction may get aborted with Cannot find status tablet for write_batch transaction error if there is a deadlock

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20013] opened 2023-11-22 17:33 UTC
Jira Link: [DB-8980](https://yugabyte.atlassian.net/browse/DB-8980)
### Description

Tried on version: **2.21.0.0-b238**

While running a Read Committed + Geo-partition + Wait on conflict test, one of the transaction got aborted with the following error, the deadlock part of the error is expected but `Cannot find status tablet for write_batch transaction` may not be expected? 

`
DETAIL:  Errors occurred while reaching out to the tablet servers: . Errors from tablet servers: [Internal error (yb/docdb/conflict_resolution.cc:985): Cannot find status tablet for write_batch transaction 47cd5214-ac3c-4870-b8dd-8865dc742ae4, Operation expired (yb/docdb/deadlock_detector.cc:636): Transaction 47cd5214-ac3c-4870-b8dd-8865dc742ae4 aborted due to a deadlock.
47cd5214-ac3c-4870-b8dd-8865dc742ae4 -> f2b62260-4595-4cef-9a99-c3a98c4065b8 -> 47cd5214-ac3c-4870-b8dd-8865dc742ae4 : kDeadlock (transaction error 6)]
`
Note: Aggressive Tablet Splitting is enabled

Test details:
```
- Create a cluster with required g-flags
- Create 2 database
- Create both colocated and non-colocated tables
- Create all types of indexes
- Start a thread which will execute flush and compaction on all the tables
    after every 5 mins.
- Start 8 threads and perform the following operation for 40 mins
                (There maybe some conflicts in DMLs)
                a. Insert 10 rows in all the tables
                b. Add a savepoint S1
                c. Update 1 row in all the tables
                d. Add a savepoint S2
                e. Select 1 row(FOR (UPDATE, SHARE, NO KEY UPDATE, KEY SHARE, "")) in all the tables
                f. Add a savepoint S3
                g. Delete some rows in all the tables
                h. Add a savepoint S4
                i. Rollback to any savepoint
                j. Increase age column of a constant PK
                k. Commit both the transaction

```

G-flags
```
t_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_num_shards_per_tserver": 1,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "scheduled_full_compaction_frequency_hours": "12",
                "scheduled_full_compaction_jitter_factor_percentage": "100",
                "scheduled_full_compaction_check_interval_min": "5",
                "yb_enable_read_committed_isolation": "true",
                "consistent_restore": "true"
            })
            m_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "yb_enable_read_committed_isolation": "true",
                "enable_automatic_tablet_splitting": "true",
                "tablet_split_high_phase_shard_count_per_node": 200,
                "tablet_split_low_phase_shard_count_per_node": 16,
                # high_phase_size 2MB
                "tablet_split_high_phase_size_threshold_bytes": 2097152,
                # low_phase_size 100KB
                "tablet_split_low_phase_size_threshold_bytes": 102400,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "consistent_restore": "true"
            })
```
[Logs https://drive.google.com/file/d/19YZgpY3GIA5FS0Ui_1syWcP2uxFRTTLT/view?usp=sharing](https://drive.google.com/file/d/19YZgpY3GIA5FS0Ui_1syWcP2uxFRTTLT/view?usp=sharing)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8980]: https://yugabyte.atlassian.net/browse/DB-8980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment] 2023-11-27 17:13
this is another case of a retryable error being combined with deadlock error, and both being reported ot the user. we should always only report the deadlock error

dupe of https://github.com/yugabyte/yugabyte-db/issues/18611

**Closed by robertsami** 2023-11-27 17:13 UTC
Labels: kind/bug, area/docdb, priority/medium, QA, qa_automation
