### ISSUE TITLE
Compact_table is getting timed out when running workload with 3600 seconds (flush_table is succeeding quick)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#14466] opened 2022-10-13 10:35 UTC
Jira Link: [DB-3865](https://yugabyte.atlassian.net/browse/DB-3865)
### Description

While running workload, flush_table is succeeding but compact_table is getting timed out. Please note, workload is run and writes are happening in continuous fashion.

```
2022-10-13 16:17:15,196:DEBUG: > 172.151.29.227 > /home/yugabyte/tserver/bin/yb-admin --master_addresses 172.151.29.227,172.151.25.192,172.151.26.2 flush_table ysql.postgres test_packed_columns_sql_75a013 3600 2>&1
2022-10-13 16:17:20,275:DEBUG: < 172.151.29.227 < Flushed [postgres.test_packed_columns_sql_75a013] tables.

2022-10-13 16:17:20,276:DEBUG: > 172.151.29.227 > /home/yugabyte/tserver/bin/yb-admin --master_addresses 172.151.29.227,172.151.25.192,172.151.26.2 compact_table ysql.postgres test_packed_columns_sql_75a013 3600 2>&1
2022-10-13 17:17:21,737:DEBUG: < 172.151.29.227 < Error running compact_table: Timed out (yb/util/backoff_waiter.cc:48): Unable to compact table postgres.test_packed_columns_sql_75a013: Timed out waiting for FlushTables
```

**Sample apps:**
export JAVA_HOME=/tmp/tests/artifacts/java-11/jdk-11; export PATH=$PATH:/tmp/tests/artifacts/java-11/jdk-11/bin; nohup java  -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.19.jar --workload SqlDataLoad  --uuid 476b84b3-4a30-4f06-b212-59301ebf34d6 --create_table_name test_packed_columns_sql_75a013 --num_writes -1 --num_threads_write 5 --num_reads -1 --num_threads_read 10 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 10 --uuid_marker cab93fb4-c4fd-42a1-a611-6fcd9c821063 --nodes 172.151.29.227:5433,172.151.25.192:5433,172.151.26.2:5433 2>&1 > /tmp/tests/PackedColumnsSuite/test_sql_packed_columns_toggle_on_and_off/workload-SqlDataLoad.20221013161342.log 2>&1 &
**Note:** I have enabled packed columns. (I am yet to test it without packed columns enabled)

Here is the SST size graph (for 1 hour since it started). But flush_table and compact table was executed at 4:17 PM IST. We can see that at that time it was about 0.15 GB. AFAIK, flush_table and compact_table will execute and consider data until when the command was run. PFA for screenshot of graph.

![Screenshot 2022-10-13 at 5 33 48 PM](https://user-images.githubusercontent.com/109518123/195591828-cec8da18-81af-43ae-ada1-1312959f1e81.png)

Also attaching different graphs associated with DocDB and Nodes: recording, if it would be useful.

Uploading Screen Recording 2022-10-13 at 5.37.29 PM.mov…

cc: @kripasreenivasan

**Comment by jmeehan16** [comment] 2023-04-10 21:30
Closing this as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/16230

**Comment by jmeehan16** [comment] 2023-04-10 21:31
https://github.com/yugabyte/yugabyte-db/issues/16230

**Closed by jmeehan16** 2023-04-10 21:30 UTC
Labels: kind/bug, area/docdb, priority/medium, qa_automation
