### ISSUE TITLE
[YSQL] Port pg_regress_isolation

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2703] opened 2019-10-23 22:13 UTC
Jira Link: [DB-2000](https://yugabyte.atlassian.net/browse/DB-2000)
Currently, we use `pg_regress` from the Postgres source code to run a lot of our tests (see `PgRegressRunner`).  We could benefit from also porting `pg_regress_isolation`.  This would unlock the tests in [`src/postgres/src/test/isolation/`][1].

[1]: https://github.com/yugabyte/yugabyte-db/tree/master/src/postgres/src/test/isolation

**Comment by jj-kim** [comment] 2019-10-25 18:03
In the meantime, `pg_regress_isolation` can be manually run.

1. `./yb_build.sh <options>`
1. `cd build/latest/postgres_build/src/test/isolation`
1. For Yugabyte: `./pg_regress_isolation --host=localhost --port=5433 --user=yugabyte`

   For vanilla PostgreSQL: `./pg_regress_isolation --host=localhost --port=5432 --user=$USER`

This is under the assumption that you have a vanilla PostgreSQL installation with role `$USER` and your port numbers are as specified.

**Comment by jj-kim** [comment] 2019-11-01 18:40
One thing that may need to be done to get this working is handling probabilistic outcomes.  For example, if session A and session B conflict, it may be the case that session A fails and session B succeeds or vice versa.  Pure `diff` used by `pg_regress_isolation` may not be sufficient.

**Comment by jasonyb** [comment] 2023-05-04 20:19
Now duplicate of more recent issue #12637

**Closed by jasonyb** 2023-05-04 20:19 UTC
Labels: kind/enhancement, area/ysql, priority/medium
