### ISSUE TITLE
[DocDB] YSQL select max() returns inconsistent result after tablet splitting

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#15016] opened 2022-11-15 17:20 UTC
Jira Link: [DB-4257](https://yugabyte.atlassian.net/browse/DB-4257)
### Description

Tried multiple times on RF=3 cluster with version `version 2.17.1.0 build PRE_RELEASE revision 8aca6c655352702eed83c47c0f7e185bc99a99db build_type RELEASE`.
```
create table demo2 ( id int generated always as identity, data text, primary key(id asc) );
copy demo2(data) from program 'base64 -w 16384 /dev/urandom | head -c 419430400';
COPY 25599

copy demo2(data) from program 'base64 -w 16384 /dev/urandom | head -c 419430400';
COPY 25599

yugabyte=# select count(*) from demo2;
 count
-------
 51198
(1 row)

yugabyte=# select min(id) from demo2;
 min
-----
   1
(1 row)

yugabyte=# select max(id) from demo2;
  max
-------
 37735
(1 row)
```

Then restarted ysqlsh and getting:

```
yugabyte=# select max(id) from demo2;
  max
-------
 19302
(1 row)
```

**Comment by ttyusupov** [comment] 2022-11-15 17:22
Restarting both `yb-tserver` and `postgres` processes on cluster fixes the issue until the next split.

**Comment by andrei-mart** [comment] 2022-11-15 17:55
Summarizing analysis from the slack thread https://yugabyte.slack.com/archives/C01HD5HPK8A/p1668523105712039
The key facts here are that 
- we have a backward scan
- tablet split has happened

Postgres planner applies min/max optimization when there is suitable (asc or desc) index on the column, so it scans the index in correct direction and picks the first row. 
So executor composes a request to scan the PK backward with 1 row limit. However, executor does know about the split, and thinking there is only one partition, it routes the request to the tablet with empty lower bound (we use lower bound to identify target tablet). In practice, the target tablet has a higher bound, which differ from expected (empty), but nonetheless tserver starts scan and return one row, which is taken by PG as one with the highest key.

When doing forward scan tserver handles mismatched upper bound by injecting paging info into the response when end of the tablet is reached, so scan continues into the next partition. To be consistent, backward scan shouldn't start if target tablet has mismatching upper bound, instead it should return no rows and paging state with redirection to correct tablet.

There is a problem if there was multiple splits. It is easy to identify next partition, its lower bound would be the same as the upper bound of the current partition, however lower bound of the last partition may be not known.

**Comment by OlegLoginov** [comment] 2022-11-30 22:36
Similar issue in YCQL:  https://github.com/yugabyte/yugabyte-db/issues/13295
(Root cause is different - in YCQL the bug is in the YCQL Executor, which does not process all tablets.)

**Comment by rthallamko3** [comment] 2022-12-27 19:28
reactivating for backports.

**Comment by arybochkin** [comment] 2023-01-24 13:15
Backported, hence closing.

**Closed by arybochkin** 2023-01-24 13:15 UTC
Labels: kind/bug, area/docdb, priority/critical, 2.14 Backport Required, tablet-splitting, 2.16 Backport Required
