### ISSUE TITLE
[xCluster] Set deadline for TableRange

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#9891] opened 2021-08-31 20:22 UTC
Currently calls to client::TableRange() don't set deadline for the underlying YBSession::Batcher() (called via TableIterator).
This results in:
```
60110	     @ 0x7f5e9d2a4d19 yb::client::YBSession::Batcher() (src/yb/client/session.cc:341)
60111	     @ 0x7f5e9d2a547f yb::client::YBSession::Apply(shared_ptr<yb::client::YBOperation>) (src/yb/client/session.cc:352)
60112	     @ 0x7f5e9d2ebbfd yb::client::TableIterator::ExecuteOps() (src/yb/client/table_handle.cc:246)
60113	     @ 0x7f5e9d2eb26a TableIterator (src/yb/client/table_handle.cc:237)
```
This revision sets the deadline in CatalogManager::CleanUpDeletedCDCStreams() and TableIterator ctor for YBSession.

**Comment by hari90** [comment] 2023-09-07 18:43
Duplicate of #18398

**Closed by hari90** 2023-09-07 18:43 UTC
