### ISSUE TITLE
[YCQL] Prepares are Not being Refreshed after Changes (Alter) to Table Schema

### ISSUE THREAD

**Issue by randersenYB** [yugabyte/yugabyte-db#10774] opened 2021-12-03 17:22 UTC
Jira Link: [DB-702](https://yugabyte.atlassian.net/browse/DB-702)
### Description

A large customer does not wish to perform a rolling restart of their production cluster whenever they are required to make table schema changes. Their cluster supports multiple applications and consists of multiple keyspaces. They consider this a "**serious**" issue.

### Issue
If a column is added or the data type of a column is changed, the YCQL nodes' corresponding prepare cache(s) are not being refreshed resulting in the application driver using the old prepare from the YB node. The attached driver traces explicitly shows that the driver does request a prepare from a node after the alter is detected. The old prepares on the nodes are used even if the application is restarted. As such, this results in unexpected driver exceptions/behaviors like:

- CodecNotFoundException (in the case of data type change)
- InvalidQueryException: Undefined Column. Column doesn't exist (in the case a column is added)
- A null value is returned,  on selects, using a newly added column even when there is existing data associated with that column

### Environment
The customer is using YBDB version 2.6.5.0-b4 and the applications are using YB Java driver 3.4 and 4.6. The cluster has two AZs with a total of 24 nodes. Each zone has 12 nodes and one is defined as a primary.

### Reproduce
I was able to reproduce this issue on a 6 node one AZ cluster on version 2.6.5.0-b4. I wrote (actually reused) a Java application using YB Java driver 3.8.0-yb-5 and  Java driver 4.11.4-yb-1-RC1.

I have attached the Java applications, DDL, and complete debug driver trace outputs. Note that the Java test applications are hacks and are messy...

### Tried Work-Arounds
I have tried different work-arounds but nothing I tried seemed to work except a rolling restart or remove the prepares. I tried the following:

- Changing the below values:
> - cql_system_query_cache_stale_msecs
> - cql_system_query_cache_tables
> - cql_update_system_query_cache_msecs
> - cql_service_max_prepared_statement_size_bytes
- Restarting the application which at times does work but a majority of times it fails
- Re-Preparing the DML statement within the application after the alter
- Closing and re-opening the session within the application after the alter
- Closing the cluster and re-building using different contact point within the application after the alter
- Dropping and re-adding the table with the same name (via ycqlsh)
- Altering the table in ycqlsh (manually) and within the application

### Similar Issues

- Issue #7832
- Issue #3500
- Issue #1427
- Issue #1425
- Issue #497
- Issue #1425
- Issue [\[WIP\] Update client-side cache of prepared statements unconditionally #2](https://github.com/yugabyte/cassandra-java-driver/pull/2)

### Files

[YCQLPrepareEx0308Java.zip](https://github.com/yugabyte/yugabyte-db/files/7651101/YCQLPrepareEx0308Java.zip)
[YCQLrepareEx0411Java.zip](https://github.com/yugabyte/yugabyte-db/files/7651217/YCQLrepareEx0411Java.zip)
[YCQLDebugOutputJava0308.txt](https://github.com/yugabyte/yugabyte-db/files/7651253/YCQLDebugOutputJava0308.txt)
[YCQLDebugOutputJava0411.txt](https://github.com/yugabyte/yugabyte-db/files/7651254/YCQLDebugOutputJava0411.txt)
[YCQLPrepareDDL.cql](https://github.com/yugabyte/yugabyte-db/files/7651278/YCQLPrepareDDL.cql.txt)

**Comment by randersenYB** [comment] 2021-12-08 18:30
FYI, the Java driver's metadata for the altered table is **updated** properly when the alter occurs.

**Comment by OlegLoginov** [comment] 2022-01-31 15:50
If the Table Schema is changed the TSes are not notified (by design for now). That's why the Prepared Statement cache is not updated.

Workarounds:
- restart all TSes (to clean Prepared Statement cache in memory)
- make a dummy change in the statement text (such as adding a space) so that the old entries in the prepared statement cache is not reused


The similar issue is fixed in `ycqlsh` tool. It's https://github.com/yugabyte/yugabyte-db/issues/9683
But it affects only `ycqlsh` tool.

**Comment by randersenYB** [comment] 2022-01-31 16:12
As stated in the description, a rolling restart is not acceptable by the customer.  Is there a timeline when the root cause of this issue is actually fixed? Thanks...

**Comment by randersenYB** [comment] 2022-01-31 16:13
reopened...

**Comment by OlegLoginov** [comment] 2022-04-27 14:28
WIP fix:  https://phabricator.dev.yugabyte.com/D15510

Behavior before the fix:

Prepared Query ID = MD5( current-keyspace-name + query-text )
The query is analyzed ONCE only when it's created (first PREPARE is called).
The stored analyzed prepared statement is NEVER updated even if the table is ALTERed or reCREATEd, or if the PREPARE is called again.
That's why even the client application restart does not help to update the stored Prepared statement.

The main issue: once stored Prepared statement is never updated.
(The only way - to restart all TSes to clean it from the memory.)

The diff includes 2 fixes:
- The main change - on every PREPARE request the related table schema is checked. The stored Prepared Statement is replaced by a new one if the related table schema was changed. This is fixing the main issue - it's updating the stored Prepared Statement if the client app calls PREPARE once again for the altered table. This is controlled by the new g-flag `cql_check_table_schema_in_prepare` (it's TRUE by default).
- Include schema-info into the EXECUTE Result Response. It's controlled by the new g-flag `cql_always_return_metadata_in_execute_response` (it's TRUE by default.) This allows the driver side correctly shows results of Prepared "SELECT * FROM ..." statements after the schema update. It works with the fix even if the PREPARE was NOT called again. But as the Execute Response includes now the schema info - the driver can use it internally to show the correct result. Note: the new mode is ENABLED by default. (As the Execute Response is enlarged by the schema info, the feature increases the network traffic a bit for CQL EXECUTE calls. If it's critical - it can be disabled via the flag mentioned above.)

Some explanations for the testAlterDropAddSameSizeType() test:
- For the existing connections - the behavior is UNCHANGED. It's possible to write INT8 into FLOAT8 due to the driver implementation.
- For the NEW connections - the behavior is IMPROVED: with the fix the new type correctly used in 100% runs, before - there are ~65% failures (because it's trying to use the old type by mistake).

**Comment by OlegLoginov** [comment] 2022-04-27 14:52
Notes for the behavior above - when we writing INT8 and reading DOUBLE:
1. It's not directly related to the GH issue #10774, because the Prepared statements Cache refresh does not help with the behavior.
2. The issue reason is architectural - it's in the CQL Protocol - the CQL EXECUTE Request does not include type-info, so the server side should interpret the incoming bytes in accordance with the available table schema. So, it cannot know that the driver packed into the request another type value.

To resolve it the Server should send in time the SCHEMA_CHANGE event to the driver. So, it should be a separate fix.

**Comment by OlegLoginov** [comment] 2022-10-17 09:32
Fixed in 2.12, 2.14, Master (2.17).

**Closed by OlegLoginov** 2022-10-17 09:32 UTC
Labels: kind/enhancement, priority/high, area/ycql, 2.12 Backport Required, 2.14 Backport Required
