### ISSUE TITLE
[YSQL] FROM clause in UPDATE not supported yet Error

### ISSUE THREAD

**Issue by annaelizabeth2019** [yugabyte/yugabyte-db#4539] opened 2020-05-20 23:02 UTC
On this query:
```		UPDATE table1 x SET
		updated_at = now(),
		time_spent = EXTRACT(EPOCH FROM (now() - created_at))
		FROM table1 y
		WHERE 
			x.domain_id = y.domain_id and
			x.profile_id = y.profile_id and
			x.session_id = y.session_id and
			x.domain_id = $1 and 
			x.profile_id = $2 and 
			x.session_id = $3
		RETURNING
		EXTRACT(EPOCH FROM(now() - y.updated_at))
```

It returns an error:  `FROM clause in UPDATE not supported yet`

**Comment by jaki** [comment] 2020-05-20 23:06
This is part of issue #738.  It might be worth keeping around to track separately, but I'll let someone else decide whether to close this as a duplicate.

**Comment by ndeodhar** [comment] 2020-07-27 20:51
Closing as duplicate of #738.

**Closed by ndeodhar** 2020-07-27 20:51 UTC
Labels: area/ysql, community/request
