### ISSUE TITLE
[YSQL] Prevent requests to YSQL DB while the DB is being restored from backup.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#5105] opened 2020-07-15 17:04 UTC
When YSQL DB is being restored via `yb_backup.py .. restore` - any read/write operations can fail or can return incorrect result. To prevent this - any requests to the DB must be prohibited.

**Comment by ndeodhar** [comment] 2020-07-16 02:47
@OlegLoginov Closing this as duplicate of https://github.com/yugabyte/yugabyte-db/issues/4885.

**Closed by ndeodhar** 2020-07-16 02:47 UTC
Labels: area/ysql
