### ISSUE TITLE
[YSQL] Filter out system_platform queries from SQL ops metric

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#10903] opened 2021-12-17 06:17 UTC
### Description

Platform plans to create a dummy table in system_platform namespace to verify reads/writes (instead of just connections as currently done). These will show up in ysql/ycql ops metrics dashboad. Ideally we should be able to filter this db out of the metrics collection. @m-iancu @anmalysh-yb

**Comment by sushantrmishra** [comment] 2022-05-02 05:02
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/11483

**Closed by sushantrmishra** 2022-05-02 05:02 UTC
Labels: area/ysql
