### ISSUE TITLE
[doc] Document non-replicated install proccess

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#8289] opened 2021-05-04 21:29 UTC
There's a couple of PDFs for non-replicated workflow for installing yugaware, but it's a supported pattern. We need to migrate this information to the official docs to make sure the documentation is searchable and findable.

**Comment by lizayugabyte** [comment] 2022-07-18 16:46
@tylarb Could you provide links to these PDFs, please?

**Comment by lizayugabyte** [comment] 2022-09-27 19:03
@tylarb Could you provide links to these PDFs, please?

**Comment by lizayugabyte** [comment] 2022-09-28 16:28
Comment by Tyler via slack:

This one, we can probably close and / or roll into documentation for Yugabundle enhanced installer.. I assume Sridhar and Nikhil Bhatia have the docs work lined up as part of their epic there. So if there's an existing placeholder for the new yugabundle documentation, we can close this issue, or if not, we can re-purpose it and I can edit the description to make it more clear

**Comment by lizayugabyte** [comment] 2022-11-30 16:28
Jira ticket on yugabundle: https://yugabyte.atlassian.net/browse/PLAT-5616

**Comment by lizayugabyte** [comment] 2022-11-30 16:28
I'm closing this ticket as duplicate of PLAT-5616

**Closed** 2022-11-30 16:28 UTC
