### ISSUE TITLE
[YSQL] Feature request: Read-From-Follower

### ISSUE THREAD

**Issue by ryli17** [yugabyte/yugabyte-db#4207] opened 2020-04-13 20:11 UTC
Example of this feature:

For a multi-region deployment, with 2-nodes in region1, and 1-node in region2. The feature will allow client read from region2 (no need to read the latest or greatest data).

**Comment by ddorian** [comment] 2020-08-05 14:51
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/4207

**Closed by ddorian** 2020-08-05 14:51 UTC
Labels: area/ysql, community/request
