### ISSUE TITLE
Online DDL progress output

### ISSUE THREAD

**Issue by dataindataout** [yugabyte/yugabyte-db#10338] opened 2021-10-18 18:12 UTC
Jira Link: [DB-826](https://yugabyte.atlassian.net/browse/DB-826)
During a long online DDL, it would be helpful to know the status of the process and an ETA of progress to completion.

This could look something like:

INFO: Started requested DDL (alter column asdf set not null)
PROGRESS: 10001/565554 1.8% Elapsed: 10s  Remaining: 500s
PROGRESS: 20001/565554 3.5% Elapsed: 20s  Remaining: 490s
...
PROGRESS: 565501/565554 99.9% Elapsed: 499s  Remaining: 1s
INFO: Completed requested DDL

This could go in a log and standard output.

**Comment by yb-valerie** [comment] 2022-05-09 20:59
Related work https://github.com/yugabyte/yugabyte-db/issues/11928

**Comment by tverona1** [comment] 2023-01-31 20:47
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/10338

**Closed by tverona1** 2023-01-31 20:47 UTC
Labels: kind/enhancement, area/ysql, priority/medium, pgcm
