### ISSUE TITLE
TotalMemWatcher kills the server process.

### ISSUE THREAD

**Issue by virtenv** [yugabyte/yugabyte-db#3525] opened 2020-02-02 20:49 UTC
Hi Yugabyte team,

I run Yugabyte with docker-compose. When I try to connect to the Yugabyte server using Hasura docker container, the server crashes. My laptop probably doesn't have enough memory. Anyway, it can happen to everyone. Then the database structure is not persistent anymore. 
```
yb-tserver-n1 | 2020-02-02 20:27:33.382 UTC [32] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
yb-tserver-n1 | 2020-02-02 20:27:33.423 UTC [32] LOG:  listening on IPv4 address "0.0.0.0", port 5433
yb-tserver-n1 | 2020-02-02 20:27:33.536 UTC [32] LOG:  redirecting log output to logging collector process
yb-tserver-n1 | 2020-02-02 20:27:33.536 UTC [32] HINT:  Future log output will appear in directory "/mnt/disk0/yb-data/tserver/logs".
yb-master-n1  | *** Aborted at 1580672448 (unix time) try "date -d @1580672448" if you are using GNU date ***
yb-master-n1  | PC: @     0x7fcebb36d46d __GI___nanosleep
yb-master-n1  | *** SIGTERM (@0x0) received by PID 1 (TID 0x7fcec929db40) from PID 0; stack trace: ***
yb-master-n1  |     @     0x7fcebb36dba0 (unknown)
yb-master-n1  |     @     0x7fcebb36d46d __GI___nanosleep
yb-master-n1  |     @     0x7fcec676372c  yb::server::TotalMemWatcher::MemoryMonitoringLoop()
yb-master-n1  |     @           0x4084ff  yb::master::MasterMain()
yb-master-n1  |     @     0x7fceba9dc825 __libc_start_main
yb-master-n1  |     @           0x407d99 _start
yb-master-n1  |     @                0x0 (unknown)
```
Regards

**Comment by ddorian** [comment] 2020-02-03 09:02
Can you write your laptop specs ?

**Comment by virtenv** [comment] 2020-02-03 18:03
Host: localhost.localdomain Kernel: 5.4.15-200.fc31.x86_64 x86_64 bits: 64 
           compiler: gcc v: 9.2.1 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM 
           Distro: Fedora release 31 (Thirty One) 
Machine:   Type: Laptop System: ASUSTeK product: UX31A v: 1.0 serial: <filter> 
           Mobo: ASUSTeK model: UX31A v: 1.0 serial: <filter> UEFI: American Megatrends 
           v: UX31A.206 date: 06/05/2012 
Battery:   ID-1: BAT0 charge: 39.2 Wh condition: 40.3/47.9 Wh (84%) volts: 8.3/7.4 
           model: ASUSTeK UX31-35 serial: <filter> status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i7-3517U bits: 64 type: MT MCP arch: Ivy Bridge 
           rev: 9 L2 cache: 4096 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19155 
           Speed: 814 MHz min/max: 800/3000 MHz Core speeds (MHz): 1: 798 2: 797 3: 826 4: 830 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: ASUSTeK Zenbook Prime UX31A 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: Fedora Project X.org 1.20.6 driver: modesetting 
           unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile v: 4.2 Mesa 19.2.8 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio 
           vendor: ASUSTeK Zenbook Prime UX31A driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           chip ID: 8086:1e20 
           Sound Server: ALSA v: k5.4.15-200.fc31.x86_64 
Network:   Device-1: Intel Centrino Advanced-N 6235 driver: iwlwifi v: kernel port: f040 
           bus ID: 02:00.0 chip ID: 8086:088e 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 115.48 GiB used: 60.78 GiB (52.6%) 
           ID-1: /dev/sda vendor: SanDisk model: SSD U100 124GB size: 115.48 GiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 49.09 GiB used: 45.45 GiB (92.6%) fs: ext4 dev: /dev/dm-0 
           ID-2: /boot size: 476.2 MiB used: 102.6 MiB (21.5%) fs: ext4 dev: /dev/sda2 
           ID-3: /home size: 59.90 GiB used: 15.22 GiB (25.4%) fs: ext4 dev: /dev/dm-2 
           ID-4: swap-1 size: 3.75 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-1 
Sensors:   System Temperatures: cpu: 42.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 212 Uptime: 4m Memory: 3.73 GiB used: 644.5 MiB (16.9%) Init: systemd v: 243 
           runlevel: 5 target: graphical.target Compilers: gcc: 9.2.1 
           Client: Unknown python3.7 client inxi: 3.0.37

**Comment by ddorian** [comment] 2020-02-06 11:02
@virtenv what error do you get when you say `Then the database structure is not persistent anymore` ?
Does commands from this page work https://docs.yugabyte.com/latest/quick-start/explore-ysql/ ?

**Comment by virtenv** [comment] 2020-02-06 20:27
> @virtenv what error do you get when you say `Then the database structure is not persistent anymore` ?
> Does commands from this page work https://docs.yugabyte.com/latest/quick-start/explore-ysql/ ?
Yes, although I use the commands for docker https://docs.yugabyte.com/latest/quick-start/explore-ysql/#docker
To give you an answer I have to write more about how I use Hasura with YugaByte.
a) $ sudo docker-compose up -d
Creating network "yugabyte_default" with the default driver
Creating yb-master-n1 ... done
Creating yb-tserver-n1 ... done
![Screenshot from 2020-02-06 20-21-06](https://user-images.githubusercontent.com/47945633/73970933-50b35d00-491e-11ea-8839-440a53a6642a.png)

b) $ sudo docker exec -it yb-tserver-n1 bash
c) $ mkdir data
d) $ exit
e) sudo docker exec -it yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1  --echo-queries
f) CREATE DATABASE yb_mydb;
g) \c yb_mydb;
Here comes the part with postgres permissions related to Hasura:
CREATE USER hasurauser WITH PASSWORD 'hasurauser';
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS hdb_catalog;
CREATE SCHEMA IF NOT EXISTS hdb_views;
ALTER SCHEMA hdb_catalog OWNER TO hasurauser;
ALTER SCHEMA hdb_views OWNER TO hasurauser;
GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO hasurauser;
GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO hasurauser;
GRANT USAGE ON SCHEMA public TO hasurauser;
GRANT ALL ON ALL TABLES IN SCHEMA public TO hasurauser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO hasurauser;
h) $ sudo docker-compose up -d
Creating hasura_graphql-engine_1 ... done
![Screenshot from 2020-02-06 20-36-50](https://user-images.githubusercontent.com/47945633/73972078-70e41b80-4920-11ea-99f6-037a390dc9c1.png)
i) The docker containers look fine.
![Screenshot from 2020-02-06 20-38-54](https://user-images.githubusercontent.com/47945633/73972248-bf91b580-4920-11ea-8800-815749ab00e4.png)
j) Now I can run the command "$ hasura console"
- 1st case: Sometimes I can start it and use my browser to create database tables. Then I get the database error, i.e. if I try to add a new column. As soon as I'll get the console running again I will paste a screen shot here and tell you what the database says.


- 2nd case: Sometimes '$ hasura console' tries to get the connection on the wrong port, I think, because defaults are:
      --api-port string       port for serving migrate api (default "9693")
      --console-port string   port for serving console (default "9695")
and my 'config.yaml' is an empty file. Normally after '$ hasura init' the default config.yaml is created with the entry: 'endpoint: http://localhost:8080' but Hasura works slow on this port and I remove it.

I got:
"FATA[0000] version check: failed to get version from server: failed making version api call: Get http://localhost:8080/v1/version: dial tcp [::1]:8080: connect: connection refused"
graphql-engine_1  | 

Then I run: '$ sudo docker-compose down' to remove hasura container and create it again.

After the new Hasura container was created the following info has been displayed:
{"kind":"db_migrate","info":"Already at the latest catalog version (28); nothing to do."}}

And the 'postgres tx error' was soon there.
![Screenshot from 2020-02-06 20-58-38](https://user-images.githubusercontent.com/47945633/73975238-354c5000-4926-11ea-9d14-ab39bac04bc6.png)

**Comment by bmatican** [comment] 2020-02-06 21:02
@virtenv I think specifically for Hasura, we have this doc page: https://docs.yugabyte.com/latest/develop/graphql/hasura/

Since you're running this from docker, you have to add this to your yml to make sure this env var `YB_SUPPRESS_UNSUPPORTED_ERROR=1` is set on the tserver process.

This might be good enough to get you to successfully run Hasura on top of YugabyteDB. cc @ddorian 

However, the initial error you reported, with `TotalMemWatcher` killing the master, is likely related to the amount of memory available to your master process when you run it in docker. If you have the complete `yb-master.INFO` log and are ok sharing that, would be useful to get a sense of what was happening at that point and how much memory the master thought it had available.

**Comment by virtenv** [comment] 2020-02-06 22:15
> @virtenv I think specifically for Hasura, we have this doc page: https://docs.yugabyte.com/latest/develop/graphql/hasura/
> 
> Since you're running this from docker, you have to add this to your yml to make sure this env var `YB_SUPPRESS_UNSUPPORTED_ERROR=1` is set on the tserver process.
Yes, 'echo $YB_SUPPRESS_UNSUPPORTED_ERROR' returns 1. I forgot to write about my .bashrc
I mean, it's set up properly since I use Hasura and YugaByte.

> 
> This might be good enough to get you to successfully run Hasura on top of YugabyteDB. cc @ddorian
> 
> However, the initial error you reported, with `TotalMemWatcher` killing the master, is likely related to the amount of memory available to your master process when you run it in docker. If you have the complete `yb-master.INFO` log and are ok sharing that, would be useful to get a sense of what was happening at that point and how much memory the master thought it had available.
Actually I've already pasted the whole unique content of the error messages, but yes I will paste all lines. If it is possible I will set the log variable to DEBUG or something like that.
The case you mentioned is my 3rd case I hardly ever can see i.e. during CREATE DATABASE or if I use the docker exec command with redis. As far as I know, only this returns the memory size info.

**Comment by mbautin** [comment] 2020-02-07 00:38
The entire contents of yb-tserver.INFO leading to the TotalMemWatcher crash would be extremely useful for us to help diagnose the issue. Also setting the flag `--memory_limit_termination_threshold_pct=1000` or a higher value might useful as a temporary workaround.

**Comment by virtenv** [comment] 2020-02-07 19:59
> The entire contents of yb-tserver.INFO leading to the TotalMemWatcher crash would be extremely useful for us to help diagnose the issue. Also setting the flag `--memory_limit_termination_threshold_pct=1000` or a higher value might useful as a temporary workaround.

I didn't know how to use YugaByte  flags with docker-composer, that's why I started the database using:
./bin/yb-ctl --rf 1 create --tserver_flags "memory_limit_termination_threshold_pct=1000"

I also wanted to try out the flag '--stderrthreshold=0' but I got an error message and the web port 7000 did not work but I could connect via 9000:
- - -
I0207 18:21:43.526499 23663 partition.cc:388] Creating partitions with num_tablets: 2
I0207 18:21:43.534790 23663 catalog_manager.cc:2155] Successfully created table hdb_schema_update_event [id=000040000000300080000000000040c8] per request from 127.0.0.1:47615
I0207 18:21:43.626196 25594 catalog_manager.cc:4057] Peer 8b7b78d600d940fcbd374585b76d5bdd sent incremental report for 44de893b9a494d1ba7f2c95add116dc0, prev state op id: -1, prev state term: 0, prev state has_leader_uuid: 0. Consensus state: current_term: 0 config { opid_index: -1 peers { permanent_uuid: "8b7b78d600d940fcbd374585b76d5bdd" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
I0207 18:21:43.683648 23663 catalog_manager.cc:4057] Peer 8b7b78d600d940fcbd374585b76d5bdd sent incremental report for 9832781ff9574fcda635b35d67697521, prev state op id: -1, prev state term: 0, prev state has_leader_uuid: 0. Consensus state: current_term: 1 config { opid_index: -1 peers { permanent_uuid: "8b7b78d600d940fcbd374585b76d5bdd" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
I0207 18:21:43.683861 23663 catalog_manager.cc:4057] Peer 8b7b78d600d940fcbd374585b76d5bdd sent incremental report for 44de893b9a494d1ba7f2c95add116dc0, prev state op id: -1, prev state term: 0, prev state has_leader_uuid: 0. Consensus state: current_term: 1 config { opid_index: -1 peers { permanent_uuid: "8b7b78d600d940fcbd374585b76d5bdd" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
I0207 18:21:43.684551 23737 catalog_manager.cc:4022] Tablet: 9832781ff9574fcda635b35d67697521 reported consensus state change. New consensus state: current_term: 1 leader_uuid: "8b7b78d600d940fcbd374585b76d5bdd" config { opid_index: -1 peers { permanent_uuid: "8b7b78d600d940fcbd374585b76d5bdd" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } } from 8b7b78d600d940fcbd374585b76d5bdd
I0207 18:21:43.684635 23737 catalog_entity_info.cc:97] T 9832781ff9574fcda635b35d67697521: Leader changed from <NULL> to 0x0000000003251c10 -> { permanent_uuid: 8b7b78d600d940fcbd374585b76d5bdd registration: common { private_rpc_addresses { host: "127.0.0.1" port: 9100 } http_addresses { host: "127.0.0.1" port: 9000 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } placement_uuid: "" } capabilities: 2189743739 placement_id: cloud1:datacenter1:rack1 }
I0207 18:21:43.688717 23737 catalog_manager.cc:4022] Tablet: 44de893b9a494d1ba7f2c95add116dc0 reported consensus state change. New consensus state: current_term: 1 leader_uuid: "8b7b78d600d940fcbd374585b76d5bdd" config { opid_index: -1 peers { permanent_uuid: "8b7b78d600d940fcbd374585b76d5bdd" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } } from 8b7b78d600d940fcbd374585b76d5bdd
I0207 18:21:43.688781 23737 catalog_entity_info.cc:97] T 44de893b9a494d1ba7f2c95add116dc0: Leader changed from <NULL> to 0x0000000003251c10 -> { permanent_uuid: 8b7b78d600d940fcbd374585b76d5bdd registration: common { private_rpc_addresses { host: "127.0.0.1" port: 9100 } http_addresses { host: "127.0.0.1" port: 9000 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } placement_uuid: "" } capabilities: 2189743739 placement_id: cloud1:datacenter1:rack1 }
I0207 18:21:44.271132 25594 catalog_manager.cc:1792] CreateTable from 127.0.0.1:47615:
name: "hdb_schema_update_event_one_row"
schema {
  columns {
    name: "expr"
    type {
      main: BOOL
    }
    is_key: true
    is_hash_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 0
    order: 1
  }
  columns {
    name: "ybuniqueidxkeysuffix"
    type {
      main: BINARY
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: -102
  }
  columns {
    name: "ybidxbasectid"
    type {
      main: BINARY
    }
    is_key: false
    is_nullable: true
    is_static: false
    is_counter: false
    sorting_type: 0
    order: -101
  }
  table_properties {
    contain_counters: false
    is_transactional: true
    consistency_level: STRONG
    use_mangled_column_name: false
    num_tablets: 2
    is_ysql_catalog_table: false
  }
}
num_tablets: 2
partition_schema {
  hash_schema: PGSQL_HASH_SCHEMA
}
table_type: PGSQL_TABLE_TYPE
namespace {
  id: "00004000000030008000000000000000"
  name: "yb_mewa"
  database_type: YQL_DATABASE_PGSQL
}
indexed_table_id: "000040000000300080000000000040c8"
is_local_index: false
is_unique_index: true
table_id: "000040000000300080000000000040cc"
index_info {
  is_unique: true
  indexed_table_id: "000040000000300080000000000040c8"
}
colocated: true
I0207 18:21:44.271261 25594 partition.cc:388] Creating partitions with num_tablets: 2
W0207 18:21:45.072458 23646 log.cc:702] Time spent Fsync log took a long time: real 0.791s	user 0.000s	sys 0.000s
I0207 18:21:45.072820 25594 catalog_manager.cc:2155] Successfully created index hdb_schema_update_event_one_row [id=000040000000300080000000000040cc] per request from 127.0.0.1:47615
W0207 18:21:45.081313 25594 scoped_leader_shared_lock.cc:114] Long lock of catalog manager: 0.801s
    @     0x7f7002ad6730  yb::master::ScopedLeaderSharedLock::Unlock()
    @     0x7f7002b0cb85  yb::master::MasterServiceImpl::CreateTable()
    @     0x7f6ffd329a00  yb::master::MasterServiceIf::Handle()
    @     0x7f6ffb3b0c19  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f6ffb3548f4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f6ffb3bc868  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f6ff99aae0f  yb::Thread::SuperviseThread()
    @     0x7f6ff5372694  start_thread
    @     0x7f6ff4aaf41d  __clone
    @              (nil)  (unknown)
W0207 18:21:45.453966 23646 log.cc:702] Time spent Fsync log took a long time: real 0.381s	user 0.000s	sys 0.000s
W0207 18:21:45.468966 23743 scoped_leader_shared_lock.cc:114] Long lock of catalog manager: 0.916s
    @     0x7f7002ad6730  yb::master::ScopedLeaderSharedLock::Unlock()
    @     0x7f7002acf91c  yb::master::CatalogManagerBgTasks::Run()
    @     0x7f6ff99aae0f  yb::Thread::SuperviseThread()
    @     0x7f6ff5372694  start_thread
    @     0x7f6ff4aaf41d  __clone
    @              (nil)  (unknown)
- - -
After using the first command I got the server running:
'$ ./bin/yb-ctl status'
----------------------------------------------------------------------------------------------------
| Node Count: 1 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/cqlsh                                                                  |
| YEDIS Shell         : bin/redis-cli                                                              |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/me/yugabyte-data                                           |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 1: yb-tserver (pid 23638), yb-master (pid 23635)                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/cqlsh                                                                  |
| YEDIS Shell         : bin/redis-cli                                                              |
| data-dir[0]         : /home/me/yugabyte-data/node-1/disk-1/yb-data                     |
| yb-tserver Logs     : /home/me/yugabyte-data/node-1/disk-1/yb-data/tserver/logs        |
| yb-master Logs      : /home/me/yugabyte-data/node-1/disk-1/yb-data/master/logs         |
----------------------------------------------------------------------------------------------------

Then I turned on the Hasura docker container:
First it couldn't connect to any port like yesterday, see attached logs.
[hasura.txt](https://github.com/yugabyte/yugabyte-db/files/4172684/hasura.txt)
I needed to remove the exited docker container and run it again. 
After that I went to http://localhost:8080/console and I got connected.
The trouble is, I could create all tables I wanted to create for now and it worked without any errors, see screen shot:
![Screenshot from 2020-02-07 20-53-38](https://user-images.githubusercontent.com/47945633/74061325-14e6c900-49ec-11ea-8070-c6dea254bd38.png)

Even when I tried to simulate an error, it still worked, see screen shot:
![Screenshot from 2020-02-07 20-19-16](https://user-images.githubusercontent.com/47945633/74061370-29c35c80-49ec-11ea-9757-74f2c7434e83.png)

Tomorrow I will try to repeat the test without any flag running YugaByte like today, I mean without docker.

**Comment by rkarthik007** [comment] 2020-02-07 20:06
Adding @nchandrappa since he has run Hasura on top of YugabyteDB as well.

**Comment by virtenv** [comment] 2020-02-09 00:28
As I wrote before, I didn't use any flag now to create my database and used Hasura to create my tables. After creating them I stopped Hasura using '$ sudo docker-compose down' and I run '$ ./bin/yb-ctl restart' to retry the processes. I wasn't able to start the yb-master server because of the following error:
---
Log file created at: 2020/02/09 00:14:10
Running on machine: localhost.localdomain
Application fingerprint: version 2.0.11.0 build 23 revision 2d52e1dfef65294a0ddf7c6377e3da2b8ed5a6b0 build_type RELEASE built at 24 Jan 2020 17:54:53 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0209 00:14:10.056598 36726 log_util.cc:211] Could not read footer for segment: /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000003: Not found (yb/consensus/log_util.cc:446): Footer not found. Footer magic doesn't match
W0209 00:14:10.056694 36726 log_reader.cc:182] T 00000000000000000000000000000000 P 5b4754ad4cde47a48edb4ca4a4c32c61: Log segment /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000003 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0209 00:14:10.110066 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.111776 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.112828 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.124322 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.150347 36726 log_util.cc:211] Could not read footer for segment: /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000004: Not found (yb/consensus/log_util.cc:446): Footer not found. Footer magic doesn't match
W0209 00:14:10.150390 36726 log_reader.cc:182] T 00000000000000000000000000000000 P 5b4754ad4cde47a48edb4ca4a4c32c61: Log segment /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000004 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0209 00:14:10.164306 36726 log_util.cc:211] Could not read footer for segment: /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000005: Not found (yb/consensus/log_util.cc:446): Footer not found. Footer magic doesn't match
W0209 00:14:10.164361 36726 log_reader.cc:182] T 00000000000000000000000000000000 P 5b4754ad4cde47a48edb4ca4a4c32c61: Log segment /home/users/me/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000005 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0209 00:14:10.298408 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.299266 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.335705 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.545781 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.546563 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.583065 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.685986 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.686554 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.709513 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.781999 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.893638 36767 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
W0209 00:14:10.905941 36745 master_service.cc:108] Could not set master raft config : Illegal state (yb/master/catalog_manager.cc:6156): Node 5b4754ad4cde47a48edb4ca4a4c32c61 peer not initialized.
---
I mean
http://localhost:7000 works
http://localhost:9000 doesn't work

**Comment by virtenv** [comment] 2020-02-14 23:04
Hi everybody,
I cannot give you more details. As workaround I installed Hasura and PostgreSQL using https://raw.githubusercontent.com/hasura/graphql-engine/master/install-manifests/docker-compose/docker-compose.yaml
Now the services work for me. If you cannot reproduce the issues mentioned above, feel free to close my ticket.

**Comment by ddorian** [comment] 2020-03-12 15:00
closing as can't reproduce

**Closed by ddorian** 2020-03-12 15:00 UTC
Labels: area/docdb, community/request
