### ISSUE TITLE
[YSQL] Dirty reads may occur for serializable transactions + prepared statements

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#14370] opened 2022-10-07 09:21 UTC
Jira Link: [DB-3793](https://yugabyte.atlassian.net/browse/DB-3793)
### Description

Issue is easily reproduced on local environment w/o any restarts and nemesis. It depends on write threads, difference with Jepsen test is that here we have 2x more threads.
Reproduced on latest master code (~2.15.4.0-b72)

Simple bank workload code:
[SqlBankTransferSimple.java.zip](https://github.com/yugabyte/yugabyte-db/files/9732918/SqlBankTransferSimple.java.zip)

Sample apps with SqlBankTransferSimple workload:
[yb-sample-apps.jar.zip](https://github.com/yugabyte/yugabyte-db/files/9732920/yb-sample-apps.jar.zip)

Launch command:
```
--workload SqlBankTransferSimple 
--nodes 127.0.0.1:5433 
--num_threads_write 50 
--num_threads_read 20 
--num_writes -1 
--num_reads -1 
--bank_enable_logging true
 --bank_exit_on_fail true 
--bank_number_of_accounts 20 
--bank_transaction_type 8 
--bank_rollback_percentage 20
```

[DB-3793]: https://yugabyte.atlassian.net/browse/DB-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by qvad** [comment] 2022-10-07 09:56
Looks like it's not related to indexes, explain shows that it's sequential scans.

```
EXPLAIN SELECT id, balance FROM %s order by id;
Sort  (cost=149.83..152.33 rows=1000 width=8)
  Sort Key: id
  ->  Seq Scan on bankaccounts  (cost=0.00..100.00 rows=1000 width=8)
```

**Comment by qvad** [comment] 2022-10-11 09:32
Same workload evaluated against Postgres 12 doesn't fail in 30 minutes, will update this comment is there is a test failure

**Comment by pkj415** [comment] 2023-02-03 08:34
This seems to be a non-issue -- I have confirmed that the dirty read is seen in an aborted read transaction, not a committed one. And the sum can be different in an aborted transaction (will explain below how).

I confirmed this by changing the `doRead()` and `getSum()` functions in the SqlBankTransferSimple.java file as follows -

```
public class Pair { 
        public final int sum;
        public final int num_rows_read;

        public Pair(int sum, int num_rows_read) {
            this.sum = sum;
            this.num_rows_read = num_rows_read;
        }
    }

    @Override
    public long doRead() {
        Integer currentSum = null;
        Pair p = new Pair(0,0);
        String error = "";
        // appConfig.bankTransactionType
        try (Connection connection = getPostgresConnection()) {
            connection.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            connection.setAutoCommit(false);
            String committed = "";
            Integer numRowsRead = 0;
            try (Statement statement = connection.createStatement()) {
                p = getSum(statement);
                connection.commit();
                committed = "C";
            } catch (Exception e) {
                error = e.getMessage();
                if (connection != null) {
                    try {
                        connection.rollback();
                        committed = "R";
                    } catch (SQLException ex) {
                        LOG.error("Failed to rollback failed transaction", ex);
                    }
                }
            } finally {
                if (appConfig.bankEnableLogging) {
                    committed += p.sum + ", " + p.num_rows_read + ", " + error;

                    try (Connection historyConnection = getPostgresConnection();
                         Statement historyStatement = historyConnection.createStatement()) {
                        historyStatement.executeUpdate(String.format("INSERT INTO BankHistory_%s(committed, op, accFrom, accTo, balance) VALUES ('%s', '%s', %s, %s, %s)",
                                getTableName(), committed, "READ", 0, 0, p.sum));
                    }
                }

                if (committed == "C" && p.sum != sum && appConfig.bankExitOnFail) {
                    LOG.error(String.format("Failed to compare sums: expected %s - actual %s ", sum, p.sum));

                    stopApp();
                }
            }
        } catch (Exception e) {
            return 0;
        }

        return 1;
    }

    private Pair getSum(Statement statement) throws SQLException {
        statement.execute(String.format("SELECT id, balance FROM %s order by id;",
                getTableName()));

        int sum = 0;
        int num_rows_read = 0;
        try (ResultSet rs = statement.getResultSet()) {
            while (rs.next()) {
                sum += rs.getInt(2);
                num_rows_read += 1;
            }
        }

        return new Pair(sum, num_rows_read);
    }
```

After running this with modified function, performing a `select committed from BankHistory_bankaccounts where op='READ' ;`shows that the sum is inconsistent only in read transactions that couldn't commit (whose`committed` field starts with 'R'). The details after C/ R are in the format - `read sum, number of accounts read, error`. There are no entries of the form `C...` where the sum is different, implying that the sum is always consistent in case of a committed transaction.

Now coming to the scenario of how the sum can be inconsistent in an aborted transaction -
1. Assume the transaction that reads the balances is T1 and there is a concurrent transaction T2 that moves a balance of 10 from account A to B. Both transactions run in SERIALIZABLE isolation level. Also assume that the table has 2 tablets tablet1 and tablet2. Further assume that account A resides in tablet2 and account B resides in tablet1.
2. Assume that the initial balances of A and B are 100.
3. T1 performs a read rpc to fetch balances from tablet1. It finds a balance of 100 in account B.
4. T2 performs a decrement on account A in tablet2. It then performs an increment on account B in tablet1. This increment will conflict with the read already performed by T1 on tablet1. Assume that T2 has a higher priority assigned and hence it aborts transaction T1 when updating account B on tablet1. T2 then commits.
5. Even though T2 aborted T1, it could so happen that the query layer is yet to learn that that T1 has been aborted. So, T1 might send a read rpc to tablet2 and read the new balance for account A (which is already committed and hence there is no conflict).
6. T1 finally returns the old balance for account B but new balance for account A. But the transaction T1 was aborted, so that transaction can't commit in future.

**Closed by pkj415** 2023-02-03 08:34 UTC
Labels: kind/bug, area/ysql, priority/medium
