### ISSUE TITLE
[TabletSplitting] Automatic tablet splitting is misbehaving

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#11418] opened 2022-02-10 12:37 UTC
**Scenario1**:
If user creates a table and index(regular) it works well(splitting happens for table and index)  If user deletes the table and create other table(different name with same schema) and index(different name) it fails to split tablets for table (splitting is working for index)

**Steps**:
1. `./bin/yb-ctl --rf 3 create --master_flags "enable_automatic_tablet_splitting=true,tablet_split_low_phase_size_threshold_bytes=13421,tablet_split_low_phase_shard_count_per_node=16,outstanding_tablet_split_limit=5" --tserver_flags "yb_num_shards_per_tserver=1"`
2. `./bin/ysqlsh and execute:`

```
create table employees(id int primary key, name text, description text);
create index idx1 on employees(description ASC);
```
3. Validate tablets count for both table and index
4. Run `./collect_insert_data.py`
5. `./bin/ysqlsh -f sql_data.sql`
6. Wait for the data to be loaded
7. Validate tablets for both table and index - **Actual**: tablet count increases(for both table and index) compared to Step:3
8. Run `./bin/ysqlsh` and execute: 
```
delete table employees;
create table emp(id int primary key, name text, description text);
create index emp_idx on emp(description ASC);
```
9. Validate tablets count for both table and index
10. Update table name(emp) in collect_insert_data.py file 
11. Run `./collect_insert_data.py`
12. `./bin/ysqlsh -f sql_data.sql`
13. Wait for the data to be loaded
14. Validate tablets for both table and index - **Actual**: tablet count increases for index and it remains same for table compared to Step:9

**Scenario-2:**
Observed if tablets got split for one table and its related index, then splitting is not happening for other tables which are created after splitting is happened for first table.
**Steps**:
1. `./bin/yb-ctl --rf 3 create --master_flags "enable_automatic_tablet_splitting=true,tablet_split_low_phase_size_threshold_bytes=13421,tablet_split_low_phase_shard_count_per_node=16,outstanding_tablet_split_limit=5" --tserver_flags "yb_num_shards_per_tserver=1"`
2. `./bin/ysqlsh` and execute:

```
create table employees(id int primary key, name text, description text);
create index idx1 on employees(description ASC);
```
3. Validate tablets count for both table and index
4. Run `./collect_insert_data.py`
5. `./bin/ysqlsh -f sql_data.sql`
6. Wait for the data to be loaded
7. Validate tablets for both table and index - **Actual**: tablet count increases(for both table and index) compared to Step:3
8. Create another table with same schema
Run `./bin/ysqlsh` and execute: 
```
create table emp(id int primary key, name text, description text);
create index emp_idx on emp(description ASC);
```
9. Validate tablets count for both table and index
10. Update table name(emp) in collect_insert_data.py file 
11. Run ` ./collect_insert_data.py`
12. `./bin/ysqlsh -f sql_data.sql`
13. Wait for the data to be loaded
14. Validate tablets for both table and index - **Actual**: tablet count remains same as in Step:9

[collect_insert_data.txt](https://github.com/yugabyte/yugabyte-db/files/8040986/collect_insert_data.txt)

Move this file to collect_insert_data.py and execute.

**Comment by Arjun-yb** [comment] 2022-02-11 16:13
Validated with **`2.11.3.0-b126`**
Scenario1 is working as expected - Splitting is happening in both cases(mentioned in above scenario1)
Scenario2 is reproducible.

**Comment by bmatican** [comment] 2022-02-14 22:01
@SrivastavaAnubhav investigated this and we realized the problem and filed https://github.com/yugabyte/yugabyte-db/issues/11461 for this. @arybochkin will be working on that.

**Comment by rthallamko3** [comment] 2022-05-11 17:14
Closing as duplicate of #11461.

**Closed by rthallamko3** 2022-05-11 17:14 UTC
Labels: area/docdb
