### ISSUE TITLE
[Docs] Missing CREATE TABLESPACE statement [YSQL]

### ISSUE THREAD

**Issue by droberts-yb** [yugabyte/yugabyte-db#17815] opened 2023-06-16 17:21 UTC
### Description

There does not appear to be a reference to the CREATE TABLESPACE statement that details all the geo-placement options

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by deeps1991** [comment] 2023-06-16 22:21
Duplicate of #13614

**Closed by deeps1991** 2023-06-16 22:21 UTC
Labels: area/documentation
