### ISSUE TITLE
[YSQL] Invalid attnum for INTERSECT queries with range conditions on secondary columns with partial HASH indexes 

### ISSUE THREAD

**Issue by Navaratna-yb** [yugabyte/yugabyte-db#23104] opened 2024-07-03 05:11 UTC
Jira Link: [DB-12037](https://yugabyte.atlassian.net/browse/DB-12037)
### Description

When the INTERSECT query was executed with the following flags set in tserver -
ysql_pg_conf_csv="enable_seqscan=false,enable_indexscan=false,yb_enable_bitmapscan=true",
it aborted throwing the following error - 
```
ERROR:  invalid attnum 15 for relation "*SELECT* 1"
```
Query used - 
```
/*+ BitmapScan(bitmapscan_test_table_1) */ EXPLAIN
                 (ANALYZE, COSTS OFF, SUMMARY OFF)
                 SELECT id, name, age, details
                 FROM bitmapscan_test_table_1 t1 WHERE age < 25
                 INTERSECT
                 SELECT id, name, age, details
                 FROM bitmapscan_test_table_1 t2 WHERE val = 1;
``` 
DMLs and DDLS mentioned in the JIRA Ticket.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12037]: https://yugabyte.atlassian.net/browse/DB-12037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment] 2024-08-26 20:57
Looks like a duplicate of #22533 
```
yugabyte=# EXPLAIN (COSTS OFF) SELECT age FROM test_intersect_att WHERE age < 25 INTERSECT SELECT age FROM test_intersect_att WHERE age < 25;
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 HashSetOp Intersect
   ->  Append
         ->  Subquery Scan on "*SELECT* 1"
               ->  Index Scan using tia_partial on test_intersect_att
                     Storage Index Filter: (age < 25)
         ->  Subquery Scan on "*SELECT* 2"
               ->  Index Scan using tia_partial on test_intersect_att test_intersect_att_1
                     Storage Index Filter: (age < 25)
(8 rows)
```
There are Index Scans with a Storage Index Filter in a subquery.

**Closed by andrei-mart** 2024-08-26 20:57 UTC
Labels: kind/bug, area/ysql, priority/medium
