### ISSUE TITLE
[DocDB] Backup/restore fails on colocated database due to schema packing issue

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#15966] opened 2023-02-03 10:26 UTC
Jira Link: [DB-5376](https://yugabyte.atlassian.net/browse/DB-5376)
### Description

Create one rf=1 cluster without specifying any packed_row flag.
```
./bin/yb-ctl destroy && ./bin/yb-ctl create && ./bin/yb-ctl start && ./bin/ysqlsh
```

Repro
```
create database qqq with colocation = true;
\c qqq
create table tbl (k int, v int);
create index on tbl(k);
drop table tbl;
create table tbl (k int, v int);
create table tbl3 (k int, v int, v2 text);
create unique index idx2 on tbl3(v2);
create index idx on tbl3(v);
alter table tbl3 add primary key (k);

backup && restore:
./managed/devops/bin/yb_backup.py --masters 127.0.0.1 --remote_yb_admin_binary ./build/latest/bin/yb-admin --remote_ysql_dump_binary ./build/latest/postgres/bin/ysql_dump --remote_ysql_shell_binary ./build/latest/postgres/bin/ysqlsh --no_ssh --storage_type nfs --nfs_storage_path ~/yugabyte-data --backup_location ~/bug_repro/ --no_auto_name --keyspace ysql.qqq --verbose create

recreate a fresh cluster

./managed/devops/bin/yb_backup.py --masters 127.0.0.1 --remote_yb_admin_binary ./build/latest/bin/yb-admin --remote_ysql_dump_binary ./build/latest/postgres/bin/ysql_dump --remote_ysql_shell_binary ./build/latest/postgres/bin/ysqlsh --no_ssh --storage_type nfs --nfs_storage_path ~/yugabyte-data --backup_location ~/bug_repro/ --no_auto_name --keyspace ysql.qqq --verbose restore
```

The restore process cannot finish.
```
2023-02-03 10:24:27,995 INFO: Waiting for snapshot restoring to complete...
```

And tserver has fatal error: 
```
F0203 10:23:56.669042 12390 tablet_metadata.cc:241] TBL 00004000000030008000000000004006 T 498513c0ad4b4efdb9ddbbcf5e389644 P ca6f5d18a3484ff3be9f41356b5065fc: After merging schema packings during restore, latest schema does not have the same packing as the corresponding latest packing for table 00004000000030008000000000004006
```.

[DB-5376]: https://yugabyte.atlassian.net/browse/DB-5376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment] 2023-02-03 23:06
Sounds like a duplicate of https://github.com/yugabyte/yugabyte-db/issues/14861.
@sanketkedia can you confirm this is one duplicate issue?

**Comment by bmatican** [comment] 2023-02-03 23:29
cc @lingamsandeep but yes, as I understand it, packed + colocation + backup/restore has an issue now with schema packing

that being said, that's why we've disabled packed for colocation, even if you turn it on! so @yifanguan can you confirm if you had explicitly turned packed on for this?

**Comment by lingamsandeep** [comment] 2023-02-04 00:05
@msun07 is looking into fixing this. This is indeed a duplicate of https://github.com/yugabyte/yugabyte-db/issues/14861. I am assuming you turned ON packed for colocated using the 2 GFlags.

**Comment by yifanguan** [comment] 2023-02-04 00:28
@bmatican @lingamsandeep Just repro the issue again.
I create an rf=1 cluster without specifying any packed_row flag.
```
./bin/yb-ctl destroy && ./bin/yb-ctl create && ./bin/yb-ctl start && ./bin/ysqlsh
```

**Comment by druzac** [comment] 2023-02-27 17:38
The expected behaviour in this case - doing a restore of a colocated database - is that the new logic added to the restore path to deal with schema packings shouldn't be triggered. That logic is only intended to handle the non-colocated case for now until we resolve https://github.com/yugabyte/yugabyte-db/issues/14861.

Unfortunately, this example reliably generates a `table_id` collision between the source and target clusters. In the cluster we perform a backup against, `tbl` has `table_id` `00004000000030008000000000004006`. In the new cluster we perform the restore against, `idx2` has `table_id` `00004000000030008000000000004006`. Note there are the same.

This collision causes the loop here to sail through and we try to merge the schema packings for `tbl` into `idx2`. Given the schemas are incompatible for these two tables it's not surprising this operation fails.

**Closed** 2023-03-21 14:58 UTC
Labels: kind/bug, area/docdb, priority/medium
