### ISSUE TITLE
[DocDB] Confusing raft follower log reporting large Time left

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#15848] opened 2023-01-26 20:57 UTC
Jira Link: [DB-5244](https://yugabyte.atlassian.net/browse/DB-5244)
### Description

> Denying vote to candidate 39b2ed50714949ca86a8ade8b80fd507 for term 28 because replica is either leader or believes a valid leader to be alive. Time left: 9159865424.354s

The `Time left` part of the log comes from
>  withhold_votes_until_.load(std::memory_order_acquire) - MonoTime::Now());

But on followers, `withhold_votes_until_` is defaulted to `MonoTime::Min`
```
  // Now that we're a replica, we can allow voting for other nodes.
  withhold_votes_until_.store(MonoTime::Min(), std::memory_order_release);
```

This leads to confusion when reading logs.

[DB-5244]: https://yugabyte.atlassian.net/browse/DB-5244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment] 2023-02-03 20:39
```cpp
Status RaftConsensus::BecomeLeaderUnlocked() {
  DCHECK(state_->IsLocked());
  TRACE_EVENT2("consensus", "RaftConsensus::BecomeLeaderUnlocked",
               "peer", peer_uuid(),
               "tablet", tablet_id());
  LOG_WITH_PREFIX(INFO) << "Becoming Leader. State: " << state_->ToStringUnlocked();

  // Disable FD while we are leader.
  DisableFailureDetector();

  // Don't vote for anyone if we're a leader.
  withhold_votes_until_.store(MonoTime::Max(), std::memory_order_release);
```

If a peer becomes leader, it would set `withhold_votes_until_` to the max value.

This might not be an issue. cc @bmatican

**Comment by rthallamko3** [comment] 2023-03-09 21:23
Doesn't seem to be a real bug, the Max() value on the leader is by design. Closing it for now.

**Closed by rthallamko3** 2023-03-09 21:23 UTC
Labels: kind/enhancement, area/docdb, priority/low
