### ISSUE TITLE
[YSQL] Low TPS when I use sysbench to benchmark yugabytedb.

### ISSUE THREAD

**Issue by Franzli9467** [yugabyte/yugabyte-db#23585] opened 2024-08-22 02:38 UTC
Jira Link: [DB-12503](https://yugabyte.atlassian.net/browse/DB-12503)
### Description

When I use sysbench to benchmark test yugabytedb, the tps is very low.
There are 10 tables, each with 1 million records.
Three-node cluster, each node configured with CPU as E5-2630 v4 and 128GB memory.
For oltp_read_write, the tps is only single digits.
For oltp_read_only, the tps is also only single digits.
For oltp_write_only, the tps can reach 5000+.
How can I improve the tps for oltp_read_write, or is this a bug in yugabytedb?

### Issue Type

kind/question

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12503]: https://yugabyte.atlassian.net/browse/DB-12503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Franzli9467** [comment] 2024-08-23 09:51
I figured out the reason for the low TPS query. By default, sysbench table creation is hash partitioned. Under hash partitioning, range queries will become full table scans. When I changed the table creation statement to range partitioning, performance improved. Is this a bug in hash partitioning?

**Comment by ddorian** [comment] 2024-09-02 07:08
Closing as duplicate of https://forum.yugabyte.com/t/low-tps-when-i-use-sysbench-to-benchmark-yugabytedb/2843/5

**Closed by ddorian** 2024-09-02 07:08 UTC
Labels: kind/question, area/ysql, priority/medium, status/awaiting-triage
