### ISSUE TITLE
Foreign Key insertion crashes postgres process

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2747] opened 2019-10-28 17:18 UTC
Seeing this on master where inserting data into a table with foreign key reference crashes postgres. To repro:
```
create table pk(a int primary key);
create table fk(a int primary key, b int references pk(a));
insert into pk values (1);
insert into fk values (1,1);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Stack trace logged:
```
*** Check failure stack trace: ***                                                                   
    @        0x1104e37b2  google::LogMessage::SendToLog()                                            
    @        0x1104e3eb5  google::LogMessage::Flush()                                                
    @        0x1104e3fa2  google::LogMessage::~LogMessage()                                          
    @        0x10d0afada  yb::client::YBTransaction::Impl::Flushed()                                 
    @        0x10d01c8f2  yb::client::internal::Batcher::RemoveInFlightOpsAfterFlushing()            
    @        0x10d00ef8c  yb::client::internal::AsyncRpc::Finished()                                 
    @        0x10d018a7c  _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRNS_6__bindIMN2yb6client8internal8AsyncRpcEFvRKNS4_6StatusEEJPNS6_7ReadRpcENS8_2OKEEEEEEEvDpOT_
    @        0x10e2126e5  yb::rpc::OutboundCall::InvokeCallbackSync()                                
    @        0x10e2693a0  yb::rpc::(anonymous namespace)::Worker::Execute()                          
    @        0x10f58be1e  yb::Thread::SuperviseThread()                                              
    @     0x7fff5706c661  _pthread_body                                                              
    @     0x7fff5706c50d  _pthread_start                                                             
    @     0x7fff5706bbf9  thread_start                                                               
2019-10-28 09:46:34.263 PDT [49332] LOG:  server process (PID 72276) was terminated by signal 6: Abort trap
```

**Comment by hectorgcr** [comment] 2019-10-29 22:07
This is a known issue:
```F20191029 22:05:28 ../../src/yb/client/transaction.cc:250] 2f38718c-efb5-47dc-b8bc-adaa8860ff29: Read time already picked ({ read: { physical: 1572386728089127 } local_limit: { physical: 1572386728139127 } globa\
l_limit: { physical: 1572386728139127 } in_txn_limit: { physical: 1572386728190147 } serial_no: 0 }, but server replied with used read time: { read: { physical: 1572386728192087 } local_limit: { physical: 157238\
6728242091 } global_limit: { physical: 1572386728242091 } in_txn_limit: <max> serial_no: 0 }                                                                                                                        
    @     0x7f7a820e34f0  yb::LogFatalHandlerSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long) (src/yb/util/logging.cc:474)                                                     
    @     0x7f7a80922e15                                                                                                                                                                                            
    @     0x7f7a80920509                                                                                                                                                                                            
    @     0x7f7a80920740                                                                                                                                                                                            
    @     0x7f7a805caa60  yb::client::YBTransaction::Impl::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybrid\
Time const&, yb::Status const&) (src/yb/client/transaction.cc:250)                                                                                                                                                  
    @     0x7f7a805c10ac  yb::client::YBTransaction::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybridTime c\
onst&, yb::Status const&) (src/yb/client/transaction.cc:871)                                                                                                                                                        
    @     0x7f7a8052e6b8  yb::client::internal::Batcher::RemoveInFlightOpsAfterFlushing(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > c\
onst&, yb::Status const&, yb::client::internal::FlushExtraResult) (src/yb/client/batcher.cc:641)                                                                                                                    
    @     0x7f7a8051e01b  yb::client::internal::AsyncRpc::Finished(yb::Status const&) (src/yb/client/async_rpc.cc:167)                                                                                              
    @     0x7f7a8052586e                                                                                                                                                                                            
    @     0x7f7a7fd379e7  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)                                                                                                
    @     0x7f7a7fd379e7  yb::rpc::OutboundCall::InvokeCallbackSync() (src/yb/rpc/outbound_call.cc:384)                                                                                                             
    @     0x7f7a7fd37cbe  yb::rpc::InvokeCallbackTask::Run() (src/yb/rpc/outbound_call.cc:165)                                                                                                                      
    @     0x7f7a7fd915c6  Execute (src/yb/rpc/thread_pool.cc:99)                                                                                                                                                    
    @     0x7f7a7fd8cfee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:600)                                                                                                                         
    @     0x7f7a7fd8cfee  __call<void, 0ul> (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)                                                                                                                         
    @     0x7f7a7fd8cfee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)                                                                                                                        
    @     0x7f7a7fd8cfee  _M_invoke (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)                                                                                                                                 
    @     0x7f7a821666b4  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)                                                                                                
    @     0x7f7a821666b4  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:741)```

Duplicate of #2780

**Closed** 2020-02-07 06:00 UTC
Labels: area/sql, kind/bug, priority/high
