### ISSUE TITLE
[Platform]- Allow configure replication using cluster, schema and tablenames

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#8965] opened 2021-06-17 17:56 UTC
Feature Request:

Description:

Currently, in Platform, if the User wants to Configure replication, they have to use "UUID." 

Suggested Solution:

Instead of "UUID," it will be easy to do it by active cluster, schema, or table name.

Reference Ticket:#1342

**Comment by ymahajan** [comment] 2021-06-18 20:45
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/8963

**Closed by ymahajan** 2021-06-18 20:45 UTC
Labels: area/platform
