### ISSUE TITLE
[SDYB] Spring Data YugabyteDB fails to start up on older versiond of YBDB < 2.7.2.0

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yugabyte-db#9742] opened 2021-08-16 20:21 UTC
When attempting to run a Spring Data Yugabyte application against 2.7.1.1 (and probably older), I get this error during startup of the application:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception; nested exception is org.springframework.jdbc.BadSqlGrammarException: ConnectionCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: function yb_servers() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
...
Caused by: org.springframework.jdbc.BadSqlGrammarException: ConnectionCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: function yb_servers() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
...
Caused by: org.postgresql.util.PSQLException: ERROR: function yb_servers() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
```

It looks like the datasource setup is looking for a specific function on the systems database `yb_servers()` that does not exist on older versions.  My example application is here: https://github.com/ssherwood/spring-petclinic-data-jdbc/tree/s1p2021

**Comment by nchandrappa** [comment] 2021-08-30 11:00
The issue is fixed with the following [commit](https://github.com/yugabyte/spring-data-yugabytedb/commit/25ece4f86f58976dab97f53fb34bbbee887fbe9a).

**Closed by nchandrappa** 2021-08-30 11:00 UTC
