### ISSUE TITLE
[YSQL] Unit test: testPgMemoryGcOrderBy is failing

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#17774] opened 2023-06-14 13:30 UTC
Jira Link: [DB-6868](https://yugabyte.atlassian.net/browse/DB-6868)
### Description

**Test**: TestPgMemoryGC.testPgMemoryGcOrderBy
**ERROR**: `java.lang.AssertionError: Freed bytes should be recycled when GC threshold is reached`

Stability link: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgMemoryGC&fail_tag=all&name=testPgMemoryGcOrderBy&platform=linux

Jenkins: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release/1677/testReport/junit/org.yb.pgsql/TestPgMemoryGC/testPgMemoryGcOrderBy/

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6868]: https://yugabyte.atlassian.net/browse/DB-6868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment] 2023-07-10 12:26
Duplicate of #17821

**Closed by timothy-e** 2023-07-10 12:26 UTC
Labels: kind/bug, area/ysql, kind/failing-test, priority/medium
