### ISSUE TITLE
Thread Sanitizer Check Failure in DeleteTableTest_TestMergeConsensusMetadata

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14242] opened 2022-09-29 04:38 UTC
Jira Link: [DB-3701](https://yugabyte.atlassian.net/browse/DB-3701)
### Description

Thread Sanitizer Check Failure in DeleteTableTest_TestMergeConsensusMetadata in latest master- 2.15.4.0-b40
Stacktrace- https://gist.github.com/kripasreenivasan/d24e5f245d14a6695816c4b02106a504

**Comment by bmatican** [comment] 2022-09-29 14:14
Duplicate of #14098

**Closed by bmatican** 2022-09-29 14:14 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage, qa_automation
