### ISSUE TITLE
[YSQL] Import pg_partman extension

### ISSUE THREAD

**Issue by averyshum62** [yugabyte/yugabyte-db#13083] opened 2022-06-28 18:03 UTC
Jira Link: [DB-2797](https://yugabyte.atlassian.net/browse/DB-2797)
### Description

The pg_partman extension is not supported by Yugabyte (https://github.com/pgpartman/pg_partman).

pg_partman is an extension to create and manage both time-based and serial-based table partition sets.

**Comment by adil246** [comment] 2022-07-19 21:49
@averyshum62 This is a similar request opened earlier by Sushant. 

https://github.com/yugabyte/yugabyte-db/issues/11087

**Comment by adil246** [comment] 2022-07-19 23:46
I'm closing this issue since it's a duplicate of https://github.com/yugabyte/yugabyte-db/issues/11087

**Closed** 2024-07-10 15:56 UTC
Labels: kind/enhancement, area/ysql, priority/medium
