### ISSUE TITLE
[YSQL] YugabyteDB returns a wrong record with a ORDER clause that shouldn't be returned

### ISSUE THREAD

**Issue by komamitsu** [yugabyte/yugabyte-db#22140] opened 2024-04-25 09:15 UTC
Jira Link: [DB-11068](https://yugabyte.atlassian.net/browse/DB-11068)
### Description

I'm evaluating YugabyteDB v2.21 and facing a bug that returns a wrong record with a ORDER clause.

```
$ psql -h localhost -p 5433 -U yugabyte
psql (14.11 (Homebrew), server 11.2-YB-2.21.0.0-b0)
Type "help" for help.

yugabyte=# \d "int_test_storage_mul_ckey_BOOLEAN"."BOOLEAN_DESC_BOOLEAN_ASC"
Table "int_test_storage_mul_ckey_BOOLEAN.BOOLEAN_DESC_BOOLEAN_ASC"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 pkey   | integer |           | not null | 
 ckey1  | boolean |           | not null | 
 ckey2  | boolean |           | not null | 
 col    | integer |           |          | 
Indexes:
    "BOOLEAN_DESC_BOOLEAN_ASC_pkey" PRIMARY KEY, lsm (pkey HASH, ckey1 ASC, ckey2 ASC)
    "int_test_storage_mul_ckey_BOOLEAN.BOOLEAN_DESC_BOOLEAN_ASC_clus" UNIQUE, lsm (pkey ASC, ckey1 DESC, ckey2 ASC)

yugabyte=# SELECT * FROM "int_test_storage_mul_ckey_BOOLEAN"."BOOLEAN_DESC_BOOLEAN_ASC";
 pkey | ckey1 | ckey2 | col 
------+-------+-------+-----
    1 | f     | f     |   1
    1 | f     | t     |   1
    1 | t     | f     |   1
    1 | t     | t     |   1
(4 rows)

yugabyte=# SELECT * FROM "int_test_storage_mul_ckey_BOOLEAN"."BOOLEAN_DESC_BOOLEAN_ASC" WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false;
 pkey | ckey1 | ckey2 | col 
------+-------+-------+-----
(0 rows)           <<<<<<<<<<<<<< Correct

yugabyte=# SELECT * FROM "int_test_storage_mul_ckey_BOOLEAN"."BOOLEAN_DESC_BOOLEAN_ASC" WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false ORDER BY "ckey1" ASC,"ckey2" DESC;
 pkey | ckey1 | ckey2 | col 
------+-------+-------+-----
    1 | t     | f     |   1
(1 row)           <<<<<<<<<<<<<< Wrong
```

In the above case, with `ORDER BY "ckey1" ASC,"ckey2" DESC` YugabyteDB returns the wrong record while it expectedly returns no record w/o the ORDER clause.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11068]: https://yugabyte.atlassian.net/browse/DB-11068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment] 2024-04-25 09:43
Hi @komamitsu 

Thank you for the bug report. I could reproduce below. An eng from out team will look into it.

```sql
yugabyte=# create table mytest(pkey integer, ckey1 boolean, ckey2 boolean, col integer, PRIMARY KEY(pkey HASH, ckey1 ASC, ckey2 ASC));
yugabyte=# create index mytest_idx ON mytest(pkey ASC, ckey1 DESC, ckey2 ASC);             
yugabyte=# INSERT INTO mytest VALUES (1,false,false,1),(1,false,true,1),(1,true,false,1),(1,true,true,1);
yugabyte=# SELECT * FROM mytest WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false;                                               
 pkey | ckey1 | ckey2 | col 
------+-------+-------+-----
(0 rows)
yugabyte=# SELECT * FROM mytest WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false ORDER BY "ckey1" ASC,"ckey2" DESC;                                                                   
 pkey | ckey1 | ckey2 | col 
------+-------+-------+-----
    1 | t     | f     |   1
(1 row)
yugabyte=# explain SELECT * FROM mytest WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false;                                                                                                                                                                       
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Index Scan using mytest_pkey on mytest  (cost=0.00..15.75 rows=100 width=10)
   Index Cond: ((pkey = 1) AND (ckey2 > false) AND (ckey2 <= false))
   Remote Filter: ckey1
(3 rows)

yugabyte=# explain SELECT * FROM mytest WHERE "pkey"=1 AND "ckey1"=true AND "ckey2">false AND "ckey2"<=false ORDER BY "ckey1" ASC,"ckey2" DESC;
                                      QUERY PLAN                                      
--------------------------------------------------------------------------------------
 Index Scan Backward using mytest_idx on mytest  (cost=0.00..17.85 rows=100 width=10)
   Index Cond: ((pkey = 1) AND (ckey2 > false) AND (ckey2 <= false))
   Remote Index Filter: ckey1
(3 rows)

**Comment by ddorian** [comment] 2024-04-26 06:44
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/21383. It will be in the next release.

**Closed by ddorian** 2024-04-26 06:44 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
