### ISSUE TITLE
[YSQL] Performance is not Good: long_operation_tracker.cc:142] Read took a long time: 3.162s detected 

### ISSUE THREAD

**Issue by GiKyouGetsu** [yugabyte/yugabyte-db#12680] opened 2022-05-27 04:46 UTC
Jira Link: [DB-572](https://yugabyte.atlassian.net/browse/DB-572)
### Description

When I try to save many records(10 threads and more then 8000 records per thread) to yugabyte DB, I found the long_operation_tracker detect the read took a long time, the log like below :
```
W0527 04:24:37.828864 53709 log.cc:922] Time spent Fsync log took a long time: real 0.069s	user 0.001s	sys 0.000s
W0527 04:24:38.415030    18 log.cc:922] Time spent Fsync log took a long time: real 0.058s	user 0.000s	sys 0.001s
W0527 04:24:38.546056 53670 long_operation_tracker.cc:142] Read took a long time: 2.367s
W0527 04:24:38.639997   139 long_operation_tracker.cc:142] Read took a long time: 4.498s
I0527 04:24:38.942461    25 reactor.cc:459] TabletServer_R000: DEBUG: Closing idle connection: Connection (0x000000001e5566d0) server 10.44.0.0:60623 => 10.44.0.9:9100 - it has been idle for 65.088s
W0527 04:24:39.143821    98 long_operation_tracker.cc:113] Read running for 3.485s in thread 139:
    @     0x7f1610a7711f  (unknown)
    @     0x7f161eb0a860  yb::docdb::SubDocument::MoveFrom()
    @     0x7f161eb1708c  yb::docdb::(anonymous namespace)::ProcessSubDocument()
    @     0x7f161eb18d8b  yb::docdb::SubDocumentReader::Get()
    @     0x7f161ea93fb3  yb::docdb::DocDBTableReader::Get()
    @     0x7f161eabe14d  yb::docdb::DocRowwiseIterator::HasNext()
    @     0x7f161eae5db1  yb::docdb::PgsqlReadOperation::ExecuteScalar()
    @     0x7f161eae7e76  yb::docdb::PgsqlReadOperation::Execute()
    @     0x7f161fa56f62  yb::tablet::AbstractTablet::HandlePgsqlReadRequest()
    @     0x7f161fa8d1c8  yb::tablet::Tablet::HandlePgsqlReadRequest()
    @     0x7f1620406c75  yb::tserver::TabletServiceImpl::DoReadImpl()
    @     0x7f1620407d2b  yb::tserver::TabletServiceImpl::DoRead()
    @     0x7f1620408077  yb::tserver::TabletServiceImpl::CompleteRead()
    @     0x7f162040a11e  yb::tserver::TabletServiceImpl::Read()
    @     0x7f161cd93aa3  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7f1619dce0f8  yb::rpc::ServicePoolImpl::Handle()
W0527 04:24:39.328258 53707 long_operation_tracker.cc:142] Read took a long time: 3.162s
W0527 04:24:39.441066   129 long_operation_tracker.cc:142] Read took a long time: 3.281s
```
The records insert successful, but  slower than at my local postgres DB(take 123s), yugabyte in my server take more than 475 s,  here is my server metrices for yugabyte working node
```
top - 12:44:57 up 20:16,  1 user,  load average: 1.04, 2.10, 3.93
Tasks: 321 total,   1 running, 320 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.2 us,  7.6 sy,  0.0 ni, 83.7 id,  0.0 wa,  0.0 hi,  0.5 si,  0.0 st
KiB Mem : 41017992 total, 26951160 free,  7290872 used,  6775960 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 33379276 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                  
  8271 root      20   0   40.9g   2.6g  63972 S  32.0  6.6 400:45.63 yb-tserver                                                                                                                               
  1079 root      20   0 2336388 113644  40848 S  27.4  0.3 182:39.33 kubelet                                                                                                                                  
  8258 root      20   0 1626828 163212  40284 S  25.7  0.4 279:20.70 yb-tserver                                                                                                                               
  3056 root      20   0 1256524 454844  47916 S  20.8  1.1 146:52.04 kube-apiserver   
```
attached the log file
[yb-tserver-0.log](https://github.com/yugabyte/yugabyte-db/files/8783957/yb-tserver-0.log)

**Comment by ddorian** [comment] 2022-05-27 06:31
@GiKyouGetsu 

Can you describe your server(or cluster?) hardware? (vcpu, SSD, memory)

Can you describe your table schema + indexes?

How are you running the db? Just to know any custom settings you've may set?

**Comment by GiKyouGetsu** [comment] 2022-05-30 05:56
> @GiKyouGetsu
> 
> Can you describe your server(or cluster?) hardware? (vcpu, SSD, memory)
> 
> Can you describe your table schema + indexes?
> 
> How are you running the db? Just to know any custom settings you've may set?
### CPU:  
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
Stepping:              2
CPU MHz:               2933.437
BogoMIPS:              5866.87
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-3

### Using cat /sys/block/*/queue/rotational return 0, which is not SDD disk

### Memory info:              
total        used        free      shared  buff/cache   available
Mem:          31993         581       24588          19        6823       31165
Swap:             0           0           0

### Our table have 296 columns and without any primary key, but have two indexs

### we run yugabyte on kubernetes , which have one worker node, on master node, here is our configuration about yugabyte resource

  Containers:
   yb-tserver:
    Image:       ****
    Ports:       9000/TCP, 12000/TCP, 11000/TCP, 13000/TCP, 9100/TCP, 6379/TCP, 9042/TCP, 5433/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      exec /home/yugabyte/bin/yb-tserver \
        --fs_data_dirs=/mnt/disk0 \
        --tserver_master_addrs=yb-master-0.yb-masters.$(NAMESPACE).svc.cluster.local:7100 \
        --metric_node_name=$(HOSTNAME) \
        --memory_limit_hard_bytes=3649044480 \
        --stderrthreshold=0 \
        --num_cpus=1 \
        --undefok=num_cpus,enable_ysql \
        --use_node_hostname_for_local_tserver=true \
        --rpc_bind_addresses=0.0.0.0:9100 \
        --server_broadcast_addresses=$(HOSTNAME).$(NAMESPACE).svc.cluster.local:9100 \
        --webserver_interface=0.0.0.0 \
        --enable_ysql=true \
        --pgsql_proxy_bind_address=0.0.0.0:5433 \
        --cql_proxy_bind_address=0.0.0.0:9042
      
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:     500m
      memory:  512Mi
    Environment:
      POD_IP:      (v1:status.podIP)
      HOSTNAME:    (v1:metadata.name)
      NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /mnt/disk0 from datadir0 (rw)

**Comment by ddorian** [comment] 2022-05-30 07:06
> Using cat /sys/block/*/queue/rotational
> 
> return 0, which is not SDD disk

Is it SSD or HDD? Because HDD is not supported at this time.

Note that you should create a primary key for the table, otherwise a hidden one will be created.

You're also using very low hardware compared to our requirements: https://docs.yugabyte.com/preview/deploy/checklist/#hardware-requirements

**Comment by atomanV** [comment] 2022-05-30 10:23
Thanks @ddorian for your advice and comments. 
https://docs.yugabyte.com/preview/deploy/checklist/#hardware-requirements is mentioned SSD is requirement, but not strongly mentioned HDD is not supported. So is there any work-around to optimize the current situation? thanks a lot!

**Comment by ddorian** [comment] 2022-05-30 11:23
> is mentioned SSD is requirement, but not strongly mentioned HDD is not supported. So is there any work-around to optimize the current situation?

There is no workaround. You have to remove the HDD and add the required SSD.

**Comment by ddorian** [comment] 2022-06-02 11:28
Closing as "work as designed" for now. 
Please open a new issue if the problem persists with SSD drives.

**Closed by ddorian** 2022-06-02 11:28 UTC
Labels: kind/bug, area/ysql, priority/medium
