### ISSUE TITLE
YQL value too long INSERT INTO ybdemo.ugent(id, data) VALUES (?, ?) with overlong JSON data

### ISSUE THREAD

**Issue by zopyx** [yugabyte/yugabyte-db#2116] opened 2019-08-21 05:33 UTC
Inserting a JSON document larger than 7 MB or so using a prepared statement through yb-cassandra-python causes an internal loop of messages

```
E0821 04:49:58.241580 18126 process_context.cc:180] SQL Error: Invalid Arguments. YQL value too long
INSERT INTO ybdemo.ugent(id, data) VALUES (?, ?)
```

and does not cause a propagation of the error back to the Python client/driver

https://forum.yugabyte.com/t/insert-of-large-json-data-for-cassandra-driver-very-slow/469/17?u=zopyx

**Comment by kmuthukk** [comment] 2019-08-21 06:12
For the sample I tried, I was able to insert larger values - like 24MB JSONB -- but it had a single large field.

Perhaps, in your case, there are many more fields, and the internal representation exceeds some threshold, and you are getting  "YQL value too long" error.

Also, agreed that this error should be surfaced upstream to the program cleanly.

**Comment by zopyx** [comment] 2019-08-21 06:43
No, this happens with JSON with exactly one key

**Comment by OlegLoginov** [comment] 2019-08-23 15:26
@zopyx Please provide the used 7 MB value (or any similar) for testing purposes. Thanks!

**Comment by zopyx** [comment] 2019-08-23 15:29
Here is my script


```

import os
import json
import time
from cassandra.cluster import Cluster, ExecutionProfile

cluster = Cluster(['127.0.0.1'])
profile = ExecutionProfile()
profile.request_timeout = 5
cluster.add_execution_profile('standard', profile)
session = cluster.connect()
session.execute('CREATE KEYSPACE IF NOT EXISTS ybdemo;')

session.execute(
  """
  CREATE TABLE IF NOT EXISTS ybdemo.ugent (id int PRIMARY KEY,
                                           data jsonb);
  """)

st = session.prepare("INSERT INTO ybdemo.ugent(id, data) VALUES (?, ?)")

for i in range (0,100000):
    data = dict()
    for y in range(0, int(1.5**i)):
        data[y] = '**********'
    data = json.dumps(data, sort_keys=True)
    try:
        ts = time.time()                                        
        bound = st.bind((i, data))
        session.execute(bound, execution_profile=profile)
    except Exception as e:
        raise
    finally:
        print(len(data), time.time() - ts)
cluster.shutdown()

```

**Comment by zopyx** [comment] 2019-08-23 15:31
Oops...my initial claim is wrong...the data has a growing number of keys...not a single large key...anyway...the error must be propagated..yes, an artificial test.

**Comment by kmuthukk** [comment] 2019-08-23 15:42
hi @zopyx -- thx for updated input. Yes that makes more sense that for 7MB you had a different payload with a larger number of keys and somehow the internal representation was making it cross the 32MB limit. 

I agree that main/hi-pri issue is to cleanly catch the error and propagate to client.

**Comment by OlegLoginov** [comment] 2019-09-26 15:30
Root cause: the error code mapping: (value too long) Status::InvalidArgument -> ErrorCode::INVALID_ARGUMENTS -> ErrorCode::STALE_METADATA -> Code::UNPREPARED (YCQL error code). UNPREPARED code is retryable in the driver.
(In case of Python driver the retry loop is endless, so the user will never get the error message.)

Fix: the fixed error code mapping is: (value too long) Status::NotSupported -> ErrorCode::INVALID_REQUEST -> Code::INVALID (non-retryable YCQL error code).

**Comment by OlegLoginov** [comment] 2019-09-27 16:31
Fixed by the commmit above.

**Closed by OlegLoginov** 2019-09-27 16:31 UTC
Labels: community/request, kind/bug
