### ISSUE TITLE
[YSQL] ERROR:  XX000: invalid attnum, on EXPLAIN, with expression pushdown, and index scan

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#23638] opened 2024-08-26 21:26 UTC
Jira Link: [DB-12551](https://yugabyte.atlassian.net/browse/DB-12551)
### Description

Here is a case where we encounter `ERROR:  XX000: invalid attnum 9 for relation "customer"` except with hash join:

```
CREATE TABLE public.customer (
    c_custkey    INTEGER NOT NULL ,
    c_name       VARCHAR(255),
    c_address    VARCHAR(255),
    c_nationkey  INTEGER,
    c_phone      VARCHAR(20),
    c_acctbal    NUMERIC(12,2),
    c_mktsegment VARCHAR(10),
    c_comment    TEXT,
    PRIMARY KEY (c_custkey)
);
CREATE INDEX customer_c_custkey_idx ON public.customer USING lsm (c_custkey ASC);
CREATE TABLE public.orders (
    o_orderkey      INTEGER NOT NULL ,
    o_custkey       INTEGER NOT NULL,
    o_orderstatus   CHAR(1),
    o_totalprice    NUMERIC(12,2),
    o_orderdate     DATE,
    o_orderpriority CHAR(15),
    o_clerk         VARCHAR(15),
    o_shippriority  INTEGER,
    o_comment       TEXT,
    PRIMARY KEY (o_orderkey) ,
    CONSTRAINT orders_o_custkey_fkey FOREIGN KEY (o_custkey) REFERENCES public.customer(c_custkey)
);
CREATE INDEX orders_o_custkey_o_comment_idx ON public.orders USING lsm (o_custkey ASC, o_comment ASC);

set enable_hashjoin to off;

EXPLAIN
SELECT
      "orders per customer"."number of orders"
      AS "number of orders per customer"
     , COUNT(*)
       AS "number of customers"
FROM
        (
              SELECT
                     "customer".c_custkey
                      AS "customer"
                   , COUNT("customer order".o_orderkey)
                     AS "number of orders"
              FROM customer
                 AS "customer"
              LEFT OUTER JOIN orders
                AS "customer order"
              ON "customer".c_custkey
                      = "customer order".o_custkey
                AND "customer order".o_comment
                          NOT LIKE '%unusual%packages%'
              GROUP BY "customer".c_custkey
        )
  AS "orders per customer"
GROUP BY "number of orders"
ORDER BY
    "number of customers" DESC
  , "number of orders per customer" DESC
;

```
On 2024.1.1:
```
ERROR:  XX000: invalid attnum 9 for relation "customer"
LOCATION:  get_variable, ruleutils.c:6903

```

Disabling `yb_enable_expression_pushdown` works but with Filter instead of Storage Filter
Enabling hash join also works because it does a Seq Scan rather than Index Scan

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12551]: https://yugabyte.atlassian.net/browse/DB-12551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment] 2024-08-26 22:52
Duplicate of #22533 
```
yugabyte=# EXPLAIN (COSTS OFF)
yugabyte-# SELECT
yugabyte-#       "orders per customer"."number of orders"
yugabyte-#       AS "number of orders per customer"
yugabyte-#      , COUNT(*)
yugabyte-#        AS "number of customers"
yugabyte-# FROM
yugabyte-#         (
yugabyte(#               SELECT
yugabyte(#                      "customer".c_custkey
yugabyte(#                       AS "customer"
yugabyte(#                    , COUNT("customer order".o_orderkey)
yugabyte(#                      AS "number of orders"
yugabyte(#               FROM customer
yugabyte(#                  AS "customer"
yugabyte(#               LEFT OUTER JOIN orders
yugabyte(#                 AS "customer order"
yugabyte(#               ON "customer".c_custkey
yugabyte(#                       = "customer order".o_custkey
yugabyte(#                 AND "customer order".o_comment
yugabyte(#                           NOT LIKE '%unusual%packages%'
yugabyte(#               GROUP BY "customer".c_custkey
yugabyte(#         )
yugabyte-#   AS "orders per customer"
yugabyte-# GROUP BY "number of orders"
yugabyte-# ORDER BY
yugabyte-#     "number of customers" DESC
yugabyte-#   , "number of orders per customer" DESC
yugabyte-# ;
                                                QUERY PLAN                                                
----------------------------------------------------------------------------------------------------------
 Sort
   Sort Key: (count(*)) DESC, (count("customer order".o_orderkey)) DESC
   ->  HashAggregate
         Group Key: count("customer order".o_orderkey)
         ->  GroupAggregate
               Group Key: customer.c_custkey
               ->  Merge Left Join
                     Merge Cond: (customer.c_custkey = "customer order".o_custkey)
                     ->  Index Scan using customer_c_custkey_idx on customer
                     ->  Materialize
                           ->  Index Scan using orders_o_custkey_o_comment_idx on orders "customer order"
                                 Storage Index Filter: (o_comment !~~ '%unusual%packages%'::text)
(12 rows)
```
Index Scan with a Storage Index Filter in a subquery.
Though subquery was flattened in this case, it does not prevent the problem.

**Closed by andrei-mart** 2024-08-26 22:52 UTC
Labels: kind/bug, area/ysql, priority/medium
