### ISSUE TITLE
[YSQL] `ERROR:  Restart read required` or `ERROR:  Restarting a DDL transaction not supported` with ANALYZE

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#24004] opened 2024-09-18 09:44 UTC
Jira Link: [DB-12892](https://yugabyte.atlassian.net/browse/DB-12892)
### Description

ANALYZE fails on read restart when there are ongoing changes (and I guess when it encounters a change made less than 500ms before the start of analyze, as it is the default max clock skew). The error is different in read committed and in repeatable read.

It is easy to reproduce with:
```
set client_min_messages=error;
\! PGOPTIONS='-c client_min_messages=error' pgbench -iIdtpG
\! pgbench -c10 -T60 -n & sleep 5
analyze pgbench_accounts;
```

on 2.23 without read committed:
```
yugabyte=# analyze pgbench_accounts;
ERROR:  Restart read required at: { read: { physical: 1726651937400217 } local_limit: { physical: 1726651937400217 }
global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```

on 2.23 with read commited
```
yugabyte=# analyze pgbench_accounts;
ERROR:  Restarting a DDL transaction not supported
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12892]: https://yugabyte.atlassian.net/browse/DB-12892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pao214** [comment] 2024-09-18 18:34
This should be resolved by d298d4406060. Please reopen if the issue is not resolved.

**Closed by pao214** 2024-09-18 18:34 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
