### ISSUE TITLE
[YSQL][LST] ERROR:  Illegal state: Restart of completed transaction ...: kAborted

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13184] opened 2022-07-07 08:39 UTC
Jira Link: [DB-2868](https://yugabyte.atlassian.net/browse/DB-2868)
### Description

```
$ cd ~/code/yugabyte-db
$ git checkout 226465305d
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,ysql_num_shards_per_tserver=1,enable_stream_compression=true,stream_compression_algo=1,yb_num_shards_per_tserver=1 --master_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,enable_stream_compression=true,stream_compression_algo=1,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=40,tablet_split_high_phase_shard_count_per_node=50
$ cd ~/code/yb-long-system-test
$ git checkout 80c10f2b
$ python3.9 ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=763272
2022-07-06 23:51:48,949 MainThread INFO     Reproduce with: git checkout 80c10f2b && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=763272
2022-07-06 23:51:49,398 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
2022-07-06 23:51:49,400 MainThread INFO     Creating tables for database db_lst_763272
2022-07-06 23:52:16,904 MainThread INFO     Starting worker_0: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 23:52:16,904 MainThread INFO     Starting worker_1: RandomSelectAction, SetConfigAction
2022-07-06 23:52:16,909 MainThread INFO     Starting worker_2: RandomSelectAction, SetConfigAction
2022-07-06 23:52:16,911 MainThread INFO     Starting worker_3: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 23:52:16,922 MainThread INFO     Starting worker_4: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 23:52:16,923 MainThread INFO     Starting worker_5: RandomSelectAction, SetConfigAction
2022-07-06 23:52:16,925 MainThread INFO     Starting worker_6: RandomSelectAction, SetConfigAction
2022-07-06 23:52:16,925 MainThread INFO     Starting worker_7: RandomSelectAction, SetConfigAction
2022-07-06 23:52:16,928 MainThread INFO     Starting worker_8: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 23:52:16,928 MainThread INFO     Starting worker_9: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 23:52:26,939 MainThread INFO     Worker queries/s: [017.7][009.3][008.5][024.4][017.6][020.6][008.3][008.6][011.1][019.2]
[...]
2022-07-07 00:06:47,884 MainThread INFO     Worker queries/s: [009.9][005.3][005.1][013.9][008.2][000.0][003.2][003.8][006.1][010.7]
2022-07-07 00:06:48,439 worker_4   ERROR    Unexpected query failure: InternalError_
Query: UPDATE t0 SET c1_int = -25 WHERE TRUE;
  values: None
  runtime: 2022-07-07 00:06:47.441 - 2022-07-07 00:06:48.439
  supports explain: True
  supports rollback: True
  affected rows: None
Action: SingleUpdateAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Illegal state: Restart of completed transaction 03e59b53-4d00-489a-903f-f4f226715d99: kAborted
    @           0x997b88  errmsg
    @           0x9c31e8  HandleYBStatusAtErrorLevel
    @           0x6f0b30  ybcIterateForeignScan
    @           0x6e55a9  ForeignNext
    @           0x6bc16d  ExecScan
    @           0x6dae5f  ExecModifyTable
    @           0x6b35ba  standard_ExecutorRun
    @     0x7fd5e169eaa5  pgss_ExecutorRun
    @     0x7fd5e169563a  ybpgm_ExecutorRun
    @           0x843bed  ProcessQuery
    @           0x843162  PortalRunMulti
    @           0x8428c6  PortalRun
    @           0x8400c6  yb_exec_simple_query_impl
    @           0x840666  yb_exec_query_wrapper_one_attempt
    @           0x83d6e8  PostgresMain
    @           0x7ad7fc  BackendRun
    @           0x7acc50  ServerLoop
    @           0x7a92bb  PostmasterMain
    @           0x71301d  PostgresServerProcessMain
    @           0x7134c2  main
    @     0x7fd5e5b97825  __libc_start_main
    @           0x4b8969  _start
Transaction isolation level: committed
DB Node: host: 127.0.0.2, port: 5433
DB Backend PID: 2251509
```
[lst_2022-07-06_23:51:48_763272.zip](https://github.com/yugabyte/yugabyte-db/files/9061868/lst_2022-07-06_23.51.48_763272.zip)
This failure happens occasionally. If it's expected, I would at least change the error code away from Internal Error.

**Comment by pkj415** [comment] 2024-01-24 17:06
Duplicate of #19010

**Closed by pkj415** 2024-01-24 17:06 UTC
Labels: kind/bug, area/ysql, priority/medium, qa_automation, qa_lst
