### ISSUE TITLE
yb-admin set_load_balancer_enabled setting fails to find master leader

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#2738] opened 2019-10-26 07:22 UTC
This command doesn't find master leader even if the master leader is active.

```
[yugabyte@ip-10-100-25-194 bin]$ ./yb-admin --master_addresses=10.100.149.129:7100,10.100.25.194:7100,10.100.91.98:7100 set_load_balancer_enabled 1
I1026 07:21:51.060727 13557 mem_tracker.cc:250] MemTracker: hard memory limit is 12.558644 GB
I1026 07:21:51.060915 13557 mem_tracker.cc:252] MemTracker: soft memory limit is 10.674848 GB
Error: Illegal state (yb/master/scoped_leader_shared_lock.cc:76): Unable to change load balancer state: Not the leader. Local UUID: 41ed5c277978434bac99e3ba5e65db2b, Consensus state: current_term: 138 leader_uuid: "0c2af2834bbd43a08fb206f7b0f1dd32" config { opid_index: 728068 peers { permanent_uuid: "41ed5c277978434bac99e3ba5e65db2b" member_type: VOTER last_known_private_addr { host: "10.100.149.129" port: 7100 } } peers { permanent_uuid: "0c2af2834bbd43a08fb206f7b0f1dd32" member_type: VOTER last_known_private_addr { host: "10.100.25.194" port: 7100 } } peers { permanent_uuid: "8412e5f726f645b487569881d9ebe018" member_type: VOTER last_known_private_addr { host: "10.100.91.98" port: 7100 } } }

```

**Comment by bmatican** [comment] 2019-10-30 00:22
Duplicate of #1941

**Closed by bmatican** 2019-10-30 00:22 UTC
Labels: area/docdb, priority/high
