### ISSUE TITLE
[YSQL] pg_dump does not work for sequences

### ISSUE THREAD

**Issue by ndeodhar** [YugaByte/yugabyte-db#1219] opened 2019-04-17 18:47 UTC
Because we don't create a sequence table per table, pg_dump does not work for databases that contain sequences.
```
./postgres/bin/pg_dump -d postgres -h 127.0.0.1 -p 5433 -U postgres
pg_dump: [archiver (db)] query failed: ERROR:  "bar_a_seq" is a sequence table
DETAIL:  Querying sequence tables is not supported yet.
HINT:  Use lastval() and currval() instead.
pg_dump: [archiver (db)] query was: SELECT last_value, is_called FROM public.bar_a_seq
```

**Comment by hectorgcr** [comment] 2019-04-17 20:35
Duplicate of #999

**Closed by hectorgcr** 2019-04-17 20:35 UTC
Labels: ysql
