### ISSUE TITLE
Backup/restore Failure when sql db has two tables with same name in different schema

### ISSUE THREAD

**Issue by uday-accel** [yugabyte/yugabyte-db#7808] opened 2021-03-25 14:15 UTC
version: 2.5.1

we are trying to implement multi tenancy using schema( one for each tenant), where in all tables will be replicated in each schema. we are trying to backup restore as per documentation using python scripts.
 
error : 
*code=1 output=Error: Invalid argument (yb/tools/yb-admin_client.cc:375): Namespace 'ysql.table_abc' has multiple tables named 'flyway_schema_history', specify table id instead*

Expected result: backup should succeed. 

I also tried to modify script so that table id is used instead of name. backup succeeds. but restore fails with below error

*Error: Invalid argument (yb/master/catalog_manager_ent.cc:1107): Unable to import snapshot meta file /tmp/yb_backup_gmgrjjmvezyaidzi/SnapshotInfoPB: Found 2 YSQL tables with the same name: <table_name> - 0000413c000030008000000000004140, 0000413c00003000800000000000417b: SNAPSHOT_FAILED (master error 23)*

**Comment by kerneljake** [comment] 2021-08-30 21:22
dupe of #8804

**Comment by OlegLoginov** [comment] 2021-09-02 14:40
Closing as duplicate of #8804 
Note: it's fixed in the `master` branch, in 2.6 and in 2.9.0.

**Closed by OlegLoginov** 2021-09-02 14:40 UTC
Labels: area/ysql
