### ISSUE TITLE
[DocDB] enum error after backup and restore:  invalid internal value for enum

### ISSUE THREAD

**Issue by epratt-yb** [yugabyte/yugabyte-db#10925] opened 2021-12-21 22:12 UTC
### Description

When backing up and restoring tables that have enum types you get the following error:

```
ERROR:  invalid internal value for enum: <enumid>
```
repro steps:

create the following type and table:

```
yugabyte=# create type e_t as enum('c', 'b', 'a');
CREATE TYPE
yugabyte=# create table t(id e_t);
CREATE TABLE
yugabyte=# insert into t values ('a'), ('b'), ('c');
INSERT 0 3
yugabyte=# select * from t order by id;j
 id
----
 c
 b
 a
(3 rows)
```
check the pg_enum table:

```
yugabyte=# select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | c
 16388 |     16385 |             2 | b
 16390 |     16385 |             3 | a
(3 rows)
```
take a backup of the table and restore it to another cluster and try and select the data:

```
yugabyte=# select * from t;
ERROR:  invalid internal value for enum: 16386
```

check pg_enum table:

```
yugabyte=# select oid, * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 20688 |     20686 |             1 | c
 20690 |     20686 |             2 | b
 20692 |     20686 |             3 | a
(3 rows)
```

Note: source db was on 2.7.3 and target was 2.8.0. Also the same occurs on 2.6.6 source and 2.8.0 backup

**Comment by epratt-yb** [comment] 2021-12-22 20:00
Tested 2.6.6 backup and restore to 2.6.6 as well and it still occurs

**Comment by myang2021** [comment] 2022-03-03 01:57
Duplicate of #11383

**Closed by myang2021** 2022-03-03 01:57 UTC
Labels: area/ysql
