### ISSUE TITLE
 [YSQL] Enable support for UNLOGGED syntax as no-op 

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#24183] opened 2024-09-28 14:06 UTC
Jira Link: [DB-13068](https://yugabyte.atlassian.net/browse/DB-13068)
### Description

Ignore, but do not fail if `UNLOGGED` keyword is used in the statements:
```
CREATE UNLOGGED TABLE ... ;
ALTER TABLE ... SET UNLOGGED;
ALTER TABLE ... SET LOGGED;
SELECT ... INTO UNLOGGED TABLE ... FROM ...;
CREATE UNLOGGED MATERIALIZED VIEW ... ;
```
Plus allow the following syntax (as no-op too):
```
ALTER TABLE ... SET (<storage_param>=<value>);
ALTER TABLE ... RESET (<storage_param>);
```

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13068]: https://yugabyte.atlassian.net/browse/DB-13068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment] 2024-10-01 17:12
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/23895.

**Closed by m-iancu** 2024-10-01 17:12 UTC
Labels: kind/enhancement, area/ysql, priority/medium, 2024.2 Backport Required
