### ISSUE TITLE
[2DC] Producer still shows in consumer registry get_universe_config after "successful" delete

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#2325] opened 2019-09-14 22:24 UTC
When deleting a peer from 2DC replication, a delete_universe_replication appears to succeed but still shows in the configuration after the operation is completed. 

Session:
```
[yugabyte@ip-172-151-36-2 ~]$ master/bin/yb-admin -master_addresses 172.151.36.2:7100,172.151.62.67:7100,172.151.18.19:7100 delete_universe_replication 41882d3b09b0465a9734dd88ebb29015 172.152.68.65:7100,172.152.55.41:7100,172.152.97.201:7100 fffc512fec1a403c8246c191f2cdf125
I0914 22:11:44.508621 14294 mem_tracker.cc:250] MemTracker: hard memory limit is 6.201147 GB
I0914 22:11:44.508698 14294 mem_tracker.cc:252] MemTracker: soft memory limit is 5.270975 GB
Replication deleted successfully
[yugabyte@ip-172-151-36-2 ~]$ master/bin/yb-admin -master_addresses 172.151.36.2:7100,172.151.62.67:7100,172.151.18.19:7100 get_universe_config
I0914 22:11:51.413547 14307 mem_tracker.cc:250] MemTracker: hard memory limit is 6.201147 GB
I0914 22:11:51.413625 14307 mem_tracker.cc:252] MemTracker: soft memory limit is 5.270975 GB
Config:
version: 2
replication_info {
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "aws"
        placement_region: "us-west-2"
        placement_zone: "us-west-2b"
      }
      min_num_replicas: 1
    }
    placement_uuid: "732e3564-f2e0-49cf-9ed4-a1234bf3c7c1"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2a"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2c"
  }
  affinitized_leaders {
    placement_cloud: "aws"
    placement_region: "us-west-2"
    placement_zone: "us-west-2b"
  }
}
cluster_uuid: "67838d2c-6375-425e-87ac-bbe92a1f4000"
consumer_registry {
  producer_map {
    key: "41882d3b09b0465a9734dd88ebb29015"
    value {
      stream_map {
        key: "b681d6c309f84c41a5c512d0f1e0060a"
        value {
          consumer_producer_tablet_map {
            key: "02b904537c5c4a24b8df18cd7f8ab784"
            value {
              tablets: "3e2d55d4b70d4d468b10250df569829d"
              tablets: "c815ace6d72740349b9a6c2c3f612924"
            }
          }
          consumer_producer_tablet_map {
            key: "2687aafe7fb04b2fb20761497f8bef63"
            value {
              tablets: "3eec7df3ff754d6e93e1a0e891b78db0"
              tablets: "20b405914efc4720906713b3907feabd"
            }
          }
          consumer_producer_tablet_map {
            key: "4ce5e78551b9429db543602029c97056"
            value {
              tablets: "7945fc42f6304caebde02dee9cbe357f"
              tablets: "14c31b47d63543e891ab9bd5d8cfc0db"
            }
          }
          consumer_producer_tablet_map {
            key: "531955db0ca144c5b4b159e1dac14597"
            value {
              tablets: "c845873f8f6d496caf6e3153171e425a"
              tablets: "7ca8d2e68d334207af987c3d7a8c4a01"
            }
          }
          consumer_producer_tablet_map {
            key: "55d61a34992f402488b6c33c169fe915"
            value {
              tablets: "87233d783a1c4aa3943ea7b228afcdce"
              tablets: "b7b8e7d50f274176b90bea925175dd25"
            }
          }
          consumer_producer_tablet_map {
            key: "69bc17d670a94b40836a8850115a74c5"
            value {
              tablets: "d827c6fd48b34660b2beb58c69a1f8cc"
              tablets: "2b0b1f6a32f344b88710ac162788e6a8"
              tablets: "9d12437f5e9f45378ab90f0ad8ee0cbc"
            }
          }
          consumer_producer_tablet_map {
            key: "8ba7f17cd27f413f89154316214905e7"
            value {
              tablets: "2c6e402bc8894585a0d8fc3355502439"
              tablets: "e1c8e2fe10ba42868670ee4bb02544f8"
              tablets: "d90120e0b01d4630b8acab94a1b8bfab"
            }
          }
          consumer_producer_tablet_map {
            key: "d3d1112b629b497d91fe9b8c1ce03c8c"
            value {
              tablets: "e1fa9bd45b99439e8583c650cc3ee853"
              tablets: "1d4f0c88a39943c7b6805f4cd4b83a7f"
            }
          }
          consumer_producer_tablet_map {
            key: "d99e9214e8234b72a711d84946c935bb"
            value {
              tablets: "3199a4749f5a4c5d80032f9aa18eea39"
              tablets: "4235fa015e7648e4821e57ba7b5a71f9"
              tablets: "8bda08c546314945985a9abf197bd23b"
            }
          }
          consumer_producer_tablet_map {
            key: "e11b4602828c41408bb905872c5ffa67"
            value {
              tablets: "94ed00dc3a0e4ff38eb0ba4d599f81b9"
              tablets: "7f0bf994027248579c3ed47419be9c10"
              tablets: "9b64ba2ec5a94bb092a68ba81eae52de"
            }
          }
          consumer_table_id: "882d970c81c3407da64df1706d3fffe0"
          producer_table_id: "fffc512fec1a403c8246c191f2cdf125"
        }
      }
      master_addrs {
        host: "172.152.68.65"
        port: 7100
      }
      master_addrs {
        host: "172.152.55.41"
        port: 7100
      }
      master_addrs {
        host: "172.152.97.201"
        port: 7100
      }
      tserver_addrs {
        host: "172.152.97.201"
        port: 9100
      }
      tserver_addrs {
        host: "172.152.68.65"
        port: 9100
      }
      tserver_addrs {
        host: "172.152.55.41"
        port: 9100
      }
    }
  }
}
[yugabyte@ip-172-151-36-2 ~]$ master/bin/yb-admin -master_addresses 172.151.36.2:7100,172.151.62.67:7100,172.151.18.19:7100 delete_universe_replication 41882d3b09b0465a9734dd88ebb29015
I0914 22:12:18.623682 14359 mem_tracker.cc:250] MemTracker: hard memory limit is 6.201147 GB
I0914 22:12:18.623760 14359 mem_tracker.cc:252] MemTracker: soft memory limit is 5.270975 GB
Error deleting universe replication: Universe replication info does not exist: producer_id: "41882d3b09b0465a9734dd88ebb29015"

Error: Not found (yb/master/catalog_manager_ent.cc:1783): Unable to delete replication for universe 41882d3b09b0465a9734dd88ebb29015: Universe replication info does not exist: producer_id: "41882d3b09b0465a9734dd88ebb29015"
```
From the master log:
```
I0914 22:11:44.532343 24373 catalog_manager_ent.cc:1766] Servicing DeleteUniverseReplication request from 172.151.36.2:57762: producer_id: "41882d3b09b0465a9734dd88ebb29015"
I0914 22:11:44.532402 24373 catalog_manager_ent.cc:1793] Deleting subscriber for table 882d970c81c3407da64df1706d3fffe0
I0914 22:11:44.532476 24373 catalog_manager_ent.cc:1819] Processed delete universe replication 41882d3b09b0465a9734dd88ebb29015 [data=producer_id: "41882d3b09b0465a9734dd88ebb29015"
producer_master_addresses {
  host: "172.152.68.65"
  port: 7100
}
producer_master_addresses {
  host: "172.152.55.41"
  port: 7100
}
producer_master_addresses {
  host: "172.152.97.201"
  port: 7100
}
tables: "fffc512fec1a403c8246c191f2cdf125"
state: DELETED
validated_tables {
  key: "fffc512fec1a403c8246c191f2cdf125"
  value: "882d970c81c3407da64df1706d3fffe0"
}
table_streams {
  key: "fffc512fec1a403c8246c191f2cdf125"
  value: "e07dc15457ad42f08b1f0771984793ff"
}
]  per request from 172.151.36.2:57762
**W0914 22:11:44.704957 16788 thread.h:213] Thread join failed: Invalid argument (yb/util/thread.cc:538): Can't join on own thread: rpc_tp_ybclient_0**
I0914 22:12:18.627445 24795 catalog_manager_ent.cc:1766] Servicing DeleteUniverseReplication request from 172.151.36.2:57774: producer_id: "41882d3b09b0465a9734dd88ebb29015"
I0914 22:13:21.301144 26080 catalog_manager_ent.cc:1766] Servicing DeleteUniverseReplication request from 172.151.36.2:57788: producer_id: "41882d3b09b0465a9734dd88ebb29015"
```

**Comment by ndeodhar** [comment] 2019-09-15 00:12
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/2155.

**Closed** 2019-09-15 23:42 UTC
Labels: area/cdc
