### ISSUE TITLE
[YSQL] Unexpected random behavior of `INSERT ... ON CONFLICT ... DO UPDATE SET...`

### ISSUE THREAD

**Issue by Wizmann** [yugabyte/yugabyte-db#15310] opened 2022-12-13 11:11 UTC
Jira Link: [DB-4462](https://yugabyte.atlassian.net/browse/DB-4462)
### Description

> Cluster setup:
> * Replication Factor : 3
> * Num Nodes (TServers) : 9
> * YugabyteDB Version : 2.15.3.0
> * Build Type : RELEASE
> * OS: Ubuntu 2204

Suppose we have a table like this:

```sql
CREATE TABLE IF NOT EXISTS mytest
(
    id1 bigint NOT NULL,
    id2 character varying(120) COLLATE pg_catalog."default" NOT NULL,
    value bigint NOT NULL DEFAULT nextval('value_sequence'::regclass),
    CONSTRAINT id_pkey PRIMARY KEY (id1, id2)
)
```

And we're trying to insert new records or fetch existing records in batch using SQL statement like this:
(one client, no concurrent trasactions)

```sql
INSERT into mytest (id1, id2) values 
(0,'1670861561.05736899375915527344'),
(1,'1670861561.05738210678100585938'),
(2,'1670861561.05738306045532226562'),
(3,'1670861561.05738401412963867188'),
...
(20,'1670861561.05738592147827148438')
ON CONFLICT (id1, id2) 
DO UPDATE SET id1 = excluded.id1, id2 = excluded.id2 RETURNING *
```

It randomly returns the rows (**expected**) or throws `duplicate key value violates unique constraint "id_pkey"` (**unexpected**) exception with YugabyteDB.

Interestingly: 
* if we change the batch size to 5, it's more likely to work fine
* if we change the batch size to 50, it will throw the exception for most of the time

If we change the SQL statement to:

```sql
INSERT into mytest (id1, id2) values 
(0,'1670861561.05736899375915527344'),
...
(20,'1670861561.05738592147827148438')
ON CONFLICT (id1, id2) 
DO UPDATE SET value = excluded.value RETURNING *
```

It will works fine, no exception will be throwed.

Meanwhile, we've run the same SQL statement with PostgreSQL, it always returns the rows, which is the expected behavior.

**Comment by FranckPachot** [comment] 2022-12-14 08:04
Please confirm that you get this (`duplicate key value violates unique constraint`) when you insert duplicates

**Comment by FranckPachot** [comment] 2022-12-14 08:11
And also the reason for `set id1 = excluded.id1, id2 = excluded.id2`. This will update to the same value, as it conflicted on those, right?

**Comment by Wizmann** [comment] 2022-12-14 08:19
> Please confirm that you get this (duplicate key value violates unique constraint) when you insert duplicates
Yes. I run the same INSERT statement multiple times. There're duplicate keys in the table except the first time.

> And also the reason for set id1 = excluded.id1, id2 = excluded.id2. This will update to the same value, as it conflicted on those, right?

It's a trick to get `value` if the `<id1, id2>` pair already exists in the table ([ref][1]).

[1]: https://stackoverflow.com/questions/46751530/postgresql-upsert-return-id-on-conflict

**Comment by ddorian** [comment] 2022-12-14 08:28
> It's a trick to get value if the <id1, id2> pair already exists in the table ([ref](https://stackoverflow.com/questions/46751530/postgresql-upsert-return-id-on-conflict)).

This trick should be much more expensive (because it's updating rows that shouldn't be updated) compared to just sending another query for rows that weren't updated and not returned (by doing the diff on the client side).

**Comment by FranckPachot** [comment] 2022-12-14 11:39
@Wizmann I've put some alternatives here, to avoid any dummy update:
https://dev.to/yugabyte/insert-on-conflict-returning-old-values-5025

**Comment by sushantrmishra** [comment] 2023-09-05 05:26
@Wizmann It seems @FranckPachot 's workaround worked well for you, hence closing the issues.

If you have a reproducible test case for "duplicate key value violates unique constraint" then please share and reopen this issue.

**Closed by sushantrmishra** 2023-09-05 05:26 UTC
Labels: kind/bug, area/ysql, priority/medium
