### ISSUE TITLE
[YSQL] Orphaned postgres backend cannot be killed (SIGTERM)

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#8616] opened 2021-05-25 21:29 UTC
Jira Link: [DB-2266](https://yugabyte.atlassian.net/browse/DB-2266)
I ran into an orphaned Postgres logger process that was unable to terminate cleanly. It survived the failure of the Postmaster, and was unresponsive to SIGTERM. The process had the following stack trace:

```
Thread 1 (Thread 0x7f9afd8fc280 (LWP 1994)):
#0 0x00007f9afa6159d3 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1 0x0000000000841446 in WaitEventSetWaitBlock (nevents=1, occurred_events=0x7ffcdab51e80, cur_timeout=86400000, set=0x32c5b78) at ../../../../../../../src/postgres/src/backend/storage/ipc/latch.c:1048
returned_events = 0
cur_event = <optimized out>
rc = <optimized out>
cur_epoll_event = <optimized out>
#2 WaitEventSetWait (set=set@entry=0x32c5b78, timeout=timeout@entry=86400000, occurred_events=occurred_events@entry=0x7ffcdab51e80, nevents=nevents@entry=1, wait_event_info=wait_event_info@entry=83886090)
at ../../../../../../../src/postgres/src/backend/storage/ipc/latch.c:1000
returned_events = 0
start_time = {tv_sec = 1305169, tv_nsec = 788782534}
cur_time = {tv_sec = 11, tv_nsec = 72}
cur_timeout = 86400000
#3 0x0000000000841916 in WaitLatchOrSocket (latch=0xf02530 <LocalLatchData>, wakeEvents=<optimized out>, sock=8, timeout=86400000, wait_event_info=wait_event_info@entry=83886090) at ../../../../../../../src/postgres/src/backend/storage/ipc/latch.c:385
ret = 0
rc = <optimized out>
event = {pos = -625664176, events = 32764, fd = 0, user_data = 0x7ffcdab51ed0}
set = 0x32c5b78
#4 0x00000000007d889c in SysLoggerMain (argv=0x0, argc=0) at ../../../../../../src/postgres/src/backend/postmaster/syslogger.c:452
time_based_rotation = <optimized out>
size_rotation_for = <optimized out>
cur_timeout = <optimized out>
rc = <optimized out>
logbuffer = "\000\000e\000\375*\000\000t2021-05-18 04:49:04.434 UTC [11005] FATAL: terminating connection due to unexpected postmaster exit\nit code 1\ncommand\nTEMENT: select"...
bytes_in_logbuffer = 0
currentLogDir = 0x3275cb8 "/data/yb-data/tserver/logs"
currentLogFilename = 0x3275f30 "postgresql-%Y-%m-%d_%H%M%S.log"
currentLogRotationAge = 1440
now = 1621468800
#5 0x00000000007d9562 in SysLogger_Start () at ../../../../../../src/postgres/src/backend/postmaster/syslogger.c:645
sysloggerPid = 0
filename = <optimized out>
__func__ = "SysLogger_Start"
#6 0x00000000007d68ce in PostmasterMain (argc=argc@entry=25, argv=argv@entry=0x326e9f0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1302
opt = <optimized out>
status = <optimized out>
userDoption = <optimized out>
listen_addr_saved = true
i = <optimized out>
output_config_variable = <optimized out>
__func__ = "PostmasterMain"
#7 0x00000000007229ba in PostgresServerProcessMain (argc=25, argv=0x326e9f0) at ../../../../../../src/postgres/src/backend/main/main.c:234
do_check_root = <optimized out>
#8 0x0000000000722bb9 in main ()
No symbol table info available.
```

It has a FATAL message in its `logbuffer`, so it did log the FATAL message before starting to `WaitLatchOrSocket`.

**Comment by tylarb** [comment] 2021-07-07 17:14
also 2.4.3 - same as issue #8615

**Comment by sushantrmishra** [comment] 2022-08-25 06:34
https://github.com/yugabyte/yugabyte-db/issues/11343 and https://github.com/yugabyte/yugabyte-db/issues/12784 should ideally address this issue. Closing it for now, please reopen if the issue is seen again.

**Closed by sushantrmishra** 2022-08-25 06:34 UTC
Labels: kind/bug, area/ysql, priority/medium
