### ISSUE TITLE
[DocDB] A simple insertion results in WAL/log statistics counting two actions.

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#14830] opened 2022-11-03 15:35 UTC
Jira Link: [DB-4133](https://yugabyte.atlassian.net/browse/DB-4133)
### Description

# Versions
This issue has been noticed on a recent 2.17 build in dev.portal and with the public preview build of 2.15.3.0.
Other versions have not been tested.

# Cluster
The tested cluster is running with 3 nodes with RF3.
The test table is defined in the following way:
```
create table t ( id int primary key );
```
This results in the following tablet layout:
```
192.168.66.82:7000 ysql yugabyte t 000033e8000030008000000000004200 RUNNING
tablet:242e58c7799946cb85c18631cd7a84ae RUNNING : ( VOTER,yb-3.local:9100,FOLLOWER VOTER,yb-2.local:9100,FOLLOWER VOTER,yb-1.local:9100,LEADER )
tablet:346c1a58ed3b4b7ca237f30503fa11eb RUNNING : ( VOTER,yb-3.local:9100,FOLLOWER VOTER,yb-2.local:9100,LEADER VOTER,yb-1.local:9100,FOLLOWER )
tablet:bac9990e3958406a80177ff9898c1385 RUNNING : ( VOTER,yb-3.local:9100,LEADER VOTER,yb-2.local:9100,FOLLOWER VOTER,yb-1.local:9100,FOLLOWER )
```
In other words: the table t contains 3 tablets, with a leader on every one of the 3 nodes.

# Issue
When an insert is performed on the test table:
```
insert into t values (1);
```
The expectancy is that count of the statistics:
- log_append_latency
- log_entry_batches_per_group
- log_group_commit_latency
- log_sync_latency  

would increase by 1, however the count of the statistics:
- log_append_latency
- log_entry_batches_per_group
- log_group_commit_latency  

does increase by 2.  

Only the count of the statistic:
- log_sync_latency  

Is increased by one.

This can be measured in a simple way by using the yb_stats utility, and create a snapshot before and after the insert:
```
yb_stats --snapshot
snapshot number 25
...perform insert in another session...
yb_stats --snapshot
snapshot number 26
```
And then viewing the result by filtering the statistics names on `log`:
```
yb_stats --snapshot-diff -b 25 -e 26 --hostname-match 9000 --stat-name-match log
192.168.66.80:9000   tablet   log_bytes_logged                                                                   150 bytes           14.306 /s
192.168.66.81:9000   tablet   log_bytes_logged                                                                   154 bytes           14.692 /s
192.168.66.82:9000   tablet   log_bytes_logged                                                                   154 bytes           15.011 /s
192.168.66.80:9000   table    log_append_latency                                                                   2                  0.191 /s avg:        55 tot:             111 us
192.168.66.80:9000   table    log_entry_batches_per_group                                                          2                  0.191 /s avg:         1 tot:               2 reqs
192.168.66.80:9000   table    log_group_commit_latency                                                             2                  0.191 /s avg:      1103 tot:            2207 us
192.168.66.80:9000   table    log_sync_latency                                                                     1                  0.095 /s avg:      2030 tot:            2030 us
192.168.66.81:9000   table    log_append_latency                                                                   2                  0.191 /s avg:       226 tot:             453 us
192.168.66.81:9000   table    log_entry_batches_per_group                                                          2                  0.191 /s avg:         1 tot:               2 reqs
192.168.66.81:9000   table    log_group_commit_latency                                                             2                  0.191 /s avg:      1210 tot:            2420 us
192.168.66.81:9000   table    log_sync_latency                                                                     1                  0.095 /s avg:      1899 tot:            1899 us
192.168.66.82:9000   table    log_append_latency                                                                   2                  0.195 /s avg:       182 tot:             365 us
192.168.66.82:9000   table    log_entry_batches_per_group                                                          2                  0.195 /s avg:         1 tot:               2 reqs
192.168.66.82:9000   table    log_group_commit_latency                                                             2                  0.195 /s avg:      1653 tot:            3307 us
192.168.66.82:9000   table    log_sync_latency                                                                     1                  0.097 /s avg:      2766 tot:            2766 us
```
By default, the yb_stats statistics are grouped per server for readability. However, the `--details-enable` switch allows to break down statistics to the original source:
```
yb_stats --snapshot-diff -b 25 -e 26 --hostname-match 9000 --stat-name-match log --details-enable
192.168.66.80:9000   tablet   0177ff9898c1385 yugabyte        t                              log_bytes_logged                                                                   150 bytes           14.306 /s
192.168.66.81:9000   tablet   0177ff9898c1385 yugabyte        t                              log_bytes_logged                                                                   154 bytes           14.692 /s
192.168.66.82:9000   tablet   0177ff9898c1385 yugabyte        t                              log_bytes_logged                                                                   154 bytes           15.011 /s
192.168.66.80:9000   table    000000000004200 yugabyte        t                              log_append_latency                                                                   2                  0.191 /s avg:        55 tot:             111 us
192.168.66.80:9000   table    000000000004200 yugabyte        t                              log_entry_batches_per_group                                                          2                  0.191 /s avg:         1 tot:               2 reqs
192.168.66.80:9000   table    000000000004200 yugabyte        t                              log_group_commit_latency                                                             2                  0.191 /s avg:      1103 tot:            2207 us
192.168.66.80:9000   table    000000000004200 yugabyte        t                              log_sync_latency                                                                     1                  0.095 /s avg:      2030 tot:            2030 us
192.168.66.81:9000   table    000000000004200 yugabyte        t                              log_append_latency                                                                   2                  0.191 /s avg:       226 tot:             453 us
192.168.66.81:9000   table    000000000004200 yugabyte        t                              log_entry_batches_per_group                                                          2                  0.191 /s avg:         1 tot:               2 reqs
192.168.66.81:9000   table    000000000004200 yugabyte        t                              log_group_commit_latency                                                             2                  0.191 /s avg:      1210 tot:            2420 us
192.168.66.81:9000   table    000000000004200 yugabyte        t                              log_sync_latency                                                                     1                  0.095 /s avg:      1899 tot:            1899 us
192.168.66.82:9000   table    000000000004200 yugabyte        t                              log_append_latency                                                                   2                  0.195 /s avg:       182 tot:             365 us
192.168.66.82:9000   table    000000000004200 yugabyte        t                              log_entry_batches_per_group                                                          2                  0.195 /s avg:         1 tot:               2 reqs
192.168.66.82:9000   table    000000000004200 yugabyte        t                              log_group_commit_latency                                                             2                  0.195 /s avg:      1653 tot:            3307 us
192.168.66.82:9000   table    000000000004200 yugabyte        t                              log_sync_latency                                                                     1                  0.097 /s avg:      2766 tot:            2766 us
```
The statistics that we use for the count and sum statistics (as well as the percentiles) are kept on the table level.
The simple value statistics (counters and gauges) are kept at the tablet level.
The tablet UUID above is shortened, but it matches the tablet with the leader on yb-3.

I performed a test with ycsqlsh (YCQL), where the exact same behaviour was noticed.

**Comment by fritshoogland-yugabyte** [comment] 2022-11-03 15:39
Looking at the YSQL level statistics, it does NOT mention it being a single shared transaction:
```
yb_stats --snapshot-diff -b 25 -e 26 --hostname-match 13000
192.168.66.80:13000  handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt                                1 avg:          22.289 tot:          22.289 ms, avg:               1 tot:               1 rows
192.168.66.80:13000  handler_latency_yb_ysqlserver_SQLProcessor_Transactions                              1 avg:          22.289 tot:          22.289 ms, avg:               1 tot:               1 rows
192.168.66.80:13000           1 avg:          22.290 tot:          22.290 ms avg:          1 tot:          1 rows: insert into t values ($1)
```

**Comment by fritshoogland-yugabyte** [comment] 2022-11-03 16:05
I've repeated the test on a single node/RF1 database, which shows identical statistics:
```
yb_stats --snapshot-diff --hostname-match '(9000|13000)' --stat-name-match log -b 34 -e 35
192.168.66.80:9000   tablet   log_bytes_logged                                                                   148 bytes           12.544 /s
192.168.66.80:9000   table    log_append_latency                                                                   2                  0.170 /s avg:        24 tot:              49 us
192.168.66.80:9000   table    log_entry_batches_per_group                                                          2                  0.170 /s avg:         1 tot:               2 reqs
192.168.66.80:9000   table    log_group_commit_latency                                                             2                  0.170 /s avg:      2682 tot:            5365 us
192.168.66.80:9000   table    log_sync_latency                                                                     1                  0.085 /s avg:      5251 tot:            5251 us
192.168.66.80:13000           1 avg:           6.256 tot:           6.256 ms avg:          1 tot:          1 rows: insert into t values ($1)
```

**Comment by fritshoogland-yugabyte** [comment] 2022-11-03 16:06
I've repeated the test on a single node/RF1 database, which shows identical statistics:
```
yb_stats --snapshot-diff --hostname-match '(9000|13000)' --stat-name-match log -b 34 -e 35
192.168.66.80:9000   tablet   log_bytes_logged                                                                   148 bytes           12.544 /s
192.168.66.80:9000   table    log_append_latency                                                                   2                  0.170 /s avg:        24 tot:              49 us
192.168.66.80:9000   table    log_entry_batches_per_group                                                          2                  0.170 /s avg:         1 tot:               2 reqs
192.168.66.80:9000   table    log_group_commit_latency                                                             2                  0.170 /s avg:      2682 tot:            5365 us
192.168.66.80:9000   table    log_sync_latency                                                                     1                  0.085 /s avg:      5251 tot:            5251 us
192.168.66.80:13000           1 avg:           6.256 tot:           6.256 ms avg:          1 tot:          1 rows: insert into t values ($1)
```

**Comment by fritshoogland-yugabyte** [comment] 2022-11-04 10:23
I used `perf trace` to see if the two events align with the WAL writes being performed:
```
# perf trace -e writev -p $(pgrep tserver) --call-graph fp
     0.000 ( 0.044 ms): append [worker/1209 writev(fd: 195, vec: 0x7fa65bdeae10, vlen: 2)                         = 126
                                       __GI___writev (/opt/yugabyte/yugabyte-2.15.3.0/linuxbrew/lib/libc-2.23.so)
                                       yb::(anonymous namespace)::PosixWritableFile::AppendSlices (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::WritableLogSegment::WriteEntryBatch (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::Log::DoAppend (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::Log::Appender::ProcessBatch (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::TaskStream<yb::log::LogEntryBatch>::Run (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::ThreadPool::DispatchThread (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::Thread::SuperviseThread (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       start_thread (/opt/yugabyte/yugabyte-2.15.3.0/linuxbrew/lib/libpthread-2.23.so)
    29.175 ( 0.029 ms): append [worker/1209 writev(fd: 195, vec: 0x7fa65bdeae10, vlen: 2)                         = 28
                                       __GI___writev (/opt/yugabyte/yugabyte-2.15.3.0/linuxbrew/lib/libc-2.23.so)
                                       yb::(anonymous namespace)::PosixWritableFile::AppendSlices (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::WritableLogSegment::WriteEntryBatch (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::Log::DoAppend (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::log::Log::Appender::ProcessBatch (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::TaskStream<yb::log::LogEntryBatch>::Run (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::ThreadPool::DispatchThread (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       yb::Thread::SuperviseThread (/opt/yugabyte/yugabyte-2.15.3.0/bin/yb-tserver)
                                       start_thread (/opt/yugabyte/yugabyte-2.15.3.0/linuxbrew/lib/libpthread-2.23.so)
```
These are two identical stacks, only the amount that is written (seen as return code of the writev() systemcall) is different.

**Comment by yusong-yan** [comment] 2022-11-28 18:30
The reason why one insert causes two WAL log writes is that, after committing the actual SQL write, Raft will do a round of empty batch write (in `RaftConsensus::UpdateMajorityReplicated()`) to persistently update the most committed index.

**Comment by yusong-yan** [comment] 2022-12-01 23:54
For only one insert senario, after the leader commits and applies this operation, there will be no pending operation in the background. So, leader will just append an empty entry. I ran this senario by myself, and the metric result is the same as what Frist found out.

But this doesn't mean metrics `log_append_latency` `log_entry_batches_per_group` `log_group_commit_latency` will always show 2x the number of actual inserts. This has been validated by concurrently inserting 10000 rows into one table. And the result of those metrics is 10108 instead of 20000. The reason is empty batch append will not be triggered when there is a pending operation that needs to be replicated. In a series of concurrent inserts, it is highly possible to have pending operations for every insert. Thus, the empty batch append will not happen for every insert.

**Comment by rthallamko3** [comment] 2023-01-17 04:03
This is by design, see @yusong-yan 's comment above.

**Closed by rthallamko3** 2023-01-17 04:03 UTC
Labels: kind/bug, area/docdb, priority/medium
