### ISSUE TITLE
[YSQL] Support TRUNCATE TABLE [ RESTART IDENTITY | CONTINUE IDENTITY ]

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1405] opened 2019-05-17 23:48 UTC
Now that we have sequences, we can support these options.

**Comment by sushantrmishra** [comment] 2022-01-15 08:26
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/9950

**Closed by sushantrmishra** 2022-01-15 08:26 UTC
Labels: area/ysql, pgcm
