### ISSUE TITLE
[New Feature] Sharding by column or UDF

### ISSUE THREAD

**Issue by Bessonov** [yugabyte/yugabyte-db#16316] opened 2023-03-05 20:42 UTC
Dear YugaByteDB team,

I've been looking at the documentation, especially [Hash and range sharding](https://docs.yugabyte.com/preview/architecture/docdb-sharding/sharding/), [Tablet splitting](https://docs.yugabyte.com/preview/architecture/docdb-sharding/tablet-splitting/), and [Distributed SQL: Sharding and Partitioning in YugabyteDB](https://www.yugabyte.com/blog/distributed-sql-essentials-sharding-and-partitioning-in-yugabytedb/). I've been looking at github issues, but haven't been able to find any related feature request.

There are a lot of use cases where it is very beneficial to have data physically co-located (not to be confused with [Colocated tables](https://docs.yugabyte.com/preview/architecture/docdb-sharding/colocated-tables/)). For example, in a SaaS application there might be a `tenant_id` column in each table. And all related joins can operate on locally available data without the need to exchange data with other nodes across the network.

The idea isn't new and I like the implementation of Citus: [Creating And Distributing Tables](https://docs.citusdata.com/en/v11.2/develop/reference_ddl.html#creating-and-distributing-tables) and [Choosing Distribution Column](https://docs.citusdata.com/en/v11.2/sharding/data_modeling.html). This is already a very powerful way of associating data (especially with `colocate_with` and reference tables). It could be even more powerful, if a user defined function could be used.

Please vote with :+1:

**Comment by ddorian** [comment] 2023-03-06 08:59
This is called co-partition. Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/79.  
Please subscribe/vote that issue instead.

**Closed by ddorian** 2023-03-06 08:59 UTC
Labels: kind/new-feature

**Comment by ddorian** [comment] 2023-03-06 09:00
> It could be even more powerful, if a user defined function could be used.

You can create an new column and set it's value with this function, and use that column in the partitioning key.

**Comment by Bessonov** [comment] 2023-03-06 09:33
@ddorian great, awesome! Thank you!
