### ISSUE TITLE
[Docs] [infra] add a "contribute" dropdown

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11029] opened 2022-01-07 20:27 UTC
### Description

Three items: Edit this page, Report a doc issue, Suggest new content

**Edit this page** will take more work. (So if it's not feasible right now, we can make that "phase 2" of this effort.)

**Report a doc issue** should take you to a GitHub issue template and include the URL of the page you were on.

**Suggest new content** should take you to a different GitHub issue template, and include the URL of the page you were on.

![image](https://user-images.githubusercontent.com/538384/148602900-03daca62-ddec-4dce-8570-a235ea39366d.png)

**Comment by rajmaddy89** [comment] 2022-01-07 21:29
Can you please assign this issue to me, thanks

**Comment by polarweasel** [comment] 2022-01-07 21:57
@ymahajan FYI

**Comment by rajmaddy89** [comment] 2022-01-11 02:58
Just want to seek some clarification from Product team, maybe..

Where do we want to place the drop down menu 

1. On the shared top menu bar which has  search text box, Get started etc, 
2. Should it be part of the actual page itself
3. Should it be part of the bottom menu which has "Contact us"

Please clarify which option is appropriate

**Comment by ymahajan** [comment] 2022-01-11 04:29
@rajmaddy89 - Thanks for looking into this. Yes, we need it to part of the actual page itself. It should be placed on the top right corner.

**Comment by ymahajan** [comment] 2022-01-11 04:30
@rajmaddy89 - Also do you think we can add feedback widget also - Here is the one sample with simple like/dislike and also users can provide additional feedback. https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is-azure-data-studio?view=sql-server-ver15 

If this is feasible, this feedback widget can be at the bottom right of the actual page.

**Comment by polarweasel** [comment] 2022-01-11 05:52
For the "Contribute" dropdown menu, instead of the top right corner, I'm inclined to try at the bottom of the left nav. Top right is already crowded with random buttons.
<img width="248" alt="image" src="https://user-images.githubusercontent.com/538384/148888434-540a4a88-e7d7-4e9c-b1fe-0a6c33a56451.png">

And for the feedback widget, I assume you're talking about the "Is this page helpful?" thumbs-up/down next to the article title, and not the big one at the bottom of the page @ymahajan?
<img width="679" alt="image" src="https://user-images.githubusercontent.com/538384/148888634-7b00506b-569b-4284-b990-5c361522389c.png">

**Comment by ymahajan** [comment] 2022-01-11 06:06
@polarweasel Yes, i am talking about the "Is this page helpful?" thumbs-up/down (as shown in your image)

**Comment by polarweasel** [comment] 2022-01-12 18:41
@rajmaddy89 the [release notes for Hugo 0.92.0](https://www.google.com/url?q=https://github.com/gohugoio/hugo/releases/tag/v0.92.0) have some useful information on getting the path to a page's source file. Useful information for the "Edit this page" button!

**Comment by polarweasel** [comment] 2022-01-14 02:24
And a suggestion from Denis Magda (no GH account linked yet):

> If you don't mind, please consider adding [bugyard](https://bugyard.io/) (or comparable service) to collect feedback from developers in the simplest way possible. With bugyard, developers can just click a button, highlight a paragraph/sentence/code snippet/etc, and share feedback with you within a minute. No JIRAs, Github issues, etc - which are time-consuming. Your team can receive notifications through Slack, email, and other channels. You can see how bugyard works on the Ignite docs (click the Docs Feedback button): <https://ignite.apache.org/docs/latest/#>

**Comment by rajmaddy89** [comment] 2022-01-14 03:08
Thanks for sharing the information, I have started working on drop down as a solution for now.

I believe this(mentioned by Denis) is a good idea but this might require some research and is experimental. Compatibility with front end looks challenging. This could take some time.

I need clarification on which might be better at this stage.
My personal opinion is to go for option 1(drop down). Later, May be research about bug yard and it's compatibility can be done.

**Comment by dmagda** [comment] 2022-01-14 03:16
@rajmaddy89 you can customize the bugyard button the way you like. For the Apache Ignite website, the red button was the way to go, for YugaByte we can use another UI element. A menu item from your dropdown list works to: a visitor selects the item and you call the bugyard feedback window. My suggestion is to spend extra cycles and look into bugyard.

**Comment by rajmaddy89** [comment] 2022-01-14 03:42
Also it has got only 14 day free trail. I can integrate, but I have following questions 
1. Does that mean we need to pay them after the free trail ? I suppose yes. The widget cannot be used beyond 14 days as it is not free.
2. For Slack/Email Id integration I need YB workspace owner for Slack or the Yugabyte email id. This will help me to ensure the integration is working as intended.
3. Also when lots of feedback gets submitted, it becomes difficult for people ( documentation team) within Yugabyte to keep track of everything. Is that discussed already?
Cc @polarweasel

**Comment by polarweasel** [comment] 2022-01-14 04:11
1. I'll defer to @ymahajan, but if the service is good and priced reasonably, I don't see an issue.

2. Yes use my email address for testing for the moment.

3. I'm guessing we are not going to get inundated with so much feedback that we can't handle it. If we do, we can adjust (automate, redesign, rethink) as necessary at that point.  Sometimes it's actually best to do something that won't scale well, just to get started. 😊

**Comment by dmagda** [comment] 2022-01-14 04:29
3. The beauty of the service is that you, eventually, start hearing back from your **open source** end-users on all sorts of issues/suggestions (typos, broken code snippets, inaccurate sentences in specific paragraphs, etc.). As an example, presently, the Ignite community receives 2-5 suggestions/issues weekly from the end-users. Guess how many end-users reported documentation issues through JIRA (before bugyard was used)? Zero!!! Only Ignite committers (people who develop Ignite) were creating tickets through JIRA/GitHub, it was time-consuming for the end-users :)

Btw, @rajmaddy89 @polarweasel that's an email notification for the feedback that @rajmaddy89 has just posted on the Ignite docs:
![Screen Shot 2022-01-13 at 10 50 49 PM](https://user-images.githubusercontent.com/1537233/149451481-0eb9f232-454a-4a45-85c8-cce7e54080b1.png)

and this is the Admin panel with the list of all issues/suggestions:
![Screen Shot 2022-01-13 at 11 27 34 PM](https://user-images.githubusercontent.com/1537233/149451607-de7987dc-b741-4a18-8848-4d1cda3332a0.png)

**Comment by rajmaddy89** [comment] 2022-01-14 04:34
Wow, you can access my integration so quickly 😀 and see what's happening, that's nice.. I will share a integration video tomorrow via Slack

**Comment by dmagda** [comment] 2022-01-14 04:39
@rajmaddy89 nope, that's not your integration :) As an Ignite committer, I receive notifications from bugyard. Check the first screenshot, the recipient is the dev@ignite.apache.org alias.

**Comment by rajmaddy89** [comment] 2022-01-14 11:36
Oh , guess I did not look closely at the screenshot

**Comment by rajmaddy89** [comment] 2022-01-22 03:47
In Progress PR: https://github.com/yugabyte/yugabyte-db/pull/11174

**Comment by rajmaddy89** [comment] 2022-02-07 03:13
PR ready to be reviewed: https://github.com/yugabyte/yugabyte-db/pull/11174

**Comment by aishwarya24** [comment] 2023-02-27 15:11
Closing this as its complete.

**Closed by aishwarya24** 2023-02-27 15:11 UTC
Labels: area/documentation, temp/docs-migration
