### ISSUE TITLE
[DocDB] [Clone DB] Clone DB query fails to clone the source DB

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#22764] opened 2024-06-06 18:59 UTC
Jira Link: [DB-11669](https://yugabyte.atlassian.net/browse/DB-11669)
### Description

Clone DB query fails to clone the source DB

**Version**: `2.23..0.0-b435`

**Steps**:
1. Create database(demo1) and table
2. Create snapshot schedule on created database
3. Load some data to table
4. Run `CREATE DATABASE demo2 TEMPLATE demo1;`

**Actual**:
1. It returns `CREATE DATABASE` as output(means query worked), but when user describe the databases there clone db wont be present. and list clone returns
```
[
    {
        "aggregate_state": "ABORTED",
        "source_namespace_id": "00004105000030008000000000000000",
        "seq_no": "1",
        "target_namespace_name": "demo2",
        "restore_time": "2024-06-06 18:51:26.436971",
        "abort_message": "Runtime error (yb/util/subprocess.cc:634): Subprocess '/home/yugabyte/yb-software/yugabyte-2.23.0.0-b435-centos-x86_64/bin/../postgres/bin/ysql_dump' terminated with non-zero exit status 256"
    }
]
```

**Expected**:
1. Clone query should work and clone the db as source db
2. If clone query fails then it should return appropriate error message( for good user experience )

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11669]: https://yugabyte.atlassian.net/browse/DB-11669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment] 2024-06-06 19:45
I am trying to reproduce this locally. However, clone works fine and the clone wasn't aborted. I am sharing the script with you so that you can tell me if you run things differently.

```
./bin/yb-ctl destroy
./bin/yb-ctl create --rf=3 --master_flags "enable_db_clone=true,allowed_preview_flags_csv=enable_db_clone" --tserver_flag "flagfile=/net/dev-server-mhaddad/share/ybd-tserver-trust-local.conf"
sleep 3
./bin/ysqlsh
CREATE DATABASE db1;
\c db1
CREATE TABLE t (k INT PRIMARY KEY, v INT) SPLIT INTO 2 TABLETS;
\q

./build/latest/bin/yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 create_snapshot_schedule 2 60 ysql.db1
sleep 5
./bin/ysqlsh
\c db1;

--mark the time
SELECT (EXTRACT (EPOCH FROM CURRENT_TIMESTAMP)*1000000)::decimal(38,0);
-- t1= 1717668777556610

--insert 5 rows
INSERT INTO t (k,v) SELECT i,i FROM generate_series(1,5) AS i;


CREATE DATABASE db2 TEMPLATE db1 AS OF 1717702256935140;

```
After that I managed to connect to db2 and the table was empty as expected.
I also run:
`./build/latest/bin/yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_clones 00004000000030008000000000000000 1`
and the status indicates that restore is successful.
```
19:35 ~/code/yugabyte-db [yamen-ysqldump-readtime] $ ./build/latest/bin/yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_clones 00004000000030008000000000000000 1
[
    {
        "aggregate_state": "RESTORED",
        "source_namespace_id": "00004000000030008000000000000000",
        "seq_no": "1",
        "target_namespace_name": "db2",
        "restore_time": "2024-06-06 19:30:56.935140"
    }
]
```

**Comment by yamen-haddad** [comment] 2024-06-06 21:46
Was YSQL auth disabled in this universe?
If yes, then clone is failing as `ysql_dump` cannot connect to postgres using local unix domain socket. The error we are getting is:
`ysql_dump: [archiver (db)] connection to database "db1" failed: FATAL:  no pg_hba.conf entry for host "[local]", user "yugabyte", database "db1", SSL off`
After checking the `pg_hba.conf` and when ysql auth is off:
```
$ cat /mnt/d0/pg_data/ysql_hba.conf
# This is an autogenerated file, do not edit manually!
# Internal configuration:
# local all postgres yb-tserver-key
hostssl all all all trust
```
However, when ysql auth is enabled then clone should succeed. This is because we trust local connections in case ysql auth is on. As shown here:
```
$ cat /mnt/d0/pg_data/ysql_hba.conf
# This is an autogenerated file, do not edit manually!
# Internal configuration:
# local all postgres yb-tserver-key
local all yugabyte trust
hostssl all all all md5
```
So in order for clone to work we need to run ysql_dump and ysqlsh according to whether ysql auth is enabled/disabled as follows:

- When ysql auth is disabled, we guarantee that we trust connections using ssl:  hostssl all all all trust and thus we connect to pg using IP.

- When ysql quth is enabled, we guarantee that we trust local connections using unix domain sockets local all yugabyte trust and thus we connect to pg using local UDX.

**Comment by SrivastavaAnubhav** [comment] 2024-06-13 18:56
Closing as this was an authentication configuration issue.

**Closed by SrivastavaAnubhav** 2024-06-13 18:56 UTC
Labels: kind/bug, priority/medium
