### ISSUE TITLE
[DocDB] Dynamically set the db_block_cache_num_shard_bits based on the number of cores

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#17360] opened 2023-05-15 22:13 UTC
Jira Link: [DB-6553](https://yugabyte.atlassian.net/browse/DB-6553)
### Description

`db_block_cache_num_shard_bits` is used to specify the number of bits to use for sharding the block cache (defaults to 4 bits). We should auto-tune this gflag on larger core machines - instead of user having to bump this up. Basically, initialize to -1, and if number of cores is less than 16 -- leave it at 4... but other wise use 5 for 17 to 32 cores, 6 for 33-64 cores, and so on.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6553]: https://yugabyte.atlassian.net/browse/DB-6553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by appleconda** [comment] 2023-05-16 11:24
If the issue is still not resolved I would like to address the issue. I am thinking of writing a function which uses <thread> to get the number of cores and this function will rturn the appropriate shard bits which then can be assigned to db_block_cache_num_shard_bits

**Comment by rthallamko3** [comment] 2023-05-19 00:11
@appleconda , We already have something in review. If you are interested, I can assign something else to you.

**Comment by rthallamko3** [comment] 2023-06-21 19:58
Reactivating for 2.18 backport. cc @chinmay291

**Comment by rthallamko3** [comment] 2023-09-20 16:08
@es1024 , Can you complete the backport for 2.18, as chinmay's internship is done.

**Closed** 2023-09-21 15:23 UTC
Labels: kind/enhancement, good first issue, area/docdb, priority/medium, 2.18 Backport Required
