### ISSUE TITLE
[YSQL]Partitioned table unique index allowing duplicates

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#11136] opened 2022-01-19 16:24 UTC
### Description

Unique constraint not violated allowing duplicates for the primary key on a partitioned table. 

```
yugabyte=# \d+ foo
                                    Table "public.foo"
 Column |  Type   | Collation | Nullable | Default | Storage  | Stats target | Description
--------+---------+-----------+----------+---------+----------+--------------+-------------
 a      | integer |           | not null |         | plain    |              |
 b      | date    |           | not null |         | plain    |              |
 c      | text    |           |          |         | extended |              |
Partition key: RANGE (b)
Indexes:
    "foo_pkey" PRIMARY KEY, lsm (a HASH, b ASC)
Partitions: b_202001 FOR VALUES FROM ('2020-01-01') TO ('2020-02-01'),
            b_202002 FOR VALUES FROM ('2020-02-01') TO ('2020-03-01'),
            b_202003 FOR VALUES FROM ('2020-03-01') TO ('2020-04-01')

yugabyte=# insert into foo(a,b,c) values(1,'2020-01-05','CA');
INSERT 0 1
yugabyte=# insert into foo(a,b,c) values(1,'2020-01-05','CA');
INSERT 0 1
yugabyte=# insert into foo(a,b,c) values(1,'2020-01-05','GA');
INSERT 0 1
yugabyte=# select * from foo;
 a |     b      | c
---+------------+----
 1 | 2020-01-05 | CA
 1 | 2020-01-05 | CA
 1 | 2020-01-05 | GA
(3 rows)
```

**Comment by adil246** [comment] 2022-01-19 16:34
Ref Issue - https://github.com/yugabyte/yugabyte-db/issues/6149

**Comment by kmuthukk** [comment] 2022-01-19 17:39
@adil246 -- 

Can you share all the DDL used to create the parent table & child partitions?

**Comment by adil246** [comment] 2022-01-19 19:24
> @adil246 --
> 
> Can you share all the DDL used to create the parent table & child partitions?

@kmuthukk @deeps1991 Here is the DDL

```
CREATE TABLE foo (
    a integer NOT NULL,
    b date NOT NULL,
    c text,
    PRIMARY KEY((a) HASH, b ASC)
)
PARTITION BY RANGE (b);

CREATE TABLE b_202001 PARTITION OF foo (
    PRIMARY KEY((a) HASH, b ASC)
)
FOR VALUES FROM ('2020-01-01') TO ('2020-02-01');

CREATE TABLE b_202002 PARTITION OF foo (
    PRIMARY KEY((a) HASH, b ASC)
)
FOR VALUES FROM ('2020-02-01') TO ('2020-03-01');

CREATE TABLE b_202003 PARTITION OF foo (
    PRIMARY KEY((a) HASH, b ASC)
)
FOR VALUES FROM ('2020-03-01') TO ('2020-04-01');
```

**Comment by adil246** [comment] 2022-01-19 19:30
This was in v 2.6.3
```
[yugabyte@yb-dev-aakram-support-issues-n2 bin]$ ./ysqlsh -h `hostname` -c 'show server_version;' -c '\q'
   server_version
--------------------
 11.2-YB-2.6.3.0-b0
(1 row)

```

**Comment by deeps1991** [comment] 2022-01-20 01:32
This is a duplicate of #6149. The back port to 2.6.3 is still in progress, which is why you are seeing the above issue. 

Also JFYI:
The above DDL wouldn't even work in master:
```
ERROR:  multiple primary keys for table "b_202001" are not allowed
```
This is because the primary key should either be specified while creating the parent or while creating the children. Not in both places (PG has the same behavior).

**Closed by deeps1991** 2022-01-20 01:32 UTC
Labels: area/ysql
