### ISSUE TITLE
[Docs] yb-ts-cli: add certs_dir_name flag

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#10017] opened 2021-09-15 18:59 UTC
Add the `--certs_dir_name` flag to [yb-ts-cli](https://docs.yugabyte.com/latest/admin/yb-ts-cli/#flags). It's the same flag and meaning as the one for [yb-admin](https://docs.yugabyte.com/latest/admin/yb-admin/)

**Comment by ddorian** [comment] 2023-05-07 08:47
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/13571

**Closed by ddorian** 2023-05-07 08:47 UTC
Labels: area/documentation, temp/docs-migration
