### ISSUE TITLE
[tsan] Potential race condition in our cpp Cassandra driver in LoadBalancingPolicy

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#877] opened 2019-02-16 06:45 UTC
We seem to have a data race in our cpp cassandra driver. Detected from a TSAN run of one of our tests: `ybd tsan --cxx-test integration-tests_cassandra_cpp_driver-test --gtest_filter CppCassandraDriverTest.TestInsertLocality`

TSAN warning:
```
2519 | WARNING: ThreadSanitizer: data race (pid=13470)
2520 | Read of size 8 at 0x7b100016b490 by thread T36:
2521 | #0 cass::LoadBalancingPolicy::control_connection() $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/load_balancing.cpp:21:10 (libcassandra.so.2+0xedbca)
2522 | #1 cass::PartitionAwarePolicy::on_work(cass::PeriodicTask*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/partition_aware_policy.cpp:319:15 (libcassandra.so.2+0x1331b6)
2523 | #2 cass::PeriodicTask::on_work(uv_work_s*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/periodic_task.hpp:76:5 (libcassandra.so.2+0xecc5b)
2524 | #3 uv__queue_work $YB_THIRDPARTY_DIR/build/tsan/libuv-1.23.0/../../../src/libuv-1.23.0/src/threadpool.c:259:3 (libuv.so+0xb365)
2525 | #4 worker $YB_THIRDPARTY_DIR/build/tsan/libuv-1.23.0/../../../src/libuv-1.23.0/src/threadpool.c:83:5 (libuv.so+0xb6f7)
2526 |  
2527 | Previous write of size 8 at 0x7b100016b490 by thread T34:
2528 | #0 cass::LoadBalancingPolicy::init_session(cass::Session*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/load_balancing.hpp:90:57 (libcassandra.so.2+0x8ca1e)
2529 | #1 cass::ChainedLoadBalancingPolicy::init_session(cass::Session*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/load_balancing.hpp:131 (libcassandra.so.2+0x8ca1e)
2530 | #2 cass::LoadBalancingPolicy::new_query_plan(string const&, cass::RequestHandler*, cass::Session*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/load_balancing.hpp:100:5 (libcassandra.so.2+0x8cb43)
2531 | #3 cass::RequestHandler::init(cass::Session*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/request_handler.cpp:125:53 (libcassandra.so.2+0x14ce4f)
2532 | #4 cass::Session::on_execute(uv_async_s*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:823:24 (libcassandra.so.2+0x162c24)
2533 | #5 uv__async_io $YB_THIRDPARTY_DIR/build/tsan/libuv-1.23.0/../../../src/libuv-1.23.0/src/unix/async.c:118:5 (libuv.so+0x1030b)
2534 | #6 uv__io_poll $YB_THIRDPARTY_DIR/build/tsan/libuv-1.23.0/../../../src/libuv-1.23.0/src/unix/linux-core.c:401:11 (libuv.so+0x28593)
2535 | #7 uv_run $YB_THIRDPARTY_DIR/build/tsan/libuv-1.23.0/../../../src/libuv-1.23.0/src/unix/core.c:370:5 (libuv.so+0x10b96)
2536 | #8 cass::LoopThread::on_run_internal(void*) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/loop_thread.hpp:128:5 (libcassandra.so.2+0x16c7bd)
2537 |  
2538 | Location is heap block of size 56 at 0x7b100016b480 allocated by main thread:
2539 | #0 operator new(unsigned long) $YB_THIRDPARTY_DIR/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/compiler-rt/lib/tsan/rtl/tsan_new_delete.cc:65 (cassandra_cpp_driver-test+0x4d4d07)
2540 | #1 cass::Config::new_instance() const $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/config.hpp:111:15 (libcassandra.so.2+0x167e93)
2541 | #2 cass::Session::clear(cass::Config const&) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:171:20 (libcassandra.so.2+0x162081)
2542 | #3 cass::Session::connect_async(cass::Config const&, string const&, cass::SharedRefPtr<cass::Future> const&) $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:343:3 (libcassandra.so.2+0x15efc6)
2543 | #4 cass_session_connect_keyspace_n $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:66:12 (libcassandra.so.2+0x15eda0)
2544 | #5 cass_session_connect_keyspace $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:55:10 (libcassandra.so.2+0x15eb99)
2545 | #6 cass_session_connect $YB_THIRDPARTY_DIR/build/tsan/cassandra-cpp-driver-2.9.0-yb-4/../../../src/cassandra-cpp-driver-2.9.0-yb-4/src/session.cpp:49 (libcassandra.so.2+0x15eb99)
2546 | #7 yb::CppCassandraDriver::CppCassandraDriver(yb::ExternalMiniCluster const&) /net/centos-gcp-cloud-jenkins-slave-1ac/share/jenkins/workspace/yugabyte-phabricator@2/build/tsan-clang-dynamic-enterprise-ninja/../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:89:28 (cassandra_cpp_driver-test+0x4e5c0c)
2547 | #8 yb::CppCassandraDriverTest::SetUp() /net/centos-gcp-cloud-jenkins-slave-1ac/share/jenkins/workspace/yugabyte-phabricator@2/build/tsan-clang-dynamic-enterprise-ninja/../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:184:19 (cassandra_cpp_driver-test+0x4e1149)
2548 | #9 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x55c5f)
2549 | #10 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x55c5f)
2550 | #11 testing::Test::Run() $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2470:3 (libgmock.so+0x34f11)
2551 | #12 testing::TestInfo::Run() $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2656:11 (libgmock.so+0x3629c)
2552 | #13 testing::TestCase::Run() $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36d76)
2553 | #14 testing::internal::UnitTestImpl::RunAllTests() $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x430c6)
2554 | #15 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56bcf)
2555 | #16 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56bcf)
2556 | #17 testing::UnitTest::Run() $YB_THIRDPARTY_DIR/build/tsan/googletest-release-1.8.0/shared/googlemock/../../../../../src/googletest-release-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42971)
2557 | #18 RUN_ALL_TESTS() $YB_THIRDPARTY_DIR/installed/tsan/include/gtest/gtest.h:2233:46 (libyb_test_main.so+0x505b)
2558 | #19 main /net/centos-gcp-cloud-jenkins-slave-1ac/share/jenkins/workspace/yugabyte-phabricator@2/build/tsan-clang-dynamic-enterprise-ninja/../../src/yb/util/test_main.cc:104:13 (libyb_test_main.so+0x4cad)
```

cc @mbautin @OlegLoginov

**Comment by OlegLoginov** [comment] 2020-11-06 18:08
It should be fixed by the commit: yugabyte/cassandra-cpp-driver@bccc76e

So, it's a duplicate of #1837

**Closed by OlegLoginov** 2020-11-06 18:08 UTC
Labels: kind/bug
