### ISSUE TITLE
[Platform] Delete backup option is enabled for Inprogress backup

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8448] opened 2021-05-14 06:55 UTC
Can we delete Inprogress backup? There is NO action button for Inprogress backup which means its restricted from deleting this backup. But the new "Delete backup" button gets enabled if we select (small checkbox) for the inprogress backup. Eventhough its not able to delete it, this option should be disabled for inprogress. It might cause inconsistent data if we delete half way.

**Comment by streddy-yb** [comment] 2021-05-18 00:30
Duplicate of #8481

**Closed by streddy-yb** 2021-05-18 00:30 UTC
Labels: area/platform, team/platform-hi
