### ISSUE TITLE
[xCluster][DB-Scope DR] Replication failing with error ColocationId not found

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#23177] opened 2024-07-11 04:29 UTC
Jira Link: [DB-12116](https://yugabyte.atlassian.net/browse/DB-12116)
### Description

Setup:
xCluster(DB-Scope DR) + colocation + Copy commands 

Observed on version `2024.1.1.0-b127`
Error: 
```
E0710 22:56:07.960215 113130 xcluster_output_client.cc:657] Error while applying replicated record: Not found (yb/tserver/xcluster_output_client.cc:287): ColocationId 40000 not found., consumer tablet: 846e488bed384d00ab6c7d3fe32bbed1
```
Master UI shows that both clusters have tables with the same colocation id
![image (6)](https://github.com/yugabyte/yugabyte-db/assets/121818428/7ddce890-e212-4cbf-af3f-72c3f6233df0)

Query to create table:
```
CREATE TABLE employees_col_cpy(id text, uuid_col uuid DEFAULT uuid_generate_v4 (), name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX", date DATE, n NUMERIC (3, 2), r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT, t1 TIME, ts1 TIMESTAMP, i4 INTERVAL, p2 path, p3 polygon, b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code, PRIMARY KEY(id, name, uuid_col, age)) WITH (colocated = True,COLOCATION_ID=40000)
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12116]: https://yugabyte.atlassian.net/browse/DB-12116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by agsh-yb** [comment] 2024-07-11 07:22
cc: @kripasreenivasan

**Comment by lingamsandeep** [comment] 2024-07-18 15:13
Duplicate of #23188

**Closed by lingamsandeep** 2024-07-18 15:13 UTC
Labels: kind/bug, area/docdb, priority/medium, QA, status/awaiting-triage, qa_automation, qa_itest-system, 2024.1.1_blocker, 2024.1.2_blocker, 2024.2_blocker
