### ISSUE TITLE
[ysql] Support deleting all rows from a PostgreSQL table by reusing the TRUNCATE implementation we have for YCQL (and FLUSHDB/FLUSHALL for Redis)

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#563] opened 2018-11-08 01:33 UTC
From @robertpang : We should be able to support TRUNCATE table given we have the support for YCQL already.

**Comment by robertpang** [comment] 2019-04-16 22:26
Duplicate of #693.

**Closed by robertpang** 2019-04-16 22:26 UTC
Labels: enhancement
