### ISSUE TITLE
[DocDB] 'Unexpected new leader in same term!' FATAL is found in long running tests

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16985] opened 2023-04-24 02:52 UTC
Jira Link: [DB-6307](https://yugabyte.atlassian.net/browse/DB-6307)
### Description

In one of the long running tests with CDC, after ~16 hours saw a fatal.

Yugabyte version: 2.18.0.0-b16

Find stress report in JIRA.

```
F20230421 21:42:00 ../../src/yb/consensus/raft_consensus.cc:1816] T 61bdb0d9e0184ea098f49cdfb41b18de P e34f253e93ff488ba6ff7422ced1f177 [term 61 FOLLOWER]: Unexpected new leader in same term! Existing leader UUID: 49fce80784b643e1b3d3b3f265350cee, new leader UUID: 49fce80784b643e1...<32 bytes total>
    @     0x55d595e61b07  google::LogMessage::SendToLog()
    @     0x55d595e62a4d  google::LogMessage::Flush()
    @     0x55d595e630c9  google::LogMessageFatal::~LogMessageFatal()
    @     0x55d596307d33  yb::consensus::RaftConsensus::CheckLeaderRequestUnlocked()
    @     0x55d596302aa4  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x55d5962e758b  yb::consensus::RaftConsensus::Update()
    @     0x55d597139d7d  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x55d5963656ad  std::__1::__function::__func<>::operator()()
    @     0x55d59636626f  yb::consensus::ConsensusServiceIf::Handle()
    @     0x55d596e060ea  yb::rpc::ServicePoolImpl::Handle()
    @     0x55d596d45ecf  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x55d596e14c83  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x55d5974d4bb2  yb::Thread::SuperviseThread()
    @     0x7fb21a649694  start_thread
    @     0x7fb21ab4b41d  __clone

```

![Profile (5)](https://user-images.githubusercontent.com/109518123/233889186-bf1a01e6-d919-498a-9f90-4bbb9cf23a36.png)

Gflags I had:

```
master_gflags={'enable_automatic_tablet_splitting': 'true',
                           'tablet_split_low_phase_size_threshold_bytes': 35001520, 
                           'tablet_split_limit_per_table': 149, 
                           'tablet_split_low_phase_shard_count_per_node': 134217728,
                           'ysql_num_shards_per_tserver': 1,
                           'yb_num_shards_per_tserver': 1,
                           'ysql_enable_packed_row': 'true',
                           'ycql_enable_packed_row': 'true',
                           'enable_stream_compression': 'true',
                           'stream_compression_algo': 1,
                           'ysql_enable_packed_row_for_colocated_table': 'true'},
            tserver_gflags={'enable_automatic_tablet_splitting': 'true',
                            'yb_num_shards_per_tserver': 1,
                            'ysql_num_shards_per_tserver': 1,
                            'ysql_enable_packed_row': 'true',
                            'ycql_enable_packed_row': 'true',
                            'enable_stream_compression': 'true',
                            'stream_compression_algo': 1,
                            'ysql_enable_packed_row_for_colocated_table': 'true',
                            'scheduled_full_compaction_jitter_factor_percentage': 100,
                            'scheduled_full_compaction_frequency_hours': 12,
                            'scheduled_full_compaction_check_interval_min': 5}
        )]),
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6307]: https://yugabyte.atlassian.net/browse/DB-6307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-04-26 17:25
Removing the 2.18.0_blocker label as the FATAL is a result of network partition caused by network nemesis in the test. The tserver recovers well after the FATAL.

**Comment by rthallamko3** [comment] 2023-09-26 22:32
@shamanthchandra-yb , Do we still run into this issue?

**Comment by shamanthchandra-yb** [comment] 2023-09-27 06:32
@rthallamko3 I had hit this almost ~2 months back once in one of the CDC case: http://stress.dev.yugabyte.com/stress_test/daffed5e-eb68-4422-aec7-a2fda6e56569

But this is very rare, with the combination of network nemesis in some scenario.

Probably, I will need to add this as known_fatal as we expect it to recover as per above comment and see.

**Comment by rthallamko3** [comment] 2023-09-27 17:15
Closing the issue based on the above notes. cc @shamanthchandra-yb

**Closed by rthallamko3** 2023-09-27 17:15 UTC
Labels: kind/bug, area/docdb, priority/high, qa_automation
