### ISSUE TITLE
[YSQL] Orphaned postgres backend cannot be killed (SIGTERM)

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#8615] opened 2021-05-25 20:50 UTC
Jira Link: [DB-1861](https://yugabyte.atlassian.net/browse/DB-1861)
I have run into a number orphaned of Postgres backends which are unable to terminate cleanly. They survived the failure of the Postmaster, and were unresponsive to SIGTERM.

```
$ ps -ef | grep postgres
yugabyte 11032 10897 0 May18 ? 00:00:45 /home/yugabyte/yb-software/yugabyte-2.4.3.0-b6-centos-x86_64/postgres/bin/postgres -D /data/pg_data -p 5433 -h 0.0.0.0 -k /tmp/.yb.8228272234018189749 -c unix_socket_permissions=0700 -c logging_collector=on -c log_directory=/data/yb-data/tserver/logs -c shared_preload_libraries=pg_stat_statements,yb_pg_metrics,pgaudit -c yb_pg_metrics.port=13000 -c config_file=/data/pg_data/ysql_pg.conf -c hba_file=/data/pg_data/ysql_hba.conf
yugabyte 11121 11032 0 May18 ? 00:00:00 postgres: logger
yugabyte 11125 11032 0 May18 ? 00:00:35 postgres: YSQL webserver
yugabyte 11143 11032 0 May18 ? 00:00:00 postgres: checkpointer
yugabyte 11144 11032 0 May18 ? 00:00:00 postgres: stats collector
yugabyte 22609 1 0 May06 ? 00:22:38 postgres: yugabyte yugabyte 127.0.0.1(53018) idle <--- Orphaned postgres process
yugabyte 28899 1 0 May06 ? 00:25:49 postgres: yugabyte yugabyte 127.0.0.1(57758) idle <--- Orphaned postgres process
yugabyte 31414 11032 0 21:25 ? 00:00:00 /home/yugabyte/yb-software/yugabyte-2.4.3.0-b6-centos-x86_64/postgres/bin/postgres -D /data/pg_data -p 5433 -h 0.0.0.0 -k /tmp/.yb.8228272234018189749 -c unix_socket_permissions=0700 -c logging_collector=on -c log_directory=/data/yb-data/tserver/logs -c shared_preload_libraries=pg_stat_statements,yb_pg_metrics,pgaudit  -c yb_pg_metrics.port=13000 -c config_file=/data/pg_data/ysql_pg.conf -c hba_file=/data/pg_data/ysql_hba.conf
root 31419 30615 0 21:25 pts/0 00:00:00 grep --color=auto postgres
```

 In every case they had the below stack trace:

```
Thread 1 (process 22609):
#0 0x00007f9afaee046d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1 0x00007f9afbe636aa in sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /home/yugabyte/yb-software/yugabyte-2.4.1.0-b25-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/thread:293
__ts = {tv_sec = 0, tv_nsec = 10000000}
#2 yb::internal::ThreadList<yb::internal::URCUThreadData>::~ThreadList (this=0x7f9afc2110a0 <yb::internal::ThreadList<yb::internal::URCUThreadData>::Instance()::result>, __in_chrg=<optimized out>) at ../../src/yb/util/concurrent_value.h:57
current_thread_id = {_M_thread = 140303655748224}
desired_allocated_threads = 0
#3 0x00007f9afa564969 in __run_exit_handlers (status=status@entry=0, listp=0x7f9afa8c55c0 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
atfct = <optimized out>
onfct = <optimized out>
cxafct = <optimized out>
f = <optimized out>
#4 0x00007f9afa5649b5 in __GI_exit (status=status@entry=0) at exit.c:104
No locals.
#5 0x000000000084021c in proc_exit (code=code@entry=0) at ../../../../../../../src/postgres/src/backend/storage/ipc/ipc.c:156
__func__ = "proc_exit"
#6 0x000000000086eb57 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x3270358, dbname=0x3270208 "yugabyte", username=0x32701e8 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5337
firstchar = 88
input_message = {data = 0x3275968 "", len = 0, maxlen = 1024, cursor = 0}
local_sigjmp_buf = {{__jmpbuf = {15740248, 4031564978946147990, 1474973306, 10936258, 52888416, 1, 4031564978883233430, -4032047011002218858}, __mask_was_saved = 1, __saved_mask = {__val = {0, 0, 140723977794400, 35184372088832, 15441536, 0, 0,
0, 0, 0, 0, 0, 0, 140723977794464, 140723977794464, 12347012}}}}
send_ready_for_query = false
disable_idle_in_transaction_timeout = false
__func__ = "PostgresMain"
#7 0x000000000049a8af in BackendRun (port=0x32c1f20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4428
ac = 1
secs = 673626160
usecs = 590849
i = 1
av = 0x3270358
maxac = <optimized out>
#8 BackendStartup (port=0x32c1f20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4094
bn = <optimized out>
pid = <optimized out>
#9 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1737
rmask = {fds_bits = {8, 0 <repeats 15 times>}}
selres = <optimized out>
now = <optimized out>
readmask = {fds_bits = {40, 0 <repeats 15 times>}}
last_lockfile_recheck_time = <optimized out>
last_touch_time = 1620310009
__func__ = "ServerLoop"
#10 0x00000000007d6a51 in PostmasterMain (argc=argc@entry=25, argv=argv@entry=0x326e9f0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1400
opt = <optimized out>
status = <optimized out>
userDoption = <optimized out>
listen_addr_saved = true
i = <optimized out>
output_config_variable = <optimized out>
__func__ = "PostmasterMain"
#11 0x00000000007229ba in PostgresServerProcessMain (argc=25, argv=0x326e9f0) at ../../../../../../src/postgres/src/backend/main/main.c:234
do_check_root = <optimized out>
#12 0x0000000000722bb9 in main ()
```

They appear to be stuck in this descructor: `yb::internal::ThreadList<yb::internal::URCUThreadData>::~ThreadList`

**Comment by tedyu** [comment] 2021-05-26 02:51
Does 2.4.1.0-b25 contain backport for commit 1e27ad7524fe3092cff60b8e534cd75b933656ec ?

Fix a deadlock on URCU shutdown

**Comment by sushantrmishra** [comment] 2022-08-25 06:33
https://github.com/yugabyte/yugabyte-db/issues/11343 and https://github.com/yugabyte/yugabyte-db/issues/12784 should ideally address this issue. Closing it for now, please reopen if the issue is seen again.

**Closed by sushantrmishra** 2022-08-25 06:33 UTC
Labels: kind/bug, area/ysql, priority/medium
