### ISSUE TITLE
Document details of user enforced consistency

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#1696] opened 2019-06-13 23:20 UTC
Used for higher performance of writes in inserts where consistency semantics can be relaxed. Typically used in streaming apps where high ingest is required.

## Details

**Main caveat: If an insert/update or batch of such operations fails, it is the app's responsibility to retry the operation so that the index is consistent.** Much like in a 2-table case, it would have been the apps responsibility to retry (in case of a failure between the update to the two tables) to make sure both tables are in sync again.

Main advantage of this approach rather than you having to use a second table is for UPDATE cases where the old index record has to be deleted from the table, and so would be an extra roundtrip to the database.

## Example

Notice that here the table is not marked with transactions enabled. And the index has the 'consistency_level' : 'user_enforced'  clause. # Example

```
create table example (
  ...,
  PRIMARY KEY (...)
) WITH CLUSTERING ORDER BY (...)
   AND transactions = { 'enabled' : false };

CREATE INDEX example_index ON example (...) INCLUDE (cluster_size)
    WITH CLUSTERING ORDER BY(...)
    AND transactions = { 'enabled' : false, 'consistency_level' : 'user_enforced' };
```

**Comment by ddorian** [comment] 2023-02-06 12:25
From #6082 that was a duplicate of this:

Typical trying to create table and index:

```cql
CREATE TABLE t (i int PRIMARY KEY, j int);
CREATE INDEX ON t (j);
```

```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid Table Definition. Transactions cannot be enabled in an index of a table without transactions enabled.
CREATE INDEX ON t (j);
^^^^^^
 (ql error -302)"
```

Okay...  Look at [the documentation][1] and find

> `WITH transactions = { 'enabled' : true };`

Let's try it with false to disable transactions.

```cql
CREATE INDEX ON t (j) WITH transactions = { 'enabled' : false };
```

```
ycqlsh:k> CREATE INDEX ON t (j) WITH transactions = { 'enabled' : false };
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid Table Definition. Consistency level must be user-enforced in an index without transactions enabled.
CREATE INDEX ON t (j) WITH transactions = { 'enabled' : false };
^^^^^^
 (ql error -302)"
```

Okay...  Look at [the documentation][1] again, but don't find anything about "consistency level" or "user enforced" (search terms "consistency" and "enforced" don't show up on the page at all).

Go to GitHub issues and search until coming up with [a good query][2] leading to issue #1591 that shows

> `transactions = {'enabled' : FALSE, 'consistency_level' : 'user_enforced'};`

Let's try it with that.

```cql
CREATE INDEX ON t (j) WITH transactions = { 'enabled' : false, 'consistency_level' : 'user_enforced' };
DESC t;
```

```
CREATE TABLE k.t (
    i int PRIMARY KEY,
    j int
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
CREATE INDEX t_j_idx ON k.t (j, i)
    WITH transactions = {'enabled': 'false', 'consistency_level': 'user_enforced'};
```

Finally works.  If one has no idea and doesn't care what transactions and user enforced are, the steps one has to take to make it work are not fun.  This information should be clear in the docs (even `WITH transactions` isn't in the grammar at the top of the page).

[1]: https://docs.yugabyte.com/latest/api/ycql/ddl_create_index/
[2]: https://github.com/yugabyte/yugabyte-db/issues?q=is%3Aissue+is%3Aopen+Consistency+level+must+be+user-enforced+in+an+index+without+

**Closed** 2023-11-05 01:28 UTC
Labels: area/documentation, temp/docs-migration
