### ISSUE TITLE
[YCQL] Spurious "Object Not Found" errors when dropping a table

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3133] opened 2019-12-11 22:17 UTC
The table itself gets dropped successfully.

Example:
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. The object does not exist: table_name: "some_table_name"
namespace {
  name: "some_keyspace_name"
}
```
YugabyteDB version: 1.3.2.5 build 2 revision 2f2be51472692661993d38bf974f9ad0c098d897

**Comment by smalyshev** [comment] 2019-12-11 22:50
Not sure if related, but sometimes I also get error like this:
```
ServerError: The table '71490c8919be4d60a9a428f19f8fb270.counters' does not exist
```
working with existing keyspace and existing table. If I repeat the query, it goes away.

**Comment by OlegLoginov** [comment] 2019-12-12 19:01
The issue happens if the DeleteTable takes more 5 sec (default timeout).
In such case internal request from CQL Server (client code) to Master fails with Timeout error, and CQL Server sends the request once again. But the table was marked as DELETING, so the Master returns 'Object Not Found'.

Fix (locally tested):  
```
index cda446a96..7b53e9d8d 100644
--- a/src/yb/client/client-internal.cc
+++ b/src/yb/client/client-internal.cc
@@ -573,7 +573,6 @@ Status YBClient::Data::DeleteTable(YBClient* client,
   const Status s = SyncLeaderMasterRpc<DeleteTableRequestPB, DeleteTableResponsePB>(
       deadline, client, req, &resp,
       &attempts, "DeleteTable", &MasterServiceProxy::DeleteTable);
-  RETURN_NOT_OK(s);
 
   if (resp.has_error()) {
     if (resp.error().code() == MasterErrorPB::OBJECT_NOT_FOUND && attempts > 1) {
@@ -584,6 +583,8 @@ Status YBClient::Data::DeleteTable(YBClient* client,
     } else {
       return StatusFromPB(resp.error().status());
     }
+  } else {
+    RETURN_NOT_OK(s);
   }
 
   // Spin until the table is fully deleted, if requested.
```

**Comment by OlegLoginov** [comment] 2019-12-12 19:10
Local reproducer:
```
./bin/yb-ctl create --num_shards_per_tserver 32 --replication_factor 3
```
```
cqlsh:a> create table t (id int primary key) with transactions = {'enabled':true};
cqlsh:a> create index i12 on t(id);
cqlsh:a> create index i11 on t(id);
cqlsh:a> drop table t;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. The object does not exist: table_name: "t"
namespace {
  name: "a"
  database_type: YQL_DATABASE_CQL
}
drop table t;
           ^
 (ql error -301)"
```
The main point - number of shards (tablets) for the table with indexes must be big enough to make yb::master::CatalogManager::DeleteTable() taking > 5 sec.

**Comment by OlegLoginov** [comment] 2019-12-12 19:12
NOTE: The issue is in the return code only. The table is successfully deleted in fact, so the wrong error code can be just ignored.

**Comment by OlegLoginov** [comment] 2019-12-24 18:42
Fixed by the commit:
https://github.com/yugabyte/yugabyte-db/commit/a70ab64b07f4fcaf658805c71e595ec5a7f781de

**Closed by OlegLoginov** 2019-12-24 18:42 UTC
