### ISSUE TITLE
[docdb] leader election failing when a tablet is being moved to a different node

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3293] opened 2020-01-08 21:08 UTC
When decommissioning a node, first we move the tablets off that node. During this time, we have seen sometimes a tablet has no leader temporarily. At this time there are 4 peers in the quorum. We need to investigate why there is no leader. Eventually it recovers and the 4th peer is removed and a leader is elected.
This was observed on 1.3.2.3.

**Comment by bmatican** [comment] 2020-06-12 21:37
I think this is a duplicate of #4298 which @iSignal recently fixed.

**Closed by bmatican** 2020-06-12 21:37 UTC
Labels: area/docdb, kind/bug, priority/high
