### ISSUE TITLE
[YSQL] "Discard not supported exception" from EntityFramework

### ISSUE THREAD

**Issue by azeemshahzad** [yugabyte/yugabyte-db#1512] opened 2019-06-10 03:57 UTC
EntityFramework throws following exception while trying to run DDL against YugaByte-1.2.9

fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (101ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "products" (
          "product_id" bigserial NOT NULL,
          "description" varchar(255) NULL,
          "price" decimal(10,2) NOT NULL,
          "product_name" varchar(50) NULL,
          CONSTRAINT "PK_products" PRIMARY KEY ("product_id")
      );
Npgsql.PostgresException (0x80004005): 0A000: DISCARD not supported yet
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadPrependedMessages(Boolean async)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Application startup exception: Npgsql.PostgresException (0x80004005): 0A000: DISCARD not supported yet
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadPrependedMessages(Boolean async)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at YugaByteStore.Startup.SeedData.Initialize(IServiceProvider serviceProvider) in /orm-examples/c#.net/entityframework/Startup.cs:line 59
   at YugaByteStore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /orm-examples/c#.net/entityframework/Startup.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception/

**Comment by aclemmensen** [comment] 2019-09-18 19:27
I believe it's related to how Npgsql attempts to clear session variables: https://www.npgsql.org/doc/performance.html#pooled-connection-reset

You can disable it by adding the following to your connection string: `No Reset On Close=true;`

**Comment by kmuthukk** [comment] 2019-09-18 20:10
Thx for the pointer @aclemmensen .

**Comment by ndeodhar** [comment] 2020-01-17 00:43
Duplicate of 2491. It has been fixed now.

**Closed by ndeodhar** 2020-01-17 00:43 UTC
Labels: area/sql, community/request
