### ISSUE TITLE
[Platform] [Bug] Node doesn't appear on UI during universe creation process

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#7868] opened 2021-03-30 22:07 UTC
**Issue:** 

This issue is noted in Azure on-prem workflow. On-prem nodes don't appear on the platform UI while creating the universe. The nodes were part of the already deleted universe. 

The `in_use` column has the value `t`  in the node_instance table for the particular node. Deleting universe doesn't seem to update this table. 

Zendesk issue: https://yugabyte.zendesk.com/agent/tickets/1016

Let me know if you need more info.

**Comment by adil246** [comment] 2021-03-31 18:16
@tylarb This was in the 2.4.1 version.

**Comment by hkandala** [comment] 2021-04-19 09:23
Able to replicate in 2.4.1 but not in latest version. After analyzing the code flow realized fix for this issue is already taken care with this commit [5466bfd](https://github.com/yugabyte/yugabyte-db/commit/5466bfded0e5801b72963350b5c6cf5377be809c). Marking the current issue as duplicate to #6758
@streddy-yb, let know if this needs to be backported to 2.4.1

**Comment by hkandala** [comment] 2021-04-19 09:23
Duplicate #6758

**Comment by hkandala** [comment] 2021-04-19 09:25
Duplicate of #6758

**Closed** 2021-04-20 03:57 UTC
Labels: area/platform
