### ISSUE TITLE
[CDC] Error tracking for dropped records

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3807] opened 2020-03-02 22:13 UTC
Today, our CDC / 2DC metrics are focused on replication lag. We should also add some correctness metrics and visibility. For example, how can we identify if a record was dropped during replication and did not make it to the consumer successfully?

**Comment by nspiegelberg** [comment] 2022-10-21 22:14
Duplicate of #10645

**Closed by nspiegelberg** 2022-10-21 22:14 UTC
Labels: area/cdc
