### ISSUE TITLE
[Docs] YugabyteDB Core: fail to start cluster on macOS Monterey

### ISSUE THREAD

**Issue by dmagda** [yugabyte/yugabyte-db#11240] opened 2022-01-26 19:30 UTC
### Description

We need to revisit at least the following two pages for the macOS scenario:

- https://docs.yugabyte.com/latest/quick-start/install/macos/
- https://docs.yugabyte.com/latest/quick-start/create-local-cluster/macos/

I got the exception below when was trying to launch the database with the command `./bin/yugabyted start`

```
bash: pstree: command not found
bash: pstree: command not found
ps: Invalid process id: f34
bash: pstree: command not found
ps: Invalid process id: f35
F0126 10:42:39.444931 14702080 master_main.cc:140] Network error (yb/server/webserver.cc:245): Webserver: Could not start on address 0.0.0.0:7000
```

To solve the issues, I did the following:

- installed `pstree` with `brew install pstree`
- changed the webserver port number to the one different from default `7000`. Turns out that you can easily change the port in the `{directory_created_by_yugabytedb}/var/conf/﻿yugabyted.conf`. But, our documentation doesn't mention the `yugabyted.conf` file and settings that can be adjusted there.

That's the reason why our web server can't longer listen on `7000` on the latest macOS versions: https://developer.apple.com/forums/thread/682332

**Comment by polarweasel** [comment] 2022-01-27 18:37
`pstree` shouldn't be a requirement to run locally. It runs on mine without, but it _is_ required to build from source, as it's used in one place in the source.

This ticket, otherwise, should be a duplicate of #11062. Please reopen if that's not the case — or better, please comment on the other ticket so we can address all issues at once.

**Closed by polarweasel** 2022-01-27 18:38 UTC
Labels: area/documentation, DevRel
