### ISSUE TITLE
Build error on Ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by mirageyjd** [yugabyte/yugabyte-db#4369] opened 2020-05-01 21:42 UTC
The cmake version is 3.17.2, the gcc version is 7.1.0, and the installed dependecies are as followed: 

`sudo apt-get install uuid-dev libbz2-dev libreadline-dev maven ninja-build cmake curl rsync python-pip zip autoconf libtool pkg-config libssl1.0-dev libicu-dev bison flex`

![error](https://user-images.githubusercontent.com/54912085/80843506-1dedcd80-8bca-11ea-905b-536da682f787.png)

**Comment by kmuthukk** [comment] 2020-05-01 23:41
hi @svarnau -- assigning this to you. If you need full logs, please feel free to request.

**Comment by svarnau** [comment] 2020-05-04 22:51
I was able to re-produce this on Ubuntu 16.04.  I also tried to follow web page and install missing dependencies as I went. I ended up with similar list as @mirageyjd, though I installed libssl-dev instead of the 1.0 version.

I think the issue is that postgres gets built before libssl is installed, so the missing library does not get built.  I was able to progress further by doing:  ./yb_build.sh --rebuild-postgres release

**Comment by svarnau** [comment] 2020-05-04 23:42
Along with installing maven 3.5 and JDK1.8 as the web page says, and I was able to complete build on ubuntu 16.04.

So the real problem here is that the ubuntu build page is incomplete with the dependency list. If you start building before ssl is installed, postgres is incomplete.  I will propose a change to that web page, before I close this issue.

**Comment by svarnau** [comment] 2020-05-05 15:38
Addressed by existing PR: https://github.com/yugabyte/yugabyte-db/pull/3888

**Closed** 2020-05-20 19:54 UTC
Labels: community/request
