### ISSUE TITLE
DB and Table creation delay

### ISSUE THREAD

**Issue by markwylde** [yugabyte/yugabyte-db#1939] opened 2019-07-31 04:53 UTC
One issue we're seeing is that creating databases and table's takes around 10 seconds. We have tried both a replication factor of 1 and also 3 but the same effect on both.

We've also looked at the option here:
https://github.com/YugaByte/yugabyte-db/commit/6831eabf1be4caf5f167711de1bd2ffc894783ef

But it didn't seem to change anything.

We're just using the docker ctl to provision the cluster on an Ubuntu host.

## Attempt 1
```bash
yb-docker-ctl create
docker exec -it yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1  --echo-queries
CREATE DATABASE testing;
```

## Attempt 3
```bash
yb-docker-ctl create --rf 3
docker exec -it yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1  --echo-queries
CREATE DATABASE testing;
```

## Attempt 3
```bash
yb-docker-ctl create --rf 3 --master_flags="quick_leader_election_on_create=false"
docker exec -it yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1  --echo-queries
CREATE DATABASE testing;
```

Each of the above takes around 10 seconds for the CLI to resolve.

I should note looking into the yugabyte UI the database seems to get created much quicker. It's just the cli that hangs.

<img width="1636" alt="Screen Shot 2019-07-31 at 2 55 43 pm" src="https://user-images.githubusercontent.com/5929807/62184944-b9d07b80-b3a3-11e9-9ee2-358f8c43bdb3.png">

**Comment by rahuldesirazu** [comment] 2019-07-31 21:09
Hi @markwylde, reproduced this RF=1 docker setup on a 2 core CentOS host and got these results:

```
postgres=# CREATE DATABASE d;       
CREATE DATABASE d;
CREATE DATABASE
Time: 6737.894 ms (00:06.738)
postgres=# CREATE TABLE bar (a int PRIMARY KEY);
CREATE TABLE bar (a int PRIMARY KEY);
CREATE TABLE
Time: 619.650 ms
```

Seems like CREATE DATABASE takes on the order of what you described, but CREATE TABLE is pretty quick. Would you mind enabling timing and sending a snippet of the CREATE TABLE query you're running to produce the delay?

**Comment by kmuthukk** [comment] 2019-07-31 21:11
@rahuldesirazu 

Would you mind trying this on docker on Mac also to see if what the baseline for that is?

regards,
Kannan

**Comment by rahuldesirazu** [comment] 2019-07-31 21:13
@kmuthukk On mac, results on roughly the same order as CentOS (with a small slowdown):

```
postgres=# CREATE DATABASE d;       
CREATE DATABASE d;
CREATE DATABASE
Time: 8463.375 ms (00:08.463)
postgres=# CREATE TABLE bar (a int PRIMARY KEY);
CREATE TABLE bar (a int PRIMARY KEY);
CREATE TABLE
Time: 1696.698 ms (00:01.697)
```

**Comment by rahuldesirazu** [comment] 2019-11-20 01:19
Optimized create table flow in this commit: https://github.com/yugabyte/yugabyte-db/commit/6831eabf1be4caf5f167711de1bd2ffc894783ef. Since we haven't been able to reproduce this bug, closing this issue.

**Closed by rahuldesirazu** 2019-11-20 01:19 UTC
Labels: area/docdb, community/request, kind/bug
