### ISSUE TITLE
Issue with with distributed transactions in YSQL using JDBC driver

### ISSUE THREAD

**Issue by reeselevine** [yugabyte/yugabyte-db#7462] opened 2021-03-03 20:52 UTC
Jira Link: [DB-1873](https://yugabyte.atlassian.net/browse/DB-1873)
Hi, I was working on distributed transactions using the YSQL API, and am running into some issues using distributed transactions.

**Yugabyte Version:** 2.5.1.0
**Cluster setup:** Running locally on docker using `yb-docker-ctl`, specifically with this command: `./yb-docker-ctl create --rf 5 --tserver_flags="ysql_log_statement=all"`
**Client:** YSQL postgres jdbc client, i.e. what is found on https://docs.yugabyte.com/latest/quick-start/build-apps/java/ysql-jdbc/

## Issue
The two following transactions are executed in parallel, using the JDBC APIs with autocommit set to false:
```
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
BEGIN;
UPDATE table0 SET y = 1 WHERE id = 0;
UPDATE table1 SET r0 = x WHERE id = 0;
COMMIT;
```
```
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
BEGIN;
UPDATE table1 SET x = 1 WHERE id = 0;
UPDATE table0 SET r1 = y WHERE id = 0;
COMMIT;
```

The result of these concurrent transactions should be that both x and y are set to 1, and either r0 or r1 are set to 1, but not both. However, I sometimes see the following results (or with all values flipped):
```
x: 1, y: 0, r0: 1, r1: 0
```

Since I have ysql logging on, here is what I see in those logs:
```
2021-03-03 20:35:38.939 UTC [1012] LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE
2021-03-03 20:35:38.939 UTC [1000] LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE
2021-03-03 20:35:38.941 UTC [1012] LOG:  execute <unnamed>: BEGIN
2021-03-03 20:35:38.942 UTC [1012] LOG:  execute <unnamed>: UPDATE table1 SET y = 1 WHERE id = 0
2021-03-03 20:35:38.944 UTC [1000] LOG:  execute <unnamed>: BEGIN
2021-03-03 20:35:38.946 UTC [1000] LOG:  execute <unnamed>: UPDATE table0 SET x = 1 WHERE id = 0
2021-03-03 20:35:38.958 UTC [1000] LOG:  execute <unnamed>: UPDATE table1 SET r1 = y WHERE id = 0
2021-03-03 20:35:38.967 UTC [1012] LOG:  execute <unnamed>: UPDATE table0 SET r0 = x WHERE id = 0
I0303 20:35:38.975018  1022 tablet_rpc.cc:432] Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): Failed Read(tablet: 62a5489802274d62a0243697b9255add, num_ops: 1, num_attempts: 1, txn: c052dc3b-c6a3-4540-9e5f-7bc5c8d8c35c) to tablet 62a5489802274d62a0243697b9255add on tablet server { uuid: 0d80b98e27044fc4bd881dd4735b9d52 private: [host: "yb-tserver-n3" port: 9100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): c052dc3b-c6a3-4540-9e5f-7bc5c8d8c35c Conflicts with higher priority transaction: 65a30ecc-a928-4813-899f-ffb11f301f93 (transaction error 3)
2021-03-03 20:35:38.992 UTC [1000] LOG:  execute S_1: COMMIT
2021-03-03 20:35:39.077 UTC [1012] LOG:  execute <unnamed>: UPDATE table0 SET r0 = x WHERE id = 0
2021-03-03 20:35:39.105 UTC [1012] LOG:  execute S_1: COMMIT
```

It appears that Yugabyte correctly identifies the conflict, but then retries only the second update in the conflicting transaction, not the first one, and allows the commit to proceed. The error is also not reported at the client level. This leaves the database in an inconsistent state, as shown above.

I've recreated a minimal example, which is available here: https://github.com/reeselevine/yugabyte-bug. Note that it's not quite deterministic, but the error should happen within a few iterations of running the above code. Also note that when I tried to recreate the same issue using `ysqlsh`, the error in the logs above does seem to be reported to the client with the following message: `ERROR:  Operation failed. Try again.: 2d59b978-d4d7-4199-a878-6504bf474920 Conflicts with higher priority transaction: 679c8d93-b41a-4125-a837-081083b6051e`, and only one of the transactions is allowed to commit.

There's also a chance I'm misunderstanding Yugabyte's distributed transactions, or have some bug in the way I'm using the JDBC driver.

**Comment by d-uspenskiy** [comment] 2021-06-07 16:01
Hello @reeselevine 

I've failed to reproduce the problem on both latest and 2.5.1.0 builds. Could you please give some explanation regarding the issue description

There are 4 possible results of running the following transactions simultaneously:
```
-- Txn 1
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
BEGIN;
UPDATE table0 SET y = 1 WHERE id = 0;
UPDATE table1 SET r0 = x WHERE id = 0;
COMMIT;

-- Txn 2
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
BEGIN;
UPDATE table1 SET x = 1 WHERE id = 0;
UPDATE table0 SET r1 = y WHERE id = 0;
COMMIT;
```

They are:
- txn1 is committed txn2 is rejected due to conflict
- txn2 is committed txn1 is rejected due to conflict
- both txn1 an txn2 is committed in order txn1, txn2
- both txn1 an txn2 is committed in order txn2, txn1

Rows with id = 0 in `table0` and `table1` will be the following for each situation:
- table0 (x:0 y:1 r0:0 r1:0), table1 (x:0 y:0 r0:0 r1:0)
- table0 (x:0 y:0 r0:0 r1:0), table1 (x:1 y:0 r0:0 r1:0)
- table0 (x:0 y:1 r0:0 r1:1), table1 (x:1 y:0 r0:0 r1:0)
- table0 (x:0 y:1 r0:0 r1:0), table1 (x:1 y:0 r0:1 r1:0)

For some reason you are expecting other results:

Quote
```
The result of these concurrent transactions should be that both x and y are set to 1, and either r0 or r1 are set to 1, but not both. However, I sometimes see the following results (or with all values flipped):

x: 1, y: 0, r0: 1, r1: 0
```

`x: 1, y: 0, r0: 1, r1: 0` is expected row in table1 in case both transactions has been committed in order txn2, txn1

**Comment by d-uspenskiy** [comment] 2022-07-04 10:31
problem is not reproducible on latest builds, no response from originator for a long time, closing.

**Closed by d-uspenskiy** 2022-07-04 10:31 UTC
Labels: kind/bug, area/ysql, priority/medium
