### ISSUE TITLE
Possible memory leak, when tablet servers cannot form a Raft consensus.

### ISSUE THREAD

**Issue by metala** [yugabyte/yugabyte-db#9968] opened 2021-09-10 09:56 UTC
Jira Link: [DB-1983](https://yugabyte.atlassian.net/browse/DB-1983)
I have started a 3-node YugabyteDB multi-cloud multi-DC cluster using a Docker and a mesh/overlay network. Due to improper configuration and misunderstanding of the architecture I have formed a Raft consensus on just the yb-masters and the yb-tservers were not interconnected. As a result in about 24 hours time, I've got an OOM on two of the nodes and one of them got killed by the OOM killer.

**docker-compose.yml** (node1)
```yaml
version: '3'

services:
  yb-master:
      image: yugabytedb/yugabyte:2.9.0.0-b4
      container_name: yb-master-n1
      volumes:
        - /data/yb-master-data:/mnt/master
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=3",
                "--placement_cloud=scw",
                "--placement_region=eu-west",
                "--placement_zone=eu-west-ams"]

      ports:
        - "7000:7000"
        - "7100:7100"
      environment:
        SERVICE_7000_NAME: yb-master
      extra_hosts:
        - 'yb-master-n2:10.1.1.2'
        - 'yb-master-n3:10.1.1.3'


  yb-tserver:
      image: yugabytedb/yugabyte:2.9.0.0-b4
      container_name: yb-tserver-n1
      volumes:
        - /data/yb-tserver-data:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1:9100",
                "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
                "--placement_cloud=scw",
                "--placement_region=eu-west",
                "--placement_zone=eu-west-ams"]
      ports:
        - "9042:9042"
        - "5433:5433"
        - "9000:9000"
        - "9100:9100"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
        - yb-master
      extra_hosts:
        - 'yb-master-n2:10.1.1.2'
        - 'yb-master-n3:10.1.1.3'
```
What is missing is a few more entries in tserver's extra_hosts:
```
        - 'yb-tserver-n2:10.1.1.2'
        - 'yb-tserver-n3:10.1.1.3'
```

Here is an excerpt from the log to confirm that the tablet servers were indeed unable to form a consensus:
```
W0909 07:23:02.107297 14659 proxy.cc:276] Resolve yb-tserver-n2 failed: Network error (yb/util/net/dns_resolver.cc:64): Resolve failed yb-tserver-n2: Host not found (authoritative)
W0909 07:23:02.107388    71 leader_election.cc:276] T bb604685fda245e8bbb78e58c3266566 P 0c82a7c0bc7f468e8a3136afc4119547 [CANDIDATE]: Term 1 pre-election: RPC error from VoteRequest() call 
to peer bc2fb2f10256494d9eb1e980f2472db5: Network error (yb/util/net/dns_resolver.cc:64): Resolve failed yb-tserver-n2: Host not found (authoritative)
I0909 07:23:02.107421 14659 leader_election.cc:215] T bb604685fda245e8bbb78e58c3266566 P 0c82a7c0bc7f468e8a3136afc4119547 [CANDIDATE]: Term 1 pre-election: Requesting vote from peer bc467b2e
5d09466f94dc9b0be5b64bf6
W0909 07:23:02.107447 14659 proxy.cc:276] Resolve yb-tserver-n3 failed: Network error (yb/util/net/dns_resolver.cc:64): Resolve failed yb-tserver-n3: Host not found (authoritative)
W0909 07:23:02.107527 25412 leader_election.cc:276] T bb604685fda245e8bbb78e58c3266566 P 0c82a7c0bc7f468e8a3136afc4119547 [CANDIDATE]: Term 1 pre-election: RPC error from VoteRequest() call 
to peer bc467b2e5d09466f94dc9b0be5b64bf6: Network error (yb/util/net/dns_resolver.cc:64): Resolve failed yb-tserver-n3: Host not found (authoritative)
I0909 07:23:02.107555 25412 leader_election.cc:241] T bb604685fda245e8bbb78e58c3266566 P 0c82a7c0bc7f468e8a3136afc4119547 [CANDIDATE]: Term 1 pre-election: Election decided. Result: candidat
e lost.
```

And here is a graph of the memory usage and the crash on node2:
![Screenshot at 2021-09-10 12-05-42](https://user-images.githubusercontent.com/120106/132836382-2a2a21ec-1277-442a-9a2f-f8ced768fb1e.png)

**Comment by tylarb** [comment] 2021-09-15 15:19
@metala  Did the OOM kill happen inside the container or on your host OS?

**Comment by metala** [comment] 2021-09-16 11:36
@tylarb I have not set memory limit to the container (see docker-compose.yml), thus the host OOM should have killed a few processes.

**Comment by tylarb** [comment] 2021-09-16 15:46
@metala  I reproduced a subset of this issue, where I added a firewall rule to block only port 9100, the port used for intra-tserver communication: 

```
# firewall-cmd --list-all
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" port port="9100" protocol="tcp" reject
```

I'm getting connection failed, but not host not found (of course, because DNS is ok). 

```
I0916 15:45:34.985491 19053 raft_consensus.cc:654] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [term 4 FOLLOWER]: Starting pre-election with config: opid_index: -1 peers { permanent_uuid: "c8c952a4ba734b05ad1eabef07b1362a" member_type: VOTER last_known_private_addr { host: "10.69.3.4" port: 9100 } cloud_info { placement_cloud: "gcp" placement_region: "us-east1" placement_zone: "us-east1-d" } } peers { permanent_uuid: "565ba61e0ecc48e4b4c4072159af9c5d" member_type: VOTER last_known_private_addr { host: "10.69.3.6" port: 9100 } cloud_info { placement_cloud: "gcp" placement_region: "us-east1" placement_zone: "us-east1-c" } } peers { permanent_uuid: "e9a0ff48d5cc45c38b1af6ce4f05c7b7" member_type: VOTER last_known_private_addr { host: "10.69.3.5" port: 9100 } cloud_info { placement_cloud: "gcp" placement_region: "us-east1" placement_zone: "us-east1-b" } }
I0916 15:45:34.985536 19053 leader_election.cc:215] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [CANDIDATE]: Term 5 pre-election: Requesting vote from peer c8c952a4ba734b05ad1eabef07b1362a
I0916 15:45:34.985586 19053 leader_election.cc:215] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [CANDIDATE]: Term 5 pre-election: Requesting vote from peer 565ba61e0ecc48e4b4c4072159af9c5d
W0916 15:45:34.986310 19118 leader_election.cc:276] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [CANDIDATE]: Term 5 pre-election: RPC error from VoteRequest() call to peer c8c952a4ba734b05ad1eabef07b1362a: Network error (yb/util/net/socket.cc:557): recvmsg error: Connection refused (system error 111)
W0916 15:45:34.986873 19115 leader_election.cc:276] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [CANDIDATE]: Term 5 pre-election: RPC error from VoteRequest() call to peer 565ba61e0ecc48e4b4c4072159af9c5d: Network error (yb/util/net/socket.cc:557): recvmsg error: Connection refused (system error 111)
I0916 15:45:34.986907 19115 leader_election.cc:241] T 641910871b1540bd971c5279b23a55a5 P e9a0ff48d5cc45c38b1af6ce4f05c7b7 [CANDIDATE]: Term 5 pre-election: Election decided. Result: candidate lost.

```


Not seeing any memory leak - Mem usage is static.

**Comment by tylarb** [comment] 2021-09-16 15:58
@metala  Can you post the OOM killer logs ? or upload /var/log/messages or syslog if you're on Ubuntu

**Comment by metala** [comment] 2021-09-16 17:31
@tylarb Sorry, that compute node is already destroyed so I cannot read the dmesg buffer anymore and don't backup dmesg logs. I may try to reproduce the issue locally in the next few days.

**Comment by tylarb** [comment] 2021-09-17 16:34
@metala  I seem to have been able to repro your issue for the _master leader_ node when I give it a 24 hr window, memory usage goes up ~1.2 GB on an idle node.

I didn't use docker, I just added a firewall rule to block traffic on port 9100 (tserver RPC port).

![image](https://user-images.githubusercontent.com/20615828/133823125-c3a6f3f3-6bcf-4a83-b2de-4852557fff7a.png)

**Comment by tylarb** [comment] 2021-09-17 16:52
After review - it's not the process using memory, this is just an increase in cache.

My expectation of what is happening here is this:

Because you don't have consensus, you'll have a TON of log spam, which you've provided examples for above.

In the containers we ship, logs are dumped to /var/log - docs here: https://docs.yugabyte.com/latest/troubleshoot/nodes/check-logs/#yugabytedb-base-folder

> When using the docker container, logs are located in /root/var/logs inside the container.

I see in your docker compose file that, while you have a drive mounted at `/mnt/master` , you don't have one mounted at `/var/log` 

```
      volumes:
        - /data/yb-master-data:/mnt/master
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
```

So any log written to `/var/log/` will be inside of container memory

So what I think is happening is that the container is growing in memory usage, because those logs are only in memory, and not backed by disk.

While it's clear you have a problem anyway, and the DB won't work in this configuration, we also don't have a memory leak, and I expect you can "run" this way, and fill up disk instead of memory, if you mounted a volumn at `/var/log` or moved the YB logs to the `/mnt/master` endpoint (the `--log_dir` flag: https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#logging-flags)

**Comment by metala** [comment] 2021-09-19 08:36
Ok, there are a few thing that I think are wrong here:
I will start with saying that the memory usage was not cache, but RES memory. So to say yb-tserver was showing 70% MEM in `top`. There wouldn't be any OOM killings, if it was cache.

On the logs issue:
> In the containers we ship, logs are dumped to /root/var/log - docs here:
> I see in your docker compose file that, while you have a drive mounted at /mnt/master , you don't have one mounted at /var/log

But you are sending my a link that starts with the following otherwise:
> The logs for each node are written to a subdirectory of the YugabyteDB yugabyte-data directory.
Which is either misleading, because it suggests that either this is broken and cannot be configured using `--fs_data_dirs`. However, I have read the logs from the data dir and not from the docker. What I mean is that in my case there were logs stored in `/data/yb-master=data/yb-data/master/logs` for the master servers and `/data/yb-tserver-data/yb-data/tserver/logs` for the tserver, which in the tserver were multiple files with size of 1.8GB and a smaller current log.

**Comment by tylarb** [comment] 2021-09-20 20:12
@metala  I see.

How long did you let this run? 

This is very hard to diagnose without knowing for certain what triggered the OOM kill - again, it could be something at Docker layer that OOM killed that isn't present in Yugabyte. Also, of course, the database wouldn't  be usable in this state anyway.

**Closed** 2022-07-27 03:53 UTC
Labels: kind/bug, area/docdb, priority/medium
