### ISSUE TITLE
[YSQL] Update on table with multiple FK tables crashes postgres

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3583] opened 2020-02-07 06:08 UTC
This is an error seen on debug build only.

To reproduce:
```
yugabyte=# create table pk(b int, a int, y int, x int, primary key(a, b));
CREATE TABLE
yugabyte=# create unique index on pk(x, y);
CREATE INDEX
yugabyte=# insert into pk(a,b,x,y) values(1,10,100,1000);
yugabyte=# create table fk_primary(id int primary key, b int, a int, foreign key(a, b) references pk(a, b));
CREATE TABLE
yugabyte=# create table fk_unique(id int primary key, y int, x int, foreign key(x, y) references pk(x, y));
CREATE TABLE
yugabyte=# insert into pk(a,b,x,y) values(2,20,200,2000);
INSERT 0 1
yugabyte=# begin;
BEGIN
yugabyte=# INSERT INTO fk_unique(id, y, x) VALUES(2000, 2000, 200);
INSERT 0 1
yugabyte=# UPDATE pk SET x=201, y=2001 WHERE x=200 AND y=2000;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> exit

```
Note that the error only happens if both tables have FK references. Changing the above to use just 1 FK reference (by removing fk_primary table) won't cause the error.

**Comment by kmuthukk** [comment] 2020-02-07 06:18
good find!

**Comment by kmuthukk** [comment] 2020-02-15 16:44
Do we have a backtrace from the crash?

**Comment by kmuthukk** [comment] 2020-02-15 17:30
Was not able to repro this with yugabyte-2.0.10.0.

Is it possible that this is a regression in newer builds?

**Comment by ndeodhar** [comment] 2020-02-25 18:14
This is only seen in debug builds and not in the release binary.

**Comment by ddorian** [comment] 2020-02-27 15:33
A user with same issue said it's fixed in 2.1

**Comment by z0mb1ek** [comment] 2020-02-27 15:33
Hi. try last version and it start working

**Comment by z0mb1ek** [comment] 2020-02-29 16:11
1. create all tables https://pastebin.com/N5JZfx7W
2. reboot cluster(i use 1 master and 1 tserver)
3. insert this 
```
INSERT INTO public.realm (id, access_code_lifespan, user_action_lifespan, access_token_lifespan, account_theme, admin_theme, email_theme, enabled, events_enabled, events_expiration, login_theme, name, not_before, password_policy, registration_allowed, remember_me, reset_password_allowed, social, ssl_required, sso_idle_timeout, sso_max_lifespan, update_profile_on_soc_login, verify_email, master_admin_client, login_lifespan, internationalization_enabled, default_locale, reg_email_as_username, admin_events_enabled, admin_events_details_enabled, edit_username_allowed, otp_policy_counter, otp_policy_window, otp_policy_period, otp_policy_digits, otp_policy_alg, otp_policy_type, browser_flow, registration_flow, direct_grant_flow, reset_credentials_flow, client_auth_flow, offline_session_idle_timeout, revoke_refresh_token, access_token_life_implicit, login_with_email_allowed, duplicate_emails_allowed, docker_auth_flow, refresh_token_max_reuse, allow_user_managed_access, sso_max_lifespan_remember_me, sso_idle_timeout_remember_me) VALUES ('master', 60, 300, 60, null, null, null, true, false, 0, null, 'master', 0, null, false, false, false, false, 'EXTERNAL', 1800, 36000, false, false, null, 1800, false, null, false, false, false, false, 0, 1, 30, 6, 'HmacSHA1', 'totp', '14f74ffb-ea39-4719-aad2-14868c1752be', 'e18dbd82-d4a0-43a9-8e2f-0727e2850621', '6413f82d-4cf2-4db3-b75b-f1b133dec76c', 'a880f3ae-e1a1-48eb-a4db-e3ef202724ee', 'c67701e9-917b-4aad-a49a-ad8efea614d0', 2592000, false, 900, true, false, 'c17dc9b7-0804-404d-b25b-2f17d0d9539a', 0, false, 0, 0);
INSERT INTO public.client (id, enabled, full_scope_allowed, client_id, not_before, public_client, secret, base_url, bearer_only, management_url, surrogate_auth_required, realm_id, protocol, node_rereg_timeout, frontchannel_logout, consent_required, name, service_accounts_enabled, client_authenticator_type, root_url, description, registration_token, standard_flow_enabled, implicit_flow_enabled, direct_access_grants_enabled) VALUES ('68b5d7c4-0aad-4bf7-9783-094fc53d2d46', true, true, 'master-realm', 0, false, '02cc9444-ccf1-4824-935e-048d562d3c87', null, true, null, false, 'master', null, 0, false, false, 'master Realm', false, 'client-secret', null, null, null, true, false, false);
UPDATE public.realm SET master_admin_client = '68b5d7c4-0aad-4bf7-9783-094fc53d2d46' WHERE id='master';
```

**Comment by ddorian** [comment] 2020-03-02 09:53
the core dump for @z0mb1ek crash above
[yugabyte-2.1.0.0_bin_postgres.crash.zip](https://github.com/yugabyte/yugabyte-db/files/4274640/yugabyte-2.1.0.0_bin_postgres.crash.zip)

**Comment by d-uspenskiy** [comment] 2020-03-02 18:08
```

**Comment by kmuthukk** [comment] 2020-03-05 05:49
@z0mb1ek -- we have identified root cause, and implementing the fix. The scope of the fix should not be too large -- therefore, hope to get it out really soon.

**Closed** 2020-03-09 19:18 UTC
Labels: area/sql, kind/bug, priority/high
