### ISSUE TITLE
ysql_dump: [archiver (db)] query was: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public.commands

### ISSUE THREAD

**Issue by vahid-sohrabloo** [yugabyte/yugabyte-db#6469] opened 2020-11-24 13:02 UTC
I try to dump from my database  with this command

```
ysql_dump -h myhost -d mydb -a --column-inserts --inserts
```
and it gave me this error

```
ysql_dump: [archiver (db)] query failed: ERROR:  DECLARE CURSOR not supported yet
LINE 1: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public...
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
ysql_dump: [archiver (db)] query was: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public.commands

```

**Comment by ddorian** [comment] 2020-11-24 13:15
Hi @vahid-sohrabloo 

Can you try dumping without `--inserts` ?

**Comment by vahid-sohrabloo** [comment] 2020-11-24 18:27
I did it. But still, I have an error

```
ysql_dump -h myhost -d mydb -a --column-inserts
```

```
--
-- YSQL database dump
--

-- Dumped from database version 11.2-YB-2.3.3.0-b0
-- Dumped by ysql_dump version 11.2-YB-2.3.3.0-b0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: commands; Type: TABLE DATA; Schema: public; Owner: yugabyte
--

ysql_dump: [archiver (db)] query failed: ERROR:  DECLARE CURSOR not supported yet
LINE 1: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public...
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues
ysql_dump: [archiver (db)] query was: DECLARE _pg_dump_cursor CURSOR FOR SELECT * FROM ONLY public.commands
```

but it works  without --inserts and --column-inserts

**Comment by ddorian** [comment] 2020-11-25 08:51
[DECLARE CURSOR](https://github.com/yugabyte/yugabyte-db/issues/3286) is still being worked on.

For now you should work without `--inserts` and `--column-inserts`.

**Comment by kmuthukk** [comment] 2020-11-25 19:31
Closing as duplicate of #3286 . We are working on this feature actively.

**Closed by kmuthukk** 2020-11-25 19:31 UTC
Labels: area/ysql
