### ISSUE TITLE
[YSQL] Check failed: partition_key.size() == kPartitionKeySize

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#4768] opened 2020-06-12 23:01 UTC
Given these initial queries

```sql
CREATE TABLE rn (i int, j int, PRIMARY KEY (i ASC)) SPLIT AT VALUES ((3), (5));
INSERT INTO rn VALUES
    (1, 10),
    (2, 20),
    (3, 30),
    (4, 40),
    (5, 50),
    (6, 60);
```

these queries cause FATALs:

- `SELECT COUNT(*) FROM rn;`
- `SELECT COUNT(i) FROM rn;`
- `SELECT COUNT(j) FROM rn;`
- `SELECT MAX(j) FROM rn;`

and these queries return the wrong result:

- `SELECT MAX(i) FROM rn; -- returns 2`

The FATAL failure is

```
F0612 15:47:59.724808   374 partition.cc:374] Check failed: partition_key.size() == kPartitionKeySize (6 vs. 2)
```

with stack trace

```
    @     0x7f0747ad62af  yb::PartitionSchema::DecodeMultiColumnHashValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/yb/common/partition.cc:374)
    @     0x7f074c8728b5  yb::pggate::PgDocReadOp::InitializeParallelSelectCountOps(int) (src/yb/yql/pggate/pg_doc_op.cc:401)
    @     0x7f074c872d52  yb::pggate::PgDocReadOp::SendRequestImpl(bool) (src/yb/yql/pggate/pg_doc_op.cc:437)
    @     0x7f074c86f7d4  yb::pggate::PgDocOp::SendRequest(bool) (src/yb/yql/pggate/pg_doc_op.cc:172)
    @     0x7f074c86f852  yb::pggate::PgDocOp::Execute(bool) (src/yb/yql/pggate/pg_doc_op.cc:134)
    @     0x7f074c863b23  yb::pggate::PgDmlRead::Exec(PgExecParameters const*) (src/yb/yql/pggate/pg_dml_read.cc:184)
    @     0x7f074c835ee1  yb::pggate::PgApiImpl::ExecSelect(yb::pggate::PgStatement*, PgExecParameters const*) (src/yb/yql/pggate/pggate.cc:926)
    @     0x7f074c83000e  YBCPgExecSelect (src/yb/yql/pggate/ybc_pggate.cc:603)
    @           0x70570e  ybcIterateForeignScan (src/postgres/src/backend/executor/ybc_fdw.c:513)
    @           0x6f9463  ForeignNext (src/postgres/src/backend/executor/nodeForeignscan.c:56)
    @           0x6cd102  ExecScanFetch (src/postgres/src/backend/executor/execScan.c:95)
    @           0x6cd102  ExecScan (src/postgres/src/backend/executor/execScan.c:145)
    @           0x6f93fb  ExecForeignScan (src/postgres/src/backend/executor/nodeForeignscan.c:126)
    @           0x6cb240  ExecProcNodeFirst (src/postgres/src/backend/executor/execProcnode.c:446)
    @           0x6d56fb  ExecProcNode (src/postgres/src/include/executor/executor.h:249)
    @           0x6d56fb  fetch_input_tuple (src/postgres/src/backend/executor/nodeAgg.c:411)
    @           0x6d76be  agg_retrieve_direct (src/postgres/src/backend/executor/nodeAgg.c:1911)
    @           0x6d76be  ExecAgg (src/postgres/src/backend/executor/nodeAgg.c:1721)
    @           0x6cb240  ExecProcNodeFirst (src/postgres/src/backend/executor/execProcnode.c:446)
    @           0x6c23cd  ExecProcNode (src/postgres/src/include/executor/executor.h:249)
    @           0x6c23cd  ExecutePlan (src/postgres/src/backend/executor/execMain.c:1731)
    @           0x6c23cd  standard_ExecutorRun (src/postgres/src/backend/executor/execMain.c:368)
    @     0x7f073fc39023  pgss_ExecutorRun (src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947)
    @     0x7f073fa31348  ybpgm_ExecutorRun (src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:410)
    @           0x6c257e  ExecutorRun (src/postgres/src/backend/executor/execMain.c:309)
    @           0x864a17  PortalRunSelect (src/postgres/src/backend/tcop/pquery.c:942)
    @           0x86659e  PortalRun (src/postgres/src/backend/tcop/pquery.c:783)
    @           0x860db7  exec_simple_query (src/postgres/src/backend/tcop/postgres.c:1160)
    @           0x860db7  yb_exec_simple_query_attempting_to_restart_read (src/postgres/src/backend/tcop/postgres.c:4193)
    @           0x86252f  PostgresMain (src/postgres/src/backend/tcop/postgres.c:4794)
    @           0x7cf649  BackendRun (src/postgres/src/backend/postmaster/postmaster.c:4411)
    @           0x7cf649  BackendStartup (src/postgres/src/backend/postmaster/postmaster.c:4077)
    @           0x7cf649  ServerLoop (src/postgres/src/backend/postmaster/postmaster.c:1737)
    @           0x7cf649  PostmasterMain (src/postgres/src/backend/postmaster/postmaster.c:1400)
    @           0x725ce1  PostgresServerProcessMain (src/postgres/src/backend/main/main.c:234)
    @           0x725d7d
    @     0x7f074b902824  __libc_start_main (csu/libc-start.c:289)
    @           0x48ffb8  (unknown) (sysdeps/x86_64/start.S:118)
    @ 0xffffffffffffffff
```

I have not tested CQL.

**Comment by jaki** [comment] 2020-06-12 23:50
This was tested on commits 8ab79a251af59fcd559dbfa612da1ece3fe2fb72 and 0909995634e4367774f119ac9d19d488a8a935e5, and they both got the FATAL.

**Comment by nocaway** [comment] 2020-06-24 23:39
Duplicate of #4770

**Closed by nocaway** 2020-06-24 23:39 UTC
Labels: area/ysql, duplicate, kind/bug
