### ISSUE TITLE
[Phase 3][Colocation] Tablet Server UI shows only colocated parent table

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3675] opened 2020-02-18 18:49 UTC
Jira Link: [[DB-393]](https://yugabyte.atlassian.net/browse/DB-393)
Tablet Server `tables` page only shows the colocated parent table (see screenshot below). We should extend this to show all colocated tables (and hide the parent table since it's an internal detail?).

![image](https://user-images.githubusercontent.com/15746068/74767735-45283600-523c-11ea-825e-b8cede285546.png)

[DB-393]: https://yugabyte.atlassian.net/browse/DB-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaki** [comment] 2020-05-07 18:12
I think that, in addition to colocated user tables, showing the colocated parent table is good.  Besides, the `transactions` table is shown here.

There's also the tablets page, and that can be left untouched to show just the colocated parent table and tablet rather than also the colocated user tables.

Helpful info assuming tserver running on 127.0.0.1:

* tablet server ui: http://127.0.0.1:9000
* tablet server ui tables page: http://127.0.0.1:9000/tables
* tablet server ui tablets page: http://127.0.0.1:9000/tablets

Related:

* #3674

**Comment by tverona1** [comment] 2022-09-29 21:52
Closing this as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/5086.

**Closed by tverona1** 2022-09-29 21:52 UTC
Labels: kind/bug, area/ysql, priority/medium
