### ISSUE TITLE
[YCQL] EXPLAIN SELECT causes tserver to crash

### ISSUE THREAD

**Issue by fastest963** [yugabyte/yugabyte-db#2616] opened 2019-10-15 18:06 UTC
I'm running release version 2.0.1. When running `EXPLAIN SELECT * FROM accounts_api.logins WHERE ...` via cqlsh the local tserver crashes with:
```
Oct 15 17:37:25 watson bash[16013]: *** Aborted at 1571161045 (unix time) try "date -d @1571161045" if you are using GNU date ***
Oct 15 17:37:25 watson bash[16013]: PC: @     0x7f51308454e6 std::_Maybe_get_result_type<>
Oct 15 17:37:25 watson bash[16013]: *** SIGILL (@0x7f51308454e6) received by PID 16013 (TID 0x7f50fa4b8700) from PID 813978854; stack trace: ***
Oct 15 17:37:25 watson bash[16013]: @     0x7f51231d5ba0 (unknown)
Oct 15 17:37:25 watson bash[16013]: @     0x7f51308454e5  std::_Maybe_get_result_type<>
Oct 15 17:37:25 watson bash[16013]: @     0x7f513135663e  yb::ql::QLProcessor::ExecuteAsync()
Oct 15 17:37:25 watson bash[16013]: @     0x7f513135680d  yb::ql::QLProcessor::RunAsync()
Oct 15 17:37:25 watson bash[16013]: @     0x7f5131febf97  yb::cqlserver::CQLProcessor::ProcessRequest()
Oct 15 17:37:25 watson bash[16013]: @     0x7f5131fefb64  yb::cqlserver::CQLProcessor::ProcessRequest()
Oct 15 17:37:25 watson bash[16013]: @     0x7f5131fefed4  yb::cqlserver::CQLProcessor::ProcessCall()
Oct 15 17:37:25 watson bash[16013]: @     0x7f51320097ad  yb::cqlserver::CQLServiceImpl::Handle()
Oct 15 17:37:25 watson bash[16013]: @     0x7f512a0dd0d0  yb::rpc::ServicePoolImpl::Handle()
Oct 15 17:37:25 watson bash[16013]: @     0x7f512a089763  yb::rpc::InboundCall::InboundCallTask::Run()
Oct 15 17:37:25 watson bash[16013]: @     0x7f512a0e8c57  yb::rpc::(anonymous namespace)::Worker::Execute()
Oct 15 17:37:25 watson bash[16013]: @     0x7f51286cea18  yb::Thread::SuperviseThread()
Oct 15 17:37:25 watson bash[16013]: @     0x7f51231cd694 start_thread
Oct 15 17:37:25 watson bash[16013]: @     0x7f512290a41d __clone
Oct 15 17:37:25 watson bash[16013]: @                0x0 (unknown)
Oct 15 17:37:25 watson systemd[1]: yugabyte-tserver.service: main process exited, code=killed, status=4/ILL
Oct 15 17:37:25 watson systemd[1]: Unit yugabyte-tserver.service entered failed state.
```
I haven't tried other tables or other queries to see if they cause it to crash.

Here's the table, if that helps:
```
> DESCRIBE TABLE accounts_api.logins;
CREATE TABLE accounts_api.logins (
    auth_id text,
    auth_type smallint,
    scope text,
    auth_desc text,
    auth_secret text,
    auth_email text,
    auth_updated timestamp,
    scope_string_id text,
    scope_int_id bigint,
    created timestamp,
    updated timestamp,
    last_used timestamp,
    account_ids map<uuid, smallint>,
    flags int,
    alias authidtype,
    PRIMARY KEY (auth_id, auth_type, scope)
) WITH CLUSTERING ORDER BY (auth_type ASC, scope ASC)
    AND default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
```

**Comment by OlegLoginov** [comment] 2019-10-17 11:30
Hi @fastest963.
Unfortunately I cannot reproduce the issue locally.
Please provide:
 - definition for **authidtype** user type
 - 'where... ' part for the SELECT statement

**Comment by OlegLoginov** [comment] 2019-10-17 11:32
```
cqlsh:accounts_api> CREATE TABLE logins (     auth_id text,     auth_type smallint,     scope text,     auth_desc text,     auth_secret text,     auth_email text,     auth_updated timestamp,     scope_string_id text,     scope_int_id bigint,     created timestamp,     updated timestamp,     last_used timestamp,     account_ids map<uuid, smallint>,     flags int,     PRIMARY KEY (auth_id, auth_type, scope) ) WITH CLUSTERING ORDER BY (auth_type ASC, scope ASC)     AND default_time_to_live = 0     AND transactions = {'enabled': 'false'};
cqlsh:accounts_api> SELECT * FROM accounts_api.logins where auth_id='';

 auth_id | auth_type | scope | auth_desc | auth_secret | auth_email | auth_updated | scope_string_id | scope_int_id | created | updated | last_used | account_ids | flags
---------+-----------+-------+-----------+-------------+------------+--------------+-----------------+--------------+---------+---------+-----------+-------------+-------

(0 rows)
cqlsh:accounts_api> explain SELECT * FROM accounts_api.logins where auth_id='';

 QUERY PLAN
-----------------------------------
 Range Scan on accounts_api.logins
   Key Conditions: (auth_id = '') 
```

**Comment by fastest963** [comment] 2019-10-17 16:58
Hmm I tried to do what you did but even simpler and it still crashed:
```
Connected to local cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> CREATE KEYSPACE test;
cassandra@cqlsh> use test
   ... ;
cassandra@cqlsh:test> CREATE TABLE logins (auth_id text, PRIMARY KEY (auth_id) );
cassandra@cqlsh:test> SELECT * FROM logins WHERE auth_id='';

 auth_id
---------

(0 rows)
cassandra@cqlsh:test> explain SELECT * FROM logins WHERE auth_id='';
NoHostAvailable:      
cassandra@cqlsh:test> 
```
When I got the `NoHostAvailable` that's when it crashed.

Here are the list of my tablets for this server:
```
# yb-admin -master_addresses $MASTER_ADDRS list_tablets test logins 0;
I1017 16:51:19.462229 23195 mem_tracker.cc:250] MemTracker: hard memory limit is 9.838906 GB
I1017 16:51:19.462524 23195 mem_tracker.cc:252] MemTracker: soft memory limit is 8.363070 GB
I1017 16:51:19.469722 23195 yb-admin_client.cc:1201] Resolving namespace id for 'test' of type 'ycql'
Tablet UUID                             Range                                                           Leader
1b54cae12f134d28b49cecb484cd7cd5        partition_key_start: "" partition_key_end: "\002\350"           10.138.15.194:9200
a469bd8860a8489b8afad6722d042d8d        partition_key_start: "\002\350" partition_key_end: "\005\320"   10.138.15.194:9200
f776f5a4f4a84d0ea043c1ac1cfcb69b        partition_key_start: "\005\320" partition_key_end: "\010\270"   10.128.0.64:9200
71dbe8e5a97e4ed6abc69b31f71f0569        partition_key_start: "\010\270" partition_key_end: "\013\240"   10.128.0.64:9200
79181f37c2d74a0798d33a5b5398c793        partition_key_start: "\013\240" partition_key_end: "\016\210"   10.142.0.176:9200
1c9498750e754965b637391457c2354b        partition_key_start: "\016\210" partition_key_end: "\021p"      10.128.0.64:9200
9e327eaac5214e1589c2f9b02b4758a4        partition_key_start: "\021p" partition_key_end: "\024X"         10.142.0.176:9200
2697b17324954b77a79be42c135d061d        partition_key_start: "\024X" partition_key_end: "\027@"         10.138.15.194:9200
6ad4a15ca9fe4593846310dbd78ff983        partition_key_start: "\027@" partition_key_end: "\032("         10.142.0.176:9200
9dcf6fb79c5b4ddfb3a37e6273ba2abd        partition_key_start: "\032(" partition_key_end: "\035\020"      10.142.0.176:9200
62fcf4bc7f0644f7a9ca334b00d9bdf8        partition_key_start: "\035\020" partition_key_end: "\037\370"   10.138.15.194:9200
b9ee2741a1e44d5d802212da75d534a4        partition_key_start: "\037\370" partition_key_end: "\"\340"     10.142.0.176:9200
0f583b87a9774201a414124780355520        partition_key_start: "\"\340" partition_key_end: "%\310"        10.128.0.64:9200
8589deccdfa743d7bf6d3d304e3da062        partition_key_start: "%\310" partition_key_end: "(\260"         10.138.15.194:9200
54f25f5955484ce18d3d40c39993537a        partition_key_start: "(\260" partition_key_end: "+\230"         10.142.0.176:9200
bf44981727ab46508a84397f0c729422        partition_key_start: "+\230" partition_key_end: ".\200"         10.128.0.64:9200
5eea3eb2aac143189949c03b40db90a6        partition_key_start: ".\200" partition_key_end: "1h"            10.142.0.176:9200
b27c6e4f472643ce92d6af2f142ec914        partition_key_start: "1h" partition_key_end: "4P"               10.138.15.194:9200
5719c34fe0a948c8929896ae7f74ca44        partition_key_start: "4P" partition_key_end: "78"               10.138.15.194:9200
fba99c2b5259462a9d77b4a4177eeb6a        partition_key_start: "78" partition_key_end: ": "               10.138.15.194:9200
6b1c30070a8f4841ae1c7683517e38a3        partition_key_start: ": " partition_key_end: "=\010"            10.128.0.64:9200
f18a3c9f23b54400b2737a8a17de7004        partition_key_start: "=\010" partition_key_end: "?\360"         10.142.0.176:9200
83d1f352d3dd46328ae5267ddfe0975d        partition_key_start: "?\360" partition_key_end: "B\330"         10.138.15.194:9200
587a601e368e4d38be0eaca9bd07e0dd        partition_key_start: "B\330" partition_key_end: "E\300"         10.128.0.64:9200
ed762fd174c040be9e6cab475e1e05bb        partition_key_start: "E\300" partition_key_end: "H\250"         10.142.0.176:9200
f4947d5d5406409e9f8c362a7cdfddcf        partition_key_start: "H\250" partition_key_end: "K\220"         10.138.15.194:9200
1ec23a6c4fe24ba2849f8a7f28b8800c        partition_key_start: "K\220" partition_key_end: "Nx"            10.138.15.194:9200
b848eec04f514efdbf2f624162273fcd        partition_key_start: "Nx" partition_key_end: "Q`"               10.142.0.176:9200
6f4635457d00492cbeeeafe7b620e3d0        partition_key_start: "Q`" partition_key_end: "TH"               10.138.15.194:9200
3de4e51aa18d4fd6bb78ca0d026871b8        partition_key_start: "TH" partition_key_end: "W0"               10.138.15.194:9200
244de344acfc4db68aa69cc47e70dedc        partition_key_start: "W0" partition_key_end: "Z\030"            10.128.0.64:9200
3cf118823d9346b78ae307fa4ef2c63b        partition_key_start: "Z\030" partition_key_end: "]\000"         10.142.0.176:9200
4beff317f2554f85b9376271ca437f4b        partition_key_start: "]\000" partition_key_end: "_\350"         10.138.15.194:9200
229753a76a584db8a6c538c70d942927        partition_key_start: "_\350" partition_key_end: "b\320"         10.138.15.194:9200
5b0e0a0b5b5f49479d83cff1a154d7eb        partition_key_start: "b\320" partition_key_end: "e\270"         10.128.0.64:9200
215cf80455c14a65a03cde4d4cc8fa2a        partition_key_start: "e\270" partition_key_end: "h\240"         10.128.0.64:9200
8727506f825d4686b5324e80e3608ceb        partition_key_start: "h\240" partition_key_end: "k\210"         10.128.0.64:9200
c3c4056052da4df193e23e14152e2409        partition_key_start: "k\210" partition_key_end: "np"            10.128.0.64:9200
d244b6625a5b4b1590a16b6a6c7ba0dc        partition_key_start: "np" partition_key_end: "qX"               10.128.0.64:9200
d9005b77bedc4d5ba6cfb4962ce35afd        partition_key_start: "qX" partition_key_end: "t@"               10.142.0.176:9200
83b9c49a68734eaf8419dd5509b0fef6        partition_key_start: "t@" partition_key_end: "w("               10.142.0.176:9200
400210d3f7a341f68b39d909d4b8b450        partition_key_start: "w(" partition_key_end: "z\020"            10.128.0.64:9200
d34092f804d9407cbb139169a50c56cb        partition_key_start: "z\020" partition_key_end: "|\370"         10.142.0.176:9200
ccda579e47e64f599f0387293e2b130a        partition_key_start: "|\370" partition_key_end: "\177\340"      10.128.0.64:9200
e47a2ee972224582a208400cc8187e9c        partition_key_start: "\177\340" partition_key_end: "\202\310"   10.142.0.176:9200
fd1ce064dfb94793bb40d23e5f0646aa        partition_key_start: "\202\310" partition_key_end: "\205\260"   10.128.0.64:9200
dc1dafd96a7147ffa22fd7bc4a59db10        partition_key_start: "\205\260" partition_key_end: "\210\230"   10.138.15.194:9200
7e0240b9234447e18ef7390c6960f3bb        partition_key_start: "\210\230" partition_key_end: "\213\200"   10.128.0.64:9200
ae96db96da754a40a82999f385c07a75        partition_key_start: "\213\200" partition_key_end: "\216h"      10.138.15.194:9200
e90ec65803bf47bcbb7adb8cb5b31ef7        partition_key_start: "\216h" partition_key_end: "\221P"         10.142.0.176:9200
d2d7aa55943b4cae94d4f782696e8624        partition_key_start: "\221P" partition_key_end: "\2248"         10.142.0.176:9200
b22de5a44ea042beb7bd24a00ba4d8b3        partition_key_start: "\2248" partition_key_end: "\227 "         10.142.0.176:9200
9a9fb63425954045a5b3d9b028bd06e1        partition_key_start: "\227 " partition_key_end: "\232\010"      10.128.0.64:9200
292790fc163f431289b012cff697a81c        partition_key_start: "\232\010" partition_key_end: "\234\360"   10.128.0.64:9200
e6aca21cb94a4ddf980dd78bb5a9fc8d        partition_key_start: "\234\360" partition_key_end: "\237\330"   10.142.0.176:9200
6a4d27a9dbf948dbbd8aeae5b526ea19        partition_key_start: "\237\330" partition_key_end: "\242\300"   10.138.15.194:9200
6530fbae0cb54038a9ea229d3999f2a9        partition_key_start: "\242\300" partition_key_end: "\245\250"   10.138.15.194:9200
bb79ba74771c4097961f0e15f8e985ca        partition_key_start: "\245\250" partition_key_end: "\250\220"   10.128.0.64:9200
dc5a2b6ab78b4ec393f855a1f6066a38        partition_key_start: "\250\220" partition_key_end: "\253x"      10.138.15.194:9200
1af4813784944d9f868db68f291932b7        partition_key_start: "\253x" partition_key_end: "\256`"         10.138.15.194:9200
8db0462bb9af4d56b3f230dbe9d77893        partition_key_start: "\256`" partition_key_end: "\261H"         10.128.0.64:9200
686373416c274fd8b4f0482f5e7c1965        partition_key_start: "\261H" partition_key_end: "\2640"         10.142.0.176:9200
6354afcc2f2c4ad8a4ec58d9cc18a44b        partition_key_start: "\2640" partition_key_end: "\267\030"      10.142.0.176:9200
a8f88b0235cb4528944d159f978b8420        partition_key_start: "\267\030" partition_key_end: "\272\000"   10.138.15.194:9200
d825135a93fb4033a775be6151a13415        partition_key_start: "\272\000" partition_key_end: "\274\350"   10.138.15.194:9200
3c1008fb4fa24912b14c37606e123ee6        partition_key_start: "\274\350" partition_key_end: "\277\320"   10.128.0.64:9200
ee6e0e5ed7c64c728e6b4cbfb938ee02        partition_key_start: "\277\320" partition_key_end: "\302\270"   10.142.0.176:9200
d74d0acf5fef489a8454a378d5f50a47        partition_key_start: "\302\270" partition_key_end: "\305\240"   10.142.0.176:9200
a10327c5c0d847298d16a923c5d86562        partition_key_start: "\305\240" partition_key_end: "\310\210"   10.138.15.194:9200
578d6b83af6747199a9896661557cd74        partition_key_start: "\310\210" partition_key_end: "\313p"      10.138.15.194:9200
f4e1ea67ee764b4b9ffd91156a672414        partition_key_start: "\313p" partition_key_end: "\316X"         10.128.0.64:9200
28ed64b3d3ae439da1c2e1221a5d9191        partition_key_start: "\316X" partition_key_end: "\321@"         10.128.0.64:9200
d9616ae9a52f45a49c318b4dde50cc6f        partition_key_start: "\321@" partition_key_end: "\324("         10.142.0.176:9200
71021c0ec9fb4851af718b96ad4aa2b8        partition_key_start: "\324(" partition_key_end: "\327\020"      10.128.0.64:9200
1497f7978a6c4b09b6476c5d48e6ce98        partition_key_start: "\327\020" partition_key_end: "\331\370"   10.128.0.64:9200
f16d67d480604a22b3aaf1590e974a2d        partition_key_start: "\331\370" partition_key_end: "\334\340"   10.128.0.64:9200
25536d05ee4d45d5bfa0a2bc3bbbbfce        partition_key_start: "\334\340" partition_key_end: "\337\310"   10.138.15.194:9200
3c5b52b02bf7452a82c36ef52bd83fc2        partition_key_start: "\337\310" partition_key_end: "\342\260"   10.138.15.194:9200
8da9250db9f84861a8894ad7855b2b30        partition_key_start: "\342\260" partition_key_end: "\345\230"   10.128.0.64:9200
55bfec0b04ed44d09266537520fd7c2f        partition_key_start: "\345\230" partition_key_end: "\350\200"   10.142.0.176:9200
f824b689d7774abeb4f0402115423967        partition_key_start: "\350\200" partition_key_end: "\353h"      10.142.0.176:9200
2ab107183ca24bea8dbdc319049cf660        partition_key_start: "\353h" partition_key_end: "\356P"         10.138.15.194:9200
eb25b2c6f966417e9f28df1ef6f8fde2        partition_key_start: "\356P" partition_key_end: "\3618"         10.128.0.64:9200
3f40a7c852b845b8b8471d4cce415f0d        partition_key_start: "\3618" partition_key_end: "\364 "         10.142.0.176:9200
0e2affd1eff84409bb2269fc2790bf0c        partition_key_start: "\364 " partition_key_end: "\367\010"      10.138.15.194:9200
466eb218d2714cb68d3f3db07d33eefa        partition_key_start: "\367\010" partition_key_end: "\371\360"   10.142.0.176:9200
a328c3136d0546ef800e8b4587d2261b        partition_key_start: "\371\360" partition_key_end: "\374\330"   10.128.0.64:9200
c7f45223c3944f26a299c725bec91f8f        partition_key_start: "\374\330" partition_key_end: ""           10.142.0.176:9200
```

Universe config:
```
version: 29
replication_info {
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-east1"
        placement_zone: "us-east1-c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-central1"
        placement_zone: "us-central1-c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-west1"
        placement_zone: "us-west1-c"
      }
      min_num_replicas: 1
    }
  }
  read_replicas {
    num_replicas: 8
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-east1"
        placement_zone: "us-east1-d-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-east1"
        placement_zone: "us-east1-b-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-central1"
        placement_zone: "us-central1-b-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-us-west1"
        placement_zone: "us-west1-b-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-europe-west1"
        placement_zone: "europe-west1-b-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-europe-west1"
        placement_zone: "europe-west1-c-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-asia-east1"
        placement_zone: "asia-east1-b-rr"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "gce"
        placement_region: "gce-asia-east1"
        placement_zone: "asia-east1-c-rr"
      }
      min_num_replicas: 1
    }
    placement_uuid: "d3def1af-6c71-42af-8845-3fd79811732f"
  }
}
server_blacklist {
  initial_replica_load: 0
}
cluster_uuid: "d7ff7873-40c2-469b-b56a-8b59142b5494"
```

It seems to happen on our dev cluster as well which only has 2 nodes (RF=1) so I'm not sure if its related to my configuration. The only other thing is that I'm logging in with the cassandra user, I'm not sure if that matters at all?

**Comment by OlegLoginov** [comment] 2019-10-18 09:09
Thanks for the detailed info! I'll try to repeat it.

**Comment by OlegLoginov** [comment] 2019-10-18 09:58
@fastest963 Unfortunately I cannot reproduce the crash.
```
cqlsh> CREATE KEYSPACE test;
cqlsh> use test;
cqlsh:test> CREATE TABLE logins (auth_id text, PRIMARY KEY (auth_id) );
cqlsh:test> SELECT * FROM logins WHERE auth_id='';

 auth_id
---------
(0 rows)
cqlsh:test> explain SELECT * FROM logins WHERE auth_id='';
 QUERY PLAN
-----------------------------------
 Primary Key Lookup on test.logins
   Key Conditions: (auth_id = '') 
```
I tried RF=1 (1 node) and RF=3 (3 nodes) local clusters.
I'm using latest YB build - 2.0.3.0.
May be the issue was already fixed in the main branch. Could you please try the latest build?

Another idea: you can try a new dev cluster (no other tables) - on a separate host. (Just to confirm that the issue is not reproducible on an empty cluster with your version of YB software.)

**Comment by OlegLoginov** [comment] 2019-10-18 10:01
PS:  I tried 'cassandra' user too..
```
cassandra@cqlsh:test2> explain SELECT * FROM logins WHERE auth_id='';
 QUERY PLAN
------------------------------------
 Primary Key Lookup on test2.logins
   Key Conditions: (auth_id = '')  
```

**Comment by fastest963** [comment] 2019-10-18 11:23
Ah, I'm still running 2.0.1, when is a new release going to be made? I didn't see a release for 2.0.2 either. Let me know and I'll update and try again

**Comment by kmuthukk** [comment] 2019-10-18 14:31
@OlegLoginov -- two things you could try:

1) Use 2.0.1 to repro (using steps here - https://docs.yugabyte.com/latest/quick-start/install/#linux)

2) I am not sure whether you were trying to repro on Mac or Linux. But perhaps you could try both. I think James setup is on Linux (based on the systemd messages in the logs).

**Comment by OlegLoginov** [comment] 2019-10-21 15:06
I tried v2.0.1 on CentOS. (On MAC I tried local up-to-date YB.)
Same result - it works:
```
ip-10-9-2-238.us-west-2.compute.internal:~/yugabyte-2.0.1.0 
15:01 $ ./bin/cqlsh -u cassandra
Password: 
Connected to local cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> use a;
cassandra@cqlsh:a> CREATE TABLE logins2 (auth_id text, PRIMARY KEY (auth_id) );
cassandra@cqlsh:a>  SELECT * FROM logins2 WHERE auth_id='';
 auth_id
---------
(0 rows)
cassandra@cqlsh:a> explain SELECT * FROM logins2 WHERE auth_id='';
 QUERY PLAN
----------------------------------
 Primary Key Lookup on a.logins2 
   Key Conditions: (auth_id = '')
```

**Comment by fastest963** [comment] 2019-10-21 15:19
Hmm, I thought it might've been something related to the cluster but even on my dev machine it crashes. Here are the flags I'm running the master and tserver with:
```
# /etc/systemd/system/yugabyte-master.service
[Unit]
After=network.target
Description=yugabyte-master

[Service]
RestartForceExitStatus=SIGPIPE
EnvironmentFile=/etc/sysconfig/admiral_env
StartLimitInterval=0
ExecStart=/bin/bash -c '/opt/misc/yugabyte/bin/yb-master \
--master_addresses=vagrant.node.vagrant-james-laptop.admiral:7100 \
--fs_data_dirs=/opt/data/1/yugabyte \
--rpc_bind_addresses=$(ip addr show tun0 | grep -oP \'(?<=inet\s)\d+(\.\d+){3}\' | head -n 1):7100 \
--webserver_port=7000 \
--use_private_ip=never \
--placement_cloud=dev \
--placement_region=vagrant-james-laptop \
--placement_zone=vagrant \
--metric_node_name=vagrant \
--logtostderr --replication_factor=1'

LimitCORE=infinity
TimeoutStartSec=30
LimitNOFILE=1048576
LimitNPROC=12000
RestartSec=5
ExecStartPre=/usr/bin/su -c "mkdir -p /opt/data/1/yugabyte && chown yugabyte:yugabyte /opt/data/1/yugabyte"
MemoryLimit=919M
PermissionsStartOnly=True
User=yugabyte
TimeoutStopSec=300
Restart=always

[Install]
WantedBy=multi-user.target
```

```
# /etc/systemd/system/yugabyte-tserver.service
[Unit]
After=network.target
Description=yugabyte-tserver

[Service]
RestartForceExitStatus=SIGPIPE
EnvironmentFile=/etc/sysconfig/admiral_env
StartLimitInterval=0
ExecStart=/bin/bash -c '/opt/misc/yugabyte/bin/yb-tserver \
--tserver_master_addrs=vagrant.node.vagrant-james-laptop.admiral:7100 \
--fs_data_dirs=/opt/data/1/yugabyte \
--rpc_bind_addresses=$(ip addr show eth1 | grep -oP \'(?<=inet\s)\d+(\.\d+){3}\' | head -n 1):9200 \
--webserver_port=7001 \
--use_private_ip=never \
--placement_cloud=dev \
--placement_region=vagrant-james-laptop \
--placement_zone=vagrant \
--webserver_port=7001 \
--start_redis_proxy=false \
--use_cassandra_authentication=true \
--metric_node_name=vagrant \
--logtostderr'

LimitCORE=infinity
TimeoutStartSec=30
LimitNOFILE=1048576
LimitNPROC=12000
RestartSec=5
ExecStartPre=/usr/bin/su -c "mkdir -p /opt/data/1/yugabyte && chown yugabyte:yugabyte /opt/data/1/yugabyte"
MemoryLimit=1654M
PermissionsStartOnly=True
User=yugabyte
TimeoutStopSec=300
Restart=always

[Install]
WantedBy=multi-user.target
```

If there are some debug flags or something I can run on my side that might help, let me know. Since I can reproduce it on my dev machine then it'll be a lot easier for me to try things out there.

**Comment by OlegLoginov** [comment] 2019-10-21 15:53
@fastest963 By the way, do you use YB version of 'cqlsh' tool? 
<yugabyte-db>/bin/cqlsh
Right?

**Comment by fastest963** [comment] 2019-10-21 16:11
We have the yugabyte version in `/opt/misc/yugabyte/bin/cqlsh` and that's what I was using.

**Comment by ndeodhar** [comment] 2019-10-21 17:17
@fastest963 It looks like you're using vagrant.
@OlegLoginov Maybe, you can try to repro with that.

**Comment by fastest963** [comment] 2019-10-21 21:14
I was using vagrant locally for development but I can produce this on GCE machines running CentOS 7 as well.

**Comment by kmuthukk** [comment] 2019-10-22 02:42
@OlegLoginov -- when you tried it on Linux was it a GCE or AWS dev server?

@fastest963 -- could you please share output of `cat /proc/cpuinfo`? Because you are getting a SIGILL (illegal instruction), curious about the exact processor `model name` &` flags` (to see if it somehow specific to certain processors).

**Comment by fastest963** [comment] 2019-10-22 02:46
From GCE:
```$ cat /proc/cpuinfo                                                                                                                                                                                                                                                   
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU @ 2.30GHz
stepping        : 0
microcode       : 0x1
cpu MHz         : 2300.000
cache size      : 46080 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsav
e avx f16c rdrand hypervisor lahf_lm abm ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear spec_ctrl intel_stibp arch_capabilities
bogomips        : 4600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

From vagrant:
```
# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
stepping        : 10
cpu MHz         : 2208.002
cache size      : 9216 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hy
pervisor lahf_lm abm 3dnowprefetch fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bogomips        : 4416.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

**Comment by fastest963** [comment] 2019-10-22 04:19
I was able to reproduce it with a GCE n1-standard-1 (first generation CPU) server with 20GB spinning disk and GCE-supplied CentOS 7 image and running (as root):
https://gist.github.com/fastest963/d4c30ffb36e9681abb0897abe259c5f8

**Comment by OlegLoginov** [comment] 2019-10-22 11:30
@fastest963 Could you please provide arch/cpu info do you use?
Please run  `cat /proc/cpuinfo `
And what's used OS version.
Thanks.

**Comment by OlegLoginov** [comment] 2019-10-22 12:01
@fastest963  Thanks for the script!
I reproduced the issue.
(I was not able to reproduce it on the same GCE dev server with default configs. So, the configuration files look important.)

**Comment by OlegLoginov** [comment] 2019-10-22 12:34
Call stack:
```
*** Aborted at 1571747360 (unix time) try "date -d @1571747360" if you are using GNU date ***
PC: @     0x7f9eeb9734e6 std::_Maybe_get_result_type<>
*** SIGILL (@0x7f9eeb9734e6) received by PID 11482 (TID 0x7f9ec4ec7700) from PID 18446744073367139558; stack trace: ***
@     0x7f9ede303ba0 (unknown)
@     0x7f9eeb9734e5  std::_Maybe_get_result_type<>
@     0x7f9eec48463e  yb::ql::QLProcessor::ExecuteAsync()
@     0x7f9eec48480d  yb::ql::QLProcessor::RunAsync()
@     0x7f9eed119f97  yb::cqlserver::CQLProcessor::ProcessRequest()
@     0x7f9eed11db64  yb::cqlserver::CQLProcessor::ProcessRequest()
@     0x7f9eed11ded4  yb::cqlserver::CQLProcessor::ProcessCall()
@     0x7f9eed1377ad  yb::cqlserver::CQLServiceImpl::Handle()
@     0x7f9ee520b0d0  yb::rpc::ServicePoolImpl::Handle()
@     0x7f9ee51b7763  yb::rpc::InboundCall::InboundCallTask::Run()
@     0x7f9ee5216c57  yb::rpc::(anonymous namespace)::Worker::Execute()
@     0x7f9ee37fca18  yb::Thread::SuperviseThread()
@     0x7f9ede2fb694 start_thread
@     0x7f9edda3841d __clone
@                0x0 (unknown)
systemd[1]: yugabyte-tserver.service: main process exited, code=killed, status=4/ILL
systemd[1]: Unit yugabyte-tserver.service entered failed state.
systemd[1]: yugabyte-tserver.service failed.
systemd[1]: yugabyte-tserver.service holdoff time over, scheduling restart.
systemd[1]: Starting yugabyte-tserver...
```

**Comment by OlegLoginov** [comment] 2019-10-22 12:53
Reproduced with the following command line args:
```
 sudo -u yugabyte /opt/misc/yugabyte/bin/yb-master --master_addresses=127.0.0.1:7100 --fs_data_dirs=/opt/data/1/yugabyte --rpc_bind_addresses=127.0.0.1:7100 --webserver_port=7000 --use_private_ip=never --placement_cloud=gce --placement_region=test --placement_zone=test --metric_node_name=test --logtostderr --replication_factor=1 &

sudo -u yugabyte /opt/misc/yugabyte/bin/yb-tserver --tserver_master_addrs=127.0.0.1:7100 --fs_data_dirs=/opt/data/1/yugabyte --rpc_bind_addresses=127.0.0.1:9200 --webserver_port=7001 --use_private_ip=never --placement_cloud=gce --placement_region=test --placement_zone=test --webserver_port=7001 --start_redis_proxy=false --use_cassandra_authentication=true --metric_node_name=test --logtostderr &
```

**Comment by OlegLoginov** [comment] 2019-10-22 13:21
Reproduced locally (on MAC) with the keys:
`./bin/yb-ctl create  --use_cassandra_authentication`

**Comment by OlegLoginov** [comment] 2019-10-22 13:28
Root cause: invalid type cast from PTExplainStmt (derived from TreeNode) to PTDmlStmt.

```
bool QLProcessor::CheckPermissions(const ParseTree& parse_tree, StatementExecutedCallback cb) {
...
      case TreeNodeOpcode::kPTUpdateStmt: FALLTHROUGH_INTENDED;
      case TreeNodeOpcode::kPTDeleteStmt: FALLTHROUGH_INTENDED;
      case TreeNodeOpcode::kPTExplainStmt: FALLTHROUGH_INTENDED;  <<<<<<<<<<<<<<
      case TreeNodeOpcode::kPTInsertStmt: {
        const YBTableName table_name = static_cast<const PTDmlStmt*>(tnode)->table_name();       <<<<<<<<<<<<<<<<
        s = ql_env_.HasTablePermission(table_name, PermissionType::MODIFY_PERMISSION);
        break;
      }
```

**Comment by kmuthukk** [comment] 2019-10-22 16:57
Thx a lot @fastest963 for the repro steps, and @OlegLoginov for narrowing it down further.

**Comment by OlegLoginov** [comment] 2019-10-23 12:02
Fixed by the commit above.

**Closed by OlegLoginov** 2019-10-23 12:02 UTC
Labels: community/request
