### ISSUE TITLE
[YSQL] Read RPC timeout exception on SUM over Decimal call

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#10085] opened 2021-09-23 08:23 UTC
Scenario
```
drop table if exists t1;

CREATE TABLE t1(c0 DECIMAL );
INSERT INTO t1(c0) VALUES(0.4632167437031089463062016875483095645904541015625), (0.82173140818865475498711248292238451540470123291015625), (0.69990454445895500246166420765803195536136627197265625), (0.7554730989898816861938257716246880590915679931640625);
ALTER TABLE  ONLY t1 FORCE ROW LEVEL SECURITY, DISABLE ROW LEVEL SECURITY, NO FORCE ROW LEVEL SECURITY;
INSERT INTO t1(c0) VALUES(0.9946693818538820952568357824929989874362945556640625), (0.13653666831997435249235195442452095448970794677734375), (0.3359001510719556993223022800520993769168853759765625), (0.312027233370160583802999099134467542171478271484375);


SELECT SUM(count) FROM (SELECT (CAST((((('[-1962327130,2000870418)'::int4range)*('(-1293215916,183586536]'::int4range)))-((('[-545024026,526859443]'::int4range)*(NULL)))) AS VARCHAR)~current_query())::INT as count FROM ONLY t1) as res;

-- result
-- [XX000] ERROR: Timed out: Read RPC (request call id 791) to 127.0.0.1:9100 timed out after 5.474s
```

Reproducible in local cluster, where it fails with FATAL 
```
F20210922 13:35:07 ../../src/yb/yql/pggate/pg_expr.cc:175] No supported Sum TSOpcode for operand type: 15
    @        0x113aa7ee3  google::LogDestination::LogToSinks()
    @        0x113aa714c  google::LogMessage::SendToLog()
    @        0x113aa7a45  google::LogMessage::Flush()
    @        0x113aa7882  google::LogMessage::~LogMessage()
    @        0x107326181  yb::pggate::PgExpr::OperandTypeToSumTSOpcode()
    @        0x10732b6df  yb::pggate::PgOperator::PrepareForRead()
    @        0x1072e9032  yb::pggate::PgDml::AppendTargetPB()
    @        0x1072e8dcf  yb::pggate::PgDml::AppendTarget()
    @        0x107254002  yb::pggate::PgApiImpl::DmlAppendTarget()
    @        0x107225d9f  YBCPgDmlAppendTarget
    @        0x1060385fc  ybcSetupScanTargets
    @        0x106037ca9  ybcIterateForeignScan
    @        0x1060274dc  ForeignNext
    @        0x105fe568f  ExecScanFetch
    @        0x105fe5382  ExecScan
    @        0x106026fbb  ExecForeignScan
    @        0x105fe3092  ExecProcNodeFirst
    @        0x105ff73e2  ExecProcNode
    @        0x105ff728c  fetch_input_tuple
    @        0x105ff6c75  agg_retrieve_direct
    @        0x105ff3a44  ExecAgg
    @        0x105fe3092  ExecProcNodeFirst
    @        0x105fdbe82  ExecProcNode
    @        0x105fd6c51  ExecutePlan
    @        0x105fd6b2b  standard_ExecutorRun
    @        0x114e2aebf  pgss_ExecutorRun
    @        0x114e4095c  ybpgm_ExecutorRun
    @        0x105fd6894  ExecutorRun
    @        0x10624b296  PortalRunSelect
    @        0x10624ac0b  PortalRun
    @        0x106248200  exec_simple_query
    @        0x106246cf5  yb_exec_simple_query_impl
```

**Comment by nocaway** [comment] 2021-09-23 22:48
The issue is `current_query()` function is not processed properly. Here's simplified test case.
Function `lower()` was executed correctly while call to function `current_query()` incorrectly triggers a push-down for `SUM(c1)` and cause errors.

A work around would be key in the `select text` in place of `current_query()`.

```
postgres=# CREATE TABLE t1(c0 DECIMAL );
CREATE TABLE

postgres=# SELECT SUM(count) FROM (SELECT (lower('XXX') = 'xxx')::INT as count FROM t1) as res;
 sum 
-----
    
(1 row)

postgres=# SELECT SUM(count) FROM (SELECT (current_query() = 'xxx')::INT as count FROM t1) as res;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by myang2021** [comment] 2021-10-01 04:18
Fixed by https://github.com/yugabyte/yugabyte-db/commit/de1867939e05c20339d720bc0407d5b59aa5355d

**Comment by myang2021** [comment] 2021-10-11 20:18
Backported to 2.6: b7ae8d1edfc8dc2842c51db846f88239548d3ca3

**Closed** 2021-10-11 20:18 UTC
Labels: area/ysql, 2.6 Backport Required
