### ISSUE TITLE
Document Extensions in Explore Section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7696] opened 2021-03-17 15:39 UTC
create docs page explaining Extensions and explain the ones that we support ex. pgcrypto... the content is available at https://docs.yugabyte.com/latest/api/ysql/extensions/

**Comment by polarweasel** [comment] 2021-03-17 16:07
Duplicate of #7697 — more details in that one

**Closed** 2021-03-17 17:35 UTC
Labels: area/documentation, priority/high
