### ISSUE TITLE
Check failed: last_id_in_wal.term() <= GetCurrentTermUnlocked() (3459 vs. 3457)

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#2573] opened 2019-10-10 20:37 UTC
Observed on a stress cluster w/ 2.0.10-b19

[yugabyte@ip-172-151-25-217 logs]$ cat yb-tserver.FATAL
Log file created at: 2019/10/10 20:30:05
Running on machine: ip-172-151-25-217.us-west-2.compute.internal
Application fingerprint: version 2.0.1.0 build 19 revision 6607435dcbd4e8a90b48c2efc37f7ec50fce995a build_type RELEASE built at 04 Oct 2019 22:26:27 UTC
Running duration (h:mm:ss): 0:00:03
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1010 20:30:05.284113 23320 replica_state.cc:105] Check failed: last_id_in_wal.term() <= GetCurrentTermUnlocked() (3459 vs. 3457) T 0447492ac3514d589ea67981f68eaf88 P 5f71ef545c4c496489a51d8c8ff2b946 [term 3457 LEARNER]: The last op in the WAL with id 3459.56150180 has a term (3459) that is greater than the latest recorded term, which is 3457

[yugabyte@ip-172-151-25-217 logs]$ cat yb-tserver.FATAL.details.2019-10-10T20_25_04.pid22659.txt
F20191010 20:25:04 ../../src/yb/consensus/replica_state.cc:105] Check failed: last_id_in_wal.term() <= GetCurrentTermUnlocked() (3459 vs. 3457) T 0447492ac3514d589ea67981f68eaf88 P 5f71ef545c4c496489a51d8c8ff2b946 [term 3457 LEARNER]: The last op in the WAL with id 3459.56150180 has a term (3459) that is greater than the latest recorded term, which is 3457
    @     0x7f87437d30c5  yb::LogFatalHandlerSink::send()
    @     0x7f87429da616  google::LogMessage::SendToLog()
    @     0x7f87429d7d0a  google::LogMessage::Flush()
    @     0x7f87429dac39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f874a446aa5  yb::consensus::ReplicaState::StartUnlocked()
    @     0x7f874a4313dd  yb::consensus::RaftConsensus::Start()
    @     0x7f874a75cea1  yb::tablet::TabletPeer::Start()
    @     0x7f874b2046ab  yb::tserver::TSTabletManager::OpenTablet()
    @     0x7f8743860764  yb::ThreadPool::DispatchThread()
    @     0x7f874385ba19  yb::Thread::SuperviseThread()
    @     0x7f873e359694  start_thread
    @     0x7f873da9641d  __clone
    @              (nil)  (unknown)

**Comment by bmatican** [comment] 2019-10-10 23:30
Duplicate of #2570

**Comment by bmatican** [comment] 2019-10-10 23:33
(was meaning to keep this one and have the other one marked as duplicate)

Did some digging, this seems related to remote bootstrap sessions not being terminated when the leadership ends!

Timeline and notes

On leader, 8988f4fe61b54d3bb2def89d16317d8c, doing RBS
18:00:38.256662 -- 8988f4fe61b54d3bb2def89d16317d8c (LEADER term 3457) starts RBS to add in 5f71ef545c4c496489a51d8c8ff2b946
18:01:07.501719 -- 8988f4fe61b54d3bb2def89d16317d8c steps down, due to term 3458
18:06:44.528102 -- 5f71ef545c4c496489a51d8c8ff2b946 finishes file download and tries to wrap up RBS -- config has current term (!) 3459, but old index 56147987 (!)
On follower, 5f71ef545c4c496489a51d8c8ff2b946, during local bootstrap
18:06:44.898322 -- Rocksdb files are correct, corresponding to checkpoint done during RBS: 3457.56147986
18:06:47.714694 -- WAL files fully read, committed OpID: 3459.56150180
18:06:47.735081 -- CMeta 3457.56147987

**Comment by bmatican** [comment] 2019-10-11 19:11
13253e74a7502016c0b2af5193681865d7b6aa4a should have fixed this. We should add a regression test for it.

**Closed by bmatican** 2019-10-11 19:11 UTC
Labels: area/docdb, kind/bug, priority/high
