### ISSUE TITLE
[DocDB] Fatals and crashes observed in stress tests.

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16242] opened 2023-02-27 07:13 UTC
Jira Link: [DB-5664](https://yugabyte.atlassian.net/browse/DB-5664)
### Description

In backtrace there are quite a few related to:

```
frame #0: 0x00005639a34e4a02 yb-tserver`yb::docdb::DocDBTableReader::FlatGetHelper::DecodePackedColumn() [inlined] yb::Result<bool> yb::docdb::DocDBTableReader::GetHelperBase::DoDecodePackedColumn<yb::docdb::DocDBTableReader::FlatGetHelper::DecodePackedColumn(this=0x00007f82e8152c20, parent_exp=<unavailable>, get_value_address=(unnamed class) @ rbx)::'lambda'()>(yb::docdb::Expiration const&, yb::docdb::DocDBTableReader::FlatGetHelper::DecodePackedColumn()::'lambda'()) at doc_reader.cc:405:12
    frame #1: 0x00005639a34e496e yb-tserver`yb::docdb::DocDBTableReader::FlatGetHelper::DecodePackedColumn(this=0x00007f82e8152c20) at doc_reader.cc:764:12
```

Run: http://stress.dev.yugabyte.com/stress_test/f3e040e2-7c6f-4f03-b191-0d480db815d0

[DB-5664]: https://yugabyte.atlassian.net/browse/DB-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment] 2023-03-09 18:54
cc @ttyusupov could this be some recent regression, from your FlatTable improvement?

**Comment by ttyusupov** [comment] 2023-03-09 20:53
We can check on commit 011c86aca24a7881ddf40f1b76e9909bd03fe496 to verify if this is happening on previous builds.

**Comment by ttyusupov** [comment] 2023-03-15 09:19
On commit 011c86aca24a7881ddf40f1b76e9909bd03fe496 it is failing due to https://github.com/yugabyte/yugabyte-db/issues/15166 which is not yet fixed. Also stacktraces mentioned in the current issue description are not related to the thread that crashed the process. Interestingly, thread that crashed the processed received SIGILL:
```
* thread #1, name = 'yb-tserver', stop reason = signal SIGILL
  * frame #0: 0x00007f8375d0300f libpthread.so.0`pthread_cond_wait@@GLIBC_2.3.2 at pthread_cond_wait.S:185
    frame #1: 0x00005639a3276c0b yb-tserver`yb::TerminationMonitor::WaitForTermination() [inlined] void std::__1::condition_variable::wait<yb::TerminationMonitor::WaitForTermination()::$_0>(this=0x00005639b9cff990, __lk=<unavailable>, __pred=(unnamed class) @ rbx)::$_0) at __mutex_base:398:9
    frame #2: 0x00005639a3276bf3 yb-tserver`yb::TerminationMonitor::WaitForTermination(this=0x00005639b9cff960) at termination_monitor.cc:67:16
    frame #3: 0x00005639a425b93c yb-tserver`yb::tserver::TabletServerMain(argc=<unavailable>, argv=<unavailable>) at tablet_server_main_impl.cc:321:24
    frame #4: 0x00005639a2f38fd8 yb-tserver`main(argc=3, argv=0x00007fff1c8f4a68) at master_main.cc:185:12
    frame #5: 0x00007f837613a825 libc.so.6`__libc_start_main(main=(yb-tserver`main at master_main.cc:180), argc=3, argv=0x00007fff1c8f4a68, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fff1c8f4a58) at libc-start.c:289
    frame #6: 0x00005639a2c8a02e yb-tserver`_start + 46
```

"The SIGILL signal is raised when an attempt is made to execute an invalid, privileged, or ill-formed instruction. SIGILL is usually caused by a program error that overlays code with data or by a call to a function that is not linked into the program load module."

**Comment by rthallamko3** [comment] 2023-03-15 17:22
@shamanthchandra-yb , I removed the PackedRow aspect from the title, to be more reflective of the latest findings.

**Comment by rthallamko3** [comment] 2023-04-11 21:08
Based on internal conversations, the main issue seems to be #15166. Closing this out in favor of #15166

**Closed by rthallamko3** 2023-04-11 21:08 UTC
Labels: kind/bug, area/docdb, priority/medium, qa_automation, 2.18.0_blocker
