### ISSUE TITLE
[DocDB] sysbench perf test OOMs due to reactor based call expiration

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#19102] opened 2023-09-13 17:34 UTC
Jira Link: [DB-7908](https://yugabyte.atlassian.net/browse/DB-7908)
### Description

Reported by @sonalsagarwal.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7908]: https://yugabyte.atlassian.net/browse/DB-7908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-09-19 19:04
seems like a duplicate of [[#19090]](https://phorge.dev.yugabyte.com/D28531)

**Closed by rthallamko3** 2023-09-19 19:04 UTC
Labels: kind/enhancement, area/docdb, priority/medium
