### ISSUE TITLE
Remove cloud accessKey after cloud provider is deleted

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6447] opened 2020-11-20 21:51 UTC
After deleting the cloud provider we don't clean up the platform generated ssh accessKey which can lead to universe creation failures for the new cloud provider. 

`2020-11-20 21:30:53,169 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in TaskPool-CloudBootstrap(b86a0858-8bb5-48a5-ab81-5437e0633b13)-5 - ybops.common.exceptions.YBOpsRuntimeError: Runtime error: KeyPair already exists yb-dev-aws-cloud-key`

**Comment by chirag-yb** [comment] 2020-11-20 21:52
cc: @WesleyW Please add more details if needed

**Comment by jitendra-12113** [comment] 2021-01-11 15:00
@chirag-yb  I am unable to repro this issue. I might be missing something here. 
 Things tried:
 1. Configure AWS cloud provider and then deleted it.
 2. Again re-configured the  AWS cloud provider(with same Configuration) - Got success
 
 I can see the below stack trace in the log, when deleted the provider 
 
 **2021-01-11 20:16:57,274 [INFO] from ShellProcessHandler in application-akka.actor.default-dispatcher-60 - Starting proc (abbrev cmd) - bin/ybcloud.sh aws --region ap-south-1 access delete-key /opt/yugaware/keys/2b0ca9c0-a694-462e-a727-47315ba49d22
2021-01-11 20:16:57,276 [DEBUG] from ShellProcessHandler in application-akka.actor.default-dispatcher-60 - Starting proc (full cmd) - 'bin/ybcloud.sh' 'aws' '--region' 'ap-south-1' 'access' 'delete-key' '--key_pair_name' 'yb-admin-aws-key' '--key_file_path' '/opt/yugaware/keys/2b0ca9c0-a694-462e-a727-47315ba49d22' - logging stdout=/tmp/shell_process_out8368048741916156822tmp, stderr=/tmp/shell_process_err7678450237757373171tmp
2021-01-11 20:17:00,026 [DEBUG] from ShellProcessHandler in application-akka.actor.default-dispatcher-60 - Proc stdout | {"success": "Keypair yb-admin-aws-key deleted."}**

Please suggest! Thanks! 

PS: I tried it today by pulling the latest code. 

cc: @jaydeepkumara

**Comment by jitendra-12113** [comment] 2021-01-20 18:48
We are not able to repro this. The platform generated key is being deleted when we delete cloud provider(Tested only for aws). Closing this for now as cannot reproduce. Please feel free to reopen if still we want to do something as part of this ticket. Thanks!

cc: @Arnav15  @streddy-yb

**Comment by chirag-yb** [comment] 2021-03-14 19:42
@jvigil-yugabyte was able to reproduce this issue. Jason - can you provide clear steps?

**Comment by streddy-yb** [comment] 2021-03-14 21:54
Cleanup itself works fine as @jitendra-12113  mentioned. The key issue here is if there is already another key with the same name at the time of provider creation, the code is silently ignoring the "`KeyPair already exists`" error below. Key name is generated based on the provider name user selects. It is possible that multiple users are using the same shared AWS account and creating keys in the same region with the same name. Platform should generate a unique key name by appending say timestamp when there is another key with the same name. The other option is to fail the universe creation saying pick a different provider name.

`Traceback (most recent call last):                                                                                                                                             
  File "/opt/yugabyte/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>                                                                                           
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')                                                                                                         
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script                                                
    self.require(requires)[0].run_script(script_name, ns)                                                                                                                      
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script                                               
    exec(code, namespace, namespace)                                                                                                                                           
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>                             
    YbCloud().run()                                                                                                                                                            
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run                                       
    self.options.func(self.options)                                                                                                                                            
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper                    
    self.callback(args)                                                                                                                                                        
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/aws/method.py", line 159, in callback                              
    self.cloud.add_key_pair(args)                                                                                                                                              
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/aws/cloud.py", line 126, in add_key_pair                           
    raise YBOpsRuntimeError("KeyPair already exists {}".format(key_pair_name))                                                                                                 
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: KeyPair already exists yb-dev-aws-streddy-key        `

**Comment by jitendra-12113** [comment] 2021-03-22 17:22
We are appending providerUUIID along with provider name just to ensure unique ssh key every time it gets created.  -> This way, above issue will get resolved
Please review!
https://github.com/yugabyte/yugabyte-db/pull/7750

Thanks!

cc: @streddy-yb @Arnav15

**Closed** 2021-04-10 09:21 UTC
Labels: area/platform, good first issue, team/platform-hi
