### ISSUE TITLE
Thread Race in cassandra cpp driver

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#4696] opened 2020-06-05 23:45 UTC
https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F39435%2Fartifact%2Fbuild%2Ftsan-clang-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cassandra_cpp_driver-test%2FCppCassandraDriverTest_TestLongJson.log?max_lines=3000&start_line=3001

```

WARNING: ThreadSanitizer: data race (pid=18187)
--
3080 | Write of size 8 at 0x7b10000358d0 by thread T36:
3081 | #0 cass::LoadBalancingPolicy::init_session(cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.hpp:90:57 (libcassandra.so.2+0x8caae)
3082 | #1 cass::ChainedLoadBalancingPolicy::init_session(cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.hpp:131 (libcassandra.so.2+0x8caae)
3083 | #2 cass::LoadBalancingPolicy::new_query_plan(string const&, cass::RequestHandler*, cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.hpp:100:5 (libcassandra.so.2+0x8cbd3)
3084 | #3 cass::RequestHandler::init(cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/request_handler.cpp:125:53 (libcassandra.so.2+0x14cedf)
3085 | #4 cass::Session::on_execute(uv_async_s*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:823:24 (libcassandra.so.2+0x162cb4)
3086 | #5 uv__async_io /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/async.c:118:5 (libuv.so+0x1031b)
3087 | #6 uv__io_poll /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/linux-core.c:401:11 (libuv.so+0x285a3)
3088 | #7 uv_run /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/core.c:370:5 (libuv.so+0x10ba6)
3089 | #8 cass::LoopThread::on_run_internal(void*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/loop_thread.hpp:128:5 (libcassandra.so.2+0x16c84d)
3090 |  
3091 | Previous read of size 8 at 0x7b10000358d0 by thread T38:
3092 | #0 cass::LoadBalancingPolicy::control_connection() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.cpp:21:10 (libcassandra.so.2+0xedc5a)
3093 | #1 cass::PartitionAwarePolicy::on_work(cass::PeriodicTask*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:319:15 (libcassandra.so.2+0x133246)
3094 | #2 cass::PeriodicTask::on_work(uv_work_s*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/periodic_task.hpp:76:5 (libcassandra.so.2+0xecceb)
3095 | #3 uv__queue_work /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:259:3 (libuv.so+0xb375)
3096 | #4 worker /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:83:5 (libuv.so+0xb707)
3097 |  
3098 | Location is heap block of size 56 at 0x7b10000358c0 allocated by main thread:
3099 | #0 operator new(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/llvm-7.1.0.src/projects/compiler-rt/lib/tsan/rtl/tsan_new_delete.cc:65 (cassandra_cpp_driver-test+0x4e00b7)
3100 | #1 cass::Config::new_instance() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/config.hpp:111:15 (libcassandra.so.2+0x167f23)
3101 | #2 cass::Session::clear(cass::Config const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:171:20 (libcassandra.so.2+0x162111)
3102 | #3 cass::Session::connect_async(cass::Config const&, string const&, cass::SharedRefPtr<cass::Future> const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:343:3 (libcassandra.so.2+0x15f056)
3103 | #4 cass_session_connect_keyspace_n /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:66:12 (libcassandra.so.2+0x15ee30)
3104 | #5 cass_session_connect_keyspace /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:55:10 (libcassandra.so.2+0x15ec29)
3105 | #6 cass_session_connect /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:49 (libcassandra.so.2+0x15ec29)
3106 | #7 yb::CassandraSession::Connect(CassCluster_*) /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:258:26 (libcql_test_util.so+0xb01b)
3107 | #8 yb::CassandraSession::Create(CassCluster_*) /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:264:3 (libcql_test_util.so+0xb0ec)
3108 | #9 yb::CppCassandraDriver::CreateSession() /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:371:10 (libcql_test_util.so+0xbf48)
3109 | #10 yb::CppCassandraDriverTest::SetUp() /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:112:16 (cassandra_cpp_driver-test+0x50f85b)
3110 | #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x55c6f)
3111 | #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x55c6f)
3112 | #13 testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2470:3 (libgmock.so+0x34f21)
3113 | #14 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11 (libgmock.so+0x362ac)
3114 | #15 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36d86)
3115 | #16 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x430d6)
3116 | #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56bdf)
3117 | #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56bdf)
3118 | #19 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42981)
3119 | #20 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/installed/tsan/include/gtest/gtest.h:2233:46 (libyb_test_main.so+0x525b)
3120 | #21 main /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/util/test_main.cc:104:13 (libyb_test_main.so+0x4e3d)
3121 |  
3122 | Thread T36 (tid=18385, running) created by main thread at:
3123 | #0 pthread_create /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/llvm-7.1.0.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965 (cassandra_cpp_driver-test+0x46d92b)
3124 | #1 uv_thread_create /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/thread.c:202:9 (libuv.so+0x240c9)
3125 | #2 cass::LoopThread::run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/loop_thread.hpp:106:14 (libcassandra.so.2+0x15f4e4)
3126 | #3 cass::Session::connect_async(cass::Config const&, string const&, cass::SharedRefPtr<cass::Future> const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:373 (libcassandra.so.2+0x15f4e4)
3127 | #4 cass_session_connect_keyspace_n /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:66:12 (libcassandra.so.2+0x15ee30)
3128 | #5 cass_session_connect_keyspace /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:55:10 (libcassandra.so.2+0x15ec29)
3129 | #6 cass_session_connect /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:49 (libcassandra.so.2+0x15ec29)
3130 | #7 yb::CassandraSession::Connect(CassCluster_*) /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:258:26 (libcql_test_util.so+0xb01b)
3131 | #8 yb::CassandraSession::Create(CassCluster_*) /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:264:3 (libcql_test_util.so+0xb0ec)
3132 | #9 yb::CppCassandraDriver::CreateSession() /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cql_test_util.cc:371:10 (libcql_test_util.so+0xbf48)
3133 | #10 yb::CppCassandraDriverTest::SetUp() /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/integration-tests/cassandra_cpp_driver-test.cc:112:16 (cassandra_cpp_driver-test+0x50f85b)
3134 | #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x55c6f)
3135 | #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x55c6f)
3136 | #13 testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2470:3 (libgmock.so+0x34f21)
3137 | #14 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11 (libgmock.so+0x362ac)
3138 | #15 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36d86)
3139 | #16 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x430d6)
3140 | #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56bdf)
3141 | #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56bdf)
3142 | #19 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42981)
3143 | #20 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/installed/tsan/include/gtest/gtest.h:2233:46 (libyb_test_main.so+0x525b)
3144 | #21 main /nfusr/centos-gcp-cloud/jenkins-slave-207/jenkins/jenkins-github-yugabyte-db-phabricator-39435/build/tsan-clang-dynamic-ninja/../../src/yb/util/test_main.cc:104:13 (libyb_test_main.so+0x4e3d)
3145 |  
3146 | Thread T38 (tid=18522, running) created by thread T36 at:
3147 | #0 pthread_create /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/llvm-7.1.0.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965 (cassandra_cpp_driver-test+0x46d92b)
3148 | #1 uv_thread_create /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/thread.c:202:9 (libuv.so+0x240c9)
3149 | #2 init_threads /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:164:9 (libuv.so+0xaf90)
3150 | #3 init_once /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:191 (libuv.so+0xaf90)
3151 | #4 pthread_once /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/llvm-7.1.0.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1406 (cassandra_cpp_driver-test+0x46fe4f)
3152 | #5 uv_once /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/thread.c:363:7 (libuv.so+0x24520)
3153 | #6 uv__work_submit /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:199:3 (libuv.so+0xb26a)
3154 | #7 uv_queue_work /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:287 (libuv.so+0xb26a)
3155 | #8 cass::PeriodicTask::on_timeout(uv_timer_s*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/periodic_task.hpp:66:5 (libcassandra.so.2+0xecc97)
3156 | #9 uv__run_timers /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/timer.c:174:5 (libuv.so+0xc875)
3157 | #10 uv_run /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/unix/core.c:361:5 (libuv.so+0x10a41)
3158 | #11 cass::LoopThread::on_run_internal(void*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/loop_thread.hpp:128:5 (libcassandra.so.2+0x16c84d)
3159 |  
3160 | SUMMARY: ThreadSanitizer: data race /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.hpp:90:57 in cass::LoadBalancingPolicy::init_session(cass::Session*)
3161 | ==================


```

**Comment by mbautin** [comment] 2020-06-29 18:40
@OlegLoginov we might need a fix along the lines of https://github.com/yugabyte/cassandra-cpp-driver/pull/4

**Comment by OlegLoginov** [comment] 2020-11-06 18:05
It should be fixed by the commit:  https://github.com/yugabyte/cassandra-cpp-driver/commit/bccc76e6af60f513070d71b2cddd9580d0003cd6

So, it's a duplicate of https://github.com/yugabyte/yugabyte-db/issues/1837

**Closed by OlegLoginov** 2020-11-06 18:05 UTC
