### ISSUE TITLE
Fix TSAN failures in CppCassandraDriverTest

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2854] opened 2019-11-05 23:11 UTC

**Comment by OlegLoginov** [comment] 2020-06-04 07:03
Some details are here:  https://github.com/yugabyte/yugabyte-db/issues/4513
(Data race on the `session_` field in the LoadBalancingPolicy.)

**Comment by OlegLoginov** [comment] 2020-07-15 17:48
A set of issues:
https://github.com/yugabyte/yugabyte-db/issues/1837
https://github.com/yugabyte/yugabyte-db/issues/5107
https://github.com/yugabyte/yugabyte-db/issues/5108

**Comment by OlegLoginov** [comment] 2020-08-30 09:52
Closing as duplicate of  https://github.com/yugabyte/yugabyte-db/issues/5107.

**Closed by OlegLoginov** 2020-08-30 09:52 UTC
Labels: kind/failing-test
