### ISSUE TITLE
Ensure updates to multiple json fields are accumulated and applied together.

### ISSUE THREAD

**Issue by pritamdamania87** [yugabyte/yugabyte-db#319] opened 2018-06-05 19:19 UTC
While updating json documents, users might specify multiple updates as follows:

UPDATE foo SET c2->'a'->'b'->'c' = '1', c2->'x'->'y'->'z' = '2', .... WHERE .....

In such cases currently, we deserialize and serialize the jsonb for each update to the same column. If there are a lot of such updates in the same UPDATE statement, this would be pretty expensive.

An optimization would be to accumulate all the json updates to the same column and perform all the updates together.

**Comment by m-iancu** [comment] 2022-03-03 03:55
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/11054. Fixed in commit [432f59a](https://github.com/yugabyte/yugabyte-db/commit/432f59ae2b4275c2de183fe7f5fecb3514382f6d).

**Closed by m-iancu** 2022-03-03 03:55 UTC
Labels: kind/enhancement
