### ISSUE TITLE
[ysql] Support tables without a primary key in PostgreSQL

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#549] opened 2018-11-07 23:52 UTC
Will need some internal id-like column (uoid? bigoid?)
Probably should not use OID to avoid confusion.

**Comment by m-iancu** [comment] 2019-04-15 23:22
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/638. Fixed by @robertpang in cf980de.

**Closed by m-iancu** 2019-04-15 23:22 UTC
