### ISSUE TITLE
Problem with interpreting of IP-adresses in master-addresses

### ISSUE THREAD

**Issue by synnack** [yugabyte/yugabyte-db#3643] opened 2020-02-13 15:58 UTC
Starting yb_master with:

/opt/yugabyte-2.0.11.0/bin/yb-master \                                                                                  
  --master_addresses [2001:470:7b66:0:5054:ff:fea5:8824]:7100,[2001:982:286d:15::10]:7100 \                             
  --rpc_bind_addresses 2001:982:286d:15::10  \                                                                          
  --fs_data_dirs "/opt/yugabyte-2.0.11.0/data"

Results in the following messages:
Log file created at: 2020/02/13 15:51:44
Running on machine: hitclab
Application fingerprint: version 2.0.11.0 build 23 revision 2d52e1dfef65294a0ddf7c6377e3da2b8ed5a6b0 build_type RELEASE built at 24 Jan 2020 17:54:53 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0213 15:51:44.685276 28832 main_util.cc:22] Invalid argument (yb/util/net/net_util.cc:156): Couldn't parse the master_addresses flag ('[2001:470:7b66:0:5054:ff:fea5:8824]:7100,[2001:982:286d:15::10]:7100'): Invalid port: [2001:470:7b66:0:5054:ff:fea5:8824]:7100

Is there a different format I should use? All the examples only show legacy IP addresses, which my clusters don't have anywhere.

**Comment by synnack** [comment] 2020-02-13 16:30
Hostname based also appears not to work:
If I use --rpc_bind_address hitclab.synnack.net, I get:
E0213 16:29:41.603329 27275 main_util.cc:22] Network error (yb/util/net/net_util.cc:197): Unable to resolve address hitclab.synnack.net, getaddrinfo returned -2 (EAI_NONAME): Name or service not known

**Comment by synnack** [comment] 2020-02-13 16:31
It seems to mistakenly use legacy IP when it should have been using the current internet protocol..

**Comment by schoudhury** [comment] 2020-02-13 16:37
@synnack YugabyteDB currently does not support IPv6 addresses. It is on our roadmap and we hope to get to it sometime later this year. You can track progress through https://github.com/yugabyte/yugabyte-db/issues/3644

**Comment by ddorian** [comment] 2020-02-13 18:03
closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/3644
@synnack please subscribe to that issue

**Closed by ddorian** 2020-02-13 18:03 UTC
Labels: community/request
