### ISSUE TITLE
[YCQL] Statements doesn't run serially by default in YCQL transaction block

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#11686] opened 2022-03-08 15:19 UTC
Jira Link: [DB-1216](https://yugabyte.atlassian.net/browse/DB-1216)
### Description

In order to run operations serially in the YCQL transaction block, the `_ycql_serial_operation_in_transaction_block_` variable has to be set to True, else statements within the block are not able to see changes made by previous. In the below example, when this flag is set to false, the delete statement after insert got lost. 

**Steps to Reproduce the issue**

```
 curl -s `hostname -i`:9000/varz |grep ycql_serial_operation_in_transaction_block
--ycql_serial_operation_in_transaction_block=false

ycqlsh:app> begin transaction insert into t1(a,b,c) values(6,4,'b');  delete from t1 where a=6;  end transaction;
ycqlsh:app> select * from t1;

 a | b | c
---+---+---
 6 | 4 | b

(1 rows)

 ./yb-ts-cli --server_address=`hostname -i`:9100 --force set_flag ycql_serial_operation_in_transaction_block 1
 curl -s `hostname -i`:9000/varz |grep ycql_serial_operation_in_transaction_block
--ycql_serial_operation_in_transaction_block=true


ycqlsh:app> begin transaction insert into t1(a,b,c) values(6,4,'b');  delete from t1 where a=6;  end transaction;
ycqlsh:app> select * from t1;

 a | b | c
---+---+---

(0 rows)
```

**Ref Ticket**
2658

**Comment by m-iancu** [comment] 2022-03-08 19:16
@adil246 In the latest version the `ycql_serial_operation_in_transaction_block` is set to `true` by default (see [executor.cc#L109](https://github.com/yugabyte/yugabyte-db/blob/master/src%2Fyb%2Fyql%2Fcql%2Fql%2Fexec%2Fexecutor.cc#L109)). 

It can be disabled to enable full parallelism but only if the user is sure the workload does not contain conflicting statements within one transaction.
Is this by any chance an older version where that flag did not exist or was not set to true by default? Or perhaps it is explicitly set to false through a GFlag?

**Comment by m-iancu** [comment] 2022-10-11 18:12
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/5026.

**Closed by m-iancu** 2022-10-11 18:12 UTC
Labels: kind/bug, priority/medium, area/ycql
