### ISSUE TITLE
[yugabyted] When using advertise_address UI fails to start

### ISSUE THREAD

**Issue by sfrique** [yugabyte/yugabyte-db#19816] opened 2023-11-02 14:14 UTC
Jira Link: [DB-8751](https://yugabyte.atlassian.net/browse/DB-8751)
### Description

How to reproduce:

```sh
docker run -it --rm --name yb  yugabytedb/yugabyte:2.19.3.0-b140 bash
./bin/yugabyted start --advertise_address 0.0.0.0
ps aux | grep yugabyted-ui
```
You will see that there is a defunct process.

Output:
```
➜ docker run -it --rm --name yb  yugabytedb/yugabyte:2.19.3.0-b140 bash
[root@e65e1b43f50c yugabyte]# ./bin/yugabyted start --advertise_address 0.0.0.0
Starting yugabyted...
✅ YugabyteDB Started
✅ UI ready
✅ Data placement constraint successfully verified

⚠ WARNINGS:
- ntp/chrony package is missing for clock synchronization. For centos 7, we recommend installing either ntp or chrony package and for centos 8, we recommend installing chrony package.
- Cluster started in an insecure mode without authentication and encryption enabled. For non-production use only, not to be used without firewalls blocking the internet traffic.
Please review the 'Quick start for Linux' docs and rerun the start command: https://docs.yugabyte.com/preview/quick-start/linux/


+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 1                                                                                  |
| Web console         : http://127.0.0.1:7000                                                              |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte                   |
| YSQL                : bin/ysqlsh   -U yugabyte -d yugabyte                                               |
| YCQL                : bin/ycqlsh   -u cassandra                                                          |
| Data Dir            : /root/var/data                                                                     |
| Log Dir             : /root/var/logs                                                                     |
| Universe UUID       : 750d531e-3838-4cc7-a6a2-5a78e58ad550                                               |
+----------------------------------------------------------------------------------------------------------+
🚀 YugabyteDB started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/


[root@e65e1b43f50c yugabyte]# ps aux | grep yugabyted-ui
root         340  0.3  0.0      0     0 ?        Z    14:13   0:00 [yugabyted-ui] <defunct>
root         347  0.0  0.0  39076  2176 pts/0    S+   14:13   0:00 grep --color=auto yugabyted-ui
```

I didn't debug, but most likely the error is because of this:
https://github.com/yugabyte/yugabyte-db/blob/master/bin/yugabyted#L1686
And it fails.

If we don't pass the `--advertise_address 0.0.0.0` it works fine.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8751]: https://yugabyte.atlassian.net/browse/DB-8751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment] 2023-11-03 06:06
Hi @sfrique 
Can you run `./bin/yugabyted collect_logs` inside the container and upload them here?

**Comment by sfrique** [comment] 2023-11-06 12:45
[yugabyted-2023-11-06-12h42m57.467660s.tar.gz](https://github.com/yugabyte/yugabyte-db/files/13266605/yugabyted-2023-11-06-12h42m57.467660s.tar.gz)

Here it goes.

**Comment by ddorian** [comment] 2024-08-05 07:40
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/18580

**Closed by ddorian** 2024-08-05 07:40 UTC
Labels: kind/enhancement, priority/medium, area/ecosystem
