### ISSUE TITLE
[DocDB] flaky test: QLTabletTest.*

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#19195] opened 2023-09-19 13:39 UTC
Jira Link: [DB-7992](https://yugabyte.atlassian.net/browse/DB-7992)
### Description

Seeing these 3 tests bubbling up in stability recently

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=QLTabletTest&fail_tag=all&name=GCLogWithoutWrites&platform=linux

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=QLTabletTest&name=GCLogWithRestartWithoutWrites&num_commits=500

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=QLTabletTest&name=LeaderLease

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7992]: https://yugabyte.atlassian.net/browse/DB-7992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-09-19 15:57
QLTablet.* have been failing with error [1] , see detective report [2]. [GH1119](https://github.com/yugabyte/yugabyte-db/issues/1119) assigned to Yusong indicates that its not a regression and we have been seeing this failure intermittently from a while ago. But it looks like it is hitting lot more frequently now (probably due to race condition changes). Would be good to get to the bottom of it. 

[1]
 unknown file C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body.
[2]
https://detective-gcp.dev.yugabyte.com/search?error_details=+%28index%29+%3C+%28current_size_%29%3A

**Comment by bmatican** [comment] 2023-09-22 01:18
Perhaps this is also related to #16525 ?

**Comment by rthallamko3** [comment] 2024-08-01 19:14
Recent trends indicate that the test is stable.

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=QLTabletTest&name=GCLogWithoutWrites 

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=QLTabletTest&name=GCLogWithRestartWithoutWrites

**Closed by rthallamko3** 2024-08-01 19:14 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/medium
