### ISSUE TITLE
[YSQL] FATALs Error binding socket to 172.151.29.231:9100: Address already in use (system error 98) in CDC + Tablet Splitting + Nemesis case

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16654] opened 2023-04-03 07:01 UTC
Jira Link: [DB-6039](https://yugabyte.atlassian.net/browse/DB-6039)
### Description

http://stress.dev.yugabyte.com/stress_test/856bebb2-29a6-4c5a-9395-b661ed3bae01

Btw, this case was failing with data loss mostly in its history. Since saw series of FATALS (90+ files) in this run.

```
F20230402 03:57:01 ../../src/yb/tserver/tablet_server_main_impl.cc:224] Network error (yb/util/net/socket.cc:325): Error binding socket to 172.151.29.231:9100: Address already in use (system error 98)
    @     0x5557e4b89f97  google::LogMessage::SendToLog()
    @     0x5557e4b8aedd  google::LogMessage::Flush()
    @     0x5557e4b8b559  google::LogMessageFatal::~LogMessageFatal()
    @     0x5557e5f034be  yb::tserver::TabletServerMain()
    @     0x5557e4b2ea48  main
    @     0x7f761404f825  __libc_start_main
    @     0x5557e486e02e  _start
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6039]: https://yugabyte.atlassian.net/browse/DB-6039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-04-03 16:17
@shamanthchandra-yb , This happened during the end of the test run, during tear down. Can we follow up with Platform team on why 172.151.29.231:9100 was reused etc? The tserver failure

**Comment by rthallamko3** [comment] 2023-04-03 16:18
@shamanthchandra-yb , Can you clarify the steps followed by the test and the order of the operations? How does the test tear down the cluster?

**Comment by rthallamko3** [comment] 2023-04-05 04:58
Based on the offline discussion with @shamanthchandra-yb , the fatal is expected as the tserver is trying to come up with the same IP:port combo and according to the K8s platform, that IP is still in use. 

We plan to close this defect as by design. In case the test runs into again, the test needs to be updated with additional sleeps, before running `yb-server-ctl.sh ....... start `.

**Closed by rthallamko3** 2023-04-05 04:58 UTC
Labels: kind/bug, area/docdb, priority/medium, qa_automation
