### ISSUE TITLE
[YCQL] Undefined Behaviour of IN() with no Argument 

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#7065] opened 2021-02-02 19:17 UTC
Version 2.5 

The issue is when I used the IN() with no argument Query Failed 
Expected Behaviour: IN() with no argument is interpreted as "false"  
I found this feature request from Cassandra that notes that IN() (that is, IN() without arguments) should always resolve as false.
https://datastax-oss.atlassian.net/browse/JAVA-106

Reproduce:

```
ycqlsh> insert into test.nullin(id,name,size) values (5b6962dd-3f90-4c93-8f61-eabfa4a80310, NULL,NULL);
ycqlsh> select * from test.nullin;

 id                                   | name  | size
--------------------------------------+-------+--------
 5b6962dd-3f90-4c93-8f61-eabfa4a803e7 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e5 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e3 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e2 | first | second
 5b6962dd-3f90-4c93-8f61-eabfa4a80310 |  null |   null

(5 rows)
ycqlsh> \d
ycqlsh> 
ycqlsh> select * from test.nullin where name IN();
Traceback (most recent call last):
  File "/home/yugabyte/bin/ycqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/home/yugabyte/bin/../lib/cassandra-driver-internal-only-3.13.0.post0-743d942c.zip/cassandra-driver-3.13.0.post0-743d942c/cassandra/cluster.py", line 4033, in result
    raise self._final_exception
error: unpack requires a string argument of length 4

ycqlsh> select * from test.nullin where name IN();
NoHostAvailable: 
ycqlsh> select * from test.nullin where name IN();
NoHostAvailable: 
ycqlsh> select * from test.nullin where name IN();
Traceback (most recent call last):
  File "/home/yugabyte/bin/ycqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/home/yugabyte/bin/../lib/cassandra-driver-internal-only-3.13.0.post0-743d942c.zip/cassandra-driver-3.13.0.post0-743d942c/cassandra/cluster.py", line 4033, in result
    raise self._final_exception
error: unpack requires a string argument of length 4

ycqlsh> select * from test.nullin where name IN();
NoHostAvailable: 
ycqlsh> select * from test.nullin where name IN('');

 id                                   | name | size
--------------------------------------+------+------
 5b6962dd-3f90-4c93-8f61-eabfa4a803e3 |      |     
 5b6962dd-3f90-4c93-8f61-eabfa4a803e5 |      |     
 5b6962dd-3f90-4c93-8f61-eabfa4a803e7 |      |     

(3 rows)
ycqlsh> select * from test.nullin where name IN(null);

 id                                   | name | size
--------------------------------------+------+------
 5b6962dd-3f90-4c93-8f61-eabfa4a80310 | null | null

(1 rows)

```

**Comment by OlegLoginov** [comment] 2021-02-04 16:36
I cannot reproduce the issue on the master branch:
```
ycqlsh:a> desc nullin
CREATE TABLE a.nullin (
    id uuid PRIMARY KEY,
    name text,
    size text
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
ycqlsh:a> select * from nullin;
 id                                   | name  | size
--------------------------------------+-------+--------
 5b6962dd-3f90-4c93-8f61-eabfa4a803e7 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e5 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e3 |       |       
 5b6962dd-3f90-4c93-8f61-eabfa4a803e2 | first | second
 5b6962dd-3f90-4c93-8f61-eabfa4a80310 |  null |   null
(5 rows)
ycqlsh:a> select * from nullin where name IN();
 id | name | size
----+------+------
(0 rows)
ycqlsh:a> select * from nullin where name IN();
 id | name | size
----+------+------
(0 rows)
ycqlsh:a> select * from nullin where name IN();
 id | name | size
----+------+------
(0 rows)
ycqlsh:a> select * from a.nullin where name IN();
 id | name | size
----+------+------
(0 rows)
ycqlsh:a> select * from nullin where name IN('');
 id                                   | name | size
--------------------------------------+------+------
 5b6962dd-3f90-4c93-8f61-eabfa4a803e7 |      |     
 5b6962dd-3f90-4c93-8f61-eabfa4a803e5 |      |     
 5b6962dd-3f90-4c93-8f61-eabfa4a803e3 |      |     
(3 rows)
ycqlsh:a> select * from nullin where name IN(null);
 id                                   | name | size
--------------------------------------+------+------
 5b6962dd-3f90-4c93-8f61-eabfa4a80310 | null | null
(1 rows)
```

**Comment by m-iancu** [comment] 2021-02-04 22:03
Thanks @OlegLoginov! 
@karishmalalani can you share the exact 2.5 version you were testing with?
Was it 2.5.0 or 2.5.1?

**Comment by karishmalalani** [comment] 2021-02-04 23:00
Reproduce in a docker container with  rf1 

Version JSON:  
```
{"git_hash": "e2e53dd3221b6f648423064d829dfa193a46a16a", "build_hostname": "centos-gcp-cloud-jenkins-worker-1e4", "build_timestamp": "18 Dec 2020 03:35:44 UTC", "build_username": "jenkins", "build_clean_repo": $│·true", "build_id": "1745", "build_type": "RELEASE", "version_number": "2.5.1.0", "build_number": "153"}

```

**Comment by karishmalalani** [comment] 2021-02-04 23:28
@OlegLoginov  I realized in reproducing that we actually have an INDEX on name

I was not able to reproduce without a name index

DESC test.nullin
```
CREATE TABLE test.nullin (
    id uuid PRIMARY KEY,
    name text,
    size text
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'true'};
CREATE INDEX name ON test.nullin (name, id)
    WITH CLUSTERING ORDER BY (id ASC)
    AND transactions = {'enabled': 'true'};
```

**Comment by tedyu** [comment] 2021-02-05 05:25
With the index, I got the following error :
```
ycqlsh:a> select * from nullin where name IN();
Traceback (most recent call last):
  File "/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/common/cqlsh/bin/ycqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/common/cqlsh/bin/../lib/cassandra-driver-internal-only-3.13.0.post0-743d942c.zip/cassandra-driver-3.13.0.post0-743d942c/cassandra/cluster.py", line 4033, in result
    raise self._final_exception
error: unpack requires a string argument of length 4
```

**Comment by OlegLoginov** [comment] 2021-02-08 15:24
Reproduced:
```
ycqlsh:a> create table nullin (id uuid primary key, name text, size text) with transactions={'enabled':'true'};
ycqlsh:a> create index i on nullin (name, id);
ycqlsh:a> select * from nullin where name IN();
Traceback (most recent call last):
  File "/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111063010-7047513803-ubuntu1804-gcc7/installed/common/cqlsh/bin/ycqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111063010-7047513803-ubuntu1804-gcc7/installed/common/cqlsh/bin/../lib/cassandra-driver-internal-only-3.13.0.post0-743d942c.zip/cassandra-driver-3.13.0.post0-743d942c/cassandra/cluster.py", line 4033, in result
    raise self._final_exception
error: unpack requires a string argument of length 4
```

**Comment by OlegLoginov** [comment] 2021-02-28 09:33
Fixed by the commit above.

**Closed by OlegLoginov** 2021-02-28 09:33 UTC
Labels: area/ycql
