### ISSUE TITLE
[test] ComparisonFailure when running TestYbBackup

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5336] opened 2020-08-07 02:04 UTC
TestYbBackup failed with:
```
2020-08-06 20:16:57,790 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
org.junit.ComparisonFailure: expected:<...3456789, Wed Jul 29 [12:24:56 UTC] 2020, /127.0.0.1, 1...> but was:<...3456789, Wed Jul 29 [05:24:56 PDT] 2020, /127.0.0.1, 1...>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.yb.AssertionWrappers.lambda$assertEquals$7(AssertionWrappers.java:140)
        at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
        at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:140)
        at org.yb.cql.BaseCQLTest.assertQuery(BaseCQLTest.java:529)
        at org.yb.cql.BaseCQLTest.assertQuery(BaseCQLTest.java:533)
        at org.yb.cql.TestYbBackup.checkValuesInTables(TestYbBackup.java:380)
        at org.yb.cql.TestYbBackup.testYCQLRestoreIntoOriginalTable(TestYbBackup.java:469)
        at org.yb.cql.TestYbBackup.testYCQLBackupRestoringIntoOriginalTable(TestYbBackup.java:483)
```

**Comment by tedyu** [comment] 2020-08-07 02:48
I added more ports in 127.0.0.X form.
Still the same result:
```
2020-08-06 19:43:52,155 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:305)] used ip: 127.0.0.2
2020-08-06 19:43:52,156 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:313)] port is not free /127.0.0.3 9042
2020-08-06 19:43:52,157 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:313)] port is not free /127.0.0.5 9042
2020-08-06 19:43:52,157 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:305)] used ip: 127.0.0.10
2020-08-06 19:43:52,158 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:305)] used ip: 127.0.0.8
2020-08-06 19:43:52,158 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:313)] port is not free /127.0.0.4 9042
2020-08-06 19:43:52,158 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:305)] used ip: 127.0.0.1
2020-08-06 19:43:52,159 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.canUseBindIP(MiniYBCluster.java:305)] used ip: 127.0.0.6
```
It seems build/debug-clang-dynamic/bin/yb-tserver launched in previous run was not terminated.

**Comment by tedyu** [comment] 2020-08-07 03:21
In java/yb-cql/target/surefire-reports_org.yb.cql.TestYbBackup__testYCQLBackupRestoringIntoOriginalTable/org.yb.cql.TestYbBackup-output.txt , I saw:
```
2020-08-06 18:56:52,821 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.cql.TestYbBackup", method="testYCQLBackupRestoringIntoOriginalTable"
java.io.IOException: Cannot find a loopback IP of the form 127.0.x.y to launch a tablet server on. Considered options: [127.0.0.1, 127.0.0.2, 127.0.0.3].
        at org.yb.minicluster.MiniYBCluster.pickFreeBindIpOnMacOrWithCertificate(MiniYBCluster.java:411)
        at org.yb.minicluster.MiniYBCluster.getDaemonBindAddress(MiniYBCluster.java:326)
        at org.yb.minicluster.MiniYBCluster.getTabletServerBindAddress(MiniYBCluster.java:334)
        at org.yb.minicluster.MiniYBCluster.startTServer(MiniYBCluster.java:524)
        at org.yb.minicluster.MiniYBCluster.startTServer(MiniYBCluster.java:506)
        at org.yb.minicluster.MiniYBCluster.startTabletServers(MiniYBCluster.java:471)
        at org.yb.minicluster.MiniYBCluster.startCluster(MiniYBCluster.java:453)
        at org.yb.minicluster.MiniYBCluster.<init>(MiniYBCluster.java:191)
```
```
% ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	inet 127.0.0.2 netmask 0xff000000
	inet 127.0.0.3 netmask 0xff000000
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by tedyu** [comment] 2020-08-07 17:40
Looking at org.yb.cql.TestYbBackup-output.txt, there was no other mention of 05:24:56 apart from exception message.

[org.yb.cql.TestYbBackup-output.txt](https://github.com/yugabyte/yugabyte-db/files/5042856/org.yb.cql.TestYbBackup-output.txt)

**Comment by tedyu** [comment] 2020-08-07 17:51
When exception is encountered starting subsequent TServer(s), the previously started TServer(s) should be stopped.
We can iterate over tserverProcesses and stop them.

Otherwise fewer ports would be available for subsequent test runs.

**Comment by ddorian** [comment] 2020-08-11 12:08
cc @svarnau

**Comment by OlegLoginov** [comment] 2020-09-21 13:44
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/5431.

**Closed by OlegLoginov** 2020-09-21 13:44 UTC
Labels: area/ycql, community/request
