### ISSUE TITLE
ERROR:  ALTER OPERATOR SET <define> not supported yet

### ISSUE THREAD

**Issue by prakalp07** [yugabyte/yugabyte-db#3023] opened 2019-11-26 07:51 UTC
I am trying to dump our postgres database while dumping I am getting this exception on yugabyte postgres server

**Comment by ddorian** [comment] 2019-12-02 13:11
Currently `ALTER OPERATOR` isn't implemented yet.
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/2711

**Closed by ddorian** 2019-12-02 13:11 UTC
Labels: community/request
