### ISSUE TITLE
[flaky test] org.yb.cql.TestPartialIndex.testUniquePartialIndexPart2_4

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11643] opened 2022-03-03 22:06 UTC
Jira Link: [DB-786](https://yugabyte.atlassian.net/browse/DB-786)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.cql.TestPartialIndex&name=testUniquePartialIndexPart2_4&platform=all

**Comment by m-iancu** [comment] 2022-09-06 17:48
Looks like failure rate increased in the commit range: https://github.com/yugabyte/yugabyte-db/compare/5c3f73189ab142269d876ff3e78bbf7d5ad5bbd3~...4a38579b23b473dbf7b8384317382505f14e6a46

Only YCQL commit there is: https://github.com/yugabyte/yugabyte-db/commit/5c3f73189ab142269d876ff3e78bbf7d5ad5bbd3

This is probably (ast least in part) same root cause as https://github.com/yugabyte/yugabyte-db/issues/13891

**Comment by m-iancu** [comment] 2022-09-06 18:15
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/13891.

**Closed by m-iancu** 2022-09-06 18:15 UTC
Labels: kind/bug, kind/failing-test, priority/medium, area/ycql
