### ISSUE TITLE
[DocDB] sst_dump does not recognise packed rows and displays 'Schema packing not found: 0: .'.

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#15151] opened 2022-11-27 12:41 UTC
Jira Link: [DB-4348](https://yugabyte.atlassian.net/browse/DB-4348)
### Description

YugabyteDB version: version 2.15.3.2 build 1 revision 5ef608b43a994ab03a12ed3359258ec156d04a14 build_type RELEASE

When packed rows are enabled by setting: `--ysql_enable_packed_row=true` in the tserver configuration, and inserts are performed, these are likely inserted as packed rows.

When using the `sst_dump` utility on the sst files, the output is:
```
sst_dump --command=scan --file=. --output_format=decoded_regulardb
from [] to []
Process ./000010.sst
Sst file format: block-based
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0x1210, [1], []), [HT{ physical: 1669549573660326 logical: 5 }])
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0xc0c4, [2], []), [HT{ physical: 1669549573660326 logical: 5 w: 1 }])
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0xfca0, [3], []), [HT{ physical: 1669549573660326 logical: 5 w: 2 }])
```

Testcase:
1. set `--ysql_enable_packed_row=true` in the tserver configuration, and effectuate the setting.
2. create a table:
```
drop table if exists table_1;
create table table_1(
id int,
f1 varchar,
f2 int,
f3 timestamp,
constraint table_1_pk primary key ( id )
) split into 1 tablets;
insert into table_1 values
(1, 'AAAA', 1111, current_timestamp),
(2, 'BBBB', 2222, current_timestamp),
(3, 'CCCC', 3333, current_timestamp);
```
3. obtain table id and tablet id:
```
yb_stats --print-entities --table-name-match table_1
Table:    ysql.yugabyte.table_1, state: RUNNING, id: 000033e8000030008000000000004400
Tablet:   ysql.yugabyte.table_1.f3d7c560576e4b2689206ed3e081aa15 state: RUNNING
            ( VOTER,yb-1.local:9100,FOLLOWER VOTER,yb-3.local:9100,FOLLOWER VOTER,yb-2.local:9100,LEADER )
```
4. flush the table:
```
yb-admin -init_master_addrs localhost:7100 flush_table_by_id 000033e8000030008000000000004400 600
Flushed [000033e8000030008000000000004400] tables.
```
5. dump the sst files:
```
cd /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e8000030008000000000004400/tablet-f3d7c560576e4b2689206ed3e081aa15
sst_dump --command=scan --file=. --output_format=decoded_regulardb
from [] to []
Process ./000010.sst
Sst file format: block-based
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0x1210, [1], []), [HT{ physical: 1669549573660326 logical: 5 }])
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0xc0c4, [2], []), [HT{ physical: 1669549573660326 logical: 5 w: 1 }])
Not found (yb/docdb/schema_packing.cc:173): Schema packing not found: 0: . Key: SubDocKey(DocKey(0xfca0, [3], []), [HT{ physical: 1669549573660326 logical: 5 w: 2 }])
```

With non-packed rows the output is:
```
sst_dump --command=scan --file=. --output_format=decoded_regulardb
from [] to []
Process ./000010.sst
Sst file format: block-based
SubDocKey(DocKey(0x1210, [1], []), [SystemColumnId(0); HT{ physical: 1669469147804503 }]) -> null; intent doc ht: HT{ physical: 1669469147795462 }
SubDocKey(DocKey(0x1210, [1], []), [ColumnId(1); HT{ physical: 1669469147804503 w: 1 }]) -> "AAAA"; intent doc ht: HT{ physical: 1669469147795462 w: 1 }
SubDocKey(DocKey(0x1210, [1], []), [ColumnId(2); HT{ physical: 1669469147804503 w: 2 }]) -> 1111; intent doc ht: HT{ physical: 1669469147795462 w: 2 }
SubDocKey(DocKey(0x1210, [1], []), [ColumnId(3); HT{ physical: 1669469147804503 w: 3 }]) -> 722784347775780; intent doc ht: HT{ physical: 1669469147795462 w: 3 }
SubDocKey(DocKey(0xc0c4, [2], []), [SystemColumnId(0); HT{ physical: 1669469147804503 w: 4 }]) -> null; intent doc ht: HT{ physical: 1669469147795462 w: 4 }
SubDocKey(DocKey(0xc0c4, [2], []), [ColumnId(1); HT{ physical: 1669469147804503 w: 5 }]) -> "BBBB"; intent doc ht: HT{ physical: 1669469147795462 w: 5 }
SubDocKey(DocKey(0xc0c4, [2], []), [ColumnId(2); HT{ physical: 1669469147804503 w: 6 }]) -> 2222; intent doc ht: HT{ physical: 1669469147795462 w: 6 }
SubDocKey(DocKey(0xc0c4, [2], []), [ColumnId(3); HT{ physical: 1669469147804503 w: 7 }]) -> 722784347775780; intent doc ht: HT{ physical: 1669469147795462 w: 7 }
SubDocKey(DocKey(0xfca0, [3], []), [SystemColumnId(0); HT{ physical: 1669469147804503 w: 8 }]) -> null; intent doc ht: HT{ physical: 1669469147795462 w: 8 }
SubDocKey(DocKey(0xfca0, [3], []), [ColumnId(1); HT{ physical: 1669469147804503 w: 9 }]) -> "CCCC"; intent doc ht: HT{ physical: 1669469147795462 w: 9 }
SubDocKey(DocKey(0xfca0, [3], []), [ColumnId(2); HT{ physical: 1669469147804503 w: 10 }]) -> 3333; intent doc ht: HT{ physical: 1669469147795462 w: 10 }
SubDocKey(DocKey(0xfca0, [3], []), [ColumnId(3); HT{ physical: 1669469147804503 w: 11 }]) -> 722784347775780; intent doc ht: HT{ physical: 1669469147795462 w: 11 }
```

**Comment by Huqicheng** [comment] 2023-03-14 18:47
Duplicate of #14063

**Comment by rthallamko3** [comment] 2023-03-14 19:35
DUP of #14063. Closing this out.

**Closed by rthallamko3** 2023-03-14 19:35 UTC
Labels: kind/bug, area/docdb, priority/medium
