### ISSUE TITLE
[DocDB] Thread Sanitizer check failed in UT XClusterAdminCliTest_TestRenameUniverseReplication

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14188] opened 2022-09-26 05:20 UTC
Jira Link: [DB-3656](https://yugabyte.atlassian.net/browse/DB-3656)
### Description

Thread Sanitizer check failed in UT XClusterAdminCliTest_TestRenameUniverseReplication- https://gist.github.com/kripasreenivasan/978d8a25340628564416eb6ae4779865

**Comment by mbautin** [comment] 2022-09-26 22:01
Some more occurrences of this error: 

https://gist.githubusercontent.com/mbautin/7fd4ccda0ca874bb0719e730163c41fc/raw

**Comment by mbautin** [comment] 2022-09-26 22:02
Duplicate of #14098.

**Closed by mbautin** 2022-09-26 22:02 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage
