### ISSUE TITLE
[Yugaware Platform] Email alerts are missing ip <-> hostname associations

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#6799] opened 2021-01-06 17:12 UTC
--- Customer Request ---

In 2.2.5 yugaware, the Universe dashboard view of Nodes displays ip and associated hostname. 

Alert emails only display ip information. 

Requesting that emails include associated hostname of ip; identical/similar to what we see from yugaware platform node view.  

This would reduce the impact to customer duties when working to mitigate an issue. The current state, with hostname omitted, forces the customer to take additional steps to identify the problematic host.

**Comment by chirag-yb** [comment] 2021-02-01 04:30
@CharlotteRose Is this a duplicate of [6718](https://github.com/yugabyte/yugabyte-db/issues/6718)?

**Comment by jitendra-12113** [comment] 2021-02-22 10:13
@chirag-yb  Yes it looks like a duplicate of https://github.com/yugabyte/yugabyte-db/issues/6718
@CharlotteRose  Closing this as a duplicate. Please feel free to re-open if needed.

Thanks

**Closed** 2021-03-16 21:38 UTC
Labels: area/platform, platform/current, team/platform-hi
