### ISSUE TITLE
[YSQL] [Unit Test] Failing test case PgMiniTest.ReadRestartSnapshot

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#16520] opened 2023-03-22 13:01 UTC
Jira Link: [DB-5917](https://yugabyte.atlassian.net/browse/DB-5917)
### Description

Following testcase PgMiniTest.ReadRestartSnapshot has been failing a lot recently on alma8-gcc11-fastdebug and is now in >50% bucket. When in logs, it marks it passed but there is a SIGSEV. It started failing on commit: [f0fceca0](https://github.com/yugabyte/yugabyte-db/commits/f0fceca0172d4e1606fbc3a3c67073ee23db103c) but passed in between and again started failing on commit: [15d0e50f](https://github.com/yugabyte/yugabyte-db/commits/15d0e50fe077a7c0c162f23e23cb8bfbec1bf85d). 

```
I0322 08:45:06.940953 13438 mini_cluster.cc:503] Shutdown when mini cluster is not running (did mini cluster startup fail?)
[       OK ] PgMiniTest.ReadRestartSnapshot (66908 ms)
[----------] 1 test from PgMiniTest (66911 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (66912 ms total)
[  PASSED  ] 1 test.
*** Aborted at 1679474706 (unix time) try "date -d @1679474706" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0xfffffffffffe7960) received by PID 13438 (TID 0x7fb5e1743300) from PID 18446744073709451616; stack trace: ***
    @     0x7fb5e587d667 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb5e3ba3cf0 (unknown)
    @     0x7fb5e4e24e49 openssl_lh_strcasehash
    @     0x7fb5e4e35e8c obj_name_hash
    @     0x7fb5e4e246f1 getrn
    @     0x7fb5e4e24b85 OPENSSL_LH_delete
    @     0x7fb5e4e36519 OBJ_NAME_remove
    @     0x7fb5e4e24d7d OPENSSL_LH_doall
    @     0x7fb5e4e36708 OBJ_NAME_cleanup
    @     0x7fb5e4e182be evp_cleanup_int
    @     0x7fb5e4e2202e OPENSSL_cleanup
    @     0x7fb5e381c29c __run_exit_handlers
    @     0x7fb5e381c3d0 __GI_exit
    @     0x7fb5e3805d8c __libc_start_main
    @           0x419bbe _start
    @                0x0 (unknown)
I0322 08:45:07.860900 13437 run-with-timeout.cc:198] subprocess.Wait finished, waitpid() returned 139
I0322 08:45:07.860972 13437 run-with-timeout.cc:205] Waiting for reaper thread to join
I0322 08:45:07.860981 13439 run-with-timeout.cc:182] Reaper thread: finished=1, subprocess_is_run
```
Stability page: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgMiniTest&fail_tag=all&name=ReadRestartSnapshot&platform=linux
Jenkins log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-gcc11-fastdebug/2106/artifact/build/fastdebug-gcc11-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_mini-test/PgMiniTest_ReadRestartSnapshot.log

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5917]: https://yugabyte.atlassian.net/browse/DB-5917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mdbridge** [comment] 2023-03-22 15:55
Duplicate of #16501

**Closed** 2023-03-22 16:59 UTC
Labels: kind/bug, area/ysql, priority/medium, area/unittest, status/awaiting-triage
