### ISSUE TITLE
[YSQL] [Unit Test] Flaky test PgCatalogVersionTest.FixCatalogVersionTable

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#17643] opened 2023-06-01 15:47 UTC
Jira Link: [DB-6765](https://yugabyte.atlassian.net/browse/DB-6765)
### Description

FOllowing testcase PgCatalogVersionTest.FixCatalogVersionTable has been flaky across alma builds since introduced. It is failing with error:

```
[m-1] W0601 08:58:23.041857 15342 transaction_participant.cc:794] T {sys_catalog_tablet_id} P {m1_peer_id}: Get client failed: Timed out (yb/tablet/tablet_peer.cc:1482): Client not ready
[m-1] W0601 08:58:23.041893 15342 yb_rpc.cc:336] Call yb.tserver.TabletServerService.UpdateTransaction 127.58.28.0:43423 => 127.0.0.1:21944 (request call id 1959) took 5000ms (client timeout 4720ms). 

```

Jenkins log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-release-aarch64/1260/artifact/build/release-clang15-full-lto-ninja/yb-test-logs/tests-pgwrapper__pg_catalog_version-test/PgCatalogVersionTest_FixCatalogVersionTable.log

Stability link: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgCatalogVersionTest&fail_tag=all&name=FixCatalogVersionTable&platform=linux

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6765]: https://yugabyte.atlassian.net/browse/DB-6765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment] 2023-08-01 18:43
duplicate of #17849

**Closed by myang2021** 2023-08-01 18:43 UTC
Labels: kind/bug, area/ysql, priority/medium
