### ISSUE TITLE
[YSQL] Illegal state: Transaction for catalog table write operation 'pg_database' not found

### ISSUE THREAD

**Issue by ozturkberkay** [yugabyte/yugabyte-db#12222] opened 2022-04-21 08:52 UTC
### Description

Hi,

Before dropping a database, first I want to prevent new connections and then drop the existing the connections. However, I'm stuck at the first step:

```
ysqlsh (11.2-YB-2.1.1.0-b0)

yugabyte=# SELECT * FROM pg_database;
          datname           | datdba | encoding | datcollate |  datctype   | datistemplate | datallowconn | datconnlimit | datlastsysoid | datfrozenxid | datminmxid | dattablespace |               datacl
----------------------------+--------+----------+------------+-------------+---------------+--------------+--------------+---------------+--------------+------------+---------------+-------------------------------------
 template1                  |     10 |        6 | C          | en_US.UTF-8 | t             | t            |           -1 |             0 |            0 |          1 |          1663 | {=c/postgres,postgres=CTc/postgres}
 template0                  |     10 |        6 | C          | en_US.UTF-8 | t             | f            |           -1 |             0 |            0 |          1 |          1663 | {=c/postgres,postgres=CTc/postgres}
 postgres                   |     10 |        6 | C          | en_US.UTF-8 | f             | t            |           -1 |             0 |            0 |          1 |          1663 |
 yugabyte                   |     10 |        6 | C          | en_US.UTF-8 | f             | t            |           -1 |             0 |            0 |          1 |          1663 |
 system_platform            |     10 |        6 | C          | en_US.UTF-8 | f             | t            |           -1 |             0 |            0 |          1 |          1663 |
 test_1650530283_52506      |  12462 |        6 | C          | en_US.UTF-8 | f             | t            |           -1 |             0 |            0 |          1 |          1663 |
(6 rows)

yugabyte=# UPDATE pg_database SET datallowconn=false WHERE datname = 'test_1650530283_52506';
ERROR:  Illegal state: Transaction for catalog table write operation 'pg_database' not found
```

**Comment by jaki** [comment] 2022-04-22 03:45
Other sys catalog changes like `UPDATE pg_index SET indisvalid=false WHERE indexrelid = 54321` work fine.  The difference I see is that the write op is marked "need_transaction" for the pg_database update but not for the pg_index update (not sure why).  See `ShouldHandleTransactionally`:

```cpp
  if (!table.schema().table_properties().is_transactional() ||
      !op.need_transaction() ||
      YBCIsInitDbModeEnvVarSet()) {
    return false;
  }
  ...
  if (txn_manager.IsDdlMode() || (yb_non_ddl_txn_for_sys_tables_allowed && has_non_ddl_txn)) {
    return true;
  }
  if (op.is_write()) {
    // For consistent read from catalog tables all write operations must be done in transaction.
    return STATUS_FORMAT(IllegalState,
                         "Transaction for catalog table write operation '$0' not found",
                         table.table_name().table_name());
  }
```

@ozturkberkay, one way to work around this is to `SET yb_non_ddl_txn_for_sys_tables_allowed = on;`.  Since the update is trivial, I don't see problems with this, even though this session variable is marked for testing only.  cc: @d-uspenskiy

```sql
SET yb_non_ddl_txn_for_sys_tables_allowed = on;
UPDATE pg_database SET datallowconn=false WHERE datname = 'test_1650530283_52506';
RESET yb_non_ddl_txn_for_sys_tables_allowed; -- optional
```

From testing, I noticed other sessions pick up the change even though the catalog version is not bumped.  If you want to be extra safe, you can force a catalog version bump, causing all other sessions to update their system catalog caches.

```sql
SET yb_non_ddl_txn_for_sys_tables_allowed = on;
BEGIN;
UPDATE pg_database SET datallowconn=false WHERE datname = 'test_1650530283_52506';
WITH w AS (SELECT current_version + 1 AS new_version FROM pg_yb_catalog_version) UPDATE pg_yb_catalog_version SET current_version = new_version, last_breaking_version = new_version FROM w;
COMMIT;
RESET yb_non_ddl_txn_for_sys_tables_allowed; -- optional
```

**Comment by d-uspenskiy** [comment] 2022-04-22 07:53
Hi @ozturkberkay described behavior is not a bug. Everything works as expected. It is not recommended to change system tables manually. If it absolutely necessary for some reason user should set  the `yb_non_ddl_txn_for_sys_tables_allowed` GUC variable to `true`. But user will do this on its own risk.

Could you please close the issue as no fix is planned.

**Comment by d-uspenskiy** [comment] 2022-04-22 08:03
BTW to disallow connection to DB it is better to use this query instead of changing system table manually

```
ALTER DATABASE db WITH ALLOW_CONNECTIONS false;
```

**Closed** 2022-04-22 08:25 UTC
Labels: area/ysql, status/awaiting-triage
