### ISSUE TITLE
[YSQL] Stored generated column is not supported

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#10695] opened 2021-11-24 17:40 UTC
Jira Link: [DB-1115](https://yugabyte.atlassian.net/browse/DB-1115)
### Description

```
yugabyte=# CREATE TABLE gtest0 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (55) STORED);
ERROR:  syntax error at or near "("
LINE 1: ...st0 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (55) STORE...
                                                             ^
```

**Comment by saurik** [comment] 2022-01-30 07:14
Apparently this was a PostgreSQL 12 feature (and Yugabyte is based on PostgreSQL 11.2).

**Comment by TroyKomodo** [comment] 2024-02-09 14:30
Would be nice if this ticket made it into a milestone.

**Comment by smiziara** [comment] 2024-09-21 19:40
+1, cannot use some packages like zitadel, due to lack of this feature.

**Comment by sushantrmishra** [comment] 2024-10-24 22:08
Fixed as part of https://github.com/yugabyte/yugabyte-db/issues/24291 . This should be available in 2025.1 release of YugabyteDB in which YugabyteDB is update to PG15 compatible. 

duplicate of https://github.com/yugabyte/yugabyte-db/issues/24291

**Closed** 2024-10-24 22:08 UTC
Labels: kind/enhancement, area/ysql, priority/medium, pgcm
