### ISSUE TITLE
[yugabyted] metrics panels keep spinning

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#3196] opened 2019-12-20 22:01 UTC
Trying the new yugabyted (in 2.0.8).

The panels rendered fine initially, but then after a while kept spinning.

**Comment by kmuthukk** [comment] 2019-12-20 22:01
[logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/3990446/logs.tar.gz)

**Comment by WesleyW** [comment] 2019-12-20 22:25
Already fixed in current verison.

**Comment by kmuthukk** [comment] 2019-12-20 22:46
@WesleyW - please mention details of what the high level issue was, and what commit addresses it.

**Comment by iSignal** [comment] 2019-12-21 02:51
@kmuthukk : From @m-iancu : I think the metrics isssue is caused by dropping the demo db and re-creating and will manifest as a Keyspace identifier not found  error in the tserver logs.
I think it should be fixed by @jason’s DROP DATABASE  fix (that landed recently but is not in 2.0.8 ).

Looks like the fix was verified by wesley.

I don't have the exact commit that fixes it but my guess would be 6994a85679ef798eb032427a8fef7ff842268e6f - is that right?

**Comment by kmuthukk** [comment] 2019-12-27 22:56
@WesleyW -- feel free to close the issue again (given @iSignal 's information above).

**Comment by m-iancu** [comment] 2019-12-27 23:00
@iSignal Yes, 6994a85 is the commit that fixed the root cause.

**Closed** 2020-01-06 18:05 UTC
