### ISSUE TITLE
[DocDB] Setting TEST_docdb_log_write_batches=true results in failure of INSERT

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#12194] opened 2022-04-18 20:57 UTC
Jira Link: [DB-469](https://yugabyte.atlassian.net/browse/DB-469)
### Description

Create a cluster with TEST_docdb_log_write_batches=true and observe the following -

```
./bin/yb-ctl create --rf=1 --data_dir ~/yugabyte-data --tserver_flags 'TEST_docdb_log_write_batches=true'
./bin/ysqlsh
yugabyte=# create table test (k int primary key, v int);
CREATE TABLE
yugabyte=# insert into test values (1, 1);
ERROR:  Network error: recvmsg error: Connection refused
yugabyte=#
```

**Comment by rthallamko3** [comment] 2022-04-20 17:07
good starter task

**Comment by jasonyb** [comment] 2022-05-20 23:07
I do not think it's simple.  Duplicate of issue #11975.

**Closed by jasonyb** 2022-05-20 23:07 UTC
Labels: kind/bug, duplicate, good first issue, area/docdb, priority/medium
