### ISSUE TITLE
[YSQL] "Rows Removed by Index Recheck"  with row-wise comparison

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#11280] opened 2022-01-30 19:54 UTC
Jira Link: [DB-1101](https://yugabyte.atlassian.net/browse/DB-1101)
### Description

With [row-wise comparison](https://www.postgresql.org/docs/current/functions-comparisons.html#ROW-WISE-COMPARISON) it looks like the predicates are not pushed down. And, combined with column comparison, show a wrong result bug. This is 11.2-YB-2.11.2.0-b0 

The testcase is an example for pagination easy to reproduce:
```
create table demo (id int primary key,ts timestamptz, key int, val int);
insert into  demo 
select n, timestamptz '2021-01-29 00:00:00'+mod(n,300)*interval '1 minute', mod(n,3), 42 
from generate_series(1,1000) n;

create index demoi on demo(key, ts desc,id desc);

-- get the first first page of 5 rows

select * from demo
where key=1
order by ts desc,id desc limit 5;

-- get the next page after the fifth row fro above result:

select * from demo
where key=1
and (ts,id)<(timestamptz '2021-01-29 04:55:00',595)
order by ts desc,id desc limit 5;
```
Execution plan for this second page shows:
```
yugabyte=# explain analyze
select * from demo
where key=1
and (ts,id)<(timestamptz '2021-01-29 04:55:00',595)
order by ts desc,id desc limit 5;

                                                      QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..0.84 rows=5 width=20) (actual time=2.385..2.390 rows=5 loops=1)
   ->  Index Scan using demoi on demo  (cost=0.00..16.75 rows=100 width=20) (actual time=2.383..2.388 rows=5 loops=1)
         Index Cond: ((key = 1) AND (ROW(ts, id) < ROW('2021-01-29 04:55:00+00'::timestamp with time zone, 595)))
         Rows Removed by Index Recheck: 5
 Planning Time: 0.087 ms
 Execution Time: 2.429 ms
(6 rows)
```
The `Rows Removed by Index Recheck` is the number of rows that we wanted to skip with `and (ts,id)<(timestamptz '2021-01-29 04:55:00',595)` so it looks like this was not pushed down.

Trying to add the predicate on the first column in order to workaround this:
```
yugabyte=# 
select * from demo 
where key=1
and (ts,id)<(timestamptz '2021-01-29 04:55:00',595)
     and ts<=timestamptz '2021-01-29 04:55:00'
order by ts desc,id desc limit 5;

 id | ts | key | val
----+----+-----+-----
(0 rows)
```
This is a wrong result. The same with `/*+ SeqScan(demo) */` returns `(5 rows)` which is the right result

[DB-1101]: https://yugabyte.atlassian.net/browse/DB-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by FranckPachot** [comment] 2022-01-30 20:16
Adding a workaround waiting for a fix:
```
explain analyze 
select * from demo 
where key=1
and (ts<=timestamptz '2021-01-29 04:55:00')
and (ts!=timestamptz '2021-01-29 04:55:00' or id < 595) 
order by ts desc,id desc limit 5;
```
This will skip to the timestamp, so the `Rows Removed by Filter` is limited to the rows with the same timestamp

**Comment by sushantrmishra** [comment] 2023-10-24 20:51
Correctness issue is fixed by  issue #19384

**Comment by tanujnay112** [comment] 2023-10-24 21:03
Right now we only support pushing down row compare expressions if the table in question is range partitioned and the row compare expression must involve the entire primary key. In this case, the concerned table seems hash partitioned. We can extend support to more cases in the future if needed.

**Comment by sushantrmishra** [comment] 2023-10-28 16:28
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/11794

**Closed by sushantrmishra** 2023-10-28 16:28 UTC
Labels: kind/bug, area/ysql, priority/high
