### ISSUE TITLE
[YCQL] Long term fix for PREPARE performance degradation

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#16247] opened 2023-02-27 17:21 UTC
Jira Link: [DB-5673](https://yugabyte.atlassian.net/browse/DB-5673)
### Description

A regression in `PREPARE` performance was introduced in the following fix: https://github.com/yugabyte/yugabyte-db/commit/06f5be74e44c4409913c8caa6f33c6832b64ab3a
Since `PREPARE` is supposed to be rare (typical flow prepare once and execute many times) this should not affect most use-cases. But it case `PREPARE` is misused or perhaps the app setup creates a `PREPARE` storm by running many prepares at once, then this could be an significant performance issue.

In https://github.com/yugabyte/yugabyte-db/issues/16135 this was partially addressed by adding a flag:
The diff adds a new flag `cql_use_metadata_cache_for_schema_version_check` (`false` by default). If set to true it uses the local metadata cache bypassing the performance issue. But the tradeoff is that `PREPARE` may now use old metadata leading to more app errors after an ALTER that modifies the specific table.

This issue tracks a long-term solution that would address the perf degradation while also having reasonable behavior after an `ALTER` table.

[DB-5673]: https://yugabyte.atlassian.net/browse/DB-5673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment] 2023-03-02 15:57
One of possible solutions:
https://phabricator.dev.yugabyte.com/D23259   (WIP)
POC - a try to replace RPC to the Master by RPC to a Tablet.
To get the up-to-date table schema version - to check it in PREPARE
(and to do re-PREPARE if the table was changed). (edited)

**Comment by OlegLoginov** [comment] 2023-05-05 16:55
See the doc with new tests results - it's referenced in https://yugabyte.atlassian.net/browse/DB-5673.
From the tests I don't see any difference between "cql_use_metadata_cache_for_schema_version_check" is  true and  false.
That's why it looks safe to set the flag into true by default.

My conclusion: let's trust the cache (via `cql_use_metadata_cache_for_schema_version_check=true` by default) and stop the activity.

**Comment by OlegLoginov** [comment] 2023-05-19 16:36
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/17163

**Closed by OlegLoginov** 2023-05-19 16:36 UTC
Labels: priority/high, area/ycql, kind/perf
