### ISSUE TITLE
[YSQL] Postgres process does not exit on mac

### ISSUE THREAD

**Issue by spolitov** [YugaByte/yugabyte-db#763] opened 2019-01-16 19:34 UTC
Executing:
bin/yb-ctl create --enable_postgres
bin/yb-ctl stop

ps -ef | grep postgres

There are a lot of postgres processes exists.

**Comment by mbautin** [comment] 2019-01-16 19:44
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/650

**Closed** 2019-01-16 19:44 UTC
Labels: bug
