### ISSUE TITLE
FATAL: New operation's hybrid time too low: { physical: 1593156402030123 }

### ISSUE THREAD

**Issue by keerthikumarsr95** [yugabyte/yugabyte-db#4911] opened 2020-06-28 13:17 UTC
Jira Link: [DB-1721](https://yugabyte.atlassian.net/browse/DB-1721)
@kmuthukk @mbautin as per the slack conversion
https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1593184068362000

One of the tserver went down in a 3 master 9 node setup on 3 regions. 

As one of the tserver went down had impact on db operations
**Not Working**
- create table
- create index

**Working**
- create database
- insert
- read

**Encountered error** 
```
ERROR:  Invalid argument: Invalid table definition: Timed out waiting for Table Creation
```
**Log from one of the master**
```
E0626 11:28:13.304296  2161 catalog_manager_bg_tasks.cc:138] Error processing pending assignments, aborting the current task: Invalid argument (yb/master/catalog_manager.cc:6517): An error occurred while selecting replicas for tablet 001ae39a55664142b6f0041ce298066a: Invalid argument (yb/master/catalog_manager.cc:6517): Not enough tablet servers in the requested placements. Need at least 3, have 2: Not enough tablet servers in the requested placements. Need at least 3, have 2
```

**Log from failed Node**
```
E0626 07:38:08.536649 25122 consensus_queue.cc:629] T f167d49b893048cb907cc3817351133f P b91ccfe7ea064d519245032d2396e11a [LEADER]: Error trying to read ahead of the log while preparing peer request: Incomplete (yb/consensus/log_cache.cc:252): Op with index 3 is ahead of the local log (next sequential op: 3). Destination peer: 31c0c7c451ec45e1a4235596b566612e
F0626 07:38:10.687754 12745 mvcc.cc:398] T f167d49b893048cb907cc3817351133f P b91ccfe7ea064d519245032d2396e11a: T f167d49b893048cb907cc3817351133f P b91ccfe7ea064d519245032d2396e11a: Recent 32 MVCC operations:
1. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157080782071 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
2. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157081037010 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
3. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157081324141 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
4. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157081467084 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
5. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157081942269 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
6. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157081989209 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
7. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157082367321 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
8. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157082401378 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
9. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157082898457 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
10. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157082935443 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
11. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157083460523 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
12. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157083475590 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
13. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157083982618 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
14. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157084000626 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
15. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157084396782 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
16. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157084574696 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
17. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157084828825 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
18. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157085069836 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
19. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157085222980 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
20. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157085621884 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
21. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157085796052 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
22. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157086154959 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
23. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157086199150 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
24. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157086671258 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
25. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157086777025 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
26. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157087140368 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
27. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157087338126 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
28. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157087559461 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
29. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157087846216 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
30. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157087954579 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
31. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157088465300 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
32. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1593157088536616 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
New operation's hybrid time too low: { physical: 1593156402030123 }
  max_safe_time_returned_with_lease_={ safe_time: { physical: 1593156404529248 } source: kHybridTimeLease }
  *ht < max_safe_time_returned_with_lease_.safe_time=1
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_with_lease_.safe_time.ToUint64())=-10236416000
  ht->PhysicalDiff(max_safe_time_returned_with_lease_.safe_time)=-2499125
  max_safe_time_returned_without_lease_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_without_lease_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_without_lease_.safe_time.ToUint64())=6525568622715383808
  ht->PhysicalDiff(max_safe_time_returned_without_lease_.safe_time)=1593156402030123
  max_safe_time_returned_for_follower_={ safe_time: <min> source: kUnknown }
  *ht < max_safe_time_returned_for_follower_.safe_time=0
  static_cast<int64_t>(ht->ToUint64() - max_safe_time_returned_for_follower_.safe_time.ToUint64())=6525568622715383808
  ht->PhysicalDiff(max_safe_time_returned_for_follower_.safe_time)=1593156402030123
  (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown})={ safe_time: <min> source: kUnknown }
  *ht < (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time.ToUint64())=6525568622715383808
  ht->PhysicalDiff((SafeTimeWithSource{last_replicated_, SafeTimeSource::kUnknown}).safe_time)=1593156402030123
  (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown})={ safe_time: <min> source: kUnknown }
  *ht < (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time=0
  static_cast<int64_t>(ht->ToUint64() - (SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time.ToUint64())=6525568622715383808
  ht->PhysicalDiff((SafeTimeWithSource{last_ht_in_queue, SafeTimeSource::kUnknown}).safe_time)=1593156402030123
  is_follower_side=1
  queue_.size()=0
  queue_=[]
  aborted=[]
```
Issue was solved on bringing back failed node. But want to know what was the root cause?

**Comment by ddorian** [comment] 2020-06-29 15:01
@keerthikumarsr95 can you verify is [ntp is configured and running](https://www.2daygeek.com/check-verify-ntp-sync-is-working-or-not-in-linux-using-ntpq-ntpstat-timedatectl/) ? Or are you using another tool for clock synchronization ?

**Comment by mbautin** [comment] 2020-07-01 05:26
@keerthikumarsr95 Would you mind sharing the full log file for the tablet server that crashed?

**Comment by mbautin** [comment] 2020-07-01 05:28
And also from other tablet servers, if possible. I am interested in logs up to 06/26/2020 11:30 (i.e. until the moment the tserver crashed).

**Comment by kmuthukk** [comment] 2020-07-01 06:15
@keerthikumarsr95 also shared that:

date seems to be same on all the machines.
Also can see the ntp status similar across all node.
but one error is common in all nodes as below
```
 [root@yb-db ~]# ntpq -p
ntpq: read: Connection refused
```

and later:
```
i am using YB 2.1.6.0

recently leaders node was going down . I noticed It was due to low memory. 
Got to know because logs were around 16GB for both Tserver/Master process. 
the log collected was for 9 days with each day around 1.8GB...
Does the log rotation happens automatically?  is there any way to configure log ?
```

**Comment by keerthikumarsr95** [comment] 2020-07-02 05:21
@mbautin I recently cleared all the logs due to below error

`recently leaders node was going down . I noticed It was due to low memory. 
Got to know because logs were around 16GB for both Tserver/Master process. 
the log collected was for 9 days with each day around 1.8GB...
Does the log rotation happens automatically?  is there any way to configure log ?`

Also i was testing the what happens when all the  tserver process is down except 1 Leader and 1 Follower.
Overnight it has generated 20GB of logs. 

All Log files contained 

`I0701 12:13:58.569895  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569898  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569903  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569907  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569911  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569916  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569919  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.
I0701 12:13:58.569924  6791 cluster_balance_util.h:457] tablet server 88174e5e823e4e468283511f27d9dd02 has invalid placement info. Not allowing it to take more tablets.`

**Comment by kmuthukk** [comment] 2020-07-02 19:53
hi @keerthikumarsr95 --

another user had reported similar issue in slack: https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1592524612137600

and it turned out that the conf file:

```
--placement_cloud=aws 
--placement_region=us-east
--placement_zone=us-east-1a
```
had an extra space after the word "aws" at the end of the line. And this caused the load balancer / create table etc. operations to complain that placement info of TServer didn't match the yb-master's placement info settings.

Unfortunately, because the error message just said "invalid placement info" without further details, it took longer to troubleshoot. We have filed issue #4827 to make the error reporting more informative.

Can you share the output of http://yb-master-ip:7000/cluster-config and see if the placement info their matches the available TServers (you can verify each TServer's placement on http://yb-master-ip:7000/tablet-servers view).



Bin Shi (Pinterest):hourglass_flowing_sand:  14 days ago

**Comment by mbautin** [comment] 2020-07-02 21:26
Hi @keerthikumarsr95, just as some background on the "new operation hybrid time too low" issue. This is an internal invariant check that makes sure we are not trying to update the database state at a hybrid timestamp if it has already been read at a higher hybrid timestamp. Hybrid timestamps, assigned using the [Hybrid Logical Clock](https://cse.buffalo.edu/tech-reports/2014-04.pdf) algorithm, are what we use for MVCC (multi-version concurrency control) timestamps. And "safe time" is a timestamp determined by the leader of a tablet (shard) such that the state of the tablet at that timestamp (or an earlier timestamp) is not supposed to change. It is determined using a concept of a "hybrid time leader lease", which is a way for the leader of a tablet to declare its exclusive authority of assigning hybrid timestamps less than or equal than a certain "leader lease expiration" value, normally assigned as the current hybrid time plus two seconds. This leader lease expiration time is included in Raft RPCs the leader sends to followers, and a hybrid time leader lease acknowledged by the majority of the Raft group of the tablet (e.g. the leader and one follower in case of replication factor of 3) is considered to be a "majority replicated" hybrid time leader lease. This document has more details on this topic: https://docs.yugabyte.com/latest/architecture/transactions/single-row-transactions/#safe-timestamp-assignment-for-a-read-request

Normally, of course, an invariant violation like this would not happen. But currently, in certain situations, like server crashes, clock skew, servers coming online after being offline for an extended time period, there might still be subtle issues causing these invariant violations to happen, and it is important for us to get to diagnosing the root cause of them.

While we are still in the process of investigating this issue, we have some observations based on the log above. If we look at one of the messages from the log above, e.g.:

```
SafeTime { min_allowed: deadline: 9223372036.855s ht_lease: { time: { physical: 1593157088536616 } lease: { physical: 1593156404529248 } } safe_time: { physical: 1593156404529248 } }
```
we see that the difference between the current clock time and the hybrid time expiration timestamp (ht_lease) timestamp is `1593157088536616 - 1593156404529248` or `684007368` microseconds, or approximately 10 minutes 48 seconds (thanks to @spolitov for pointing this out). This means that this tablet server, even given the fact that it still considered the itself leader of the Raft group, was not able to replicate an extension of its hybrid time leader lease expiration to its followers for that amount of time. It is possible in case of a network partition, when the two other servers in the Raft group could have already elected a new leader and that new leader added some records to the Raft log.

Coming back to the invariant violation itself, `is_follower_side=1`, meaning this tablet server finally became a follower of the tablet, and got an UpdateConsensus RPC from the new leader with some new records.
Also, we see that `ht->PhysicalDiff(max_safe_time_returned_with_lease_.safe_time)=-2499125` (this is microseconds), which means that the new record's hybrid timestamp was 2.5 seconds behind the previous majority-replicated leader lease of the old leader. 2.5 seconds is a common default RPC timeout in YugabyteDB, which is an additional avenue for our further investigation.

We will continue this investigation and attempts to reproduce this issue internally, and will post additional findings as they become available.

**Comment by keerthikumarsr95** [comment] 2020-07-06 16:39
@kmuthukk check for the placement info... I can see that data is replicated on all three placement zones. I have attached the images for reference 
<img width="1278" alt="Screenshot 2020-07-06 at 10 02 43 PM" src="https://user-images.githubusercontent.com/34748484/86617277-a165d980-bfd4-11ea-9927-228f96b4ab46.png">
<img width="639" alt="Screenshot 2020-07-06 at 9 49 28 PM" src="https://user-images.githubusercontent.com/34748484/86617306-a9257e00-bfd4-11ea-86d3-13da5a1aa825.png">

@mbautin thank you for the details explanation... If i face the same issue will the log...
I have used  yb_client_admin_operation_timeout_sec as 600 seconds. could this also be the reason, as timeout happens after 600 seconds and in between the new leader was elected?

**Comment by kmuthukk** [comment] 2020-07-06 17:28
hi @keerthikumarsr95 --

You have 9 TServers, but in 9 different zones. Given that the replication factor is 3 -- it'll be better if the three regions have 3 servers each in the same zone within the region rather than in three different zones within each region.

Essentially, you can put 3 TServers in asia-northeast1-c, 3 TServers in europe-west1-b, 3 TServers in us-centra1-f to match your http://yb-master-ip:7000/cluster-config.

Currently, because 6 of your TServers are not in any of the above three zones -- they are not being utilized at all as you can see from your first screenshot.

**Comment by CharlotteRose** [comment] 2021-03-25 16:59
@mbautin - now that we are seeing this crop up in some environments, I am curious if this has been addressed in any builds, moreover what is the general status/consensus on priority of this issue. Additionally, if there is information you need from our customer I am happy to give as much data and context as needed in order to round out this story.

**Closed** 2022-07-27 23:02 UTC
Labels: kind/bug, area/docdb, priority/medium, community/request
