### ISSUE TITLE
[Platform] User claims to have selecetd S3 Default but BackupParams point to  NFS

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#8855] opened 2021-06-11 08:54 UTC
Observed on http://portal.dev.yugabyte.com/universes/47fdf7db-78fc-4ef0-b92e-fd3ed1c9ec9a/overview

User was trying to restore backup
The backup task failed with error like could not find "/backup" path on tserver.
The task in question had storageConfigUuid pointing to NFS default with storage location being s3 url.
User is certain that she selected S3 default each time. Yet we end up creating a task that has incorrect params.
The restore task is:
```
{
  "errorString": null,
  "nodeExporterUser": "prometheus",
  "deviceInfo": null,
  "universeUUID": "47fdf7db-78fc-4ef0-b92e-fd3ed1c9ec9a",
  "expectedUniverseVersion": null,
  "cmkArn": null,
  "encryptionAtRestConfig": {
    "encryptionAtRestEnabled": false,
    "kmsConfigUUID": null,
    "opType": "UNDEFINED",
    "type": "DATA_KEY"
  },
  "nodeDetailsSet": null,
  "communicationPorts": {
    "masterHttpPort": 7000,
    "masterRpcPort": 7100,
    "tserverHttpPort": 9000,
    "tserverRpcPort": 9100,
    "redisServerHttpPort": 11000,
    "redisServerRpcPort": 6379,
    "yqlServerHttpPort": 12000,
    "yqlServerRpcPort": 9042,
    "ysqlServerHttpPort": 13000,
    "ysqlServerRpcPort": 5433,
    "nodeExporterPort": 9300
  },
  "extraDependencies": {
    "installNodeExporter": true
  },
  "firstTry": true,
  "keyspace": "yugabyte",
  "tableName": null,
  "tableUUID": null,
  "sse": false,
  "storageConfigUUID": "2164e937-f4ed-478a-9251-5c1ee7366157",
  "kmsConfigUUID": null,
  "storageLocation": "s3://backups.yugabyte.com/portal/univ-fe588e92-088f-4465-b863-14b880c68605/backup-2021-06-10T11:21:50-2060695218/keyspace-yugabyte",
  "actionType": "RESTORE",
  "backupType": null,
  "tableNameList": null,
  "tableUUIDList": null,
  "backupList": null,
  "schedulingFrequency": 0,
  "cronExpression": null,
  "timeBeforeDelete": 0,
  "enableVerboseLogs": false,
  "transactionalBackup": false,
  "parallelism": 8,
  "scheduleUUID": null
}
```

`  "storageConfigUUID": "2164e937-f4ed-478a-9251-5c1ee7366157", `
points to NFS Default storage.
Looking at backend code only way we can end up with this task params combination is if UI posts it as such.
Also interesting that backup config page on the UI thinks that the universe in question is using `NFS Default` config
![image](https://user-images.githubusercontent.com/73500297/121658844-8f977c80-ca56-11eb-9607-d07c0ff17668.png)

**Comment by sb-yb** [comment] 2021-06-11 23:00
![image](https://user-images.githubusercontent.com/73500297/121756154-07ed5480-cace-11eb-864a-ec8ca0887826.png)

![image](https://user-images.githubusercontent.com/73500297/121756166-13408000-cace-11eb-9143-f82fc41849d1.png)

**Comment by sunilsutarDCE** [comment] 2021-06-15 12:34
@sb-yb : Discussed with perf team and have managed to reproduce this . This happens at first time when go to backups and try to restore . Will fix this .

**Comment by shashwat-yb** [comment] 2021-07-06 20:04
I am facing this issue on [2.7 portal](http://portal.dev.yugabyte.com/). I selected S3 backup storage but it is pointing to NFS and failing to create backup.

`Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"f160ce4e-0671-4957-9e7c-58a5c0577307","expectedUniverseVersion":null,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":120..., hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Backup exception: Did not find nfs backup storage path: /backup mounted on tablet server 172.151.20.88"}.`

cc @VijiYB @sridhar-yb @sb-yb

**Comment by VijiYB** [comment] 2021-07-06 20:06
@sunilsutarDCE - Can you please check, we are still facing the same issue on the portal which is on b159.

**Comment by VijiYB** [comment] 2021-07-07 01:12
Looks like this issue is for restore which got fixed, same is happening currently with the **backup creation**. So closing this as we can track the backup creation with a new GH issue https://github.com/yugabyte/yugabyte-db/issues/9190

@sunilsutarDCE - Assigned the backup creation to you.

**Comment by sunilsutarDCE** [comment] 2021-07-08 04:47
Closing this as related issue for create backup is create #9190 .

**Closed by sunilsutarDCE** 2021-07-08 04:47 UTC
Labels: area/platform
