### ISSUE TITLE
[DocDB] Cluster with splitting enabled that was recently restored may fail select count(*) statement

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#12780] opened 2022-06-03 19:18 UTC
Jira Link: [DB-660](https://yugabyte.atlassian.net/browse/DB-660)
### Description

Reproduced in 2.13.3.0-b134 version, 3 nodes cluster.

flags to enable intensive splitting
```
"instance_type": "c5.2xlarge",
"master_gflags": {
    "tablet_split_low_phase_size_threshold_bytes": "2097152",
    "tablet_split_limit_per_table": "8172",
    "enable_automatic_tablet_splitting": "true",
    "tablet_split_low_phase_shard_count_per_node": "134217728",
    "ysql_num_shards_per_tserver": "1",
},
"tserver_gflags": {
    "ysql_num_shards_per_tserver": "1",
    "memstore_size_mb": "1",
}
```

1. start cluster with intensive splitting
2. start READ-WRITE workload for 2 hours
3. create snapshot schedule and wait for first snapshot created
4. restore snapshot 20 times in row  
5. after that run select count(*)  to determine approximate number of inserted keys
6. continue read only workload and check data consistency

Restore itself works fine.
On 4th step test failed while calling `select count(*)` statement with following error

```
ERROR:  Not found: [Not found (yb/tserver/read_query.cc:322): Tablet not found: 1f8ae5d7
```

Might be related to https://github.com/yugabyte/yugabyte-db/issues/12631

**Comment by SrivastavaAnubhav** [comment] 2022-06-10 19:44
Closing as duplicate of #12802.

**Closed by SrivastavaAnubhav** 2022-06-10 19:44 UTC
Labels: kind/bug, area/docdb, priority/medium
