### ISSUE TITLE
[YCQL] Logging into a role without password will crash tserver.

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#2506] opened 2019-10-03 20:27 UTC
After enabling YCQL authentication, I tried creating a role with `login=true` and no password. Creation worked but attempting to log in with the role will crash the tserver.
Steps:
- `bin/yb-ctl start --tserver_flags=use_cassandra_authentication=true`
- `bin/cqlsh -u cassandra -p cassandra`
- `create role testing with login=true;`
- `select * from system_auth.roles` shows correct roles.
- `exit`
- `bin/cqlsh -u testing` will prompt for a password and then crash after any input.

tserver fatal log:
```
F1003 13:18:14.812242 268431360 ql_value.h:113] Check failed: pb_.has_string_value() 
```

Looks like a failed null check since password is recorded as null.

**Comment by hectorgcr** [comment] 2020-10-05 18:23
This has been closed by 65d3cc7 and duplicate of #4459

**Closed by hectorgcr** 2020-10-05 18:23 UTC
Labels: kind/bug
