### ISSUE TITLE
[YCQL] Prepare Statements are being Re-Prepared Resulting in Higher Latency

### ISSUE THREAD

**Issue by randersenYB** [yugabyte/yugabyte-db#10999] opened 2022-01-05 23:03 UTC
Jira Link: [DB-692](https://yugabyte.atlassian.net/browse/DB-692)
### Description

At times, YCQL prepare statements are being re-prepared without any reason. This behavior is consistent with both the Java 3.x and 4.x drivers and the C# driver. I haven't been able to reproduce this issue with Apache Cassandra V3.11 using Java driver version 4.13.

The issue is that when the statements are being re-prepared it is causing additional latency plus resource utilization on both the server and on the client. We also noticed with a customer that non-prepared statements actually outperformed prepared statements under heavy load. 

When this behavior occurs it is consistent across multiple executions of the testing application until the cluster is restarted. It can also occur randomly where the re-prepares occur during normal execution of the original prepares. 

The test application just performs four select statements against the same table (with and without a bind). The select statement is only prepared once and used in 3 of the select statements. The fourth select is a simple statement for reference. The table is not altered or updated during the testing. Tablet leader elections did not occur during the testing. I have ran the test application approx. 100 times with varying degrees of behavior. 

I have enabled "debug" mode on the driver to capture debugging tracing information to document the driver's behavior using YB 4.11 Java driver with a YB 2.6.5 and 2.11 DB. The YDB cluster is a single AZ with 6 nodes.

I have attached four driver traces where the prepare behavior was "correct" and when it re-prepared during select statement execution. 

### I have an example debug trace of a prepare statement:
`
==> Prepare...
DEBUG [s0|id: 0xd29a6a1f, L:/172.22.144.1:1094 - R:/172.17.0.10:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|1178290888] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1178290888] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|1178290888] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1178290888] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1178290888] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1178290888] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1178290888] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|1178290888] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|1178290888] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|1178290888] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|id: 0xf33d1b69, L:/172.22.144.1:1093 - R:/172.17.0.7:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|1178290888] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
DEBUG [s0|id: 0xd1138d77, L:/172.22.144.1:1098 - R:/172.17.0.8:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|id: 0x771e5e8d, L:/172.22.144.1:1095 - R:/172.17.0.11:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|id: 0x33b87539, L:/172.22.144.1:1097 - R:/172.17.0.9:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|id: 0xf54b5483, L:/172.22.144.1:1096 - R:/172.17.0.12:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|1178290888] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
DEBUG [s0|1178290888] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
DEBUG [s0|1178290888] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
DEBUG [s0|1178290888] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
java.nio.HeapByteBufferR[pos=0 lim=16 cap=16]
==> Prepare Completed
`

### Below is a select statement using the prepared statement, normal behavior:
`
==> Select 2 (prepared)...
DEBUG [s0|id: 0xf54b5483, L:/172.22.144.1:1096 - R:/172.17.0.12:9042] Got last response on in-flight stream id 0, completing and releasing
==> Select 2 expecting Completed
==> Select 2 Result java.util.LinkedHashSet: {91,65,null,[]},
`

### Below is a select statement using the prepared statement, re-prepared behavior:
`
==> Select 2 (prepared)...
DEBUG [s0|id: 0xb983433f, L:/172.22.144.1:1952 - R:/172.17.0.12:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|1930837320|0] Executing PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null)
DEBUG [s0|1930837320|0] Successfully wrote PREPARE(SELECT pk, ck, coll  FROM randersen.t1521_v1, null), waiting for response
DEBUG [s0|id: 0xb983433f, L:/172.22.144.1:1952 - R:/172.17.0.12:9042] Got last response on in-flight stream id 0, completing and releasing
DEBUG [s0|1930837320|0] Got response PREPARED(0x974e17fc7c5675f5c90aaea78887d2f5)
DEBUG [s0|id: 0xb983433f, L:/172.22.144.1:1952 - R:/172.17.0.12:9042] Got last response on in-flight stream id 0, completing and releasing
==> Select 2 expecting Completed
==> Select 2 Result java.util.LinkedHashSet: {91,65,null,[]},
`

[YCQLSelectPrepare4X-OutputNormal.txt](https://github.com/yugabyte/yugabyte-db/files/7818241/YCQLSelectPrepare4X-OutputNormal.txt)
[YCQLSelectPrepare4X-OutputNormalPK.txt](https://github.com/yugabyte/yugabyte-db/files/7818242/YCQLSelectPrepare4X-OutputNormalPK.txt)
[YCQLSelectPrepare4X-OutputRePrepare.txt](https://github.com/yugabyte/yugabyte-db/files/7818243/YCQLSelectPrepare4X-OutputRePrepare.txt)
[YCQLSelectPrepare4X-OutputRePreparePK.txt](https://github.com/yugabyte/yugabyte-db/files/7818244/YCQLSelectPrepare4X-OutputRePreparePK.txt)
[YCQLSelectPrepare4X.zip](https://github.com/yugabyte/yugabyte-db/files/7818246/YCQLSelectPrepare4X.zip)
[t1521_v1-ddl.zip](https://github.com/yugabyte/yugabyte-db/files/7818265/t1521_v1-ddl.zip)

**Comment by randersenYB** [comment] 2022-02-04 21:55
Maybe related to https://github.com/yugabyte/yugabyte-db/issues/11258?

**Comment by Sfurti-yb** [comment] 2022-03-27 16:53
I tried reproducing the error with the example that was provided, and am unable to do so. I created the table with the ddl provided, and inserted few rows in it. Then I ran the example with Driver version 4.11 and Yugabyte version 2.11. Are there any steps that I am missing or anything additional that I have to do? Since you have mentioned that this error is seen only at times, was the example run multiple times to get it?

**Comment by randersenYB** [comment] 2022-03-30 20:59
A few rows and running the application once will not trigger this issues. You need to add at least 50,000 rows making sure all nodes have an equal number of rows. The application doesn't trigger the issue but you must "somehow get into this state". It can take 100K selects and multiple runs (it is not easy). Once the DB is in this "state" it is consistent until you perform a rolling restart.

**Comment by ashetkar** [comment] 2023-01-13 10:12
Issue not reproducible, closing the ticket.

**Closed by ashetkar** 2023-01-13 10:12 UTC
Labels: kind/bug, priority/medium, area/ecosystem
