### ISSUE TITLE
[Docs] Port over explore section to use yugabyted instead of yb-ctl

### ISSUE THREAD

**Issue by sanketkedia** [yugabyte/yugabyte-db#8612] opened 2021-05-25 17:35 UTC
Currently, our [explore ](https://docs.yugabyte.com/latest/explore/) section uses yb-ctl as the tool for managing local clusters. We want to move away from it to use yugabyted. This issue tracks the porting over work.

**Comment by polarweasel** [comment] 2021-05-26 20:45
Duplicate of #6187

**Closed by polarweasel** 2021-05-26 20:45 UTC
Labels: area/documentation
