### ISSUE TITLE
[DocDB] PITR: Disallow TRUNCATE for colocated tables

### ISSUE THREAD

**Issue by vkulichenko** [yugabyte/yugabyte-db#12505] opened 2022-05-13 19:02 UTC
Jira Link: [[DB-340]](https://yugabyte.atlassian.net/browse/DB-340)
### Description

Fix provided in #11777 is not applied to colocated tables. TRUNCATE should be disabled for all tables (colocated and non-colocated) in case there is a PITR schedule.

[DB-340]: https://yugabyte.atlassian.net/browse/DB-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment] 2023-03-03 16:08
We will support TRUNCATE + PITR with colocated tables. On colocated tables, TRUNCATE emits a tombstone record and is correctly rolled back on PITR restore.

Longer-term, we may use the same approach to support TRUNCATE + PITR on distributed tables.

Resolving this as by design.

**Closed by tverona1** 2023-03-03 16:08 UTC
Labels: kind/enhancement, area/docdb, priority/medium
