### ISSUE TITLE
[YSQL][Colocation]: NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 158, master version 157

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18112] opened 2023-07-06 08:16 UTC
Jira Link: [DB-7147](https://yugabyte.atlassian.net/browse/DB-7147)
### Description

Tried on version **2.19.1.0-b109**
While creating index on a colocated table the following issue popped up.
```
NOTICE:  Retrying wait for backends catalog version: Requested catalog version is too high: req version 158, master version 157
```
```
1. Create a cluster with g-flags for Tablet splitting, RPC and Packed columns
2. Restore a backup which has 2000 colocated tables with 1k rows in each
3. Create 5 non-colocated table 
4. Create 1000 colocated index ----> Issue seen here
```
**Instance size**: c5.large
```
tserver_gflags={
                "ysql_enable_packed_row": "true",
                "ysql_enable_packed_row_for_colocated_table": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_max_connections": "500",
                "backfill_index_client_rpc_timeout_ms": "180000",
                'client_read_write_timeout_ms': str(30 * 60 * 1000),
                'yb_client_admin_operation_timeout_sec': str(30 * 60),
                "lazily_flush_superblock": "true"
            }
master_gflags={
                "ysql_enable_packed_row": "true",
                "ysql_enable_packed_row_for_colocated_table": "true",
                "enable_automatic_tablet_splitting": "true",
                "tablet_split_low_phase_size_threshold_bytes": "2097152",
                "tablet_split_limit_per_table": "8172",
                "consistent_restore": "true",
                "enable_truncate_on_pitr_table": "true",
                "lazily_flush_superblock": "true"
            }
```
[Logs](http://stress.dev.yugabyte.com/stress_test/2eae9912-ab1f-4dc4-8437-22c14b297853) (Attachment -> Universe logs)
[Test Logs](http://stress.dev.yugabyte.com/stress_test/2eae9912-ab1f-4dc4-8437-22c14b297853)(Attachment -> Framework logs)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7147]: https://yugabyte.atlassian.net/browse/DB-7147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment] 2023-07-06 18:06
Duplicate of #17342

**Closed by jasonyb** 2023-07-06 18:06 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
