### ISSUE TITLE
[YSQL] Regression (2.16 only): Observing lots of ERROR: Illegal state: Used read time is not set with INSERTs. (SqlDataLoad)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#20099] opened 2023-11-30 15:49 UTC
Jira Link: [DB-9042](https://yugabyte.atlassian.net/browse/DB-9042)
### Description

Noticing a regression in test runs. Mainly running SqlDataLoad and observing lots of `ERROR: Illegal state: Used read time is not set`  with INSERTs.

I am seeing this on only 2.16 and from somewhere after build 2.16.9.0-b29. Please note this is consistently seen in the following runs. 

Thus, I suspect this checkin [[BACKPORT 2.16][#19407] YSQL: Single shard operations should pick read time only after conflict resolution](https://phorge.dev.yugabyte.com/D29856), which went in is causing this, which went in from 2.16.9.0-b32.

Stress run report in JIRA.

```
[Thread-10] ERROR ExceptionsTracker - Failed write with error: Batch entry 1 INSERT INTO test_cdc_ddd734 (k, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
java.sql.BatchUpdateException: Batch entry 1 INSERT INTO test_cdc_ddd734 (k, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, uuid) VALUES (..........)
.
. 
was aborted:  Call getNextException to see other errors in the batch.
	at com.yugabyte.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:570) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:887) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.jdbc.PgStatement.executeBatch(PgStatement.java:910) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.sample.apps.SqlDataLoad.doWrite(SqlDataLoad.java:406) [yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:972) [yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88) [yb-stress-sample-apps-1.1.29.jar:?]
Caused by: com.yugabyte.util.PSQLException: ERROR: Illegal state: Used read time is not set
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2098) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1455) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1480) ~[yb-stress-sample-apps-1.1.29.jar:?]
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:545) ~[yb-stress-sample-apps-1.1.29.jar:?]
	... 7 more
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9042]: https://yugabyte.atlassian.net/browse/DB-9042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment] 2023-12-13 18:12
Found the root cause: this is occurring on 2.16 and not master because the above test does a batch INSERT. Before 48cd6825, each insert in a batch was incorrectly treated as a separate single shard i.e., fast path transaction. However, the whole batch is supposed to be a single distributed transaction. The fix was backported to 2.16 but explicitly disabled (`yb_pg_batch_detection_mechanism` is set to `IGNORE_BATCH_DELETE_AND_UPDATE_MAY_FAIL` on 2.16 instead of `DETECT_BY_PEEKING` which is the default on master).

Precise detail as to why a batch insert fails with `used read time not set` when it doesn't use a distributed transaction: when each insert in a batch is wrongly treated as a separate single shard transaction, the 2nd insert expects the `used_read_time` to be present in pg_client_session.cc, which doesn't happen if a distributed transaction is started on the 1st insert (which leads to a read point being set for the whole transaction lifetime).

Assigning to @gauravk-in to fix it. @gauravk-in once fixed, let me know and I can help test it out.

**Closed** 2024-03-16 21:57 UTC
Labels: kind/bug, area/ysql, priority/high, qa_stress
