### ISSUE TITLE
PostgreSQL: Support for pg_notify and LISTEN

### ISSUE THREAD

**Issue by juwalter** [yugabyte/yugabyte-db#2899] opened 2019-11-09 19:58 UTC
I was wondering, if `pg_notify` and accordingly `LISTEN` is supported in any capacity?

```
LISTEN foo;
ERROR:  This statement not supported yet
LINE 1: LISTEN foo;
        ^
HINT:  Please report the issue on https://github.com/YugaByte/yugabyte-db/issues```

https://www.postgresql.org/docs/9.0/sql-notify.html
```

Actual use case:

```
CREATE TABLE dashboard_subscriptions(
    id SERIAL,
    category varchar(256),
    is_event boolean);

CREATE OR REPLACE FUNCTION dashboard_subscriptions_notify()
	RETURNS trigger AS
$$
BEGIN
	PERFORM pg_notify(
	    'dashboard_subscriptions_channel',
	    json_build_object(
            'operation', TG_OP,
            'record', row_to_json(NEW)
        )::text
	);
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER dashboard_subscriptions
	AFTER INSERT OR UPDATE OF is_event
	ON dashboard_subscriptions
	FOR EACH ROW
EXECUTE PROCEDURE dashboard_subscriptions_notify();

--
INSERT INTO dashboard_subscriptions (category, is_event)
VALUES ('info', 'false');
```

Thanks!

**Comment by ddorian** [comment] 2019-11-11 09:12
duplicate of https://github.com/yugabyte/yugabyte-db/issues/1872

**Closed by ddorian** 2019-11-11 09:12 UTC
Labels: community/request
