### ISSUE TITLE
[YSQL] A Read Operation Blocking A Conflicting Write Operation in MVCC Implemented by YugabyteDB

### ISSUE THREAD

**Issue by Coconut-DB1024** [yugabyte/yugabyte-db#17033] opened 2023-04-26 03:22 UTC
Jira Link: [DB-6346](https://yugabyte.atlassian.net/browse/DB-6346)
### Description

When runing a workload on the lasted version of YugabyteDB, we find that a select operation wound block a conflicting update operation.
However, as described in [YugabyteDB Transaction][1], YugabyteDB have implemented MVCC to achieve the read operations do not blocking the conflicting write operations.
We have run the same workload on PostgreSQL, the anomaly does not happen.
More specifically, the workload is as follows.

|  transaction ID   | operation  |
|---|---|
|   0  |   START TRANSACTION ISOLATION LEVEL SERIALIZABLE;    |
|   0  | SELECT k,v FROM table0 WHERE k=3; |
|   1  |   START TRANSACTION ISOLATION LEVEL SERIALIZABLE;    |
|  1  | UPDATE table0 SET v=123 WHERE k=3; |

YugabyteDB version we use is PostgreSQL 11.2-YB-2.17.2.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.3 (https://github.com/yugabyte/llvm-project.git 0b8d1183745fd3998d8beffeec8cbe99c1b20529), 64-bit.

Note that, the database schema and the initial datbase are as follows
drop database if exists "DDB";
create database "DDB";
create table table0 (k int primary key, v int);
insert into table0 values(3, 12344);

[1]: https://docs.yugabyte.com/preview/architecture/transactions/transactions-overview/ 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6346]: https://yugabyte.atlassian.net/browse/DB-6346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment] 2023-05-10 17:17
This is expected behaviour -- a read in `serializable` isolation conflicts with a write because YugabyteDB's implementation of serializable isolation differs from Postgres'. Pg uses SSI (serializable snapshot isolation) to implement serializability, but we use 2PL (two phase locking).

This difference is more because of the different underlying implementation than MVCC:

1. Even in Pg's serializable, a read can conflict with a write in certain cases e.g., if you have two transactions T1 and T2 such that they read keys k1 and k2 respectively, but then write to keys k2 and k1. Pg will throw a serialization error here even though there are no conflicting writes. So, Pg utilizes MVCC in serializable level to avoid conflicts in simpler situations like the one you mentioned.

2. In other words, Pg utilizes MVCC to reduce the number of conflicts by not conflicting until there are no [circular r-w dependencies](https://wiki.postgresql.org/wiki/SSI). YugabyteDB's data format allows MVCC too but it doesn't utilize MVCC's power in serializable isolation level. In repeatable read and read committed isolation, YugabyteDB makes uses of the MVCC ability and behaves the same as Postgres i.e., reads don't conflict with writes.

However, I will encourage you to try serializable isolation after setting these Tserver gflags: `enable_wait_queues=true` and `enable_deadlock_detection=true`.  Setting these flags will switch our concurrency control scheme to [Wait-on-Conflict](https://docs.yugabyte.com/preview/architecture/transactions/concurrency-control/#wait-on-conflict) which is a beta feature, but this helps reduce the number of conflicts in serializable isolation level. I am going to skip the explanation as to why this mode reduces the number of conflicts in serializable isolation level.

**Closed** 2023-06-01 18:38 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
