### ISSUE TITLE
Data file size are different between nodes

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#4012] opened 2020-03-19 02:11 UTC
Why the tserver data size are different between nodes(logs size not counted)?
I have a 3 node universe with rf 3 but the size of data between nodes are too much different:
![yugabyte-filesize](https://user-images.githubusercontent.com/28354390/77024306-6d25c900-69a3-11ea-8722-de71ed134dcb.png)
2 tserver are using about 10GB (number 1 & 3) while one of them using about 1.5GB(number 3)

![tablet-servers](https://user-images.githubusercontent.com/28354390/77024444-c7bf2500-69a3-11ea-9a45-92635b1f9263.png)

while yb-admin UI is showing tablets are balanced between nodes

**Comment by bmatican** [comment] 2020-03-19 02:30
cc @amitanandaiyer , maybe similar to https://github.com/yugabyte/yugabyte-db/issues/3666 ?

@zeinali0 Are your disks xfs? Also which version of yugabyte are you using?

**Comment by kmuthukk** [comment] 2020-03-19 04:52
From the screenshot there's ~1200 tablets on each node. So ~1200 MANIFEST* files.

So, like @bmatican suspects, if it is the issue #3666 (which has recently been fixed) -- that could explain about 1200*4MB = 4.8GB overhead on nodes where the yb-tserver was restarted (because of the unintended 4MB pre-allocation/fallocate call). This is a one-time cost per tablet in older release - and will be avoided in releases that include the fix for #3666.

@zeinali0 -- can you look for some MANIFEST* files inside the data directory and compare the size reported by "du -hs <filename>" vs. "ls -lh <filename" to see if it is a duplicate of #3666?

Thx!

**Comment by zeinali0** [comment] 2020-03-19 07:03
i'm using version 2.1.0.0.
i reset another node tserver and now it is using about 1.5GB.

**Comment by zeinali0** [comment] 2020-03-19 07:17
> can you look for some MANIFEST* files inside the data directory and compare the size reported by "du -hs " vs. "ls -lh <filename" to see if it is a duplicate of #3666?
Yes it is duplicate 66 byte file size and 4.0 MB on disk

**Comment by zeinali0** [comment] 2020-03-19 08:01
it increased to 10GB again

**Comment by ddorian** [comment] 2020-03-19 09:02
Looks like the patch is in 2.1.2 https://github.com/yugabyte/yugabyte-db/blob/50aaf8d5853b40b7e393d9f138aa536ff3e224c1/src/yb/rocksdb/util/options.cc#L264

I tried locally and reports to 64KB. Can you retry @zeinali0 ?

**Comment by kmuthukk** [comment] 2020-03-19 15:26
Thx for confirming @zeinali0 that it indeed is a duplicate of #3666.

Like @ddorian mentioned, this issue is fixed in 2.1.2 release. Please see release notes here:

https://github.com/yugabyte/yugabyte-db/releases/tag/v2.1.2

However, please note that the fix will not apply to tables already created. It will only apply to new tables created after the upgrade.

**Closed by kmuthukk** 2020-03-19 15:26 UTC
Labels: area/docdb, community/request

**Comment by zeinali0** [comment] 2020-03-26 11:13
The issue fixed after upgrading to 2.1.2.0.
