### ISSUE TITLE
[DocDB] Restore task while migrating from the old colocation implementation to the new one gets stuck in IMPORT_SNAPSHOT and fails; Core file generated

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#16324] opened 2023-03-06 11:28 UTC
Jira Link: [DB-5751](https://yugabyte.atlassian.net/browse/DB-5751)

### Description

- Create a universe in 2.14 with automatic tablet splitting enabled
- Create a colocated database with tables opted in and out of colocation using the old schema; Create views and materialized views on these tables, Create Indexes(unique, partial and secondary) on the tables
- Execute DDLs', DMLs' on the schema
- Create a backup- B01
- Execute more DDLs, DMLs'
- Create a backup- B02 
- Upgrade the universe to 2.16 and add packed storage, auto scheduled compactions and Packed Columns + Packed and Colocation gflags
- Execute DDLs, DMLs' 
- Create a backup- B03 
- Execute DDLs, DMLs' 
- Create a backup- B04  
- Upgrade the universe to 2.18 
- Create a backup of the DB i
- Drop the databases created in step 2
- Restore the most latest backup
**Issue:**
Restore backup fails with 
```
Task id 3bfa06a2-1038-4791-878f-ac69e08c010f_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Failed with error COMMAND_FAILED.
```

**Logs:** https://drive.google.com/drive/folders/138jJrrADG87U2VebFAQE2Db5_esVsnpi?usp=share_link 
 
**Core file** is uploaded to the jumphost in this location- `/home/centos/kripa_cores/core_sq_worker.30790`
**Build:** 2.17.3.0-b44 
**Universe:** https://portal.dev.yugabyte.com/universes/ebd3565c-5a8f-4c2d-8531-a40d3abd61ed/overview

Before failing, the restore was indefinitely stuck in the `IMPORT_SNAPSHOT` step.
```
-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:00:23.570Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:00:23.570Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:00:38.572Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:00:38.572Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:00:53.573Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:00:53.573Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:01:08.575Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:01:08.575Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:01:23.576Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:01:23.577Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:01:38.578Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:01:38.578Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
YW 2023-03-06T11:01:53.579Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Number of retries 0
YW 2023-03-06T11:01:53.580Z [INFO] 140bbc73-9e9c-4cd8-9f1b-0fca2061d7be from YbcTaskBase in TaskPool-RestoreBackup(ebd3565c-5a8f-4c2d-8531-a40d3abd61ed)-0 - Task id 202d4264-ab88-4f91-98a1-4fb4e6b14f14_PGSQL_TABLE_TYPE_cl_old_implementation_01 status: Current task stage - IMPORT_SNAPSHOT
```

**Schema used:**
```
create database cl_old_implementation_01 with colocated=true;
\c cl_old_implementation_01
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE complex AS (re float8, im float8);
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');
CREATE DOMAIN postal_code AS TEXT CHECK(VALUE ~ '^\d{5}$'OR VALUE ~ '^\d{5}-\d{4}$');

CREATE TABLE cl_size_check (id TEXT PRIMARY KEY, uuid_col uuid DEFAULT uuid_generate_v4(), name text COLLATE "en_US.utf8", c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX",date DATE, n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code)  WITH (COLOCATED = true);


Create many colocated tables:
-----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('CREATE TABLE table_with_cl_old_def_%s (id TEXT PRIMARY KEY, uuid_col uuid DEFAULT uuid_generate_v4(), name text COLLATE "en_US.utf8", c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX",date DATE, n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code, fk_id text, CONSTRAINT foreign_key_%s FOREIGN KEY(fk_id) REFERENCES table_with_cl_old_def_1(id) ON DELETE SET NULL) WITH (COLOCATED = true)',k,k);
   END LOOP;
END
$do$;


Create materialized views on colocated tables:
-----------------------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('CREATE MATERIALIZED VIEW mv_table_with_cl_old_def_%s as select * from table_with_cl_old_def_%s',k,k);
   END LOOP;
END
$do$;

Create views on colocated tables:
-----------------------------------------------
DO
$do$
BEGIN 
   FOR k IN 23..100 LOOP
      EXECUTE format('CREATE VIEW v_table_with_cl_old_def_%s as select * from table_with_cl_old_def_%s',k,k);
   END LOOP;
END
$do$;

Create non-colocated tables:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE TABLE table_%s (id TEXT PRIMARY KEY, uuid_col uuid DEFAULT uuid_generate_v4(), name text COLLATE "en_US.utf8", c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details, age int, collated_data text collate "POSIX",date DATE, n NUMERIC (3, 2),r real, c1 CHAR(1), created_at timestamptz, uuid0 uuid DEFAULT uuid_nil(), uuid1 uuid DEFAULT uuid_generate_v1(), p1 POINT,t1 TIME,ts1 TIMESTAMP,i4 INTERVAL,p2 path, p3 polygon,b box, c2 circle, l line, l1 lseg, a2 text[][], zip postal_code) WITH (COLOCATED = false)',k);
   END LOOP;
END
$do$;

Create mat views on non-colocated tables:
------------------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE MATERIALIZED VIEW mv_table_%s as select * from table_%s',k,k);
   END LOOP;
END
$do$;

Create views on non-colocated tables:
------------------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE VIEW v_table_%s as select * from table_%s',k,k);
   END LOOP;
END
$do$;



Indexes:
------
Colocated:
----------
Unique:
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('CREATE UNIQUE INDEX uni_cl_old_%s ON table_with_cl_old_def_%s(id)',k,k);
   END LOOP;
END
$do$;

Indexes:
---------
partial:
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('CREATE INDEX par_cl_old_%s ON table_with_cl_old_def_%s(id) WHERE id LIKE ''%%3''',k,k);
   END LOOP;
END
$do$;

Secondary:
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('CREATE INDEX sec_cl_old_%s ON table_with_cl_old_def_%s(id)',k,k);
   END LOOP;
END
$do$;

Non-colocated:
--------------
Unique: 
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE UNIQUE INDEX uni_ncl_%s ON table_%s(id)',k,k);
   END LOOP;
END
$do$;


partial:
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE INDEX par_ncl_%s ON table_%s(id) WHERE id LIKE ''%%3''',k,k);
   END LOOP;
END
$do$;

Secondary:
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('CREATE INDEX sec_ncl_%s ON table_%s(id)',k,k);
   END LOOP;
END
$do$;

Insert rows into the table:
----------------------------
DO
$do$
BEGIN 
   FOR i IN 1..5 LOOP
      FOR j IN 1..2000 LOOP
      EXECUTE format('INSERT INTO table_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000);',i,j);
      END LOOP;
   END LOOP;
END
$do$;

DO
$do$
BEGIN 
   FOR i IN 1..100 LOOP
      FOR j IN 1..200 LOOP
      EXECUTE format('INSERT INTO table_with_cl_old_def_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000);',i,j);
      END LOOP;
   END LOOP;
END
$do$;


Refresh materialized view: Non-colocated tables:
-----------------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('Refresh materialized view mv_table_%s',k);
   END LOOP;
END
$do$;


Refresh materialized view: colocated table
-----------------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('Refresh materialized view mv_table_with_cl_old_def_%s',k);
   END LOOP;
END
$do$;

ADD COLUMNS TO CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('ALTER TABLE table_with_cl_old_def_%s add column new_col_1 text, add column new_col_2 text, add column new_col_3 text',k);
   END LOOP;
END
$do$;

ADD COLUMNS TO NON-CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('ALTER TABLE table_%s add column new_col_1 text, add column new_col_2 text, add column new_col_3 text',k);
   END LOOP;
END
$do$;

Insert post alter 1:
-------------------

DO
$do$
BEGIN 
   FOR i IN 1..5 LOOP
      FOR j IN 2001..10000 LOOP
      EXECUTE format('INSERT INTO table_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;

DO
$do$
BEGIN 
   FOR i IN 1..100 LOOP
      FOR j IN 201..250 LOOP
      EXECUTE format('INSERT INTO table_with_cl_old_def_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;

Update old rows pre -upgrade 1:
------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('UPDATE table_with_cl_old_def_%s SET new_col_1= md5(random()::text), new_col_2= md5(random()::text), new_col_3= md5(random()::text)',k);
   END LOOP;
END
$do$;


DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('UPDATE table_%s  SET new_col_1= md5(random()::text), new_col_2= md5(random()::text), new_col_3= md5(random()::text)',k);
   END LOOP;
END
$do$;

Alter 2:
---------
ADD COLUMNS TO CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('ALTER TABLE table_with_cl_old_def_%s add column new_col_4 text, add column new_col_5 text, add column new_col_6 text',k);
   END LOOP;
END
$do$;

ADD COLUMNS TO NON-CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('ALTER TABLE table_%s add column new_col_4 text, add column new_col_5 text, add column new_col_6 text',k);
   END LOOP;
END
$do$;


Update old rows pre -upgrade 2:
------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('UPDATE table_with_cl_old_def_%s SET new_col_4= md5(random()::text), new_col_5= md5(random()::text), new_col_6= md5(random()::text)',k);
   END LOOP;
END
$do$;


DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('UPDATE table_%s  SET new_col_4= md5(random()::text), new_col_5= md5(random()::text), new_col_6= md5(random()::text)',k);
   END LOOP;
END
$do$;


Insert post alter 2:
-------------------
DO
$do$
BEGIN 
   FOR i IN 1..5 LOOP
      FOR j IN 10001..20000 LOOP
      EXECUTE format('INSERT INTO table_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;


DO
$do$
BEGIN 
   FOR i IN 1..100 LOOP
      FOR j IN 251..350 LOOP
      EXECUTE format('INSERT INTO table_with_cl_old_def_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;

Alter 3:
---------
ADD COLUMNS TO CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('ALTER TABLE table_with_cl_old_def_%s add column new_col_7 text, add column new_col_8 text, add column new_col_9 text',k);
   END LOOP;
END
$do$;

ADD COLUMNS TO NON-CL TABLE:
----------------------------
DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('ALTER TABLE table_%s add column new_col_7 text, add column new_col_8 text, add column new_col_9 text',k);
   END LOOP;
END
$do$;


Update old rows pre -upgrade 3:
------------------------------
DO
$do$
BEGIN 
   FOR k IN 1..100 LOOP
      EXECUTE format('UPDATE table_with_cl_old_def_%s SET new_col_7= md5(random()::text), new_col_8= md5(random()::text), new_col_9= md5(random()::text)',k);
   END LOOP;
END
$do$;


DO
$do$
BEGIN 
   FOR k IN 1..5 LOOP
      EXECUTE format('UPDATE table_%s  SET new_col_7= md5(random()::text), new_col_8= md5(random()::text), new_col_9= md5(random()::text)',k);
   END LOOP;
END
$do$;


Insert post alter 3:
-------------------
DO
$do$
BEGIN 
   FOR i IN 1..5 LOOP
      FOR j IN 20001..30000 LOOP
      EXECUTE format('INSERT INTO table_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6,new_col_7,new_col_8,new_col_9) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;


DO
$do$
BEGIN 
   FOR i IN 1..100 LOOP
      FOR j IN 401..450 LOOP
      EXECUTE format('INSERT INTO table_with_cl_old_def_%s(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details,age,collated_data, date,n,r,c1,created_at,p1,t1,ts1,i4,p2,p3,c2,l,l1,a2,zip,new_col_1,new_col_2,new_col_3,new_col_4,new_col_5,new_col_6,new_col_7,new_col_8,new_col_9) VALUES (%s,''Hermione'',(1,2), ''{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}'',''{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}'', ''{1, 2, 3}'', ''$99.99'' ,''1.1.1.1'', ''00:00:00:00:00:00'',1,2,666,''Sms'',15, md5(random()::text), current_timestamp,5.36,2147483647,''G'',now(), point(3, 4),LOCALTIME(0), current_timestamp(0),  ''00:25:00'', ''(1,3), (4,12)'',''(1,3),(4,12), (2,4)'',''10, 4, 10'',''{1,2,3}'',''(0, 4), (2,8)'',''{{"b1", "c"}, {"m1", "l"}}'',89000,md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text),md5(random()::text));',i,j);
      END LOOP;
   END LOOP;
END
$do$;

```

[DB-5751]: https://yugabyte.atlassian.net/browse/DB-5751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment] 2023-03-07 05:57
@yifanguan ,

I see that the logs are flooded with 
```
I0306 10:17:20.418606  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1be85d5e3b9b4a23b67635fe76d49ad0 (table_5 [id=00004000000030008000000000004a98]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x000055956295fc18, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418612  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1c8750eb30334abab3b793c71200e669 (table_3 [id=00004000000030008000000000004a7c]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x000055956295ee18, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418618  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1d3508848ab9414a99dc5fbd39de2aca (sec_ncl_2 [id=00004000000030008000000000004c01]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x00005595592c4fd8, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418624  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1d59402a63484fc1844e957a3a6d6c1e (sec_ncl_3 [id=00004000000030008000000000004c02]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x00005595592c4718, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418630  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1dd9c80579eb4f1f8ea6cb9f51511434 (sec_ncl_1 [id=00004000000030008000000000004c00]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x00005595592c5a58, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418638  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1e36e54583cc4621a0a3c4188397e035 (table_3 [id=00004000000030008000000000004a7c]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x00005595592c4e18, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
I0306 10:17:20.418643  7840 async_rpc_tasks.cc:398] DeleteTablet RPC for tablet 1e681a2da27b4974acdf9da509784452 (uni_ncl_1 [id=00004000000030008000000000004bf6]) on TS=c6dd294fb7c6439098a0f02d0f795e26 (task=0x000055955908e718, state=kRunning): Scheduling retry with a delay of 45ms (attempt = 2 / 2147483647)...
```
Per table I see about 20 entries of the Scheduling retry log and then I see for these tables
```
4fb7c6439098a0f02d0f795e26: delete failed for tablet 3b0b446b53ac460eab2b60ce12e8b7c5 with error code TABLET_NOT_RUNNING: Already present (yb/tserver/ts_tablet_manager.cc:1460): State transition of tablet 3b0b446b53ac460eab2b60ce12e8b7c5 already in progress: {3b0b446b53ac460eab2b60ce12e8b7c5, opening tablet}
```

**Comment by yifanguan** [comment] 2023-03-07 21:27
Duplicate of #14861

**Closed** 2023-03-08 17:26 UTC
Labels: kind/bug, area/docdb, priority/medium
