### ISSUE TITLE
[YugabyteD] [QA] [Enhancement] Have different generated password for YSQL and YCQL and also allow user to give passwords

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14871] opened 2022-11-05 16:28 UTC
### Description

Currently we are generating same password for YSQL and YCQL. We should generate different passwords for them.
And we should also allow users to give their choice of passwords.
```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ cat /Users/mzafar/kk/data/yugabyted_credentials.txt 
YSQL Credentials:
Username: yugabyte
Password: dzlD9AWwzO7i
Database: yugabyte

YCQL Credentials:
Username: cassandra
Password: dzlD9AWwzO7i
Keyspace: None
```

**Comment by nchandrappa** [comment] 2022-11-09 00:56
Duplicate of #14870, do we know what yb-managed or yb-anywhere do here?

**Comment by zlareb1-yb** [comment] 2022-11-09 06:06
We can give different passwords for YSQL and YCQ during provisioning of Universes in YBA @nchandrappa

**Comment by ShikharSahay** [comment] 2023-11-17 04:50
When creating a universe in YB-Anywhere, an identical password is generated for both YSQL and YCQL. This is consistent with the existing functionality in yugabyted.

**Closed by ShikharSahay** 2023-11-17 04:50 UTC
Labels: area/ossexp
