### ISSUE TITLE
JSONB support for Go Cassandra-driver

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#844] opened 2019-02-07 01:27 UTC

**Comment by m-iancu** [comment] 2022-03-07 03:42
Duplicate of #1373. Fixed in [29ccf593e60ae47479f61155dd1c5d995d1c4c8d](https://github.com/yugabyte/gocql/commit/ff20ac0da69945c9c57b94103b2e0dd73a4bbbc7).

**Closed by m-iancu** 2022-03-07 03:42 UTC
Labels: kind/enhancement
