### ISSUE TITLE
[platform] AWS backup provider config should support IAM role as well

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4204] opened 2020-04-13 18:37 UTC
the main AWS cloud provider can be setup using either IAM Role or using Access Key/Secret. however, the AWS backup provider config is only for Access Key/Secret. we need to add support for IAM Role as another way to configure the AWS backup provider.

**Comment by ajcaldera1** [comment] 2020-04-13 23:59
Duplicate of 4199.

**Comment by ajcaldera1** [comment] 2020-04-14 00:13
Closed in error -- reopened.

**Comment by schoudhury** [comment] 2020-04-14 21:25
this issue is dependent on https://github.com/yugabyte/yugabyte-db/issues/4199 since the data nodes need to be provisioned with the IAM role first.

**Closed** 2020-04-23 06:54 UTC
Labels: area/platform, kind/enhancement, priority/high
