### ISSUE TITLE
[Platform] Universe creation (with TLS) failed on non-replicated env

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8465] opened 2021-05-14 21:00 UTC
Universe creation (with TLS) failed with below error on non-replicated platform instance

Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":250,"numVolumes":1,"diskIops":null,"throughput":null,"storageClass":"standard","mountPoints":null,"storageType":"GP2"}..., hit error java.lang.RuntimeException: 2021-05-14 20:53:28,373 INFO validate_credentials:cloud.py:95: Found aws cloud credentials in env.
/opt/yugabyte/packages/yugabyte-2.7.1.0-b184/devops/python2_installed_modules/boto3/compat.py:86: PythonDeprecationWarning: Boto3 will no longer support Python 2.7 starting July 15, 2021. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be found here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
  warnings.warn(warning, PythonDeprecationWarning)
2021-05-14 20:53:28,406 INFO load:credentials.py:1100: Found credentials in environment variables.
2021-05-14 20:53:28,946 INFO scp_to_tmp:__init__.py:664: [app] Copying local '/opt/yugabyte/releases/2.7.1.0-b184/yugabyte-2.7.1.0-b184-centos-x86_64.tar.gz' to remote '/tmp/yugabyte-2.7.1.0-b184-centos-x86_64.tar.gz'
2021-05-14 20:53:39,387 INFO callback:method.py:661: [app] Copying package /opt/yugabyte/releases/2.7.1.0-b184/yugabyte-2.7.1.0-b184-centos-x86_64.tar.gz to yb-dev-viji-nonrep-271-t1-n1 took 10.442 sec
2021-05-14 20:53:39,388 INFO callback:method.py:663: Configuring Instance: yb-dev-viji-nonrep-271-t1-n1
2021-05-14 20:53:39,388 INFO callback:method.py:680: Creating and copying over client TLS certificate to yb-dev-viji-nonrep-271-t1-n1
Traceback (most recent call last):
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b184/devops/python2_installed_modules/bin/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b184/devops/python2_installed_modules/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b184/devops/python2_installed_modules/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b184/devops/python2_installed_modules/ybops/cloud/....

**Comment by streddy-yb** [comment] 2021-05-18 00:15
hi @VijiYB - Can you provide the complete scenario? Is it simple universe creation with TLS enabled on a non-replicated Platform?

**Comment by VijiYB** [comment] 2021-05-18 00:20
Yes its a simple universe creation with client-node and node-node TLS enabled.

**Comment by WesleyW** [comment] 2021-05-19 02:46
Issue was caused by #8345 , closing this one as duplicate

**Closed by WesleyW** 2021-05-19 02:46 UTC
Labels: 2.6 Backport Required, area/platform, priority/high
