### ISSUE TITLE
[Docs] [Platform] clarify OS compatibility

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#10767] opened 2021-12-02 19:11 UTC
### Description

From [this thread](https://yugabyte.slack.com/archives/C01HFHVV3NV/p1638388849298100?thread_ts=1638377551.286300&cid=C01HFHVV3NV)... Need to clarify per Sridhar's third point (edited):

> Supported OSs for deploying YBDB using Platform. Platform team needs to do additional work to qualify each of the OSs from Ansible/Python/3rd party dependencies point of view. Ubuntu 18.04 and Oracle 8 are good examples of this. [this is not documented]
>
> There are two sources of ambiguity here:
> - When someone is looking at Platform docs, they might think that list is also supported for running DBs which is not the case.
> - If someone is looking at OSS docs, it might give the impression Platform supports these as well. 
>
> I think we should add a supported OSs for DB section as part of Platform documentation.

This is related to #9847. PR #10749 addresses the OS version 8 incompatibility, but doesn't address the larger issue.

**Comment by lizayugabyte** [comment] 2022-05-31 18:09
Someone from product management should provide guidance on this

**Comment by lizayugabyte** [comment] 2022-07-25 18:23
This looks like a duplicate of https://yugabyte.atlassian.net/browse/PLAT-4780

**Comment by lizayugabyte** [comment] 2022-10-21 16:31
Closing as duplicate

**Closed by lizayugabyte** 2022-10-21 16:31 UTC
Labels: area/documentation
