### ISSUE TITLE
[YCQL] Flaky 2.12 test: CqlTabletSplitTest.BatchTimeseriesRf1

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#14627] opened 2022-10-24 19:25 UTC
Jira Link: [DB-3998](https://yugabyte.atlassian.net/browse/DB-3998)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=2.12&class=CqlTabletSplitTest&name=BatchTimeseriesRf1

**Comment by arybochkin** [comment] 2023-01-30 18:41
Looks like it's not failing on [master]( https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=CqlTabletSplitTest&name=BatchTimeseriesRf1&num_commits=500) branch starting from 09/23/2022:

09/23/2022 20:03	centos-master-clang14-tsan/47/		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang14-tsan/47/artifact/build/tsan-clang14-dynamic-ninja/yb-test-logs/tests-integration-tests__cql-tablet-split-test/CqlTabletSplitTest_BatchTimeseriesRf1.log

../../src/yb/integration-tests/cql-tablet-split-test.cc:688
Expected: (num_read_errors) <= (kMaxReadErrors), actual: 779 vs 100

**Comment by arybochkin** [comment] 2023-01-30 18:44
But still fails for [2.14](https://detective-gcp.dev.yugabyte.com/stability/test?branch=2.14&class=CqlTabletSplitTest&name=BatchTimeseriesRf1&num_commits=500):

01/26/2023 20:05	mac12-master-clang-release-x86_64/15/		Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-mac12-master-clang-release-x86_64/15/artifact/build/release-clang-dynamic-ninja/yb-test-logs/tests-integration-tests__cql-tablet-split-test/CqlTabletSplitTest_BatchTimeseriesRf1.log

../../src/yb/integration-tests/cql-tablet-split-test.cc:687
Expected: (num_read_errors) <= (kMaxReadErrors), actual: 107 vs 100

**Comment by arybochkin** [comment] 2023-01-30 19:43
Maybe this issue should be backport to 2.14 https://github.com/yugabyte/yugabyte-db/issues/13847, backport to 2.12 is looking incomplete.

**Comment by arybochkin** [comment] 2023-02-02 12:42
it might take a lot of cycles to identify all the changes which fixed the test in master/2.16 branches and may become a real challenge to backport all of them. so, it was decided to not backport to 2.14 and older releases (confirmed with @rthallamko3), hence closing.

**Closed by arybochkin** 2023-02-02 12:42 UTC
Labels: kind/bug, area/docdb, priority/medium
