### ISSUE TITLE
Need arm64 build of YugabyteDB

### ISSUE THREAD

**Issue by doughadfield** [yugabyte/yugabyte-db#7978] opened 2021-04-09 14:53 UTC
Please can we have an arm64 build of YugabyteDB, so we can use lower cost hardware for testing/training etc?

**Comment by ddorian** [comment] 2021-04-11 07:40
@doughadfield closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/2519. Please subscribe to that issue.

**Closed by ddorian** 2021-04-11 07:40 UTC
