### ISSUE TITLE
[YSQL] Truncate doesn't seem to delete index tables

### ISSUE THREAD

**Issue by ramkumarvs** [YugaByte/yugabyte-db#1175] opened 2019-04-08 21:59 UTC
```
# create table test(id int primary key, value int);
CREATE TABLE
# create unique index uq_test_value on test(value);
CREATE INDEX
# insert into test values(1, 2);
INSERT 0 1
# select * from test;
 id | value
----+-------
  1 |     2
(1 row)

# truncate test;
TRUNCATE TABLE
# select * from test;
 id | value
----+-------
(0 rows)

# insert into test values(1, 2);
ERROR:  Query error: Duplicate key found in primary key or unique index
```

**Comment by robertpang** [comment] 2019-05-02 19:57
The issue is fixed in commit [b7fa3d9](https://github.com/YugaByte/yugabyte-db/commit/b7fa3d9a6fe8b0093478ab0e9ecff506403049fe).

**Closed by robertpang** 2019-05-02 19:57 UTC
Labels: bug, ysql
