### ISSUE TITLE
[DocDB] Backup Task Failed Due to Prolonged Snapshot Creation for Colocated Tables 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#24358] opened 2024-10-09 17:21 UTC
Jira Link: [DB-13270](https://yugabyte.atlassian.net/browse/DB-13270)
### Description

Version: **2.20.7.1-b1**

Logs: Added in Jira

A backup task failed due to prolonged snapshot creation for colocated tables, leading to a timeout after 1 hour and 45 minutes. The backup task encountered several retries for the snapshot creation, but ultimately timed out, causing the backup to fail.
**Database had 10k colocated + 100 non-colocated tables**
Note: The backup was successfully created when the datasize was around 25 GB

Details:

- Backup task failed at: 2024-10-05 T18:01:06
- Backup task ID: c7da597d-0d49-4628-8c8e-990b34b0ed08
- Tablet ID: 2e9c8e7498d24a67954e059aa910b7e4
- Keyspace: colocateddb
- Initial request to create snapshot sent at: 2024-10-05 T16:00:40

Backup task failed at 2024-10-05 T18:01:06 
```
YW 2024-10-05T18:01:06.842Z [ERROR] f45e2f63-787f-4cce-8cf4-6d826e075d3b from BackupTableYbc in TaskPool-CreateBackup(6bf317f6-cc3c-42fb-9a28-b464f5aa6811)-0 - Backup c7da597d-0d49-4628-8c8e-990b34b0ed08 - Keyspace colocateddb - ParamsIdentifier 10ba7209-5871-4b0a-b677-04b2b47367c1 : Polling backup task progress on YB-Controller failed with error Task id c7da597d-0d49-4628-8c8e-990b34b0ed08_PGSQL_TABLE_TYPE_colocateddb_10ba7209-5871-4b0a-b677-04b2b47367c1 status: Failed with error TIMEOUT

```

Backup task was triggered at 2024-10-05 T15:53:47
```
Request to create snapshot was sent at 16:00:40.795425
I1005 16:00:40.795425 45166 catalog_manager_ext.cc:170] Servicing CreateSnapshot request: tables { table_id: "00004000000030008000000000010555" table_name: "table_10099" namespace { id: "00004000000030008000000000000000" name: "colocateddb" database_type: YQL_DATABASE_PGSQL } } tables { table_id: 
.
.
.
 tables { table_id: "00004000000030008000000000010249" table_name: "table_9943" namespace { id: "00004000000030008000000000000000" name: "colocateddb" database_type: YQL_DATABASE_PGSQL } } tables { table_id: "00004000000030008000000000010244" table_name: "table_9942" namespace { id: "00004000000030008000000000000000" name: "colocateddb" database_type: YQL_DATABASE_PGSQL } } tables { table_id: "0000400000003000800000000001023f" table_name: "table_9941" namespace { id: "00004000
I1005 16:00:41.045599 45089 log.cc:882] T 00000000000000000000000000000000 P 918189e2aec54fa8ba02db8f2c836590: Max segment size 67108864 reached. Starting new segment allocation.
I1005 16:00:41.536669 836170 state_with_tablets.cc:157] Snapshot[22cc7b9b-e780-47a8-b97b-7f771d4af740]: Finished CREATING at 35edac99bd26497c97f2648a229a21a5, 601 was running
I1005 16:00:41.536707 836170 catalog_manager_ext.cc:2786] Handling Create Tablet Snapshot Response for tablet 35edac99bd26497c97f2648a229a21a5 (table table_10000 [id=00004000000030008000000000010366])  OK
W1005 16:00:41.536717 836170 catalog_manager_ext.cc:2796] No active snapshot: 
I1005 16:00:41.536919 836168 state_with_tablets.cc:157] Snapshot[22cc7b9b-e780-47a8-b97b-7f771d4af740]: Finished CREATING at e98fc5781e504c7288ed058a52c747d6, 600 was running
I1005 16:00:41.537137 836168 catalog_manager_ext.cc:2786] Handling Create Tablet Snapshot Response for tablet e98fc5781e504c7288ed058a52c747d6 (table table_10000 [id=00004000000030008000000000010366])  OK
W1005 16:00:41.537145 836168 catalog_manager_ext.cc:2796] No active snapshot: 
I1005 16:00:41.539492 836166 state_with_tablets.cc:157] Snapshot[22cc7b9b-e780-47a8-b97b-7f771d4af740]: Finished CREATING at ab5c77cc5a8b462f9f587e282b94a676, 599 was running
I1005 16:00:41.539512 836166 catalog_manager_ext.cc:2786] Handling Create Tablet Snapshot Response for tablet ab5c77cc5a8b462f9f587e282b94a676 (table table_10000 [id=00004000000030008000000000010366])  OK
W1005 16:00:41.539520 836166 catalog_manager_ext.cc:2796] No active snapshot: 
Then TabletSnapshotOp RPC first timed out at 16:01:11.202481
W1005 16:01:11.202481 843868 async_rpc_tasks.cc:586] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2c8282e0, state=kRunning): TS d289e3718aa1480285ec6e3ac4227df5: Tablet Snapshot Operation RPC failed for tablet 2e9c8e7498d24a67954e059aa910b7e4: Timed out (yb/rpc/outbound_call.cc:643): TabletSnapshotOp RPC (request call id 564595) to 172.151.25.169:9100 timed out after 30.000s
I1005 16:01:11.202531 843868 async_rpc_tasks.cc:387] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2c8282e0, state=kRunning): Scheduling retry with a delay of 29ms (attempt = 1 / 20)...
I1005 16:01:13.318065 45111 master_snapshot_coordinator.cc:1211] Number of snapshot operations to be executed 5
which eventually failed at 16:15:41.201930
W1005 16:15:41.201930 1019585 async_rpc_tasks.cc:586] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2c8282e0, state=kRunning): TS d289e3718aa1480285ec6e3ac4227df5: Tablet Snapshot Operation RPC failed for tablet 2e9c8e7498d24a67954e059aa910b7e4: Timed out (yb/rpc/outbound_call.cc:643): TabletSnapshotOp RPC (request call id 571413) to 172.151.25.169:9100 timed out after 0.010s
W1005 16:15:41.201987 1019585 async_rpc_tasks.cc:382] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2c8282e0, state=kRunning): Timed out (yb/master/async_rpc_tasks.cc:381): Request timed out
W1005 16:15:41.202008 1019585 state_with_tablets.cc:170] Snapshot[22cc7b9b-e780-47a8-b97b-7f771d4af740]: Timed out (yb/master/async_rpc_tasks.cc:381): Failed to CREATING snapshot at 2e9c8e7498d24a67954e059aa910b7e4: Request timed out, terminal: 0, 71 was running
```

It was started again
```
W1005 16:16:11.732668 1026057 async_rpc_tasks.cc:586] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2bb8d620, state=kRunning): TS d289e3718aa1480285ec6e3ac4227df5: Tablet Snapshot Operation RPC failed for tablet 2e9c8e7498d24a67954e059aa910b7e4: Timed out (yb/rpc/outbound_call.cc:643): TabletSnapshotOp RPC (request call id 571489) to 172.151.25.169:9100 timed out after 30.000s
I1005 16:16:11.732722 1026057 async_rpc_tasks.cc:387] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d2bb8d620, state=kRunning): Scheduling retry with a delay of 29ms (attempt = 1 / 20)...
```

and then it continued until the backup timed out

```
I1005 18:09:22.361871 2402999 async_rpc_tasks.cc:387] 2e9c8e7498d24a67954e059aa910b7e4 (table 00004000000030008000000000004018.colocation.parent.tablename [id=00004000000030008000000000004018.colocation.parent.uuid]) Tablet Snapshot Operation CREATE_ON_TABLET RPC 22cc7b9b-e780-47a8-b97b-7f771d4af740 (task=0x0000242d3cb66de0, state=kRunning): Scheduling retry with a delay of 60013ms (attempt = 14 / 20)...


```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13270]: https://yugabyte.atlassian.net/browse/DB-13270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment] 2024-10-31 16:54
This is a duplicate of https://github.com/yugabyte/yugabyte-db/issues/11117. Closing it as we'll continue work on it as part of https://github.com/yugabyte/yugabyte-db/issues/11117.

**Closed by lingamsandeep** 2024-10-31 16:54 UTC
Labels: kind/bug, area/docdb, priority/high, QA, qa_automation, 2024.2_blocker
