### ISSUE TITLE
[DocDB] flaky test: TestCQLServiceWithCassAuth.TestReadSystemTableAuthenticated

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17802] opened 2023-06-15 23:42 UTC
Jira Link: [DB-6891](https://yugabyte.atlassian.net/browse/DB-6891)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=TestCQLServiceWithCassAuth&fail_tag=all&name=TestReadSystemTableAuthenticated&platform=linux

traces back to https://phorge.dev.yugabyte.com/D24116

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6891]: https://yugabyte.atlassian.net/browse/DB-6891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hbhanawat** [comment] 2023-11-23 06:16
Duplicate of #17779

**Closed by hbhanawat** 2023-11-23 06:16 UTC
Labels: kind/bug, kind/failing-test, priority/medium, area/ycql
