### ISSUE TITLE
CQL support for DATE, TIME

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#188] opened 2018-04-17 21:41 UTC
Reported by @rkarthik007.

**Comment by m-iancu** [comment] 2022-03-03 01:42
Duplicate of #471. Fixed in 512a592a265c10ab16d6dfc2b5ba8950ae1407ab and 7fa87956bfbfbe5010300d229ed9e1c1c33726a0.

**Closed by m-iancu** 2022-03-03 01:42 UTC
Labels: kind/enhancement
