### ISSUE TITLE
[platform] get universe details api returns inconsistent actions that can be performed on node.

### ISSUE THREAD

**Issue by mjoshi0923** [yugabyte/yugabyte-db#7209] opened 2021-02-11 06:44 UTC
/api/customers/<customerId>/universes/<universeID>

When client access above resource and resource(universe) is one node universe,  we provide two action "REMOVE", "STOP". in most case this actions can't performed when universe is one node cluster. you can't remove that node for sure. you should be able to stop it(not sure).

 
 `universeDetails.nodeDetailsSet: {
   0: {
      allowedActions: ["REMOVE", "STOP"]
  }
 }`

This will show actions in UI which is not possible for user to perform.

**Comment by SergeyPotachev** [comment] 2021-03-30 12:45
Duplicate of #5733.

**Closed** 2021-05-23 21:54 UTC
Labels: area/platform
