### ISSUE TITLE
[YSQL][LST] FATAL: Failed to load sys catalog: Corruption (yb/master/catalog_loaders.cc:265): Failed while visiting tablets in sys catalog: Cannot add a table ... (ColocationId: ...) to a colocation group for tablet ...: place is taken by a table ...

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13167] opened 2022-07-06 07:50 UTC
Jira Link: [DB-2851](https://yugabyte.atlassian.net/browse/DB-2851)
### Description

```
$ cd ~/code/yugabyte-db
$ git checkout 12bff13aeaee3462af62507e9a5510b8c2a66b22
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,ysql_num_shards_per_tserver=1,enable_stream_compression=true,stream_compression_algo=1,yb_num_shards_per_tserver=1 --master_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,enable_stream_compression=true,stream_compression_algo=1,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=40,tablet_split_high_phase_shard_count_per_node=50
$ cd ~/code/yb-long-system-test
$ git checkout e78e1e69c8ca04d8019d54703f1fe70ab75ca3e5
$ python3.9 ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=20 --runtime=60 --max-columns=20 --complexity=full --seed=184667
2022-07-06 03:29:35,536 MainThread INFO     Reproduce with: git checkout e78e1e69 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=20 --runtime=60 --max-columns=20 --complexity=full --seed=184667
2022-07-06 03:29:37,455 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
2022-07-06 03:29:37,461 MainThread INFO     Creating tables for database db_lst_184667
2022-07-06 03:30:52,634 MainThread INFO     Starting worker_0: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,643 MainThread INFO     Starting worker_1: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-07-06 03:30:52,646 MainThread INFO     Starting worker_2: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,684 MainThread INFO     Starting worker_3: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 03:30:52,700 MainThread INFO     Starting worker_4: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,715 MainThread INFO     Starting worker_5: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,753 MainThread INFO     Starting worker_6: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,764 MainThread INFO     Starting worker_7: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 03:30:52,789 MainThread INFO     Starting worker_8: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,809 MainThread INFO     Starting worker_9: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 03:30:52,911 MainThread INFO     Starting worker_10: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,921 MainThread INFO     Starting worker_11: RandomSelectAction, SetConfigAction
2022-07-06 03:30:52,960 MainThread INFO     Starting worker_12: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 03:30:53,018 MainThread INFO     Starting worker_13: RandomSelectAction, SetConfigAction
2022-07-06 03:30:53,020 MainThread INFO     Starting worker_14: RandomSelectAction, SetConfigAction
2022-07-06 03:30:53,025 MainThread INFO     Starting worker_15: RandomSelectAction, SetConfigAction
2022-07-06 03:30:53,030 MainThread INFO     Starting worker_16: RandomSelectAction, SetConfigAction
2022-07-06 03:30:53,034 MainThread INFO     Starting worker_17: RandomSelectAction, SetConfigAction
2022-07-06 03:30:53,039 MainThread INFO     Starting worker_18: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-06 03:30:53,042 MainThread INFO     Starting worker_19: RandomSelectAction, SetConfigAction
2022-07-06 03:31:03,166 MainThread INFO     Worker queries/s: [000.1][000.2][000.1][000.6][000.1][000.1][000.1][000.1][000.1][001.0][000.2][000.0][000.5][000.3][000.2][000.1][000.3][000.2][000.2][000.2]
[...]
2022-07-06 04:28:39,321 MainThread INFO     Worker queries/s: [000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0]
2022-07-06 04:28:48,607 worker_6   ERROR    Unexpected query failure: InternalError_
Query: EXECUTE stmt;
  values: None
  runtime: 2022-07-06 04:20:18.667 - 2022-07-06 04:28:48.607
  supports explain: True
  supports rollback: True
  affected rows: None
Action: RandomSelectAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Network error: Rpc timeout, passed: 15.011s, timeout: 15.000s, now: 137112.428s, last_read_time_: 137097.416s
    @           0x997768  errmsg
    @           0x9c2d38  HandleYBStatusAtErrorLevel
    @           0x56a4d3  YbGetMasterCatalogVersion
    @           0x83e28d  YBPrepareCacheRefreshIfNeeded
    @           0x83cff0  PostgresMain
    @           0x7ad3cc  BackendRun
    @           0x7ac820  ServerLoop
    @           0x7a8e8b  PostmasterMain
    @           0x712bcd  PostgresServerProcessMain
    @           0x713072  main
    @     0x7fdd01f4e825  __libc_start_main
    @           0x4b8939  _start
Transaction isolation level: repeatable read
DB Node: host: 127.0.0.1, port: 5433
DB Backend PID: 971941
```
[lst_2022-07-06_03:29:35_184667.zip](https://github.com/yugabyte/yugabyte-db/files/9052749/lst_2022-07-06_03.29.35_184667.zip)

FATALs:
```
[dfelsing@dev-server-dfelsing yugabyte-data]$ cat ./node-1/disk-1/yb-data/master/logs/yb-master.FATAL.details.2022-07-06T04_23_48.pid149080.txt ./node-3/disk-1/yb-data/master/logs/yb-master.FATAL.details.2022-07-06T04_24_43.pid149086.txt
F20220706 04:23:48 ../../src/yb/master/catalog_manager.cc:993] T 00000000000000000000000000000000 P 3af617ba858641abacfdab5339c6bef7: Failed to load sys catalog: Corruption (yb/master/catalog_loaders.cc:265): Failed while visiting tablets in sys catalog: Cannot add a table 0000809f0000300080000000000081d5 (ColocationId: 309274741) to a colocation group for tablet 137909f38a6b4dcba338f57387527641: place is taken by a table 0000809f0000300080000000000081d5
    @     0x7fa0e992a34c  google::LogDestination::LogToSinks()
    @     0x7fa0e992401f  google::LogMessage::SendToLog()
    @     0x7fa0e9924928  google::LogMessage::Flush()
    @     0x7fa0e9927aaf  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa0ece34039  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7fa0e9c0c16a  yb::ThreadPool::DispatchThread()
    @     0x7fa0e9c00551  yb::Thread::SuperviseThread()
    @     0x7fa0e7fe0694  start_thread
    @     0x7fa0e7d2141d  __clone

F20220706 04:24:43 ../../src/yb/master/catalog_manager.cc:993] T 00000000000000000000000000000000 P 2a8ea5c5745e44bf852bdb8f99fe744c: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: Tablegroup 000067a10000300080000000000067c9 already exists
    @     0x7f4e43d5434c  google::LogDestination::LogToSinks()
    @     0x7f4e43d4e01f  google::LogMessage::SendToLog()
    @     0x7f4e43d4e928  google::LogMessage::Flush()
    @     0x7f4e43d51aaf  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4e4725e039  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7f4e4403616a  yb::ThreadPool::DispatchThread()
    @     0x7f4e4402a551  yb::Thread::SuperviseThread()
    @     0x7f4e4240a694  start_thread
    @     0x7f4e4214b41d  __clone

```
Can't connect to database anymore afterwards:
```
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5433 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```
I have seen these failures before as a consequence of https://github.com/yugabyte/yugabyte-db/issues/12813. Now I haven't seen the "Invalid value of enum ValueEntryType" fatal anymore, but there is still a corruption. @spolitov Is this related to the original issue or a separate issue?
I'll keep yugabyte-data directory around, accessible from Yugabyte organization: https://drive.google.com/file/d/1ASWRJcgOv_77VHkeMIk2OMp-INnQNoEi/view?usp=sharing

**Comment by bmatican** [comment] 2022-07-06 15:36
@def- to confirm, were you hitting this even with packed off?

**Comment by def-** [comment] 2022-07-06 15:50
No, I have recently only checked with `ysql_enable_packed_row=true` since I was actually trying to verify Sergei's other fixes. This (and the other LST bugs) only came up as a side effect of that verification.

**Comment by qvad** [comment] 2022-08-16 10:02
Reproduced during stress testing TABLEGROUPS @frozenspider

**Comment by frozenspider** [comment] 2022-08-18 07:40
From #13644:

> Issue occured during stress testing TABLEGROUPS with 3/3 runs.
> 
> Scenario - spawn 2xlarge VMs 3RF cluster, create 5 tablegroups, spawn 5*10*100 (batches) workload that will load data to tables.
> At some point FATAL occurs
> 
> ```
> F20220816 07:22:59 ../../src/yb/master/catalog_manager.cc:1001] T 00000000000000000000000000000000 P c158b26d1df94b5595435d1103627cbb: Failed to load sys catalog: Corruption (yb/master/catalog_loaders.cc:265): Failed while visiting tablets in sys catalog: Cannot add a table 000033e6000030008000000000004048 (ColocationId: 1838765072) to a colocation group for tablet 6a398db1629e43ff9a9c81084514fe59: place is taken by a table 000033e6000030008000000000004048
>     @     0x7fc14e985c1b  google::LogMessage::SendToLog()
>     @     0x7fc14e986cd8  google::LogMessage::Flush()
>     @     0x7fc14e98715f  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fc151fc3e7e  yb::master::CatalogManager::LoadSysCatalogDataTask()
>     @     0x7fc14ec29e5c  yb::ThreadPool::DispatchThread()
>     @     0x7fc14ec252fb  yb::Thread::SuperviseThread()
>     @     0x7fc14cf9a694  start_thread
>     @     0x7fc14c6d741d  __clone
> ```

**Comment by def-** [comment] 2022-09-15 18:40
I have now also run into this with https://phabricator.dev.yugabyte.com/D19079 which adds backup/restore of the created tables to upgrade tests:
```
testupgraderestorefirst-aws-rf3-upgrade-2.6.18.0_3: Start
	(     0.551s) User Login : Success
	(     0.158s) Refresh YB Version : Success
	(    90.427s) Setup Provider : Success
	(     0.062s) Updating Health Check Interval to 60000 sec : Success
	(   511.230s) Create universe jenk-isd1833-e3b2150e31-20220915-162551 : Success
	(   259.577s) Start sample workloads : Success
	(   906.360s) Create Backups : Success
	(   210.513s) Create Backups : Success
	(    43.788s) Restore Backup: None : Success
	(    30.144s) Restore Backup: None : Success
	(   393.244s) Upgrade Software to 2.15.3.0-b169 : >>> Integration Test Failed <<< 
wait_for_task: Failed task with errors in 390.72315192222595s:
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"8212bee6-5fca-4f65-afab-eabfa16424a1","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=ChangeLoadBalancerState, service=yb.master.MasterService, tablet=null, attempt=22, maxAttempts=100, maxTimeoutMs=120000, elapsedTimeMs=116697). Master config (10.9.135.106:7100,10.9.199.57:7100,10.9.208.114:7100) has no leader.. Exceptions received: org.yb.client.ConnectionResetException: [Peer YB Master - 10.9.135.106:7100] Connection reset on [id: 0x6fc9d72f],org.yb.client.ConnectionResetException: [Peer YB Master - 10.9.199.57:7100] Connection reset on [id: 0x5521a8b5].
	(    21.223s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.15.3.0_testupgraderestorefirst-aws-rf3-upgrade-2.6.18.0_3_20220915_175139 : Success
	(    24.443s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.15.3.0_testupgraderestorefirst-aws-rf3-upgrade-2.6.18.0_3_20220915_175205 : Success
	(     0.000s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.15.3.0_testupgraderestorefirst-aws-rf3-upgrade-2.6.18.0_3_20220915_175205 : Hit error before destroying universe 'jenk-isd1833-e3b2150e31-20220915-162551':
Found FATAL log file in 10.9.135.106/master.
Found FATAL log file in 10.9.199.57/master.
Found FATAL log file in 10.9.208.114/master.

	(   150.269s) Destroy universe : Success
testupgraderestorefirst-aws-rf3-upgrade-2.6.18.0_3: End
```
The FATALs all look like this:
```
F20220915 17:50:02 ../../src/yb/master/catalog_manager.cc:1026] T 00000000000000000000000000000000 P 131af188132943e3a080b43983f232e3: Failed to load sys catalog: Corruption (yb/master/catalog_loaders.cc:265): Failed while visiting tablets in sys catalog: System catalog snapshot is corrupted or built using different build type: Cannot add a table 00004005000030008000000000004006 (ColocationId: 16390) to a colocation group for tablet 12a2ae6fcfb54fd68c28d3a3e042d42d: place is taken by a table 00004005000030008000000000004006
    @     0x7f310ff9cc1b  google::LogMessage::SendToLog()
    @     0x7f310ff9dcd8  google::LogMessage::Flush()
    @     0x7f310ff9e15f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f31137135ce  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7f3110246d7c  yb::ThreadPool::DispatchThread()
    @     0x7f311024221b  yb::Thread::SuperviseThread()
    @     0x7f310e5b1694  start_thread
    @     0x7f310dcee41d  __clone
```
Full logs accessible from within Yugabyte org: https://drive.google.com/file/d/11G4Re1GeeXSMg369zdcihU5_R4doSeVF/view?usp=sharing

**Comment by frozenspider** [comment] 2022-09-16 05:37
Fortunately, in both cases this is not an actual corruption, but rather an attempt to add a same table to the colocation group twice, so some minor bug in `TabletLoader::Visit`.
Would be great to understand exact conditions leading to this...

**Comment by def-** [comment] 2022-09-16 10:23
It seems perfectly reproducible with itest-system and https://phabricator.dev.yugabyte.com/D19079
The test creates a colocated database with some tables, backs it up, drops the tables, restores the backup and then runs an upgrade, which is when it FATALs.

**Comment by yifanguan** [comment] 2023-02-01 09:48
Direct reason is we have duplicate `TableId` in the field: `table_ids` of `SysTabletsEntryPB`.

**Comment by yifanguan** [comment] 2023-02-02 07:04
Found this extra information in master error log:
```
E0915 17:07:07.684747 31584 catalog_entity_info.cc:445] Two tablets with the same partition key start and split depth: committed_consensus_state { current_term: 1 leader_uuid: "63ccdbc35d104ac2b150060594e3c63c" config { opid_index: -1 peers { permanent_uuid: "63ccdbc35d104ac2b150060594e3c63c" member_type: VOTER last_known_private_addr { host: "10.9.209.79" port: 9100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2d" } } peers { permanent_uuid: "718ea49280ba49daaafc88abdd01a3c3" member_type: VOTER last_known_private_addr { host: "10.9.203.83" port: 9100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2c" } } peers { permanent_uuid: "9c9a57fc9ba04be19a31a50d967eaca3" member_type: VOTER last_known_private_addr { host: "10.9.132.45" port: 9100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2b" } } } } state: RUNNING state_msg: "Tablet reported with an active leader" table_id: "00004000000030008000000000000000.colocated.parent.uuid" partition { partition_key_start: "" partition_key_end: "" } table_ids: "00004000000030008000000000000000.colocated.parent.uuid" table_ids: "00004000000030008000000000004001" table_ids: "00004000000030008000000000004006" table_ids: "00004000000030008000000000004007" table_ids: "0000400000003000800000000000400c" table_ids: "0000400000003000800000000000400d" table_ids: "00004000000030008000000000004012" table_ids: "00004000000030008000000000004013" table_ids: "00004000000030008000000000004018" table_ids: "00004000000030008000000000004001" table_ids: "00004000000030008000000000004007" table_ids: "0000400000003000800000000000400d" table_ids: "00004000000030008000000000004013" table_ids: "00004000000030008000000000004043" table_ids: "00004000000030008000000000004044" table_ids: "00004000000030008000000000004045" table_ids: "00004000000030008000000000004046" colocated: true and 
```

 We have duplicate TableId in table_ids repeated field.

**Comment by yifanguan** [comment] 2023-02-04 04:30
TableId gets reused again. See two CreateTable Requests have the same TableId below.
```
I0706 03:22:28.831785 166908 catalog_manager.cc:3287] CreateTable from 127.0.0.1:43819:
name: "idx_tg0_0_c32_float4_c28_smallint_c19_float8_c1_bigint_c11_nume"
schema {
  columns {
    name: "c32_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_hash_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 0
    order: 1
    pg_type_oid: 700
  }
  columns {
    name: "c28_smallint"
    type {
      main: INT16
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 2
    pg_type_oid: 21
  }
  columns {
    name: "c19_float8"
    type {
      main: DOUBLE
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 3
    pg_type_oid: 701
  }
  columns {
    name: "c1_bigint"
    type {
      main: INT64
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 4
    pg_type_oid: 20
  }
  columns {
    name: "c11_numeric"
    type {
      main: DECIMAL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 5
    pg_type_oid: 1700
  }
  columns {
    name: "c35_int"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 6
    pg_type_oid: 23
  }
  columns {
    name: "c10_bigint"
    type {
      main: INT64
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 7
    pg_type_oid: 20
  }
  columns {
    name: "c9_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 8
    pg_type_oid: 25
  }
  columns {
    name: "c21_int"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 9
    pg_type_oid: 23
  }
  columns {
    name: "c23_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 10
    pg_type_oid: 25
  }
  columns {
    name: "c13_date"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 11
    pg_type_oid: 1082
  }
  columns {
    name: "c17_date"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 12
    pg_type_oid: 1082
  }
  columns {
    name: "c15_boolean"
    type {
      main: BOOL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 13
    pg_type_oid: 16
  }
  columns {
    name: "c4_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 14
    pg_type_oid: 700
  }
  columns {
    name: "c5_numeric"
    type {
      main: DECIMAL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 15
    pg_type_oid: 1700
  }
  columns {
    name: "c26_bigint"
    type {
      main: INT64
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 16
    pg_type_oid: 20
  }
  columns {
    name: "c16_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 17
    pg_type_oid: 25
  }
  columns {
    name: "c20_boolean"
    type {
      main: BOOL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 18
    pg_type_oid: 16
  }
  columns {
    name: "c34_int"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: 19
    pg_type_oid: 23
  }
  columns {
    name: "ybidxbasectid"
    type {
      main: BINARY
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: -101
    pg_type_oid: 0
  }
  table_properties {
    contain_counters: false
    is_transactional: true
    consistency_level: STRONG
    use_mangled_column_name: false
    is_ysql_catalog_table: false
    retain_delete_markers: false
    partition_key_version: 0
  }
  colocated_table_id {
  }
  pgschema_name: "public"
}
num_tablets: 3
partition_schema {
  hash_schema: PGSQL_HASH_SCHEMA
}
table_type: PGSQL_TABLE_TYPE
namespace {
  id: "0000809f000030008000000000000000"
  name: "db_lst_760151"
  database_type: YQL_DATABASE_PGSQL
}
indexed_table_id: "0000809f0000300080000000000080da"
is_local_index: false
is_unique_index: false
table_id: "0000809f0000300080000000000081d5"
index_info {
  indexed_table_id: "0000809f0000300080000000000080da"
}
is_colocated_via_database: false
skip_index_backfill: true
tablegroup_id: "0000809f0000300080000000000080c3"
transaction {
  transaction_id: "q\003k/W\007J\302\253\0011>\224XP\262"
  isolation: SNAPSHOT_ISOLATION
  status_tablet: "7e470575dca346d595185e692979f451"
  priority: 1356111783105764496
  start_hybrid_time: 6787390425860530176
  locality: GLOBAL
}
is_backfill_deferred: false
is_matview: false
```

and

```
I0706 03:25:43.807511 460214 catalog_manager.cc:3287] CreateTable from 127.0.0.3:47071:
name: "idx_tg0_2_c34_text_c1_float8_c0_text_c27_boolean_c21_boolean_c2"
schema {
  columns {
    name: "c34_text"
    type {
      main: STRING
    }
    is_key: true
    is_hash_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 0
    order: 1
    pg_type_oid: 25
  }
  columns {
    name: "c1_float8"
    type {
      main: DOUBLE
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 2
    pg_type_oid: 701
  }
  columns {
    name: "c0_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 3
    pg_type_oid: 25
  }
  columns {
    name: "c27_boolean"
    type {
      main: BOOL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 3
    order: 4
    pg_type_oid: 16
  }
  columns {
    name: "c21_boolean"
    type {
      main: BOOL
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 5
    pg_type_oid: 16
  }
  columns {
    name: "c24_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 6
    pg_type_oid: 700
  }
  columns {
    name: "c35_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 7
    pg_type_oid: 700
  }
  columns {
    name: "c10_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 8
    pg_type_oid: 25
  }
  columns {
    name: "c11_bigint"
    type {
      main: INT64
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: 9
    pg_type_oid: 20
  }
  columns {
    name: "c28_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 10
    pg_type_oid: 700
  }
  columns {
    name: "c14_float4"
    type {
      main: FLOAT
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 2
    order: 11
    pg_type_oid: 700
  }
  columns {
    name: "c7_text"
    type {
      main: STRING
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: 12
    pg_type_oid: 25
  }
  columns {
    name: "c37_int"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: 13
    pg_type_oid: 23
  }
  columns {
    name: "c4_bigint"
    type {
      main: INT64
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 14
    pg_type_oid: 20
  }
  columns {
    name: "c16_date"
    type {
      main: INT32
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 4
    order: 15
    pg_type_oid: 1082
  }
  columns {
    name: "ybidxbasectid"
    type {
      main: BINARY
    }
    is_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 1
    order: -101
    pg_type_oid: 0
  }
  table_properties {
    contain_counters: false
    is_transactional: true
    consistency_level: STRONG
    use_mangled_column_name: false
    is_ysql_catalog_table: false
    retain_delete_markers: false
    partition_key_version: 0
  }
  colocated_table_id {
  }
  pgschema_name: "public"
}
num_tablets: 3
partition_schema {
  hash_schema: PGSQL_HASH_SCHEMA
}
table_type: PGSQL_TABLE_TYPE
namespace {
  id: "0000809f000030008000000000000000"
  name: "db_lst_760151"
  database_type: YQL_DATABASE_PGSQL
}
indexed_table_id: "0000809f0000300080000000000080eb"
is_local_index: false
is_unique_index: false
table_id: "0000809f0000300080000000000081d5"
index_info {
  indexed_table_id: "0000809f0000300080000000000080eb"
}
is_colocated_via_database: false
skip_index_backfill: true
tablegroup_id: "0000809f0000300080000000000080c3"
transaction {
  transaction_id: "\326\221j3,\347IK\236\376\311}\265\272\231."
  isolation: SNAPSHOT_ISOLATION
  status_tablet: "0663c4b45d884eb69169808aae05a151"
  priority: 10890515240283483287
  start_hybrid_time: 6787391254726344704
  locality: GLOBAL
}
is_backfill_deferred: false
is_matview: false
```

**Comment by yifanguan** [comment] 2023-02-04 04:31
This issue indeed should be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/11129 as well.

**Comment by yifanguan** [comment] 2023-03-07 22:12
Close this issue because commit 98645ac6caac29b0fba4db2a3b5b0cb7c6726a2e solves this issue. It changes the way we persist the info of the set of tables hosted on a colocated tablet on master.

**Closed by yifanguan** 2023-03-07 22:12 UTC
Labels: kind/bug, area/ysql, priority/medium, qa_automation
