### ISSUE TITLE
[YSQL] TestPgWriteRestart::testWriteRestart test doesn't work

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#5852] opened 2020-09-28 13:09 UTC
Unit test fails
```
./yb_build.sh --java-test org.yb.pgsql.TestPgWriteRestart#testWriteRestart
```

Reason: Transaction can't be restarted in case more than one write operations are sent to `tserver` due to batching. As in this case first operation will be failed with
`Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): a6778034-0e89-4eb8-814d-416a418ec5f0 Conflicts with higher priority transaction: 3684c2b5-34f4-4eb2-ae5a-20b383f8ee2d (transaction error 3)`
and another with
`Operation failed. Try again. (yb/tablet/tablet.cc:1074): Transaction was recently aborted: a6778034-0e89-4eb8-814d-416a418ec5f0 (pgsql error 40001)`
Result of whole operation will be
`IO error: Errors occured while reaching out to the tablet servers: . Errors from tablet servers: [Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): a6778034-0e89-4eb8-814d-416a418ec5f0 Conflicts with higher priority transaction: 3684c2b5-34f4-4eb2-ae5a-20b383f8ee2d (transaction error 3), Operation failed. Try again. (yb/tablet/tablet.cc:1074): Transaction was recently aborted: a6778034-0e89-4eb8-814d-416a418ec5f0 (pgsql error 40001)]`

postgres layer failed to detect that this error can be retried.

**Comment by d-uspenskiy** [comment] 2020-09-28 13:42
Duplicate
https://github.com/yugabyte/yugabyte-db/issues/5760

**Comment by psudheer21** [comment] 2020-09-29 15:55
Duplicate of #5760

**Closed** 2020-09-29 15:55 UTC
Labels: kind/bug
