### ISSUE TITLE
YugabyteDB activity monitoring and audit log support

### ISSUE THREAD

**Issue by sanjimoh** [yugabyte/yugabyte-db#1331] opened 2019-05-08 16:08 UTC
Support audit logging (CONNECT, DCL events for example) with YugabyteDB. 

## Goals

The primary aim of this feature is to monitor and audit database activity in order to identify and report on fraudulent, illegal or other undesirable behavior. 

Note that the audit log and database activity data will be stored outside the database (in log files), in order to ensure that the log is immutable.

## Scope of what will be monitored

Below are the guidelines for what needs to be monitored:
* Monitoring privileged users: database users that have elevated privileges to access sensitive information within the database.
* Monitoring sensitive objects: Access to database objects (tables, views, etc.) including who accessed these objects, at what time, from what IP address, and the specific SQL statement that was used.
* Misc: Monitor all accesses into the DB including grant/revoke of Access, SQL errors, and failed logins.

To achieve the above, the monitored activities include SQL events such as Select, Insert, Update, Delete, Drop, Create, and Alter. The following data should be logged:
* Date/Timestamp
* User ID (OS User and DB User Name)
* Client and Server IP Address
* Server Type
* Source Program
* Activity/Error (e.g., SQL Statement)

### YSQL
It should be possible to achieve most of the above by using something like [pgAudit](https://github.com/pgaudit/pgaudit).

### YCQL
For YCQL, we should follow the format specified at: Audit Logging Cassandra. We could start with connections events, (LOGIN, ALTER ROLE, CREATE ROLE, GRANT, REVOKE ROLE, DROP ROLE, GRANT PERMISSION, REVOKE PERMISSION.

✅ YCQL audit logging #5887 (DONE).

## Additional features/integrations

In order to consume these, we would need a number of integrations.

⬜️ Splunk forwarder for audit logs #4422
⬜️ Integration with thirdparty tools for policy violation reporting

[![Analytics](https://yugabyte.appspot.com/UA-104956980-4/issues/1331/audit-logging-support?pixel&useReferer)](https://github.com/yugabyte/ga-beacon)

**Comment by kmuthukk** [comment] 2019-05-13 02:21
hi @sanjimoh - we currently do not have audit logging support, but it is on the roadmap.

Are you interested primarily in tracking all DDL operations (such as CREATE <tbl>, ALTER, DROP ... ) or also write operations (such as tracking every modificiation also - UPDATE/INSERT)

**Comment by sanjimoh** [comment] 2019-05-13 04:21
From a security point of view, CONNECT, DCL & DDL Queries would be my priorities.

**Comment by CH-JosephBironas** [comment] 2019-08-19 15:59
+1 to this, but also for ycql (assuming it doesn't already exist).

**Comment by ajcaldera1** [comment] 2020-04-22 19:39
For YCQL, we should follow the format specified at: [Audit Logging Cassandra](http://cassandra.apache.org/blog/2018/10/29/audit_logging_cassandra.html). We could start with connections events, (`LOGIN`, `ALTER ROLE`, `CREATE ROLE`, `GRANT`, `REVOKE ROLE`, `DROP ROLE`, `GRANT PERMISSION`, `REVOKE PERMISSION`.

**Comment by schoudhury** [comment] 2020-06-05 17:36
Status update - design and planning for this feature to start in early July 2020.

**Comment by frozenspider** [comment] 2020-09-25 22:01
YCQL audit was implemented in fdec43a0b4beed89c0e855c9a7dfbe67e45e832c, with the following limitations:
* Operations restarted internally are logged upon restart.
* Client-side only operations (`DESCRIBE`, `LIST`) are not logged.
* Login events are logged twice (probably caused by maintaining a control connection).

**Comment by m-iancu** [comment] 2020-09-30 19:37
Closing as this is done, any follow-up improvements will be tracked in separate issues.

**Comment by ramsrivatsa** [comment] 2020-10-22 19:03
Both YSQL([commit link](fb7ce2bd095280cadf2ce7a09ed4a57d569a1fb4)) and YCQL audit logging support is enabled.

**Closed by ramsrivatsa** 2020-10-22 19:03 UTC
Labels: area/ysql, community/request, kind/new-feature, roadmap-tracking-issue
