### ISSUE TITLE
[YSQL][Memory leak] Memory leak observed in PgLibPqTest_SecondaryIndexInsertSelect

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15194] opened 2022-12-01 11:14 UTC
Jira Link: [DB-4380](https://yugabyte.atlassian.net/browse/DB-4380)
### Description

Memory leak observed in PgLibPqTest_SecondaryIndexInsertSelect in the latest master build 2.17.1.0-b275

Logs - https://gist.github.com/kripasreenivasan/4a87f2794972f7cfe4e2fa21cd141d66

**Comment by def-** [comment] 2022-12-01 11:26
All the failures with "Can't read from symbolizer" are a duplicate of https://github.com/yugabyte/yugabyte-db/issues/14895

**Closed by def-** 2022-12-01 11:26 UTC
Labels: kind/bug, area/ysql, priority/medium
