### ISSUE TITLE
[YSQL] Regression in execution of nested correlated subqueries

### ISSUE THREAD

**Issue by lukaseder** [yugabyte/yugabyte-db#20316] opened 2023-12-14 16:42 UTC
Jira Link: [DB-9289](https://yugabyte.atlassian.net/browse/DB-9289)
### Description

Given this schema:

```sql
create table a (a int);
insert into a values (1),(2),(3),(4);

create table b (b int, a int);
insert into b values (1, 1),(2, 1),(3, 2),(4, 4);

create table c (c int);
insert into c values (1),(2),(3);

create table d (b int, c int);
insert into d values (1, 1),(1, 2),(1, 3),(2, 1),(3, 2),(3, 3);
```

Consider this query:

```sql
select
  a.a,
  (
    select json_agg(json_build_array(t.v0))
    from (
      select c.c as v0
      from c
      where c.c in (
        select d.c
        from d
          join b
            on b.b = d.b
        where b.a = a.a
      )
    ) as t
  )
from a
order by a.a;
```

In [PostgreSQL](https://dbfiddle.uk/26Rn5MeG) and [YugabyteDB 2.18](https://dbfiddle.uk/8EEXN1Ge), it produces:

```
|a  |json_agg       |
|---|---------------|
|1  |[[1], [2], [3]]|
|2  |[[2], [3]]     |
|3  |               |
|4  |               |
```

In YugabyteDB 2.19.3 (`PostgreSQL 11.2-YB-2.19.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 16.0.6 (https://github.com/yugabyte/llvm-project.git 1e6329f40e5c531c09ade7015278078682293ebd), 64-bit`), it no longer produces this result, but this, instead:

```
|a  |json_agg|
|---|--------|
|1  |        |
|2  |        |
|3  |        |
|4  |        |
```

It seems that some subquery cache is doing something wrong. If we restrict `a` on the outer query:

```sql
select
  a.a,
  (
    select json_agg(json_build_array(t.v0))
    from (
      select c.c as v0
      from c
      where c.c in (
        select d.c
        from d
          join b
            on b.b = d.b
        where b.a = a.a
      )
    ) as t
  )
from a
where a in (1, 2)
order by a.a;
```

Then we get this result, which is still wrong, but differently:

```
|a  |json_agg       |
|---|---------------|
|1  |[[3], [1], [2]]|
|2  |[[3], [1], [2]]|
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9289]: https://yugabyte.atlassian.net/browse/DB-9289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lukaseder** [comment] 2023-12-14 16:44
Note, this regression breaks quite a few jOOQ integration tests. It's safe to assume that jOOQ users using jOOQ with YugabyteDB will run into this as well, as this practice of correlating JSON aggregating subqueries is quite idiomatic with jOOQ's popular `MULTISET` operator:

- https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/multiset-value-constructor/

**Comment by lukaseder** [comment] 2023-12-14 17:02
The test case can be made simpler if we remove one level of nesting:

```sql
select
  a.a,
  (
    select json_agg(json_build_array(t.v0))
    from (
      select d.c v0
      from d
        join b
          on b.b = d.b
      where b.a = a.a
    ) as t
  )
from a 
-- where a in (1, 2)
order by a.a;
```

The problem still reproduces here

**Comment by ddorian** [comment] 2023-12-15 11:00
Hi @lukaseder 

Thanks for the report, I was able to reproduce it.

**Comment by sushantrmishra** [comment] 2023-12-21 20:40
This issue is duplicate of  https://github.com/yugabyte/yugabyte-db/issues/19694 and  https://github.com/yugabyte/yugabyte-db/issues/20297

**Comment by tanujnay112** [comment] 2023-12-21 21:25
Hi @lukaseder thanks for finding this regression and a really simple repro for it! I posted a workaround for this issue in #20297 while we get the fix out.

**Comment by lukaseder** [comment] 2023-12-22 09:56
Thanks, @sushantrmishra, @tanujnay112

**Comment by m-iancu** [comment] 2024-01-05 23:36
Fixed as part of https://github.com/yugabyte/yugabyte-db/issues/19694, dedicated test added in [b64b536](https://github.com/yugabyte/yugabyte-db/commit/b64b5365f3372bfafc7b824ef04b62ac456d52b0).

**Closed by m-iancu** 2024-01-05 23:36 UTC
Labels: kind/bug, area/ysql, priority/highest
