### ISSUE TITLE
[DocDB] Decreased performance in transactional contention workloads after enabling wait-on-conflict

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#21360] opened 2024-03-08 05:48 UTC
Jira Link: [DB-10257](https://yugabyte.atlassian.net/browse/DB-10257)
### Description

There are few benchmarks in [benchbase](https://github.com/yugabyte/benchbase) that has contention transactions in it. 
[AuctionMark](https://github.com/cmu-db/benchbase/wiki/AuctionMark)
[CH-benCHmark](https://github.com/cmu-db/benchbase/wiki/CH-benCHmark)
[SEATS](https://github.com/cmu-db/benchbase/wiki/Seats)
[SmallBank](https://github.com/cmu-db/benchbase/wiki/SmallBank)
[Voter](https://github.com/cmu-db/benchbase/wiki/Voter)

Here is Voter results for 2.21.1.0-b125
Default cluster (with enabled WoC and deadlock detection)
```
[INFO ] 2024-03-05 18:32:08,146 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 278.6 txn/sec
[INFO ] 2024-03-05 18:32:13,146 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 285.2 txn/sec
[INFO ] 2024-03-05 18:32:18,147 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 287.4 txn/sec
```
Disabled deadlock detection
```
[INFO ] 2024-03-06 17:04:28,509 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 304.4 txn/sec
[INFO ] 2024-03-06 17:04:33,509 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 292.2 txn/sec
[INFO ] 2024-03-06 17:04:38,509 [Thread-3] com.oltpbenchmark.ThreadBench run - Throughput: 303.6 txn/sec
```
With disabled WoC and deadlock detection
```
[INFO ] 2024-03-07 06:00:57,770 [Thread-3]  com.oltpbenchmark.ThreadBench run - Throughput: 311.2 txn/sec
[INFO ] 2024-03-07 06:01:02,771 [Thread-3]  com.oltpbenchmark.ThreadBench run - Throughput: 300.8 txn/sec
[INFO ] 2024-03-07 06:01:07,771 [Thread-3]  com.oltpbenchmark.ThreadBench run - Throughput: 311.0 txn/sec
```

AuctionMark
Default
```
[0;1mCompleted Transactions:[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.GetItem/01                   [14636] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.GetUserInfo/02               [ 3279]
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewBid/03                    [ 6405] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewComment/04                [  631] ***
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewCommentResponse/05        [  314] *
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewFeedback/06               [ 1314] *******
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem/07                   [ 2881] ***************
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase/08               [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.UpdateItem/09                [  991] *****
com.oltpbenchmark.benchmarks.auctionmark.procedures.ResetDatabase/1552978964     [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.LoadConfig/1624820151        [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.CloseAuctions/2061347276     [    0] 

[0;1mAborted Transactions:[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem/07                   [ 408] 

[0;1mRejected Transactions (Server Retry):[0;0m
<EMPTY>

[0;1mRejected Transactions (Retry Different):[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewCommentResponse/05        [   2] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase/08               [1664] 
```
Disabled WoC and deadlock detection
```
[0;1mCompleted Transactions:[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.GetItem/01                   [17875] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.GetUserInfo/02               [ 4030] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewBid/03                    [ 7848] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewComment/04                [  786] ***
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewCommentResponse/05        [  423] *
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewFeedback/06               [ 1593] *******
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem/07                   [ 3448] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase/08               [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.UpdateItem/09                [ 1170] *****
com.oltpbenchmark.benchmarks.auctionmark.procedures.ResetDatabase/1552978964     [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.LoadConfig/1624820151        [    0] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.CloseAuctions/2061347276     [    0] 

[0;1mAborted Transactions:[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewFeedback/06               [   1] 
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem/07                   [ 573] 

[0;1mRejected Transactions (Server Retry):[0;0m
<EMPTY>

[0;1mRejected Transactions (Retry Different):[0;0m
com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase/08               [2006] 
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10257]: https://yugabyte.atlassian.net/browse/DB-10257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment] 2024-03-11 16:09
let's investigate root cause and triage this further

**Comment by robertsami** [comment] 2024-04-19 17:07
the discrepancy in throughput is accounted for by the increased failure rate in the workload run against a cluster without wait on conflict enabled. when running these workloads, we observe slightly higher resource utilization in the workload without wait on conflict enabled. closing this issue as expected due to contention

**Closed by robertsami** 2024-04-19 17:07 UTC
Labels: kind/bug, area/docdb, priority/medium
