### ISSUE TITLE
[YSQL] Aggregates should not pushdown with index scans if recheck is required

### ISSUE THREAD

**Issue by andrei-mart** [yugabyte/yugabyte-db#18454] opened 2023-07-27 20:45 UTC
Jira Link: [DB-7432](https://yugabyte.atlassian.net/browse/DB-7432)
### Description

```
yugabyte=# CREATE TABLE test(h int, r text, vi int, vs text, PRIMARY KEY ((h, r) hash));
CREATE TABLE
yugabyte=# create index on test(vs);
CREATE INDEX
yugabyte=# insert into test values (1, 'foo', 1, 'foo');
INSERT 0 1
yugabyte=# select vs, yb_hash_code(vs) from test;
 vs  | yb_hash_code 
-----+--------------
 foo |        26462
(1 row)

yugabyte=# explain select vs from test where yb_hash_code(vs) = 26462;
                                  QUERY PLAN                                   
-------------------------------------------------------------------------------
 Index Only Scan using test_vs_idx on test  (cost=0.00..5.15 rows=10 width=32)
   Index Cond: (yb_hash_code(vs) = 26462)
(2 rows)

yugabyte=# select vs from test where yb_hash_code(vs) = 26462;
 vs  
-----
 foo
(1 row)

yugabyte=# explain select count(vs) from test where yb_hash_code(vs) = 26462;
                                     QUERY PLAN                                      
-------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=5.18..5.19 rows=1 width=8)
   ->  Index Only Scan using test_vs_idx on test  (cost=0.00..5.15 rows=10 width=32)
         Index Cond: (yb_hash_code(vs) = 26462)
         Partial Aggregate: true

yugabyte=# select count(vs) from test where yb_hash_code(vs) = 26462;
ERROR:  attribute 1 of type record has been dropped
```

The error happens because recheck of the `yb_hash_code(vs) = 26462` condition is attempted on the Postgres side.
It shouldn't push down the aggregate in the first place if recheck is required. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7432]: https://yugabyte.atlassian.net/browse/DB-7432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment] 2023-07-27 20:49
Looks like duplicate of issue #18296

**Closed by jasonyb** 2023-07-27 20:49 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
