### ISSUE TITLE
[xCluster] Integration with index backfill

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7613] opened 2021-03-11 23:09 UTC
Jira Link: [DB-1661](https://yugabyte.atlassian.net/browse/DB-1661)
Currently, when we do a CREATE INDEX it will trigger an index backfill operation. This has several implications on 2DC replication:
- to start replication, the user must specify the 2 tables to be linked, but those tables need to be created first
- the index table is created when the CREATE INDEX command is issued, but backfill will start immediately writing rows to the index table, which could not have yet had replication setup
- backfill also involves some metadata state transitions, both on the TS side, as well as the master side, which may or may not be relevant for 2DC replication

**Comment by nspiegelberg** [comment] 2022-07-29 22:40
#13488

**Comment by hari90** [comment] 2024-02-15 03:28
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/13488

**Closed** 2024-02-15 03:29 UTC
Labels: kind/enhancement, area/docdb, priority/medium
