### ISSUE TITLE
[YSQL] Allow mode in which errors are logged but allow the user to continue making progress

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1085] opened 2019-03-27 22:31 UTC
Since our YSQL offering is still in Beta, we should allow users to experiment with our API without stopping them at the very first step that does not work. We can explicitly log errors about the features that are not supported and warn the user upfront that they may experience certain types of issues or expectation mismatches, but fundamentally allow them to make progress.

This would be very helpful, for example, in trying out ORMs on top of YSQL, which might require features we're still actively working on..

cc @rkarthik007 @robertpang @mbautin

**Comment by m-iancu** [comment] 2019-04-15 21:32
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/1132 (already done).

**Closed by m-iancu** 2019-04-15 21:32 UTC
Labels: improve-ux, in progress, ysql
