### ISSUE TITLE
[YCQL] Server crashes on WHERE condition for key_column and collection_column

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#2638] opened 2019-10-17 19:00 UTC
In the following test case, we use LIST datatype to demonstrate, but the same issue also occurs when referencing column of type SET, MAP, TUPLE, or JSONB in the WHERE clause.

```
cqlsh:test> CREATE TABLE tab(h INT, r INT, v INT, j JSONB, l list<int>, PRIMARY KEY (h, r)) WITH TRANSACTIONS = { 'enabled' : true};
cqlsh:test> CREATE INDEX vidx ON tab(v);
# Crash - DEREF a collection in WHERE condition for INDEX AND LIST.
cqlsh:test> SELECT * FROM tab WHERE v = 1 AND l[1] = 1;
NoHostAvailable: 
cqlsh:test> 
```

**Comment by OlegLoginov** [comment] 2019-10-18 10:03
Reproduced locally.

**Comment by OlegLoginov** [comment] 2019-10-18 10:24
Stack:
```
F1018 13:06:17.066902 297381888 pt_expr.cc:611] Check failed: 'ref->desc()' Must be non NULL 
Fatal failure details written to /Users/oleg/yugabyte-data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.FATAL.details.2019-10-18T13_06_17.pid34842.txt
F20191018 13:06:17 ../../src/yb/yql/cql/ql/ptree/pt_expr.cc:611] Check failed: 'ref->desc()' Must be non NULL 
    @        0x1147b4500  google::LogDestination::LogToSinks()
    @        0x1147b350b  google::LogMessage::SendToLog()
    @        0x1147b3eb5  google::LogMessage::Flush()
    @        0x1147b89bf  google::LogMessageFatal::~LogMessageFatal()
    @        0x1147b4ea9  google::LogMessageFatal::~LogMessageFatal()
    @        0x1105f425f  google::CheckNotNull<>()
    @        0x1105f3cdd  yb::ql::PTRelationExpr::SetupSemStateForOp2()
    @        0x1103183d8  yb::ql::PTExpr2<>::Analyze()
    @        0x110316e43  yb::ql::PTExpr2<>::Analyze()
    @        0x1105d3999  yb::ql::PTDmlStmt::AnalyzeWhereExpr()
    @        0x1105d3747  yb::ql::PTDmlStmt::AnalyzeWhereClause()
    @        0x1105dcd82  yb::ql::PTSelectStmt::Analyze()
    @        0x1105dd9fe  yb::ql::PTSelectStmt::AnalyzeIndexes()
    @        0x1105dcdd1  yb::ql::PTSelectStmt::Analyze()
    @        0x11059ec81  yb::ql::ParseTree::Analyze()
    @        0x11014525c  yb::ql::Analyzer::Analyze()
    @        0x110103259  yb::ql::QLProcessor::Analyze()
    @        0x110103486  yb::ql::QLProcessor::Prepare()
    @        0x110105dca  yb::ql::QLProcessor::RunAsync()
    @        0x10f645d41  yb::cqlserver::CQLProcessor::ProcessRequest()
    @        0x10f644eca  yb::cqlserver::CQLProcessor::ProcessRequest()
    @        0x10f644889  yb::cqlserver::CQLProcessor::ProcessCall()
    @        0x10f66668d  yb::cqlserver::CQLServiceImpl::Handle()
    @        0x11342479c  yb::rpc::ServicePoolImpl::Handle()
    @        0x1133c99a6  yb::rpc::InboundCall::InboundCallTask::Run()
    @        0x1134322d0  yb::rpc::(anonymous namespace)::Worker::Execute()
    @        0x113f6de1e  yb::Thread::SuperviseThread()
    @     0x7fff763ed305  _pthread_body
    @     0x7fff763f026f  _pthread_start
    @     0x7fff763ec415  thread_start

```

**Comment by OlegLoginov** [comment] 2019-10-18 13:26
In the case the statement analysis selected Index to process the SELECT request:
`I1018 16:20:14.370586 185937920 pt_select.cc:488] Selected = Selectivity: index_id 948b810f6c7b44c0924b031218078938 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully false`

But in the index there is no column 'l', so the where_clause analysis failed.
The index should NOT be selected for the statement, because the index does not have enough data for the statement processing (no column 'l' in it).

**Comment by OlegLoginov** [comment] 2019-10-18 14:04
```
I1018 16:32:55.195273 209698816 pt_select.cc:478] Selectivity: index_id 948b810f6c7b44c0924b031218078938 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully false
I1018 16:32:55.195302 209698816 pt_select.cc:478] Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true

I1018 16:32:55.195324 209698816 pt_select.cc:488] Selected = Selectivity: index_id 948b810f6c7b44c0924b031218078938 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully false
```

**Comment by OlegLoginov** [comment] 2019-10-24 20:18
Fixed by the commit above.

**Closed by OlegLoginov** 2019-10-24 20:18 UTC
Labels: kind/bug
