### ISSUE TITLE
[YCQL] cqlsh: incorrect output of DESC <tbl> command if the table was deleted with a timeout.

### ISSUE THREAD

**Issue by verzlo** [yugabyte/yugabyte-db#2672] opened 2019-10-22 00:25 UTC
Observed misleading error when dropping Cassandra table(s) .

-- table exist:
-- drop table produce error:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. The object does not exist: table_name: "infocustomertobrokeragelink"
namespace {
  name: "cmstest"
}

drop table cmstest.infocustomertobrokeragelink;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 (ql error -301)"

-- AND table still showing that it existed:
-- BUT after relogin it looks like table is actually gone.

See example:

cassandra@cqlsh> desc cmstest.infocustomertobrokeragelink

CREATE TABLE cmstest.infocustomertobrokeragelink (
    brokerageid text PRIMARY KEY,
    custnum int
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'true'};
CREATE INDEX infocustomertobrokeragelink_custnum_idx ON cmstest.infocustomertobrokeragelink (custnum, brokerageid)
    WITH CLUSTERING ORDER BY (brokerageid ASC)
    AND transactions = {'enabled': 'true'};

cassandra@cqlsh> drop table cmstest.infocustomertobrokeragelink;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. The object does not exist: table_name: "infocustomertobrokeragelink"
namespace {
  name: "cmstest"
}

drop table cmstest.infocustomertobrokeragelink;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 (ql error -301)"
cassandra@cqlsh> desc cmstest.infocustomertobrokeragelink

CREATE TABLE cmstest.infocustomertobrokeragelink (
    brokerageid text PRIMARY KEY,
    custnum int
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'true'};
CREATE INDEX infocustomertobrokeragelink_custnum_idx ON cmstest.infocustomertobrokeragelink (custnum, brokerageid)
    WITH CLUSTERING ORDER BY (brokerageid ASC)
    AND transactions = {'enabled': 'true'};

cassandra@cqlsh> exit
[root@klxcasst4 scripts]# $YUGABYTE_HOME/bin/cqlsh klxcasst4 -u cassandra -p cassandra --request-timeout=3600
Connected to local cluster at klxcasst4:9042.
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> desc cmstest.infocustomertobrokeragelink

'infocustomertobrokeragelink' not found in keyspace 'cmstest'

**Comment by ndeodhar** [comment] 2019-10-24 17:06
@verzlo Before you got the `Object not found` error from `DROP TABLE`, had you previously already run `DROP TABLE` which maybe timed out?
I'm able to see this happen easily when the first request to drop table times out and then second request onward, we get a `not found` error (but `desc` still shows the table).

@OlegLoginov cqlsh client will cache table and keyspace information and `desc` uses that. Since `drop table` had a time out, that cache on client didn't get refreshed. We'll need to look into a mechanism for updating the cache in such scenarios.

**Comment by ndeodhar** [comment] 2019-10-24 17:08
@OlegLoginov To repro:
```
./bin/cqlsh -u cassandra -p cassandra --request-timeout=3

cassandra@cqlsh> CREATE TABLE cmstest.infocustomertobrokeragelink ( brokerageid text PRIMARY KEY, custnum int ) WITH default_time_to_live = 0 AND transactions = {'enabled': 'true'}; CREATE INDEX infocustomertobrokeragelink_custnum_idx ON cmstest.infocustomertobrokeragelink (custnum, brokerageid) WITH CLUSTERING ORDER BY (brokerageid ASC) AND transactions = {'enabled': 'true'};

cassandra@cqlsh> drop table cmstest.infocustomertobrokeragelink;
OperationTimedOut: errors={'127.0.0.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1
cassandra@cqlsh> desc cmstest.infocustomertobrokeragelink;

CREATE TABLE cmstest.infocustomertobrokeragelink (
    brokerageid text PRIMARY KEY,
    custnum int
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'true'};
CREATE INDEX infocustomertobrokeragelink_custnum_idx ON cmstest.infocustomertobrokeragelink (custnum, brokerageid)
    WITH transactions = {'enabled': 'true'};

cassandra@cqlsh:new_keyspace> drop table cmstest.infocustomertobrokeragelink;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Object Not Found. The object does not exist: table_name: "infocustomertobrokeragelink"
namespace {
  name: "cmstest"
}

drop table cmstest.infocustomertobrokeragelink;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 (ql error -301)"
```

**Comment by verzlo** [comment] 2019-10-24 18:03
> @verzlo Before you got the `Object not found` error from `DROP TABLE`, had you previously already run `DROP TABLE` which maybe timed out?
> I'm able to see this happen easily when the first request to drop table times out and then second request onward, we get a `not found` error (but `desc` still shows the table).
> 
> @OlegLoginov cqlsh client will cache table and keyspace information and `desc` uses that. Since `drop table` had a time out, that cache on client didn't get refreshed. We'll need to look into a mechanism for updating the cache in such scenarios.

No - I did not run the drop same table before .. I did not have evidence anymore - but I know that table existed prior to drop command. 

Also I can not simulate this  anymore as after I removed and recreated CDC replication - DDL delays are much smaller and regular timeouts do not capture this condition.

**Comment by OlegLoginov** [comment] 2019-11-07 13:36
The `cqlsh.py` tool uses `cassandra.cluster` object as a source of keyspaces/tables metadata.
So in the scenario: 
```
 1. DROP TABLE <tbl>   - should fail with a timeout
 2. DESC <tbl>
 3. DROP TABLE <tbl> - should return 'Object Not Found'
```
The step 2 is invalid - it works with old metadata which is not updated by the driver.

A fix should be implemented in the python driver:  https://github.com/yugabyte/cassandra-python-driver

**Comment by OlegLoginov** [comment] 2019-12-12 19:19
Unexpected 'Object Not Found' error issue:  https://github.com/yugabyte/yugabyte-db/issues/3133

Let's fix in this issue incorrect behavior of   DESC <tbl>  if the table was deleted with a Timeout. (Fix should be in the python driver code.)

**Comment by OlegLoginov** [comment] 2021-10-13 19:03
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/9683
Fix:   https://github.com/yugabyte/cqlsh/commit/4e0084836b50943de0725a7690a95ded8c36023e

**Closed by OlegLoginov** 2021-10-13 19:03 UTC
Labels: community/request, area/tools, python, area/ycql
