### ISSUE TITLE
[CDCSDK] Provide an option to add new tables for CDC after connector is started

### ISSUE THREAD

**Issue by cdavid** [yugabyte/yugabyte-db#13290] opened 2022-07-13 23:06 UTC
Jira Link: [DB-3218](https://yugabyte.atlassian.net/browse/DB-3218)
As a Developer, I want to be able to modify an existing CDC stream for my database and change which tables to include for tracking changes

**Comment by vrajat** [comment] 2022-07-14 04:00
CDCSDK Server can support adding new tables with a restart. The state is already stored in YugabyteDB. The server will get an API call for graceful shutdown. Also the shutdown time has been reduced. So the plan is to support a workflow where the config file is modified and the Server is restarted to pick up the new config.

**Comment by vaibhav-yb** [comment] 2022-08-17 07:34
Closing this as this is a duplicate of #10921.

**Closed by vaibhav-yb** 2022-08-17 07:34 UTC
Labels: kind/bug, priority/medium, area/cdcsdk
