### ISSUE TITLE
Raise ulimits to recommended values via setrlimit if possible

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#4121] opened 2020-03-31 18:10 UTC
A common blocker to running yugabyte is low ulimit values (especially developers trying it out on MacOS). The OS has both soft and hard ulimits. Soft ulimits can be raised by the user until the hard limit. We should attempt to raise the ulimit available to master/tserver by manually calling setrlimit with the recommended values specified in https://docs.yugabyte.com/latest/quick-start/install/macos/#prerequisites

For example, on my home ubuntu machine, the values for the open file ulimit are:
```
sanketh@matsya:~$ ulimit -n -H
1048576
sanketh@matsya:~$ ulimit -n
1024
sanketh@matsya:~$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
```
So a setrlimit up to 1048576 will be succesful.

**Comment by bmatican** [comment] 2020-07-06 20:42
Duplicate of #4943

**Closed by bmatican** 2020-07-06 20:42 UTC
Labels: area/docdb, good first issue, help wanted
