### ISSUE TITLE
[DocDB] 'Invalid value of enum consensus::OperationType ' FATAL is found in long running tests

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16986] opened 2023-04-24 03:08 UTC
Jira Link: [DB-6308](https://yugabyte.atlassian.net/browse/DB-6308)
### Description

In one of the long running tests with CDC, fatal is seen.
Yugabyte version: 2.18.0.0-b16

Find stress report in JIRA.

```
F20230423 08:41:43 ../../src/yb/tablet/tablet_peer.cc:1263] Invalid value of enum consensus::OperationType (full enum type: yb::consensus::OperationType, expression: replicate_msg->op_type()): 0.
    @     0x55d2c9ff7b07  google::LogMessage::SendToLog()
    @     0x55d2c9ff8a4d  google::LogMessage::Flush()
    @     0x55d2c9ff90c9  google::LogMessageFatal::~LogMessageFatal()
    @     0x55d2cb5df0b1  yb::FatalInvalidEnumValueInternal()
    @     0x55d2cb0b3c46  yb::tablet::TabletPeer::CreateOperation()
    @     0x55d2cb0b10d1  yb::tablet::TabletPeer::StartReplicaOperation()
    @     0x55d2ca49e5e8  yb::consensus::RaftConsensus::StartReplicaOperationUnlocked()
    @     0x55d2ca49944c  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x55d2ca47d58b  yb::consensus::RaftConsensus::Update()
    @     0x55d2cb2cfd7d  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x55d2ca4fb6ad  std::__1::__function::__func<>::operator()()
    @     0x55d2ca4fc26f  yb::consensus::ConsensusServiceIf::Handle()
    @     0x55d2caf9c0ea  yb::rpc::ServicePoolImpl::Handle()
    @     0x55d2caedbecf  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x55d2cafaac83  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x55d2cb66abb2  yb::Thread::SuperviseThread()
    @     0x7fdbb37ce694  start_thread
    @     0x7fdbb3cd041d  __clone

```

![Profile (6)](https://user-images.githubusercontent.com/109518123/233891411-78f58eac-2b76-4759-9211-d78b291822f1.png)

Gflags in testcase:

```
master_gflags={'enable_automatic_tablet_splitting': 'true',
                           'tablet_split_low_phase_size_threshold_bytes': 35001520, 
                           'tablet_split_limit_per_table': 149, 
                           'tablet_split_low_phase_shard_count_per_node': 134217728,
                           'ysql_num_shards_per_tserver': 1,
                           'yb_num_shards_per_tserver': 1,
                           'ysql_enable_packed_row': 'true',
                           'ycql_enable_packed_row': 'true',
                           'enable_stream_compression': 'true',
                           'stream_compression_algo': 1,
                           'ysql_enable_packed_row_for_colocated_table': 'true'},
            tserver_gflags={'enable_automatic_tablet_splitting': 'true',
                            'yb_num_shards_per_tserver': 1,
                            'ysql_num_shards_per_tserver': 1,
                            'ysql_enable_packed_row': 'true',
                            'ycql_enable_packed_row': 'true',
                            'enable_stream_compression': 'true',
                            'stream_compression_algo': 1,
                            'ysql_enable_packed_row_for_colocated_table': 'true',
                            'scheduled_full_compaction_jitter_factor_percentage': 100,
                            'scheduled_full_compaction_frequency_hours': 12,
                            'scheduled_full_compaction_check_interval_min': 5}
        )]),
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6308]: https://yugabyte.atlassian.net/browse/DB-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-04-25 23:30
@Huqicheng , This is another bug that has weird symptoms similar to https://github.com/yugabyte/yugabyte-db/issues/16986 cc @ttyusupov

**Comment by Huqicheng** [comment] 2023-04-26 15:21
This issue and #16985 both happened around the time network partition happened. And seeing many LMP errors.

**Comment by rthallamko3** [comment] 2023-04-26 17:28
Removing the 2.18.0_blocker label as the FATAL is a result of network partition caused by network nemesis in the test. The tserver recovers well after the FATAL.

**Comment by rthallamko3** [comment] 2024-02-27 19:46
This seems by design during nemesis runs. Closing it for now.

**Closed by rthallamko3** 2024-02-27 19:46 UTC
Labels: kind/bug, area/docdb, priority/medium, long_running_universe, qa_automation, qa_stress
