### ISSUE TITLE
Transactional DDL not supported

### ISSUE THREAD

**Issue by 78bits** [yugabyte/yugabyte-db#11526] opened 2022-02-18 06:10 UTC
Reproduce:
start transction;
create schema sometest;
rollback;
\dn 
(shows some test to still be there)

postgres behaves different here and reverts the create schema. The same limitatons apply to create table. This maes migrations in yugabyte unusable.

**Comment by ddorian** [comment] 2022-02-22 10:25
Hi @78bits 

This isn't yet supported. Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/1404. Please subscribe to that issue for updates.

**Closed by ddorian** 2022-02-22 10:25 UTC
