### ISSUE TITLE
[YSQL] ysql_dump fails with non-existing function yb_is_database_colocated

### ISSUE THREAD

**Issue by cberge908** [yugabyte/yugabyte-db#18646] opened 2023-08-10 13:54 UTC
Jira Link: [DB-7570](https://yugabyte.atlassian.net/browse/DB-7570)
### Description

Hi,

we're trying to backup a DB from yugabyte with the `ysql_dump` command.
When trying to do this, we're immediately getting an error message that a certain function does not exist:

```bash
[root@yb-tserver-0 bin]# ./ysql_dump --format=t --create --clean --blobs --if-exists --dbname=cloudquery --file=./db_backup_cloudquery.sql
ysql_dump: [archiver (db)] query failed: ERROR:  function yb_is_database_colocated(boolean) does not exist
LINE 1: SELECT yb_is_database_colocated(false), yb_is_database_coloc...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ysql_dump: [archiver (db)] query was: SELECT yb_is_database_colocated(false), yb_is_database_colocated(true)
```

We're using version 2.19:
```bash
[root@yb-tserver-0 bin]# ./ysqlsh --version
psql (PostgreSQL) 11.2-YB-2.19.0.0-b0
```

So far I have not found any further input for this. 
Not sure if this is a bug - I'm happy for every hint :)

Thanks in advance!

Cheers,
@cberge908

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7570]: https://yugabyte.atlassian.net/browse/DB-7570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tkoeppen** [comment] 2023-08-15 17:26
thanks for the quick reply.
On our affected database the upgrade_ysql procedure was missing.
No bug. User error.

```
sh-4.4# /home/yugabyte/bin/yb-admin -master_addresses yb-master-0,yb-master-1,yb-master-2 upgrade_ysql

...
I0815 17:20:03.071092    48 ysql_upgrade.cc:417] Minimum version is 35.1 which is latest
I0815 17:20:03.071260    48 tablet_service.cc:1748] YSQL upgrade done successfully
```

after migration finished (approx. 2 min) yb_is_database_colocated() was available again.

fixed it on our affected database upgrade.
we may consider including this in a custom ansible playbook procedure, that we do not forget this on future db version upgrades.

**Comment by cberge908** [comment] 2023-08-17 10:59
Thanks @yifanguan!
This actually solved the situation - did I miss anything in the documentation where it states to run this after an upgrade?

**Comment by ddorian** [comment] 2023-09-13 12:50
@cberge908 it's here: https://docs.yugabyte.com/preview/manage/upgrade-deployment/#upgrade-the-ysql-system-catalog

Closing as works as intended.

**Closed by ddorian** 2023-09-13 12:50 UTC
Labels: kind/enhancement, area/ysql, priority/medium, status/awaiting-triage
