### ISSUE TITLE
[YSQL] Row-level locking fails for colocated tables

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#15353] opened 2022-12-16 11:53 UTC
Jira Link: [DB-4488](https://yugabyte.atlassian.net/browse/DB-4488)
### Description

Ran the test `PgMiniTest.SnapshotInOperatorLock` on a colocated database.
Row-level locking doesn't work as expected for colocated tables.
Both legacy colocated database and new colocation (tablegroup) have the issue.

Cluster creation: 
```
./bin/yb-ctl destroy && ./bin/yb-ctl create --master_flags "ysql_legacy_colocated_database_creation=false" && ./bin/ysqlsh
```

Below is the repro for the issue:
Connection 1:
```
(step 1) CREATE DATABASE col WITH COLOCATION = true;
(step 2) \c col
(step 3) set yb_transaction_priority_lower_bound = 0.5;
(step 4) CREATE TABLE t (h INT, r1 INT, r2 INT, PRIMARY KEY(h, r1 ASC, r2 ASC));
(step 5) INSERT INTO t VALUES (1, 11, 1),(1, 12, 1),(1, 13, 1),(2, 11, 2),(2, 12, 2),(2, 13, 2);
(step 6) START TRANSACTION ISOLATION LEVEL REPEATABLE READ;
(step 7) SELECT * FROM t WHERE h = 1 AND r1 IN (11, 12) AND r2 = 1 FOR KEY SHARE;
```

Connection 2:
```
(step 8)   \c col
(step 9)   set yb_transaction_priority_upper_bound = 0.4;
(step 10)  START TRANSACTION ISOLATION LEVEL REPEATABLE READ;
(step 11)  DELETE FROM t WHERE h = 1 AND r1 = 11 AND r2 = 1; -- This line is expected to fail because the deleted row is locked in the transaction in connection 1.
```

**Comment by robertsami** [comment] 2023-01-17 19:21
this should be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/14569

**Closed by robertsami** 2023-01-17 19:21 UTC
Labels: kind/bug, area/ysql, priority/medium
