### ISSUE TITLE
[DocDB] Xcluster: SetupReplication fails if colocated table has index

### ISSUE THREAD

**Issue by skorobogatydmitry** [yugabyte/yugabyte-db#10951] opened 2021-12-28 19:26 UTC
Jira Link: [DB-1302](https://yugabyte.atlassian.net/browse/DB-1302)
### Description

```
yb-admin -certs_dir_name /home/yugabyte/yugabyte-tls-config -master_addresses IP1,IP2,IP3 setup_universe_replication $SOURCE_UNIVERSE_UUID  $SOURCE_UNIVERSE_MASTER_IPS $SOURCE_CLUSTER_TABLE_UUIDS;
```

SOURCE_CLUSTER_TABLE_UUIDS contains parent table UUID: `00004131000030008000000000000000.colocated.parent.uuid`, command works without this ID.

Command fails with the following error:
```
Error running setup_universe_replication: Illegal state (yb/master/catalog_manager_ent.cc:3074): Unable to setup replication from universe 0d323ded-dbef-49d7-84a7-9dcbc20075a7: Source and target table oids don't match for colocated table: Source: 000041310000300080000000000041a0, Target: 00004100000030008000000000004170, Source table oid: 16800, Target table oid: 16752
```

CREATE statement in the backup for 000041310000300080000000000041a0: `CREATE INDEX api_keys_pk ON public.api_keys USING lsm (some_id ASC, key ASC) WHERE ((upper(pop) IS NULL) AND (upper(pov) IS NULL));`.

Source database version is 2.6.6.0-b10, target - 2.8.0.0-b37.

**Comment by hulien22** [comment] 2021-12-28 19:33
The issue is actually with the backup / restore process for colocated dbs, where we are not creating the colocated indexes with the same oids - and hence we get the oid mismatch on the indexes during the xcluster setup

If the oids of the indexes are the same, then the xcluster setup should work. 

---

Workaround for now:
Drop the index on the sink then recreate it manually with:
```
set yb_enable_create_with_table_oid=1;
CREATE INDEX api_keys_pk ON public.api_keys USING lsm (some_id ASC, key ASC) WHERE ((upper(pop) IS NULL) AND (upper(pov) IS NULL)) with (table_oid = 16800);
```

**Comment by lingamsandeep** [comment] 2023-03-09 18:07
ColocationID matching on both the source and target of replication is a requirement for setting up XCluster. It is possible to do this for all create index options - implicit and explicit. Once the ColocationIDs match on both sides, replication can be setup by providing the parent table id as shown below - which automatically sets up replication for all tables in the colocation group.

e.g: Implicit index creation:

```
./bin/ysqlsh -h 127.0.0.1 -d car -c "create table colaa(a int, b int UNIQUE WITH (colocation_id=20001) ) with (colocation_id = 20000);"
./bin/ysqlsh -h 127.0.0.2 -d car -c "create table colaa(a int, b int UNIQUE WITH (colocation_id=20001)) with (colocation_id = 20000);"
yba -master_addresses 127.0.0.2 setup_universe_replication A1-B2 127.0.0.1 00004000000030008000000000004004.colocation.parent.uuid 
yba -master_addresses 127.0.0.1 setup_universe_replication B2-A1 127.0.0.2 00004000000030008000000000004004.colocation.parent.uuid
```

e.g. Explicit index creation: 
```
./bin/ysqlsh -h 127.0.0.1 -d car -c "create table colb(a int, b int) with (colocation_id = 30000);"
./bin/ysqlsh -h 127.0.0.2 -d car -c "create table colb(a int, b int) with (colocation_id = 30000);"
./bin/ysqlsh -h 127.0.0.1 -d car -c "create unique index indb on colb(b) with (colocation_id = 30001);"
./bin/ysqlsh -h 127.0.0.2 -d car -c "create unique index indb on colb(b) with (colocation_id = 30001);"

yba -master_addresses 127.0.0.2 setup_universe_replication A1-B2 127.0.0.1 00004000000030008000000000004004.colocation.parent.uuid 

yba -master_addresses 127.0.0.1 setup_universe_replication B2-A1 127.0.0.2 00004000000030008000000000004004.colocation.parent.uuid
```

**Comment by lingamsandeep** [comment] 2023-03-09 18:07
Closing this as this is not an issue.

**Closed by lingamsandeep** 2023-03-09 18:07 UTC
Labels: kind/bug, area/docdb, priority/medium
