### ISSUE TITLE
[YSQL] TSAN failure at "SysNamespaceEntryPB::has_transaction()" during initDb

### ISSUE THREAD

**Issue by SteveXiSong** [yugabyte/yugabyte-db#18292] opened 2023-07-18 20:02 UTC
Jira Link: [DB-7285](https://yugabyte.atlassian.net/browse/DB-7285)
### Description

TSAN failure logs in attachment.

Jenkins link: https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F165798%2Fartifact%2Fbuild%2Ftsan-clang15-dynamic-ninja%2Fyb-test-logs%2Ftests-pgwrapper__create_initial_sys_catalog_snapshot%2FCreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.log?class=CreateInitialSysCatalogSnapshotTest&name=CreateInitialSysCatalogSnapshot

[tsan fail at SysNamespaceEntryPB--has_transaction.txt](https://github.com/yugabyte/yugabyte-db/files/12088587/tsan.fail.at.SysNamespaceEntryPB--has_transaction.txt)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7285]: https://yugabyte.atlassian.net/browse/DB-7285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment] 2023-07-19 18:00
Duplicate of https://phorge.dev.yugabyte.com/D27095

**Closed by hari90** 2023-07-19 18:00 UTC
Labels: kind/enhancement, area/ysql, priority/medium, status/awaiting-triage
