### ISSUE TITLE
[DocDB] fix broken test XClusterSafeTimeTest.ConsumerHistoryCutoff

### ISSUE THREAD

**Issue by mdbridge** [yugabyte/yugabyte-db#24543] opened 2024-10-21 17:26 UTC
Jira Link: [DB-13577](https://yugabyte.atlassian.net/browse/DB-13577)
### Description

The following test is broken (often fails on trunk):
```
ybd tsan --cxx-test integration-tests_xcluster_safe_time-itest --gtest_filter XClusterSafeTimeTest.ConsumerHistoryCutoff --clang17
```

The failure is:
```
[C-m-3] W1020 23:32:54.555904  7591 master_heartbeat_service.cc:427] Could not get YSQL db catalog versions for heartbeat response: 
../../src/yb/integration-tests/xcluster/xcluster_safe_time-itest.cc:194: Failure
Expected equality of these values:
  safe_time
    Which is: { days: 20016 time: 23:32:54.141449 }
  ts_manager->AllowedHistoryCutoff( tablet->metadata()).primary_cutoff_ht
    Which is: { days: 20016 time: 23:32:53.099615 }
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-13577]: https://yugabyte.atlassian.net/browse/DB-13577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by spolitov** [comment] 2024-11-29 07:28
Duplicate of #22518

**Closed by spolitov** 2024-11-29 07:28 UTC
Labels: kind/bug, area/docdb, priority/medium
