### ISSUE TITLE
[SQLancer][YSQL] ASC Primary keys update operation may insert new value into a table if complex WHERE statement used

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11298] opened 2022-02-01 11:42 UTC
### Description

Reproducible in 2.11.2.0-b89
Originally issue was found in COLOCATED database, but ASC primary key is enough. **Couldn't simplify condition in WHERE because in this case issue is not reproducible.**

SQL scenario:
```
CREATE TABLE t2(c0 FLOAT, c1 FLOAT, PRIMARY KEY(c0 asc));
INSERT INTO t2(c0, c1) VALUES(0.32205635, 0.19828989);
select count(*) from t2; -- return 1 rows
UPDATE t2 SET c1 = 1, c0 = (0.3402957) WHERE (((((0.68992973136991209148760617608786560595035552978515625)::VARCHAR(354))||('195.136.159.127')))||(((CAST(B'1010000111100010011100011101101' AS INT))+(+ (419716608)))))!~((0.77233493)::MONEY)::VARCHAR;
select count(*) from t2; -- return 2 rows !!!
```

Output from JDBC tool:
```
yugabyte.public> CREATE TABLE t2(c0 FLOAT, c1 FLOAT, PRIMARY KEY(c0 asc))
[2022-02-01 14:42:09] completed in 301 ms
yugabyte.public> INSERT INTO t2(c0, c1) VALUES(0.32205635, 0.19828989)
[2022-02-01 14:42:09] 1 row affected in 29 ms
yugabyte.public> select * from t2
[2022-02-01 14:42:09] 1 row retrieved starting from 1 in 411 ms (execution: 18 ms, fetching: 393 ms)
yugabyte.public> UPDATE t2 SET c1 = 1, c0 = (0.3402957) WHERE (((((0.68992973136991209148760617608786560595035552978515625)::VARCHAR(354))||('195.136.159.127')))||(((CAST(B'1010000111100010011100011101101' AS INT))+(+ (419716608)))))!~((0.77233493)::MONEY)::VARCHAR
[2022-02-01 14:42:09] 1 row affected in 20 ms
yugabyte.public> select * from t2
[2022-02-01 14:42:09] 2 rows retrieved starting from 1 in 44 ms (execution: 8 ms, fetching: 36 ms)
```

**Comment by myang2021** [comment] 2022-02-10 18:33
Duplicate of #11346

**Closed** 2022-02-10 18:33 UTC
Labels: area/ysql
