### ISSUE TITLE
[CDCSDK] Split `CreateNewXReplStream` into xCluster and CDCSDK specific functions

### ISSUE THREAD

**Issue by dr0pdb** [yugabyte/yugabyte-db#20538] opened 2024-01-10 10:08 UTC
Jira Link: [DB-9549](https://yugabyte.atlassian.net/browse/DB-9549)
### Description

Split `CreateNewXReplStream` into `CreateNewXclusterStream` and `CreateNewCdcsdkStream` functions.

### Source connector version

NA

### Connector configuration

NA

### YugabyteDB version

NA

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9549]: https://yugabyte.atlassian.net/browse/DB-9549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment] 2024-04-03 02:56
Duplicate of #20536

**Closed** 2024-04-03 02:57 UTC
Labels: kind/enhancement, priority/medium, area/cdcsdk, xCluster
