### ISSUE TITLE
[YSQL] Analyze table does not work

### ISSUE THREAD

**Issue by dodilp** [yugabyte/yugabyte-db#1420] opened 2019-05-22 23:21 UTC
Similar to : https://www.postgresql.org/docs/9.1/sql-analyze.html

**Comment by m-iancu** [comment] 2022-03-14 01:53
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/8756 (now done).

**Closed by m-iancu** 2022-03-14 01:53 UTC
Labels: kind/enhancement, area/ysql, community/request
