### ISSUE TITLE
[DocDB] [Clone DB] Clone DB command(yb-admin) fails to clone DB

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#22763] opened 2024-06-06 18:48 UTC
Jira Link: [DB-11668](https://yugabyte.atlassian.net/browse/DB-11668)
### Description

Clone DB command(yb-admin) fails to clone DB

Version: **2.23.0.0-b435**

**Steps**:
1. Create Database(db1) and table
2. Create snapshot schedule on created database
3. Collect time(t1)
4. Load some data to table
5. Run clone namespace (yb-admin) command to clone database(db1) to database(db2)
6. List clones and it returns

```
[
    {
        "aggregate_state": "ABORTED",
        "source_namespace_id": "00004107000030008000000000000000",
        "seq_no": "1",
        "target_namespace_name": "d2",
        "restore_time": "2024-06-06 17:06:34.217744",
        "abort_message": "Runtime error (yb/util/subprocess.cc:634): Subprocess '/home/yugabyte/yb-software/yugabyte-2.23.0.0-b422-centos-x86_64/bin/../postgres/bin/ysql_dump' terminated with non-zero exit status 256"
    }
]
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11668]: https://yugabyte.atlassian.net/browse/DB-11668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SrivastavaAnubhav** [comment] 2024-06-13 18:57
Closing as duplicate of #22764

**Comment by SrivastavaAnubhav** [comment] 2024-06-13 18:57
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/22764

**Closed by SrivastavaAnubhav** 2024-06-13 18:57 UTC
Labels: kind/bug, priority/medium
