### ISSUE TITLE
[YSQL] New operation's hybrid time too low FATAL in tablet splitting case with large keys

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#14225] opened 2022-09-28 13:28 UTC
Jira Link: [DB-3685](https://yugabyte.atlassian.net/browse/DB-3685)
### Description

Hit this issue in latest master builds for a 2 times already.
Pretty hard to reproduce.

Scenario:
1. Started cluster with following flags:
```
"instance_type": "c5.2xlarge",
"master_gflags": {
    "tablet_split_low_phase_size_threshold_bytes": "2097152",
    "tablet_split_limit_per_table": "8172",
    "enable_automatic_tablet_splitting": "true",
    "tablet_split_low_phase_shard_count_per_node": "134217728",
    "ysql_num_shards_per_tserver": "1",
    "yb_num_shards_per_tserver": "1",
},
"tserver_gflags": {
    "enable_automatic_tablet_splitting": "true",
    "ysql_num_shards_per_tserver": "1",
    "yb_num_shards_per_tserver": "1",
}
```
2. Start SqlDataLoad sample apps workload
3. Evaluate nemesis in random order: tserver/master restarts, network slowdown and partition
4. Check that there is no FATAL in logs

```
F20220927 23:31:35 ../../src/yb/tablet/mvcc.cc:393] T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d: T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d: Recent 32 MVCC operations:
1. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
5. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321483683504 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
6. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
7. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321483890465 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
8. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
9. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
10. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
11. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
12. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
13. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
14. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321486909626 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
15. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321487077585 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
16. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
17. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
18. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
19. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
20. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
21. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
22. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321489965743 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
23. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321490111706 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
24. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
25. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
26. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
27. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
28. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
29. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
30. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321492984860 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
31. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
32. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321493632846 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
33. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
34. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
35. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
New operation's hybrid time too low: { physical: 1664321222064997 }, op id: 11.200361
  max_safe_time_returned_with_lease_={ safe_time: { physical: 1664321461809671 } source: kHybridTimeLease }
  !!! ht <= max_safe_time_returned_with_lease_.safe_time=1
  static_cast<int64_t>(ht.ToUint64() - max_safe_time_returned_with_lease_.safe_time.ToUint64())=-981994184704
  ht.PhysicalDiff(max_safe_time_returned_with_lease_.safe_time)=-239744674
  
  max_safe_time_returned_without_lease_={ safe_time: <min> source: kUnknown }
  ht <= max_safe_time_returned_without_lease_.safe_time=0
  static_cast<int64_t>(ht.ToUint64() - max_safe_time_returned_without_lease_.safe_time.ToUint64())=6817059725578227712
  ht.PhysicalDiff(max_safe_time_returned_without_lease_.safe_time)=1664321222064997
  
  max_safe_time_returned_for_follower_={ safe_time: { physical: 1664321221771262 } source: kPropagated }
  ht <= max_safe_time_returned_for_follower_.safe_time=0
  static_cast<int64_t>(ht.ToUint64() - max_safe_time_returned_for_follower_.safe_time.ToUint64())=1203138560
  ht.PhysicalDiff(max_safe_time_returned_for_follower_.safe_time)=293735
  
  last_replicated_={ physical: 1664321216908192 }
  ht <= last_replicated_=0
  static_cast<int64_t>(ht.ToUint64() - last_replicated_.ToUint64())=21122273280
  ht.PhysicalDiff(last_replicated_)=5156805
  
  last_ht_in_queue=<min>
  ht <= last_ht_in_queue=0
  static_cast<int64_t>(ht.ToUint64() - last_ht_in_queue.ToUint64())=6817059725578227712
  ht.PhysicalDiff(last_ht_in_queue)=1664321222064997
  
  propagated_safe_time_={ physical: 1664321221771262 }
  ht <= propagated_safe_time_=0
  static_cast<int64_t>(ht.ToUint64() - propagated_safe_time_.ToUint64())=1203138560
  ht.PhysicalDiff(propagated_safe_time_)=293735
  
  queue_.size()=0
  queue_=[]
    @          0x2a825f8  google::LogMessage::SendToLog()
    @          0x2a834b3  google::LogMessage::Flush()
    @          0x2a839af  google::LogMessageFatal::~LogMessageFatal()
    @          0x35a76bc  yb::tablet::MvccManager::AddPending()
    @          0x35aba0a  yb::tablet::MvccManager::AddFollowerPending()
    @          0x3638955  yb::tablet::TabletPeer::NewOperationDriver()
    @          0x36346db  yb::tablet::TabletPeer::StartReplicaOperation()
    @          0x2ea3ee1  yb::consensus::RaftConsensus::StartReplicaOperationUnlocked()
    @          0x2e9ebfc  yb::consensus::RaftConsensus::UpdateReplica()
    @          0x2e835d4  yb::consensus::RaftConsensus::Update()
    @          0x380281d  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @          0x2ef094b  std::__1::__function::__func<>::operator()()
    @          0x2ef1444  yb::consensus::ConsensusServiceIf::Handle()
    @          0x352163c  yb::rpc::ServicePoolImpl::Handle()
    @          0x3466ba3  yb::rpc::InboundCall::InboundCallTask::Run()
    @          0x35305b9  yb::rpc::(anonymous namespace)::Worker::Execute()
    @          0x3b38dd2  yb::Thread::SuperviseThread()
    @     0x7f87689cd694  start_thread
    @     0x7f8768ecf41d  __clone
```

**Comment by bmatican** [comment] 2022-10-11 22:35
@qvad can you confirm this was on a version that had the lease revocation flag off?

**Comment by qvad** [comment] 2022-10-12 09:16
@bmatican It occurred on 2.15.4.0-b29 version, how can we check default flag version on this build?

**Comment by bmatican** [comment] 2022-10-12 13:51
[#13611] DocDB: Disable enable_lease_revocation by default

Was in 2.14.4.0-b1 now, so it's indeed off.

**Comment by Huqicheng** [comment] 2022-10-12 21:12
For reference http://stress.dev.yugabyte.com/stress_test/9f0388ea-2fe1-4074-8fd3-ed47991a71ad

**Comment by Huqicheng** [comment] 2022-10-17 18:52
```
I0927 23:31:35.186293 21116 raft_consensus.cc:3384] T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d [term 13 FOLLOWER]: NO_OP [12.200361] replication failed: Aborted (yb/consensus/replica_state.cc:634): Operation aborted by new leader
...
New operation's hybrid time too low: { physical: 1664321222064997 }, op id: 11.200361
  max_safe_time_returned_with_lease_={ safe_time: { physical: 1664321461809671 } source: kHybridTimeLease }
```

Current term is 13, seems we should also reject 11.200361

**Comment by Huqicheng** [comment] 2022-10-19 03:14
```
TS-1      last committed op_id  11.200360
(Leader)TS-2 last committed op_id 11.200361
TS-3 last committed op_id 11.127389
11.127389. Preceding OpId from leader: 12.200361

TS-1 detect leader failure, and itself become leader after getting TS-3’s vote

(New leader)TS-1 last committed op_id 12.200361(NO_OP)
TS-2 last committed op_id 11.200361
TS-3 last committed op_id 11.127389 catching up TS-1

TS-2 start election again, and gets vote from TS-3

TS-1 last committed op_id 12.200361(NO_OP) <- 11.200361 ….. so 12.200361 is aborted, append 11.200361 to TS-1’s log
(Leader)TS-2 last committed op_id 11.200361
TS-3 last committed op_id 11.127389
```

`11.200361` is a write op having hybrid time `{ physical: 1664321222064997 }`
the sanity safe time lower bound is ` max_safe_time_returned_with_lease_={ safe_time: { physical: 1664321461809671 } source: kHybridTimeLease }`, should be calculated from ht lease.

And the ht lease has been reset to NoneValue due to abort of NO_OP 12.200361,
`[term 13 FOLLOWER]: Reset our ht lease: { physical: 1664321461809671 }`

Does it make sense to still use the ht lease as the safe time lower bound?

**Comment by Huqicheng** [comment] 2022-10-19 14:39
ht_lease can be set at update majority replicated

1664321461809671 is at Tuesday, September 27, 2022 11:31:01.809 PM

Looking for logs nearby:
```
W0927 23:31:01.387616 20254 replica_state.cc:793] T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d [term 12 LEADER]: Can't advance the committed index across term boundaries until operations from the current term are replicated. Last committed operation was: 11.200360, New majority replicated is: 11.196175, Current term is: 12
```

Seems we are getting such a big ht lease because of calling UpdateMajorityReplicdated with a wrong ht_lease_expiration

**Comment by bmatican** [comment] 2022-10-19 14:58
@Huqicheng could this be due to us having disabled the lease expiration mechanism? is this happening during leader changes/stepdowns? or just steady state?

**Comment by Huqicheng** [comment] 2022-10-19 15:04
@bmatican It's happening during leader changes.

**Comment by Huqicheng** [comment] 2022-10-19 21:29
```
F0927 23:31:35.272414 21116 mvcc.cc:393] T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d: T 7b8909519ae64772a5a5b880a7175157 P f4da37c3c25f44c7a52504461c87be5d: Recent 32 MVCC operations:
1. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
2. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321483683504 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
3. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
4. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321483890465 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
5. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
6. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
7. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
8. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
9. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
10. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
11. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321486909626 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
12. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321487077585 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
13. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
14. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
15. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
16. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
17. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
18. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
19. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321489965743 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
20. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321490111706 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
21. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
22. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
23. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
24. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
25. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
26. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
27. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321492984860 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
28. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
29. SafeTime { min_allowed: <min> deadline: 9223372036.855s ht_lease: { time: { physical: 1664321493632846 } lease: { physical: 1664321461809671 } } safe_time: { physical: 1664321461809671 } }
30. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
31. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
32. SafeTimeForFollower { min_allowed: <min> deadline: <uninitialized> safe_time_with_source: { safe_time: { physical: 1664321221771262 } source: kPropagated } }
```

**Comment by Huqicheng** [comment] 2022-10-21 16:08
I have reproduced the scenario with a small test

To summarize it:

1. old leader ts-1 has operations not majority replicated and crashed.
   ts-1 has 1.1(NoOp)  1.2 1.3 1.4           last committed 1.3 and last received 1.4
   ts-2 has 1.1(NoOp)  1.2 1.3                last committed 1.3 and last received 1.3
   ts-3 has  1.1(NoOp)                            last committed 1.1 and last received 1.1

2. ts-2 becomes the new leader and replicate 1.2 1.3 to ts-3, but before NO_OP replicated on ts-3, it serves a read,
    and advanced the safe time lower bound.

  ts-1 crashed
  ts-2 has 1.1(NoOp)  1.2 1.3  2.4(NoOp)   last committed 1.3 and last received 2.4
  ts-3 has 1.1(NoOp)  1.2 1.3                        last committed 1.3 and last received 1.3

3. ts-1 becomes the leader again and replicated its pending operation (1.4) with lower hybrid time to ts-2, ts-2 raise a fatal error

New operation's hybrid time too low: { physical: 1666367884528238 }, op id: 1.4

**Comment by bmatican** [comment] 2022-11-18 16:55
Closing, fixed by Jonathan's change above.

**Closed** 2023-01-03 17:31 UTC
Labels: kind/bug, area/docdb, priority/medium, 2.12 Backport Required, 2.14 Backport Required, 2.16 Backport Required
