### ISSUE TITLE
[YSQL] SPLIT Clause should not work with colocated tables CREATE STATEMENT

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#11540] opened 2022-02-19 00:18 UTC
### Description

It makes no sense to have a SPLIT clause in the CREATE statement of colocated tables.
Colocated tables put all of their data into a single tablet, called the colocation tablet, and they are not split into multiple tablets. Therefore, the SPLIT clause should not be allowed. It seems we currently ignore the SPLIT part of the CREATE statement for colocated tables.

SPLIT AT && SPLIT INTO examples:
```
CREATE DATABASE colocation_test colocated = true;
\c colocation_test

-- SPLIT AT
CREATE TABLE tbl_colocated_range (
  a INT,
  b TEXT,
  PRIMARY KEY(a ASC, b ASC)
) SPLIT AT VALUES((-100, 'bar'), (250, 'foo'));
DROP TABLE tbl_colocated_range;

-- SPLIT INTO
CREATE TABLE tbl_colocated_hash (
  a INT PRIMARY KEY,
  b TEXT
) SPLIT INTO 4 TABLETS;
DROP TABLE tbl_colocated_hash;

\c yugabyte
DROP DATABASE colocation_test;
```

**Comment by yifanguan** [comment] 2022-02-19 16:10
The expected behavior probably should be similar as TABLEGROUP.
```
CREATE TABLEGROUP tbl_group;

-- SPLIT AT
CREATE TABLE tbl_group_range (
  a INT,
  PRIMARY KEY(a ASC)
) SPLIT AT VALUES((-100), (250)) TABLEGROUP tbl_group;
ERROR:  Cannot use TABLEGROUP with SPLIT.

-- SPLIT INTO
CREATE TABLE tbl_group_hash (
  a INT PRIMARY KEY,
  b TEXT
) SPLIT INTO 4 TABLETS TABLEGROUP tbl_group;
ERROR:  Cannot use TABLEGROUP with SPLIT.

DROP TABLEGROUP tbl_group;
```

**Comment by frozenspider** [comment] 2022-04-20 17:38
Closing as a duplicate of #11980 since it has more info

**Closed by frozenspider** 2022-04-20 17:38 UTC
Labels: area/ysql
