### ISSUE TITLE
Master log spew: "tablet server has a pending delete"

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#882] opened 2019-02-20 18:38 UTC
E.g. from a test log:
```
141901 | [m-3L] | I | 515.861690 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141902 | [m-3L] | I | 515.861695 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141903 | [m-3L] | I | 515.861715 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141904 | [m-3L] | I | 515.861720 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141905 | [m-3L] | I | 515.861724 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141906 | [m-3L] | I | 515.861754 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141907 | [m-3L] | I | 515.861764 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141908 | [m-3L] | I | 515.861769 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141909 | [m-3L] | I | 515.861787 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141910 | [m-3L] | I | 515.861791 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141911 | [m-3L] | I | 515.861795 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141912 | [m-3L] | I | 515.861813 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141913 | [m-3L] | I | 515.861818 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141914 | [m-3L] | I | 515.861821 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141915 | [m-3L] | I | 515.861857 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141916 | [m-3L] | I | 515.861869 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141917 | [m-3L] | I | 515.861873 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141918 | [m-3L] | I | 515.861891 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141919 | [m-3L] | I | 515.861895 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141920 | [m-3L] | I | 515.861900 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141921 | [m-3L] | I | 515.861919 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141922 | [m-3L] | I | 515.861927 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141923 | [m-3L] | I | 515.861931 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141924 | [m-3L] | I | 515.861956 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141925 | [m-3L] | I | 515.861965 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141926 | [m-3L] | I | 515.861970 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
141927 | [m-3L] | I | 515.861992 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-3 has a pending delete
141928 | [m-3L] | I | 515.861999 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-1 has a pending delete
141929 | [m-3L] | I | 515.862002 | 18919 | cluster_balance_util.h:401 | tablet server PEER_TS-2 has a pending delete
```

**Comment by rahuldesirazu** [comment] 2019-05-23 00:51
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/1421, closing.

**Closed by rahuldesirazu** 2019-05-23 00:51 UTC
Labels: master
