### ISSUE TITLE
User frontier metadata is not recognized by the ldb tool

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3940] opened 2020-03-12 21:14 UTC
[libprotobuf WARNING google/protobuf/text_format.cc:1812] Proto type type.googleapis.com/yb.docdb.ConsensusFrontierPB not found
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0312 21:12:14.756052 17406 db_impl.cc:751] Shutdown done
Failed: Illegal state (yb/rocksdb/db/version_edit.cc:175): Boundary values contains user frontier but extractor is not specified: key: "G\225LS15bda468-9af2-4991-9250-4dd70b9bce48:900769261\000\000!!J\200#\200\001\263\231\356\250\3743~J\001?tc\005\000\000\004" seqno: 1125899997243655 user_values { tag: 1 data: "\200\001\263\231\356\333T\235\200J" } user_frontier { type_url: "type.googleapis.com/yb.docdb.ConsensusFrontierPB" value: "\n\007\010\t\020\373\230\306\025\021\000 \266\346\204@\nZ\031\376\377\377\377\377\377\377\377" }

**Comment by bmatican** [comment] 2020-06-24 06:38
Closing as duplicate of #4505

**Closed by bmatican** 2020-06-24 06:38 UTC
