### ISSUE TITLE
[YSQL][Driver] Implement LoadBalance in Golang(pgx) YSQL driver

### ISSUE THREAD

**Issue by kneeraj** [yugabyte/yugabyte-db#10918] opened 2021-12-21 06:50 UTC
Implement both

- Cluster aware load balancer which does uniform load distribution and
- Topology aware load balance

**Comment by ashetkar** [comment] 2021-12-22 04:40
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/10760

**Closed by ashetkar** 2021-12-22 04:40 UTC
Labels: area/ecosystem
