### ISSUE TITLE
[YSQL] Performance Issue - Loading data into RANGE partitioning table is noticeably slow.

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#9921] opened 2021-09-03 21:23 UTC
Jira Link: [DB-4787](https://yugabyte.atlassian.net/browse/DB-4787)
Test case.
Define a table using RANGE partition and loading data will run slower than its hash counterpart.

**Table Definition with Range Partitioning.**
It tooks 8 hours to load 13 GB of data.
```
CREATE TABLE test(id int, v int, PRIMARY KEY(id ASC)) SPLIT INTO 3 TABLETS;
```

**Table Definition with Hash Partitioning.**
```
CREATE TABLE test(id int PRIMARY KEY, v int) SPLIT INTO 3 TABLETS;
```

**All Indexes have the same definition.**
```
yugabyte=# CREATE INDEX test_idx1 ON test (v HASH);
yugabyte=# CREATE INDEX test_idx2 ON test (v ASC);
yugabyte=# CREATE INDEX test_idx3 ON test (v DESC);
yugabyte=# CREATE INDEX test_idx4 ON test (v);

\yugabyte=# \d test
                Table "public.test"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 id     | integer |           | not null | 
 v      | integer |           |          | 
Indexes:
    "test_pkey" PRIMARY KEY, lsm (id HASH)
    "test_idx1" lsm (v HASH)
    "test_idx2" lsm (v ASC)
    "test_idx3" lsm (v DESC)
    "test_idx4" lsm (v HASH)
```

**Comment by rthallamko3** [comment] 2023-03-03 16:11
Should be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/15362

**Closed by rthallamko3** 2023-03-03 16:11 UTC
Labels: kind/bug, area/docdb, priority/medium
