### ISSUE TITLE
[YSQL] INSERT On Conflict handling differs from postgres11

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#4274] opened 2020-04-22 20:00 UTC
Jira Link: [DB-4821](https://yugabyte.atlassian.net/browse/DB-4821)
`INSERT` with multiple values and `ON CONFLICT` is restricted in vanilla postgres 11 but allowed in YB

PGSQL 11
```
postgres=# create table test(k int primary key, v int);
CREATE TABLE
postgres=# insert into test values(1, 1), (2, 2), (1, 3) on conflict on constraint test_pkey do update set v = excluded.v;
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
postgres=# 
``` 

YB
```
yugabyte=# create table test(k int primary key, v int);
CREATE TABLE
yugabyte=# insert into test values(1, 1), (2, 2), (1, 3) on conflict on constraint test_pkey do update set v = excluded.v;
INSERT 0 3
```

[DB-4821]: https://yugabyte.atlassian.net/browse/DB-4821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment] 2024-08-06 22:32
marking as duplicate of more detailed #18895

**Closed by jasonyb** 2024-08-06 22:32 UTC
Labels: kind/bug, area/ysql, priority/medium
