### ISSUE TITLE
Set up xCluster replication for whole cluster or DB at once

### ISSUE THREAD

**Issue by ubendre** [yugabyte/yugabyte-db#12540] opened 2022-05-18 09:09 UTC
Jira Link: [DB-4617](https://yugabyte.atlassian.net/browse/DB-4617)
### Description

As of release 2.12, we are required to set up universe replication for each table separately when replicating from one universe to another. For several DBs and tables, this would be very tedious to manage. Many installations would have a 2DC, 3DC set up in production, where it could be hard to manage replications because of this limitation.

**Comment by lingamsandeep** [comment] 2023-06-20 18:34
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/10984

**Closed by lingamsandeep** 2023-06-20 18:34 UTC
Labels: kind/enhancement, area/docdb, priority/medium
