### ISSUE TITLE
[YSQL] In range partitioned tables, IndexScan(default) is about 4x-5x slower than SeqScan(query hint)

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#16148] opened 2023-02-17 09:15 UTC
Jira Link: [DB-5584](https://yugabyte.atlassian.net/browse/DB-5584)
### Description

This query is part of a transaction from auctionmark benchmark, from benchbase.
For this query, YB hash partitioned tables use SeqScan by default, but range partitioned tables used IndexScan. With range partitioned tables, the latencies were 10x higher than hash partitioned tables.
On range partitioned tables, when the query was with query hint for SeqScan(/YB SeqScan), the latencies dropped to 20%. So, the IndexScan latencies are 4x higher than SeqScan on range partitioned tables.

YB range partitioned tables:
Query plan using IndexScan (default)
```
yb_colocated=# explain (analyze,dist,costs off,verbose) SELECT MAX(ib_id) FROM item_bid WHERE ib_i_id = '000000000100000001390000000000' AND ib_u_id = '00000000010000000139';
                                                                                            QUERY PLAN                                                                                            
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Result (actual time=2164.065..2164.065 rows=1 loops=1)
   Output: $0
   InitPlan 1 (returns $0)
     ->  Limit (actual time=2164.060..2164.061 rows=1 loops=1)
           Output: item_bid.ib_id
           ->  Index Scan Backward using item_bid_pkey on public.item_bid (actual time=2164.058..2164.058 rows=1 loops=1)
                 Output: item_bid.ib_id
                 Index Cond: ((item_bid.ib_id IS NOT NULL) AND ((item_bid.ib_i_id)::text = '000000000100000001390000000000'::text) AND ((item_bid.ib_u_id)::text = '00000000010000000139'::text))
                 Storage Index Read Requests: 1
                 Storage Index Execution Time: 2163.965 ms
 Planning Time: 0.110 ms
 Execution Time: 2164.110 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 2163.965 ms
 Peak Memory Usage: 8 kB
(16 rows)

Time: 2165.059 ms (00:02.165)
```
Query plan using 'YB Seq Scan' (query hint)
```
yb_colocated=# explain (analyze,dist,costs off,verbose)/*+ SeqScan (item_bid) */SELECT MAX(ib_id) FROM item_bid WHERE ib_i_id = '000000000100000001390000000000' AND ib_u_id = '00000000010000000139';
                                                                         QUERY PLAN                                                                         
------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate (actual time=521.413..521.414 rows=1 loops=1)
   Output: max(ib_id)
   ->  YB Seq Scan on public.item_bid (actual time=521.396..521.404 rows=18 loops=1)
         Output: ib_id, ib_i_id, ib_u_id, ib_buyer_id, ib_bid, ib_max_bid, ib_created, ib_updated
         Remote Filter: (((item_bid.ib_i_id)::text = '000000000100000001390000000000'::text) AND ((item_bid.ib_u_id)::text = '00000000010000000139'::text))
 Planning Time: 0.165 ms
 Execution Time: 521.468 ms
 Storage Read Requests: 0
 Storage Write Requests: 0
 Storage Execution Time: 0.000 ms
 Peak Memory Usage: 31 kB
(11 rows)

Time: 522.424 ms
```
YB regular tables : 
Query plan using SeqScan(default):
```
yugabyte=# explain (analyze,dist,costs off,verbose) SELECT MAX(ib_id) FROM item_bid WHERE ib_i_id = '000000000100000001390000000000' AND ib_u_id = '00000000010000000139';
                                                                         QUERY PLAN                                                                         
------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate (actual time=180.685..180.685 rows=1 loops=1)
   Output: max(ib_id)
   ->  Seq Scan on public.item_bid (actual time=180.679..180.679 rows=0 loops=1)
         Output: ib_id, ib_i_id, ib_u_id, ib_buyer_id, ib_bid, ib_max_bid, ib_created, ib_updated
         Remote Filter: (((item_bid.ib_i_id)::text = '000000000100000001390000000000'::text) AND ((item_bid.ib_u_id)::text = '00000000010000000139'::text))
         Partial Aggregate: true
         Storage Table Read Requests: 1
         Storage Table Execution Time: 180.999 ms
 Planning Time: 0.117 ms
 Execution Time: 180.758 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 180.999 ms
 Peak Memory Usage: 30 kB
(14 rows)

Time: 181.699 ms
```
QueryPlan using IndexScan(query hint)
```
yugabyte=# explain (analyze,dist,costs off,verbose)/*+ IndexOnlyScan(item_bid item_bid_pkey) */SELECT MAX(ib_id) FROM item_bid WHERE ib_i_id = '000000002500000000120000000016' AND ib_u_id = '00000000250000000012';
                                                                       QUERY PLAN                                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate (actual time=941.732..941.733 rows=1 loops=1)
   Output: max(ib_id)
   ->  Index Scan using item_bid_pkey on public.item_bid (actual time=3.699..941.725 rows=1 loops=1)
         Output: ib_id, ib_i_id, ib_u_id, ib_buyer_id, ib_bid, ib_max_bid, ib_created, ib_updated
         Index Cond: (((item_bid.ib_i_id)::text = '000000002500000000120000000016'::text) AND ((item_bid.ib_u_id)::text = '00000000250000000012'::text))
         Storage Index Read Requests: 324
         Storage Index Execution Time: 800.996 ms
 Planning Time: 0.175 ms
 Execution Time: 944.879 ms
 Storage Read Requests: 324
 Storage Write Requests: 0
 Storage Execution Time: 800.996 ms
 Peak Memory Usage: 107000 kB
(13 rows)

Time: 945.900 ms
```
 

[DB-5584]: https://yugabyte.atlassian.net/browse/DB-5584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sonalsagarwal** [comment] 2023-02-22 10:50
Some easy steps to reproduce the bug : 
```
yugabyte=# create table t1 (id int , val int, primary key (id asc) );
yugabyte=# insert into t1 select a, a from generate_series(1,10000) a;
yugabyte=# create table t2 (id int , val int, primary key (id) );
yugabyte=# insert into t2 select a, a from generate_series(1,10000) a;
yugabyte=# explain analyze select id from t1 where val = 1 ;

yugabyte=#  explain (analyze, dist) /*+ SeqScan(t1) */select max(id) from t1 where val =1 ;
                                                 QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=105.00..105.01 rows=1 width=4) (actual time=24.740..24.740 rows=1 loops=1)
   ->  YB Seq Scan on t1  (cost=0.00..102.50 rows=1000 width=4) (actual time=24.731..24.733 rows=1 loops=1)
         Remote Filter: (val = 1)
 Planning Time: 0.198 ms
 Execution Time: 24.804 ms
 Storage Read Requests: 0
 Storage Write Requests: 0
 Storage Execution Time: 0.000 ms
 Peak Memory Usage: 30 kB
(9 rows)

Time: 25.547 ms
yugabyte=#  explain (analyze, dist) select max(id) from t1 where val =1 ;
                                                             QUERY PLAN                                                              
-------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=4.12..4.13 rows=1 width=4) (actual time=57.348..57.348 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.00..4.12 rows=1 width=4) (actual time=57.336..57.337 rows=1 loops=1)
           ->  Index Scan Backward using t1_pkey on t1  (cost=0.00..4.12 rows=1 width=4) (actual time=57.330..57.330 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Remote Filter: (val = 1)
                 Storage Index Read Requests: 1
                 Storage Index Execution Time: 57.224 ms
 Planning Time: 0.123 ms
 Execution Time: 57.421 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 57.224 ms
 Peak Memory Usage: 8 kB
(14 rows)

Time: 59.069 ms
```

**Comment by sonalsagarwal** [comment] 2023-02-22 12:58
Another issue observed here is that, with max() latencies shoot  upto 2.5x than querying the column.
```
create table t1 (id int , val int, primary key (id asc) );
insert into t1 select a, a from generate_series(1,10000) a;
```
```
yb_colocated=# explain (analyse,dist,verbose, costs off) select max(id) from t1 where val = 1 ;
                                                  QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
 Result (actual time=119.777..119.777 rows=1 loops=1)
   Output: $0
   InitPlan 1 (returns $0)
     ->  Limit (actual time=119.774..119.774 rows=1 loops=1)
           Output: t1.id
           ->  Index Scan Backward using t1_pkey on public.t1 (actual time=119.772..119.772 rows=1 loops=1)
                 Output: t1.id
                 Index Cond: (t1.id IS NOT NULL)
                 Remote Filter: (t1.val = 1)
                 Storage Index Read Requests: 1
                 Storage Index Execution Time: 118.999 ms
 Planning Time: 0.085 ms
 Execution Time: 119.813 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 118.999 ms
 Peak Memory Usage: 8 kB
(17 rows)

Time: 120.558 ms

yb_colocated=# explain (analyse,dist,verbose, costs off) select id from t1 where val = 1 ;
                            QUERY PLAN                             
-------------------------------------------------------------------
 Seq Scan on public.t1 (actual time=10.372..10.372 rows=1 loops=1)
   Output: id
   Remote Filter: (t1.val = 1)
   Storage Table Read Requests: 1
   Storage Table Execution Time: 10.000 ms
 Planning Time: 0.030 ms
 Execution Time: 10.402 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 10.000 ms
 Peak Memory Usage: 14 kB
(11 rows)

Time: 10.946 ms

```

**Comment by sushantrmishra** [comment] 2023-02-23 21:19
Seem like the issue is due to backward scan. Changing the query to execute min make it much faster for index scan scenario.

**Index scan:**

```
yugabyte=# explain (analyze, dist) select min(id) from t1 where val =1 ;                              [36/313]
                                                        QUERY PLAN

--------------------------------------------------------------------------------------------------------------
------------
 Result  (cost=4.12..4.12 rows=1 width=4) (actual time=0.325..0.325 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.00..4.12 rows=1 width=4) (actual time=0.322..0.323 rows=1 loops=1)
           ->  Index Scan using t1_pkey on t1  (cost=0.00..4.12 rows=1 width=4) (actual time=0.320..0.320 rows
=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Remote Filter: (val = 1)
                 Storage Index Read Requests: 1
                 Storage Index Execution Time: 1.000 ms
 Planning Time: 0.517 ms
 Execution Time: 0.363 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 1.000 ms
 Peak Memory Usage: 8 kB
(14 rows)
```

```
yugabyte=# explain (analyze, dist) select max(id) from t1 where val =1 ;
                                                             QUERY PLAN

--------------------------------------------------------------------------------------------------------------
-----------------------
 Result  (cost=4.12..4.13 rows=1 width=4) (actual time=29.381..29.381 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.00..4.12 rows=1 width=4) (actual time=29.376..29.377 rows=1 loops=1)
           ->  Index Scan Backward using t1_pkey on t1  (cost=0.00..4.12 rows=1 width=4) (actual time=29.374..
29.374 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Remote Filter: (val = 1)
                 Storage Index Read Requests: 1
                 Storage Index Execution Time: 29.000 ms
 Planning Time: 0.105 ms
 Execution Time: 29.435 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 29.000 ms
 Peak Memory Usage: 8 kB
(14 rows)
```

**YB SeqScan** 

```
yugabyte=# explain (analyze, dist) /*+ SeqScan(t1) */select min(id) from t1 where val =1 ;
                                                  QUERY PLAN
--------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=1050.00..1050.01 rows=1 width=4) (actual time=13.172..13.173 rows=1 loops=1)
   ->  YB Seq Scan on t1  (cost=0.00..1025.00 rows=10000 width=4) (actual time=13.165..13.166 rows=1 loops=1)
         Remote Filter: (val = 1)
 Planning Time: 0.162 ms
 Execution Time: 13.224 ms
 Storage Read Requests: 0
 Storage Write Requests: 0
 Storage Execution Time: 0.000 ms
 Peak Memory Usage: 30 kB
(9 rows)
```


```
yugabyte=# explain (analyze, dist) /*+ SeqScan(t1) */select max(id) from t1 where val =1 ;
                                                  QUERY PLAN
--------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=1050.00..1050.01 rows=1 width=4) (actual time=13.075..13.076 rows=1 loops=1)
   ->  YB Seq Scan on t1  (cost=0.00..1025.00 rows=10000 width=4) (actual time=13.067..13.068 rows=1 loops=1)
         Remote Filter: (val = 1)
 Planning Time: 0.165 ms
 Execution Time: 13.124 ms
 Storage Read Requests: 0
 Storage Write Requests: 0
 Storage Execution Time: 0.000 ms
 Peak Memory Usage: 30 kB
(9 rows)
```

**Comment by sushantrmishra** [comment] 2023-10-22 06:37
Backward scan improvement is tracked by https://github.com/yugabyte/yugabyte-db/issues/12609 , hence closing this issue.

**Closed by sushantrmishra** 2023-10-22 06:37 UTC
Labels: kind/bug, area/ysql, priority/medium
