### ISSUE TITLE
[YSQL] Meta command \dS+ dumps table with id 000033f50000300080000000000004ed does not exists

### ISSUE THREAD

**Issue by archit-rastogi** [yugabyte/yugabyte-db#20030] opened 2023-11-23 19:04 UTC
Jira Link: [DB-8995](https://yugabyte.atlassian.net/browse/DB-8995)
### Description

```
yugabyte=# create database yb1;
CREATE DATABASE

yugabyte=# \c yb1
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
You are now connected to database "yb1" as user "yugabyte"

yb1=# \dS+
NOTICE:  1 tablets of relation pg_aggregate did not provide disk size estimates, and were not added to the displayed totals.
NOTICE:  1 tablets of relation pg_am did not provide disk size estimates, and were not added to the displayed totals.
NOTICE:  1 tablets of relation pg_amop did not provide disk size estimates, and were not added to the displayed totals.
NOTICE:  1 tablets of relation pg_amproc did not provide disk size estimates, and were not added to the displayed totals.
NOTICE:  1 tablets of relation pg_attrdef did not provide disk size estimates, and were not added to the displayed totals.
NOTICE:  1 tablets of relation pg_attribute did not provide disk size estimates, and were not added to the displayed totals.
ERROR:  Table with id 000040000000300080000000000004ed does not exist
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8995]: https://yugabyte.atlassian.net/browse/DB-8995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment] 2024-08-06 21:18
Looks like a bug when trying to get table size for shared relations:
```
SELECT pg_catalog.pg_table_size(oid) FROM pg_class where relisshared = true;
ERROR:  Table with id 000033c3000030008000000000000470 does not exist
```
For non-shared system relations we don't get the right size yet (`pg_table_size` is only supported for non-colocated tables). So that limitation explains the `NOTICE`. But the ERROR for shared relations is unexpected and should be fixed. 
Most likely the issue is when constructing the UUID for the shared relations we should use the shared DB ID (template1) rather than the current DB id.

**Comment by m-iancu** [comment] 2024-08-06 21:25
It looks like in this code: https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/backend/utils/adt/dbsize.c#L410-L411
```
		HandleYBStatus(YBCPgGetTableDiskSize(YbGetRelfileNodeId(rel),
			MyDatabaseId, (int64_t *)&size, &num_missing_tablets));
```
we should have used `YBCGetDatabaseOid(Relation rel)` instead of  `MyDatabaseId`. The former checks if the relation is shared and adjusts the DatabaseId.

**Comment by OlegLoginov** [comment] 2024-08-09 19:59
Fixed.

**Closed** 2024-08-25 15:39 UTC
Labels: kind/bug, area/ysql, priority/medium, area/ecosystem, 2.20 Backport Required, 2024.1 Backport Required, 2024.1_blocker
