### ISSUE TITLE
[DocDB] Compilation error in release build using gcc9

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12317] opened 2022-04-29 16:10 UTC
### Description

https://gist.githubusercontent.com/mbautin/3cb045367323ca73fb567dc0a52a5461/raw

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
In file included from src/postgres/src/include/postgres.h:47,
                 from src/postgres/src/backend/tcop/postgres.c:20:
src/postgres/src/backend/tcop/postgres.c: In function ‘yb_exec_query_wrapper’:
src/postgres/src/include/utils/elog.h:301:15: error: ‘save_exception_stack’ is used uninitialized in this function [-Werror=uninitialized]
  301 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |               ^~~~~~~~~~~~~~~~~~~~
src/postgres/src/include/utils/elog.h:301:15: note: ‘save_exception_stack’ was declared here
  301 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |               ^~~~~~~~~~~~~~~~~~~~
src/postgres/src/backend/tcop/postgres.c:4555:3: note: in expansion of macro ‘PG_TRY’
 4555 |   PG_TRY();
      |   ^~~~~~
src/postgres/src/include/utils/elog.h:302:25: error: ‘save_context_stack’ is used uninitialized in this function [-Werror=uninitialized]
  302 |   ErrorContextCallback *save_context_stack = error_context_stack; \
      |                         ^~~~~~~~~~~~~~~~~~
src/postgres/src/include/utils/elog.h:302:25: note: ‘save_context_stack’ was declared here
  302 |   ErrorContextCallback *save_context_stack = error_context_stack; \
      |                         ^~~~~~~~~~~~~~~~~~
src/postgres/src/backend/tcop/postgres.c:4555:3: note: in expansion of macro ‘PG_TRY’
 4555 |   PG_TRY();
      |   ^~~~~~
cc1: all warnings being treated as errors

Input files:
  build/release-gcc9-dynamic-ninja/postgres_build/src/backend/tcop/postgres.c
Output file (from -o): postgres.o
```

**Comment by jasonyb** [comment] 2022-04-29 17:13
Duplicate of issue #11712.

**Closed by jasonyb** 2022-04-29 17:13 UTC
Labels: area/docdb, status/awaiting-triage
