### ISSUE TITLE
[YCQL] Table recreation does not clear prepared statements cache

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#1425] opened 2019-05-23 18:48 UTC
Jira Link: [DB-4697](https://yugabyte.atlassian.net/browse/DB-4697)
Reproduction steps:

1) Create a table:
```cql
CREATE TABLE t (pk int PRIMARY KEY, ctr counter);
```

2) Create a prepared statement (using Java for this example):
```java
// ...
PreparedStatement ps = session.prepare("UPDATE t SET ctr = ctr + 1 WHERE pk = ?");
session.execute(ps.bind(1)));
```

3) Drop and recreate the table with different type for `pk`:
```cql
DROP TABLE t;
CREATE TABLE t (pk uuid PRIMARY KEY, ctr counter);
```

4) Change your client accordingly:
```java
// ...
session.execute(ps.bind(UUID.fromString("139ca0c0-db08-4058-ba6b-37b086a636b6"))));
```

5) Try to run the client:
```
Exception in thread "main" com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [int <-> java.util.UUID]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:742)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:603)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:583)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:508)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:201)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:140)
	at com.yugabyte.CqlPlayground.main(CqlPlayground.java:48)
```

Note that adding e.g. a space in the CQL statement avoids this error.

**Comment by frozenspider** [comment] 2019-05-23 20:29
More details about the issue:
1. Affects `SELECT` statement as well
1. Does not depend on `counter`-type column
1. Does not depend specifically on deleting tables, `ALTER`ing it to drop/add column also works
1. Identified a possibly related issue #1427

**Comment by frozenspider** [comment] 2019-05-23 22:49
The problem:
Executing `session.prepare(...)` ends up in `yb::cqlserver::CQLServiceImpl::AllocatePreparedStatement`:
```cpp
shared_ptr<CQLStatement> CQLServiceImpl::AllocatePreparedStatement(
    const CQLMessage::QueryId& query_id, const string& keyspace, const string& query) {
```
(where `query_id` is essentially an MD5 made from keyspace and query strings.)
There a query is matched against prepared statements cache using said `query_id` - and a (stale) match is found and returned to the client.
Client later fails with client-side error when attempting to `.bind(...)` a correct type since the statement returned by the `tserver` has old types.
So the thing is, our prepared statements cache has no immediate idea about a table version - or that it has changed.

**Comment by OlegLoginov** [comment] 2023-01-17 08:38
Closing as a duplicate of the fixed issue: https://github.com/yugabyte/yugabyte-db/issues/10774

**Closed by OlegLoginov** 2023-01-17 08:38 UTC
Labels: kind/bug, priority/medium, area/ycql
