### ISSUE TITLE
Crash: pre-existing shared memory block is still in use

### ISSUE THREAD

**Issue by davidcorbin** [yugabyte/yugabyte-db#7331] opened 2021-02-21 19:24 UTC
Jira Link: [DB-1729](https://yugabyte.atlassian.net/browse/DB-1729)
Getting a strange crash message after a seemingly random amount of time <20 minutes after the cluster starts and is working correctly. 

Tserver log: 

```
...
I0221 19:01:52.288110   871 tablet_service.cc:2418] Leader stepdown request tablet_id: "57717bf0b69c449294e767ec9bd4405f" dest_uuid: "df96ba46661641b1893ce0555e1fc2f7" new_leader_uuid: "673e01e697934095a51d116009e4aa7d" success. Resp code=UNKNOWN_ERROR
I0221 19:01:52.289208   134 raft_consensus.cc:2245] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 4 FOLLOWER]: Pre-election. Granting vote for candidate 673e01e697934095a51d116009e4aa7d in term 5
I0221 19:01:52.309290   505 raft_consensus.cc:3229] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 4 FOLLOWER]: Advancing to term 5
I0221 19:01:52.312636   505 consensus_meta.cc:282] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7: Updating active role from FOLLOWER to FOLLOWER. Consensus state: current_term: 5 leader_uuid: "" config { opid_index: -1 peers { permanent_uuid: "df96ba46661641b1893ce0555e1fc2f7" member_type: VOTER last_known_private_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "f117777e33d7491fa04c917816a6a8ca" member_type: VOTER last_known_private_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "673e01e697934095a51d116009e4aa7d" member_type: VOTER last_known_private_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0221 19:01:52.312727   505 raft_consensus.cc:3168] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Snoozing failure detection for 3.229s
I0221 19:01:52.322957   505 raft_consensus.cc:2765] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]:  Leader election vote request: Granting yes vote for candidate 673e01e697934095a51d116009e4aa7d in term 5.
I0221 19:01:52.324167   180 raft_consensus.cc:1588] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Refusing update from remote peer 673e01e697934095a51d116009e4aa7d: Log matching property violated. Preceding OpId in replica: 4.323. Preceding OpId from leader: 5.324. (index mismatch)
I0221 19:01:52.324236   180 raft_consensus.cc:1818] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 4.323. Preceding OpId from leader: 5.324. (index mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1586 errors: "\000" } }
I0221 19:01:52.325193   647 consensus_meta.cc:282] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7: Updating active role from FOLLOWER to FOLLOWER. Consensus state: current_term: 5 leader_uuid: "673e01e697934095a51d116009e4aa7d" config { opid_index: -1 peers { permanent_uuid: "df96ba46661641b1893ce0555e1fc2f7" member_type: VOTER last_known_private_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "f117777e33d7491fa04c917816a6a8ca" member_type: VOTER last_known_private_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "673e01e697934095a51d116009e4aa7d" member_type: VOTER last_known_private_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0221 19:01:52.325237   647 raft_consensus.cc:3104] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Calling mark dirty synchronously for reason code NEW_LEADER_ELECTED
I0221 19:01:52.325256   647 replica_state.cc:1172] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Reset our lease: -1.722s
I0221 19:01:52.325279   647 replica_state.cc:1179] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Reset our ht lease: { physical: 1613934114045899 }
I0221 19:01:52.337033   165 raft_consensus.cc:3104] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: Calling mark dirty synchronously for reason code FOLLOWER_NO_OP_COMPLETE
I0221 19:01:52.337126   165 replica_state.cc:1408] T 57717bf0b69c449294e767ec9bd4405f P df96ba46661641b1893ce0555e1fc2f7 [term 5 FOLLOWER]: SetLeaderNoOpCommittedUnlocked(1), committed: { term: 4 index: 323 }, received: { term: 5 index: 324 }
I0221 19:01:53.290696   647 raft_consensus.cc:2245] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 7 FOLLOWER]: Pre-election. Granting vote for candidate 673e01e697934095a51d116009e4aa7d in term 8
I0221 19:01:53.304059   134 raft_consensus.cc:3229] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 7 FOLLOWER]: Advancing to term 8
I0221 19:01:53.307286   134 consensus_meta.cc:282] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7: Updating active role from FOLLOWER to FOLLOWER. Consensus state: current_term: 8 leader_uuid: "" config { opid_index: -1 peers { permanent_uuid: "f117777e33d7491fa04c917816a6a8ca" member_type: VOTER last_known_private_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "df96ba46661641b1893ce0555e1fc2f7" member_type: VOTER last_known_private_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "673e01e697934095a51d116009e4aa7d" member_type: VOTER last_known_private_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0221 19:01:53.307350   134 raft_consensus.cc:3168] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: Snoozing failure detection for 3.156s
I0221 19:01:53.317489   134 raft_consensus.cc:2765] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]:  Leader election vote request: Granting yes vote for candidate 673e01e697934095a51d116009e4aa7d in term 8.
I0221 19:01:53.318994   647 raft_consensus.cc:1588] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: Refusing update from remote peer 673e01e697934095a51d116009e4aa7d: Log matching property violated. Preceding OpId in replica: 7.245. Preceding OpId from leader: 8.246. (index mismatch)
I0221 19:01:53.319094   647 raft_consensus.cc:1818] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 7.245. Preceding OpId from leader: 8.246. (index mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1586 errors: "\000" } }
I0221 19:01:53.319983   182 consensus_meta.cc:282] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7: Updating active role from FOLLOWER to FOLLOWER. Consensus state: current_term: 8 leader_uuid: "673e01e697934095a51d116009e4aa7d" config { opid_index: -1 peers { permanent_uuid: "f117777e33d7491fa04c917816a6a8ca" member_type: VOTER last_known_private_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-1.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "df96ba46661641b1893ce0555e1fc2f7" member_type: VOTER last_known_private_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-0.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "673e01e697934095a51d116009e4aa7d" member_type: VOTER last_known_private_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } last_known_broadcast_addr { host: "yb-tserver-2.yb-tservers.yb.svc.cluster.local" port: 9100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }, has_pending_config = 0
I0221 19:01:53.320032   182 raft_consensus.cc:3104] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: Calling mark dirty synchronously for reason code NEW_LEADER_ELECTED
I0221 19:01:53.328137   165 raft_consensus.cc:3104] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: Calling mark dirty synchronously for reason code FOLLOWER_NO_OP_COMPLETE
I0221 19:01:53.328217   165 replica_state.cc:1408] T 3e636bbaf73e46a89c6b9d4067aeef36 P df96ba46661641b1893ce0555e1fc2f7 [term 8 FOLLOWER]: SetLeaderNoOpCommittedUnlocked(1), committed: { term: 7 index: 245 }, received: { term: 8 index: 246 }
I0221 19:02:47.322868    26 reactor.cc:450] TabletServer_R001: DEBUG: Closing idle connection: Connection (0x0000000008ac70f0) server 10.42.1.20:40605 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:47.323208    25 reactor.cc:450] TabletServer_R000: DEBUG: Closing idle connection: Connection (0x0000000008ac7c30) server 10.42.1.20:35309 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:49.323529    28 reactor.cc:450] TabletServer_R003: DEBUG: Closing idle connection: Connection (0x000000000908c910) server 10.42.1.20:52777 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:49.323639    28 reactor.cc:450] TabletServer_R003: DEBUG: Closing idle connection: Connection (0x000000000908c490) server 10.42.1.20:52687 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:51.323293    26 reactor.cc:450] TabletServer_R001: DEBUG: Closing idle connection: Connection (0x000000000908ceb0) server 10.42.1.20:37433 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:53.323632    26 reactor.cc:450] TabletServer_R001: DEBUG: Closing idle connection: Connection (0x000000000908c6d0) server 10.42.1.20:40139 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:55.323875    27 reactor.cc:450] TabletServer_R002: DEBUG: Closing idle connection: Connection (0x000000000908de70) server 10.42.1.20:36697 => 10.42.2.28:9100 - it has been idle for 65.0972s
I0221 19:02:57.322942    25 reactor.cc:450] TabletServer_R000: DEBUG: Closing idle connection: Connection (0x0000000009245690) server 10.42.1.20:47859 => 10.42.2.28:9100 - it has been idle for 65.0972s
W0221 19:09:08.628403    47 pg_wrapper.cc:602] PostgreSQL server exited with code 9
I0221 19:09:08.661248    47 pg_wrapper.cc:618] Restarting PostgreSQL server
I0221 19:09:08.741082    47 pg_wrapper.cc:361] PostgreSQL server running as pid 6238
2021-02-21 19:09:09.032 UTC [6238] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2021-02-21 19:09:09.033 UTC [6238] FATAL:  pre-existing shared memory block (key 5433001, ID 0) is still in use
2021-02-21 19:09:09.033 UTC [6238] HINT:  If you're sure there are no old server processes still running, remove the shared memory block or just delete the file "postmaster.pid".
W0221 19:09:09.037916    47 pg_wrapper.cc:602] PostgreSQL server exited with code 256
I0221 19:09:09.038053    47 pg_wrapper.cc:618] Restarting PostgreSQL server
I0221 19:09:09.051527    47 pg_wrapper.cc:361] PostgreSQL server running as pid 6239
2021-02-21 19:09:09.275 UTC [6239] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2021-02-21 19:09:09.275 UTC [6239] FATAL:  pre-existing shared memory block (key 5433001, ID 0) is still in use
2021-02-21 19:09:09.275 UTC [6239] HINT:  If you're sure there are no old server processes still running, remove the shared memory block or just delete the file "postmaster.pid".
W0221 19:09:09.278913    47 pg_wrapper.cc:602] PostgreSQL server exited with code 256
I0221 19:09:09.279036    47 pg_wrapper.cc:618] Restarting PostgreSQL server
I0221 19:09:09.293031    47 pg_wrapper.cc:361] PostgreSQL server running as pid 6240
2021-02-21 19:09:09.538 UTC [6240] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2021-02-21 19:09:09.538 UTC [6240] FATAL:  pre-existing shared memory block (key 5433001, ID 0) is still in use
2021-02-21 19:09:09.538 UTC [6240] HINT:  If you're sure there are no old server processes still running, remove the shared memory block or just delete the file "postmaster.pid".
W0221 19:09:09.542975    47 pg_wrapper.cc:602] PostgreSQL server exited with code 256
I0221 19:09:09.543081    47 pg_wrapper.cc:618] Restarting PostgreSQL server
...
```

The server says that it's restarting forever, although the pod isn't stopped and restarted.

Using the yugabyte official helm chart on kubernetes.

Yugabyte version 2.5.1.0
Kubernetes version: 1.20.2

**Comment by tedyu** [comment] 2021-02-22 04:20
While looking at related code, I found that YB code misses some in-use shared memory patches from upstream.
Such as #7333

**Comment by sushantrmishra** [comment] 2022-09-16 05:01
Duplicate of  https://github.com/yugabyte/yugabyte-db/issues/12784

**Closed by sushantrmishra** 2022-09-16 05:01 UTC
Labels: kind/bug, area/ysql, priority/medium
