### ISSUE TITLE
[DocDB] Compaction policies should take into account deletes in SST files and compact SSTs more frequently for TTL tables.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#13786] opened 2022-08-27 19:37 UTC
Jira Link: [DB-3305](https://yugabyte.atlassian.net/browse/DB-3305)
### Description

SST files that accumulate lots of deletes may not get compacted aggressively, leading to slow reads. The workaround for such customers is to schedule manual background compactions on that particular table (see KB - https://support.yugabyte.com/hc/en-us/articles/4407412055181-Read-queries-are-timing-out-after-large-deletes). However, we have seen a few customers impacted by this. Compaction policies can be tuned to take into account the following aspects - large number of deletes/slow reads/scans and schedule compactions more aggressively.  

Here are some notes from a customer that ran into this problem: Note it was on a CQL table., with TTL enabled 

1. Before compactions, the total size of SST files for one of the tablets was around 160MB. The reads on this partition took over 5 seconds.
2. Post compaction, the total size of SST files for the same tablet in (1) was around 80 MB. The reads post compaction finished in ms.

The user table table that ran into this issue is heavily used across all the apps in the system, Apparently the same table ran into scans taking longer than 5 seconds few months ago too.

Mitigation: We have recommended scheduling a fortnightly compaction on the affected table.

**Comment by jmeehan16** [comment] 2023-05-15 22:07
Closing this issue as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/15776, both of which are tackled by https://github.com/yugabyte/yugabyte-db/commit/e9c9f74dc46f631ce6fd291d7699739405e36046

**Comment by rthallamko3** [comment] 2023-05-16 00:47
reactivating till the backports are done.

**Comment by rthallamko3** [comment] 2023-05-31 18:50
Will consider the 2.14 and 2.16 backports if there is need.

**Comment by jmeehan16** [comment] 2023-05-31 21:40
If backported, https://github.com/yugabyte/yugabyte-db/commit/bc6682c0229447cfffc7bf8aa6c9d5deb7802ff2 and https://github.com/yugabyte/yugabyte-db/commit/bc6682c0229447cfffc7bf8aa6c9d5deb7802ff2 need to be included as well.
Closing this issue for now.

**Closed by jmeehan16** 2023-05-31 21:40 UTC
Labels: kind/enhancement, area/docdb, priority/medium, 2.18 Backport Required
