### ISSUE TITLE
[YSQL][LST] ERROR:  Timed out: Timed out waiting for Create Database

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13310] opened 2022-07-14 22:05 UTC
Jira Link: [DB-2945](https://yugabyte.atlassian.net/browse/DB-2945)
### Description

After running LST for a few hours, without any fatals or crashes, YugabyteDB sometimes becomes unable to create a new database:
```
yugabyte=# create database foo;
ERROR:  Timed out: Timed out waiting for Create Database
```
This happened after running this:
```
$ cd ~/code/yugabyte-db
$ git checkout 8e03ef6e3d752534d9ebd28e2c2ec3a7bd7109cf
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=yb_enable_read_committed_isolation=true,ysql_num_shards_per_tserver=1,enable_stream_compression=true,stream_compression_algo=1,yb_num_shards_per_tserver=1 --master_flags=yb_enable_read_committed_isolation=true,enable_stream_compression=true,stream_compression_algo=1,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=40,tablet_split_high_phase_shard_count_per_node=50
$ cd ~/code/yb-long-system-test
$ git checkout feb4d1abf2884e7435357b2a20a8cb42945dfd11
$ while true; do python3.9 ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=20 --runtime=10 --max-columns=200 --complexity=average; sleep 60; done
```
One run everything was fine, next run the database creation timed out. So I don't think the LST logs will help much: 
[lst.zip](https://github.com/yugabyte/yugabyte-db/files/9115851/lst.zip)
I'll provide the yugabyte-data directory, but it's 60 GB in size uncompressed, available from within Yugabyte oranization: https://drive.google.com/file/d/1xWL_H3yheK6mzQ4pzzz_DCH0H0mx3HyL/view?usp=sharing
Maybe create database just keeps being slower when you have many databases.

**Comment by myang2021** [comment] 2022-10-10 17:13
@def- `Maybe create database just keeps being slower when you have many databases.` Do you know how many databases this LST test creates? From the LST logs I only see two create database statements:

```
[myang@dev-server-myang tmp]$ grep -i "create database" lst_2022-07-14_20\:*/*.log
lst_2022-07-14_20:22:26_890086/schema.log:2022-07-14 20:22:28,987 MainThread CREATE DATABASE db_lst_890086;
lst_2022-07-14_20:37:05_517793/schema.log:2022-07-14 20:37:08,238 MainThread CREATE DATABASE db_lst_517793;
```

**Comment by def-** [comment] 2022-10-10 17:25
Yes, I believe this could be it. On clean runs LST drops the database, but on failure it doesn't. Is it expected that having multiple databases will slow the creation down so much?

**Comment by myang2021** [comment] 2022-10-10 18:17
@def- , having multiple databases will eventually slow down create database but it happens gradually. So if there are only a few databases, it shouldn't cause much slow down. I think this is more likely a dup of [(https://github.com/yugabyte/yugabyte-db/issues/14155)]. There was a regression in the default create database timeout. It should be 120 seconds but due to the regression it was changed to 60 seconds. Create database is a well-known slow DDL operation that also varies wildly. So this regression did not really affect other kinds of DDLs but it did affect create database.

The bug is now fixed by:

```
commit e2d5599f2a880f6dc396466d272079caf4de6aa6
Author: Minghui Yang <myang@yugabyte.com>
Date:   Fri Sep 30 17:26:43 2022 +0000

    [#14155] YSQL: Fix create database time out regression

```

Can you please rerun the test and see if it is now fixed? Thanks!

**Comment by def-** [comment] 2022-10-10 21:03
Currently LST is always running into https://github.com/yugabyte/yugabyte-db/issues/13128 and https://github.com/yugabyte/yugabyte-db/issues/14345, which is probably hiding most other issues.

**Comment by myang2021** [comment] 2022-10-10 21:06
Got it, let's wait for those two issues are resolved and come back for this. I'll keep an eye on those two tickets.

**Closed** 2023-04-26 23:14 UTC
Labels: kind/bug, area/ysql, priority/medium, qa_automation, LST_LRT
