### ISSUE TITLE
[SQLancer] [YSQL] Autocast to real doesn't work for asc PK in where clause 

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11090] opened 2022-01-14 15:53 UTC
### Description

Same scenario work in Postgres 11

Condition - colocated database, table with column as PK. Other types are not tested yet.
```
DROP TABLE t1;

CREATE TABLE t1(c0 REAL, c1 TEXT, PRIMARY KEY(c0 asc));
INSERT INTO t1(c0, c1) VALUES(0.4, 'SHOULD BE IN RESULT');
SELECT ALL t1.c1 FROM t1 WHERE ((0.6)>(t1.c0));
```

To fix that we need to explicitly casted 0.6 into real
`SELECT ALL t1.c1 FROM t1 WHERE ((0.6::real)>(t1.c0));;`

**Comment by qvad** [comment] 2022-01-14 15:57
For some reason I can't reproduce it in ysqlsh. Looks like it also required JDBC connection?

**Comment by qvad** [comment] 2022-01-14 17:22
Output from JDBC tool
![Screenshot 2022-01-14 at 19 31 35](https://user-images.githubusercontent.com/5963536/149557893-3e695d6b-de60-408d-8694-82afdd461ddd.png)

**Comment by qvad** [comment] 2022-01-14 17:52
Reproducer attached. Also it cannot be reproduced against Yugabyte database, so we need to create new one
[MainTest.java.zip](https://github.com/yugabyte/yugabyte-db/files/7872296/MainTest.java.zip)

**Comment by myang2021** [comment] 2022-01-14 23:58
This can be reproduced in ysqlsh, just follow the java steps literally.

From the docdb request:

`I0114 23:31:24.869602 15810 pg_session.cc:437] Applying operation: PGSQL_READ client: YQL_CLIENT_PGSQL stmt_id: 42713664 schema_version: 0 targets { column_id: 10 } targets { column_id: 11 } targets { column_id: -8 } column_refs { ids: 10 ids: 11 } is_forward_scan: true is_aggregate: false limit: 1024 return_paging_state: true ysql_catalog_version: 1 table_id: "00004000000030008000000000004006" condition_expr { condition { op: QL_OP_AND operands { condition { op: QL_OP_LESS_THAN_EQUAL operands { column_id: 10 } operands { value { float_value: **4.17232506e-08** } } } } } }

`
Note the float value isn't 0.6, it is a very small number 4.17232506e-08.

`1034                                            end[idx] = ybScan->key[i].sk_argument;
`
```
(gdb) p ybScan->key[i]
$2 = {
  sk_flags = 0,
  sk_attno = 1,
  sk_strategy = 1,
  sk_subtype = 701,
  sk_collation = 0,
  sk_func = {
    fn_addr = 0xa2cb7c <float48lt>,
    fn_oid = 301,
    fn_nargs = 2,
    fn_strict = true,
    fn_retset = false,
    fn_stats = 2 '\002',
    fn_extra = 0x0,
    fn_mcxt = 0x2598000,
    fn_expr = 0x0
  },
  sk_argument = 4603579539098121011
}
```

From the function float48lt, we can see that it is < (float4, float8), not < (float4, float4).

```
Datum
float48lt(PG_FUNCTION_ARGS)
{
    float4      arg1 = PG_GETARG_FLOAT4(0);
    float8      arg2 = PG_GETARG_FLOAT8(1);

    PG_RETURN_BOOL(float8_lt((float8) arg1, arg2));
}

```
This suggests that the argument 0.6 has type float8, not float4. But the Datum of 0.6 is simply reinterpreted as float4 because that's what the column type is. When bindig a float8 to a float4 column, we are not performing a type conversion from float8 to float4, instead we are just misinterpret those bits float8 as float4, hence we see wrong value in the request sent to docdb.

This only happens when the condition is pushed down to docdb. Otherwise, we'll just rely on PG code to do the comparison and it must correctly did the type conversion.

**Comment by myang2021** [comment] 2022-01-15 00:38
Making 0.6 float4 returns the right result:

```
db10001=# SELECT t1.c1 FROM t1 WHERE ((0.6)>(t1.c0));
SELECT t1.c1 FROM t1 WHERE ((0.6)>(t1.c0));
 c1 
----
(0 rows)

db10001=# SELECT t1.c1 FROM t1 WHERE ((0.6::float4)>(t1.c0));
SELECT t1.c1 FROM t1 WHERE ((0.6::float4)>(t1.c0));
         c1          
---------------------
 SHOULD BE IN RESULT
(1 row)

db10001=# 

```

**Comment by myang2021** [comment] 2022-01-15 01:13
The reason that when connecting to yugabyte DB the bug isn't reproducible is that yugabyte DB isn't colocated. By default non-colocated table the primary key will be a hash key. For a colocated table, by default the primary key is a asc range key. As a result, (0.6) > (t1.c0) cannot be pushdown to docdb for a hash key, but only for a range key. The bug happens during pushdown code path.

**Comment by kmuthukk** [comment] 2022-01-15 01:20
@myang2021 -- 

So in this case `CREATE DATABASE db10001 WITH colocated = true;` vs not is making the difference.

@qvad -- so perhaps an updated test case to use then is just vanilla (non-colocated database).. but show two examples.. one with PRIMARY KEY being HASH and another ASC?

**Comment by myang2021** [comment] 2022-01-15 01:45
That's right, hash vs range primary key with regular database can show the difference.

**Comment by andrei-mart** [comment] 2022-01-19 00:42
Have we identified the root cause?
It was observed that the scan key function is float48lt, which takes (float4, float8), and that seems perfectly correct to me, as t1.c0 is a float4 and 0.6 is a float8, and EXPLAIN confirms that:

```
yugabyte=# explain SELECT t1.c1 FROM t1 WHERE ((0.6)>(t1.c0));
                            QUERY PLAN                             
-------------------------------------------------------------------
 Index Scan using t1_pkey on t1  (cost=0.00..4.11 rows=1 width=32)
   Index Cond: ('0.6'::double precision > c0)
(2 rows)
```

Did we use c0's type to interpret the result of the '0.6'::double precision expression? If so, it should be trivial fix.

**Comment by myang2021** [comment] 2022-01-19 04:03
Yes, we are using c0's type to interpret 0.6, that's the root cause. I'll send a fix for this.

**Closed** 2022-02-07 17:44 UTC
Labels: area/ysql
