### ISSUE TITLE
[xCluster] Enable consumer-side transactional consistency via setup replication options

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#16757] opened 2023-04-07 05:38 UTC
Jira Link: [DB-6117](https://yugabyte.atlassian.net/browse/DB-6117)
### Description

Currently transactional consistency using apply_safe_time is enabled via a GFlag - xcluster_consistent_wal. Switch this to a parameter that is passed in using setup_replication.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6117]: https://yugabyte.atlassian.net/browse/DB-6117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment] 2023-05-09 13:39
Duplicate of #15036

**Closed** 2023-05-10 05:29 UTC
Labels: kind/bug, area/docdb, priority/medium
