### ISSUE TITLE
[DocDB][LST] FATAL: [LEADER]: Error reading the log while preparing peer request: Corruption (yb/consensus/log_util.cc:912): Failed to read ops 6..6: Failed to read LogEntry for index 6 from log segment 1 offset 1002: Could not read 48-byte log entry from

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13627] opened 2022-08-15 08:27 UTC
Jira Link: [DB-3195](https://yugabyte.atlassian.net/browse/DB-3195)
### Description

```
$ cd ~/code/yugabyte-db
$ git checkout ff45d27295811c9e0bf411345095a7f504aa9c9c
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=ysql_enable_packed_row=true,yb_enable_read_committed_isolation=true,ysql_num_shards_per_tserver=2,enable_stream_compression=true,stream_compression_algo=2,yb_num_shards_per_tserver=2 --master_flags=yb_enable_read_committed_isolation=true,enable_stream_compression=true,stream_compression_algo=2,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=1,tablet_split_high_phase_shard_count_per_node=5,ysql_enable_packed_row=true
$ cd ~/code/yb-long-system-test
$ git checkout 4124bba373813f00a78d9aae54171c7116016802
$ while true; do python3.9 ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --runtime=60 --max-columns=15 --complexity=full; sleep 10; done
[...]
2022-08-13 02:26:58,668 MainThread INFO     Reproduce with: git checkout 4124bba3 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --runtime=60 --max-columns=15 --complexity=full --seed=862549
2022-08-13 02:27:02,256 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (https://github.com/yugabyte/llvm-project.git 191e3a05a55c8671bcc88d7387c04c55a4310500), 64-bit
2022-08-13 02:27:02,260 MainThread INFO     Creating tables for database db_lst_862549
```
[lst.zip](https://github.com/yugabyte/yugabyte-db/files/9335999/lst.zip)

```
[dfelsing@dev-server-dfelsing ~]$ cat /nfusr/dev-server/dfelsing/yugabyte-data/node-2/disk-1/yb-data/tserver/logs/yb-tserver.FATAL.details.2022-08-13T02_27_51.pid1257714.txt
F20220813 02:27:51 ../../src/yb/consensus/consensus_queue.cc:694] T 8d72986244064886b93fe4607b35c506 P 770036242cef47b688ba7cafe6d3a1ae [LEADER]: Error reading the log while preparing peer request: Corruption (yb/consensus/log_util.cc:912): Failed to read ops 6..6: Failed to read LogEntry for index 6 from log segment 1 offset 1002: Could not read 48-byte log entry from offset 1014 in /nfusr/dev-server/dfelsing/yugabyte-data/node-2/disk-1/yb-data/tserver/wals/table-0000735c00003000800000000000738a/tablet-8d72986244064886b93fe4607b35c506/wal-000000001: log only readable up to offset 1002. Destination peer: 2eb84a71dcf0436dacd539c0da19b262
    @     0x7f31328ab6ab  google::LogMessage::SendToLog()
    @     0x7f31328ac0ce  google::LogMessage::Flush()
    @     0x7f31328ae85f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3135c204d1  yb::consensus::PeerMessageQueue::ReadFromLogCache()
    @     0x7f3135c1ed64  yb::consensus::PeerMessageQueue::RequestForPeer()
    @     0x7f3135c151c8  yb::consensus::Peer::SendNextRequest()
    @     0x7f3135c165df  yb::consensus::Peer::ProcessResponse()
    @     0x7f3132f3a8cc  yb::rpc::OutboundCall::InvokeCallbackSync()
    @     0x7f3132f8b510  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f3132ba1f87  yb::Thread::SuperviseThread()
    @     0x7f31311d5694  start_thread
    @     0x7f3130f1741d  __clone
```
I will add yugabyte-data directory, accessible from Yugabyte org: https://drive.google.com/file/d/1D3rifnLHwKi2Sb_l5PoXOl1hldFi5IgR/view?usp=sharing

**Comment by Huqicheng** [comment] 2022-08-17 16:55
`readable_to_offset_` is updated in `UpdateSegmentReadableOffset` when doing `Log::Sync`.

`UpdateIndexForBatch` is done in `Log::DoAppend` which happens earlier.

There is a gap between setting op index and update the readable offset, which seems cause the issue.

Setting up a unit test for verification.

**Comment by Huqicheng** [comment] 2022-08-17 18:16
Set up a test for reproducing same error.

```
TEST_F(LogTest, TestLogNotReadable) {
  BuildLog();

  FLAGS_TEST_pause_before_sync = true;

  // Append 1 replicate pair asynchronously with appender.
  AppendReplicateBatchToLog(1, AppendSync::kFalse);

  // Wait for log index is written.
  sleep(5);

  const auto log_index = CHECK_RESULT(log_->GetLogReader()->TEST_GetIndexEntry(1));
  ASSERT_EQ(log_index.op_id.index, 1);

  faststring tmp_buf;
  LogEntryBatchPB batch;
  Status s = log_->GetLogReader()->ReadBatchUsingIndexEntry(log_index, &tmp_buf,  &batch);
  LOG(INFO) << s;
  ASSERT_NOK(s);

  FLAGS_TEST_pause_before_sync = false;
}
```

```
I0817 18:13:30.002017 339791 log-test.cc:819] Corruption (yb/consensus/log_util.cc:912): Failed to read LogEntry for index 1 from log segment 1 offset 153: Could not read 176-byte log entry from offset 165 in /tmp/yb_test.tmp.24113.31049.26374.pid339728/log-test.LogTest.TestLogNotReadable.1660760004989037-339791/fs_root/yb-data/tserver_test/wals/table-test-log-table/tablet-test-log-tablet/wal-000000001: log only readable up to offset 153
```

**Comment by Huqicheng** [comment] 2022-08-21 03:34
The scenario described above might happen but not the real root cause because the LogCache should be expected to protect it with min_pinned_op_index_ and any index >= min_pinned_op_index_ shouldn't be evicted from the cache. But in this case, from the wal file, we get
```
13.5@6800808162097811456	REPLICATE NO_OP, SIZE: 26
	id { term: 13 index: 5 } hybrid_time: 6800808162097811456 op_type: NO_OP committed_op_id { term: 12 index: 4 } noop_request { }
19.6@6800809148036087808	REPLICATE NO_OP, SIZE: 26
	id { term: 19 index: 6 } hybrid_time: 6800809148036087808 op_type: NO_OP committed_op_id { term: 12 index: 4 } noop_request { }
22.5@6800810362737205248	REPLICATE NO_OP, SIZE: 26
	id { term: 22 index: 5 } hybrid_time: 6800810362737205248 op_type: NO_OP committed_op_id { term: 12 index: 4 } noop_request { }
24.6@6800825019105226752	REPLICATE NO_OP, SIZE: 26
	id { term: 24 index: 6 } hybrid_time: 6800825019105226752 op_type: NO_OP committed_op_id { term: 22 index: 5 } noop_request { }
```
we have 19.6 persisted so that min_pinned_op_index_ is already 7 so the cache entry could be evicted and read from disk which is not synced yet.

```
void LogCache::LogCallback(int64_t last_idx_in_batch,
                           const StatusCallback& user_callback,
                           const Status& log_status) {
  if (log_status.ok()) {
    std::lock_guard<simple_spinlock> l(lock_);
    if (min_pinned_op_index_ <= last_idx_in_batch) {
      VLOG_WITH_PREFIX_UNLOCKED(1) << "Updating pinned index to " << (last_idx_in_batch + 1);
      min_pinned_op_index_ = last_idx_in_batch + 1;
    }
  }
  user_callback.Run(log_status);
}
```
It's set in LogCallback when replicated it locally but will not set back if a lower index comes in when leader change happens.

Seems we should make it always up to date to make sure later logs with lower index will not be evicted before it's synced to disk.

**Comment by Huqicheng** [comment] 2022-09-02 01:26
Reopen the issue because of the race on min_pinned_op_index_ between`LogCallback` and `PrepareAppendOperations`

**Comment by Huqicheng** [comment] 2022-09-02 19:55
Opening #13855 to track the  `min_pinned_op_index_ ` related race condition. Close this one instead.

**Closed by Huqicheng** 2022-09-02 19:55 UTC
Labels: kind/bug, area/docdb, priority/high
