### ISSUE TITLE
[YSQL] Expose partition_hash / client-side read optimization

### ISSUE THREAD

**Issue by danielmh0** [yugabyte/yugabyte-db#3016] opened 2019-11-24 03:45 UTC
Jira Link: [DB-1533](https://yugabyte.atlassian.net/browse/DB-1533)
I'm looking for a way to do efficient batch reads from a SQL client. Queries like `SELECT COUNT(*)`, `SELECT` on non-indexed columns, etc. are currently quite slow.

Exposing something like YCQL's `partition_hash` is one way to solve this problem. Creating a hidden `shard_id` column could also work.

I understand the current system is optimized for querying indexes or primary keys (one shard at a time). However, batch reads have some exciting use cases: e.g. Apach Spark + JDBC with a `partitionColumn`.

**Comment by ddorian** [comment] 2019-12-02 13:31
This is duplicate of https://github.com/yugabyte/yugabyte-db/issues/2480
Please subscribe to that issue.

**Comment by tylarb** [comment] 2020-12-02 17:55
@m-iancu  should this be re-opened?

**Comment by m-iancu** [comment] 2020-12-02 17:58
Reopening this as #2480 is more general and includes the driver work. Will track the partition_hash specifically here and the follow-up driver work in #2480.

**Comment by sushantrmishra** [comment] 2022-09-15 02:51
We have added support for [yb_hash_code](https://docs.yugabyte.com/preview/api/ysql/exprs/func_yb_hash_code/ ) .  yb_has_code is tracked by https://github.com/yugabyte/yugabyte-db/issues/8718

**Closed by sushantrmishra** 2022-09-15 02:51 UTC
Labels: kind/bug, area/ysql, priority/medium, community/request
