### ISSUE TITLE
[YCQL] Disallow creating unique index with tablets on column(s) which has duplicate values.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#14598] opened 2022-10-21 15:25 UTC
Jira Link: [DB-3970](https://yugabyte.atlassian.net/browse/DB-3970)
### Description

If user tries to create unique or unique partial index with tablets on column(s) which has duplicate values it goes through and creates the index. And if user describes the table it will be present with table and if user lists the indexes from system_schema it won’t be there in the indexes list.  If user tries to delete the index it throws error saying `Object not Found`.
If user exits the current session and re-open the session and describes the table then the index won’t be there.
 
 **Steps**:
  1. Create table and insert some duplicate rows. 
  2. Create unique or unique partial index on columns which has duplicate values
   ex: `CREATE UNIQUE INDEX index1 ON test.multindex ((i, s5), s6, s1) INCLUDE (s2, s3, s4) WHERE s6 != '' AND s1 != '' AND i = 1` it throws error - Expected
3. If user creates unique or unique partial index on columns which has duplicate values with tablets clause it creates the index
`CREATE UNIQUE INDEX index1 ON test.multindex ((i, s5), s6, s1) INCLUDE (s2, s3, s4) WHERE s6 != '' AND s1 != '' AND i = 1 WITH tablets = 1`
4. List the system indexes and check the absence of created index
5. Try to delete the created index and observe the behaviour
6. Exit the session and re-login and describe the table and validate.

**Comment by tylarb** [comment] 2022-10-21 16:07
@Arjun-yb   this is a duplicate of this issue:
https://github.com/yugabyte/yugabyte-db/issues/14358

**Closed** 2022-10-21 16:26 UTC
Labels: kind/bug, priority/medium, area/ycql, status/awaiting-triage

**Comment by sumitdatabase** [comment] 2022-10-25 19:05
This is not an issue once [14424](https://github.com/yugabyte/yugabyte-db/issues/14424) is resolved now. The following is in 2.14.2.1 where this is fixed

```create table t1 ( c1 int primary key, c2 text, c3 text ) with transactions = {'enabled' : 'true' } ;
create unique index partial_uniq_c3 on t1 ( c3 ) where c2 = 'A' ;
insert into t1 (c1,c2,c3) values ( 1, 'A', 'a' );
insert into t1 (c1,c2,c3) values ( 2, 'B', 'b' );
insert into t1 (c1,c2,c3) values ( 3, 'A', 'a' );
InvalidRequest: Error from server: code=2200 [Invalid query] message="Execution Error. Duplicate value disallowed by unique index partial_uniq_c3
insert into t1 (c1,c2,c3) values ( 3, 'A', 'a' );
```

However there is an issue in the evaluation of the where clause of the partial index above. The clause "where c2 = 'A'" works as expected above. But if we change the definition of the where clause to do anything other than = sign, it fails

```
drop index partial_uniq_c3 ;
create unique index partial_uniq_c3 on t1 ( c3 ) where c1 > 1 ; --> index created even though we have dups where c1>1 below.
select * from t1;

 c1 | c2 | c3
----+----+----
  1 |  A |  a
  2 |  B |  b
  3 |  A |  b
```


This should be at least fixed in the doc, I have an doc [issue](https://github.com/yugabyte/yugabyte-db/issues/14600)  for that.
