### ISSUE TITLE
[YSQL] test starts failing PgLibPqTest.MultiBankAccountSerializable

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#10394] opened 2021-10-23 10:18 UTC
Jira Link: [DB-991](https://yugabyte.atlassian.net/browse/DB-991)
### Description

|  hash  |  passed/failed/ended with exception  |  pass percentage  |
|  ---------  |  -----------  |  --------  |
|  4d294901f  |  20/0/20  |  100%  |
|  6de6dda8d  |  20/0/20  |  100%  |
|  cee337341  |  12/8/20  |  60%   |

Hi @pkj415, looks like after your commit test starts failing sometimes

**Comment by def-** [comment] 2022-12-01 11:27
@kripasreenivasan All the failures with "Can't read from symbolizer" are a duplicate of https://github.com/yugabyte/yugabyte-db/issues/14895

**Comment by pkj415** [comment] 2024-10-24 20:50
Closing since the test is stable right now

**Closed by pkj415** 2024-10-24 20:50 UTC
Labels: kind/bug, area/ysql, kind/failing-test, priority/medium
