### ISSUE TITLE
[YSQL][randgen] EXPLAIN command fails with ERROR:  XX000: invalid attnum 4 for relation "ANY_subquery"

### ISSUE THREAD

**Issue by mtakahar** [yugabyte/yugabyte-db#21489] opened 2024-03-14 21:19 UTC
Jira Link: [DB-10374](https://yugabyte.atlassian.net/browse/DB-10374)
### Description

Problem
---
* Reproducible on a recent master (305dbefe92).

```
YB test# EXPLAIN  SELECT table1.col_datetime_key AS field1 FROM C  AS table1  JOIN C  AS table2  ON ( table2 .col_varchar_key  = table1 .col_varchar_key  )  WHERE table1 .col_int_key  IN (  SELECT col_int_key  FROM CC  AS SUBQUERY1_t1  WHERE  EXISTS (  SELECT  COUNT( 0  )  FROM CC  AS CHILD_SUBQUERY1_t1  JOIN C  AS CHILD_SUBQUERY1_t2  ON ( CHILD_SUBQUERY1_t2 .col_int_key  = CHILD_SUBQUERY1_t1 .col_int_key  )  JOIN D  AS CHILD_SUBQUERY1_t3  ON ( CHILD_SUBQUERY1_t3 .pk  = CHILD_SUBQUERY1_t2 .col_int_key  )  WHERE CHILD_SUBQUERY1_t3 .col_varchar_key  > SUBQUERY1_t1 .col_varchar_nokey  AND CHILD_SUBQUERY1_t3 .col_varchar_key  <> table2 .col_varchar_key  )  )  AND table1 .col_int_nokey  >=  ANY (  SELECT  7  )   ;
ERROR:  invalid attnum 4 for relation "ANY_subquery"
YB test# \errverbose
ERROR:  XX000: invalid attnum 4 for relation "ANY_subquery"
LOCATION:  get_variable, ruleutils.c:6901
YB test#
```

Test Case
---
```
CREATE TABLE c (
    pk integer NOT NULL,
    col_int_nokey integer,
    col_int_key integer,
    col_datetime_key timestamp without time zone,
    col_varchar_key character varying(1),
    CONSTRAINT c_pkey PRIMARY KEY(pk ASC)
);

CREATE TABLE cc (
    pk integer NOT NULL,
    col_int_key integer,
    col_varchar_nokey character varying(1),
    CONSTRAINT cc_pkey PRIMARY KEY(pk ASC)
);

CREATE TABLE d (
    pk integer NOT NULL,
    col_int_nokey integer,
    col_int_key integer,
    col_varchar_key character varying(1),
    col_varchar_nokey character varying(1),
    CONSTRAINT d_pkey PRIMARY KEY(pk ASC)
);

COPY c (pk, col_int_nokey, col_int_key, col_datetime_key, col_varchar_key) FROM stdin;
1	2	4	1900-01-01 00:00:00	v
2	150	62	1979-01-03 10:33:32.027981	v
3	\N	7	2027-11-28 00:50:27.051028	c
4	2	1	2003-10-09 19:53:04.008332	\N
5	5	0	2027-11-08 21:02:12.009395	x
6	3	7	1974-04-01 00:00:00	i
7	1	7	1900-01-01 00:00:00	e
8	4	1	1973-07-12 00:00:00	p
9	\N	7	2006-04-04 01:21:01.040391	s
10	2	1	1900-01-01 00:00:00	j
11	6	5	1984-03-05 03:41:18.061978	z
12	6	2	1989-08-03 11:33:04.049998	c
13	8	0	2010-04-28 21:44:45.050791	a
14	2	1	1972-04-06 00:00:00	q
15	6	8	2017-04-18 00:00:00	y
16	8	1	2009-12-18 19:39:55.005399	\N
17	3	1	2011-08-01 12:19:39.028493	r
18	3	9	1995-09-25 21:29:06.004058	v
19	9	1	2010-09-20 09:11:48.065041	\N
20	6	5	2020-03-27 09:32:04.056959	r
\.

COPY cc (pk, col_int_key, col_varchar_nokey) FROM stdin;
10	8	x
11	7	d
12	1	r
13	7	f
14	9	y
15	\N	u
16	1	m
17	9	\N
18	2	o
19	9	w
20	2	m
21	4	q
22	0	\N
23	4	d
24	8	g
25	\N	x
26	\N	f
27	0	p
28	\N	j
29	8	c
\.

COPY d (pk, col_int_nokey, col_int_key, col_varchar_key, col_varchar_nokey) FROM stdin;
1	8	4	c	c
2	3	5	c	c
3	3	8	q	q
4	\N	4	g	g
5	7	8	e	e
6	4	2	l	l
7	7	9	\N	\N
8	7	6	v	v
9	8	\N	c	c
10	6	\N	u	u
11	3	48	x	x
12	210	228	x	x
13	1	3	x	x
14	2	5	l	l
15	251	39	e	e
16	4	6	s	s
17	4	8	k	k
18	9	3	m	m
19	4	\N	x	x
20	\N	2	s	s
21	4	6	h	h
22	\N	3	u	u
23	1	1	x	x
24	6	4	l	l
25	2	3	p	p
26	\N	1	i	i
27	4	\N	u	u
28	248	97	i	i
29	4	0	i	i
30	8	0	e	e
31	4	9	h	h
32	5	5	f	f
33	9	9	\N	\N
34	2	0	p	p
35	4	2	n	n
36	211	172	h	h
37	2	\N	m	m
38	4	5	x	x
39	125	119	d	d
40	9	1	d	d
41	4	4	t	t
42	8	8	\N	\N
43	8	\N	\N	\N
44	\N	6	v	v
45	8	5	u	u
46	4	5	p	p
47	8	1	o	o
48	\N	7	v	v
49	1	2	m	m
50	3	8	x	x
51	5	9	n	n
52	8	\N	b	b
53	7	\N	\N	\N
54	2	3	r	r
55	\N	172	v	v
56	3	\N	a	a
57	\N	6	u	u
58	9	6	\N	\N
59	1	5	b	b
60	0	4	s	s
61	0	3	t	t
62	8	2	b	b
63	\N	7	m	m
64	9	4	v	v
65	1	6	n	n
66	9	0	j	j
67	7	8	\N	\N
68	2	5	\N	\N
69	1	8	h	h
70	9	2	k	k
71	5	9	k	k
72	4	7	\N	\N
73	6	5	n	n
74	5	7	e	e
75	2	0	s	s
76	4	4	w	w
77	0	3	y	y
78	3	1	z	z
79	0	0	b	b
80	6	6	f	f
81	1	2	s	s
82	9	\N	d	d
83	4	8	\N	\N
84	9	\N	d	d
85	4	\N	n	n
86	1	\N	i	i
87	2	3	\N	\N
88	8	7	h	h
89	1	3	d	d
90	0	5	c	c
91	2	5	i	i
92	0	1	t	t
93	1	2	g	g
94	2	1	q	q
95	\N	7	l	l
96	3	1	n	n
97	8	9	z	z
98	4	9	n	n
99	4	8	r	r
100	\N	3	p	p
\.

CREATE INDEX c_datetime_key ON c USING lsm (col_datetime_key ASC);
CREATE INDEX c_int_key ON c USING lsm (col_int_key ASC);
CREATE INDEX c_varchar_key ON c USING lsm (col_varchar_key ASC, col_int_key ASC);
CREATE INDEX cc_int_key ON cc USING lsm (col_int_key ASC);
CREATE INDEX d_int_key ON d USING lsm (col_int_key ASC);
CREATE INDEX d_varchar_key ON d USING lsm (col_varchar_key ASC, col_int_key ASC);


EXPLAIN  SELECT table1.col_datetime_key AS field1 FROM C  AS table1  JOIN C  AS table2  ON ( table2 .col_varchar_key  = table1 .col_varchar_key  )  WHERE table1 .col_int_key  IN (  SELECT col_int_key  FROM CC  AS SUBQUERY1_t1  WHERE  EXISTS (  SELECT  COUNT( 0  )  FROM CC  AS CHILD_SUBQUERY1_t1  JOIN C  AS CHILD_SUBQUERY1_t2  ON ( CHILD_SUBQUERY1_t2 .col_int_key  = CHILD_SUBQUERY1_t1 .col_int_key  )  JOIN D  AS CHILD_SUBQUERY1_t3  ON ( CHILD_SUBQUERY1_t3 .pk  = CHILD_SUBQUERY1_t2 .col_int_key  )  WHERE CHILD_SUBQUERY1_t3 .col_varchar_key  > SUBQUERY1_t1 .col_varchar_nokey  AND CHILD_SUBQUERY1_t3 .col_varchar_key  <> table2 .col_varchar_key  )  )  AND table1 .col_int_nokey  >=  ANY (  SELECT  7  )   ;
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10374]: https://yugabyte.atlassian.net/browse/DB-10374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment] 2024-08-26 21:03
```
yugabyte=# EXPLAIN (COSTS OFF) SELECT table1.col_datetime_key AS field1 FROM C  AS table1  JOIN C  AS table2  ON ( table2 .col_varchar_key  = table1 .col_varchar_key  )  WHERE table1 .col_int_key  I
N (  SELECT col_int_key  FROM CC  AS SUBQUERY1_t1  WHERE  EXISTS (  SELECT  COUNT( 0  )  FROM CC  AS CHILD_SUBQUERY1_t1  JOIN C  AS CHILD_SUBQUERY1_t2  ON ( CHILD_SUBQUERY1_t2 .col_int_key  = CHILD_
SUBQUERY1_t1 .col_int_key  )  JOIN D  AS CHILD_SUBQUERY1_t3  ON ( CHILD_SUBQUERY1_t3 .pk  = CHILD_SUBQUERY1_t2 .col_int_key  )  WHERE CHILD_SUBQUERY1_t3 .col_varchar_key  > SUBQUERY1_t1 .col_varchar
_nokey  AND CHILD_SUBQUERY1_t3 .col_varchar_key  <> table2 .col_varchar_key  )  )  AND table1 .col_int_nokey  >=  ANY (  SELECT  7  )   ;
                                                         QUERY PLAN                                                          
-----------------------------------------------------------------------------------------------------------------------------
 Merge Join
   Merge Cond: ((table1.col_varchar_key)::text = (table2.col_varchar_key)::text)
   Join Filter: (SubPlan 2)
   ->  Nested Loop Semi Join
         Join Filter: (table1.col_int_nokey >= (7))
         ->  Index Scan using c_varchar_key on c table1
         ->  Materialize
               ->  Result
   ->  Materialize
         ->  Index Scan using c_varchar_key on c table2
   SubPlan 2
     ->  Seq Scan on cc subquery1_t1
           Filter: (SubPlan 1)
           SubPlan 1
             ->  Aggregate
                   ->  Merge Join
                         Merge Cond: (child_subquery1_t1.col_int_key = child_subquery1_t2.col_int_key)
                         ->  Merge Join
                               Merge Cond: (child_subquery1_t1.col_int_key = child_subquery1_t3.pk)
                               ->  Index Scan using cc_int_key on cc child_subquery1_t1
                               ->  Sort
                                     Sort Key: child_subquery1_t3.pk
                                     ->  Index Scan using d_varchar_key on d child_subquery1_t3
                                           Index Cond: ((col_varchar_key)::text > (subquery1_t1.col_varchar_nokey)::text)
                                           Storage Index Filter: ((col_varchar_key)::text <> (table2.col_varchar_key)::text)
                         ->  Materialize
                               ->  Index Scan using c_int_key on c child_subquery1_t2
(27 rows)
```
Duplicate of #22533 
There's Index Scan with a Storage Index Filter in a subquery.

**Closed by andrei-mart** 2024-08-26 21:03 UTC
Labels: kind/bug, area/ysql, priority/medium
