### ISSUE TITLE
[YSQL] Incorrect unique constraint enforcement during whole-column update

### ISSUE THREAD

**Issue by srhickma** [YugaByte/yugabyte-db#1611] opened 2019-06-24 20:06 UTC
**Summary:** When a table is divided into multiple tablets (this does not happen with only one tablet per table), it is possible for a whole-column update on a non-indexed column to cause a unique constraint violation on a different column, when no violation exists.

**Test Case:**
```
CREATE TABLE test (
  pk int PRIMARY KEY,
  a int UNIQUE,
  b int
);
INSERT INTO test VALUES (1, 2, 2), (2, 3, 3);
UPDATE test SET b = 10;
```

**Actual Results:** The following error is returned after the `UPDATE` statement:
```
ERROR:  duplicate key value violates unique constraint "test_a_key"
```

**Expected Results:** No error.

**Note:** Updating each row individually (as in the SQL below) does not produce an error.
```
CREATE TABLE test (
  pk int PRIMARY KEY,
  a int UNIQUE,
  b int
);
INSERT INTO test VALUES (1, 2, 2), (2, 3, 3);
UPDATE test SET b = 10 WHERE pk = 1;
UPDATE test SET b = 10 WHERE pk = 2;
```
**Note:** If no primary key column is specified, this error will only occur occasionally, hinting that this issue could be related to the placement of rows in different tablets.

**Comment by m-iancu** [comment] 2019-07-30 21:55
Root cause seems to be that internally, the update does a `DELETE` followed by an `INSERT` on the same row in the index and the error is caused cause the `INSERT` does not see the delete.
Looks like a simpler repro (on `1.3`) is:
```
postgres=# create table test(a int primary key, b int);
CREATE TABLE
postgres=# begin transaction;
BEGIN
postgres=# insert into test values (1);
INSERT 0 1
postgres=# delete from test;
DELETE 1
postgres=# insert into test values (1);
ERROR:  duplicate key value violates unique constraint "test_pkey"
```

**Comment by nocaway** [comment] 2019-08-08 17:45
The commit https://github.com/YugaByte/yugabyte-db/commit/ca3ebdb6cf12b11af2c52d6ba8fd682c2a80ed5b fixed one issue of the bug.  The second issue in this bug must be also fixed.

(1) The issue that was fixed. Delete behaves correctly for the following case.
create table tab(i int primary key);
insert into tab values(1);
begin;
delete from tab;
end;

(2) The issue that was NOT fixed. Delete behaves incorrectly for the following case.
create table tab(i int primary key);
begin;
insert into tab values(1);
delete from tab;
end;

**Comment by nocaway** [comment] 2019-08-09 17:57
Issue number (2) that was mentioned earlier is now reported in bug #2011 

At a higher level the two aforementioned DELETE cases look similar, but underneath the surface, they are very different.
- Case (1) is a bug in proxy server for not setting the statement timestamp. This is fixed.
- Case (2) is a but in storage layer for not checking the write-time correctly. Move to issue 2011.

**Closed by nocaway** 2019-08-09 17:57 UTC
Labels: area/sql, kind/bug, priority/high
