### ISSUE TITLE
[platform] When deleting a Node in a universe the name of the node being deleted is missing from the dialogue box

### ISSUE THREAD

**Issue by fsayedyb** [yugabyte/yugabyte-db#8794] opened 2021-06-07 14:09 UTC
Description: When deleting a Node in a universe the name of the node being deleted is missing from the dialogue box

Infrastructure: All

Feature Request: requesting to add Node name/IP to dialogue box when deleting a node 
![NodeName](https://user-images.githubusercontent.com/51944662/121031479-47e8ca80-c7a2-11eb-8fb1-b980249c7433.png)

**Comment by fsayedyb** [comment] 2021-06-07 14:10
reference ticket 1389

**Comment by gaurav061** [comment] 2021-06-16 11:16
@kkg-yb @streddy-yb In the latest code I can see the node name while trying to delete it. Please have a look at the attached screenshot.

**When node is in ready state**
![Screenshot from 2021-06-16 12-32-35](https://user-images.githubusercontent.com/60691495/122209370-14085600-cec2-11eb-807f-dc657880419f.png)

**When node is in unreachable state**
![Screenshot from 2021-06-16 12-21-27](https://user-images.githubusercontent.com/60691495/122209440-271b2600-cec2-11eb-91ad-30ceab8446d2.png)

I believe this may be there in any old builds. Please confirm.

**Comment by kkg-yb** [comment] 2021-06-21 05:51
@fsayedyb  can you let us know which version this was seen on?

**Comment by kkg-yb** [comment] 2021-06-21 05:52
The issue was seen in 2.4.4 but looks like this is already fixed.

**Comment by gaurav061** [comment] 2021-06-21 08:52
Please check this diff which has addressed this issue `https://phabricator.dev.yugabyte.com/D4712 ` Closing this issue as it is not reproducible.

**Closed** 2021-06-21 08:52 UTC
Labels: area/platform, area/ui, team/platform-hi
