### ISSUE TITLE
fsync should always be called after appending records to a RocksDB manifest file

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#816] opened 2019-01-29 23:30 UTC
Jira Link: [DB-1822](https://yugabyte.atlassian.net/browse/DB-1822)

**Comment by rthallamko3** [comment] 2022-09-19 11:38
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/1588

**Closed by rthallamko3** 2022-09-19 11:38 UTC
Labels: kind/enhancement, area/docdb, priority/medium
