### ISSUE TITLE
sqoop failed with error PSQLException: ERROR: duplicate key value violates unique constraint ""

### ISSUE THREAD

**Issue by rogerlzp** [YugaByte/yugabyte-db#2082] opened 2019-08-16 05:16 UTC
yugabyte version: 1.3.1.0
os: redhat7.5
cluster: create a culster with three nodes
sqoop script: 
sqoop export  \
--connect jdbc:postgresql://172.30.83.201:5433/postgres \
--username postgres          \
--password postgres           \
--table tincome_int_ps6             \
--input-fields-terminated-by '\001' \
--input-lines-terminated-by '\n' \
--input-null-string "\\\\N" \
--input-null-non-string "\\\\N"    \
--export-dir  /inceptor1/user/hive/warehouse/ods.db/fsfund/etfta_tincome_ps

there are about 40,000,000 records in that table.

it failed with the error:
2019-08-16 12:47:51,006 INFO  [main] mapreduce.Job (Job.java:printTaskEvents(1406)) - Task Id : attempt_1564637202110_1383_m_000001_2, Status : FAILED
Error: java.io.IOException: Can't export data, please check failed map task logs
        at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:112)
        at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:39)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
        at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1996)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "tincome_int_ps6_pkey"
        at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:220)
        at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:46)
        at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:658)
        at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
        at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:84)
        ... 10 more

checking the logs, 
W0816 04:47:55.661073 65886 rpc.cc:156] Aborted (yb/rpc/rpc.cc:155): Failed to schedule: 0x0000000003039b00 -> AbortTransaction: tablet_id: "6fc8419c5f084b94b60f040726651c54" transaction_id: "\221\013z\227\232\245C\264\206$0\252\354\337D&" propagated_hybrid_time: 6414052866693025792, retrier: { task_id: -1 state: kScheduling deadline: 13982470.488s }
W0816 04:47:55.661141 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661155 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661164 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661170 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661180 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661190 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661201 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661217 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661226 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661238 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661245 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661254 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661262 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
W0816 04:47:55.661273 65886 outbound_call.cc:171] Failed to schedule invoking callback on response for request yb.tserver.TabletServerService.UpdateTransaction to 172.30.83.201: Aborted (yb/rpc/thread_pool.cc:249): Service is shutting down
2019-08-16 04:47:55.713 UTC [65900] LOG:  unexpected EOF on client connection with an open transaction

it looks like there are some error when trying to sync the data between different nodes.

**Comment by spolitov** [comment] 2019-08-16 06:15
Duplicate of #1974

**Comment by kmuthukk** [comment] 2019-08-29 05:12
Closing as duplicate of #1974

**Closed by kmuthukk** 2019-08-29 05:12 UTC
Labels: area/sql, community/request
