### ISSUE TITLE
[YSQL][LST] EXPLAIN DELETE fails: cache lookup failed for attribute -8 of relation 16616

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11999] opened 2022-04-06 15:25 UTC
Jira Link: [DB-918](https://yugabyte.atlassian.net/browse/DB-918)
### Description

This failure happened using the [Long-running System Test](https://github.com/yugabyte/yb-long-system-test/) framework I'm currently working on. Can be reproduced locally:
```
$ cd ~/code/yugabyte-db
$ bin/yb-ctl --replication_factor 3 create
$ cd ~/code/yb-long-system-test
$ git checkout 916fd57 && ./long_system_test.py --runtime=0 --threads=10 --complexity=full --seed=773252
[...]
2022-04-06 17:23:08,271 worker_0   ERROR    Unexpected query failure: InternalError_Query: EXPLAIN (ANALYZE FALSE, VERBOSE TRUE, COSTS FALSE, BUFFERS FALSE, TIMING FALSE, SUMMARY TRUE, FORMAT TEXT) DELETE FROM t3 WHERE c3_text = '-62';
Action: SingleDeleteAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  cache lookup failed for attribute -8 of relation 16616
```

**Comment by def-** [comment] 2022-07-13 17:31
This can happen so often that we end up with 87% query failure rate:
```
2022-07-13 15:47:11,104 MainThread INFO     --------------------------------------------------------------------------------
2022-07-13 15:47:11,104 MainThread INFO     LST finished successfully in 3633.8 sec
2022-07-13 15:47:11,104 MainThread INFO     --------------------------------------------------------------------------------
2022-07-13 15:47:11,104 MainThread INFO
2022-07-13 15:47:11,104 MainThread INFO     Expected error statistics: 87% failures in 2420207 queries
2022-07-13 15:47:11,105 MainThread INFO     22003 re.compile('ERROR:  .* out of range'): Overflow can currently happen with many of our queries
2022-07-13 15:47:11,105 MainThread INFO       RandomSelectAction: 3753, SingleUpdateAction: 37, SingleDeleteAction: 17
2022-07-13 15:47:11,105 MainThread INFO     57014 ERROR:  canceling statement due to user request: Canceled by ourselves
2022-07-13 15:47:11,105 MainThread INFO       RandomSelectAction: 7010, SetConfigAction: 2, SingleDeleteAction: 70, SingleUpdateAction: 95, SingleInsertAction: 23, BulkUpdateAction: 5
2022-07-13 15:47:11,105 MainThread INFO     22012 ERROR:  division by zero:
2022-07-13 15:47:11,105 MainThread INFO       RandomSelectAction: 187
2022-07-13 15:47:11,105 MainThread INFO     25P02 ERROR:  current transaction is aborted, commands ignored until end of transaction block: Canceled by ourselves
2022-07-13 15:47:11,105 MainThread INFO       RandomSelectAction: 1802846, SetConfigAction: 20873, SingleDeleteAction: 90264, SingleUpdateAction: 90266, SingleInsertAction: 81714, BulkInsertAction: 940, BulkUpdateAction: 879
2022-07-13 15:47:11,105 MainThread INFO     XX000 ERROR:  cache lookup failed for attribute: https://github.com/yugabyte/yugabyte-db/issues/11999
2022-07-13 15:47:11,105 MainThread INFO       SingleDeleteAction: 1322, SingleUpdateAction: 1281
```
Also with other actions, especially inserts.

**Comment by def-** [comment] 2022-07-13 22:16
b355d215ba3712b72f3880e6b00b6c7bd36e3518

**Comment by def-** [comment] 2022-08-17 10:15
This is the most common failure when running LST, would be great to have this fixed. @tedyu are you planning to look into it?

**Comment by tedyu** [comment] 2022-08-17 10:59
I am on the road.
I have started looking closer at this error.

**Comment by andrei-mart** [comment] 2022-12-12 20:13
Duplicate of #1562

**Closed by andrei-mart** 2022-12-12 20:13 UTC
Labels: kind/bug, area/ysql, kind/failing-test, priority/medium, QA, qa_automation
