### ISSUE TITLE
[YSQL] Backup should be able to handle tables in different schemas with the same name

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4875] opened 2020-06-24 22:09 UTC
Jira Link: [DB-1597](https://yugabyte.atlassian.net/browse/DB-1597)
Currently, distributed backups won't work if there are 2 tables with the same name in different schemas. This is because we don't have a good way to disambiguate those in yb-master.
We need to enhance snapshot creation to add schema information for YSQL tables to make this work.

**Comment by OlegLoginov** [comment] 2023-01-26 18:47
Closing as a duplicate of fixed https://github.com/yugabyte/yugabyte-db/issues/8804.

**Closed by OlegLoginov** 2023-01-26 18:47 UTC
Labels: kind/enhancement, area/ysql, priority/medium
