### ISSUE TITLE
[YSQL] Sequelize ORM needs support for postgres datatype INTERVAL  

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#899] opened 2019-02-23 23:12 UTC
[Sequelize](http://docs.sequelizejs.com/) is a popular node.js ORM for PostgreSQL (and other RDBMS such as MySQL & MS SQL Server).

Following instructions in https://scotch.io/tutorials/getting-started-with-node-express-and-postgres-using-sequelize with PostgreSQL replaced with YSQL (and also foreign keys removed). Fails at the db:migrate step where the actual bindings to PostgreSQL are created.

```
$ sequelize db:migrate

Sequelize CLI [Node: 9.5.0, CLI: 5.4.0, ORM: 4.42.0]

Loaded configuration file "server/config/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13

ERROR: INTERVAL not supported yet
```

**Comment by d-uspenskiy** [comment] 2019-03-13 06:16
Duplicate of #711
INTERVAL support added in bd64c96

**Closed by d-uspenskiy** 2019-03-13 06:16 UTC
Labels: enhancement
