### ISSUE TITLE
[YSQL] flaky test: org.yb.pgsql.TestPgRegressMisc.testPgRegressMiscSerial3	

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#21673] opened 2024-03-25 15:40 UTC
Jira Link: [DB-10562](https://yugabyte.atlassian.net/browse/DB-10562)
### Description

Spun out from #21558

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressMisc&fail_tag=all&name=testPgRegressMiscSerial3&platform=linux

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10562]: https://yugabyte.atlassian.net/browse/DB-10562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment] 2024-03-25 16:01
duplicate of #21663

**Closed by myang2021** 2024-03-25 16:01 UTC
Labels: kind/enhancement, area/ysql, kind/failing-test, priority/medium, status/awaiting-triage
