### ISSUE TITLE
[YSQL] postgres process crash in _IO_new_fclose while loading TPCC 150k WH data.(YB version: 2.15.1.0-b3)

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12835] opened 2022-06-09 06:04 UTC
Jira Link: [DB-2601](https://yugabyte.atlassian.net/browse/DB-2601)
### Description

On one of the tserver node(172.151.31.53), we had  connectivity ysqlsh issues :

`ysqlsh: could not connect to server: Connection refused\n\tIs the server running on host "172.151.31.53" and accepting\n\tTCP/IP connections on port 5433?`
This was after 6-7 hrs after starting load. The postgres process on the tserver node 172.151.31.53 had crashed with seg fault. Following is the stack dump from the core:
```
warning: File "/home/yugabyte/yb-software/yugabyte-2.15.1.0-b3-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /home/yugabyte/yb-software/yugabyte-2.15.1.0-b3-centos-x86_64/linuxbrew/lib/libthread_db.so.1
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/home/yugabyte/yb-software/yugabyte-2.15.1.0-b3-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/home/yugabyte/yb-software/yugabyte-2.15.1.0-b3-centos-x86_64/postgres/bin/post'.
Program terminated with signal 11, Segmentation fault.
#0  _IO_new_fclose (fp=0x0) at iofclose.c:53
53	iofclose.c: No such file or directory.
(gdb) bt
#0  _IO_new_fclose (fp=0x0) at iofclose.c:53
#1  0x00000000008ab237 in BackendStartup (port=0x1b7c1e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4255
#2  ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1767
#3  0x00000000008a7d01 in PostmasterMain (argc=<optimized out>, argv=0x1b92780) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1423
#4  0x00000000007c85c3 in PostgresServerProcessMain (argc=23, argv=0x1b92780) at ../../../../../../src/postgres/src/backend/main/main.c:234
#5  0x00000000004f5ae2 in main ()
```
From postgres logs :
```
2022-06-08 23:31:02.339 UTC [26363] FATAL:  terminating connection due to unexpected postmaster exit
2022-06-08 23:31:02.340 UTC [22890] FATAL:  terminating connection due to unexpected postmaster exit
```
**Universe details :**
YB version : 2.15.1.0-b3
#nodes : 90 ( 3 master , 87 tserver)
```
GFlags :
{
    "server_tcmalloc_max_total_thread_cache_bytes":"4294967296",
    "enable_automatic_tablet_splitting":"false",
    "global_memstore_size_mb_max":"4096",
    "memstore_size_mb":"256",
    "default_memory_limit_to_ram_ratio" : "0.5" (only for master nodes)
}
```
Tservers running on the master nodes were blacklisted.
Universe link : http://10.9.131.126/universes/e5f28b47-d4e2-4e6e-94b3-586b394679ca (wont be there for long, but the  tservers nodes, mentioned above will be kept running)

**Comment by sushantrmishra** [comment] 2022-06-15 04:40
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/12843

**Closed** 2022-06-15 04:41 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
