### ISSUE TITLE
[docs] Document app consistent secondary indexes

### ISSUE THREAD

**Issue by jameshartig** [yugabyte/yugabyte-db#2271] opened 2019-09-11 20:11 UTC
Documentation is needed on how to use `app consistent secondary indexes` in YCQL

**Comment by stevebang** [comment] 2019-09-11 20:52
Slack discussion added to a Google Doc: https://docs.google.com/document/d/1s9tth9aeVWy3mvSLklCZgjh0vRu2Vf7G3w63YDha0R8/edit#

**Comment by ddorian** [comment] 2022-05-04 07:41
closing as duplicate of #6082

**Closed by ddorian** 2022-05-04 07:41 UTC
Labels: area/documentation, community/request, area/ycql
