### ISSUE TITLE
Tablet deletion after drop table delayed due to ongoing compaction

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#1290] opened 2019-05-01 00:32 UTC
During this time the tablets page for the node did not load. You can see the timeout.

**Start of compaction:**

I0430 23:26:41.558851 20505 compaction_job.cc:1224] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: [default] [JOB 3119] Compacting 10@0 files to L0, score 2.00
I0430 23:26:41.558868 20505 compaction_job.cc:1228] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: [default] Compaction start summary: Base version 3093 Base level 0, inputs: [3101(29MB) 3100(29MB) 3102(235MB) 3092(468MB) 3072(1141MB) 3025(3161MB) 2896(5152MB) 2686(6763MB) 2407(11GB) 1943(13GB)]

**Wait for the tablet to be deleted after the table was dropped:**

I0430 23:35:47.565343 31430 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:39973
I0430 23:35:47.611701 31354 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:58077
I0430 23:35:47.689585 31352 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:59269
I0430 23:35:47.831982 31502 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:36413
I0430 23:35:48.102540 31279 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:59234
I0430 23:35:48.629231 31328 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:35335
I0430 23:35:49.668385 31501 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:44552
I0430 23:35:51.731557 31411 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:39625
I0430 23:35:55.842399 31318 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:39973
I0430 23:36:04.048564 31342 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:58077
I0430 23:36:20.446493 31510 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:59269
I0430 23:36:53.230172 31259 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:41354
I0430 23:37:53.246093 31487 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:40765
I0430 23:38:53.289614 31505 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:34714
I0430 23:39:53.333634 31332 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:42864
I0430 23:40:53.349620 20263 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:39625
I0430 23:41:53.390266 31419 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:48714
I0430 23:42:53.422974 31416 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:54505
I0430 23:43:22.819612  4401 webserver.cc:278] Webserver: error reading: Resource temporarily unavailable
I0430 23:43:53.438243 31320 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:35784
I0430 23:44:53.453748 31444 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:40270
I0430 23:45:53.470137 31504 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:59630
I0430 23:46:53.485493 31370 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:36883
I0430 23:47:53.500351 31454 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:43313

**Compaction ends here:**

I0430 23:48:42.988472 20505 compaction_job.cc:587] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: [default] compacted to: files[14] max score 0.80, MB/sec: 34.0 rd, 0.0 wr, level 0, files in(0, 10) out(0) MB in(0.0, 42839.8) out(0.0), read-write-amplify(44920770646.0) write-amplify(0.0) Shutdown in progress (yb/rocksdb/db/compaction_job.cc:772): Database shutdown or Column family drop during compaction, records in: -1580812296, records dropped: 1911877001
I0430 23:48:42.988517 20505 event_logger.cc:77] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: EVENT_LOG_v1 {"time_micros": 1556668122987380, "job": 3119, "event": "compaction_finished", "compaction_time_micros": 1321428337, "output_level": 0, "num_output_files": 1, "total_output_size": 0, "num_input_records": 1915468001, "num_output_records": 3591000, "num_subcompactions": 1, "lsm_state": [14]}

**Tablet delete finally succeeds**
I0430 23:48:42.993746 31275 db_impl.cc:871] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: [JOB 3124] Delete /mnt/d0/yb-data/tserver/data/rocksdb/table-236226fa5fd442098664e9f14aeb2991/tablet-733fd9b0cd04476596c38a5b32c10926/003103.sst type=2 #3103 -- OK
I0430 23:48:42.993772 31275 event_logger.cc:67] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: EVENT_LOG_v1 {"time_micros": 1556668122993767, "job": 3124, "event": "table_file_deletion", "file_number": 3103}
I0430 23:48:42.994866 31275 raft_consensus.cc:2239] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa [term 5 LEADER]: Shutdown.
I0430 23:48:42.995877 31275 ts_tablet_manager.cc:1601] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: Deleting tablet data with delete state TABLET_DATA_DELETED
I0430 23:48:42.995971 31275 tablet_metadata.cc:371] Destroying regular db at: /mnt/d0/yb-data/tserver/data/rocksdb/table-236226fa5fd442098664e9f14aeb2991/tablet-733fd9b0cd04476596c38a5b32c10926
I0430 23:48:44.696638 31275 tablet_metadata.cc:377] Successfully destroyed regular DB at: /mnt/d0/yb-data/tserver/data/rocksdb/table-236226fa5fd442098664e9f14aeb2991/tablet-733fd9b0cd04476596c38a5b32c10926

I0430 23:48:44.696988 31275 tablet_metadata.cc:388] Successfully destroyed provisional records DB at: /mnt/d0/yb-data/tserver/data/rocksdb/table-236226fa5fd442098664e9f14aeb2991/tablet-733fd9b0cd04476596c38a5b32c10926.intents
I0430 23:48:44.776377 31275 ts_tablet_manager.cc:1611] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: Tablet deleted. Last logged OpId: { term: 5 index: 4431865 }
I0430 23:48:44.776423 31275 log.cc:970] T 733fd9b0cd04476596c38a5b32c10926P 267e5a40baec4f6a99c397796ea2c0aa: Deleting WAL dir /mnt/d0/yb-data/tserver/wals/table-236226fa5fd442098664e9f14aeb2991/tablet-733fd9b0cd04476596c38a5b32c10926
I0430 23:48:44.787809 31275 tablet_bootstrap_if.cc:71] T 733fd9b0cd04476596c38a5b32c10926 P 267e5a40baec4f6a99c397796ea2c0aa: Deleted tablet blocks from disk
I0430 23:48:44.787909 31275 ts_tablet_manager.cc:1562] Unregister data/wal directory assignment map for table: 236226fa5fd442098664e9f14aeb2991
I0430 23:48:44.787981 31275 ts_tablet_manager.cc:1683] Deleted transition in progress deleting tablet for tablet 733fd9b0cd04476596c38a5b32c10926
W0430 23:48:44.788065 31275 yb_rpc.cc:284] Call yb.tserver.TabletServerAdminService.DeleteTablet 10.150.255.2:39625 => 10.150.0.255:9100 (request call id 1429426) took 807253ms (client timeout 29999ms).
I0430 23:48:53.515058 31421 tablet_service.cc:638] Processing DeleteTablet for tablet 733fd9b0cd04476596c38a5b32c10926 with delete_type TABLET_DATA_DELETED (Table deleted at 2019-04-30 23:35:17 UTC) from 10.150.255.2:

**Comment by ttyusupov** [comment] 2019-05-28 18:01
Duplicate of https://github.com/YugaByte/yugabyte-db/issues/488

**Comment by spolitov** [comment] 2019-10-14 05:08
Fixed by dynamic compaction priorities.

**Closed by spolitov** 2019-10-14 05:08 UTC
Labels: area/docdb
