### ISSUE TITLE
[CDCSDK] YSQL CRUD functions for stream management

### ISSUE THREAD

**Issue by adithya-kb** [yugabyte/yugabyte-db#18383] opened 2023-07-24 14:01 UTC
Jira Link: [DB-7376](https://yugabyte.atlassian.net/browse/DB-7376)
CDC Change Streams can be managed using yb-admin utility. Feedback from users is that using yb-admin is not a good user experience.
It requires the user to have ssh access to one of the machines in the universe or access to the master ports.
yb-admin has many sub commands and it can be a challenge to get help and navigate the sub-commands and their parameters. 
Fine-grained access control is required to allow users/owners to self-manage publications.
In YSQL universes, a consistent user experience can be provided by allowing users to manage CDC Change Streams through YSQL clients. 

Users should be able to run commands to:
* Create publications
* Read or list publications and access information about them.
* Update/Alter the parameters or state of a publication.
* Delete publications.
* These operations should be allowed if a user has the right access control.

[DB-7376]: https://yugabyte.atlassian.net/browse/DB-7376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dr0pdb** [comment] 2023-11-22 11:26
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/18724

**Closed** 2023-11-22 11:25 UTC
Labels: kind/enhancement, priority/medium, area/cdcsdk
