### ISSUE TITLE
g++-7 ignores -mcx16 flag as a result CHECK fails at runtime

### ISSUE THREAD

**Issue by d-uspenskiy** [YugaByte/yugabyte-db#1246] opened 2019-04-24 18:40 UTC
It looks like g++-7 generates non-lock-free code for 128 bits atomic structures

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80878

as a result 
`
CHECK(leader_state_cache_.is_lock_free()); 
`
fails at runtime

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/consensus/replica_state.cc#L111

**Comment by d-uspenskiy** [comment] 2019-04-28 11:34
Some description about changes in g++-7

https://gcc.gnu.org/ml/gcc-patches/2017-01/msg02344.html

**Comment by d-uspenskiy** [comment] 2019-06-10 03:24
Duplicate #1189

**Comment by mbautin** [comment] 2019-06-19 19:46
Closing this as a duplicate of the earlier issue.

**Closed by mbautin** 2019-06-19 19:46 UTC
Labels: ybase
