### ISSUE TITLE
ThreadSanitizer check failed in XClusterAdminCliTest_TestListCdcStreamsWithBootstrappedStreams

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14245] opened 2022-09-29 04:59 UTC
Jira Link: [DB-3704](https://yugabyte.atlassian.net/browse/DB-3704)
### Description

ThreadSanitizer check failed in XClusterAdminCliTest_TestListCdcStreamsWithBootstrappedStreams in the latest master 2.15.4.0-b40
Stacktrace- https://gist.github.com/kripasreenivasan/9d62ed2024d8db76d45f696a8e223f3d

**Comment by bmatican** [comment] 2022-09-29 14:13
Duplicate of #14098

**Closed by bmatican** 2022-09-29 14:13 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage, qa_automation
