### ISSUE TITLE
[YSQL] Can't batch UPDATE statements

### ISSUE THREAD

**Issue by lukaseder** [yugabyte/yugabyte-db#17660] opened 2023-06-02 08:18 UTC
Jira Link: [DB-6778](https://yugabyte.atlassian.net/browse/DB-6778)
### Description

I'm using the latest version from docker hub:

```sql
select version();
```

Producing:

> PostgreSQL 11.2-YB-2.18.0.1-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.3 (https://github.com/yugabyte/llvm-project.git 0b8d1183745fd3998d8beffeec8cbe99c1b20529), 64-bit

And JDBC driver version: `com.yugabyte:jdbc-yugabytedb:42.3.5-yb-3`

Now, this program:

```java
try (Statement s = connection.createStatement()) {
    try {
        s.execute("create table t (a int primary key, b int)");
        s.execute("insert into t values (1, 1), (2, 2)");

        try (PreparedStatement p = connection.prepareStatement("update t set b = ? where a = ?")) {
            p.setInt(1, 11);
            p.setInt(2, 1);
            p.addBatch();
            p.setInt(1, 12);
            p.setInt(2, 2);
            p.addBatch();
            p.executeBatch();
        }
    }
    finally {
        s.execute("drop table t");
    }
}
```

Fails with:

```
Exception in thread "main" java.sql.BatchUpdateException: Batch entry 1 update t set b = 12 where a = 2 was aborted: ERROR: Used read time is not set  Call getNextException to see other errors in the batch.
	at com.yugabyte.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:570)
	at com.yugabyte.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:887)
	at com.yugabyte.jdbc.PgStatement.executeBatch(PgStatement.java:910)
	at com.yugabyte.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1634)
	at org.jooq.testscripts.JDBC.main(JDBC.java:57)
Caused by: com.yugabyte.util.PSQLException: ERROR: Used read time is not set
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:559)
	... 4 more
```

The workaround is to avoid batching:

```java
try (Statement s = connection.createStatement()) {
    try {
        s.execute("create table t (a int primary key, b int)");
        s.execute("insert into t values (1, 1), (2, 2)");

        try (PreparedStatement p = connection.prepareStatement("update t set b = ? where a = ?")) {
            p.setInt(1, 11);
            p.setInt(2, 1);
            p.execute();
            p.setInt(1, 12);
            p.setInt(2, 2);
            p.execute();
        }
    }
    finally {
        s.execute("drop table t");
    }
}
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6778]: https://yugabyte.atlassian.net/browse/DB-6778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment] 2023-06-26 23:50
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/16446

**Closed by sushantrmishra** 2023-06-26 23:50 UTC
Labels: kind/bug, area/ysql, priority/medium
