### ISSUE TITLE
[YCQL][Audit] Improve performance characteristics of audit logging

### ISSUE THREAD

**Issue by akumar-yb** [yugabyte/yugabyte-db#9901] opened 2021-09-01 15:28 UTC
The `ycql_enable_audit_log` does two things that vastly hurt performance:

1. Audits are to ERROR log which is a syncronous write
2. EVERYTHING is audited - so there's a performance hurt to every query or DML or login

It would be great to investigate some ways to improve the default flag set (maybe a good "flag set" feature in platform) that applies a sensible audit log set.

---

Background: 

After adding (client_read_write_timeout_ms: 600000 )  flag now facing  errors',  'NoHostAvailable'  in parallel DDL/DML  operations

on 1st terminal :- we performed copy (COPY testalter.layer1message FROM 'layer2message-data.csv' WITH HEADER = TRUE ;) csv having 18lakh record .
on 2nd terminal :- source 'db.cql' ;  we got 'NoHostAvailable'  issue .
on 3rd terminal :- Run  Some DDL and DML commands

After an investigation:
If we set the gflag `“ycql_enable_audit_log=false”` then the issue is resolved and when set to `true` the issue is reproduced.

---

https://yugabyte.zendesk.com/agent/tickets/1655

**Comment by frozenspider** [comment] 2022-01-26 11:42
This was caused by low system entropy getting depleted by RNG. Resolved in #10962

**Closed by frozenspider** 2022-01-26 11:42 UTC
Labels: kind/bug, area/docdb
