### ISSUE TITLE
Check Failure: client/table.cc:412] Check failed: it != partitions.begin() Could not find partition start while looking for

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#7032] opened 2021-01-29 16:22 UTC
Jira Link: [DB-4749](https://yugabyte.atlassian.net/browse/DB-4749)
```
F20210129 07:19:59 ../../src/yb/client/table.cc:412] Check failed: it != partitions.begin() Could not find partition start while looking for >� in [UP, _�, �, �H]
    @     0x7fb74f15f4d7  yb::LogFatalHandlerSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long) (src/yb/util/logging.cc:474)
    @     0x7fb74e333865
    @     0x7fb74e330e39
    @     0x7fb74e331062
    @     0x7fb75521cfef  yb::client::internal::Batcher::TabletLookupFinished(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) (src/yb/client/batcher.cc:438)
    @     0x7fb75521f9df  void std::_Mem_fn_base<void (yb::client::internal::Batcher::*)(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&), true>::_M_call<scoped_refptr<yb::client::internal::Batcher>&, shared_ptr<yb::client::internal::InFlightOp>&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&>(scoped_refptr<yb::client::internal::Batcher>&, void const volatile*, shared_ptr<yb::client::internal::InFlightOp>&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:634)
    @     0x7fb75521f9df  void std::_Mem_fn_base<void (yb::client::internal::Batcher::*)(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&), true>::operator()<scoped_refptr<yb::client::internal::Batcher>&, shared_ptr<yb::client::internal::InFlightOp>&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&, void>(scoped_refptr<yb::client::internal::Batcher>&, shared_ptr<yb::client::internal::InFlightOp>&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:610)
    @     0x7fb75521f9df  void std::_Bind<std::_Mem_fn<void (yb::client::internal::Batcher::*)(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)> (scoped_refptr<yb::client::internal::Batcher>, shared_ptr<yb::client::internal::InFlightOp>, std::_Placeholder<1>)>::__call<void, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&, 0ul, 1ul, 2ul>(tuple<yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
    @     0x7fb75521f9df  void std::_Bind<std::_Mem_fn<void (yb::client::internal::Batcher::*)(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)> (scoped_refptr<yb::client::internal::Batcher>, shared_ptr<yb::client::internal::InFlightOp>, std::_Placeholder<1>)>::operator()<yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&, void>(yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
    @     0x7fb75521f9df  std::_Function_handler<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&), std::_Bind<std::_Mem_fn<void (yb::client::internal::Batcher::*)(shared_ptr<yb::client::internal::InFlightOp>, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)> (scoped_refptr<yb::client::internal::Batcher>, shared_ptr<yb::client::internal::InFlightOp>, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
    @     0x7fb7552abf52  std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>::operator()(yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
    @     0x7fb7552b7192  bool yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<boost::shared_mutex> >(shared_ptr<yb::client::YBTable const> const&, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>*)::{lambda()#1}::operator()() const (src/yb/client/meta_cache.cc:1569)
    @     0x7fb7552bbbe9  yb::ScopeExitLambda<bool yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<boost::shared_mutex> >(shared_ptr<yb::client::YBTable const> const&, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>*)::{lambda()#1}>::~ScopeExitLambda() (src/yb/util/scope_exit.h:34)
    @     0x7fb7552bbbe9  bool yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<boost::shared_mutex> >(shared_ptr<yb::client::YBTable const> const&, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>*) (src/yb/client/meta_cache.cc:1571)
    @     0x7fb7552a9be1  yb::client::internal::MetaCache::LookupTabletByKey(shared_ptr<yb::client::YBTable const> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>) (src/yb/client/meta_cache.cc:1680)
    @     0x7fb75521e2a4  yb::client::internal::Batcher::Add(shared_ptr<yb::client::YBOperation>) (src/yb/client/batcher.cc:343)
    @     0x7fb7552c6f54  yb::client::YBSession::Apply(shared_ptr<yb::client::YBOperation>) (src/yb/client/session.cc:225)
    @     0x7fb7579e47b7  yb::tablet::Tablet::UpdateQLIndexes(unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >) (src/yb/tablet/tablet.cc:1591)
    @     0x7fb7579e548d  operator()<unique_ptr<yb::tablet::WriteOperation> > (src/yb/tablet/tablet.cc:1491)
    @     0x7fb7579e548d  invoke (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/uninstrumented/include/boost/function/function_template.hpp:158)
    @     0x7fb7579f84b1  boost::function2<void, unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >, yb::Status const&>::operator()(unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >, yb::Status const&) const (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/uninstrumented/include/boost/function/function_template.hpp:764)
    @     0x7fb7579f84b1  yb::tablet::DocWriteOperation::InvokeCallback(yb::Status const&) (src/yb/tablet/tablet.cc:2820)
    @     0x7fb757a07eaa
    @     0x7fb756a055c2  boost::function1<void, yb::Result<yb::HybridTime> const&>::operator()(yb::Result<yb::HybridTime> const&) const (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/uninstrumented/include/boost/function/function_template.hpp:764)
    @     0x7fb756a055c2  InvokeCallback (src/yb/docdb/conflict_resolution.cc:223)
    @     0x7fb756a055c2  ResolveConflicts (src/yb/docdb/conflict_resolution.cc:245)
    @     0x7fb756a055c2  Resolve (src/yb/docdb/conflict_resolution.cc:139)
    @     0x7fb756a055c2  yb::docdb::ResolveTransactionConflicts(std::vector<unique_ptr<yb::docdb::DocOperation, std::default_delete<yb::docdb::DocOperation> >, std::allocator<unique_ptr<yb::docdb::DocOperation, std::default_delete<yb::docdb::DocOperation> > > > const&, yb::docdb::KeyValueWriteBatchPB const&, yb::HybridTime, yb::HybridTime, yb::docdb::DocDB const&, yb::StronglyTypedBool<yb::docdb::PartialRangeKeyIntents_Tag>, yb::TransactionStatusManager*, yb::Counter*, boost::function<void (yb::Result<yb::HybridTime> const&)>) (src/yb/docdb/conflict_resolution.cc:893)
    @     0x7fb757a07873
    @     0x7fb7579ed0bb  yb::tablet::DocWriteOperation::Start() (src/yb/tablet/tablet.cc:2811)
    @     0x7fb7579ed0bb  yb::tablet::Tablet::StartDocWriteOperation(unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >, yb::ScopedRWOperation, boost::function<void (unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >, yb::Status const&)>) (src/yb/tablet/tablet.cc:3033)
    @     0x7fb7579ee4ba  yb::tablet::Tablet::KeyValueBatchFromQLWriteBatch(unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >) (src/yb/tablet/tablet.cc:1495)
    @     0x7fb7579eed9c  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations(unique_ptr<yb::tablet::WriteOperation, std::default_delete<yb::tablet::WriteOperation> >) (src/yb/tablet/tablet.cc:1901)
    @     0x7fb757a31991  yb::tablet::TabletPeer::WriteAsync(unique_ptr<yb::tablet::WriteOperationState, std::default_delete<yb::tablet::WriteOperationState> >, long, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) (src/yb/tablet/tablet_peer.cc:603)
    @     0x7fb7582f54a5  yb::tserver::TabletServiceImpl::Write(yb::tserver::WriteRequestPB const*, yb::tserver::WriteResponsePB*, yb::rpc::RpcContext) (src/yb/tserver/tablet_service.cc:1470)
    @     0x7fb754ec7b99  yb::tserver::TabletServerServiceIf::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/tserver/tserver_service.service.cc:148)
    @     0x7fb7508f3450  yb::rpc::ServicePoolImpl::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/rpc/service_pool.cc:262)
    @     0x7fb75088f8e4  yb::rpc::InboundCall::InboundCallTask::Run() (src/yb/rpc/inbound_call.cc:212)
    @     0x7fb75090662a  Execute (src/yb/rpc/thread_pool.cc:105)
    @     0x7fb750901d38  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
    @     0x7fb750901d38  __call<void, 0ul> (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
    @     0x7fb750901d38  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
    @     0x7fb750901d38  _M_invoke (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
    @     0x7fb74f1ee499  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
    @     0x7fb74f1ee499  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:771)
    @     0x7fb749bb2693  start_thread (/tmp/glibc-20181130-26094-cs1x60/glibc-2.23/nptl/pthread_create.c:333)
    @     0x7fb7498f441c  (unknown) (sysdeps/unix/sysv/linux/x86_64/clone.S:109)
    @ 0xffffffffffffffff
    ```

**Comment by amitanandaiyer** [comment] 2021-01-29 16:23
Also seen during other runs. This particular one was while running

ybd --cxx-test integration-tests_cassandra_cpp_driver-test --gtest_filter CppCassandraDriverTest*TestTableCreateIndexSlowAlters -n 10 --tp 1

on

https://phabricator.dev.yugabyte.com/D8946?id=50078

**Comment by bmatican** [comment] 2023-03-04 04:15
Duplicate of #6054

**Closed by bmatican** 2023-03-04 04:15 UTC
Labels: kind/bug, area/docdb, priority/medium
