### ISSUE TITLE
[YSQL] Bank workload with read committed transactions eventually stopped write operations

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#18053] opened 2023-07-03 16:26 UTC
Jira Link: [DB-7101](https://yugabyte.atlassian.net/browse/DB-7101)
### Description

Reproducible locally with latest master builds
**Same workload works if start local cluster without RC gflags or use other isolation levels**

Started local node:
`bin/yb-ctl start --tserver_flags=yb_enable_read_committed_isolation=true --master_flags=yb_enable_read_committed_isolation=true`

Started sample-apps workload that simulates bank workload (but with disabled consistency checks)
```
2023-07-03 20:16:15,164 [main] INFO CmdLineOpts - SQL: Transaction type number used: 2
2023-07-03 20:16:15,169 [main] INFO CmdLineOpts - SqlTransactions: will use 1 value columns for the main table
2023-07-03 20:16:15,339 [main] INFO SqlBankTransfer - Dropped table: bankaccounts
2023-07-03 20:16:15,359 [main] INFO SqlBankTransfer - Dropping any table(s) left from previous runs if any
2023-07-03 20:16:15,497 [main] INFO SqlBankTransfer - Created table: bankaccounts
2023-07-03 20:16:17,724 [main] INFO SqlBankTransfer - Created index: bankaccountsidx
2023-07-03 20:16:17,759 [main] INFO SqlBankTransfer - Created 20 accounts bankaccounts - sum 20000 
2023-07-03 20:16:20,203 [Thread-0] INFO MetricsTracker - Read: 11.17 ops/sec (29.08 ms/op), 56 total ops  |  Write: 13.96 ops/sec (47.31 ms/op), 70 total ops  |  Uptime: 5031 ms | 
2023-07-03 20:16:25,210 [Thread-0] INFO MetricsTracker - Read: 44.84 ops/sec (22.28 ms/op), 281 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 70 total ops  |  Uptime: 10039 ms | 
2023-07-03 20:16:30,214 [Thread-0] INFO MetricsTracker - Read: 44.95 ops/sec (22.24 ms/op), 506 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 70 total ops  |  Uptime: 15042 ms | 
2023-07-03 20:16:35,218 [Thread-0] INFO MetricsTracker - Read: 46.76 ops/sec (21.38 ms/op), 740 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 70 total ops  |  Uptime: 20046 ms | 
2023-07-03 20:16:40,226 [Thread-0] INFO MetricsTracker - Read: 45.13 ops/sec (22.13 ms/op), 966 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 70 total ops  |  Uptime: 25055 ms | 
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7101]: https://yugabyte.atlassian.net/browse/DB-7101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-07-05 17:05
@qvad , Is this a regression in master? If so, can you git bisect to determine the regression? cc @sushantrmishra

**Comment by rthallamko3** [comment] 2023-07-05 17:06
Also, what is the default set of keys that need to be written in the workload? Why do you think its a product issue and not necessarily a workload issue?

**Comment by qvad** [comment] 2023-07-06 07:18
@rthallamko3 Workload runs successfully without RC flags and on other isolation levels. In client thread dump it shows that all writer threads are stuck on requesting DB results

**Comment by qvad** [comment] 2023-07-21 16:38
Reevaluated tests with RC and `--enable_wait_queues=true,enable_deadlock_detection=true` flags. Issue is no longer reproducible and there was no errors for 7h+ test.

**Comment by pkj415** [comment] 2023-12-12 20:32
I tried this locally with an rf3 cluster based off master, but am able to repro it. Closing it, re-open if the issue is seen again.

```
[pjain@dev-server-pjain ~]$ java -jar yb-stress-sample-apps-1.1.29.jar --workload SqlBankTransfer --nodes 127.0.0.1:5433 --num_threads_read 1 --num_threads_write 1 --num_reads 1500000 --num_writes 2000000
2023-12-12 20:31:21,073 [main] INFO Main - Starting sample app...
2023-12-12 20:31:21,155 [main] INFO CmdLineOpts - Using a randomly generated UUID : a69ea495-c7c9-4813-af16-5bdf9957672b
2023-12-12 20:31:21,169 [main] INFO CmdLineOpts - App: SqlBankTransfer
2023-12-12 20:31:21,174 [main] INFO CmdLineOpts - Num reader threads: 1, num writer threads: 1
2023-12-12 20:31:21,179 [main] INFO CmdLineOpts - Num unique keys to insert: 0
2023-12-12 20:31:21,180 [main] INFO CmdLineOpts - Num keys to update: 2000000
2023-12-12 20:31:21,180 [main] INFO CmdLineOpts - Num keys to read: 1500000
2023-12-12 20:31:21,181 [main] INFO CmdLineOpts - Value size: 0
2023-12-12 20:31:21,181 [main] INFO CmdLineOpts - Restrict values to ASCII strings: false
2023-12-12 20:31:21,181 [main] INFO CmdLineOpts - Perform sanity check at end of app run: false
2023-12-12 20:31:21,181 [main] INFO CmdLineOpts - Run time (seconds): -1
2023-12-12 20:31:21,182 [main] INFO CmdLineOpts - Adding node: 127.0.0.1:5433
2023-12-12 20:31:21,183 [main] INFO CmdLineOpts - Table TTL (secs): -1
2023-12-12 20:31:21,183 [main] INFO CmdLineOpts - Row level TTL (secs): -1
2023-12-12 20:31:21,184 [main] INFO CmdLineOpts - Read only load: false
2023-12-12 20:31:21,192 [main] INFO CmdLineOpts - SqlTransactions: will use 1 value columns for the main table
2023-12-12 20:31:22,091 [main] INFO SqlBankTransfer - Dropping any table(s) left from previous runs if any
2023-12-12 20:31:22,842 [main] INFO SqlBankTransfer - Created table: bankaccounts
2023-12-12 20:31:26,135 [main] INFO SqlBankTransfer - Created index: bankaccountsidx
2023-12-12 20:31:26,340 [main] INFO SqlBankTransfer - Created 20 accounts bankaccounts - sum 20000
2023-12-12 20:31:31,368 [Thread-1] INFO MetricsTracker - Read: 5.18 ops/sec (187.02 ms/op), 26 total ops  |  Write: 5.19 ops/sec (137.18 ms/op), 26 total ops  |  Uptime: 5027 ms |
2023-12-12 20:31:36,370 [Thread-1] INFO MetricsTracker - Read: 5.39 ops/sec (186.82 ms/op), 53 total ops  |  Write: 5.60 ops/sec (130.00 ms/op), 54 total ops  |  Uptime: 10029 ms |
2023-12-12 20:31:41,371 [Thread-1] INFO MetricsTracker - Read: 5.60 ops/sec (175.57 ms/op), 81 total ops  |  Write: 6.00 ops/sec (128.90 ms/op), 84 total ops  |  Uptime: 15030 ms |
2023-12-12 20:31:46,372 [Thread-1] INFO MetricsTracker - Read: 6.00 ops/sec (167.33 ms/op), 111 total ops  |  Write: 5.60 ops/sec (120.53 ms/op), 112 total ops  |  Uptime: 20031 ms |
2023-12-12 20:31:51,372 [Thread-1] INFO MetricsTracker - Read: 6.00 ops/sec (168.11 ms/op), 141 total ops  |  Write: 6.00 ops/sec (127.81 ms/op), 142 total ops  |  Uptime: 25031 ms |
2023-12-12 20:31:56,373 [Thread-1] INFO MetricsTracker - Read: 5.40 ops/sec (181.71 ms/op), 168 total ops  |  Write: 5.40 ops/sec (130.37 ms/op), 169 total ops  |  Uptime: 30032 ms |
2023-12-12 20:32:01,374 [Thread-1] INFO MetricsTracker - Read: 6.20 ops/sec (159.48 ms/op), 199 total ops  |  Write: 6.00 ops/sec (124.87 ms/op), 199 total ops  |  Uptime: 35033 ms |
2023-12-12 20:32:06,375 [Thread-1] INFO MetricsTracker - Read: 4.80 ops/sec (211.75 ms/op), 223 total ops  |  Write: 5.00 ops/sec (153.56 ms/op), 224 total ops  |  Uptime: 40034 ms |
2023-12-12 20:32:11,376 [Thread-1] INFO MetricsTracker - Read: 6.40 ops/sec (158.55 ms/op), 255 total ops  |  Write: 6.20 ops/sec (121.27 ms/op), 255 total ops  |  Uptime: 45035 ms |
2023-12-12 20:32:16,377 [Thread-1] INFO MetricsTracker - Read: 5.80 ops/sec (171.13 ms/op), 284 total ops  |  Write: 7.40 ops/sec (121.02 ms/op), 292 total ops  |  Uptime: 50036 ms |
2023-12-12 20:32:21,378 [Thread-1] INFO MetricsTracker - Read: 6.00 ops/sec (168.57 ms/op), 314 total ops  |  Write: 5.00 ops/sec (134.32 ms/op), 317 total ops  |  Uptime: 55037 ms |
```

**Closed by pkj415** 2023-12-12 20:32 UTC
Labels: kind/bug, area/ysql, priority/medium
