### ISSUE TITLE
[colocation] fix table already exists error

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#3681] opened 2020-02-18 22:43 UTC
Jira Link: [DB-3698](https://yugabyte.atlassian.net/browse/DB-3698)
Starting from commit 74379aa5799a6f30bee5b08ee3d4942b78c676f6, YSQL table colocation encounters an error that makes it unusable.

```sql
CREATE DATABASE co WITH colocated = true;
```

causes the following to show up in tserver logs

```
F0218 14:35:59.852634  4126 tablet_metadata.cc:697] Table 00004000000030008000000000000000.colocated.parent.uuid already exists. New table info: table_id: "00004000000030008000000000000000.colocated.parent.uuid" table_name: "00004000000030008000000000000000.colocated.parent.tablename" table_type: PGSQL_TABLE_TYPE schema { columns { id: 10 name: "parent_column" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: 65537 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false num_tablets: 2 is_ysql_catalog_table: false is_backfilling: false } } schema_version: 0 partition_schema { range_schema { } }, old table info: table_id: "00004000000030008000000000000000.colocated.parent.uuid" table_name: "00004000000030008000000000000000.colocated.parent.tablename" table_type: PGSQL_TABLE_TYPE schema { columns { id: 10 name: "parent_column" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: 65537 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false num_tablets: 2 is_ysql_catalog_table: false is_backfilling: false } } schema_version: 0 partition_schema { range_schema { } }
```

and it crashes the tserver (I only tested with replication factor 1).

**Comment by jj-kim** [comment] 2020-02-18 23:25
This patch on commit 74379aa5799a6f30bee5b08ee3d4942b78c676f6 seems to make the bug disappear:

```diff
diff --git a/src/yb/master/async_rpc_tasks.cc b/src/yb/master/async_rpc_tasks.cc
index 904496d0b..c04bbfd6c 100644
--- a/src/yb/master/async_rpc_tasks.cc
+++ b/src/yb/master/async_rpc_tasks.cc
@@ -135,9 +135,6 @@ Status RetryingTSRpcTask::Run() {

   const Status s = ResetTSProxy();
   if (!s.ok()) {
-    if (RescheduleWithBackoffDelay()) {
-      return Status::OK();
-    }
     if (PerformStateTransition(MonitoredTaskState::kWaiting, MonitoredTaskState::kFailed)) {
       UnregisterAsyncTask();  // May delete this.
       return s.CloneAndPrepend("Failed to reset TS proxy");
```

However, this patch on commit c487f91537071bc3c38e3c038e065b1dabab79ee (74379aa5799a6f30bee5b08ee3d4942b78c676f6~1) seems to not introduce the bug:

```diff
diff --git i/src/yb/master/async_rpc_tasks.cc w/src/yb/master/async_rpc_tasks.cc
index e981d19c4..8e4166ce3 100644
--- i/src/yb/master/async_rpc_tasks.cc
+++ w/src/yb/master/async_rpc_tasks.cc
@@ -135,6 +135,9 @@ Status RetryingTSRpcTask::Run() {

   const Status s = ResetTSProxy();
   if (!s.ok()) {
+    if (RescheduleWithBackoffDelay()) {
+      return Status::OK();
+    }
     if (PerformStateTransition(MonitoredTaskState::kWaiting, MonitoredTaskState::kFailed)) {
       UnregisterAsyncTask();  // May delete this.
       return s.CloneAndPrepend("Failed to reset TS proxy");
```

**Comment by jj-kim** [comment] 2020-02-18 23:48
Here is a stack trace on the fatal:

```
    @     0x7faa4b007258  yb::tablet::RaftGroupMetadata::AddTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, yb::TableType, yb::Schema const&, yb::IndexMap const&, yb::PartitionSchema const&, boost::optional<yb::IndexInfo> const&, unsigned int) (src/yb/tablet/tablet_metadata.cc:698)
    @     0x7faa4af6ed5c  yb::tablet::Tablet::AddTable(yb::tablet::TableInfoPB const&) (src/yb/tablet/tablet.cc:1717)
    @     0x7faa4afd6ce2  yb::tablet::ChangeMetadataOperation::DoReplicated(long, yb::Status*) (src/yb/tablet/operations/change_metadata_operation.cc:212)
    @     0x7faa4afd24d2  yb::tablet::Operation::Replicated(long) (src/yb/tablet/operations/operation.cc:63)
    @     0x7faa4afde54d  yb::tablet::OperationDriver::ApplyTask(long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) (src/yb/tablet/operations/operation_driver.cc:442)
    @     0x7faa4afdee11  yb::tablet::OperationDriver::ApplyOperation(long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) (src/yb/tablet/operations/operation_driver.cc:421)
    @     0x7faa4afdfd26  yb::tablet::OperationDriver::ReplicationFinished(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) (src/yb/tablet/operations/operation_driver.cc:375)
    @     0x7faa4afaa5cb  void std::_Mem_fn_base<void (yb::tablet::OperationDriver::*)(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*), true>::operator()<yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*, void>(yb::tablet::OperationDriver*, yb::Status const&, long&&, std::vector<yb::OpId, std::allocator<yb::OpId> >*&&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
    @     0x7faa4afaa5cb  void std::_Bind<std::_Mem_fn<void (yb::tablet::OperationDriver::*)(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*)> (yb::tablet::OperationDriver*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>)>::__call<void, yb::Status const&, long&&, std::vector<yb::OpId, std::allocator<yb::OpId> >*&&, 0ul, 1ul, 2ul, 3ul>(tuple<yb::Status const&, long&&, std::vector<yb::OpId, std::allocator<yb::OpId> >*&&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
    @     0x7faa4afaa5cb  void std::_Bind<std::_Mem_fn<void (yb::tablet::OperationDriver::*)(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*)> (yb::tablet::OperationDriver*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>)>::operator()<yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*, void>(yb::Status const&, long&&, std::vector<yb::OpId, std::allocator<yb::OpId> >*&&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
    @     0x7faa4afaa5cb  std::_Function_handler<void (yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*), std::_Bind<std::_Mem_fn<void (yb::tablet::OperationDriver::*)(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*)> (yb::tablet::OperationDriver*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>)> >::_M_invoke(std::_Any_data const&, yb::Status const&, long&&, std::vector<yb::OpId, std::allocator<yb::OpId> >*&&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
    @     0x7faa4ac1e478  std::function<void (yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*)>::operator()(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
    @     0x7faa4ac1e478  yb::consensus::ConsensusRound::NotifyReplicationFinished(yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) (src/yb/consensus/consensus.cc:70)
    @     0x7faa4ac7d574  yb::consensus::ReplicaState::NotifyReplicationFinishedUnlocked(scoped_refptr<yb::consensus::ConsensusRound> const&, yb::Status const&, long, std::vector<yb::OpId, std::allocator<yb::OpId> >*) (src/yb/consensus/replica_state.cc:1245)
    @     0x7faa4ac857d4  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked(yb::OpId const&, yb::StronglyTypedBool<yb::consensus::CouldStop_Tag>) (src/yb/consensus/replica_state.cc:860)
    @     0x7faa4ac8621f  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked(yb::OpId const&, yb::StronglyTypedBool<yb::consensus::CouldStop_Tag>) (src/yb/consensus/replica_state.cc:797)
    @     0x7faa4ac8655e  yb::consensus::ReplicaState::UpdateMajorityReplicatedUnlocked(yb::OpIdPB const&, yb::OpIdPB*, bool*) (src/yb/consensus/replica_state.cc:711)
    @     0x7faa4ac5a26a  yb::consensus::RaftConsensus::UpdateMajorityReplicated(yb::consensus::MajorityReplicatedData const&, yb::OpIdPB*) (src/yb/consensus/raft_consensus.cc:1051)
    @     0x7faa4ac390a5  yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask(yb::consensus::MajorityReplicatedData const&) (src/yb/consensus/consensus_queue.cc:1293)
    @     0x7faa4ac3bb1a
    @     0x7faa43f783c6  yb::Callback<void ()>::Run() const (src/yb/gutil/callback.h:411)
    @     0x7faa43f7841b  void std::_Mem_fn_base<void (yb::Callback<void ()>::*)() const, true>::operator()<, void>(yb::Callback<void ()> const&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:583)
    @     0x7faa43f7841b  void std::_Bind<std::_Mem_fn<void (yb::Callback<void ()>::*)() const> (yb::Callback<void ()>)>::__call<void, , 0ul>(tuple<>&&, std::_Index_tuple<0ul>) (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
    @     0x7faa43f7841b  void std::_Bind<std::_Mem_fn<void (yb::Callback<void ()>::*)() const> (yb::Callback<void ()>)>::operator()<, void>() (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
    @     0x7faa43f7841b  std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::Callback<void ()>::*)() const> (yb::Callback<void ()>)> >::_M_invoke(std::_Any_data const&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
    @     0x7faa49c88339  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
    @     0x7faa49c88339  yb::FunctionRunnable::Run() (src/yb/util/threadpool.h:479)
    @     0x7faa43f7513b  yb::ThreadPool::DispatchThread(bool) (src/yb/util/threadpool.cc:608)
    @     0x7faa43f783f2  void std::_Mem_fn_base<void (yb::ThreadPool::*)(bool), true>::operator()<bool&, void>(yb::ThreadPool*, bool&) const (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
    @     0x7faa43f783f2  void std::_Bind<std::_Mem_fn<void (yb::ThreadPool::*)(bool)> (yb::ThreadPool*, bool)>::__call<void, , 0ul, 1ul>(tuple<>&&, std::_Index_tuple<0ul, 1ul>) (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
    @     0x7faa43f783f2  void std::_Bind<std::_Mem_fn<void (yb::ThreadPool::*)(bool)> (yb::ThreadPool*, bool)>::operator()<, void>() (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
    @     0x7faa43f783f2  std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::ThreadPool::*)(bool)> (yb::ThreadPool*, bool)> >::_M_invoke(std::_Any_data const&) (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
    @     0x7faa43f6dd6f  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
    @     0x7faa43f6dd6f  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:739)
    @     0x7faa3ebc1693  start_thread (/tmp/glibc-20181130-26094-cs1x60/glibc-2.23/nptl/pthread_create.c:333)
    @     0x7faa3e90341c  (unknown) (sysdeps/unix/sysv/linux/x86_64/clone.S:109)
    @ 0xffffffffffffffff
```

**Comment by jj-kim** [comment] 2020-02-19 00:02
This causes the following tests to fail:

* `./yb_build.sh --cxx-test pg_libpq-test --gtest_filter PgLibPqTest.TableColocation`
  * `yb_feature_colocation`
* `./yb_build.sh --java-test org.yb.pgsql.TestPgRegressBetaFeatures`

Strangely, `yb_feature_colocation` is able to create the database, connect to it, but then fail to create a table in the database.

**Comment by jj-kim** [comment] 2020-02-19 00:05
Following up on that, I was able to execute `\l` once successfully after `CREATE DATABASE` then fatal before the second `\l`.

**Comment by bmatican** [comment] 2020-02-19 00:32
The FATAL is likely a symptom of sending a CreateTablet RPC twice, for the same tablet. Maybe the new reschedule that you added @amitanandaiyer is kicking in even when it should not? cc @jj-kim

**Comment by jj-kim** [comment] 2020-02-19 00:46
This partial revert patch seems to fix it:

```diff
diff --git i/src/yb/master/async_rpc_tasks.cc w/src/yb/master/async_rpc_tasks.cc
index 904496d0b..e8e6dcce0 100644
--- i/src/yb/master/async_rpc_tasks.cc
+++ w/src/yb/master/async_rpc_tasks.cc
@@ -244,9 +244,7 @@ int RetryingTSRpcTask::max_delay_ms() {

 bool RetryingTSRpcTask::RescheduleWithBackoffDelay() {
   auto task_state = state();
-  if (task_state != MonitoredTaskState::kRunning &&
-      // Allow kWaiting for task(s) that have never successfully ResetTSProxy().
-      task_state != MonitoredTaskState::kWaiting) {
+  if (task_state != MonitoredTaskState::kRunning) {
     if (task_state != MonitoredTaskState::kComplete) {
       LOG_WITH_PREFIX(INFO) << "No reschedule for this task";
     }
```

**Comment by amitanandaiyer** [comment] 2020-02-19 02:52
This seems like a race condition/wrong behavior that's exposed more frequently after the change, but the correct fix would be to fix the tserver behavior to accept duplicate RPCs. RetryingTSRpcTasks may, in general, be retried upon various conditions -- one shouldn't expect that the tserver will only receive the call exactly once (or never in the case, of this test, where it expects it to be not received at all.)

Aside from that though -- for the runs that pass, (with the Reschedule commented out ) I see in the logs  lines such as :
```
[m-1] W0219 01:08:04.743818 24734 catalog_manager.cc:2174] Failed to send AddTableToTablet request: Not found (yb/master/catalog_entity_info.cc:133): Failed to reset TS proxy: No leader found for tablet a7999727962246dcb83599a9b942ae3b (table 00004000000030008000000000000000.colocated.parent.tablename [id=00004000000030008000000000000000.co       located.parent.uuid]) with 0 replicas: [].
```

```

  if (colocated) {
    auto call =
        std::make_shared< >(master_, worker_pool_.get(), tablets[0], table);
    table->AddTask(call);
    WARN_NOT_OK(call->Run(), "Failed to send AddTableToTablet request");
  }
``` 
Not sure if the expected behavior is that this RPC should fail right away and not reach the TServer 
If so, why make the call even?

**Comment by amitanandaiyer** [comment] 2020-02-19 03:27
@bmatican 
```
Processing CreateTablet for tablet TABLET26 (table=00004000000030008000000000000000.colocated.parent.tablename [id=00004000000030008000000000000000.colocated.parent.uuid]), partition=

Scheduling retry of AddTableToTablet RPC (00004000000030008000000000000000.colocated.parent.tablename [id=00004000000030008000000000000000.colocated.parent.uuid]) (TABLET26 (table 00004000000030008000000000000000.colocated.parent.tablename [id=00004000000030008000000000000000.colocated.parent.uuid])), state=kWaiting with a delay of 21ms (attempt = 0)...
```

would correspond to two *different* rpcs, wouldn't they?

**Comment by amitanandaiyer** [comment] 2020-02-19 04:21
my sense is that if the colocation table is being created for the very first time, we should only be issuing CreateTable, and not the AddTableToTablet. (without making changes to the TServer)

We are currently issuing both the RPCs, but getting away with it because the AddTableToTablet RPC fails right away.

**Comment by jasonyb** [comment] 2022-09-29 00:48
> the correct fix would be to fix the tserver behavior to accept duplicate RPCs. RetryingTSRpcTasks may, in general, be retried upon various conditions -- one shouldn't expect that the tserver will only receive the call exactly once (or never in the case, of this test, where it expects it to be not received at all.)

It looks like the fix was only for a specific case on colocation, but the above fix was never done.  The DFATAL still exists and is getting hit for both system tables and colocated tables:

#### system tables

On jenkins debug clang14 builds, I got the following hits for that error message:

```
./12/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/ColocatedDB__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAlterTableAddFK__1.log
./12/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools_yb-admin-snapshot-schedule-test__ColocatedDB_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlAlterTableAddFK_1__error.log
./14/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAddCheckConstraint__1.log
./15/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_PgsqlTestTruncateDisallowedWithPitr.log
./17/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlRenameTable__0.log
./19/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequenceUndoInsertedData__0.log
./22/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlDropTable__2.log
./26/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_index_backfill-test/PgIndexBackfillTest_MasterLeaderStepdown.log
./30/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlRenameTable__1.log
./30/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_DropTablegroupWithRestoredTable.log
./30/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequenceUndoCreateSequence__0.log
./30/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequenceUndoCreateSequence_0__error.log
./35/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAlterTableAddFK__2.log
./38/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlDropDefault__0.log
./48/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlCreateIndex__0.log
./49/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlDropDatabaseAndSchedule__2.log
./49/archive/build/debug-clang14-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAddColumn__0.log
```

I looked into the logs to find that all of these are coming from master.  The PgIndexBackfillTest.MasterLeaderStepdown test appears to have gotten it on the new master leader after stepdown.

#### colocated tables

For colocation to possibly hit this error, see issue #14239.

**Comment by jasonyb** [comment] 2022-10-19 20:23
Hit this master fatal

```
[m-2] F1019 12:59:52.757704 113604 tablet_metadata.cc:987] Table 000000010000300080000000000004e7 already exists. New table info: table_id: "000000010000300080000000000004e7" table_name: "pg_proc" table_type: PGSQL_TABLE_TYPE schema {...
```

when running my own test (notice the long time taken: 601s)

```
PASSED: iteration 274, 54 sec
[2022-10-19T13:09:45 common-test-env.sh:1189 did_test_succeed] Test failure reason: exit code: 1
FAILED: iteration 245, 601 sec; test log path: /path/to/logs/repeat_unit_test/pg_backends-test/PgBackendsTest.LeaderChangeInFlightNegative/2022-10-19T12_02_39/245.log.gz
PASSED: iteration 275, 56 sec
```

A clue: this was around the time my system was clogged: java build on one terminal was stuck, and a pager on another terminal was unresponsive.

Logs can be provided upon request.

**Comment by frozenspider** [comment] 2023-01-16 13:09
@jasonyb, could you please check if this still happens with the reworked colocation implementation? Since it's now pretty much a regular DB with a default tablegroup, I assume there should be no difference between colocated and non-colocated DB creation (not that I have any idea why `pg_proc` was erroring out in colocated case only though).

**Comment by jasonyb** [comment] 2023-01-24 23:50
@frozenspider

> Since it's now pretty much a regular DB with a default tablegroup

Can you be specific when this is?  Jenkins still shows failures as recent as today.  Most failures are in debug build and are about the sys catalog tablet, not colocation.

```
tests-integration-tests__twodc_ysql-test/TwoDCYSqlTestConsistentTransactionsTest_ConsistentTransactionsWithApplyDisabled.log
tests-integration-tests__twodc_ysql-test/TwoDCYSqlTestConsistentTransactionsTest_LargeTransaction.log
tests-integration-tests__twodc_ysql-test/TwoDCYSqlTestConsistentTransactionsTest_NonTransactionalWorkload.log
tests-integration-tests__xcluster_safe_time-itest/XClusterConsistencyTest_LoginWithNoSafeTime.log
tests-pgwrapper__pg_mini-test/PgMiniTest_DropAllTablesInTablegroup.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_FailAfterMigration__0.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_FailAfterMigration__1.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAddCheckConstraint__0.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAddCheckConstraint__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlAlterTableSetOwner__0.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlCreateIndex__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlRenameTable__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequencePartialCleanupAfterRestore__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSequenceUndoDropSequence__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSetDefault__1.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_PgsqlSetNotNull__2.log
tests-tools__yb-admin-snapshot-schedule-test/Colocation__YbAdminSnapshotScheduleTestWithYsqlParam_Pgsql__0.log
tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_PgsqlDisableTablegroup.log
tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_PgsqlTestTruncateDisallowedWithPitr.log
tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_RestoreDroppedTablegroup.log
tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_RestoreWithTwoTablegroups.log
tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_TablegroupGCAfterRestore.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.FailAfterMigration_0__error.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.FailAfterMigration_0__spark_stderr.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlAddCheckConstraint_0__error.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlAddCheckConstraint_0__spark_stderr.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequencePartialCleanupAfterRestore_2__error.log
tests-tools_yb-admin-snapshot-schedule-test__Colocation_YbAdminSnapshotScheduleTestWithYsqlParam.PgsqlSequencePartialCleanupAfterRestore_2__spark_stderr.log
```

**Comment by yifanguan** [comment] 2023-02-03 19:26
seems to be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/3687. Suffering from tserver rpc retry.

**Closed** 2023-02-16 15:36 UTC
Labels: kind/bug, area/ysql, priority/high
