### ISSUE TITLE
CustomerMetricsPanel in TableDetail may be broken

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#5361] opened 2020-08-11 00:31 UTC
at /universes/{universe-id}/tables/{table-id}

clicking on the "metrics" tab gives:
```
react-dom.development.js:11143 Uncaught TypeError: Cannot read property 'title' of undefined
    at GraphPanel.render (GraphPanel.js:230)
    at finishClassComponent (react-dom.development.js:17097)
    at updateClassComponent (react-dom.development.js:17050)
    at beginWork (react-dom.development.js:18510)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:291)
    at beginWork$1 (react-dom.development.js:23052)
    at performUnitOfWork (react-dom.development.js:22016)
    at workLoopSync (react-dom.development.js:21992)
    at performSyncWorkOnRoot (react-dom.development.js:21610)
    at react-dom.development.js:11130
    at unstable_runWithPriority (scheduler.development.js:656)
    at runWithPriority$1 (react-dom.development.js:11076)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11125)
    at flushSyncCallbackQueue (react-dom.development.js:11113)
    at scheduleUpdateOnFiber (react-dom.development.js:21053)
    at Object.enqueueSetState (react-dom.development.js:12675)
    at Transition.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:464)
    at Transition.safeSetState (Transition.js:388)
    at Transition.js:367
    at nextCallback (Transition.js:400)
```

It looks like maybe the issue is that `graphPanelTypes` in `CustomerMetricsPanel` specifies `tserver_table` data type but `panelTypes` in `GraphPanel` has no such corresponding key

**Comment by bmatican** [comment] 2020-09-21 21:44
Was talking to @SergeyPotachev turns out this traces back to https://phabricator.dev.yugabyte.com/D9051

@Arnav15 any reason why you removed the per-table metric keys in that diff?

**Comment by sshev** [comment] 2020-09-21 22:08
This one seems to be a duplicate of https://github.com/yugabyte/yugabyte-db/issues/5582

**Closed** 2020-09-22 16:20 UTC
Labels: area/platform, area/ui
