### ISSUE TITLE
[YSQL] Invalid value of enum ValueType (duplicate of #945)

### ISSUE THREAD

**Issue by jeffreims** [YugaByte/yugabyte-db#1101] opened 2019-04-01 11:03 UTC
version_number: 1.2.0.2
3 master nodes
3 tablet nodes

I tried YSQL for the first time after running YEDIS for a while,

After setting up a table I tried to insert some test data, 

Inserting took >30 seconds, I stopped to process and tried again. This time I got EOF back from the server.
Checking the yugabye dashboard I saw the 2 of the 3 tablet nodes were dead.

These nodes both had the following log:

`cat yb-tserver.FATAL.details.2019-04-01T10_34_41.pid3157.txt
F20190401 10:34:41 ../../src/yb/util/enums.h:176] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
   @     0x7f7833a770a2  yb::LogFatalHandlerSink::send()
   @     0x7f783100c666  google::LogMessage::SendToLog()
   @     0x7f7831009d5a  google::LogMessage::Flush()
   @     0x7f783100cc89  google::LogMessageFatal::~LogMessageFatal()
   @     0x7f7839ce2e34  yb::FatalInvalidEnumValueInternal<>()
   @     0x7f7839cdc5c3  yb::docdb::PrimitiveValue::AppendToKey()
   @     0x7f7839c9842f  yb::docdb::DocKey::AppendTo()
   @     0x7f7839c9879d  yb::docdb::DocKey::EncodeAsRefCntPrefix()
   @     0x7f7839cd6c0e  yb::docdb::PgsqlWriteOperation::Init()
   @     0x7f783a759c3a  yb::tablet::Tablet::KeyValueBatchFromPgsqlWriteBatch()
   @     0x7f783a75a282  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations()
   @     0x7f783a77a387  yb::tablet::TabletPeer::WriteAsync()
   @     0x7f783aac3087  yb::tserver::TabletServiceImpl::Write()
   @     0x7f7838501987  yb::tserver::TabletServerServiceIf::Handle()
   @     0x7f7835ad3c2a  yb::rpc::ServicePoolImpl::Handle()
   @     0x7f7835ad219a  yb::rpc::TasksPool<>::WrappedTask::Run()
   @     0x7f7835adad9e  yb::rpc::(anonymous namespace)::Worker::Execute()
   @     0x7f7833ae17c6  yb::Thread::SuperviseThread()
   @     0x7f783c185694  start_thread
   @     0x7f782f0a441d  __clone
   @              (nil)  (unknown)`

**Comment by ajcaldera1** [comment] 2019-04-01 13:51
Can you attach a sample schema and INSERT statement that caused this issue?

**Comment by jeffreims** [comment] 2019-04-01 14:12
@ajcaldera1 Yes,

Table
tasks

Column | ID | Type
-- | -- | --
id | int32 NOT NULL PARTITION KEY
name | string NULLABLE NOT A PARTITION KEY
content | binary NULLABLE NOT A PARTITION KEY
interval | int32 NULLABLE NOT A PARTITION KEY
lastclaimed | int64 NULLABLE NOT A PARTITION KEY
disabled | bool NULLABLE NOT A PARTITION KEY
jobname | string NULLABLE NOT A PARTITION KEY

`INSERT INTO tasks (name, interval, jobname) VALUES ('test', 1200, 'test-job');`

**Comment by robertpang** [comment] 2019-04-01 16:14
This should be the same issue as #945 when a NULL value is inserted into a column that is indexed. We should have a fix very soon.

**Comment by robertpang** [comment] 2019-04-01 16:37
Duplicate of #945.

**Comment by robertpang** [comment] 2019-04-02 20:28
The issue is fixed in commit [1dedcd1](https://github.com/YugaByte/yugabyte-db/commit/1dedcd1f4481d50a32517f3af2b4d5e188abf17d).

**Closed by robertpang** 2019-04-02 20:28 UTC
Labels: ysql
