### ISSUE TITLE
[YSQL] Set default_transaction_isolation to repeatable read

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1529] opened 2019-06-10 21:53 UTC
Since we default to repeatable read in YSQL, set `default_transaction_isolation` to repeatable read.

Currently, if you run `SHOW default_transaction_isolation` in ysqlsh, it shows `read committed`.

**Comment by m-iancu** [comment] 2022-03-14 03:13
duplicate of #2140.

**Closed by m-iancu** 2022-03-14 03:13 UTC
Labels: area/ysql
