### ISSUE TITLE
CL.ONE (read from followers) serving reads before node is fully caught up

### ISSUE THREAD

**Issue by rameshpoti** [YugaByte/yugabyte-db#456] opened 2018-08-31 00:03 UTC
CassandraKeyValue sample app in Read only load and when a node is restarted seeing the following error when the node joins back to the cluster.

2018-08-30 23:48:40,389 [FATAL|com.yugabyte.sample.apps.CassandraKeyValue|CassandraKeyValue] Read key: key:33191 expected 1 row in result, got 0

Initial assumption : Until a "follower" is caught up replaying its local RAFT log, it shouldn't serve reads. Until then it should just redirect to one of the other two peers. (edited)

**Comment by kmuthukk** [comment] 2018-08-31 00:11
Thanks @rameshpoti for reporting this issue. Will keep you posted once the fix is available.

**Comment by amitanandaiyer** [comment] 2018-09-12 18:07
This seems to be caused by the follower not resetting safe_time_to_read correctly.

We seem to have been setting safe_time_to_read based on the flushed sst files. Not accounting for the committed entries in rocksdb that haven't been flushed. 

But, the committed entries are present in the Write Ahead Log and replayed upon restart. The fix is to update the initial safe_time_to_read based on the applied entries from WAL in addition to the flushed files.

**Closed** 2018-09-18 18:58 UTC
Labels: bug
