### ISSUE TITLE
[DocDB] TabletSplitExternalMiniClusterITest.CrashMasterDuringSplit test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12576] opened 2022-05-19 18:47 UTC
Jira Link: [[DB-447]](https://yugabyte.atlassian.net/browse/DB-447)
### Description

Need to fix.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-447]: https://yugabyte.atlassian.net/browse/DB-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2022-09-17 19:42
@arybochkin , Is this a duplicate of https://github.com/yugabyte/yugabyte-db/issues/12572 ?

**Comment by rthallamko3** [comment] 2022-09-23 00:00
Most likely a DUP of #12572 . No additional hits since this was resolved.
```

<div id="test-trend-table_wrapper" class="dataTables_wrapper no-footer" style="box-sizing: border-box; position: relative; clear: both; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

09/07/2022 14:33 | 8ab64307d~..8ab64307d | 1 | -1
-- | -- | -- | --
09/06/2022 08:03 | c1d676580~..ee69bbf80 | 2 | 0

</div><br class="Apple-interchange-newline">09/07/2022 14:33	[8ab64307d~..8ab64307d](https://github.com/yugabyte/yugabyte-db/compare/8ab64307d0b3b549ec94af2da9446d9739ab1caf~...8ab64307d0b3b549ec94af2da9446d9739ab1caf)	1	-1
09/06/2022 08:03	[c1d676580~..ee69bbf80](https://github.com/yugabyte/yugabyte-db/compare/c1d676580933d34bd34fcbb7e86099dcd9e0eb99~...ee69bbf804117b0c76c97077925d106e6c1a47be)	2	0
```

**Closed by rthallamko3** 2022-09-23 00:00 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/medium
