### ISSUE TITLE
Add ability to specify log name

### ISSUE THREAD

**Issue by adilakram87** [yugabyte/yugabyte-db#7067] opened 2021-02-02 19:41 UTC
https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#logging-flags

We support several logging flags for management of logs including directing to stderr. It would be beneficial to add log filename directly instead of generic default. 

For example flag names:

--logfilename

**Comment by adilakram87** [comment] 2021-02-02 19:47
One intentional consequence of naming the file directly would be to give up log rotation by t-server and instead log rotation would be managed by an external utility such as logrotate.

**Comment by tylarb** [comment] 2021-02-02 21:44
Another note, for consideration, is how Postgres holds open a file handle for it's log, then switches to a new log on SIGHUP

**Comment by ddorian** [comment] 2021-02-03 07:56
> One intentional consequence of naming the file directly would be to give up log rotation by t-server and instead log rotation would be managed by an external utility such as logrotate.

Can we flag this as duplicate of https://github.com/yugabyte/yugabyte-db/issues/3604 ?

**Comment by tylarb** [comment] 2021-02-03 20:42
@ddorian  good idea. Thanks for the find there.

**Closed by tylarb** 2021-02-03 20:42 UTC
Labels: area/docdb
