### ISSUE TITLE
[YSQL] Failed while visiting tablets in sys catalog: Cannot add a table to a colocation group for tablet: place is taken by a table

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#13644] opened 2022-08-16 10:04 UTC
Jira Link: [DB-3212](https://yugabyte.atlassian.net/browse/DB-3212)
### Description

Issue occured during stress testing TABLEGROUPS with 3/3 runs.

Scenario - spawn 2xlarge VMs 3RF cluster, create 5 tablegroups, spawn 5*10*100 (batches) workload that will load data to tables.
At some point FATAL occurs

```
F20220816 07:22:59 ../../src/yb/master/catalog_manager.cc:1001] T 00000000000000000000000000000000 P c158b26d1df94b5595435d1103627cbb: Failed to load sys catalog: Corruption (yb/master/catalog_loaders.cc:265): Failed while visiting tablets in sys catalog: Cannot add a table 000033e6000030008000000000004048 (ColocationId: 1838765072) to a colocation group for tablet 6a398db1629e43ff9a9c81084514fe59: place is taken by a table 000033e6000030008000000000004048
    @     0x7fc14e985c1b  google::LogMessage::SendToLog()
    @     0x7fc14e986cd8  google::LogMessage::Flush()
    @     0x7fc14e98715f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc151fc3e7e  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7fc14ec29e5c  yb::ThreadPool::DispatchThread()
    @     0x7fc14ec252fb  yb::Thread::SuperviseThread()
    @     0x7fc14cf9a694  start_thread
    @     0x7fc14c6d741d  __clone
```

**Comment by frozenspider** [comment] 2022-08-18 07:40
Closing as a duplicate of #13167

**Closed by frozenspider** 2022-08-18 07:40 UTC
Labels: kind/bug, duplicate, area/ysql, priority/medium, status/awaiting-triage, qa_automation
