### ISSUE TITLE
[CDCSDK] CDC does not work with tablet splitting which is turned on by default in 2.15

### ISSUE THREAD

**Issue by cdavid** [yugabyte/yugabyte-db#13200] opened 2022-07-07 16:43 UTC
There is a workaround to disable tablet splitting via gflags for PoCs.

**Comment by cdavid** [comment] 2022-07-07 20:53
@bmatican  Thanks, adjusted title.

**Comment by adithya-yb** [comment] 2022-07-08 03:36
This is a duplicate of: https://github.com/yugabyte/yugabyte-db/issues/10935

**Closed by adithya-yb** 2022-07-08 03:36 UTC
