### ISSUE TITLE
[YSQL] [pg_locks] : waitstart time for waiting transaction keeps changing every time pg_locks is queried

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#18603] opened 2023-08-08 09:28 UTC
Jira Link: [DB-7532](https://yugabyte.atlassian.net/browse/DB-7532)
### Description

Steps to repro:

1. Create universe on version 2.19.1.0-b397 with read committed, wait queues and deadlock detection enabled (pg_locks is enabled by default)
2. create table tb(k int primary key, v int);
3. insert into tb values(1,1), (2,2), (3,3);
4. S1: begin; select; select * from tb where k=1 for update;
5. S2: begin; select; select * from tb where k=1 for update;
6. S3: begin; select; select * from tb where k=1 for update;
7. S4: select distinct (ybdetails->'transactionid') as txn_id, waitstart, waitend, granted, database, relation from pg_locks; --notice the waitstart time for waiting transactions
8. wait for some time
9. S4: select distinct (ybdetails->'transactionid') as txn_id, waitstart, waitend, granted, database, relation from pg_locks; --notice the waitstart time for waiting transactions has changed from what was observed in step 7

Seems to me like it is being populated with the time at which pg_locks was populated.

PFA the observed output:
<img width="1019" alt="Screenshot 2023-08-09 at 2 22 06 AM" src="https://github.com/yugabyte/yugabyte-db/assets/96899223/17a79232-71d8-4d35-956e-7b0fc7a0e3f5">

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7532]: https://yugabyte.atlassian.net/browse/DB-7532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment] 2023-12-11 17:15
duplicate of https://github.com/yugabyte/yugabyte-db/issues/20120

**Closed by robertsami** 2023-12-11 17:15 UTC
Labels: kind/bug, area/ysql, priority/medium, QA
