### ISSUE TITLE
Read time already picked DCHECK when inserting into a table with a foreign key

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2780] opened 2019-10-29 21:49 UTC
```
ts1|pid11927|:28624 F20191029 06:17:27 ../../src/yb/client/transaction.cc:250] 180d1cdb-84cb-429d-848d-2fd7e9446719: Read time already picked ({ read: { physical: 1572329847641600 } local_limit: { physical: 1572329847691600 } global_limit: { physical: 1572329847691600 } in_txn_limit: { physical: 1572329847653125 } serial_no: 0 }, but server replied with used read time: { read: { physical: 1572329847659985 } local_limit: { physical: 1572329847709989 } global_limit: { physical: 1572329847709989 } in_txn_limit: <max> serial_no: 0 }
ts1|pid11927|:28624     @     0x7efea1e5a4f0  yb::LogFatalHandlerSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long) (src/yb/util/logging.cc:474)
ts1|pid11927|:28624     @     0x7efea0699975 
ts1|pid11927|:28624     @     0x7efea0697509 
ts1|pid11927|:28624     @     0x7efea0697740 
ts1|pid11927|:28624     @     0x7efea0340a60  yb::client::YBTransaction::Impl::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybridTime const&, yb::Status const&) (src/yb/client/transaction.cc:250)
ts1|pid11927|:28624     @     0x7efea03370ac  yb::client::YBTransaction::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybridTime const&, yb::Status const&) (src/yb/client/transaction.cc:871)
ts1|pid11927|:28624     @     0x7efea02a46b8  yb::client::internal::Batcher::RemoveInFlightOpsAfterFlushing(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::Status const&, yb::client::internal::FlushExtraResult) (src/yb/client/batcher.cc:641)
ts1|pid11927|:28624     @     0x7efea029401b  yb::client::internal::AsyncRpc::Finished(yb::Status const&) (src/yb/client/async_rpc.cc:167)
ts1|pid11927|:28624     @     0x7efea029b86e 
ts1|pid11927|:28624     @     0x7efe9faab9e7  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
ts1|pid11927|:28624     @     0x7efe9faab9e7  yb::rpc::OutboundCall::InvokeCallbackSync() (src/yb/rpc/outbound_call.cc:384)
ts1|pid11927|:28624     @     0x7efe9faabcbe  yb::rpc::InvokeCallbackTask::Run() (src/yb/rpc/outbound_call.cc:165)
ts1|pid11927|:28624     @     0x7efe9fb055c6  Execute (src/yb/rpc/thread_pool.cc:99)
ts1|pid11927|:28624     @     0x7efe9fb00fee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
ts1|pid11927|:28624     @     0x7efe9fb00fee  __call<void, 0ul> (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
ts1|pid11927|:28624     @     0x7efe9fb00fee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
ts1|pid11927|:28624     @     0x7efe9fb00fee  _M_invoke (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
ts1|pid11927|:28624     @     0x7efea1edd6b4  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
ts1|pid11927|:28624     @     0x7efea1edd6b4  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:741)
ts1|pid11927|:28624     @     0x7efea150afc3 
ts1|pid11927|:28624     @     0x7efea144c9bc 
ts1|pid11927|:28624     @ 0xffffffffffffffff 
ts1|pid11927|:28624 
ts1|pid11927|:28624 *** Check failure stack trace: ***
ts1|pid11927|:28624     @     0x7efea1e58ab6  DumpStackTraceAndExit (src/yb/util/logging.cc:166)
ts1|pid11927|:28624     @     0x7efea06979bc 
ts1|pid11927|:28624     @     0x7efea0699a1c 
ts1|pid11927|:28624     @     0x7efea0697509 
ts1|pid11927|:28624     @     0x7efea0697740 
ts1|pid11927|:28624     @     0x7efea0340a60  yb::client::YBTransaction::Impl::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybridTime const&, yb::Status const&) (src/yb/client/transaction.cc:250)
ts1|pid11927|:28624     @     0x7efea03370ac  yb::client::YBTransaction::Flushed(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::ReadHybridTime const&, yb::Status const&) (src/yb/client/transaction.cc:871)
ts1|pid11927|:28624     @     0x7efea02a46b8  yb::client::internal::Batcher::RemoveInFlightOpsAfterFlushing(std::vector<shared_ptr<yb::client::internal::InFlightOp>, std::allocator<shared_ptr<yb::client::internal::InFlightOp> > > const&, yb::Status const&, yb::client::internal::FlushExtraResult) (src/yb/client/batcher.cc:641)
ts1|pid11927|:28624     @     0x7efea029401b  yb::client::internal::AsyncRpc::Finished(yb::Status const&) (src/yb/client/async_rpc.cc:167)
ts1|pid11927|:28624     @     0x7efea029b86e 
ts1|pid11927|:28624     @     0x7efe9faab9e7  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
ts1|pid11927|:28624     @     0x7efe9faab9e7  yb::rpc::OutboundCall::InvokeCallbackSync() (src/yb/rpc/outbound_call.cc:384)
ts1|pid11927|:28624     @     0x7efe9faabcbe  yb::rpc::InvokeCallbackTask::Run() (src/yb/rpc/outbound_call.cc:165)
ts1|pid11927|:28624     @     0x7efe9fb055c6  Execute (src/yb/rpc/thread_pool.cc:99)
ts1|pid11927|:28624     @     0x7efe9fb00fee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
ts1|pid11927|:28624     @     0x7efe9fb00fee  __call<void, 0ul> (gcc/5.5.0_4/include/c++/5.5.0/functional:1074)
ts1|pid11927|:28624     @     0x7efe9fb00fee  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:1133)
ts1|pid11927|:28624     @     0x7efe9fb00fee  _M_invoke (gcc/5.5.0_4/include/c++/5.5.0/functional:1871)
ts1|pid11927|:28624     @     0x7efea1edd6b4  std::function<void ()>::operator()() const (gcc/5.5.0_4/include/c++/5.5.0/functional:2267)
ts1|pid11927|:28624     @     0x7efea1edd6b4  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:741)
ts1|pid11927|:28624     @     0x7efea150afc3 
ts1|pid11927|:28624     @     0x7efea144c9bc 
ts1|pid11927|:28624     @ 0xffffffffffffffff 
ts1|pid11927|:28624 2019-10-29 06:17:28.423 UTC [11991] LOG:  server process (PID 12366) was terminated by signal 6: Aborted
ts1|pid11927|:28624 2019-10-29 06:17:28.423 UTC [11991] DETAIL:  Failed process was running: INSERT INTO FKTABLE VALUES (2, 3);
```

**Comment by hectorgcr** [comment] 2019-10-29 22:09
Duplicate of #2747

**Closed by hectorgcr** 2019-10-29 22:09 UTC
