### ISSUE TITLE
docker quick-start fails with timeout in multiple explore ysql steps

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#1288] opened 2019-04-30 18:46 UTC
Version
`version 1.2.6.0 build 3 revision b37a303fe36492011dbb9eae018b6f9547b1aa9a build_type RELEASE built at 20 Apr 2019 04:34:28 UTC`

Followed instructions on https://docs.yugabyte.com/latest/quick-start/explore-ysql/#docker

1. Timeout error at the `\i schema.sql` step (CREATE TABLEs in general felt very slow)
```
yb_demo=# \i 'schema.sql';
CREATE TABLE products(
  id         bigint PRIMARY KEY,
  created_at text,
  category   text,
  ean        text,
  price      float,
  rating     float,
  title      text,
  vendor     text
);
CREATE TABLE
CREATE TABLE users(
  id         bigint PRIMARY KEY,
  created_at text,
  name       text,
  email      text,
  address    text,
  city       text,
  state      text,
  zip        text,
  birth_date text,
  latitude   float,
  longitude  float,
  password   text,
  source     text
);
CREATE TABLE
CREATE TABLE orders(
  id         bigint PRIMARY KEY,
  created_at text,
  user_id    bigint,
  product_id bigint,
  discount   float,
  quantity   int,
  subtotal   float,
  tax        float,
  total      float
);
psql:schema.sql:38: ERROR:  Timed out: Read(tablet: cf812a5e2704471aaca859480cb0a45a, num_ops: 1, num_attempts: 343, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 251114.754s (now: 251114.773s): Leader not ready to serve requests. (yb/consensus/consensus.cc:137): Leader not yet replicated NoOp to be ready to serve requests (error 24)
CREATE TABLE reviews(
  id         bigint PRIMARY KEY,
  created_at text,
  reviewer   text,
  product_id bigint,
  rating     int,
  body       text
);
CREATE TABLE
```
All the tables were indeed created.
```
yb_demo=# \d
          List of relations
 Schema |   Name   | Type  |  Owner   
--------+----------+-------+----------
 public | orders   | table | postgres
 public | products | table | postgres
 public | reviews  | table | postgres
 public | users    | table | postgres
(4 rows)
```

2. Loaded the products and users tables fine. But failed with timeouts when inserting into the orders table.
```
yb_demo=# \i 'data/orders.sql'
INSERT INTO orders(id,created_at,discount,product_id,quantity,subtotal,tax,total,user_id) VALUES (1,'2019-02-11T21:40:27.892Z',NULL,14,2,37.648145389078365,2.07,39.718145389078366,1);
INSERT 0 1
INSERT INTO orders(id,created_at,discount,product_id,quantity,subtotal,tax,total,user_id) VALUES (2,'2018-05-15T08:04:04.580Z',NULL,123,3,110.93145648834248,6.1,117.0376564084763,1);
INSERT 0 1
INSERT INTO orders(id,created_at,discount,product_id,quantity,subtotal,tax,total,user_id) VALUES (3,'2019-12-06T22:22:48.544Z',6.416679208849759,105,2,52.723521442619514,2.9,55.62208681964182,1);
psql:data/orders.sql:3: ERROR:  Timed out: Write(tablet: cf812a5e2704471aaca859480cb0a45a, num_ops: 1, num_attempts: 344, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 251603.317s (now: 251603.649s): Leader not ready to serve requests. (yb/consensus/consensus.cc:137): Leader not yet replicated NoOp to be ready to serve requests (error 24)
INSERT INTO orders(id,created_at,discount,product_id,quantity,subtotal,tax,total,user_id) VALUES (4,'2019-08-22T16:30:42.392Z',NULL,94,6,109.21864156655383,6.01,115.2207354961295,1);
INSERT 0 1
INSERT INTO orders(id,created_at,discount,product_id,quantity,subtotal,tax,total,user_id) VALUES (5,'2018-10-10T03:34:47.309Z',NULL,132,5,127.88197029833711,7.03,134.94192935296473,1);
```

**Comment by m-iancu** [comment] 2019-04-30 19:54
It looks like the root cause is the "Leader not yet replicated NoOp" error. 
We just landed a fix for it in f3bf3f205f573193 which should be included in the next release so closing this.

**Closed by m-iancu** 2019-04-30 19:54 UTC
