### ISSUE TITLE
[YSQL][SQLancer] FATAL: Failed while visiting tablets in sys catalog: System catalog snapshot is corrupted or built using different build type: Tablegroup 0000555e00003000800000000000584f already exists

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#13810] opened 2022-08-30 06:02 UTC
Jira Link: [DB-3323](https://yugabyte.atlassian.net/browse/DB-3323)
### Description

Fatal occurs during SQLancer NoREC test evalaution. Log from master:

```
F0830 04:27:21.811143 29862 catalog_manager.cc:1013] T 00000000000000000000000000000000 P 1d3414b9a4d2407bb2c442e223e097f3: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: System catalog snapshot is corrupted or built using different build type: Tablegroup 0000555e00003000800000000000584f already exists
```

**Comment by frozenspider** [comment] 2022-12-21 16:58
Closing this as a duplicate of #13132

**Closed by frozenspider** 2022-12-21 16:58 UTC
Labels: kind/bug, area/ysql, kind/failing-test, priority/medium
