### ISSUE TITLE
[YSQL][Colocation]: implicit-explicit and explicit-implicit conflicts not detected in colocated tables

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14590] opened 2022-10-21 07:28 UTC
Jira Link: [DB-3962](https://yugabyte.atlassian.net/browse/DB-3962)
### Description

Version: 2.17.0.0-b1
Observed that waiting behaviour is absent for implicit-explicit and explicit-implicit types of conflicts for colocated tables.

Steps to repro:

```
1. CREATE DATABASE colxpl WITH COLOCATED = true;
2. \c colxpl
3. create table t1(k int, v int);
4. insert into t1 values(1, 11);
5. insert into t1 values(2, 12);
6. T1:
    a. start transaction;
    b. update t1 set v=111 where k=1;
7. T2:
    a. start transaction;
    b. select * from t1 where k=1 for update;
```

You'll notice that T2 doesn't wait for T1, for all combinations of implicit-explicit & explicit-implicit locking.

**Comment by robertsami** [comment] 2022-11-03 17:00
note that we dont see conflicts with pessimistic locking disabled, so this issue is not specific to pessimistic locking

**Comment by robertsami** [comment] 2022-11-03 17:00
note - this is likely related to https://github.com/yugabyte/yugabyte-db/issues/14350

**Comment by robertsami** [comment] 2022-11-03 17:01
note this is likely related to https://github.com/yugabyte/yugabyte-db/issues/14569

**Comment by robertsami** [comment] 2023-01-17 19:19
duplicate of https://github.com/yugabyte/yugabyte-db/issues/14569

**Closed by robertsami** 2023-01-17 19:19 UTC
Labels: kind/bug, priority/high, QA, colocation_blocker
