### ISSUE TITLE
[DocDB] TabletSplitExternalMiniClusterITest.CrashesAfterChildLogCopy test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12577] opened 2022-05-19 18:48 UTC
Jira Link: [[DB-448]](https://yugabyte.atlassian.net/browse/DB-448)
### Description

Need to fix.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-448]: https://yugabyte.atlassian.net/browse/DB-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2022-09-17 19:43
@arybochkin , Is this a duplicate of https://github.com/yugabyte/yugabyte-db/issues/12572 ?

**Comment by rthallamko3** [comment] 2022-09-22 23:59
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TabletSplitExternalMiniClusterITest&fail_tag=all&name=CrashesAfterChildLogCopy&platform=linux

**Comment by rthallamko3** [comment] 2022-10-20 00:08
Detective report looks clean. Closing this for now.

**Closed by rthallamko3** 2022-10-20 00:08 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/medium
