### ISSUE TITLE
Allow a DoNotRetry flag at the proxy layer

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#114] opened 2018-03-22 00:07 UTC
For non-idempotent operations, it may be useful to expose a do-not-retry flag, so that we avoid the situation where we are not sure if the operation gets applied exactly-once or could possibly have been applied multiple times.

**Comment by kmuthukk** [comment] 2018-12-05 08:44
@rkarthik007 , @ttyusupov :

I believe this is a duplicate of the already fixed issue - https://github.com/YugaByte/yugabyte-db/issues/537

Please confirm.

**Comment by rkarthik007** [comment] 2018-12-05 13:03
Yup, this is fixed. Will close.

**Closed** 2018-12-05 13:03 UTC
Labels: bug
