### ISSUE TITLE
[YSQL] Noticed AbortSubTransaction PG core dump in stress test

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#20214] opened 2023-12-07 08:17 UTC
Jira Link: [DB-9171](https://yugabyte.atlassian.net/browse/DB-9171)
### Description

Observed below core dump in stress test
```
(lldb) target create "/home/yugabyte/yb-software/yugabyte-2.21.0.0-b303-centos-x86_64/postgres/bin/postgres" --core "/home/yugabyte/cores/core_138007_1701660968_!home!yugabyte!yb-software!yugabyte-2.21.0.0-b303-centos-x86_64!postgres!bin!postgres"
Core file '/home/yugabyte/cores/core_138007_1701660968_!home!yugabyte!yb-software!yugabyte-2.21.0.0-b303-centos-x86_64!postgres!bin!postgres' (x86_64) was loaded.
(lldb) bt all
* thread #1, name = 'postgres', stop reason = signal SIGABRT
  * frame #0: 0x00007f722d088aff libc.so.6`raise + 271
    frame #1: 0x00007f722d05bea5 libc.so.6`abort + 295
    frame #2: 0x000056186828b1fc postgres`errfinish(dummy=<unavailable>) at elog.c:815:3
    frame #3: 0x00005618682935ef postgres`elog_start(filename="", lineno=5159, funcname=<unavailable>) at elog.c:1698:3
    frame #4: 0x0000561867c882e1 postgres`AbortSubTransaction at xact.c:5158:3
    frame #5: 0x0000561867c894f2 postgres`AbortCurrentTransaction at xact.c:3471:4
    frame #6: 0x00005618680d89a3 postgres`PostgresMain(argc=<unavailable>, argv=<unavailable>, dbname=<unavailable>, username=<unavailable>) at postgres.c:5176:3
    frame #7: 0x0000561868019fd4 postgres`BackendRun(port=0x000004523fc085a0) at postmaster.c:4722:2
    frame #8: 0x00005618680191a2 postgres`ServerLoop [inlined] BackendStartup(port=0x000004523fc085a0) at postmaster.c:4386:3
    frame #9: 0x0000561868019103 postgres`ServerLoop at postmaster.c:1773:7
    frame #10: 0x00005618680142c2 postgres`PostmasterMain(argc=25, argv=0x000004523fd0a1a0) at postmaster.c:1429:11
```
More details are in respective JIRA
    

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9171]: https://yugabyte.atlassian.net/browse/DB-9171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment] 2024-01-17 17:15
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/18192

**Closed** 2024-08-08 17:38 UTC
Labels: kind/bug, area/ysql, priority/medium, qa_automation, qa_stress, QA_Blocker
