### ISSUE TITLE
yb-admin list_cdc_streams shows incorrect results

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#9087] opened 2021-06-24 19:05 UTC
Adding replication with yb-admin setup_universe_replication and the table(s) being configured for replication don't exist in the consumer database breaks yb-admin list_cdc_streams.

Producer:
```
yugabyte=# \d
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | foo  | table | yugabyte
 public | foo2 | table | yugabyte
 public | foo3 | table | yugabyte
```

Consumer:
```
yugabyte=# \d
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | foo  | table | yugabyte
 public | foo2 | table | yugabyte
```

foo3 is missing in the Consumer.

Delete replication:
```
yb-admin -master_addresses 10.11.1.235:7100,10.11.2.75:7100,10.11.3.14:7100 delete_universe_replication f9f040a6-e6fa-4fad-ad65-461d13662368 
```

Add replication for the 3 tables:
```
yb-admin -master_addresses 10.11.1.235:7100,10.11.2.75:7100,10.11.3.14:7100  setup_universe_replication f9f040a6-e6fa-4fad-ad65-461d13662368 10.10.1.32:7100,10.10.2.113:7100,10.10.3.118:7100 000030af000030008000000000004000,000030af000030008000000000004005,000030af00003000800000000000400a
```

Listing streams:
```
yb-admin list_cdc_streams -master_addresses 10.10.1.32:7100,10.10.2.113:7100,10.10.3.118:7100
CDC Streams: 
```

Removing foo3 from replication:
```
yb-admin -master_addresses 10.11.1.235:7100,10.11.2.75:7100,10.11.3.14:7100 delete_universe_replication f9f040a6-e6fa-4fad-ad65-461d13662368 

yb-admin -master_addresses 10.11.1.235:7100,10.11.2.75:7100,10.11.3.14:7100  setup_universe_replication f9f040a6-e6fa-4fad-ad65-461d13662368 10.10.1.32:7100,10.10.2.113:7100,10.10.3.118:7100 000030af000030008000000000004000,000030af000030008000000000004005

yb-admin list_cdc_streams -master_addresses 10.10.1.32:7100,10.10.2.113:7100,10.10.3.118:7100
CDC Streams: 
streams {
  stream_id: "d34e21c0b4e1472ca0f0e81ab690c799"
  table_id: "000030af000030008000000000004000"
  options {
    key: "record_format"
    value: "WAL"
  }
  options {
    key: "record_type"
    value: "CHANGE"
  }
}
streams {
  stream_id: "00e3579ac9bf45a1a65c6bcd558285a7"
  table_id: "000030af000030008000000000004005"
  options {
    key: "record_format"
    value: "WAL"
  }
  options {
    key: "record_type"
    value: "CHANGE"
  }
}
```

**Comment by hulien22** [comment] 2021-06-24 19:17
`list_cdc_streams` is working properly, the issue is that `setup_universe_replication` errors out from the missing table, and thus replication is not properly setup (for any of the tables) and there are then no streams to show.

The main problem here is that the `setup_universe_replication` failure is not shown to the user, and so the empty `list_cdc_streams` feels unexpected. 

This will be fixed by #8757 , so closing this issue for now.

**Closed by hulien22** 2021-06-24 19:17 UTC
Labels: area/cdc
