### ISSUE TITLE
TSAN failure in MasterPartitionedTest.CauseMasterLeaderStepdownWithTasksInProgress

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3081] opened 2019-12-06 00:50 UTC

**Comment by bmatican** [comment] 2019-12-06 06:46
`Location is global 'fLI::FLAGS_slowdown_master_async_rpc_tasks_by_ms' of size 4 at 0x7f37cacafa84 (libmaster.so+0x000000548a84)`

Seems like we just need some Get/Set atomic for this test.

**Comment by bmatican** [comment] 2020-04-17 23:24
Closing this as duplicate of #2647

**Closed by bmatican** 2020-04-17 23:24 UTC
Labels: area/docdb, kind/bug, priority/high
