### ISSUE TITLE
[YSQL] Flaky unit test: PgCatalogVersionTest.RecycleManyDatabases 

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18153] opened 2023-07-10 11:22 UTC
Jira Link: [DB-7193](https://yugabyte.atlassian.net/browse/DB-7193)
### Description

Unit test `PgCatalogVersionTest.RecycleManyDatabases ` has been flaky since it was introduced.
[Stability report](https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=PgCatalogVersionTest&fail_tag=all&name=RecycleManyDatabases&num_commits=500&platform=linux)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7193]: https://yugabyte.atlassian.net/browse/DB-7193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment] 2023-07-19 23:36
duplicate of #17849

**Closed** 2023-07-19 23:36 UTC
Labels: kind/bug, area/ysql, priority/medium
