### ISSUE TITLE
[YSQL] Report table sizes in the \d+ ysqlsh (psql) command

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1501] opened 2019-06-07 21:30 UTC
Jira Link: [DB-1806](https://yugabyte.atlassian.net/browse/DB-1806)
```
postgres=# \d+
                              List of relations
 Schema |         Name          |   Type   |  Owner   |  Size   | Description
--------+-----------------------+----------+----------+---------+-------------
 public | part_drawings         | table    | postgres | 0 bytes |
 public | parts                 | table    | postgres | 0 bytes |
 public | parts_part_id_seq     | sequence | postgres | 0 bytes |
 public | vendor_parts          | table    | postgres | 0 bytes |
 public | vendors               | table    | postgres | 0 bytes |
 public | vendors_vendor_id_seq | sequence | postgres | 0 bytes |
(6 rows)
```

**Comment by croman-skyhook** [comment] 2021-06-07 15:01
Has there been any progress on this?

**Comment by sushantrmishra** [comment] 2022-08-24 04:51
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/11131

**Closed by sushantrmishra** 2022-08-24 04:51 UTC
Labels: kind/bug, area/ysql, priority/medium
