### ISSUE TITLE
[YSQL] Profile execution nodes to determine why YB is slower than PG

### ISSUE THREAD

**Issue by timothy-e** [yugabyte/yugabyte-db#15611] opened 2023-01-09 17:37 UTC
Jira Link: [DB-4994](https://yugabyte.atlassian.net/browse/DB-4994)
### Description

Postgres scan time is much faster, but even outside of that, Postgres beats Yugabyte in most nodes

[DB-4994]: https://yugabyte.atlassian.net/browse/DB-4994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment] 2023-10-20 06:50
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/16775

**Closed by sushantrmishra** 2023-10-20 06:50 UTC
Labels: kind/enhancement, area/ysql, priority/medium
