### ISSUE TITLE
 Invalid value of enum ValueType 88 during conflict resolution

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#7835] opened 2021-03-27 04:40 UTC
F20210323 22:24:22 ../../src/yb/docdb/primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
    @     0x7f595de26d3c  yb::LogFatalHandlerSink::send()
    @     0x7f595d00acae  google::LogMessage::SendToLog()
    @     0x7f595d007e3a  google::LogMessage::Flush()
    @     0x7f595d00b529  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f59624e1ff0  yb::FatalInvalidEnumValueInternal<>()
    @     0x7f59624db4dd  yb::docdb::PrimitiveValue::AppendToKey()
    @     0x7f5965aae1f5  yb::docdb::DocWriteBatch::SetPrimitiveInternal()
    @     0x7f5965aae7a2  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f5965aaea10  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f5965aaee09  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f5965aaef02  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f5965a3e2db  yb::docdb::QLWriteOperation::ApplyForRegularColumns()
    @     0x7f5965a4adaf  yb::docdb::QLWriteOperation::Apply()
    @     0x7f5965a56754  yb::docdb::ExecuteDocWriteOperation()
    @     0x7f5966a6c201  yb::tablet::DocWriteOperation::DoComplete()
    @     0x7f5966a6dca8  _ZN5boost6detail8function26void_function_obj_invoker1IZN2yb6tablet17DocWriteOperation7DoStartEvEUlRKNS3_6ResultINS3_10HybridTimeEEEE_vSA_E6invokeERNS1_15function_bufferESA_
    @     0x7f5965a32be4  yb::docdb::(anonymous namespace)::ConflictResolver::Resolve()
    @     0x7f5965a3343f  yb::docdb::ResolveOperationConflicts()
    @     0x7f5966a6d270  yb::tablet::DocWriteOperation::DoStart()
    @     0x7f5966a57aa8  yb::tablet::Tablet::StartDocWriteOperation()
    @     0x7f5966a58b64  yb::tablet::Tablet::KeyValueBatchFromQLWriteBatch()
    @     0x7f5966a59729  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations()
    @     0x7f5966a90161  yb::tablet::TabletPeer::WriteAsync()
    @     0x7f5967391610  yb::tserver::TabletServiceImpl::Write()
    @     0x7f5963e4ab5a  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7f595f698fd9  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f595f63dfc4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f595f6aaea8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f595debe6cf  yb::Thread::SuperviseThread()
    @     0x7f59586d4694  start_thread
    @     0x7f5957e1141d  __clone
    @              (nil)  (unknown)

**Comment by CharlotteRose** [comment] 2021-04-06 04:37
We are still seeing these messages: 

```
Running duration (h:mm:ss): 0:00:25
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0402 04:49:28.789283 33799 primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
F0402 04:49:29.198694 33715 primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
F0402 04:49:29.198694 33715 primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.F0402 04:49:29.243697 34882 primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
F20210402 04:49:28 ../../src/yb/docdb/primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
    @     0x7f1616573d3c  yb::LogFatalHandlerSink::send()
    @     0x7f1615757cae  google::LogMessage::SendToLog()
    @     0x7f1615754e3a  google::LogMessage::Flush()
    @     0x7f1615758529  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f161ac2eff0  yb::FatalInvalidEnumValueInternal<>()
    @     0x7f161ac284dd  yb::docdb::PrimitiveValue::AppendToKey()
    @     0x7f161e1fb1f5  yb::docdb::DocWriteBatch::SetPrimitiveInternal()
    @     0x7f161e1fb7a2  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f161e1fba10  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f161e1fbe09  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f161e1fbf02  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f161e18b2db  yb::docdb::QLWriteOperation::ApplyForRegularColumns()
    @     0x7f161e197daf  yb::docdb::QLWriteOperation::Apply()
    @     0x7f161e1a3754  yb::docdb::ExecuteDocWriteOperation()
    @     0x7f161f1b9201  yb::tablet::DocWriteOperation::DoComplete()
    @     0x7f161f1baca8  _ZN5boost6detail8function26void_function_obj_invoker1IZN2yb6tablet17DocWriteOperation7DoStartEvEUlRKNS3_6ResultINS3_10HybridTimeEEEE_vSA_E6invokeERNS1_15function_bufferESA_
    @     0x7f161e17fbe4  yb::docdb::(anonymous namespace)::ConflictResolver::Resolve()
    @     0x7f161e18043f  yb::docdb::ResolveOperationConflicts()
    @     0x7f161f1ba270  yb::tablet::DocWriteOperation::DoStart()
    @     0x7f161f1a4aa8  yb::tablet::Tablet::StartDocWriteOperation()
    @     0x7f161f1a5b64  yb::tablet::Tablet::KeyValueBatchFromQLWriteBatch()
    @     0x7f161f1a6729  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations()
    @     0x7f161f1dd161  yb::tablet::TabletPeer::WriteAsync()
    @     0x7f161fade610  yb::tserver::TabletServiceImpl::Write()
    @     0x7f161c597b5a  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7f1617de5fd9  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f1617d8afc4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f1617df7ea8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f161660b6cf  yb::Thread::SuperviseThread()
    @     0x7f1610e21694  start_thread
    @     0x7f161055e41d  __clone
    @              (nil)  (unknown)

F20210402 04:49:29 ../../src/yb/docdb/primitive_value.cc:425] Invalid value of enum ValueType (full enum type: yb::docdb::ValueType, expression: type_): 88.
    @     0x7f1616573d3c  yb::LogFatalHandlerSink::send()
    @     0x7f1615757cae  google::LogMessage::SendToLog()
    @     0x7f1615754e3a  google::LogMessage::Flush()
    @     0x7f1615758529  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f161ac2eff0  yb::FatalInvalidEnumValueInternal<>()
    @     0x7f161ac284dd  yb::docdb::PrimitiveValue::AppendToKey()
    @     0x7f161e1fb1f5  yb::docdb::DocWriteBatch::SetPrimitiveInternal()
    @     0x7f161e1fb7a2  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f161e1fba10  yb::docdb::DocWriteBatch::SetPrimitive()
    @     0x7f161e1fbe09  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f161e1fbf02  yb::docdb::DocWriteBatch::ExtendSubDocument()
    @     0x7f161e18b2db  yb::docdb::QLWriteOperation::ApplyForRegularColumns()
    @     0x7f161e197daf  yb::docdb::QLWriteOperation::Apply()
    @     0x7f161e1a3754  yb::docdb::ExecuteDocWriteOperation()
    @     0x7f161f1b9201  yb::tablet::DocWriteOperation::DoComplete()
    @     0x7f161f1baca8  _ZN5boost6detail8function26void_function_obj_invoker1IZN2yb6tablet17DocWriteOperation7DoStartEvEUlRKNS3_6ResultINS3_10HybridTimeEEEE_vSA_E6invokeERNS1_15function_bufferESA_
    @     0x7f161e17fbe4  yb::docdb::(anonymous namespace)::ConflictResolver::Resolve()
    @     0x7f161e18043f  yb::docdb::ResolveOperationConflicts()
    @     0x7f161f1ba270  yb::tablet::DocWriteOperation::DoStart()
    @     0x7f161f1a4aa8  yb::tablet::Tablet::StartDocWriteOperation()
    @     0x7f161f1a5b64  yb::tablet::Tablet::KeyValueBatchFromQLWriteBatch()
    @     0x7f161f1a6729  yb::tablet::Tablet::AcquireLocksAndPerformDocOperations()
    @     0x7f161f1dd161  yb::tablet::TabletPeer::WriteAsync()
    @     0x7f161fade610  yb::tserver::TabletServiceImpl::Write()
    @     0x7f161c597b5a  yb::tserver::TabletServerServiceIf::Handle()
    @     0x7f1617de5fd9  yb::rpc::ServicePoolImpl::Handle()
    @     0x7f1617d8afc4  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7f1617df7ea8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7f161660b6cf  yb::Thread::SuperviseThread()
    @     0x7f1610e21694  start_thread
    @     0x7f161055e41d  __clone
    @              (nil)  (unknown)
```

**Comment by CharlotteRose** [comment] 2021-04-06 22:13
@tylarb @mbautin - we can close the other issue. It was opened just one day before and was seen in the same environment.

**Comment by tvesely** [comment] 2021-04-12 20:03
It seems that this issue was caused by inserting `null` into a `map` or `set`. I was able to reproduce this issue with the following two queries:

```sql
create table test.foo(a int primary key, b set(int));
update test.foo set b = {null} where a = 1;
```

```sql
create table test.bar(a int, b map<string,string>);
update test.bar set b =  {null: 'test'} WHERE a = 1;
```

Should the database support sets or maps with nulls?

**Comment by OlegLoginov** [comment] 2021-04-14 16:13
NULL in collections in Cassandra:
MAP:
```
cqlsh:a> create table tab(i int primary key, m map<text,text>);
cqlsh:a>  update tab set m = {null: 'test'} where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
cqlsh:a>  update tab set m = { 'test':null} where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
```
SET:
```
cqlsh:a> create table tab2(i int primary key, s set<text>);
cqlsh:a>  update tab2 set s = { null } where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
```
LIST:
```
cqlsh:a> create table tab3(i int primary key, l list<text>);
cqlsh:a>  update tab3 set l = [ null ] where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
```
FROZEN:
```
cqlsh:a> create table tab4(i int primary key, m frozen<map<text,text>>);
cqlsh:a>  update tab4 set m = { 'test':null} where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
cqlsh:a>  update tab4 set m = { null:'test'} where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"

cqlsh:a> create table tab5(i int primary key, s frozen<set<text>>);
cqlsh:a>  update tab5 set s = { null } where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"

cqlsh:a> create table tab6(i int primary key, l frozen<list<text>>);
cqlsh:a>  update tab6 set l = [ null ] where i = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
```

**Comment by OlegLoginov** [comment] 2021-04-14 16:19
UDT:
```
cqlsh:a> CREATE TYPE test (a int);
cqlsh:a> create table tab7(i int primary key, t test);
cqlsh:a>  update tab7 set t = null where i = 1;
cqlsh:a> select * from tab7;
 i | t
---+---
(0 rows)
cqlsh:a>  update tab7 set t = {a:1} where i = 1;
cqlsh:a> select * from tab7;
 i | t
---+--------
 1 | {a: 1}
(1 rows)
cqlsh:a>  update tab7 set t = null where i = 1;
cqlsh:a> select * from tab7;
 i | t
---+---
(0 rows)
```
FROZEN UDT:
```
cqlsh:a> create table tab8(i int primary key, t frozen<test>);
cqlsh:a>  update tab8 set t = null where i = 1;
cqlsh:a> select * from tab8;
 i | t
---+---
(0 rows)
cqlsh:a>  update tab8 set t = {a:2}  where i = 1;
cqlsh:a> select * from tab8;
 i | t
---+--------
 1 | {a: 2}
(1 rows)
cqlsh:a>  update tab8 set t = null where i = 1;
cqlsh:a> select * from tab8;
 i | t
---+---
(0 rows)
```

**Comment by OlegLoginov** [comment] 2021-06-07 11:34
Fixed by https://github.com/yugabyte/yugabyte-db/commit/790bbf84bb30baeb8c882b02bb39caf454a8d726

**Closed by OlegLoginov** 2021-06-07 11:34 UTC
Labels: area/ycql
