### ISSUE TITLE
 IO being too detrimental?

### ISSUE THREAD

**Issue by nnsgmsone** [yugabyte/yugabyte-db#8258] opened 2021-05-01 00:51 UTC
I think this may lead to extra overhead for io when make raft log and wal together into a log engine, it may lead to io problems unless it is a log engine shared by all raft groups. Here is a benchmark: tested on a 7200 rpm hdd

not share log engine:
```
wkB/s
7292.00
3620.00
8844.00
440.00
9464.00
7452.00
6916.00
7444.00
6292.00
104.00
4716.00
5760.00
```

share log engine:
```
wkB/s
1024.00
25112.00
35140.00
35144.00
35136.00
964.00
35140.00
28.00
35144.00
30136.00
35188.00
```

not share log engine code:
```
package main

import (
    "fmt"
    "os"
)

const (
    Loop  = 100
    Batch = 10000                                                                                                                                                                                                  
)

var data []byte
var fs []*os.File

func init() {
    data = make([]byte, 512)
    fs = make([]*os.File, 10)
    for i := 0; i < 10; i++ {
        fs[i], _ = os.Create(fmt.Sprintf("%v.dat", i))
    }
}

func main() {
    for i := 0; i < Loop; i++ {
        write()
    }
}

func write() {
    for i := 0; i < Batch; i++ {
        fs[i%10].Write(data)
    }
    for _, f := range fs {
        f.Sync()
    }
}
```
share log engine code:
```
package main

import (
    "fmt"
    "os"
)

const (
    Loop  = 100
    Batch = 10000                                                                                                                                                                                                  
)

var data []byte
var fs []*os.File

func init() {
    data = make([]byte, 512)
    fs = make([]*os.File, 2)
    for i := 0; i < 2; i++ {
        fs[i], _ = os.Create(fmt.Sprintf("%v.dat", i))
    }
}

func main() {
    for i := 0; i < Loop; i++ {
        write()
    }
}

func write() {
    for i := 0; i < Batch; i++ {
        fs[0].Write(data)
        fs[1].Write(data)
    }
    fs[0].Sync()
}
```

**Comment by nnsgmsone** [comment] 2021-05-01 00:53
yugabyte is storing logs separately, how is it io burden increase avoided?

**Comment by ddorian** [comment] 2021-05-01 06:51
@nnsgmsone yes, but note that [HDD are NOT supported, SSD are required](https://docs.yugabyte.com/latest/deploy/checklist/#disks). Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/3549, which we're tracking to lower this overhead.

The current way to lower this overhead (while using SSD), is to [use a colocated database](https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_database/#colocated).

**Closed by ddorian** 2021-05-01 06:51 UTC

**Comment by nnsgmsone** [comment] 2021-05-06 02:00
@ddorian  ok, but ssd also has io deterioration, especially when there are many raft groups.

**Comment by ddorian** [comment] 2021-05-06 04:55
see reply here https://github.com/yugabyte/yugabyte-db/issues/3549#issuecomment-833217657
