### ISSUE TITLE
[YSQL] nextval() on sequence retries indefinitely despite possible starvation

### ISSUE THREAD

**Issue by georgeklees** [yugabyte/yugabyte-db#1736] opened 2019-07-09 00:33 UTC
Jira Link: [DB-1745](https://yugabyte.atlassian.net/browse/DB-1745)
The implementation of `nextval()` (specifically `nextval_internal()` in the Postgres code) involves a compare-and-swap: read the old sequence value, increment the local copy of that value, and set the sequence to that incremented value if it currently holds the old value. Because this might fail if the sequence was modified after the read but before the CAS, the function retries the whole process if the write was skipped. But there is no limit on how many retries will happen, so it is theoretically possible that Postgres might be continually starved from completing the write and hang. It would be good to set a limit on how many times the sequence functions will retry before throwing an error.

cc @ndeodhar @hectorgcr

**Comment by m-iancu** [comment] 2022-08-16 16:57
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/13123.

**Closed by m-iancu** 2022-08-16 16:57 UTC
Labels: kind/enhancement, area/ysql, priority/medium
