### ISSUE TITLE
[YSQL] Duplicate - When using SQL statement: count (*) to query the table with range partition mode, the returned value is wrong

### ISSUE THREAD

**Issue by jiaolongxue** [yugabyte/yugabyte-db#6285] opened 2020-11-05 08:40 UTC
**yugabyte-db version 2.3.2**
**3 tservers 3 masters**

step 1:
```
CREATE TABLE ordered_asc(k INT,PRIMARY KEY(k ASC)) SPLIT AT VALUES((10), (20), (30));
```

step 2:
```
yugabyte=# insert into ordered_asc values(1);
INSERT 0 1
yugabyte=# insert into ordered_asc values(2);
INSERT 0 1
yugabyte=# insert into ordered_asc values(3);
INSERT 0 1
yugabyte=# insert into ordered_asc values(4);
INSERT 0 1
yugabyte=# insert into ordered_asc values(5);
yugabyte=# insert into ordered_asc values(6);
INSERT 0 1
yugabyte=# insert into ordered_asc values(7);
INSERT 0 1
yugabyte=# insert into ordered_asc values(100);
INSERT 0 1
yugabyte=# insert into ordered_asc values(120);
```

step 3:
```
yugabyte=# select count(*) from ordered_asc;
 count 
-------
    15
(1 row)
```
**The correct value is 9**

**Comment by ddorian** [comment] 2020-11-05 08:45
Confirming, can reproduce on 2.3.3.0

**Comment by tedyu** [comment] 2020-11-05 17:50
I repeated the above procedure:
```
yugabyte=# select count(*) from ordered_asc;
 count
-------
     9
(1 row)
```
My local build was based on 3f0a8aafdb7129444183786d9a79f24af19a04fe

**Comment by tedyu** [comment] 2020-11-05 19:57
```
yugabyte=# CREATE TABLE ordered_asc(k INT,PRIMARY KEY(k ASC)) SPLIT AT VALUES((10), (20), (30));
CREATE TABLE
yugabyte=# insert into ordered_asc select generate_series(1, 7);
INSERT 0 7
yugabyte=# select count(*) from ordered_asc;
 count
-------
     7
(1 row)

yugabyte=# insert into ordered_asc values(100);
INSERT 0 1
yugabyte=# insert into ordered_asc values(120);
INSERT 0 1
yugabyte=# select count(*) from ordered_asc;
 count
-------
     9
(1 row)
```

**Comment by kmuthukk** [comment] 2020-11-05 20:03
Quite likely fixed by the RANGE PARTITIONING work here in 78a726ab58a3f8d51f298c36336a2621a5b50598

**Comment by kmuthukk** [comment] 2020-11-05 20:04
@nocaway -- can you confirm if this is a duplicate of #4770?

**Comment by nocaway** [comment] 2020-11-07 02:35
This is a duplicate with #4770

**Comment by nocaway** [comment] 2020-11-07 02:39
The SPLIT AT feature should only be used after the commit https://github.com/yugabyte/yugabyte-db/commit/78a726ab58a3f8d51f298c36336a2621a5b50598

The beta version of SPLIT AT feature should not be used in production as it has a few wrong behaviors.  Backward compatibility would be impossible to support.

**Closed** 2020-11-07 02:41 UTC
Labels: area/ysql, duplicate
