### ISSUE TITLE
Universe node fails to connect with ysqlsh for Platform Version 2.8.4.0-b4.

### ISSUE THREAD

**Issue by NiyatiSinha-yb** [yugabyte/yugabyte-db#11725] opened 2022-03-11 06:50 UTC
### Link to Universe: http://portal.aws-stable.dev.yugabyte.com/universes/dee01eb4-ddcf-4654-a4d2-17abae88b1b1/overview (puppy-food-26-tls-4)

Logs are as follows:

logs of 172.151.38.28

> `I0310 07:34:08.352480  1506 pg_wrapper.cc:722] Restarting PostgreSQL server
> I0310 07:34:08.360639  1506 pg_wrapper.cc:434] PostgreSQL server running as pid 12894
> W0310 07:34:08.524554  1506 pg_wrapper.cc:706] PostgreSQL server exited with code 256
> I0310 07:34:08.524636  1506 pg_wrapper.cc:722] Restarting PostgreSQL server
> I0310 07:34:08.532487  1506 pg_wrapper.cc:434] PostgreSQL server running as pid 12895
> W0310 07:34:08.693711  1506 pg_wrapper.cc:706] PostgreSQL server exited with code 256
> I0310 07:34:08.693800  1506 pg_wrapper.cc:722] Restarting PostgreSQL server
> I0310 07:34:08.701727  1506 pg_wrapper.cc:434] PostgreSQL server running as pid 12897
> W0310 07:34:08.864975  1506 pg_wrapper.cc:706] PostgreSQL server exited with code 256
> I0310 07:34:08.865043  1506 pg_wrapper.cc:722] Restarting PostgreSQL server
> I0310 07:34:08.873034  1506 pg_wrapper.cc:434] PostgreSQL server running as pid 12898`

Looking at the logs, I see that tservers are up and tablets have also recovered and bootstrapped successfully.

> `I0310 07:09:25.424605  1475 pg_wrapper.cc:472] Data directory /mnt/d0/pg_data already exists, skipping initdb`

However, in postgresql-2022-03-10_000000.log I see

> `I0310 04:13:41.888604 25352 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 108)`

The following logs are in loop at the beginning

> `I0310 00:03:41.794370  2215 mem_tracker.cc:297] MemTracker: hard memory limit is 2.080520 GB
> I0310 00:03:41.794667  2215 mem_tracker.cc:299] MemTracker: soft memory limit is 1.768442 GB
> I0310 00:03:41.794775  2215 secure.cc:146] Certs directory: /home/yugabyte/yugabyte-tls-config, node name:
> I0310 00:03:41.812117  2215 thread_pool.cc:171] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
> I0310 00:03:41.813932  2215 pggate.cc:161] Reset YSQL bind address to 172.151.38.28:5432
> I0310 00:03:41.814062  2215 server_base_options.cc:137] Updating master addrs to {172.151.20.253:7100},{172.151.38.28:7100},{172.151.55.141:7100}
> I0310 00:03:41.814498  2215 pggate.cc:101] InitTServerSharedObject: 0, 0, 6
> I0310 00:03:41.814762  2215 pg_client.cc:59] Using TServer host_port: 172.151.38.28:9100
> I0310 00:03:41.817842  2237 async_initializer.cc:82] Starting to init ybclient
> I0310 00:03:41.825296  2240 client-internal.cc:2345] Reinitialize master addresses from file: /home/yugabyte/tserver/conf/server.conf
> I0310 00:03:41.825429  2240 client-internal.cc:2374] New master addresses: [172.151.20.253:7100,172.151.38.28:7100,172.151.55.141:7100]
> I0310 00:03:41.837146  2237 async_initializer.cc:86] Successfully built ybclient
> I0310 00:03:41.943600  2234 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 108)`
> 

At the end,

> `2022-03-10 04:41:05.130 UTC [31758] FATAL:  terminating background worker "YSQL webserver" due to administrator command
> 2022-03-10 04:41:05.210 UTC [31742] LOG:  background worker "YSQL webserver" (PID 31758) exited with exit code 1
> I0310 04:41:10.877956 14509 tcp_stream.cc:321] { local: 172.151.38.28:53576 remote: 172.151.38.28:9100 }:  Recv failed: Network error (yb/util/net/socket.cc:557): recvmsg error: Connection refused (system error 111)
> W0310 04:41:19.926040 14514 pg_client.cc:100] Heartbeat failed: Invalid argument (yb/tserver/pg_client_service.cc:301): Unknown session: 287
> W0310 04:41:19.963783 14514 outbound_call.cc:365] RPC callback for RPC call yb.tserver.PgClientService.Heartbeat -> { remote: 172.151.38.28:9100 idx: 0 protocol: 0x00007f1c2c5669c0 -> tcpc } , state=FINISHED_SUCCESS. took 0.034s
> W0310 04:41:28.874861 14513 pg_client.cc:100] Heartbeat failed: Invalid argument (yb/tserver/pg_client_service.cc:301): Unknown session: 287`
> 

and for the next 10 hours , only the following logs:

> `W0310 04:41:28.874861 14513 pg_client.cc:100] Heartbeat failed: Invalid argument (yb/tserver/pg_client_service.cc:301): Unknown session: 287`

log messages when postmaster restarts.

> ` ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23066] WARNING:  terminating connection because of crash of another server process
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23066] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23066] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23051] WARNING:  terminating connection because of crash of another server process
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23051] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23051] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23026] LOG:  checkpointer process (PID 23037) exited with exit code 2
>  ts1|pid23017|:27205|http://127.0.0.167:10559 2022-03-08 06:10:17.624 PST [23026] LOG:  terminating any other active server processes
>  ts1|pid23017|:27205|http://127.0.0.167:10559 I0308 06:10:17.624738 153337856 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 58)
>  ts1|pid23017|:27205|http://127.0.0.167:10559 I0308 06:10:17.624760 152801280 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 58)`

 #[PLAT-3348] : [https://yugabyte.atlassian.net/browse/PLAT-3348](url) 

[PLAT-3348]: https://yugabyte.atlassian.net/browse/PLAT-3348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by andrei-mart** [comment] 2022-03-25 16:14
The problem there was because of old backend still running an INSERT statement. Apparently it did not die when node was restarted after upgrade. The backend held the shared memory block that did not allow new postgres instance to startup.
I reproduced the problem locally and figured out that Postgres' early startup messages are captured into  tserver.err, and that file was not examined.
No further action is required, closing the issue.

**Closed by andrei-mart** 2022-03-25 16:14 UTC
Labels: area/ysql
