### ISSUE TITLE
[YSQL][LST] Tablet peer T [state=QUIESCING]:  is shutting down error

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#18224] opened 2023-07-13 16:20 UTC
Jira Link: [DB-7236](https://yugabyte.atlassian.net/browse/DB-7236)
### Description

Using LST, we are hitting this issue:

`Error message: ERROR:  Tablet peer T 4ea73f019c5743899239e3c1ac1c4f34 P da66b47b641942c7980bfe09ee63367b [state=QUIESCING]:  is shutting down`

Cluster creation command:
`bin/yb-ctl destroy && bin/yb-ctl --replication_factor 3 create --tserver_flags=enable_wait_queues=true,enable_deadlock_detection=true,ysql_max_connections=20,ysql_enable_packed_row=true,yb_enable_read_committed_isolation=true,ysql_num_shards_per_tserver=2,enable_stream_compression=true,stream_compression_algo=2,yb_num_shards_per_tserver=2 --master_flags=yb_enable_read_committed_isolation=true,enable_stream_compression=true,stream_compression_algo=2,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=1,tablet_split_high_phase_shard_count_per_node=5,ysql_enable_packed_row=true,enable_deadlock_detection=true,enable_wait_queues=true`

LST run command: 

`./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --runtime=60 --max-columns=20 --complexity=full --seed=010159`

Error trace:
```
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Tablet peer T 4ea73f019c5743899239e3c1ac1c4f34 P da66b47b641942c7980bfe09ee63367b [state=QUIESCING]:  is shutting down
/home/ec2-user/code/yugabyte-db/build/debug-clang16-dynamic-ninja/../../src/yb/yql/pggate/util/ybc_util.cc:331:     @     0x7f3fa891128b  YBCGetStackTrace
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/utils/error/../../../../../../../src/postgres/src/backend/utils/error/elog.c:4781:     @     0x55b8d8c941e8  yb_errmsg_from_status_data
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/access/yb_access/../../../../../../../src/postgres/src/backend/access/yb_access/yb_scan.c:3231:     @     0x55b8d85dad90  ybFetchNext
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/ybc_fdw.c:545:     @     0x55b8d887c737  ybcIterateForeignScan
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/nodeForeignscan.c:60:     @     0x55b8d886896b  ForeignNext
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execScan.c:95:     @     0x55b8d8821434  ExecScanFetch
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execScan.c:171:     @     0x55b8d8821187  ExecScan
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/nodeForeignscan.c:130:     @     0x55b8d8868444  ExecForeignScan
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execProcnode.c:459:     @     0x55b8d881eed1  ExecProcNodeFirst
../../../../../../src/postgres/src/include/executor/executor.h:265:                                     @     0x55b8d8860b41  ExecProcNode
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/nodeSort.c:119:     @     0x55b8d8860482  ExecSort
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execProcnode.c:459:     @     0x55b8d881eed1  ExecProcNodeFirst
../../../../../../src/postgres/src/include/executor/executor.h:265:                                     @     0x55b8d88528c1  ExecProcNode
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/nodeMergejoin.c:656:     @     0x55b8d88513d7  ExecMergeJoin
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execProcnode.c:459:     @     0x55b8d881eed1  ExecProcNodeFirst
../../../../../../src/postgres/src/include/executor/executor.h:265:                                     @     0x55b8d884d041  ExecProcNode
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/nodeLimit.c:118:     @     0x55b8d884c6ab  ExecLimit
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execProcnode.c:459:     @     0x55b8d881eed1  ExecProcNodeFirst
../../../../../../src/postgres/src/include/executor/executor.h:265:                                     @     0x55b8d8817dc1  ExecProcNode
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execMain.c:1726:     @     0x55b8d88125f0  ExecutePlan
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execMain.c:357:     @     0x55b8d88124a0  standard_ExecutorRun
/home/ec2-user/code/yugabyte-db/src/postgres/contrib/pg_stat_statements/../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:1262:     @     0x7f3f92c679ad  pgss_ExecutorRun
/home/ec2-user/code/yugabyte-db/src/postgres/contrib/yb_pg_metrics/../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:508:     @     0x7f3fa8a51eb6  ybpgm_ExecutorRun
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execMain.c:295:     @     0x55b8d88121ea  ExecutorRun
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/pquery.c:960:     @     0x55b8d8a9cc54  PortalRunSelect
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/pquery.c:789:     @     0x55b8d8a9c658  PortalRun
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:1208:     @     0x55b8d8a99cf2  exec_simple_query
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4674:     @     0x55b8d8a97924  yb_exec_simple_query_impl
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4642:     @     0x55b8d8a97a4e  yb_exec_query_wrapper_one_attempt
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4666:     @     0x55b8d8a978f9  yb_exec_query_wrapper
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4689:     @     0x55b8d8a92e74  yb_exec_simple_query
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:5314:     @     0x55b8d8a91b39  PostgresMain
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4672:     @     0x55b8d89bb458  BackendRun
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4310:     @     0x55b8d89ba411  BackendStartup
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1770:     @     0x55b8d89b8f0e  ServerLoop
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1426:     @     0x55b8d89b5e2a  PostmasterMain
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:     @     0x55b8d88b4127  PostgresServerProcessMain
    @     0x55b8d88b46e1
    @     0x7f3fa6dacd84
    @     0x55b8d849c32d

/home/ec2-user/code/yugabyte-db/build/debug-clang16-dynamic-ninja/../../src/yb/yql/pggate/util/ybc_util.cc:331:     @     0x7f3fa891128b  YBCGetStackTrace
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/utils/error/../../../../../../../src/postgres/src/backend/utils/error/elog.c:1112:     @     0x55b8d8c8d3ad  errmsg
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:3954:     @     0x55b8d8a93590  YBPrepareCacheRefreshIfNeeded
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:5324:     @     0x55b8d8a91bb4  PostgresMain
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4672:     @     0x55b8d89bb458  BackendRun
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4310:     @     0x55b8d89ba411  BackendStartup
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1770:     @     0x55b8d89b8f0e  ServerLoop
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1426:     @     0x55b8d89b5e2a  PostmasterMain
/home/ec2-user/code/yugabyte-db/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:     @     0x55b8d88b4127  PostgresServerProcessMain
    @     0x55b8d88b46e1
    @     0x7f3fa6dacd84
    @     0x55b8d849c32d

CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
Transaction isolation level: read uncommitted
DB Node: host: 127.0.0.1, port: 5433
DB Backend PID: 1545782
```

LST logs/yugabyte-data folder Upload: https://drive.google.com/drive/folders/1QAxc-Nx9nTlgHtLglVReDB2lNjlo2xBr?usp=sharing (Accessible within Yugabyte Organization)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7236]: https://yugabyte.atlassian.net/browse/DB-7236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment] 2023-07-17 07:31
This is a variation of https://github.com/yugabyte/yugabyte-db/issues/15788 hit in a different moment of time, hence closing as duplicate.

**Closed by arybochkin** 2023-07-17 07:31 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage, LST_DST

**Comment by arybochkin** [comment] 2023-07-17 07:32
Duplicate of #15788
