### ISSUE TITLE
[YSQL][randgen] "ERROR:  floating-point exception" with BitmapScan

### ISSUE THREAD

**Issue by mtakahar** [yugabyte/yugabyte-db#21488] opened 2024-03-14 20:53 UTC
Jira Link: [DB-10372](https://yugabyte.atlassian.net/browse/DB-10372)
### Description

Problem
---
* Reproducible on a recent master (305dbefe92).
* No error when bitmap scan is disabled.

```
YB test# SELECT * FROM CC  AS table1  JOIN C  AS table2  ON ( table2 .col_int_key  = table1 .col_int_nokey  )  WHERE table2 .col_varchar_key  <=  SOME (  SELECT col_varchar_nokey  FROM C  )  AND table1 .col_varchar_key  = table2 .col_varchar_key  OR ( table1 .col_int_nokey  >= table2 .pk  AND table1 .col_varchar_key  IS  NULL  )   ;
ERROR:  floating-point exception
DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
YB test# EXPLAIN (COSTS OFF) SELECT * FROM CC  AS table1  JOIN C  AS table2  ON ( table2 .col_int_key  = table1 .col_int_nokey  )  WHERE table2 .col_varchar_key  <=  SOME (  SELECT col_varchar_nokey  FROM C  )  AND table1 .col_varchar_key  = table2 .col_varchar_key  OR ( table1 .col_int_nokey  >= table2 .pk  AND table1 .col_varchar_key  IS  NULL  )   ;
                                                                              QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop
   ->  Seq Scan on cc table1
   ->  YB Bitmap Table Scan on c table2
         Filter: (((SubPlan 1) AND ((table1.col_varchar_key)::text = (col_varchar_key)::text)) OR ((table1.col_int_nokey >= pk) AND (table1.col_varchar_key IS NULL)))
         ->  BitmapAnd
               ->  Bitmap Index Scan on c_int_key
                     Index Cond: (col_int_key = table1.col_int_nokey)
               ->  BitmapOr
                     ->  Bitmap Index Scan on c_varchar_key
                           Index Cond: ((table1.col_varchar_key)::text = (col_varchar_key)::text)
                     ->  Bitmap Index Scan on c_pkey
                           Index Cond: (table1.col_int_nokey >= pk)
         SubPlan 1
           ->  Materialize
                 ->  Seq Scan on c
(15 rows)
```

**Bitmap scan disabled**:
```
YB test# /*+ Set(enable_bitmapscan OFF) */SELECT * FROM CC  AS table1  JOIN C  AS table2  ON ( table2 .col_int_key  = table1 .col_int_nokey  )  WHERE table2 .col_varchar_key  <=  SOME (  SELECT col_varchar_nokey  FROM C  )  AND table1 .col_varchar_key  = table2 .col_varchar_key  OR ( table1 .col_int_nokey  >= table2 .pk  AND table1 .col_varchar_key  IS  NULL  )   ;
 pk | col_int_nokey | col_varchar_key | pk | col_int_key | col_varchar_key | col_varchar_nokey
----+---------------+-----------------+----+-------------+-----------------+-------------------
 12 |             1 | r               | 17 |           1 | r               | r
(1 row)

YB test# EXPLAIN (COSTS OFF)/*+ Set(enable_bitmapscan OFF) */SELECT * FROM CC  AS table1  JOIN C  AS table2  ON ( table2 .col_int_key  = table1 .col_int_nokey  )  WHERE table2 .col_varchar_key  <=  SOME (  SELECT col_varchar_nokey  FROM C  )  AND table1 .col_varchar_key  = table2 .col_varchar_key  OR ( table1 .col_int_nokey  >= table2 .pk  AND table1 .col_varchar_key  IS  NULL  )   ;
                                                                                     QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join
   Hash Cond: (table1.col_int_nokey = table2.col_int_key)
   Join Filter: (((SubPlan 1) AND ((table1.col_varchar_key)::text = (table2.col_varchar_key)::text)) OR ((table1.col_int_nokey >= table2.pk) AND (table1.col_varchar_key IS NULL)))
   ->  Seq Scan on cc table1
   ->  Hash
         ->  Seq Scan on c table2
   SubPlan 1
     ->  Materialize
           ->  Seq Scan on c
(9 rows)

YB test#
```

Test Case
---
```
CREATE TABLE c (
    pk integer NOT NULL,
    col_int_key integer,
    col_varchar_key character varying(1),
    col_varchar_nokey character varying(1),
    CONSTRAINT c_pkey PRIMARY KEY(pk ASC)
);

CREATE TABLE cc (
    pk integer NOT NULL,
    col_int_nokey integer,
    col_varchar_key character varying(1),
    CONSTRAINT cc_pkey PRIMARY KEY(pk ASC)
);


COPY c (pk, col_int_key, col_varchar_key, col_varchar_nokey) FROM stdin;
1	4	v	v
2	62	v	v
3	7	c	c
4	1	\N	\N
5	0	x	x
6	7	i	i
7	7	e	e
8	1	p	p
9	7	s	s
10	1	j	j
11	5	z	z
12	2	c	c
13	0	a	a
14	1	q	q
15	8	y	y
16	1	\N	\N
17	1	r	r
18	9	v	v
19	1	\N	\N
20	5	r	r
\.

COPY cc (pk, col_int_nokey, col_varchar_key) FROM stdin;
10	\N	x
11	8	d
12	1	r
13	9	f
14	4	y
15	3	u
16	2	m
17	\N	\N
18	2	o
19	\N	w
20	6	m
21	7	q
22	2	\N
23	5	d
24	7	g
25	6	x
26	6	f
27	2	p
28	9	j
29	6	c
\.

CREATE INDEX c_int_key ON c USING lsm (col_int_key ASC);
CREATE INDEX c_varchar_key ON c USING lsm (col_varchar_key ASC, col_int_key ASC);


SELECT
    *
FROM
    CC AS table1
    JOIN C AS table2 ON (
        table2.col_int_key = table1.col_int_nokey
    )
WHERE
    table2.col_varchar_key <= SOME (
        SELECT
            col_varchar_nokey
        FROM
            C
    )
    AND
    table1.col_varchar_key = table2.col_varchar_key
    OR
    (
        table1.col_int_nokey >= table2.pk
        AND
        table1.col_varchar_key IS NULL
    )
;
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10372]: https://yugabyte.atlassian.net/browse/DB-10372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment] 2024-03-18 16:30
Duplicate of #21495

**Closed by timothy-e** 2024-03-18 16:30 UTC
Labels: kind/bug, area/ysql, priority/medium
