### ISSUE TITLE
[YSQL] On YB colocated tables,  query with distinct on column (part of composite PK) fails with 'Cannot decode value type kGroupEnd from the key encoding format'

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#16257] opened 2023-02-28 10:49 UTC
Jira Link: [DB-5682](https://yugabyte.atlassian.net/browse/DB-5682)
### Description

This issue is seen only with distinct and on PK column or part of PK column.
Following are the steps to reproduce the issue :

```
drop table if exists demo;

create table demo (id bigint, col5 varchar(128), col7 float, col8 float, col9 varchar(128), col10 timestamp, col11 timestamp, col12 varchar(128),  primary key(id,col5,col9));

insert into demo (id, col5, col7, col8, col9, col10, col11, col12) select n+80000, '100000100000100000100100000100'||(n%24000)+1, n%50, n*10, '100000100000'||(n%3350)+1, '2023-02-08 14:17:23.071', '2023-02-08 14:17:23.071', '1010101010010101001101001'||(n%100)+1 from generate_series(1,275000) n;

select distinct(id) from demo where col5='10000010000010000010010000010061' and col9='10000010000061';
```
The query fails on yb colocated with : 
```
select distinct(id) from demo where col5='10000010000010000010010000010061' and col9='10000010000061';
ERROR: Query error: Cannot decode value type kGroupEnd from the key encoding format: "!"
Time: 33.807 ms

yb_colocated=# select distinct(col5) from demo where id=294460 and col9='10000010000061';
ERROR:  Cannot decode value type kGroupEnd from the key encoding format: "!"

```
Though querying the column id, count(id) , max(id) work properly.

[DB-5682]: https://yugabyte.atlassian.net/browse/DB-5682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2023-03-01 02:14
Seems like duplicate of https://github.com/yugabyte/yugabyte-db/issues/16038

**Closed** 2023-03-23 23:54 UTC
Labels: kind/bug, area/ysql, priority/medium
