### ISSUE TITLE
[DocDB] [Bulk load] [COPY cmd] Loading of 200GB csv file on a 8core 3-node universe with RF3, fails as one of the nodes goes down with disk full.

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12561] opened 2022-05-19 14:21 UTC
Jira Link: [[DB-429]](https://yugabyte.atlassian.net/browse/DB-429)
### Description

I was trying to load a 200GB csv file using psql into a 8core 3node RF3 universe. **Tablet splitting** is enabled and also load was run in **transactional** mode.
The data was generated for a table with 21 fields and 320M rows. Table was created with primary key.
YB version : 2.13.2.0-b32

Error message at the client :
```psql:test_8core_txn_20fields_idx.sql:11: FATAL:  terminating connection due to administrator command
CONTEXT:  COPY orders, line 293767268: "293767267,11f906a56378200832e59a530da66e20,e9d015e826ce27916ea560763c11c944,35b25eb40d7b91a8afa4e37d..."
psql:test_8core_txn_20fields_idx.sql:11: FATAL:  Network error: recvmsg error: Connection reset by peer
psql:test_8core_txn_20fields_idx.sql:11: fatal: connection to server was lost
```

create table ddl:
`CREATE TABLE orders (id INT primary key, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, col5 TEXT, col6 TEXT, col7 TEXT, col8 TEXT, col9 TEXT, col10 TEXT, col11 TEXT, col12 TEXT, col13 TEXT, col14 TEXT, col15 TEXT, col16 TEXT, col17 TEXT, col18 TEXT, col19 TEXT, col20 TEXT);`

copy command : 
`\copy orders from '/home/ubuntu/csv_data/orders_20_320m.csv' with (FORMAT CSV, HEADER, ROWS_PER_TRANSACTION 20000);`

**YB settings :**
```GFlags:
Tablet-spliting enabled 
max_packed_row_columns=1000
Session setting :
set ysql_max_in_flight_ops=20000;
set ysql_session_max_batch_size = 2000;

ROWS_PER_TRANSACTION 20000 (COPY command)
```

This server to which the client was connected failed when its disk full.

[DB-429]: https://yugabyte.atlassian.net/browse/DB-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sonalsagarwal** [comment] 2022-05-20 07:27
Universes link where this issue was seen :
http://10.9.131.126/universes/52459403-2c5c-4a4f-89d8-f4cc4d1728da
http://10.9.131.126/universes/142ab521-7a0f-406c-b217-d1ed3e94af03

**Comment by rthallamko3** [comment] 2022-06-01 03:52
This a 2.14 release blocker. cc @jmeehan16

**Comment by jmeehan16** [comment] 2022-06-02 03:49
This issue is a duplicate of [11064](https://github.com/yugabyte/yugabyte-db/issues/11064), resolved by the same fix. After some investigation with @rthallamko3 , there isn't any evidence of data skewing, and instead the post-split compactions are causing minor compactions to be delayed.  Performance will improve with the `automatic_compaction_extra_priority` flag.

**Closed by jmeehan16** 2022-06-02 03:49 UTC
Labels: kind/bug, area/docdb, priority/critical
