### ISSUE TITLE
Optimistic locking fails if "change detection" column is of type timestamp or timestamptz

### ISSUE THREAD

**Issue by jk-1** [yugabyte/yugabyte-db#4805] opened 2020-06-17 09:01 UTC
Jira Link: [DB-1613](https://yugabyte.atlassian.net/browse/DB-1613)
Optimistic locking fails if "change detection" column is of type timestamp or timestamptz but works fine when type is int

I use JOOQ https://www.jooq.org to generate db layer code from sql tables.

Used JOOQ version is 3.12.4
Yugabyte version is 2.1.4.0
ysqlsh version is psql (PostgreSQL) 11.2-YB-2.1.4.0-b0

Details of the defect and workaround are already documented as stackoverflow question and answer here: 
https://stackoverflow.com/questions/62346175/jooq-optimistic-locking-and-datachangedexception-database-record-has-been-chang

JOOQ debugging output shows the generated sql code so that you can probably repeat the error without installing JOOQ.
JOOQ setting `.withReturnAllOnUpdatableRecord(true)` means that if db generates or modifies any values during insert/update, these values are returned in result record. Example: if db generates id value from sequence during row insert, JOOQ assigns this id value into the returned record into field record.id.

**Comment by ddorian** [comment] 2020-06-17 10:06
Hi @jk-1 

Is it possible to set verbose logging for JOOQ so we can see all the queries that are executed on all sessions ?

Or add gflag [`--ysql_log_statement=all`](https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#ysql-log-statement) to yb-tserver and attach the logs here.

**Comment by jk-1** [comment] 2020-06-17 12:52
How can I add this --ysql_log_... flag if I start the cluster with yb-ctl start? yb-ctl does not accept that flag.

**Comment by ddorian** [comment] 2020-06-17 14:38
You can do that using [--tserver_flags ](https://docs.yugabyte.com/latest/admin/yb-ctl/#tserver-flags )

**Comment by jk-1** [comment] 2020-06-18 07:50
[yugabyte-defect-report-01.txt](https://github.com/yugabyte/yugabyte-db/files/4797075/yugabyte-defect-report-01.txt)

JOOQ trace and yugabyte postgresql log dumps are in the attached file.

**Comment by rkarthik007** [comment] 2020-06-18 20:58
> [yugabyte-defect-report-01.txt](https://github.com/yugabyte/yugabyte-db/files/4797075/yugabyte-defect-report-01.txt)
> 
> JOOQ trace and yugabyte postgresql log dumps are in the attached file.

cc @m-iancu @ndeodhar

**Comment by sushantrmishra** [comment] 2023-09-01 05:16
Closing this issue as not able to reproduce  based on the queries shared in https://github.com/yugabyte/yugabyte-db/issues/4805#issuecomment-645845597 

```
localhost:5433 yugabyte@yugabyte=# select version();
                                                                                                                      version
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2-YB-2.19.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.7 (/opt/yb-build/llvm/yb-llvm-v15.0.7-yb-1-1680596282-6b9d30d8-centos7-x86_64-build/src/llvm-project/clang 6b9d30d80f5cebc66c9fa46013d18f125ea8ec0e), 64-bit
(1 row)
```

**Closed by sushantrmishra** 2023-09-01 05:16 UTC
Labels: kind/bug, area/ysql, priority/medium, community/request
