### ISSUE TITLE
[Platform] Ability to update the Universe State from UI

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#4444] opened 2020-05-11 17:53 UTC
Right now we don't have a API driven way to switch a universe state from Error to Ready. This blocks the user from doing any further operation. We need to add the support for this, As well add necessary audit log when such action is taken.

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-443

**Comment by streddy-yb** [comment] 2020-10-12 16:26
Duplicate of #4646

**Closed by streddy-yb** 2020-10-12 16:26 UTC
Labels: area/platform
