### ISSUE TITLE
[YSQL] PITR Failed with RESTORING state(upto 3 min) and if we login to machine and check the status - there its status if FAILED

### ISSUE THREAD

**Issue by agsh-yb** [yugabyte/yugabyte-db#17084] opened 2023-04-28 11:20 UTC
Jira Link: [DB-6383](https://yugabyte.atlassian.net/browse/DB-6383)
### Description

Test name: TestTabletSplittingWithPITRCopyBRUpgradesIndexMatView
Test failing on **`2.18`** 
Scenario attempted on `2.18.0.0-b35` 
RESTORING state(upto 3 min) and if we login to machine and check the status - there its status if FAILED, attached screenshot.
Not sure this issue is due to tablet splitting or not currently triaging 
Steps:
```
1. Create universe(2.14) with automatic tablet splitting enabled, with RPC(algo=2)
        2. Create Database and Create 2
        complex tables(t1, t2) (1 Hashed 1 Range)
        3. Insert data to tables and validate data in tables
        4. Create Unique, Secondary and Partial indexes for both tables.
        5. Create snapshot_schedule
        6. COPY TO on the tables
        7. Collect time(1) and validate
        8. Insert some data and validate
        9. PITR to time(1)
        10. Validate data, tablets and index
        11. Create Materialized View
        12. Take a backup BACKUP_001
        13. Execute DDL (Add a column, Rename column and Delete a column, Add foreign key,
        Add check constraint, Add not null constraints) and DML (Update row value, delete few rows)
        14  Upgrade universe
        15. Validate data
        16. Delete some data from the table
        17. Validate data, tablets and indexes
        18. Delete PITR schedule and Drop database
        19. Restore to BACKUP_001
        20. Validate data, tablets and index and Materialized View
        21. Refresh Materialized View( non - concurrent )
        22. Validate data, tablets index and Materialized View
        23. Refresh Materialized View(refresh concurrent)
        24. Create Snapshot Schedule and Note down the time(2)
        25. Delete few rows from tables (t1 and t2)
        26. PITR to time(2)
PITR is failing to time(2) at #step26
```
Issue: Observed PITR to time(2) is failing 

Jenkins link: https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-system-developer/5723/
<img width="868" alt="Screenshot 2023-04-28 at 5 37 31 PM" src="https://user-images.githubusercontent.com/121818428/235143376-e74ce381-1857-490e-9251-d3cc4cadb39b.png">

Attached logs: https://drive.google.com/file/d/1oz9KMQjqscCh9fnMMjzyn8elNGES5VOP/view?usp=sharing
G-Flags:
Master Value

```
m_flags = {
        "enable_stream_compression": "true",
        "stream_compression_algo": "2",
        "enable_automatic_tablet_splitting": "true",
        "tablet_split_high_phase_shard_count_per_node": 200,
        # high_phase_size 2MB
        "tablet_split_high_phase_size_threshold_bytes": 2097152,
        # low_phase_size 100KB
        "tablet_split_low_phase_size_threshold_bytes": 102400,
        "tablet_split_low_phase_shard_count_per_node": 16,
        "ysql_enable_packed_row": "true"
    }
```
    
T-SERVER VALUE

    `t_flags = {
        "enable_automatic_tablet_splitting": "true",
        "ysql_num_shards_per_tserver": 1,
        "ysql_enable_packed_row": "true",
        "scheduled_full_compaction_frequency_hours": "12",
        "scheduled_full_compaction_jitter_factor_percentage": "100",
         "scheduled_full_compaction_check_interval_min": "5",
    }`
Schema used:

```
CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
CREATE EXTENSION IF NOT EXISTS pgcrypto;  CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;        CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp”;

CREATE TYPE complex AS (re float8, im float8);
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');
CREATE DOMAIN postal_code AS TEXT CHECK(VALUE ~ '^\d{5}$'OR VALUE ~ '^\d{5}-\d{4}$');
```

 Table-
```
CREATE TABLE co_tab (
  id TEXT PRIMARY KEY, 
  uuid_col uuid DEFAULT uuid_generate_v4(), 
  name text COLLATE "en_US.utf8", 
  c complex, 
  info json, 
  contact JSONB, 
  arr smallint[], 
  cash money, 
  i inet, 
  m macaddr, 
  i2 serial, 
  i3 bigserial, 
  val smallint, 
  details e_details, 
  age int, 
  collated_data text collate "POSIX", 
  date DATE, 
  n NUMERIC (3, 2), 
  r real, 
  c1 CHAR(1), 
  created_at timestamptz, 
  uuid0 uuid DEFAULT uuid_nil(), 
  uuid1 uuid DEFAULT uuid_generate_v1(), 
  p1 POINT, 
  t1 TIME, 
  ts1 TIMESTAMP, 
  i4 INTERVAL, 
  p2 path, 
  p3 polygon, 
  b box, 
  c2 circle, 
  l line, 
  l1 lseg, 
  a2 text[][], 
  zip postal_code,
  user_handle citext,
  location point,
  fuzzy_str text,
  profile_data hstore
);
```
Load data --

```
DO $do$ BEGIN FOR i IN 1..10000 LOOP INSERT INTO tab_hash(
  id, name, c, info, contact, arr, cash, 
  i, m, i2, i3, val, details, age, collated_data, 
  date, n, r, c1, created_at, p1, t1, ts1, 
  i4, p2, p3, c2, l, l1, a2, zip
) 
VALUES 
  (
    i, 
    'Hermione', 
    (1, 2), 
    '{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}', 
    '{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}', 
    '{1, 2, 3}', 
    '$99.99', 
    '1.1.1.1', 
    '00:00:00:00:00:00', 
    i, 
    i + 1, 
    666, 
    'Sms', 
    15, 
    md5(
      random():: text
    ), 
    current_timestamp, 
    5.36, 
    2147483647, 
    'G', 
    now(), 
    point(3, 4), 
    LOCALTIME(0), 
    current_timestamp(0), 
    '00:25:00', 
    '(1,3), (4,12)', 
    '(1,3),(4,12), (2,4)', 
    '10, 4, 10', 
    '{1,2,3}', 
    '(0, 4), (2,8)', 
    '{{"b1", "c"}, {"m1", "l"}}', 
    89000
  );
END LOOP;
END $do$;
```
cc: @Arjun-yb , @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6383]: https://yugabyte.atlassian.net/browse/DB-6383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment] 2023-06-19 18:44
This should have been fixed by https://github.com/yugabyte/yugabyte-db/commit/fe4bdef51b31e063eb9082f732d73da90f26c3b6. 

@agsh-yb - Can you confirm that this is passing now ?

**Comment by yamen-haddad** [comment] 2023-07-10 22:17
@agsh-yb I am unable to reproduce using the textual description mentioned. (I wrote my own queries as I do not have the exact set of queries).
I also think this has to do with sequences as we have a `serial` column. The fix that @lingamsandeep mentioned should have solved it.
Please confirm if this is still reproducible or not.

**Comment by agsh-yb** [comment] 2023-07-11 05:17
Sure @yamen-haddad I'll check and get back to you

**Comment by agsh-yb** [comment] 2023-07-11 16:57
@yamen-haddad  It is not reproducible in the current versions of `2.18` and master.
cc: @lingamsandeep @kripasreenivasan

**Comment by yamen-haddad** [comment] 2023-07-11 17:28
Ok thanks @agsh-yb . I will close the issue in this case.

**Closed by yamen-haddad** 2023-07-11 17:28 UTC
Labels: kind/bug, area/docdb, priority/high
