### ISSUE TITLE
[YSQL] Queries marked read only via pg_hint_plan do not use follower reads in READ COMMITTED

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#18806] opened 2023-08-22 20:36 UTC
Jira Link: [DB-7686](https://yugabyte.atlassian.net/browse/DB-7686)
### Description

If you enable follower reads and READ COMMITTED isolation, marking a transaction as read only using pg_hint_plan does not result in follower reads.

Repro:

Start a cluster with the gflag `yb_enable_read_committed_isolation=true`.

```sql
CREATE TABLE t (key INT PRIMARY KEY, value TEXT);
INSERT INTO t (key, value) VALUES (1, 'old');
SET yb_read_from_followers = true;
SET yb_follower_read_staleness_ms = 5000;
select pg_sleep(4);

UPDATE t SET value = 'NEW' WHERE key = 1;

select pg_sleep(1);

BEGIN TRANSACTION;
SELECT value FROM t WHERE key = 1; -- returns 'NEW'
COMMIT;

BEGIN TRANSACTION READ ONLY;
SELECT value FROM t WHERE key = 1; -- returns 'old'
COMMIT;

/*+ Set(transaction_read_only on) */ 
SELECT value FROM t WHERE key = 1;  -- should return 'old', but returns 'NEW
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7686]: https://yugabyte.atlassian.net/browse/DB-7686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment] 2023-08-24 22:03
closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/17135

**Closed by sushantrmishra** 2023-08-24 22:03 UTC
Labels: kind/bug, area/ysql, priority/medium
