### ISSUE TITLE
[docs][api] SQL statements [YSQL]

### ISSUE THREAD

**Issue by ddhodge** [yugabyte/yugabyte-db#12962] opened 2022-06-20 18:03 UTC
https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/

## Issue description

Missing DROP INDEX

## Suggested resolution

Add DROP INDEX page

**Comment by ddorian** [comment] 2023-05-13 13:21
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/9951

**Closed by ddorian** 2023-05-13 13:21 UTC
Labels: area/documentation, status/awaiting-triage, temp/docs-migration
