### ISSUE TITLE
[Restore] Restore failed (for restore on same universe) in Tablet Splitting iTests on a non colocated DB 

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#16642] opened 2023-03-31 16:45 UTC
Jira Link: [DB-6028](https://yugabyte.atlassian.net/browse/DB-6028)
### Description

**Logs**:
`2023-03-31 14:30:18,404 test_base.py:179 ERROR testysqltabletsplittingwithrpc-aws-rf3 ITEST FAILED testysqltabletsplittingwithrpc-aws-rf3 : RuntimeError('wait_for_task: Failed task with errors in 30.332180738449097s:\nFailed to execute task {"platformVersion":"2.17.3.0-b138","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"2f47ee58-321e-4b78-9503-f1d0ec602e9b","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"y..., hit error:\n\nTask id a88341ce-9b14-4fca-a420-8a0e4328f58c_PGSQL_TABLE_TYPE_non_colocated_db status: Failed with error COMMAND_FAILED.')`

Details to connect in internal Slack thread [here](https://yugabyte.slack.com/archives/C8QDREM0R/p1680280665898519?thread_ts=1680280654.498589&cid=C8QDREM0R)

Build - 2.17.3.0-b138

cc: @renjith-yb @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6028]: https://yugabyte.atlassian.net/browse/DB-6028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yifanguan** [comment] 2023-03-31 21:15
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/16441

**Closed** 2023-04-04 20:46 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage
