### ISSUE TITLE
FATAL:  sorry, too many clients already; where can I change the properties about maxconnections?

### ISSUE THREAD

**Issue by halleyshx** [YugaByte/yugabyte-db#1921] opened 2019-07-29 07:30 UTC
I test the performance by sqlinsert (312 threads) of yb-sample-apps. When I run the test command,there are some error like this and incessancy:

> Jul 29, 2019 3:15:34 PM org.postgresql.Driver connect
> SEVERE: Connection error:
> org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> 
> 3372901 [Thread-342] FATAL com.yugabyte.sample.apps.SqlInserts  - Failed writing key: key:12840905
> org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> 3365454 [Thread-73] FATAL com.yugabyte.sample.apps.SqlInserts  - Failed writing key: key:7868995
> org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "postgresqlkeyvalue_pkey"
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:156)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> Jul 29, 2019 3:15:34 PM org.postgresql.core.v3.ConnectionFactoryImpl log
> WARNING: SQLException occurred while connecting to 10.xxx.xxx.9:5433
> org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)

Then I run ysqlsh,the same error like this:
`# /export/App/yugabyte-1.3.0.0/bin/ysqlsh -h 10.xxx.xxx.9 -e`

> ysqlsh: FATAL:  sorry, too many clients already

**Comment by d-uspenskiy** [comment] 2019-07-29 09:19
@halleyshx

**Comment by halleyshx** [comment] 2019-07-29 09:42
@d-uspenskiy ，Thanks,I found the postgresql.conf and change the max_connections to 2100.
But,there are some error like this when I run the restart command.What can I do?

> # /export/App/yugabyte-1.3.0.0/bin/yb-ctl restart
> Stopping cluster.
> Starting cluster.
> Waiting for cluster to be ready.
> Traceback (most recent call last):
>   File "/export/App/yugabyte-1.3.0.0/bin/yb-ctl", line 1797, in <module>
>     control.run()
>   File "/export/App/yugabyte-1.3.0.0/bin/yb-ctl", line 1770, in run
>     self.args.func()
>   File "/export/App/yugabyte-1.3.0.0/bin/yb-ctl", line 1620, in restart_cmd_impl
>     self.wait_for_cluster_or_raise()
>   File "/export/App/yugabyte-1.3.0.0/bin/yb-ctl", line 1404, in wait_for_cluster_or_raise
>     if not self.wait_for_cluster():
>   File "/export/App/yugabyte-1.3.0.0/bin/yb-ctl", line 1350, in wait_for_cluster
>     raise ValueError("Cannot wait for cluster without knowing master addresses")
> ValueError: Cannot wait for cluster without knowing master addresses
> ^^^ Encountered errors ^^^

**Comment by d-uspenskiy** [comment] 2019-07-29 10:07
@halleyshx Probably some port is busy and cluster can't start properly.

Please try
```
yb-ctl stop
```
And check that there are no `yb-master`, `yb-tserver` and `postgres` processes

```
ps aux | grep -P '(yb-master)|(yb-tserver)|(postgres)' | grep -v grep | wc
```
If you have running processes after `yb-ctl stop` you can try to restart PC as the simplest solution

**Comment by halleyshx** [comment] 2019-07-29 10:23
@d-uspenskiy ,I kill the tserver PID and run tserver again without yb-ctl command. Then I run the test command `nohup java -jar yb-sample-apps.jar --workload SqlInserts --nodes 10.xxx.xxx.2:5433,10.xxx.xxx.8:5433,10.xxx.xxx.9:5433 --nouuid --num_unique_keys 50000000 --num_writes 50000000 --num_threads_write 356 --num_threads_read 0 2>&1 | tee /export/App/yb-sample-apps/result/pure-inserts-yb.log`,  the other problem had come, that's why?
> Jul 29, 2019 6:09:08 PM org.postgresql.Driver connect
> SEVERE: Connection error:
> org.postgresql.util.PSQLException: FATAL: Timed out: Read RPC to 10.xxx.xxx.8:7100 timed out after 2.401s
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> 
> 289840 [Thread-135] FATAL com.yugabyte.sample.apps.SqlInserts  - Failed writing key: key:732
> org.postgresql.util.PSQLException: FATAL: Timed out: Read RPC to 10.xxx.xxx.8:7100 timed out after 2.401s
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
> Jul 29, 2019 6:09:09 PM org.postgresql.core.v3.ConnectionFactoryImpl log
> WARNING: SQLException occurred while connecting to 10.xxx.xxx.8:5433
> org.postgresql.util.PSQLException: FATAL: Timed out: Read(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 76, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 55295441.703s (passed: 59.899s): Illegal state (yb/master/scoped_leader_shared_lock.cc:76): Not the leader. Local UUID: 7da68350e45b413a9479e8f8f98a49e2, Consensus state: current_term: 1 leader_uuid: "45f57795ef0547e49595ceb2879fb8c6" config { opid_index: -1 peers { permanent_uuid: "7da68350e45b413a9479e8f8f98a49e2" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.2" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "45f57795ef0547e49595ceb2879fb8c6" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.8" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "048ae2842da749b6b798726e3587aea0" member_type: VOTER last_known_private_addr { host: "10.xxx.xxx.9" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
> 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
> 	at org.postgresql.Driver.makeConnection(Driver.java:452)
> 	at org.postgresql.Driver.connect(Driver.java:254)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
> 	at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
> 	at com.yugabyte.sample.apps.SqlInserts.getPreparedInsert(SqlInserts.java:137)
> 	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:152)
> 	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:626)
> 	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)

**Comment by d-uspenskiy** [comment] 2019-07-29 14:38
@halleyshx It looks like you are using `debug` build. Please build `release` version and try your workload on it

**Comment by halleyshx** [comment] 2019-07-30 01:46
@d-uspenskiy ,I don't think so,because I download the tool with the command `wget -P target https://github.com/YugaByte/yb-sample-apps/releases/download/v1.2.0/yb-sample-apps.jar`,so I think that I use the release version.And I test the cockroach by the tool with the same workload at the same time,there are not the errors like that. Then, Is there something error with yugabyteDB by pqsql?

**Comment by d-uspenskiy** [comment] 2019-07-30 10:49
@halleyshx `yb-sample-apps.jar` is just a tool to test existed YB cluster. YB cluster can be built in `debug` or `release` mode. Could you please provide me with exact command which was used to build YB source code? 

BTW:
I've reproduced the problem you had mentioned on `debug` YB build. But there is no such issue on `release` build. Reason - `release` build is much more faster than `debug` there is no timeout issue.

**Comment by halleyshx** [comment] 2019-07-30 15:35
@d-uspenskiy Oh,sorry,I got it.Before this,I think that the release is about testing tool.   I don't build YB source code.I wget from the web with the command of `wget https://downloads.yugabyte.com/yugabyte-1.3.0.0-linux.tar.gz`.      The output of yb-ctl start command was different from yours. For the detials ,we can see https://github.com/YugaByte/yugabyte-db/issues/1933

**Comment by ttyusupov** [comment] 2019-08-01 11:16
> Thanks, I found the postgresql.conf and change the max_connections to 2100. 
...
> For the detials, we can see #1933

Hi @halleyshx , should we then close this ticket and continue investigation in #1933 ?

**Comment by ttyusupov** [comment] 2019-08-08 17:36
Closing this, since #1933 was created to track the rest.

**Closed by ttyusupov** 2019-08-08 17:36 UTC
Labels: community/request
