### ISSUE TITLE
[YCQL] Invalidate prepared statements on schema changes

### ISSUE THREAD

**Issue by codiyampa** [yugabyte/yugabyte-db#4750] opened 2020-06-11 17:51 UTC
Jira Link: [DB-4665](https://yugabyte.atlassian.net/browse/DB-4665)
When a table in YCQL is deleted and then recreated with an additional column (such things are done during development) or in general on schema changes like ALTER TABLE, prepared statements are not deleted and become invalid.

This results in following exceptions in the Java driver.
```
java.lang.IllegalArgumentException: set_notifications is not a column defined in this metadata
	at com.datastax.driver.core.ColumnDefinitions.getAllIdx(ColumnDefinitions.java:272)
	at com.datastax.driver.core.ColumnDefinitions.getFirstIdx(ColumnDefinitions.java:278)
	at com.datastax.driver.core.ArrayBackedRow.getIndexOf(ArrayBackedRow.java:85)
	at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:200)

OR

com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [int <-> java.lang.Long]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:822)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:665)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:647)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:572)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:80)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:203)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:148)
```

I also found these issues which address this topic.

https://issues.apache.org/jira/browse/CASSANDRA-7566
https://issues.apache.org/jira/browse/CASSANDRA-7910
https://issues.apache.org/jira/browse/CASSANDRA-10786
https://datastax-oss.atlassian.net/browse/JAVA-420
https://datastax-oss.atlassian.net/browse/JAVA-560

These issues are fixed with Cassandra version 4.0 and native protocol v5.

**Comment by m-iancu** [comment] 2023-01-22 23:32
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/10774 (which was fixed recently).

**Closed by m-iancu** 2023-01-22 23:32 UTC
Labels: kind/bug, priority/medium, community/request, area/ycql
