### ISSUE TITLE
[DocDB] Tserver remains in un-usable state especially for Inserts(Writes) when it hits memory soft limit

### ISSUE THREAD

**Issue by shantanugupta-yb** [yugabyte/yugabyte-db#13498] opened 2022-08-01 13:36 UTC
Jira Link: [DB-3094](https://yugabyte.atlassian.net/browse/DB-3094)
### Description

When tserver hits soft mempry limit we start rejecting/failing writes but we proactively dont cleanup freeable memory or GC on tc malloc internals. Cause of this unless we restart tserver it will continue holding the memory footprints and rejecting writes. 

tserver's memory usage from memtracker page. 

<img width="188" alt="image" src="https://user-images.githubusercontent.com/85676531/182159958-cd460a68-b6f9-419a-88fe-4e49bb5d493c.png">

Errors observed:
> ```
> ./yb-tserver.ip-10-8-7-61.us-west-2.compute.internal.yugabyte.log.WARNING.20220726-065450.32490:43035:W0726 13:03:12.646066 12469 yb_rpc.cc:392] Call yb.tserver.PgClientService.UpdateSequenceTuple 10.8.7.61:43984 => 10.8.7.61:9100 (request call id 3572) took 130962ms (client timeout 120000ms).
> ./yb-tserver.WARNING:43034:W0726 13:03:12.642804 8970 yb_rpc.cc:392] Call yb.tserver.PgClientService.UpdateSequenceTuple 10.8.7.61:43986 => 10.8.7.61:9100 (request call id 3572) took 130950ms (client timeout 120000ms).
> I0726 13:01:03.757256 32520 maintenance_manager.cc:340] we have exceeded our soft memory limit (current capacity is 93.23%). However, there are no ops currently runnable which would free memory.
> W0726 13:01:03.820058 11005 wire_protocol.cc:251] Unknown error code in status:
> I0726 13:01:03.872404 18971 raft_consensus.cc:1704] T dd215100715042b7a0d43d2e86c5d25c P bab02faf2e9c4acb8e3ff71fde4c2a99 [term 27 FOLLOWER]: Refusing update from remote peer b930dcb1bc0a4137bd05165238197e14: Log matching property violated. Preceding OpId in replica: 27.25214. Preceding OpId from leader: 27.25216. (index mismatch)
> I0726 13:01:03.872442 18971 raft_consensus.cc:1934] T dd215100715042b7a0d43d2e86c5d25c P bab02faf2e9c4acb8e3ff71fde4c2a99 [term 27 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 27.25214. Preceding OpId from leader: 27.25216. (index mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1702 errors: "\000" } }
> W0726 13:03:12.642645 32501 tablet_rpc.cc:475] Timed out (yb/rpc/rpc.cc:224): Failed Write(tablet: 01f3dee684be44a8bba7ae11f632bb9a, num_ops: 1, num_attempts: 10, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) to tablet 01f3dee684be44a8bba7ae11f632bb9a on tablet server { uuid: 3c021173915e4be782288caa9b2831a5 private: [host: "10.8.0.138" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" after 10 attempt(s): Write(tablet: 01f3dee684be44a8bba7ae11f632bb9a, num_ops: 1, num_attempts: 10, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) passed its deadline 606499.493s (passed: 130.943s): Remote error (yb/rpc/outbound_call.cc:414): Service unavailable (yb/tserver/service_util.cc:378): Soft memory limit exceeded (at 100.59% of capacity), score: 0.00 (rpc error 4)
```

**Comment by rthallamko3** [comment] 2024-03-22 18:52
Closing this as this behavior is by design. We might consider adding a dynamic memory management scheme in the future.

**Closed by rthallamko3** 2024-03-22 18:52 UTC
Labels: kind/enhancement, area/docdb, priority/medium
