### ISSUE TITLE
[YSQL] EXPLAIN ANALYZE can't display the number of rows fetched from DocDB

### ISSUE THREAD

**Issue by yzhong-yb** [yugabyte/yugabyte-db#16260] opened 2023-02-28 15:35 UTC
Jira Link: [DB-5685](https://yugabyte.atlassian.net/browse/DB-5685)
### Description

When running a query with EXPLAIN ANALYZE, the `actual rows` value on each plan node represents the number of rows that node yielded to the node above it.
```
yugabyte=# explain (analyze, dist) select * from i limit 10;
                                                 QUERY PLAN
-------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..1.00 rows=10 width=8) (actual time=4.231..4.247 rows=10 loops=1)
   ->  Seq Scan on i  (cost=0.00..100000.00 rows=1000000 width=8) (actual time=4.225..4.236 rows=10 loops=1)
                                                                                            ^^^^^^^
         Storage Table Read Requests: 1
         Storage Table Execution Time: 3.428 ms
 Planning Time: 0.138 ms
 Execution Time: 4.544 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 3.428 ms
 Peak Memory Usage: 0 kB
(10 rows)
   ```
In the above query, we push down the LIMIT so that we don't fetch any more rows than necessary, meaning that the number of rows actually fetched from DocDB is equal to the number of rows yielded.
However, in certain situations, the number of rows fetched may be greater than the number of rows yielded. Take the following queries that nest a LIMIT inside another LIMIT:

```
yugabyte=# explain (analyze, dist) select * from (select * from i limit 1000) as alias limit 10;
                                                     QUERY PLAN
---------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..1.10 rows=10 width=8) (actual time=31.195..31.212 rows=10 loops=1)
   ->  Limit  (cost=0.00..100.00 rows=1000 width=8) (actual time=31.192..31.204 rows=10 loops=1)
         ->  Seq Scan on i  (cost=0.00..100000.00 rows=1000000 width=8) (actual time=31.185..31.195 rows=10 loops=1)
               Storage Table Read Requests: 1
               Storage Table Execution Time: 30.513 ms
 Planning Time: 0.243 ms
 Execution Time: 31.618 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 30.513 ms
 Peak Memory Usage: 14 kB
(11 rows)

yugabyte=# explain (analyze, dist) select * from (select * from i limit 10) as alias limit 10;
                                                    QUERY PLAN
-------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..1.10 rows=10 width=8) (actual time=3.173..3.187 rows=10 loops=1)
   ->  Limit  (cost=0.00..1.00 rows=10 width=8) (actual time=3.171..3.181 rows=10 loops=1)
         ->  Seq Scan on i  (cost=0.00..100000.00 rows=1000000 width=8) (actual time=3.168..3.176 rows=10 loops=1)
               Storage Table Read Requests: 1
               Storage Table Execution Time: 2.602 ms
 Planning Time: 0.161 ms
 Execution Time: 3.469 ms
 Storage Read Requests: 1
 Storage Write Requests: 0
 Storage Execution Time: 2.602 ms
 Peak Memory Usage: 14 kB
(11 rows)
```

In the first query, the Seq Scan is fetching 1000 rows and yielding 10, while in the second query the Seq Scan is fetching 10 rows and yielding 10; this leads to the first query taking a lot longer to execute than the second.

For situations like this, it would be useful if we have an option for EXPLAIN ANALYZE to display the number of rows fetched.

Currently, we can `set yb_debug_log_docdb_requests to true` in the psql session and read the postgres log file to see the `limit` for each request: the number of rows included in the response will be less than or equal to this limit. This may be a good enough solution.

[DB-5685]: https://yugabyte.atlassian.net/browse/DB-5685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment] 2023-10-25 17:49
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/12344

**Closed by sushantrmishra** 2023-10-25 17:49 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
