### ISSUE TITLE
[Platform] GCP  Provider Configuration is not allowing to create a new VPC

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#7941] opened 2021-04-06 17:59 UTC
Description:

When specifying to Create a new VPC, the VPC is not created if a VPC named “yb-gcp-network” already exists. Instead, it uses this existing VPC and continues.

--screenshot--

![GCP screenshot](https://user-images.githubusercontent.com/38830089/113747045-fbffa380-96d4-11eb-912e-304f86f92a1d.png)

Problem Solved:
There should be a VPC Name parameter for the “Create a new VPC” option. If there is already a VPC with that name, it should fail.

Reference Ticket: #1052

**Comment by SergeyPotachev** [comment] 2021-04-12 15:40
Duplicate of #7934.

**Closed** 2021-04-14 02:50 UTC
Labels: area/platform, kind/new-feature
