### ISSUE TITLE
[YCQL] Cached prepared statements don't get updated on schema change

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#1427] opened 2019-05-23 20:29 UTC
Jira Link: [DB-4703](https://yugabyte.atlassian.net/browse/DB-4703)
Reproduction steps:

1) Create a table:
```cql
CREATE TABLE t (pk int PRIMARY KEY, v int, v2 int);
```

2) Run a simple prepared statement (in Java in this case). You don't even have to have bind variables.
```java
session.execute(session.prepare("SELECT * FROM t").bind());
```

3) Update schema, removing `v2`:
```cql
ALTER TABLE t DROP v2;
```

4) Run the client again:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.datastax.driver.core.ArrayBackedRow.toString(ArrayBackedRow.java:121)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at com.yugabyte.CqlPlayground.main(CqlPlayground.java:55)
```

5) After one error, all subsequent runs would work normally.

**Comment by OlegLoginov** [comment] 2023-01-17 08:39
Closing as a duplicate of the fixed issue: https://github.com/yugabyte/yugabyte-db/issues/10774

**Closed by OlegLoginov** 2023-01-17 08:39 UTC
Labels: kind/bug, priority/medium, area/ycql
