### ISSUE TITLE
[YB] Uni-direction replication: missing rows

### ISSUE THREAD

**Issue by ryli17** [yugabyte/yugabyte-db#4257] opened 2020-04-20 19:39 UTC
Yugabyte version: 2.1.3

repro:
Create two universe. Create the following schema on both universes:
Create database uni;
\c uni
CREATE TABLE uni_tbl(c1 int, c2 text);

setup uni-direction replication followed by https://docs.yugabyte.com/latest/deploy/multi-dc/2dc-deployment/#4-load-data-into-producer-universe

Script:
```
# cat uni-direction-replica.sh
#!/bin/sh
CMD=~/yugabyte-2.1.2.0/bin/yb-admin
params=( -master_addresses 10.88.181.5:7100,10.88.181.9:7100,10.88.181.19:7100 )
params+=( setup_universe_replication b1143448-7448-41f4-9f30-d72dc1803935 )
params+=( 10.88.181.1:7100,10.88.181.3:7100,10.88.181.11:7100 )
params+=( 00004000000030008000000000004001 )
 
$CMD ${params[@]}
```

-- inset 1000 rows with c1 1~1000, on producer

After a while, check rows on consumer
On producer:
```
[ryli@localhost packet-vm]$ ysqlsh -h 147.75.68.23 -d uni -c "select count(*) from uni_tbl"
count
-------
1000
(1 row
```)

On consumer:
```
[ryli@localhost packet-vm]$ ysqlsh -h 147.75.69.21 -d uni -c "select count(*) from uni_tbl"
count
-------
948
(1 row)
```

**Comment by ndeodhar** [comment] 2020-04-21 21:38
Update:
I'm able to reproduce this using these steps:
1. Create two clusters
`./bin/yb-ctl create --data_dir ~/producer_cluster --ip_start 1`
`./bin/yb-ctl create --data_dir ~/consumer_cluster --ip_start 11`

2. Create the same table on both clusters
```
./bin/ysqlsh -h 127.0.0.1
CREATE TABLE uni_tbl(c1 int, c2 text);
```
```
./bin/ysqlsh -h 127.0.0.11
CREATE TABLE uni_tbl(c1 int, c2 text);
```

3. Setup one way replication
```
./bin/yb-admin -master_addresses 127.0.0.11 setup_universe_replication <producer_uuid> 127.0.0.1 <producer_table_id>
```

4. Write 1000 rows on producer
```
./bin/ysqlsh -h 127.0.0.1
INSERT INTO uni_tbl SELECT generate_series(1,1000);
SELECT count(*) FROM uni_tbl; // Shows 1000. rows
```

5. Check replicated rows on consumer
```
./bin/ysqlsh -h 127.0.0.11
SELECT count(*) FROM uni_tbl; // Shows 700-800 rows.
```

This seems be unrelated to consensus max batch size. Tried increasing it to 32 MB and still see the same problem.
Note that cdc_state table shows the checkpoint to be advanced but we're missing some of the rows from the `write_batch` on consumer.

**Comment by bmatican** [comment] 2020-04-30 19:12
Wanted to jot down current hypothesis, to see if we can try to setup a unit test to repro this.

T1 (GetChanges):
1) read from the WAL, potentially to the end
2) check the status of the txn

T2 (Writes)
1) normal inserts
2) final APPLYING message

T3 (Transaction status)
1) Send the apply (after all writes were done)
2) Clear status of this txn

The sequence of operations that we assume is causing the problem is then:
T2.1 All inserts come in
T1.1 Read to the end of the WAL, capturing all write ops, but not the apply record << mark `have_more_messages=false`
T3.1 Apply message is sent
T2.2 Apply record comes, thus not captured by the GetChanges
T3.2 Txn info is removed
T1.2 Check for the status of this txn, potentially its state is cleaned up now, so we get a `NotFound`

So perhaps we could add some sleeps at:
- (small one) T2.2, before we add the apply record to the LogCache. This should help increase the probability that the apply record is not read from the log and `GetChanges` thinks it has no more messages.
- (larger one) T1.2, before we check the status. Increase chance we get a `NotFound` because the txn info has been removed.
cc @nspiegelberg @ndeodhar

**Comment by nspiegelberg** [comment] 2020-05-21 21:11
This bug should be fixed in the next release.  It is specific to PGSQL and transactions (generate_series creates a transaction).

**Closed** 2020-06-23 17:18 UTC
Labels: area/cdc, community/request
