### ISSUE TITLE
[DocDB] FATAL Check failed: calls_.empty while exercising failing DDLs with cross-db DDL

### ISSUE THREAD

**Issue by archit-rastogi** [yugabyte/yugabyte-db#21794] opened 2024-04-03 04:53 UTC
Jira Link: [DB-10685](https://yugabyte.atlassian.net/browse/DB-10685)
### Description

Encountered below FATAL on build `2.23.0..0-b104`
```
F20240403 04:21:38 ../../src/yb/rpc/rpc.cc:339] Check failed: calls_.empty() Calls: [0x000016653c3ef920 -> GetTransactionStatus: tablet_id: "f139e94b19304e22808a4056c5e8bd3a" transaction_id: "\355\003\335\375\310RK\021\205\300qc\341\274\035\215", retrier: { task_id: -1 state: kFinished deadline: 653.463s }]
    @     0xaaaad018aafc  google::LogMessage::SendToLog()
    @     0xaaaad018b9a0  google::LogMessage::Flush()
    @     0xaaaad018c03c  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaad13b0d68  yb::rpc::Rpcs::Shutdown()
    @     0xaaaad0f00a98  yb::master::PollTransactionStatusBase::~PollTransactionStatusBase()
    @     0xaaaad0f05108  yb::master::TableSchemaVerificationTask::~TableSchemaVerificationTask()
    @     0xaaaad0b0dc34  yb::master::CatalogEntityWithTasks::AbortTasksAndCloseIfRequested()
    @     0xaaaad0bb6e08  yb::master::CatalogManager::DeleteTableInMemory()
    @     0xaaaad0bb22e8  yb::master::CatalogManager::DeleteTableInternal()
    @     0xaaaad0efd514  yb::master::CatalogManager::YsqlDdlTxnDropTableHelper()
    @     0xaaaad0efc0d0  yb::RunnableImpl<>::Run()
    @     0xaaaad1c3e258  yb::ThreadPool::DispatchThread()
    @     0xaaaad1c3a9d8  yb::Thread::SuperviseThread()
    @     0xffffb31778b8  start_thread
    @     0xffffb31d3afc  thread_start
```

Attempt 1: http://stress.dev.yugabyte.com/stress_test/2fe71a88-36d2-4baa-ab06-3d0aa9ea0b98
Attempt 2: http://stress.dev.yugabyte.com/stress_test/3246a317-d22c-4b39-8e93-f22b5c6d0e36

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10685]: https://yugabyte.atlassian.net/browse/DB-10685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment] 2024-04-08 18:35
duplicate of #21773

**Closed by myang2021** 2024-04-08 18:35 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage
