### ISSUE TITLE
[YCQL] Prepared statement cache does not get invalidated correctly

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#3500] opened 2020-01-30 19:24 UTC
Jira Link: [DB-4692](https://yugabyte.atlassian.net/browse/DB-4692)
The prepared statements cache on each tserver is indexed by the statement string.
So if a statement is being prepared with identical syntax (as a previous statement) but different semantics the prepare step can return the wrong prepared statement (and then the subsequent executes of that prepared statement may error out or misbehave).

This could happen if a table was dropped and re-created with the same schema, or a column's type was altered (e.g. via `rename column a->old_a`, `add column a`, `remove column old_a`).

To replicate:
#### Create a simple table. 
```
create keyspace sample;
use sample;
create table test(a int, b int, c int, primary key(a));
```
#### Prepare and execute a statement in an app.
```
import com.datastax.driver.core._
import java.util._

val cluster = Cluster.builder().addContactPoint("127.0.0.1").build()
val session = cluster.connect()
val pstmt = session.prepare("insert into sample.test(a,b,c) values (?,?,?)");
session.execute(pstmt.bind(1,1,1));
```

#### Drop/recreate a table with exactly the same name and column names (but different types).

```
use sample;
drop table test;
create table test(a int, b text, c int, primary key(a));
```

#### Restart the app (or in a new app) prepare and execute same stmt against the new table
```
import com.datastax.driver.core._
import java.util._

val cluster = Cluster.builder().addContactPoint("127.0.0.1").build()
val session = cluster.connect()
// Using same query string as before (but now column b should have text type).
val pstmt = session.prepare("insert into sample.test(a,b,c) values (?,?,?)");
session.execute(pstmt.bind(1,"a",1));
```
will now return
```
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [int <-> java.lang.String]
  at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
  at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:540)
  at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:520)
  at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:470)
  at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
  at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:201)
  at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
  ... 28 elided
```

**Comment by OlegLoginov** [comment] 2020-01-31 17:39
Java reproducer:
```
  @Test
  public void testPrepareAfterTableDrop() throws Exception {
    LOG.info("Start test: " + getCurrentTestMethodName());
    String stmt = "insert into test_tbl(a,b) values (?,?);";

    session.execute("create table test_tbl(a int primary key, b int);");
    PreparedStatement insert1 = session.prepare(stmt);
    session.execute(insert1.bind(1, 1));
    assertQueryRowsUnordered("select * from test_tbl;", "Row[1, 1]");
    session.execute("drop table test_tbl;");

    // Recreate the table with the same table name and column names, but with another
    // column types and the prepared statement. 
    session.execute("create table test_tbl(a int primary key, b text);");
    PreparedStatement insert2 = session.prepare(stmt);
    session.execute(insert2.bind(1, "a"));
    assertQueryRowsUnordered("select * from test_tbl;", "Row[1, a]");
    session.execute("drop table test_tbl;");

    LOG.info("End test: " + getCurrentTestMethodName());
  }
```
Result:
```
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [int <-> java.lang.String]
     at org.yb.cql.TestPrepareExecute.testPrepareAfterTableDrop(TestPrepareExecute.java:358)
```

**Comment by OlegLoginov** [comment] 2020-01-31 17:42
The used cache is located here:
```
class CQLServiceImpl : public CQLServerServiceIf,
                       public GarbageCollector,
                       public std::enable_shared_from_this<CQLServiceImpl> {
...
  // Prepared statements cache.
  CQLStatementMap prepared_stmts_map_;  <<<<<
```
The key in the map: `std::string = QueryId = MD5_HASH(keyspace_name:string + prepared_statement:string)`

**Comment by OlegLoginov** [comment] 2020-02-04 12:25
Similar issue:   https://github.com/scylladb/scylla/issues/139

**Comment by frozenspider** [comment] 2020-02-06 16:33
Apparently a duplicate of #1425

**Closed** 2023-01-17 08:38 UTC
Labels: kind/bug, priority/high, area/ycql
