### ISSUE TITLE
[YSQL] Corrupted table after concurrently add/remove column

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#10934] opened 2021-12-23 13:48 UTC
Jira Link: [DB-998](https://yugabyte.atlassian.net/browse/DB-998)
### Description

Table became corrupted, no DML operations available of it
```
select * from postgresqlkeyvalue;  
[XX000] ERROR: Invalid argument: Invalid column number 18
```

Scenario is based on SqlInserts. On write stage we also have possibility to add column, here is schematic code:
```
doWrite() {
 if (numberOfWrites.get() > 5000 && random.nextInt(20) <= 1) {
   if (columnSize > 5) {
      "ALTER TABLE %s DROP COLUMN %s"
   } else {
      "ALTER TABLE %s ADD COLUMN %s text DEFAULT 'PostgresqlKeyValue'"
   }
 } else {
 // standard SqlInserts write
 }
}
```

**Comment by tedyu** [comment] 2021-12-24 09:50
I have a tentative patch which treats AT_DropColumn as breaking catalog change in src/postgres/src/backend/utils/misc/pg_yb_utils.c

Trying to write a test.

**Comment by myang2021** [comment] 2022-01-03 17:59
I looked into this bug. I think it should be a known issue that has to do with with YSQL not
supporting transactional DDL. Here is the sequence of events that can lead to the symptom of "ERROR:
Invalid argument: Invalid column number 18".

1. Once session starts executing "alter table t drop column v1".
2. This is a considered as a DDL statement.
3. Although a separate DDL transaction is created for any DDL statement, this separate transaction
itself isn't fully respected. Execution of "alter table t drop column v1" involves two parts:
3.1. updating a number of pg_* tables (e.g., pg_attribute).
3.2. updating sys catalog table with new DocDB schema for table t.

Note that 3.1 is under the control of the DDL transaction. However, 3.2 is writting into sys catalog
table, which is also used to store other database objects such as YQL tables. More over sys catalog
table itself is not a transactional table.

It appears that 3.1 is executed first, which involves writing to intents DB of various pg_* tables
due to the DDL transaction. Once 3.1 completes succussfully, 3.2 is executed next. Because 3.2 isn't
transactional, it directly updates the regular DB of sys catalog table. It seems to me that sys
catalog table does not even use intents DB at all. Note that at this time, the DDL transaction
hasn't committed yet.

4. Another session starts executing "alter table t add/drop ...".
5. Due to transaction conflict resolution, the seconc transaction actually wins out. The previous
transaction is aborted. This means that those updates made in the intents DB of pg_* tables will not
be applied to the regular DB of pg_* tables. As a result, column v1 will continue to exist according
to the contents of regular DB of pg_* tables. However, according to the regular DB of sys
catalog table, v1 is already dropped because 3.2 directly updated the regular DB of sys catalog
table successfully.

6. The execution of "select * from t" involves both pg_* table and the new table t schema stored in
sys catalog table. They are now inconsistent: pg_* contents say there is a column v1 because the
previous step 3.1 was aborted, sys catalog table says that there is no column v1 because 3.2 has
completed successfully.

I think this is a flaw of the current design of YSQL DDL execution. It is YSQL specific because its
DDL transaction is half-baked with YSQL distributed transaction mechanism that involves writing
provisional records in intents DB but it also uses the YQL transaction mechanism that has no concept
of provisional records or intents DB.

In order to fix the problem, 3.2 should not write directly into the regular DB of sys catalog table.
It should write to intents DB of sys catalog table, so that both 3.1 and 3.2 are protected by the
same YSQL DDL transaction. In this way, they are both commited, or both rolled back and will not
leave 3.1 rolled back + 3.2 committed.

**Comment by bmatican** [comment] 2022-01-07 15:05
@qvad @tedyu To clarify though, is the example in the issue actually multi-threaded? My understanding is that NO. We have 1 single session and we do one operation at a time, which every now and then is a DDL operation.

So then @myang2021 , this part doesn't make sense / fit
> Another session starts executing "alter table t add/drop ...".

**Comment by myang2021** [comment] 2022-01-07 17:13
@bmatican , I'll let @qvad clarify the multi-threaded question. However, when I tried to manually reproduce the bug on my dev vm, I simply started two concurrent sessions, so with that I was able to reproduce the bug. I tried single session add/drop column repeatedly and it was fine.

However, that does not mean single threaded or single session is bullet proof from the corruption. Imagine the PG process got killed or network partitioned so that the alter table drop column txn never commits, yet part 3.2 already "committed" into regular DB, we'll see the same problem.

**Comment by deeps1991** [comment] 2022-07-19 16:00
This is a side-effect of https://github.com/yugabyte/yugabyte-db/issues/13358

**Comment by deeps1991** [comment] 2022-07-19 16:06
This is a side-effect of https://github.com/yugabyte/yugabyte-db/issues/13358

**Comment by deeps1991** [comment] 2022-07-19 16:06
This is a side-effect of https://github.com/yugabyte/yugabyte-db/issues/13358

**Comment by deeps1991** [comment] 2022-07-19 22:19
Duplicate of #13358

**Comment by tverona1** [comment] 2023-10-25 17:56
Closing as duplicate

**Closed** 2023-10-25 17:56 UTC
Labels: kind/bug, area/ysql, priority/medium
