### ISSUE TITLE
ThreadSanitizer check failure in LinkedListTest_TestLoadAndVerify

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14243] opened 2022-09-29 04:47 UTC
Jira Link: [DB-3702](https://yugabyte.atlassian.net/browse/DB-3702)
### Description

ThreadSanitizer check failure in LinkedListTest_TestLoadAndVerify in latest master - 2.15.4.0-b40
Stacktrace https://gist.github.com/kripasreenivasan/1d02024584306497c2170a2bb27822e4

**Comment by bmatican** [comment] 2022-09-29 14:14
Duplicate of #14098

**Closed by bmatican** 2022-09-29 14:14 UTC
Labels: kind/bug, area/docdb, priority/medium, status/awaiting-triage, qa_automation
