### ISSUE TITLE
[DocDB] After running a big insertion, some tablet level name/value statistics show likely incorrect values

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#13842] opened 2022-09-02 13:54 UTC
Jira Link: [DB-3341](https://yugabyte.atlassian.net/browse/DB-3341)
### Description

Version: version 2.15.0.0 build 11 revision f95dc2a45454d4d43455bb847ed781e7e70e9242
Running on: linux Alma 8.6
YSQL

I created the table in the following way: 
`create table large as select id, repeat('x',500) f1 from generate_series(1,1000000) id;`

Statistics:
rocksdb_compaction_active_tasks     value: 18446744073676186577
rocksdb_compaction_paused_tasks  value: 18446744073676096026
rocksdb_compaction_queued_tasks value: 18446744073676090583

**Comment by rthallamko3** [comment] 2022-09-14 04:30
@jmeehan16 , This looks like a duplicate of https://github.com/yugabyte/yugabyte-db/issues/12795. Closing it for now. Feel free to reopen this if you feel otherwise.

**Closed by rthallamko3** 2022-09-14 04:30 UTC
Labels: kind/bug, area/docdb, priority/medium
