### ISSUE TITLE
[YSQL] Potential race issue with pggate

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#17490] opened 2023-05-22 16:48 UTC
Jira Link: [DB-6648](https://yugabyte.atlassian.net/browse/DB-6648)
### Description

steps to repo
```
./yb_build.sh tsan --gtest_filter PgLibPqTest.TestStatementTimeout
```

race warnings being reported
```
WARNING: ThreadSanitizer: data race (pid=3091719)
  Write of size 4 at 0x7b60000022d4 by thread T15:
    #0 pqReadData /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-misc.c (libpq.so.5+0x3f4e0)
    #1 PQgetResult /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1784:4 (libpq.so.5+0x3a573)
    #2 PQexecFinish /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:2069:19 (libpq.so.5+0x3ac3a)
    #3 PQexec /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1903:9 (libpq.so.5+0x3aa38)
    #4 yb::pgwrapper::PGConn::Execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:315:19 (libpq_utils.so+0x11d37)
    #5 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3566:20 (pg_libpq-test+0x233ffb)
    #6 decltype(std::declval<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()>()()) std::__1::__invoke[abi:v15003]<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (pg_libpq-test+0x233ffb)
    ...
  Previous read of size 4 at 0x7b60000022d4 by main thread:
    #0 pqParseInput3 /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-protocol3.c:82:26 (libpq.so.5+0x459e5)
    #1 parseInput /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1721:3 (libpq.so.5+0x3a387)
    #2 PQisBusy /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1738:2 (libpq.so.5+0x3a387)
    #3 yb::pgwrapper::PGConn::IsBusy() /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:337:10 (libpq_utils.so+0x128f1)
    #4 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3569:5 (pg_libpq-test+0x234832)
    #5 decltype(std::declval<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>()()) std::__1::__invoke[abi:v15003]<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (pg_libpq-test+0x234832)
    ...

SUMMARY: ThreadSanitizer: data race /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-misc.c in pqReadData
```

```
WARNING: ThreadSanitizer: data race (pid=3091719)
  Read of size 4 at 0x7b6000002114 by main thread:
    #0 PQisBusy /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1741:15 (libpq.so.5+0x3a3a2)
    #1 yb::pgwrapper::PGConn::IsBusy() /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:337:10 (libpq_utils.so+0x128f1)
    #2 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3569:5 (pg_libpq-test+0x234832)
    #3 decltype(std::declval<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>()()) std::__1::__invoke[abi:v15003]<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (pg_libpq-test+0x234832)
    #4 yb::Result<bool> std::__1::__invoke_void_return_wrapper<yb::Result<bool>, false>::__call<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:470:16 (pg_libpq-test+0x234832)
    #5 std::__1::__function::__alloc_func<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'(), std::__1::allocator<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()>, yb::Result<bool> ()>::operator()[abi:v15003]() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:185:16 (pg_libpq-test+0x234832)
    ...
  Previous write of size 4 at 0x7b6000002114 by thread T15:
    #0 PQsendQuery /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1225:20 (libpq.so.5+0x397b5)
    #1 PQexec /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1901:7 (libpq.so.5+0x3aa2c)
    #2 yb::pgwrapper::PGConn::Execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:315:19 (libpq_utils.so+0x11d37)
    #3 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3566:20 (pg_libpq-test+0x233ffb)
    #4 decltype(std::declval<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()>()()) std::__1::__invoke[abi:v15003]<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (pg_libpq-test+0x233ffb)
    #5 yb::Status std::__1::__async_func<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()>::__execute<>(std::__1::__tuple_indices<>) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/future:2169:16 (pg_libpq-test+0x233ffb)
    ...
SUMMARY: ThreadSanitizer: data race /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1741:15 in PQisBusy
```

```
WARNING: ThreadSanitizer: data race (pid=3091719)
  Write of size 4 at 0x7b60000022d8 by main thread:
    #0 pqParseInput3 /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-protocol3.c:82:18 (libpq.so.5+0x459f8)
    #1 parseInput /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1721:3 (libpq.so.5+0x3a387)
    #2 PQisBusy /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1738:2 (libpq.so.5+0x3a387)
    #3 yb::pgwrapper::PGConn::IsBusy() /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:337:10 (libpq_utils.so+0x128f1)
    #4 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3569:5 (pg_libpq-test+0x234832)
    #5 decltype(std::declval<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>()()) std::__1::__invoke[abi:v15003]<yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&>(yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda0'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230316131303-350f06229b-almalinux8-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (pg_libpq-test+0x234832)
    ...
  Previous write of size 4 at 0x7b60000022d8 by thread T15:
    #0 pqParseInput3 /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-protocol3.c:82:18 (libpq.so.5+0x459f8)
    #1 parseInput /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1721:3 (libpq.so.5+0x3a406)
    #2 PQgetResult /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1761:2 (libpq.so.5+0x3a406)
    #3 PQexecFinish /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:2069:19 (libpq.so.5+0x3ac3a)
    #4 PQexec /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-exec.c:1903:9 (libpq.so.5+0x3aa38)
    #5 yb::pgwrapper::PGConn::Execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/libpq_utils.cc:315:19 (libpq_utils.so+0x11d37)
    #6 yb::pgwrapper::PgLibPqTestStatementTimeout::ExpectBlockedAsync(yb::pgwrapper::PGConn*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'()::operator()() const /nfusr/dev-server/bkolagani/code/yugabyte-db/build/tsan-clang15-dynamic-ninja/../../src/yb/yql/pgwrapper/pg_libpq-test.cc:3566:20 (pg_libpq-test+0x233ffb)
    ...
SUMMARY: ThreadSanitizer: data race /nfusr/dev-server/bkolagani/code/yugabyte-db/src/postgres/src/interfaces/libpq/../../../../../../src/postgres/src/interfaces/libpq/fe-protocol3.c:82:18 in pqParseInput3
```

I can see `PQisBusy` present in each of the reported race warnings. https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/yql/pgwrapper/libpq_utils.cc#L337. Also, this utility func is being called on an active `PGConn` that has a statement progressing in the backend. https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/yql/pgwrapper/pg_libpq-test.cc#L3563

Is there a way we can still have this utility function, avoiding the race?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6648]: https://yugabyte.atlassian.net/browse/DB-6648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by deeps1991** [comment] 2023-05-23 02:21
Duplicate of #17295

**Closed by deeps1991** 2023-05-23 02:21 UTC
Labels: kind/bug, area/ysql, priority/medium
