### ISSUE TITLE
[docdb] org.yb.pgsql.TestIndexBackfill.insertsWhileCreatingIndex flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10367] opened 2021-10-20 17:13 UTC
detective link: https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.pgsql.TestIndexBackfill&name=insertsWhileCreatingIndex

**Comment by jaki** [comment] 2021-10-20 17:46
Duplicate of #7376 and #10294.

**Closed by jaki** 2021-10-20 17:46 UTC
Labels: area/ysql, kind/failing-test, area/docdb, priority/high
