### ISSUE TITLE
[YCQL] INSERT/UPDATE with IF NOT EXISTS may results in "Duplicate request"

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#2542] opened 2019-10-09 17:40 UTC
Jira Link: [DB-4677](https://yugabyte.atlassian.net/browse/DB-4677)
Few of our tests occasionally fails with something like this:
```
Execution Error. Duplicate request
UPDATE test_rs_trans set v1 = 3, v2 = 'c' WHERE h = 2 AND r = 2 IF NOT EXISTS RETURNS STATUS AS ROW
^^^^^^

or

Execution Error. Duplicate request
INSERT INTO test_unique (k, v) VALUES (?, ?) RETURNS STATUS AS ROW;
       ^^^^
```
Failing tests insert/update tables with UNIQUE INDEX created over it.

We're not sure what's causing this.

To reproduce: (reproduction rate is very low, 1/100 - once per batch run - on my machine)
```
ybd --java-test org.yb.cql.TestReturnsClause#testBatchDMLWithUniqueIndex -n 100
ybd --java-test org.yb.cql.TestReturnsClause#testReturnsStatusWithIndex -n 100
```
cc @nocaway

**Comment by OlegLoginov** [comment] 2020-01-22 15:12
A customer has faced the same issue.

CQL Statement:   UPDATE .... IF NOT EXISTS;
Result: ERROR: "Duplicate request" (code = ALREADY_PRESENT), CQL result code = EXEC_ERROR (-300)
In fact:  the statement was SUCCESSFULLY processed by the YB server.
Details:
CQL processing UPDATE statement
--> client::  TRY 1:    Send Write Request (to TS)
     --> tserver::Send Write Op to peers via RAFT
           --> returned ERROR: Timeout (due to the leader election or something else)
    --> returned ERROR: Timeout
...  after some time the write req was successfully processed by the RAFT level, but the result ([applied], key) was missed..
--> client::  TRY 2:    Send (same) Write Request (to TS)
     --> tserver::Send Write Op to peers via RAFT
           --> returned ERROR: ALREADY_PRESENT "Duplicate request"
Returning the error as it is to the user with CQL Result=Execution Error
If we get "Duplicate request" - that means that the write request was successfully handled before, but we don't know the result - it was missed due to first try timeout.
So, we cannot handle it as SUCCESS because we don't know what to return to the user.
cqlsh:a> update t set i=1 where id=1 IF NOT EXISTS;
 [applied]
-----------
      True               <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
cqlsh:a> update t set i=1 where id=1 IF NOT EXISTS;
 [applied] | id
-----------+----
     False |  1         <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Workaround:   handle the case on the user side - check(read)/update data if you get 'Duplicate request' error.

Fix (potential): we can cache results for a few last write requests (on the tablet level) - and return it as a successful result instead of 'Duplicate request'.

QUESTION: Do we need to fix it? Or it's OK to keep it as is and suggest the users the workaround?

**Comment by m-iancu** [comment] 2023-01-17 05:17
Closing as duplicate of (caused by) https://github.com/yugabyte/yugabyte-db/issues/5700.

**Closed by m-iancu** 2023-01-17 05:17 UTC
Labels: kind/bug, priority/low, area/ycql
