### ISSUE TITLE
Support for Alter table only add primary key constraint - pg_restore to YSQL DB.

### ISSUE THREAD

**Issue by lakshman-battini** [yugabyte/yugabyte-db#3812] opened 2020-03-03 08:21 UTC
Jira Link: [DB-2164](https://yugabyte.atlassian.net/browse/DB-2164)
Hello, I am trying to migrate the Postgres database to YSQL DB. Created dump of postgres db using pg_dump and trying to restore in YSQL DB using pg_restore.

pg_dump creates the create table script without any constraints, add the constraints using Alter table scripts. But in YSQL DB 'ALTER TABLE ONLY ADD CONSTRAINT PRIMARY KEY' is not yet supported.

pg_restore: error: could not execute query: ERROR:  This ALTER TABLE command is not yet supported.
Command was: ALTER TABLE ONLY <table>
    ADD CONSTRAINT <pkey> PRIMARY KEY (field);

**Comment by ddorian** [comment] 2020-03-03 08:45
@lakshman-battini can you try with [`ysql_dump`](https://docs.yugabyte.com/latest/admin/ysql-dump/) ? It should be able to create the primary key inside `create table` statement.

**Comment by ddorian** [comment] 2020-03-03 12:22
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/1104
The same recommendation for ysql_dump is mentioned there too.

**Comment by ndeodhar** [comment] 2020-03-03 14:57
Re-opening. This request is specifically to track an enhancement to pg_restore to create PKs inline (independently of ysql_dump).

**Comment by fizaaluthra** [comment] 2023-10-23 19:41
ADD PRIMARY KEY is supported (https://github.com/yugabyte/yugabyte-db/issues/1104)

**Closed by fizaaluthra** 2023-10-23 19:41 UTC
Labels: kind/enhancement, area/ysql, priority/medium, community/request
