### ISSUE TITLE
[YSQL] propagation of catalog changes leads to increased requests to master server

### ISSUE THREAD

**Issue by gr-yb** [yugabyte/yugabyte-db#9814] opened 2021-08-25 05:30 UTC
Jira Link: [DB-705](https://yugabyte.atlassian.net/browse/DB-705)
While running a load (selects and inserts) with high number of connections on a cluster with hundreds of tables and thousands of tablets, DDL changes (drop/add tables not involved with the load) cause increased connection requests to the master server that may cause the master leader server to failover and a node to fail.

This is how we produced this condition :
1. Create  3-node AWS c5.xlarge (4 cores, 8GB RAM) cluster in one Availability Zone running Yugabyte version 2.6.1-b24 with 500 gb of GP2 storage per node and the tserver `ysql_enable_auth` flag set to `true` and `ysql_max_connections` set to `400`
1. Create a database with 200 tables and 50 indexes with the default 8 tablets per table (9000 total tablets)
1. Use the sample app SqlInserts workload with 300 read and 300 write threads
1. Drop 10 tables that are not part of the SqlInserts workload

After completing these steps the master leader failed over to another server and one node failed (became unreachable).

## Create the database 

Login to the database with the yugabyte user to set the password for the postgres user:
```
ysqlsh -h <ip of database> -d yugabyte -U yugabyte
```
type `yugabyte` when prompted for the password and then type
``` 
\c postgres
ALTER ROLE postgres WITH PASSWORD 'postgres';
\q
```

Run the attached createTables.txt and createIndexes.txt files to create the tables and indexes:
```
ysqlsh -h <ip of database cluster> -d postgres -U postgres -a -f createTables.txt
```
```
ysqlsh -h <ip of database cluster> -d postgres -U postgres -a -f createIndexes.txt
```
[createTables.txt](https://github.com/yugabyte/yugabyte-db/files/7043825/createTables.txt)
[createIndexes.txt](https://github.com/yugabyte/yugabyte-db/files/7043862/createIndexes.txt)

From the platform console on the `Tables` tab you should see this if the commands worked:

![image](https://user-images.githubusercontent.com/84997113/130728063-29833f67-760f-4d21-9b15-0953482faf1c.png)

## Run the load

Get the sample app jar:
```
wget https://github.com/yugabyte/yb-sample-apps/releases/download/1.3.9/yb-sample-apps.jar
```

Run the SqlInserts workload with 300 read and 300 write threads:
```
java -jar ./yb-sample-apps.jar --workload SqlInserts --nodes <the ip:port list of cluster>  --num_unique_keys -1123123123123 --num_reads -1 --num_writes -1  --username postgres --password postgres --num_threads_read 300 --num_threads_write 300 
``` 

Wait about 2 minutes and run the attached dropTables.txt file:
```
ysqlsh -h <ip of database cluster> -d postgres -U postgres -f dropTables.txt
```
[dropTables.txt](https://github.com/yugabyte/yugabyte-db/files/7043854/dropTables.txt)

These are the errors we received:
```
145057 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 294331 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 136056 total ops  |  Uptime: 145024 ms |
148793 [Thread-204] INFO com.yugabyte.sample.apps.SqlInserts  - Failed writing key: 8ba671cb-0f91-4e6e-b4b2-ef67ad35f6f8:136056
org.postgresql.util.PSQLException: ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
  Detail: Internal error: Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:176)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:761)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
148905 [Thread-553] INFO com.yugabyte.sample.apps.SqlInserts  - Failed reading value: val:98924
org.postgresql.util.PSQLException: ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
  Detail: Internal error: Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.yugabyte.sample.apps.SqlInserts.doRead(SqlInserts.java:126)
	at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:787)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
```

The master leader server failed to another node and one of the nodes became unreachable.

**Comment by m-iancu** [comment] 2021-09-08 18:35
cc @emhna would the drop DDL part be fixed in latest by https://github.com/yugabyte/yugabyte-db/commit/0a3bdf9aabc036f17d5670357594b6e91c356cab.

**Comment by emhna** [comment] 2021-09-15 15:40
Based on this [new change](https://github.com/yugabyte/yugabyte-db/commit/0a3bdf9aabc036f17d5670357594b6e91c356cab) DROP DDL issue should not occur as described below.
This change allows transactions to succeed as long as the DMLs within the transaction block is not being performed on the table being dropped.  If the query performs on the table being dropped, then Catalog Version Mismatch error should occur because that table should no longer run any transactions on it.

This new change has been deployed to branch 2.7.2 so I would suggest upgrading the version to prevent this error.
Without this change, even if the transaction runs on different table other than the one that's being dropped, it will still run into the Catalog Version Mismatch error.

**Comment by m-iancu** [comment] 2021-09-15 16:49
Thanks @emhna -- so the `Catalog Version Mismatch` should be fixed in latest.
However, the master leader failover is likely a separate issue and still needs to be investigated.

**Comment by pilshchikov** [comment] 2021-09-29 18:12
@ymahajan @d-uspenskiy Tried to reproduce it on latest 2.6.2.0 and catch only this exceptions
```
145086 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 654888 total ops  |  Write: 36.40 ops/sec (133.87 ms/op), 674487 total ops  |  Uptime: 140037 ms | 
147675 [Thread-119] INFO com.yugabyte.sample.apps.SqlInserts  - Failed writing key: b0cc0768-b324-433c-bf46-dd727f36475c:674304
org.postgresql.util.PSQLException: ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
  Detail: Internal error: Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:176)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:761)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
```

But on 2.9.1.0-b112 node is failed in the moment of table drops and workloads starts failing because of the connection timeout
Workload log: [workload-SqlInserts.20210929130650.log](https://github.com/yugabyte/yugabyte-db/files/7254137/workload-SqlInserts.20210929130650.log)

looks like in 2.9.1.0 things getting worse

**Comment by pilshchikov** [comment] 2021-11-23 11:53
@d-uspenskiy tried to reproduce it on last fix
- Created 250 tables
- start SqlInserts workload
- wait 2 min
- starts `DROP` last 20 tables
During this process of dropping tables workload throughput is goes down
[workload-SqlInserts.20211123142235.log](https://github.com/yugabyte/yugabyte-db/files/7587724/workload-SqlInserts.20211123142235.log)

**Comment by m-iancu** [comment] 2022-03-09 18:10
Just a note: the rest of the work involved here is tracked in https://github.com/yugabyte/yugabyte-db/issues/10452.
But will keep this issue open until the improvements there are confirmed to address this issue.

**Comment by m-iancu** [comment] 2023-02-01 07:11
The key change is now landed under a tserver flag `ysql_enable_read_request_caching` (off by default for now).
See also https://github.com/yugabyte/yugabyte-db/issues/10821

Closing this issue as this is expected to fix it, but let's re-open if re-testing doesn't yield expected results.

**Closed by m-iancu** 2023-02-01 07:11 UTC
Labels: kind/enhancement, area/ysql, priority/critical, 2.12 Backport Required
