### ISSUE TITLE
yb-ctl start master should not error when yb-tserver count is less than RF

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4156] opened 2020-04-06 22:40 UTC
```
./bin/yb-ctl destroy
./bin/yb-ctl --rf 3 create
./bin/yb-ctl status
kill -9 <yb-tserver1-pid> <yb-master1-pid>
./bin/yb-ctl start_node 1 --master
./bin/yb-ctl start_node 1
```
the command `./bin/yb-ctl start_node 1 --master` will start yb-master1. however, it will throw an error even though the command will succeed. this is because there are only 2 yb-tservers present in the cluster at this point. this is not an error in the cluster configuration but rather a warning noting that the cluster is under-replicated or does not have enough yb-tservers to ensure continued fault tolerance.

**Comment by jaki** [comment] 2020-09-22 20:22
Closing as duplicate of issue #3506.

**Closed by jaki** 2020-09-22 20:22 UTC
Labels: area/tools, kind/enhancement
