### ISSUE TITLE
[DocDB] Allow specifying leader affinity per tablespace

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11804] opened 2022-03-18 22:32 UTC
### Description

We should allow for leader affinity to also be something we can support at a per-table level.
Given that tablespaces are how we currently tackle per table placement properties, this might be a smooth addition there.

```
CREATE TABLESPACE eu_central_1_tablespace WITH (
  replica_placement='{"num_replicas": 3, "placement_blocks":
    [{"cloud":"aws","region":"eu-central-1","zone":"eu-central-1a","min_num_replicas":1},
    {"cloud":"aws","region":"eu-central-1","zone":"eu-central-1b","min_num_replicas":1},
    {"cloud":"aws","region":"eu-central-1","zone":"eu-central-1c","min_num_replicas":1}]}',

   preferred_zones=[{cloud":"aws","region":"eu-central-1","zone":"eu-central-1a"},
                    {cloud":"aws","region":"eu-central-1","zone":"eu-central-1b"}]
);
```

Note: We should ensure that both of these are independent. You should be able to have tablespaces with JUST `preferred_zones` or JUST `replica_placement`, as well as both.

Further notes from slack: https://yugabyte.slack.com/archives/C4K1838GL/p1647618754150839

cc @deeps1991

**Comment by bmatican** [comment] 2022-03-24 23:10
Passing to Hari for now, but let's wait for Deepthi to be back, to sync up with her and confirm the complexity of this / that she hasn't already started on this.

**Comment by deeps1991** [comment] 2022-03-28 09:52
@bmatican I hadn't started working on it. I also took a look at the YB-Master code and YSQL code again, I guess I was wrong before, I couldn't find any additional complexity due to leader balancing being added to tablespaces. 

Also since this has 2 components - YB-Master and YSQL, let me know if I need to handle the YSQL side of it. Might be good to go through the functional spec process so that we are all on the same page w.r.t the new syntax being introduced.

**Comment by bmatican** [comment] 2022-03-29 21:59
I linked the other geo issue as well. That was covering the missing pieces (RR and leader affinity).

Agreed with @deeps1991 , since this would require some language glue, probably worth having a small FS, showcasing some examples. A-ok to decide along the way on the YSQL vs master split between you, or if @hari90 you want to try out a small SQL level change as well, I'm sure Deepthi could share an example diff from initially adding in the language glue on tablespace support for placement.

**Comment by deeps1991** [comment] 2022-04-05 18:42
Another note: We may have to consider providing an API to separately specify the leader affinity policy for the syscatalog tablet as well. cc @bmatican @hari90

**Comment by hari90** [comment] 2022-04-27 20:42
Duplicate of #8100

**Closed** 2022-04-27 20:43 UTC
Labels: area/ysql, area/docdb
