### ISSUE TITLE
postgresql : failed to add new column , but generated inconsistent data.

### ISSUE THREAD

**Issue by 54huanan** [yugabyte/yugabyte-db#8952] opened 2021-06-17 04:11 UTC
![image](https://user-images.githubusercontent.com/17645959/122329949-de687900-cf64-11eb-8a63-62d55af8d9b0.png)

As shown in above screenshots, I couldn't add column project_code.

version: PostgreSQL 11.2-YB-2.3.3.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit

**Comment by ddorian** [comment] 2021-06-17 07:18
@54huanan can you type all the commands that you ran to arrive at this error ? Including the initial `CREATE TABLE` command ?

**Comment by 54huanan** [comment] 2021-06-17 11:01
@ddorian 

I run following commands in the tableplus:
```

CREATE TABLE public.sys_role1 (
	id SERIAL NOT NULL PRIMARY KEY,
	role_name VARCHAR ( 50 ) NULL,
	remark VARCHAR ( 200 ) NULL,
	user_id_create INT8 NULL,
	gmt_create TIMESTAMP NULL,
	gmt_modified TIMESTAMP NULL,
	is_admin bool DEFAULT FALSE 
);

INSERT INTO "public"."sys_role1" ("id", "role_name", "remark", "user_id_create", "gmt_create", "gmt_modified", "is_admin") VALUES 
(1, 'admin', '', 0, NOW(), NULL, 't'),
(2, 'operator', '', 0, NOW(), NULL, 'f'),
(3, 'repaireman', '', 0, NOW(), NULL, 'f');
 
Alter table sys_role1 add column project_code varchar(50) not null;
 
Alter table sys_role1 add column project_code varchar(50);
```
and got the same errors as above attached screenshot.
If I drop column , got another error:

![Uploading image.png…]()

**Comment by ddorian** [comment] 2021-06-17 11:33
@54huanan can you try this on the [latest version](https://github.com/yugabyte/yugabyte-db/releases) ? Just tried on 2.7.1.1 and it didn't error for me:

```
./bin/ysqlsh
ysqlsh (11.2-YB-2.7.1.1-b0)
Type "help" for help.

yugabyte=# CREATE TABLE public.sys_role1 (
yugabyte(# id SERIAL NOT NULL PRIMARY KEY,
yugabyte(# role_name VARCHAR ( 50 ) NULL,
yugabyte(# remark VARCHAR ( 200 ) NULL,
yugabyte(# user_id_create INT8 NULL,
yugabyte(# gmt_create TIMESTAMP NULL,
yugabyte(# gmt_modified TIMESTAMP NULL,
yugabyte(# is_admin bool DEFAULT FALSE 
yugabyte(# );
CREATE TABLE
yugabyte=# INSERT INTO "public"."sys_role1" ("id", "role_name", "remark", "user_id_create", "gmt_create", "gmt_modified", "is_admin") VALUES 
yugabyte-# (1, 'admin', '', 0, NOW(), NULL, 't'),
yugabyte-# (2, 'operator', '', 0, NOW(), NULL, 'f'),
yugabyte-# (3, 'repaireman', '', 0, NOW(), NULL, 'f');
INSERT 0 3
yugabyte=# Alter table sys_role1 add column project_code varchar(50) not null;
ERROR:  column "project_code" contains null values
yugabyte=# Alter table sys_role1 add column project_code varchar(50);
ALTER TABLE
yugabyte=# 
```

**Comment by ddorian** [comment] 2021-07-01 14:43
Closing this as can't reproduce. If you can reproduce it on latest version please reply again.

**Closed by ddorian** 2021-07-01 14:43 UTC
Labels: area/ysql
