### ISSUE TITLE
[docdb] org.yb.cql.TestYbBackup still failing on mac

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5610] opened 2020-09-08 16:00 UTC
Jira Link: [DB-1545](https://yugabyte.atlassian.net/browse/DB-1545)

**Comment by bmatican** [comment] 2020-09-14 23:54
I've temporarily disabled both the cpp and java ones, for mac

**Comment by OlegLoginov** [comment] 2020-11-06 18:12
It's a duplicate of:  https://github.com/yugabyte/yugabyte-db/issues/4924

**Comment by OlegLoginov** [comment] 2023-01-26 18:36
Closing as a duplicate of https://github.com/yugabyte/yugabyte-db/issues/4924

**Closed by OlegLoginov** 2023-01-26 18:36 UTC
Labels: kind/bug, duplicate, kind/failing-test, area/docdb, priority/medium
