### ISSUE TITLE
[YSQL] tserver core dumps appears during testing PITR and automated tablet splitting tests

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#15150] opened 2022-11-27 10:11 UTC
Jira Link: [DB-4347](https://yugabyte.atlassian.net/browse/DB-4347)
### Description

Scenario is to upload data, create snapshot schedule
Then repeat few times:
1. Upload more data
2. Restore to the original point + some delta (to avoid pita limitations)
3. Validate data
In the end of test check that there is no FATAL or core dumps.

Core dump files are very large, collected using yugabyte-llvm package.

```
* thread #1, name = 'yb-tserver', stop reason = signal SIGSEGV
  * frame #0: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted() [inlined] std::__1::chrono::__duration_eq<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>::operator(this=<unavailable>, __lhs=<unavailable>, __rhs=<unavailable>)[abi:v15003](std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) const at duration.h:331:31
    frame #1: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted() [inlined] bool std::__1::chrono::operator==[abi:v15003]<long long, std::__1::ratio<1l, 1000000000l>, long long, std::__1::ratio<1l, 1000000000l>>(__lhs=<unavailable>, __rhs=<unavailable>) at duration.h:340:12
    frame #2: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted() [inlined] bool std::__1::chrono::operator==[abi:v15003]<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>(__lhs=0x0000000000000060, __rhs=<unavailable>) at time_point.h:148:37
    frame #3: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted() [inlined] bool std::__1::chrono::operator!=[abi:v15003]<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>(__lhs=0x0000000000000060, __rhs=<unavailable>) at time_point.h:158:20
    frame #4: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted() [inlined] yb::MonoTime::Initialized(this=0x0000000000000060) const at monotime.h:197:44
    frame #5: 0x000055b913fba8ae yb-tserver`yb::rpc::InboundCall::RecordHandlingCompleted(this=0x0000000000000000) at inbound_call.cc:177:3
    frame #6: 0x000055b913fec03c yb-tserver`yb::rpc::RpcContext::RespondSuccess(this=0x00007f25fc9bafe0) at rpc_context.cc:160:10
```

Core dumps from one of node:
[get-3.gz](https://github.com/yugabyte/yugabyte-db/files/10097988/get-3.gz)

**Comment by rthallamko3** [comment] 2022-12-06 17:17
Duplicate of #15165

**Closed** 2022-12-06 17:17 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage, tablet-splitting
