### ISSUE TITLE
[2DC] Add consumer acknowledged checkpoint to metrics

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#3607] opened 2020-02-10 17:38 UTC
While polling for `GetChanges`, consumer sends a checkpoint to producer acknowledging that it has applied all ops from the producer until that checkpoint. We store this checkpoint in `cdc_state` table and use it to control log retention.
For better visibility of replication, we should add this checkpoint to 2DC metrics as well.

**Comment by nspiegelberg** [comment] 2021-09-03 19:02
Duplicate of #2154

**Comment by nspiegelberg** [comment] 2021-09-03 19:02
D7964

**Closed by nspiegelberg** 2021-09-03 19:02 UTC
Labels: area/cdc
