### ISSUE TITLE
[YSQL] Concurrent DROP and row-level locking behave differently on a colocated table and a non-colocated table

### ISSUE THREAD

**Issue by yifanguan** [yugabyte/yugabyte-db#15727] opened 2023-01-17 16:54 UTC
Jira Link: [DB-5082](https://yugabyte.atlassian.net/browse/DB-5082)
### Description

Ran the java test `'org.yb.pgsql.TestPgExplicitLocks#testExplicitLocks'` in a colocated database setting.
A difference is noticed in how concurrent DROP and row-level locking behave in a colocated database and a non-colocated database.

Simplified repro for the issue:
Connection 1:
```
CREATE DATABASE col_db WITH COLOCATION = true;
CREATE ROLE yugabyte_test WITH LOGIN;
\c col_db yugabyte_test
CREATE TABLE explicitlocks (h int, r int);
BEGIN transaction isolation level serializable;
SELECT * FROM explicitlocks WHERE h=0 and r=0 FOR UPDATE;
```

Connection 2:
```
\c col_db yugabyte_test
DROP OWNED BY yugabyte_test CASCADE; -- In a non-colocated database, this statement succeeds without error.
ERROR:  Operation failed. Try again: 785f21b3-3cc9-47fc-9c0a-70c1aae9bb10 Conflicts with higher priority transaction: f8c93975-1336-457e-b823-99fd15f9efd0
```

[DB-5082]: https://yugabyte.atlassian.net/browse/DB-5082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment] 2023-01-18 23:47
I'm seeing for a colocated table, intent like `20:47:58.373593 27828 rocksdb_writer.cc:312] Add Intent SubDocKey(DocKey(ColocationId=2021360678, [], []), []), xid: 90f3938b-49c6-4e71-9809-90a0cffc5e5d`
is added, seems used to protect concurrent operations on this colocated table. But for normal tables, I don't see similar intents.

**Comment by Huqicheng** [comment] 2023-01-19 03:15
The difference should be `drop colocated table` should be implemented by PGSQL_TRUNCATE_COLOCATED

**Comment by tverona1** [comment] 2023-01-26 18:17
Per discussion with Jonathan & Yifan, resolving this as by design behavior difference between distributed table and colocated table for DROP + row-level locking:

- On a colocated table, a TRUNCATE / DROP may be aborted due to a conflict with another session that is holding row-level locks on the table. This is because a TRUNCATE/DROP on a colocated table is implemented by writing a truncate record to the tablet.
- On distributed table, the TRUNCATE / DROP will not conflict. This is because we do not acquire row-level locks and the tablets files are physically dropped.

**Closed by tverona1** 2023-01-26 18:17 UTC
Labels: kind/bug, area/ysql, priority/medium
