### ISSUE TITLE
[Backup and Restore][Packed columns enabled] Fatal files generated on restoring backup to a second universe

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12905] opened 2022-06-15 12:41 UTC
Jira Link: [DB-2648](https://yugabyte.atlassian.net/browse/DB-2648)
### Description

Steps to reproduce the issue:
- Create a universe with packed columns enabled 
```
{ "ysql_enable_packed_row" : "true",
  "ycql_enable_packed_row" : "true"
}
```
- Create a database, table inside it and insert data
- Create a backup of the database
- Drop the database
- Restore the database to a 2nd universe with packed columns enabled.
Issue:
Fatal files are generated in the source universe.
 
Fatal file error
```
F0615 12:14:02.215128 19396 primitive_value.cc:1268] Invalid value of enum ValueEntryType (full enum type: yb::docdb::ValueEntryType, expression: value_type): 35.
```

Warning log
```
W0615 12:15:01.799232 30013 catalog_manager.cc:1318] Failed to get current config: Illegal state (yb/master/catalog_manager.cc:10309): Node 4afcde3520504193b8d00dd093ccef97 peer not initialized.
W0615 12:15:01.803903 30021 catalog_manager.cc:1318] Failed to get current config: Illegal state (yb/master/catalog_manager.cc:10309): Node 4afcde3520504193b8d00dd093ccef97 peer not initialized.
W0615 12:15:01.824831 30019 log_util.cc:225] Could not read footer for segment: /mnt/d0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000004: Not found (yb/consensus/log_util.cc:539): Footer not found. Footer magic doesn't match
W0615 12:15:01.824860 30019 log_reader.cc:188] T 00000000000000000000000000000000 P 4afcde3520504193b8d00dd093ccef97: Log segment /mnt/d0/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000004 was likely left in-progress after a previous crash. Will try to rebuild footer by scanning data.
W0615 12:15:01.932834 30026 catalog_manager_bg_tasks.cc:132] Catalog manager background task thread going to sleep: Service unavailable (yb/master/scoped_leader_shared_lock.cc:92): Catalog manager is not initialized. State: 1
W0615 12:15:01.933115 30014 universe_key_client.cc:59] Rpc status: Network error (yb/util/net/socket.cc:540): recvmsg error: Connection refused (system error 111), resp:
```

CC: @rthallamko3 , @OlegLoginov , @nmantrav2 , @bmatican

**Comment by bmatican** [comment] 2022-07-06 19:22
> F0615 12:14:02.215128 19396 primitive_value.cc:1268] Invalid value of enum ValueEntryType (full enum type: yb::docdb::ValueEntryType, expression: value_type): 35.

Closing as duplicate of #12813. @kripasreenivasan if you could re-validate this scenario, with @spolitov 's fix, that'd be great!

**Closed by bmatican** 2022-07-06 19:22 UTC
Labels: kind/bug, area/docdb, priority/medium
