### ISSUE TITLE
[DocDB] Master is displaying incorrect tablet counts after splitting tablets in the master leader UI

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#15935] opened 2023-02-01 19:37 UTC
Jira Link: [DB-5348](https://yugabyte.atlassian.net/browse/DB-5348)
### Description

Master is displaying incorrect tablet counts after splitting tablets in the master leader UI. We need to check master's table page which lists individual tablets and also the counts in the Tablet Servers page of master leader UI.
Most probably pre-split parent tablets that were deleted were not accounted correctly

[DB-5348]: https://yugabyte.atlassian.net/browse/DB-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kripasreenivasan** [comment] 2023-02-02 12:17
https://yugabyte.slack.com/archives/C01CB38CZHU/p1675278535115939

**Comment by SrivastavaAnubhav** [comment] 2023-02-24 22:55
Closing as duplicate of #11307

**Closed by SrivastavaAnubhav** 2023-02-24 22:55 UTC
Labels: kind/bug, good first issue, area/docdb, priority/medium
