### ISSUE TITLE
[YSQL][postgres_fdw] Fails to copy data from stdin with: ERROR:  syntax error at end of input

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11425] opened 2022-02-10 15:25 UTC
### Description

Can be reproduced:
```
CREATE EXTENSION postgres_fdw;

CREATE SERVER testserver1 FOREIGN DATA WRAPPER postgres_fdw;
DO $d$
    BEGIN
        EXECUTE $$CREATE SERVER loopback FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
        EXECUTE $$CREATE SERVER loopback2 FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
    END;
$d$;

CREATE USER MAPPING FOR public SERVER testserver1
OPTIONS (user 'value', password 'value');
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback;
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback2;

create table ctrtest (a int, b text) partition by list (a);
create table loct1 (a int check (a in (1)), b text);
create foreign table remp1 (a int check (a in (1)), b text) server loopback options (table_name 'loct1');
create table loct2 (a int check (a in (2)), b text);
create foreign table remp2 (b text, a int check (a in (2))) server loopback options (table_name 'loct2');
alter table ctrtest attach partition remp1 for values in (1);
alter table ctrtest attach partition remp2 for values in (2);

copy ctrtest from stdin;
1	foo
2	qux
\.
```
Fails:
```
ERROR:  syntax error at end of input
CONTEXT:  remote SQL command: DEALLOCATE
```

**Comment by myang2021** [comment] 2022-02-16 20:39
I was looking at fdw example and saw this ticket. I debugged it and found that it is caused by referencing freed memory:

```
    /* If we created a prepared statement, destroy it */
    if (fmstate->p_name)
    {
        char        sql[64];
        PGresult   *res;

        snprintf(sql, sizeof(sql), "DEALLOCATE %s", fmstate->p_name);

 ```
 The memory fmstate->p_name is already freed, so we end up composing some garbage characters after DEALLOCATE. I see there is some interaction between COPY and FDW. I see there is a simple fix for this. Will make a diff and add the test case.

**Closed** 2022-02-24 23:26 UTC
Labels: kind/bug, area/ysql
