### ISSUE TITLE
[DocDB] CppCassandraDriverTest.ConcurrentIndexUpdate failing in fastdebug

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#22477] opened 2024-05-21 17:59 UTC
Jira Link: [DB-11393](https://yugabyte.atlassian.net/browse/DB-11393)
### Description

https://detective.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CppCassandraDriverTest&fail_tag=all&name=ConcurrentIndexUpdate&platform=all

```
[ts-3] I0521 01:33:28.792721 90916 tablet.cc:2884] Done BackfillIndexes at { days: 19864 time: 01:33:24.880738 } for [152a96a270de413f9d6bd5a45e690e4a] until <end of the tablet>
[ts-3] F0521 01:33:28.794052 90852 doc_reader.cc:895] Check failed: key_result.key.starts_with(root_doc_key_) 

[ts-3] Fatal failure details written to ${BUILD_ROOT}/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_ConcurrentIndexUpdate.fatal_failure_details.ts-3.2024-05-21T01_33_28.pid90141.txt
[ts-3] F20240521 01:33:28 ../../src/yb/docdb/doc_reader.cc:895] Check failed: key_result.key.starts_with(root_doc_key_) 
[ts-3] ${YB_SRC_ROOT}/src/yb/util/logging.cc:464:     @     0x7ff2f1766684  yb::LogFatalHandlerSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long)
[ts-3]     @     0x7ff2f01c21a7 
[ts-3]     @     0x7ff2f01c30a2 
[ts-3]     @     0x7ff2f01c7059 
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_reader.cc:895:     @     0x7ff2f6136165  yb::docdb::(anonymous namespace)::GetHelperBase<false, false, true>::Prepare(yb::docdb::FetchedEntry const&, yb::docdb::(anonymous namespace)::LazyDocHybridTime*)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_reader.cc:762:     @     0x7ff2f6136165  yb::docdb::(anonymous namespace)::GetHelperBase<false, false, true>::DoRun(yb::docdb::FetchedEntry const&, yb::docdb::(anonymous namespace)::LazyDocHybridTime*)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_reader.cc:1229:     @     0x7ff2f6136165  yb::docdb::(anonymous namespace)::GetHelper<std::nullptr_t>::Run(yb::docdb::FetchedEntry const&)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_reader.cc:1661:     @     0x7ff2f6136165  yb::docdb::DocDBTableReader::Get(yb::ByteBuffer<64ul>*, yb::docdb::FetchedEntry const&, yb::dockv::SubDocument*)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_rowwise_iterator.cc:349:     @     0x7ff2f619b4fa  yb::docdb::DocRowwiseIterator::FetchRow(yb::docdb::FetchedEntry const&, yb::docdb::DocRowwiseIterator::QLTableRowPair)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_rowwise_iterator.cc:322:     @     0x7ff2f619b4fa  yb::Result<bool> yb::docdb::DocRowwiseIterator::FetchNextImpl<yb::docdb::DocRowwiseIterator::QLTableRowPair>(yb::docdb::DocRowwiseIterator::QLTableRowPair)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/doc_rowwise_iterator.cc:221:     @     0x7ff2f61973b2  yb::docdb::DocRowwiseIterator::DoFetchNext(yb::qlexpr::QLTableRow*, yb::dockv::ReaderProjection const*, yb::qlexpr::QLTableRow*, yb::dockv::ReaderProjection const*)
[ts-3] ../../src/yb/docdb/ql_rowwise_iterator_interface.h:46:                                                  @     0x7ff2f60a0dec  yb::docdb::YQLRowwiseIteratorIf::FetchNext(yb::qlexpr::QLTableRow*, yb::dockv::ReaderProjection const*, yb::qlexpr::QLTableRow*, yb::dockv::ReaderProjection const*)
[ts-3] ${YB_SRC_ROOT}/src/yb/docdb/cql_operation.cc:1773:     @     0x7ff2f60a0dec  yb::docdb::QLReadOperation::Execute(yb::docdb::YQLStorageIf const&, yb::docdb::ReadOperationData const&, yb::docdb::DocReadContext const&, std::reference_wrapper<yb::ScopedRWOperation const>, yb::qlexpr::QLResultSet*, yb::HybridTime*, yb::docdb::DocDBStatistics const*)
[ts-3] ${YB_SRC_ROOT}/src/yb/tablet/abstract_tablet.cc:57:     @     0x7ff2f64c74a3  yb::tablet::AbstractTablet::HandleQLReadRequest(yb::docdb::ReadOperationData const&, yb::QLReadRequestPB const&, yb::TransactionOperationContext const&, yb::docdb::YQLStorageIf const&, std::reference_wrapper<yb::ScopedRWOperation const>, yb::tablet::QLReadRequestResult*, yb::WriteBuffer*, yb::docdb::DocDBStatistics const*)
[ts-3] ${YB_SRC_ROOT}/src/yb/tablet/tablet.cc:1706:     @     0x7ff2f651a737  yb::tablet::Tablet::HandleQLReadRequest(yb::docdb::ReadOperationData const&, yb::QLReadRequestPB const&, yb::TransactionMetadataPB const&, yb::tablet::QLReadRequestResult*, yb::WriteBuffer*)
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:691:     @     0x7ff2f6b0f0fb  yb::tserver::(anonymous namespace)::ReadQuery::DoReadImpl()
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:595:     @     0x7ff2f6b0f0fb  yb::tserver::(anonymous namespace)::ReadQuery::DoRead()
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:508:     @     0x7ff2f6b0f0fb  yb::tserver::(anonymous namespace)::ReadQuery::Complete()
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:442:     @     0x7ff2f6b0c4cd  yb::tserver::(anonymous namespace)::ReadQuery::DoPerform()
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:119:     @     0x7ff2f6b0c4cd  yb::tserver::(anonymous namespace)::ReadQuery::Perform()
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/read_query.cc:748:     @     0x7ff2f6b0c4cd  yb::tserver::PerformRead(yb::tserver::TabletServerIf*, yb::tserver::ReadTabletProvider*, yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)
[ts-3] ${YB_SRC_ROOT}/src/yb/tserver/tablet_service.cc:2347:     @     0x7ff2f6ba7a74  yb::tserver::TabletServiceImpl::Read(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)
[ts-3] ${BUILD_ROOT}/src/yb/tserver/tserver_service.service.cc:763:     @     0x7ff2f3926fd3  yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)::operator()(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) const
[ts-3] ../../src/yb/rpc/local_call.h:126:                                                                      @     0x7ff2f3926fd3  auto yb::rpc::HandleCall<yb::rpc::RpcCallPBParamsImpl<yb::tserver::ReadRequestPB, yb::tserver::ReadResponsePB>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)>(shared_ptr<yb::rpc::InboundCall>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext))
[ts-3] ${BUILD_ROOT}/src/yb/tserver/tserver_service.service.cc:761:     @     0x7ff2f3926fd3  yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1::operator()(shared_ptr<yb::rpc::InboundCall>) const
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__type_traits/invoke.h:340:     @     0x7ff2f3926fd3  decltype(std::declval<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&>()(std::declval<shared_ptr<yb::rpc::InboundCall>>())) std::__invoke[abi:v170002]<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, shared_ptr<yb::rpc::InboundCall>>(yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, shared_ptr<yb::rpc::InboundCall>&&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__type_traits/invoke.h:415:     @     0x7ff2f3926fd3  void std::__invoke_void_return_wrapper<void, true>::__call[abi:v170002]<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, shared_ptr<yb::rpc::InboundCall>>(yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1&, shared_ptr<yb::rpc::InboundCall>&&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:192:     @     0x7ff2f3926fd3  std::__function::__alloc_func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1, std::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1>, void (shared_ptr<yb::rpc::InboundCall>)>::operator()[abi:v170002](shared_ptr<yb::rpc::InboundCall>&&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:363:     @     0x7ff2f3926fd3  std::__function::__func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1, std::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1>, void (shared_ptr<yb::rpc::InboundCall>)>::operator()(shared_ptr<yb::rpc::InboundCall>&&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:517:     @     0x7ff2f3925e92  std::__function::__value_func<void (shared_ptr<yb::rpc::InboundCall>)>::operator()[abi:v170002](shared_ptr<yb::rpc::InboundCall>&&) const
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:1168:     @     0x7ff2f3925e92  std::function<void (shared_ptr<yb::rpc::InboundCall>)>::operator()(shared_ptr<yb::rpc::InboundCall>) const
[ts-3] ${BUILD_ROOT}/src/yb/tserver/tserver_service.service.cc:731:     @     0x7ff2f3925e92  yb::tserver::TabletServerServiceIf::Handle(shared_ptr<yb::rpc::InboundCall>)
[ts-3] ${YB_SRC_ROOT}/src/yb/rpc/service_pool.cc:269:     @     0x7ff2f2291283  yb::rpc::ServicePoolImpl::Handle(shared_ptr<yb::rpc::InboundCall>)
[ts-3] ${YB_SRC_ROOT}/src/yb/rpc/inbound_call.cc:303:     @     0x7ff2f21e87f9  yb::rpc::InboundCall::InboundCallTask::Run()
[ts-3] ${YB_SRC_ROOT}/src/yb/rpc/thread_pool.cc:115:     @     0x7ff2f22a8954  yb::rpc::(anonymous namespace)::Worker::Execute()
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__type_traits/invoke.h:308:     @     0x7ff2f22a8ddb  decltype(*std::declval<yb::rpc::(anonymous namespace)::Worker*&>().*std::declval<void (yb::rpc::(anonymous namespace)::Worker::*&)()>()()) std::__invoke[abi:v170002]<void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&, void>(void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:260:     @     0x7ff2f22a8ddb  std::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), tuple<yb::rpc::(anonymous namespace)::Worker*>, tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), tuple<yb::rpc::(anonymous namespace)::Worker*>, tuple<>>::value>::type std::__apply_functor[abi:v170002]<void (yb::rpc::(anonymous namespace)::Worker::*)(), tuple<yb::rpc::(anonymous namespace)::Worker*>, 0ul, tuple<>>(void (yb::rpc::(anonymous namespace)::Worker::*&)(), tuple<yb::rpc::(anonymous namespace)::Worker*>&, std::__tuple_indices<0ul>, tuple<>&&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:292:     @     0x7ff2f22a8ddb  std::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), tuple<yb::rpc::(anonymous namespace)::Worker*>, tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), tuple<yb::rpc::(anonymous namespace)::Worker*>, tuple<>>::value>::type std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>::operator()[abi:v170002]<>()
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__type_traits/invoke.h:340:     @     0x7ff2f22a8ddb  decltype(std::declval<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>()()) std::__invoke[abi:v170002]<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__type_traits/invoke.h:415:     @     0x7ff2f22a8ddb  void std::__invoke_void_return_wrapper<void, true>::__call[abi:v170002]<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&)
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:192:     @     0x7ff2f22a8ddb  std::__function::__alloc_func<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>, std::allocator<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>>, void ()>::operator()[abi:v170002]()
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:363:     @     0x7ff2f22a8ddb  std::__function::__func<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>, std::allocator<std::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>>, void ()>::operator()()
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:517:     @     0x7ff2f18a8b6f  std::__function::__value_func<void ()>::operator()[abi:v170002]() const
[ts-3] ${YB_THIRDPARTY_DIR}/installed/tsan/libcxx/include/c++/v1/__functional/function.h:1168:     @     0x7ff2f18a8b6f  std::function<void ()>::operator()() const
[ts-3] ${YB_SRC_ROOT}/src/yb/util/thread.cc:866:     @     0x7ff2f18a8b6f  yb::Thread::SuperviseThread(void*)
[ts-3] ${YB_LLVM_TOOLCHAIN_DIR}-build/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1010:     @     0x5620a0dd13de  __tsan_thread_start_func
[ts-3]     @     0x7ff2ef64c1c9 
[ts-3]     @     0x7ff2ef09ee72 
[ts-3] 
[ts-3] *** Check failure stack trace: ***

```

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11393]: https://yugabyte.atlassian.net/browse/DB-11393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment] 2024-05-26 02:54
Commit 99d42ecc added the dcheck. @spolitov , Does that mean some Scan Forward usage is not correct. Can it lead to invalid results?

**Comment by arybochkin** [comment] 2024-06-10 14:27
probably the duplicate of https://github.com/yugabyte/yugabyte-db/issues/21327

**Comment by rthallamko3** [comment] 2024-08-27 19:03
DUP of https://github.com/yugabyte/yugabyte-db/issues/21327

**Closed by rthallamko3** 2024-08-27 19:03 UTC
Labels: kind/enhancement, kind/failing-test, area/docdb, priority/high
