### ISSUE TITLE
Is PartitionAware host selection policy supported by gocql driver?

### ISSUE THREAD

**Issue by ethashamuddin-mohammed-kr** [yugabyte/yugabyte-db#11544] opened 2022-02-19 17:03 UTC
[Documentation](https://pkg.go.dev/github.com/yugabyte/gocql#hdr-Data_center_awareness_and_query_routing) says: **We recommend running with a token aware host policy in production for maximum performance.**

It's implementation is in master branch: https://github.com/yugabyte/gocql/blob/master/policies.go#L354

We are currently using `gocql@v0.0.0-20200602185649-ef3952a45ff4`

Please clarify the status of this token aware host selection policy feature. 

Can we use this api `gocql.TokenAwareHostPolicy`  from gocql driver?

**Comment by ddorian** [comment] 2022-02-22 13:06
Closing as duplicate of https://github.com/yugabyte/yugabyte-db/issues/11376

**Closed by ddorian** 2022-02-22 13:06 UTC
