### ISSUE TITLE
Implement ZINCRBY and ZSCORE for Redis sorted sets

### ISSUE THREAD

**Issue by rkarthik007** [YugaByte/yugabyte-db#94] opened 2018-03-12 01:26 UTC
The following commands are useful where implementing a "count pageviews" type of usecase:

- `ZINCRBY`:
Increment the score on each pageview. Example of incrementing the num views to the homepage by 1 when it is viewed:
```
> ZINCRBY key:pageviews 1 homepage
```
- `ZSCORE`:
Fetch the pageviews for a given page. For example, to get the current number of pageviews for the homepage:
```
> ZSCORE key:pageviews homepage
```

**Comment by rao-vasireddy** [comment] 2018-05-30 01:44
This is a dupe of https://github.com/YugaByte/yugabyte-db/issues/216 and https://github.com/YugaByte/yugabyte-db/issues/175

**Closed** 2018-05-30 01:45 UTC
Labels: enhancement
