### ISSUE TITLE
[YSQL] Colocated database visibility change in 2.17.2 leading to visibility issues

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#16661] opened 2023-04-03 14:02 UTC
Jira Link: [DB-6043](https://yugabyte.atlassian.net/browse/DB-6043)
### Description

Starting from YB version 2.17.2, the visibility of YQL colocated database has changed.

### Missing information
Before 2.17.2, colocated database information was visible in:
- the master endpoint `/tables` as "Parent tables". This shows the colocated database with keys-ace, table name (which is the table for all the actual tables), state, message, UUID, YSQL OID, Hidden, On-disk size.

Starting from 2.17.2, (colocated) database information is now visible:
- new master endpoint `/namespaces`. This shows keyspaces divided in 'User Namespaces' and 'System Namespaces', and provides 'name', 'id', 'language', 'state' and 'colocated'.

This means the on-disk size information is gone.

### Missing JSON information
But most concerning to me is that before 2.17.2, a colocated database after creation before any user objects have been created shows the following information in `/dump-entities`:

A keyspace entry:
```
    {
      "keyspace_id": "00004001000030008000000000000000",
      "keyspace_name": "zzzz",
      "keyspace_type": "ysql"
    }
```
A table entry:
```
    {
      "table_id": "00004001000030008000000000000000.colocated.parent.uuid",
      "keyspace_id": "00004001000030008000000000000000",
      "table_name": "00004001000030008000000000000000.colocated.parent.tablename",
      "state": "RUNNING"
    }
```
And a tablet entry:
```
    {
      "table_id": "00004001000030008000000000000000.colocated.parent.uuid",
      "tablet_id": "ba782585352c466091fc14f3eec50844",
      "state": "RUNNING",
      "replicas": [
        {
          "type": "VOTER",
          "server_uuid": "35cb0db775974930b319c9d8456ccff4",
          "addr": "yb-1.local:9100"
        },
        {
          "type": "VOTER",
          "server_uuid": "d4d1427986f84491a8aa2c38223e21e7",
          "addr": "yb-3.local:9100"
        },
        {
          "type": "VOTER",
          "server_uuid": "f5e28734cda44a958085b4275ed7cb4c",
          "addr": "yb-2.local:9100"
        }
      ],
      "leader": "d4d1427986f84491a8aa2c38223e21e7"
    }
```
The table and tablet entry with the 'colocated' addition makes it easy to understand if a keyspace is colocated.

However, starting from 2.17.2, the information about a colocated database after creation in `/dump-entities` is:
```
    {
      "keyspace_id": "00004000000030008000000000000000",
      "keyspace_name": "qqqqq",
      "keyspace_type": "ysql"
    }
```
In other words: it's now impossible to determine if a keyspace is colocated using the "internal" JSON output from `/dump-entities`.

As soon as an user objects is created, the colocated objects are created:
```
    {
      "table_id": "00004000000030008000000000004004.colocation.parent.uuid",
      "keyspace_id": "00004000000030008000000000000000",
      "table_name": "00004000000030008000000000004004.colocation.parent.tablename",
      "state": "RUNNING"
    }
```
But slightly different: the name is changed from colocated.parent.uuid/colocated.parent.tablename to colocation.parent.uuid/colocation.parent.tablename, and the UUID is no longer the keyspace UUID, but an UUID which contains a postgres user OID (4004). 
```
    {
      "table_id": "00004000000030008000000000004004.colocation.parent.uuid",
      "tablet_id": "ad0e2b92a161478ba151272a4cc6a41c",
      "state": "RUNNING",
      "replicas": [
        {
          "type": "VOTER",
          "server_uuid": "24e147610253436db0e806f6edbaf59e",
          "addr": "yb-1.local:9100"
        }
      ],
      "leader": "24e147610253436db0e806f6edbaf59e"
    }
```
And the tablet refers to this new OID instead of the keyspace UUID.

If possible, it would be great if we can have:
- The old information that was visible in the `/tables` endpoint, although I agree that having a database in `/tables` is not intuitive.
- Have the colocated table and tablet entities be created at database creation time.
- Have the colocated table and tablet entities have their keyspace UUID (although I would agree that if this reflects an internal change where this OID is actually used, it's best to change it and reflect reality).

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6043]: https://yugabyte.atlassian.net/browse/DB-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tverona1** [comment] 2023-04-05 17:41
Resolving this issue as by-design for colocation GA implementation:
- the /namespaces endpoint can be used to determine if a database is colocated (or ysql function yb_is_database_colocated())
- by design, the colocated parent tablet is create lazily on first table created within a colocated database
- the parent tablet's table name is suffixed with "colocation.parent.tablename"

**Closed by tverona1** 2023-04-05 17:42 UTC
Labels: kind/bug, area/ysql, priority/medium, status/awaiting-triage
