### ISSUE TITLE
[Platform ]--Allow Multiple Configurations for same Provider

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#7749] opened 2021-03-22 16:27 UTC
--context--

Only one configuration is allowed for a given Provider (AWS, GCP, Tanzu, etc). It would be ideal if you could create multiple configurations. 

--example--
 you may have a Production provider in AWS that uses the Production AWS account and a Test provider in AWS that uses a different AWS account.

---use case--
 create an additional configuration for the same provider so that you can test a new AMI.

**Comment by streddy-yb** [comment] 2021-04-14 03:18
Duplicate of #7474, which is targeted for 2.7.

**Closed by streddy-yb** 2021-04-14 03:18 UTC
Labels: area/platform, kind/new-feature, priority/high
