### ISSUE TITLE
Terraform node_count different than defaults causes failure

### ISSUE THREAD

**Issue by lvlcalebf** [yugabyte/yugabyte-db#4425] opened 2020-05-08 20:02 UTC
follow instructions here https://docs.yugabyte.com/latest/deploy/public-clouds/gcp/terraform/ using the default node_count = "3" in the main.tf file creates a cluster that can successfully create a database but when node_count = "6" database creation is unsuccessful.  The contents of my main.tf file: 
`provider "google"{
    # Provide your Creadentilals
    credentials = file("yugabyte-multi-region-50bf0364d60c.json")

    # The name of your GCP project
    project = "yugabyte-multi-region"
}

module "yugabyte-db-cluster" {
    source = "github.com/Yugabyte/terraform-gcp-yugabyte.git"

    # The name of the cluster to be created.
    cluster_name = "gcp-ydb-cluster02"

    # key pair.
    ssh_private_key = "infra_team"
    ssh_public_key = "infra_team.pub"
    ssh_user = "infra_team"

    # The region name where the nodes should be spawned.
    region_name = "us-east4"

    # The size of instance to use
    node_type = "n1-standard-1"

    # The version to install
    yb_version = "2.1.5.0"

    # Replication factor.
    replication_factor = "3"

    # The number of nodes in the cluster, this cannot be lower than the replication factor.
    node_count = "6"
}`

the error received when trying to create a db: 
`ysqlsh -h <master-ip> -c 'create database test1;'
ERROR:  Not found: The object does not exist: table_name: "transactions" namespace { name: "system" database_type: YQL_DATABASE_CQL }: . Errors from tablet servers: [Not found (yb/master/catalog_manager.cc:6559): The object does not exist: table_name: "transactions" namespace { name: "system" database_type: YQL_DATABASE_CQL }]`

**Comment by lvlcalebf** [comment] 2020-05-08 20:16
I tried to create a transaction table using the following command: `cqlsh> create keyspace sample; create table sample.test(k int primary key) with transactions={'enabled':true}
   ... ;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid Table Definition. Error creating table sample.test on the master: Error while creating transaction status table: Sum of minimum replicas per placement (6) is greater than num_replicas  (3)
create table sample.test(k int primary key) with transactions={'enabled':true}
                   ^^^^^
;
 (ql error -302)"` and received an error that may give more data

**Comment by iSignal** [comment] 2020-05-08 22:50
@lvlcalebf : thanks for reporting this issue, good catch!

I think the issue is a bug in our terraform template where we do not dedup the list of zones collected here - https://github.com/yugabyte/terraform-gcp-yugabyte/blob/5fd93bc2f08d59f34126df32d5bcb7c72e8d93eb/main.tf#L115 - so we may be ending up creating a cluster with 6 zones in https://github.com/yugabyte/utilities/blob/master/scripts/create_universe.sh#L180 (whereas we should be using 3 zones).

I will test out this theory and report back to you.

**Comment by iSignal** [comment] 2020-05-09 00:07
@lvlcalebf : I tested out the GCP terraform workflow with 6 **n1-standard-4** nodes and was unable to reproduce your issue. Could you increase the resources allocated to the nodes and try again? I will attempt a repro with **n1-standard-1** nodes.

**Comment by iSignal** [comment] 2020-05-09 01:29
@lvlcalebf : I was also unable to repro this with **n1-standard-1** nodes. Could you share the following information about your deployment to help us understand the problem better? 

If you want to share the logs privately, please feel free to join our Slack channel at https://www.yugabyte.com/slack and find us there.

* A terraform plan for your deployment
* Output from the terraform apply command
* master.conf and tserver.conf files at `yugabyte-db/master/conf/server.conf` and `yugabyte-db/tserver/conf/server.conf` from these hosts

**Comment by lvlcalebf** [comment] 2020-05-11 16:34
@iSignal I sent the files as requested in slack

**Comment by lvlcalebf** [comment] 2020-05-11 19:44
by changing the replication configuration I was able to create a database and table.  Here is the original configuration as created by terraform that fails:
``` 
version: 1
replication_info {
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-b"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-c"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-b"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-c"
      }
      min_num_replicas: 1
    }
  }
}
cluster_uuid: "4b412e5c-8eb8-434d-b8f6-53eb20bd1472"
```

and this is the one that works:
```version: 1
replication_info {
  live_replicas {
    num_replicas: 3
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-a"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-b"
      }
      min_num_replicas: 1
    }
    placement_blocks {
      cloud_info {
        placement_cloud: "GCP"
        placement_region: "us-east4"
        placement_zone: "us-east4-c"
      }
      min_num_replicas: 1
    }
  }
}
cluster_uuid: "4b412e5c-8eb8-434d-b8f6-53eb20bd1472"
```

**Comment by iSignal** [comment] 2020-05-11 22:17
Turns out the original theory in https://github.com/yugabyte/yugabyte-db/issues/4425#issuecomment-626052729 was correct after all. I am now able to reproduce the problem with the latest terraform repo. 

The issue should be fixed by https://github.com/yugabyte/terraform-gcp-yugabyte/pull/14

**Comment by iSignal** [comment] 2020-05-26 19:56
Should be fixed in all terraform repos now.

**Closed by iSignal** 2020-05-26 19:56 UTC
Labels: area/tools, community/request
