### ISSUE TITLE
libuv fails to build on macOS Catalina with CarbonCore related errors

### ISSUE THREAD

**Issue by emhna** [yugabyte/yugabyte-db#4744] opened 2020-06-11 01:51 UTC
While running ./yb_build.sh under yugabyte repo in the local computer with OS Catalina, thirdparty module does not get built successfully. 

Error message during compilation:
CMake Error at CMakeLists.txt:565 (message):
  Thirdparty was built unsuccessfully, terminating.  

libuv is only used for the CQL Cassandra driver, which is only used in tests. libuv might require upgrade.

**Comment by ddorian** [comment] 2020-06-13 06:52
Can you please print a more verbose log ? Like last 100 lines ?

**Comment by mbautin** [comment] 2020-06-13 18:23
Posting the info from #4763 (which I closed as a duplicate).

@svarnau: this might be caused by a particular version of macOS X SDK, or other software installed. This may get fixed by upgrading libuv.
This does not happen on GitHub Actions in yugabyte/yugabyte-db-thirdparty, even though those are running on macOS X Catalina as ewll.

```
[libuv (clang_uninstrumented)] [ 96%] Building C object CMakeFiles/uv.dir/src/unix/fsevents.c.o
[libuv (clang_uninstrumented)] In file included from ~/code/yugabyte/thirdparty/src/libuv-1.23.0/src/unix/fsevents.c:49:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:43:
[libuv (clang_uninstrumented)] /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UTCUtils.h:22:10: fatal error: 'CarbonCore/MacErrors.h' file not found
[libuv (clang_uninstrumented)] #include <CarbonCore/MacErrors.h>
[libuv (clang_uninstrumented)]          ^~~~~~~~~~~~~~~~~~~~~~~~
[libuv (clang_uninstrumented)] In file included from ~/code/yugabyte/thirdparty/src/libuv-1.23.0/src/unix/darwin-proctitle.c:33:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.hIn file included from ~/code/yugabyte/thirdparty/src/libuv-1.23.0/src/unix/darwin-proctitle.c:33:
[libuv (clang_uninstrumented)] :23In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
[libuv (clang_uninstrumented)] In file included from :
[libuv (clang_uninstrumented)] /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.hIn file included from :/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h20::
[libuv (clang_uninstrumented)] 23In file included from :
[libuv (clang_uninstrumented)] /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.hIn file included from :/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h43::
[libuv (clang_uninstrumented)] 20:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UTCUtils.h::4322:
[libuv (clang_uninstrumented)] :10: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UTCUtils.hfatal error:: 22'CarbonCore/MacErrors.h' file not found:
[libuv (clang_uninstrumented)] 10: fatal error: 'CarbonCore/MacErrors.h' file not found
[libuv (clang_uninstrumented)] #include <CarbonCore/MacErrors.h>#include <CarbonCore/MacErrors.h>
[libuv (clang_uninstrumented)]          ^~~~~~~~~~~~~~~~~~~~~~~~
[libuv (clang_uninstrumented)]
[libuv (clang_uninstrumented)]          ^~~~~~~~~~~~~~~~~~~~~~~~
[libuv (clang_uninstrumented)] In file included from ~/code/yugabyte/thirdparty/src/libuv-1.23.0/src/unix/fsevents.c:49:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
[libuv (clang_uninstrumented)] In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:43:
[libuv (clang_uninstrumented)] /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UTCUtils.h:22:10: fatal error: 'CarbonCore/MacErrors.h' file not found
[libuv (clang_uninstrumented)] #include <CarbonCore/MacErrors.h>
[libuv (clang_uninstrumented)]          ^~~~~~~~~~~~~~~~~~~~~~~~
[libuv (clang_uninstrumented)] 1 error generated.
[libuv (clang_uninstrumented)] 1 error generated.
[libuv (clang_uninstrumented)] make[2]: *** [CMakeFiles/uv.dir/src/unix/fsevents.c.o] Error 1make[2]:
[libuv (clang_uninstrumented)] *** [CMakeFiles/uv_a.dir/src/unix/fsevents.c.o] Error 1
[libuv (clang_uninstrumented)] make[2]: *** Waiting for unfinished jobs....
[libuv (clang_uninstrumented)] make[2]: *** Waiting for unfinished jobs....
[libuv (clang_uninstrumented)] 1 error1 error generated generated.
[libuv (clang_uninstrumented)] .
[libuv (clang_uninstrumented)] make[2]: *** [CMakeFiles/uv_a.dir/src/unix/darwin-proctitle.c.o] Error 1
[libuv (clang_uninstrumented)] make[2]: *** [CMakeFiles/uv.dir/src/unix/darwin-proctitle.c.o] Error 1
[libuv (clang_uninstrumented)] make[1]: *** [CMakeFiles/uv.dir/all] Error 2
[libuv (clang_uninstrumented)] make[1]: *** Waiting for unfinished jobs....
[libuv (clang_uninstrumented)] make[1]: *** [CMakeFiles/uv_a.dir/all] Error 2
[libuv (clang_uninstrumented)] make: *** [all] Error 2
Execution failed with code: 2
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 975, in <module>
    main()
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 971, in main
    builder.run()
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 252, in run
    self.build(BUILD_TYPE_CLANG_UNINSTRUMENTED)
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 737, in build
    self.build_dependency(dep)
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 818, in build_dependency
    dep.build(self)
  File "~/code/yugabyte/thirdparty/build_definitions/libuv.py", line 37, in build
    ] + builder.get_openssl_related_cmake_args())
  File "~/code/yugabyte/thirdparty/yb_build_thirdparty_main.py", line 717, in build_with_cmake
    log_output(log_prefix, build_tool_cmd)
  File "~/code/yugabyte/thirdparty/build_definitions/__init__.py", line 102, in log_output
    fatal("Execution failed with code: {}".format(exit_code))
  File "~/code/yugabyte/thirdparty/build_definitions/__init__.py", line 74, in fatal
    traceback.print_stack()
CMake Error at CMakeLists.txt:565 (message):
  Thirdparty was built unsuccessfully, terminating.
```

**Comment by emhna** [comment] 2020-06-17 14:06
After running git pull under master branch and bin/setup_workstation.sh, the script exits with code 0. No further issue has been detected. Note my laptop is using macOS Catalina version 10.15.5.

**Comment by svarnau** [comment] 2020-06-18 21:11
Error indicated a missing file in CommandLineTools SDK.  Solution is to re-install it:
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install

**Closed by svarnau** 2020-06-18 21:11 UTC
