### ISSUE TITLE
[YSQL] Node restart on column drop with index

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#10931] opened 2021-12-22 19:27 UTC
### Description

Cluster:
- 3 nodes
- c5.xlarge
- RF=3

Case: 
1. Run workload SqlDataLoad with 
```
java -jar yb-sample-apps.jar --workload SqlDataLoad  --num_writes -1 --num_reads -1 --num_threads_write 40 --num_threads_read 3 --num_unique_keys -1 --num_value_columns 10 --num_indexes 10 --uuid 3d0f4814-d41a-4499-9eb9-ef44d21e5f08 --create_table_name test_indexes_f9cd53 --batch_size 100 --nodes 172.151.19.241:5433,172.151.23.183:5433,172.151.30.127:5433
```
2. Start drop and add column in table in loop:
   1.1. `alter table test_indexes_f9cd53 drop column v1-10`
   1.2. `alter table test_indexes_f9cd53 add column v1-10 text`

Node will restart after some time with FATAL exception
```
F20211222 18:42:24 ../../src/yb/tablet/operations/operation_driver.cc:403] T d68305f580054900be93b5c68d1122b0 P 719480b9f2b948d29695ef3772bdb283 S RD-P Ts { physical: 1640198544509547 } kChangeMetadata: Apply failed: Not found (yb/tablet/transaction_participant.cc:404): Abort of unknown transaction: 526a2884-e6ce-40ee-a989-9433fdf7c4d2, request: tablet_id: "d68305f580054900be93b5c68d1122b0" schema { columns { id: 0 name: "k" type { main: STRING } is_key: true is_hash_key: true is_nullable: false is_static: false is_counter: false sorting_type: 0 order: 1 } columns { id: 1 name: "v1" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 2 } columns { id: 2 name: "v2" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 3 } columns { id: 3 name: "v3" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 4 } columns { id: 4 name: "v4" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 5 } columns { id: 5 name: "v5" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 6 } columns { id: 7 name: "v7" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 8 } columns { id: 8 name: "v8" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 9 } columns { id: 9 name: "v9" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 10 } columns { id: 10 name: "v10" type { main: STRING } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 11 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false is_ysql_catalog_table: false retain_delete_markers: false } colocated_table_id { } } schema_version: 21 new_table_name: "test_indexes_f9cd53" dest_uuid: "64216e4e6e554061ac79a13116028862" propagated_hybrid_time: 6718253238309728256 indexes { table_id: "000033df000030008000000000004214" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df000030008000000000004215" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df000030008000000000004216" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df000030008000000000004217" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df000030008000000000004218" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df000030008000000000004219" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df00003000800000000000421a" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df00003000800000000000421b" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df00003000800000000000421c" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } indexes { table_id: "000033df00003000800000000000421d" indexed_table_id: "000033df00003000800000000000420f" index_permissions: INDEX_PERM_READ_WRITE_AND_DELETE } alter_table_id: "000033df00003000800000000000420f" transaction_id: "2f51974b-0a21-4be8-9449-18ad981037a6" should_abort_active_txns: true
    @     0x7fbf834246ec  yb::LogFatalHandlerSink::send()
    @     0x7fbf80baa8ee  google::LogMessage::SendToLog()
    @     0x7fbf80ba7a7a  google::LogMessage::Flush()
    @     0x7fbf80bab169  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbf8c3d1225  yb::tablet::OperationDriver::ApplyTask()
    @     0x7fbf8c3d188f  yb::tablet::OperationDriver::ReplicationFinished()
    @     0x7fbf8bfed2c8  yb::consensus::ReplicaState::NotifyReplicationFinishedUnlocked()
    @     0x7fbf8bff33f6  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @     0x7fbf8bff3f3b  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @     0x7fbf8bfc7b20  yb::consensus::RaftConsensus::EarlyCommitUnlocked()
    @     0x7fbf8bfdce1f  yb::consensus::RaftConsensus::UpdateReplica()
    @     0x7fbf8bfde12c  yb::consensus::RaftConsensus::Update()
    @     0x7fbf8cf00900  yb::tserver::ConsensusServiceImpl::UpdateConsensus()
    @     0x7fbf88f6ceab  _ZNSt17_Function_handlerIFvSt10shared_ptrIN2yb3rpc11InboundCallEEEZNS1_9consensus18ConsensusServiceIf11InitMethodsERK13scoped_refptrINS1_12MetricEntityEEEUlS4_E_E9_M_invokeERKSt9_Any_dataOS4_
    @     0x7fbf88f6cca4  yb::consensus::ConsensusServiceIf::Handle()
    @     0x7fbf838c7e8e  yb::rpc::ServicePoolImpl::Handle()
    @     0x7fbf83869f64  yb::rpc::InboundCall::InboundCallTask::Run()
    @     0x7fbf838dbad8  yb::rpc::(anonymous namespace)::Worker::Execute()
    @     0x7fbf834c67e5  yb::Thread::SuperviseThread()
    @     0x7fbf7d75f694  start_thread
    @     0x7fbf7ce9c41d  __clone
    @              (nil)  (unknown)
```

Dropped column should has index on it
[logs.zip](https://github.com/yugabyte/yugabyte-db/files/7764770/logs.zip)

**Comment by tedyu** [comment] 2021-12-24 01:13
Seems to be related to #10934

**Comment by bmatican** [comment] 2022-01-07 15:06
@tedyu @pilshchikov Do I understand correctly, that the DDLs are happening in one single session?

**Comment by myang2021** [comment] 2022-01-14 01:34
From the attached logs the FATAL log looks like:
```
F1222 18:42:24.565493 23795 operation_driver.cc:403] T d68305f580054900be93b5c68d1122b0 P
719480b9f2b948d29695ef3772bdb283 S RD-P Ts { physical: 1640198544509547 } kChangeMetadata: Apply
failed: Not found (yb/tablet/transaction_participant.cc:404): Abort of unknown transaction:
526a2884-e6ce-40ee-a989-9433fdf7c4d2, request: tablet_id: "d68305f580054900be93b5c68d1122b0"
...  alter_table_id: "000033df00003000800000000000420f" transaction_id: "2f51974b-0a21-4be8-9449-18ad981037a6" should_abort_active_txns: true
```
From the log we see
(1) The current transaction that covers this alter table schema write operation is `2f51974b-0a21-4be8-9449-18ad981037a6`.
(2) should_abort_active_txns is true, which means on successful flushing of the new table schema metadata to disk, we should abort all active transactions except itself.
(3) After a successful flush of the new table schema, this tablet (as a transaction participant) is trying to abort all other active transactions, one of them is `526a2884-e6ce-40ee-a989-9433fdf7c4d2`.
(4) `526a2884-e6ce-40ee-a989-9433fdf7c4d2` is not found, which suggests it is already aborted for some other reason (e.g., there was a conflicting higher pri transaction)
(5) Because of (4), the NotFound error is thrown like an exception and propagated up:
```
Abort 526a2884-e6ce-40ee-a989-9433fdf7c4d2 (NotFound) ->
StopActiveTxnsPriorTo ->
Tablet::AlterSchema ->
ChangeMetadataOperation::DoReplicated ->
Operation::Replicated ->
OperationDriver::ApplyTask (FATAL)
```
(6) The last FATAL crashed the tablet server.

But based upon the above situation, this is a legitimate case. Note that these two transactions
`2f51974b-0a21-4be8-9449-18ad981037a6` and `526a2884-e6ce-40ee-a989-9433fdf7c4d2` are not even related.
Therefore the FATAL isn't valid.

**Comment by myang2021** [comment] 2022-03-11 19:37
Duplicate of #11393

**Closed by myang2021** 2022-03-11 19:37 UTC
Labels: area/ysql
