### ISSUE TITLE
[YCQL] Document partition_hash function

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#3015] opened 2019-11-24 03:32 UTC
We haven't documented partition_hash() yet:

https://github.com/YugaByte/yugabyte-db/issues/374

Sample Usage:

https://github.com/YugaByte/yugabyte-db/issues/633#issuecomment-444584289

**Comment by ddorian** [comment] 2019-11-25 14:00
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/2492

**Closed** 2019-11-25 14:00 UTC
Labels: area/docdb
