### ISSUE TITLE
Drop table does not flush the existing cached prepared statements

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#497] opened 2018-10-08 18:07 UTC
Scenario is as follows:

* Created a table with the following schema and ran the sample app with prepared statements against this table:
```
CREATE TABLE IF NOT EXISTS %s (k varchar, v blob, primary key (k))
```

* Subsequently, changed the value type from `blob` to `varchar`:
```
CREATE TABLE IF NOT EXISTS %s (k varchar, v varchar, primary key (k))
```

* Next, dropped the old table, modified the load tester and ran it against this table. Hitting this issue:
```
com.datastax.driver.core.exceptions.CodecNotFoundException: 
Codec not found for requested operation: [blob <-> java.lang.String]
  at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:741)
  at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:602)
  at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:582)
  at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:507)
  at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
  at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:201)
  at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:140)
  at com.yugabyte.sample.apps.CassandraKeyValue.doWrite(CassandraKeyValue.java:200)
  at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:598)
  at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
```

**Workaround**:  restart the tablet servers in the cluster to flush the cache.

**Comment by m-iancu** [comment] 2022-03-03 01:57
Closing as duplicate of #10774.

**Closed by m-iancu** 2022-03-03 01:57 UTC
Labels: kind/bug
