### ISSUE TITLE
Known unresponsive tablet servers need to be quickly evicted from tablet location cache

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1052] opened 2019-03-21 21:34 UTC
We should not get into a situation when we have tablet location cache entries pointing to to tablet servers that the system already knows are unavailable (not replying to any RPCs, or even dead, i.e. not sending heartbeats to the master for 5 minutes), and we're sending RPCs to those tablet servers anyway and waiting for timeout. This could in theory happen e.g. after decommissioning a number of nodes.

**Comment by kmuthukk** [comment] 2019-03-22 00:31
We were able to reproduce the issue internally we were seeing with one of our users. This happens when a weaker consistency level (i.e. < QUORUM) is used for reads, and the cluster for example has nodes that were decommissioned. To repro:

* created a 5-node cluster
* ran a workload with ConsistencyLevel::One (for reads).
* decommissioned two of the nodes. 
* ran the same workload against the now 3-node cluster

But the active nodes still kept trying to ping the dead/decommissioned nodes every so often. We noticed these RPCs to 172.151.30.79 (one of the decommissioned server) from the http://172.151.22.161:9000/rpcz page where 172.151.22.161 was one of the live servers:

```
        {
            "remote_ip": "172.151.30.79:9100",
            "state": "OPEN",
            "calls_in_flight": [
                {
                    "header": {
                        "call_id": 9113596,
                        "remote_method": {
                            "service_name": "yb.tserver.TabletServerService",
                            "method_name": "Read"
                        },
                        "timeout_millis": 2499
                    },
                    "micros_elapsed": 349319
                }
            ]
        },
        {
            "remote_ip": "172.151.30.79:9100",
            "state": "OPEN",
            "calls_in_flight": [
                {
                    "header": {
                        "call_id": 9109997,
                        "remote_method": {
                            "service_name": "yb.tserver.TabletServerService",
                            "method_name": "Read"
                        },
                        "timeout_millis": 2499
                    },
                    "micros_elapsed": 2792296
                }
            ]
        },
```

Turning on verbose logging on 172-151-22-161 showed that its meta_cache still had '172.151.30.79' as a replica for one of the tablets, and we kept trying to see if that replica could be moved from "failed" to "not failed" state. 

```
[yugabyte@ip-172-151-22-161 ~]$ tail -f ~/tserver/logs/yb-tserver.INFO | grep meta_cache | grep -v "Fast lookup"
I0321 23:58:09.700031 25303 meta_cache.cc:336] T 390b177ce83c4ad698d89472c01bfb70: Changing state of replica { uuid: 0a9a2bede8c1409d84c868843e756b97 private: [host: "172.151.31.77" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" from failed to not failed
I0321 23:58:09.902503 26015 meta_cache.cc:336] T 28f9790f035542c1bdd54af717dcc921: Changing state of replica { uuid: 0a9a2bede8c1409d84c868843e756b97 private: [host: "172.151.31.77" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" from failed to not failed
I0321 23:58:09.902528 26015 meta_cache.cc:336] T 28f9790f035542c1bdd54af717dcc921: Changing state of replica { uuid: 750d5f7609da4bc1843651f25197c00a private: [host: "172.151.18.245" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" from failed to not failed
*I0321 23:58:12.335980 26015 meta_cache.cc:336] T d47f107ba7c142a5bc625544a419e3b3: Changing state of replica { uuid: a2bf8df7966c488fbdd4ac6308031820 private: [host: "172.151.30.79" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" from failed to not failed*
I0321 23:58:15.382427 24751 meta_cache.cc:254] T d47f107ba7c142a5bc625544a419e3b3: Current remote replicas in meta cache: 4bb9696641aa4fabbeea45d2704afb6f (FOLLOWER, OK), 750d5f7609da4bc1843651f25197c00a (LEADER, OK), a2bf8df7966c488fbdd4ac6308031820 (FOLLOWER, OK). Replica { uuid: a2bf8df7966c488fbdd4ac6308031820 private: [host: "172.151.30.79" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" has failed: Network error (yb/util/net/socket.cc:573): recvmsg error: No route to host (error 113)
```

As far as the Raft quorum is concerned, for tablet d47f107ba7c142a5bc625544a419e3b3,  172.151.22.161 the new peers are indeed correct:
```
LEADER: 172.151.18.245
FOLLOWER: 172.151.31.77
FOLLOWER: 172.151.22.161
```
But that node's meta_cache is stale and unnecessarily keeps pinging the dead servers because its notion of the replicas seems to not be updated correctly:

```
meta_cache.cc:254] T d47f107ba7c142a5bc625544a419e3b3: \
Current remote replicas in meta cache: \
4bb9696641aa4fabbeea45d2704afb6f (FOLLOWER, OK), \
750d5f7609da4bc1843651f25197c00a (LEADER, OK), \
a2bf8df7966c488fbdd4ac6308031820 (FOLLOWER, OK). \ --> This is the UUID of the dead server
```

Quorum reads (which in YB maps to read from leader) doesn't seem to suffer from this problem. This appears to be specific to code-paths that allow the weaker consistency level of allowing reads from tablet followers.  Symptom of this issue has been slower performance and in some cases operational timeouts.

**Comment by hectorgcr** [comment] 2019-03-22 15:17
I will work on a fix for this. In the meantime there are two flags that will minimize this problem:

- Flag `force_lookup_cache_refresh_secs` is currently disabled. But a reasonable value could be 60. When turned on, we will refresh the metadata cache periodically, so we can have the correct set of replicas for the tablets getting requests.

- Setting flag `retry_failed_replica_ms` (currently set to 60s) to a very large value will ensure that a failed replica is not selected.

**Closed** 2020-09-15 23:11 UTC
Labels: kind/enhancement, priority/high
