### ISSUE TITLE
[docs] Annotation for internal LBs on PKS in AWS

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#866] opened 2019-02-13 19:41 UTC
When using Pivotal Container/Kubernetes Services (PKS) as a provider, you can pass in custom annotations so that universes will be created using internal load balancers. Without this annotation, yugabyte universes will be created with a publicly addressable load balancer:

![screen shot 2019-02-13 at 1 38 17 pm](https://user-images.githubusercontent.com/5619476/52738655-b5024180-2f94-11e9-9b06-0cfcafed5642.png)

For AWS, this annotation would be ...

```yml
annotations:
  tserver:
      loadbalancer:
          service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

It could be helpful to have this annotation included in the documentation.

Thanks for the consideration!

**Comment by aegershman** [comment] 2019-05-09 17:02
Just did a fresh install of YW using `1.2.8.0-b1` image and didn't know which annotations to use. Our universes **have** to use internal LBs, so I needed to add these annotations back.

I tried the set of annotations that worked last time I tried YW (which was around March 12-ish? but there's no way for me to tell you the exact version because they're both 1.0.0):

```
annotations:
  tserver:
      loadbalancer:
          service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

But unfortunately none of these annotations were associated to the LB when `kubectl describe svc...` on them.

I also tried this and it didn't work:

```yml
service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

I also tried this:

```
yb-masters:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
yb-tservers:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

and this:

```
serviceEndpoints:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

and this:

```
serviceEndpoints:
  yb-masters:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

and this:

```
networkAnnotation:
  service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

None of these iterations worked, unfortunately. When performing a `kubectl describe svc <service> -n <namespace`, the `annotations` associated to the `yb-tserver-service` or `yb-master-service` was listed as `null`.

For any given version of yugaware, I don't know what version of the yugabyte helm chart it's deploying behind the scenes, and so I don't know what to fill out for annotation overrides.

/cc @ajcaldera1

**Comment by ramkumarvs** [comment] 2019-05-10 00:30
@aegershman since the time we added annotation, we started to focus on the multi cluster kubernetes , and annotation and bunch of custom overrides were moved to a top level entity called overrides, and this feature is not yet ready on our Stable channel or Beta Channel, which means technically no customers should be upgrading their YugaWare, this is a miscommunication, We iterate very fast within YugaByte but we also follow the Alpha/Beta/Stable construct for our release, and if a Customer is in Production with YugaByte would never get a Alpha or Beta feature unless they chose to. I can confirm these changes aren't in our Stable channel, because it is still miss the UI plumbing to make the feature completely functional. 

The UI work should complete before our next release and after comprehensive internal testing we promote to Stable channel.

**Comment by ramkumarvs** [comment] 2019-08-16 18:19
@aegershman sorry it took a bit long to have this properly documented on our docs, but here is the updated docs location. which gives some examples around how to add overrides.
https://docs.yugabyte.com/latest/deploy/enterprise-edition/configure-cloud-providers/#configure-k8s

Let me know if this is what you were looking for or you needed more information.

**Comment by ramkumarvs** [comment] 2019-08-21 05:17
@aegershman closing this issue, as we have documentation now, feel free to reopen if the documentation provided is not sufficient

**Closed by ramkumarvs** 2019-08-21 05:17 UTC
Labels: area/documentation, area/ui, community/request, kind/enhancement
