### ISSUE TITLE
[Platform] Delete Universe fails with fk constraint "fk_universe_uuid" on table "alert_definition" violation

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#7262] opened 2021-02-17 07:39 UTC
In 2.4.1.0-b25 build, when I try to delete a universe, I see the following FK violation in the Platform logs. 

```eddy-2410-mtlstest1:1839b04a-451c-4512-bd53-9afb99bea5f7
2021-02-17 07:24:19,258 [ERROR] from com.yugabyte.yw.commissioner.SubTaskGroup in TaskPool-13 - Failed to execute task java.util.concurrent.FutureTask@625138cd, hit error io.ebean.DataIntegrityException: Error[ERROR: update or delete on table "universe" violates foreign key constraint "fk_universe_uuid" on table "alert_definition"   Detail: Key (universe_uuid)=(1839b04a-451c-4512-bd53-9afb99bea5f7) is still referenced from table "alert_definition".].
java.util.concurrent.ExecutionException: io.ebean.DataIntegrityException: Error[ERROR: update or delete on table "universe" violates foreign key constraint "fk_universe_uuid" on table "alert_definition"   Detail: Key (universe_uuid)=(1839b04a-451c-4512-bd53-9afb99bea5f7) is still referenced from table "alert_definition".]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:177)
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:43)
	at com.yugabyte.yw.commissioner.tasks.DestroyUniverse.run(DestroyUniverse.java:90)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.ebean.DataIntegrityException: Error[ERROR: update or delete on table "universe" violates foreign key constraint "fk_universe_uuid" on table "alert_definition"   Detail: Key (universe_uuid)=(1839b04a-451c-4512-bd53-9afb99bea5f7) is still referenced from table "alert_definition".]
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:48)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:219)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:83)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:41)
	at io.ebeaninternal.server.core.PersistRequestBean.executeDelete(PersistRequestBean.java:1303)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:807)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNoBatch(PersistRequestBean.java:845)
	at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:836)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:879)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:596)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:576)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:568)
	at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1996)
	at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1987)
	at io.ebean.Model.delete(Model.java:238)
	at com.yugabyte.yw.models.Universe.delete(Universe.java:385)
	at com.yugabyte.yw.commissioner.tasks.subtasks.RemoveUniverseEntry.run(RemoveUniverseEntry.java:35)
	... 5 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "universe" violates foreign key constraint "fk_universe_uuid" on table "alert_definition"
```

Since I did a force delete, the universes don't show up in the UI but I see them in the platform database.

```
yugaware=# select count (*) from universe;
 count 
-------
     5
(1 row)

yugaware=# select universe_details_json from universe limit 1;
{"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"db0ee835-6d89-4f01-b9c2-8700bca33ed9","expectedUniverseVersion":-1,"cmkA
rn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":[],"communicat
ionPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlSe
rverHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExpor
ter":true},"firstTry":true,"clusters":[{"uuid":"eddb8f12-4fcd-40f4-9fcc-52c1577a0d36","clusterType":"PRIMARY","userIntent":{"universeName":"streddy-2410-tlssql
authbackuptest","provider":"7fa65291-2168-4273-a1db-421821315975","providerType":"aws","replicationFactor":3,"regionList":["c6437966-6f80-485d-a7aa-2b4ab19f088
b","5ca1d516-70ea-4012-b9e3-573e2dbc58e2"],"preferredRegion":null,"instanceType":"c5.large","numNodes":3,"ybSoftwareVersion":"2.4.1.0-b25","accessKeyCode":"yb-
dev-aws-key","deviceInfo":{"volumeSize":250,"numVolumes":2,"diskIops":null,"storageClass":"standard","mountPoints":null,"storageType":null},"assignPublicIP":tr
ue,"useTimeSync":false,"enableYSQL":true,"enableYEDIS":false,"enableNodeToNodeEncrypt":true,"enableClientToNodeEncrypt":false,"enableVolumeEncryption":false,"e
nableIPV6":false,"awsArnString":null,"useHostname":false,"masterGFlags":{},"tserverGFlags":{"ysql_enable_auth":"true","ysql_hba_conf_csv":"\"local all all trus
t\""},"instanceTags":{}},"placementInfo":{"cloudList":[{"uuid":"7fa65291-2168-4273-a1db-421821315975","code":"aws","regionList":[{"uuid":"c6437966-6f80-485d-a7
aa-2b4ab19f088b","code":"us-west-1","name":"US West (N. California)","azList":[{"uuid":"fcd78825-d593-4765-92a9-ea7fb7651883","name":"us-west-1a","replicationF
actor":1,"subnet":"subnet-1a5aa841","numNodesInAZ":1,"isAffinitized":true,"affinitized":true},{"uuid":"fe80f9e4-0b52-4c04-9d3d-5b6e92abc020","name":"us-west-1b
","replicationFactor":1,"subnet":"subnet-e8b01c8f","numNodesInAZ":1,"isAffinitized":true,"affinitized":true}]},{"uuid":"5ca1d516-70ea-4012-b9e3-573e2dbc58e2","
code":"us-west-2","name":"US West (Oregon)","azList":[{"uuid":"0aebb167-5f4f-4b0a-b56f-7eed61ce84fe","name":"us-west-2a","replicationFactor":1,"subnet":"subnet
-11798e59","numNodesInAZ":1,"isAffinitized":true,"affinitized":true}]}]}]},"index":0}],"preflight_checks":null,"nodePrefix":"yb-dev-streddy-2410-tlssqlauthback
uptest","rootCA":"93294827-1dc2-4b50-9c0f-46e5b9c5b857","userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateS
ucceeded":false,"nextClusterIndex":1,"allowInsecure":false,"itestS3PackagePath":"","importedState":"NONE","capability":"EDITS_ALLOWED"}
(1 row)
```

This is what I see in the platform database after I deleted my 5 universes. Looks like the alert definitions for clock_skew is not getting deleted properly.

```
yugaware=# select * from alert_definition ;
                 uuid                 |                                                                             query                                      
                                        |       name       |            universe_uuid             | is_active |            customer_uuid             
--------------------------------------+------------------------------------------------------------------------------------------------------------------------
----------------------------------------+------------------+--------------------------------------+-----------+--------------------------------------
 7f3fa7a7-02c7-4582-90e6-aeb8da17fffd | max by (node_prefix) (max_over_time(hybrid_clock_skew{node_prefix="yb-dev-streddy-2400-2410-upgrade-u1"}[10m])) / 1000 
> {{ yb.alert.max_clock_skew_ms }}      | Clock Skew Alert | f87b75db-07d0-4f44-97df-415e426405f3 | t         | 3faa8ac9-13e6-4414-920d-3b27228eef31
 99ac4915-cb98-4db4-a44f-d4fdd4472c79 | max by (node_prefix) (max_over_time(hybrid_clock_skew{node_prefix="yb-dev-streddy-2410-sqlauthenabled"}[10m])) / 1000 >
 {{ yb.alert.max_clock_skew_ms }}       | Clock Skew Alert | 684cf866-285d-400f-ac6b-4a9ab16ee70c | t         | 3faa8ac9-13e6-4414-920d-3b27228eef31
 709df25e-beb8-46b7-9b57-5c5af084071f | max by (node_prefix) (max_over_time(hybrid_clock_skew{node_prefix="yb-dev-streddy-2410-tlsbackuptest"}[10m])) / 1000 > 
{{ yb.alert.max_clock_skew_ms }}        | Clock Skew Alert | cad2802d-74af-4265-b331-37eeb181a1b9 | t         | 3faa8ac9-13e6-4414-920d-3b27228eef31
 28d039a2-0a36-4e71-8e71-d2f59aaf8a85 | max by (node_prefix) (max_over_time(hybrid_clock_skew{node_prefix="yb-dev-streddy-2410-tlssqlauthbackuptest"}[10m])) / 
1000 > {{ yb.alert.max_clock_skew_ms }} | Clock Skew Alert | db0ee835-6d89-4f01-b9c2-8700bca33ed9 | t         | 3faa8ac9-13e6-4414-920d-3b27228eef31
 5136de98-1e5b-4eb9-b977-ed9adf87ea06 | max by (node_prefix) (max_over_time(hybrid_clock_skew{node_prefix="yb-dev-streddy-2410-mtlstest1"}[10m])) / 1000 > {{ y
b.alert.max_clock_skew_ms }}            | Clock Skew Alert | 1839b04a-451c-4512-bd53-9afb99bea5f7 | t         | 3faa8ac9-13e6-4414-920d-3b27228eef31
(5 rows)
```
cc @SergeyPotachev

**Comment by streddy-yb** [comment] 2021-02-17 07:50
If I don't do "force delete" the universe, the Delete Universe task fails with this message although the universe disappears from my universe dashboard.

```
Failed to execute task java.util.concurrent.FutureTask@1c4b0363, hit error io.ebean.DataIntegrityException: Error[ERROR: update or delete on table "universe" violates foreign key constraint "fk_universe_uuid" on table "alert_definition"   Detail: Key (universe_uuid)=(6c792f1b-412f-4782-a8b7-728bee784d4e) is still referenced from table "alert_definition".].
```

![image](https://user-images.githubusercontent.com/68868569/108172435-b568d200-70b1-11eb-9500-98995dee23ff.png)

**Comment by SergeyPotachev** [comment] 2021-02-17 11:19
We need to back port migration V57 to 2.4.  cc @streddy-yb @sb-yb

**Comment by SergeyPotachev** [comment] 2021-02-17 11:30
The problem could be reproduced on older releases if set the replication lag parameter and then try to remove the universe. Commit for #6017 only discovered the problem.
Looks like a duplicate of #6698.

**Closed** 2021-03-01 18:15 UTC
Labels: 2.4 Backport Required, area/platform

**Comment by SergeyPotachev** [comment] 2021-04-22 18:40
No QA verification is needed. After the new migration is applied the problem should not occur anymore.
