### ISSUE TITLE
[doc] YCQL DELETE woks for range deletes. 

### ISSUE THREAD

**Issue by Tasneem9879** [yugabyte/yugabyte-db#8801] opened 2021-06-07 20:24 UTC
In our docs we say [Currently, YugabyteDB can deletes one row at a time. Deleting multiple rows is not yet supported.](https://docs.yugabyte.com/latest/api/ycql/dml_delete/ )

There is one exception to the “delete multipe rows case”. We support what we call range-delete, where you can delete multiple rows within one partition (hash). So if the primary key is ((h1, h2), r1, r2) then you can delete multiple rows within one hash partition like:

```
delete from t where h1 = 1 and h2 = 1 ...

```

There’s some documentation about that here: https://docs.yugabyte.com/latest/api/ycql/dml_delete/#delete-several-rows-with-the-same-partition-key

As per discussion with Mihnea,  the sentence should be updated to clarify this or maybe we can just omit those two sentences entirely to keep it simple.

**Comment by lizayugabyte** [comment] 2021-06-23 16:55
This is a duplicate of https://github.com/yugabyte/yugabyte-db/issues/8983. Closing as duplicate.

**Closed** 2021-06-23 16:55 UTC
Labels: area/documentation
