### ISSUE TITLE
[DocDB] Truncating colocated table failed to clear table data

### ISSUE THREAD

**Issue by lnguyen-yugabyte** [yugabyte/yugabyte-db#15206] opened 2022-12-02 19:55 UTC
Jira Link: [DB-4389](https://yugabyte.atlassian.net/browse/DB-4389)
### Description

Create a file `tbl.csv` with 1M rows. (note that the issue only manifests with a sufficiently large file)

```
LINE 1: create database t with (colocated = true);
                               ^
yugabyte=# create database t with colocated = true;
WARNING:  'colocated' syntax will be deprecated in a future release
LINE 1: create database t with colocated = true;
                               ^
HINT:  Use 'colocation' instead of 'colocated'.
CREATE DATABASE
yugabyte=# \c t;
You are now connected to database "t" as user "yugabyte".
t= create table tbl (id int primary key) WITH (colocated = true);
WARNING:  'colocated' syntax will be deprecated in a future release
HINT:  Use 'colocation' instead of 'colocated'.
CREATE TABLE
t=# copy tbl from 'tbl.csv' with (format csv);
COPY 1000000
t=# select count(*) from tbl;
 count
-------
     0
(1 row)
t=# truncate tbl;
TRUNCATE TABLE
t=# copy tbl from 'tbl' with (format csv);
ERROR:  duplicate key value violates unique constraint "tbl_pkey"
```

[DB-4389]: https://yugabyte.atlassian.net/browse/DB-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment] 2023-01-06 20:37
The underlying issue seems to be a result of the timed out RPC which does not result in a clean cancellation and can result in some records being left behind. The select that follows immediately after the failed RPC may still see 0 records because the previous txn has not yet committed and is running in the background, however a select after you get the unique constraint failure would most likely indicate that there were actually records in the table. 

If copy were to use transactions under the cover, then you would not have this atomicity issue.

Confirmed the above with the repro below:

```
t=# truncate table cast_info;
TRUNCATE TABLE
t=# select count(*) from cast_info;
 count
-------
     0
(1 row)

t=# select count(*) from cast_info;
 count
-------
     0
(1 row)

t=# copy cast_info from '/Users/sandeep/scratch/imdb/cast_info.csv' with (format csv);
ERROR:  Timed out: Perform RPC (request call id 113) to 127.0.0.1:9100 timed out after 120.000s
t=# copy cast_info from '/Users/sandeep/scratch/imdb/cast_info.csv' with (format csv);
ERROR:  duplicate key value violates unique constraint "cast_info_pkey"
t=# select count(*) from cast_info;
 count
-------
 80000
(1 row)
```

**Comment by rthallamko3** [comment] 2023-02-16 23:46
@Huqicheng , This impacts colocated tables, so lets track it for 2.18 timeframe.

**Comment by Huqicheng** [comment] 2023-02-23 21:21
I0223 21:07:19.547874 47228 intent_aware_iterator.cc:816] FindLatestRecord: SubDocKey(DocKey(ColocationId=3743027366, [], []), []), HT<min>
I0223 21:07:19.547892 47228 intent_aware_iterator.cc:816] FindLatestRecord: SubDocKey(DocKey(ColocationId=3743027366, [], [23839]), []), HT<min>
I0223 21:07:19.547907 47228 doc_reader.cc:464] DocKey(ColocationId=3743027366, [], [23839]): Prepare: Write time: HT<min>, control fields:

Didn't get the actual ht of tombstone record `SubDocKey(DocKey(ColocationId=3743027366, [], []), [])`, hence fail to update tombstone timestamp

**Comment by Huqicheng** [comment] 2023-03-01 18:22
Dump the tablet data after duplicate key error happens, seems the tombstone is still in the docdb :(
```
5084424 I0301 17:39:39.493124 226238 pg_mini-test.cc:907] jonathan a2f155e3c7db43ba8f4b2aac8ea1613a Dumping tablet:
5084425 ---------------------------                                                                          
5084426 SubDocKey(DocKey(ColocationId=536392769, [], []), [HT{ days: 19417 time: 17:38:37.843961 }]) -> DEL; intent doc ht: HT{ days: 19417 time: 17:38:37.791630 }
5084427 SubDocKey(DocKey(ColocationId=536392769, [], [0]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 }]) -> null; intent doc ht: HT{ days: 19417 time: 17:38:4        7.946586 }
5084428 SubDocKey(DocKey(ColocationId=536392769, [], [1]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 1 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 1 }
5084429 SubDocKey(DocKey(ColocationId=536392769, [], [1]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6144 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 }
5084430 SubDocKey(DocKey(ColocationId=536392769, [], [2]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 2 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 2 }
5084431 SubDocKey(DocKey(ColocationId=536392769, [], [2]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6145 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 w: 1 }
5084432 SubDocKey(DocKey(ColocationId=536392769, [], [3]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 3 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 3 }
5084433 SubDocKey(DocKey(ColocationId=536392769, [], [3]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6146 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 w: 2 }
5084434 SubDocKey(DocKey(ColocationId=536392769, [], [4]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 4 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 4 }
5084435 SubDocKey(DocKey(ColocationId=536392769, [], [4]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6147 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 w: 3 }
5084436 SubDocKey(DocKey(ColocationId=536392769, [], [5]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 5 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 5 }
5084437 SubDocKey(DocKey(ColocationId=536392769, [], [5]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6148 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 w: 4 }
5084438 SubDocKey(DocKey(ColocationId=536392769, [], [6]), [SystemColumnId(0); HT{ days: 19417 time: 17:38:47.948923 w: 6 }]) -> null; intent doc ht: HT{ days: 19417 time: 17        :38:47.946586 w: 6 }
5084439 SubDocKey(DocKey(ColocationId=536392769, [], [6]), [SystemColumnId(0); HT{ days: 19417 time: 17:37:27.413255 w: 6149 }]) -> null; intent doc ht: HT{ days: 19417 time:         17:37:26.776740 w: 5 }
```

**Comment by Huqicheng** [comment] 2023-03-01 22:27
15905586 I0301 22:23:31.277781 257075 pgsql_operation.cc:513] Write, read time: { read: { days: 19417 time: 22:23:29.452784 } local_limit: { days: 19417 time: 22:23:29.952784          } global_limit: { days: 19417 time: 22:23:29.952784 } in_txn_limit: <max> serial_no: 0 }, txn: 8081aae4-40fc-4a0b-b9a6-a677ba7c7ca7

**Comment by Huqicheng** [comment] 2023-03-02 16:13
The issue is in DocRowwiseIterator layer, where based on the input keys, we decide whether to use rocksdb file bloom filters to filter out files. However the iterator does not include table tombstone key to this bloom filter check (also RocksDB only supports using bloom filter for a single key), therefore the rocksdb file which had the table tombstone key was filtered out.

**Closed** 2023-03-14 19:34 UTC
Labels: kind/bug, area/ysql, priority/medium
