### ISSUE TITLE
[YSQL] Locking Querying Rows

### ISSUE THREAD

**Issue by nocaway** [YugaByte/yugabyte-db#743] opened 2019-01-11 22:39 UTC
The following clause in SELECT for locking rows is not yet supported.
SELECT ...
  [ FOR
         { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE }
         [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...]
  ]

**Comment by m-iancu** [comment] 2019-06-05 17:49
Duplicate of #1199 .

**Closed by m-iancu** 2019-06-05 17:49 UTC
Labels: enhancement
