### ISSUE TITLE
[Platform] Azure - Nodes are not showing as hyperlinks in Nodes tab

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7299] opened 2021-02-19 01:59 UTC
For Azure, the universe nodes are showing as hyper links

http://portal.dev.yugabyte.com/universes/2a91769a-67f4-4d01-8816-1a0a59e42a4b/nodes
﻿
<img width="1400" alt="Screen Shot 2021-02-18 at 5 58 19 PM" src="https://user-images.githubusercontent.com/78048211/108446420-edd3f180-7212-11eb-9517-b02171b93815.png">

**Comment by VijiYB** [comment] 2021-02-19 02:02
I meant "not showing as hyperlink" while AWS nodes show as hyperlink.

**Comment by SergeyPotachev** [comment] 2021-02-19 08:07
Duplicate of #5838.

**Comment by VijiYB** [comment] 2021-04-20 22:31
Implemented in #5838.

**Closed** 2021-04-20 22:30 UTC
Labels: area/platform
