### ISSUE TITLE
[DocDB] org.yb.loadtester.TestClusterWithHighLoadAndSlowSync.testClusterFullMoveWithHighLoadAndSlowSync flaky in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#10797] opened 2021-12-07 16:57 UTC
Jira Link: [DB-1169](https://yugabyte.atlassian.net/browse/DB-1169)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&class=org.yb.loadtester.TestClusterWithHighLoadAndSlowSync&name=testClusterFullMoveWithHighLoadAndSlowSync

**Comment by m-iancu** [comment] 2022-09-06 18:49
Closing as duplicate of #13889.

**Closed by m-iancu** 2022-09-06 18:49 UTC
Labels: kind/bug, kind/failing-test, area/docdb, priority/medium
