### ISSUE TITLE
Loading data using TPC-C sometimes lead to "Duplicate Request" error.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#5751] opened 2020-09-21 17:07 UTC
Loading of data using TPC-C is a strenuous activity with our CPU usage hovering around the 80% mark when we have as many loader threads as the number of cores in the YugabyteDB cluster {So we use 48 loader threads on a 3-node C5d.4xl cluster where each node has 16 cores}.

Running the setup on a 3 node c5d.2XL with 24 loader threads caused the client to crash with the "Duplicate Request" error.
```
java.lang.RuntimeException: Unexpected fatal, error in 'TPCCWorker<038>' when executing 'Payment/02' [POSTGRES]
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:516)
        at com.oltpbenchmark.api.Worker.run(Worker.java:316)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: Already present: Duplicate request
```
The only difference in this setup compared to our usual runs is that the client was in US-west and the cluster was in US-east. Generally we run the client and the server in the same zone.

Steps to re-create the setup. Create a 3 node c5d.2xl  cluster all in the same zone in US-east. Create a benchmark node to run TPC-C in US-west and then perform the load as:
```
./tpccbenchmark --nodes=n1,n2,n3 --create=true --load=true --warehouses=100 --loaderthreads=24
```

**Comment by robertsami** [comment] 2020-10-06 21:06
closing in favor of https://github.com/yugabyte/yugabyte-db/issues/5700, which will address the immediate concern that we should not surface this error to users as its overly specific about database internals

a remaining open issue https://github.com/yugabyte/yugabyte-db/issues/5673 captures the intent to understand the root cause of these issues and determine if this is expected behavior

**Closed by robertsami** 2020-10-06 21:06 UTC
Labels: area/docdb
