### ISSUE TITLE
[YSQL] Assertion failed on TRUNCATE TABLE command

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#1632] opened 2019-06-26 15:25 UTC
The following sequence of commands 

```
postgres=# create table t(k int, v int);
postgres=# create index on t(k);
postgres=# truncate t;
```

on newly created `debug` cluster causes `assertion failed` error

```
I0626 15:18:41.137012 16755 catalog_manager.cc:2426] Servicing TruncateTable request from 127.0.0.1:52537: table_ids: "000030a500003000
8000000000004003"
F0626 15:18:41.137035 16755 catalog_manager.cc:2454] Check failed: is_index == !l->data().pb.indexed_table_id().empty()
```

**Comment by ddorian** [comment] 2019-10-31 15:06
duplicate of https://github.com/yugabyte/yugabyte-db/issues/2666 ?

**Comment by OlegLoginov** [comment] 2019-12-02 11:37
Reproduced on the latest build.
```
I1202 14:35:10.074077 16629 catalog_manager.cc:2584] Servicing TruncateTable request from 127.0.0.1:53205: table_ids: "000030a9000030008000000000004103"
F1202 14:35:10.074110 16629 catalog_manager.cc:2612] Check failed: is_index == (l->data().pb.has_index_info() || !l->data().pb.indexed_table_id().empty()) 

```

**Comment by OlegLoginov** [comment] 2019-12-02 11:50
Stack:
```libmaster.so!yb::master::CatalogManager::TruncateTable(yb::master::CatalogManager * const this,  table_id, const bool is_index, yb::master::TruncateTableResponsePB * resp, yb::rpc::RpcContext * rpc) (/home/oleg/code/yugabyte-db3/src/yb/master/catalog_manager.cc:2618)
libmaster.so!yb::master::CatalogManager::TruncateTable(yb::master::CatalogManager * const this, const yb::master::TruncateTableRequestPB * req, yb::master::TruncateTableResponsePB * resp, yb::rpc::RpcContext * rpc) (/home/oleg/code/yugabyte-db3/src/yb/master/catalog_manager.cc:2590)
libmaster.so!void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::TruncateTableRequestPB, yb::master::TruncateTableResponsePB>(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*), yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)::{lambda()#1}::operator()() const(const yb::master::MasterServiceBase::<lambda()> * const __closure) (/home/oleg/code/yugabyte-db3/src/yb/master/master_service_base-internal.h:94)
libmaster.so!yb::master::MasterServiceBase::HandleOnLeader<yb::master::TruncateTableRequestPB, yb::master::TruncateTableResponsePB, void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::TruncateTableRequestPB, yb::master::TruncateTableResponsePB>(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*), yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)::{lambda()#1}>(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*, void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::TruncateTableRequestPB, yb::master::TruncateTableResponsePB>(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::TruncateTableRequestPB const*, yb::master::TruncateTableResponsePB*, yb::rpc::RpcContext*), yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)::{lambda()#1}, yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)(yb::master::MasterServiceBase * const this, const yb::master::TruncateTableRequestPB * req, yb::master::TruncateTableResponsePB * resp, yb::rpc::RpcContext * rpc, yb::master::MasterServiceBase::<lambda()> f, yb::master::HoldCatalogLock hold_catalog_lock) (/home/oleg/code/yugabyte-db3/src/yb/master/master_service_base-internal.h:50)
libmaster.so!yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::TruncateTableRequestPB, yb::master::TruncateTableResponsePB>(yb::Status (yb::master::CatalogManager::*)(yb::master::CatalogManager * const, const yb::master::TruncateTableRequestPB *, yb::master::TruncateTableResponsePB *, yb::rpc::RpcContext *) f, yb::rpc::RpcContext * rpc, yb::master::TruncateTableResponsePB * resp, const yb::master::TruncateTableRequestPB * req, yb::master::MasterServiceBase * const this) (/home/oleg/code/yugabyte-db3/src/yb/master/master_service_base-internal.h:93)
libmaster.so!yb::master::MasterServiceImpl::TruncateTable(yb::master::MasterServiceImpl * const this, const yb::master::TruncateTableRequestPB * req, yb::master::TruncateTableResponsePB * resp, yb::rpc::RpcContext rpc) (/home/oleg/code/yugabyte-db3/src/yb/master/master_service.cc:274)
libmaster_proto.so!yb::master::MasterServiceIf::Handle(yb::master::MasterServiceIf * const this, yb::rpc::InboundCallPtr call) (/home/oleg/code/yugabyte-db3/build/debug-gcc-dynamic-ninja/src/yb/master/master.service.cc:490)
libyrpc.so!yb::rpc::ServicePoolImpl::Handle(yb::rpc::ServicePoolImpl * const this, yb::rpc::InboundCallPtr incoming) (/home/oleg/code/yugabyte-db3/src/yb/rpc/service_pool.cc:250)
libyrpc.so!yb::rpc::InboundCall::InboundCallTask::Run(yb::rpc::InboundCall::InboundCallTask * const this) (/home/oleg/code/yugabyte-db3/src/yb/rpc/inbound_call.cc:207)
libyrpc.so!yb::rpc::(anonymous namespace)::Worker::Execute(yb::rpc::(anonymous namespace)::Worker * const this) (/home/oleg/code/yugabyte-db3/src/yb/rpc/thread_pool.cc:99)
libyrpc.so!std::__invoke_impl<void, void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&>() (/usr/include/c++/7/bits/invoke.h:73)
libyrpc.so!std::__invoke<void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&>( __fn) (/usr/include/c++/7/bits/invoke.h:95)
libyrpc.so!std::_Bind<void (yb::rpc::(anonymous namespace)::Worker::*(yb::rpc::(anonymous namespace)::Worker*))()>::__call<void, 0>(std::_Bind<void (yb::rpc::(anonymous namespace)::Worker::*(yb::rpc::(anonymous namespace)::Worker*))()> * const this) (/usr/include/c++/7/functional:467)
libyrpc.so!std::_Bind<void (yb::rpc::(anonymous namespace)::Worker::*(yb::rpc::(anonymous namespace)::Worker*))()>::operator()<>(std::_Bind<void (yb::rpc::(anonymous namespace)::Worker::*(yb::rpc::(anonymous namespace)::Worker*))()> * const this) (/usr/include/c++/7/functional:551)
libyrpc.so!std::_Function_handler<void(), std::_Bind<void (yb::rpc::(anonymous namespace)::Worker::*(yb::rpc::(anonymous namespace)::Worker*))()> >::_M_invoke(const std::_Any_data &)( __functor) (/usr/include/c++/7/bits/std_function.h:316)
libyb_util.so!std::function<void ()>::operator()() const(const std::function<void()> * const this) (/usr/include/c++/7/bits/std_function.h:706)
libyb_util.so!yb::Thread::SuperviseThread(void * arg) (/home/oleg/code/yugabyte-db3/src/yb/util/thread.cc:741)
libpthread.so.0!start_thread(void * arg) (/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c:463)
libc.so.6!clone() (/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/x86_64/clone.S:95)```

**Comment by OlegLoginov** [comment] 2019-12-02 12:04
Received TRUNCATE request references Index table - 't3_k_idx' id=*4303, instead of the main table 't3' id=*4300:
```
I1202 14:59:52.982560 21200 catalog_manager.cc:2589] Servicing TruncateTable request from 127.0.0.1:42229: table_ids: "000030a9000030008000000000004303"
I1202 14:59:52.982586 21200 catalog_manager.cc:2617] TABLE PB: name: "t3_k_idx" version: 0 schema { columns { id: 10 name: "k" type { main: INT32 } is_key: true is_hash_key: true is_nullable: false is_static: false is_counter: false sorting_type: 0 order: 1 } columns { id: 11 name: "ybidxbasectid" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: -101 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false } } state: RUNNING next_column_id: 12 partition_schema { range_schema { } hash_schema: PGSQL_HASH_SCHEMA } table_type: PGSQL_TABLE_TYPE namespace_id: "000030a9000030008000000000000000" indexed_table_id: "000030a9000030008000000000004300" is_local_index: false is_unique_index: false index_info { table_id: "000030a9000030008000000000004303" indexed_table_id: "000030a9000030008000000000004300" }
```
But in the source code expected only BASE table, not an index:
```
Status CatalogManager::TruncateTable(const TruncateTableRequestPB* req,
                                     TruncateTableResponsePB* resp,
                                     rpc::RpcContext* rpc) {
  LOG(INFO) << "Servicing TruncateTable request from " << RequestorString(rpc)
            << ": " << req->ShortDebugString();

  RETURN_NOT_OK(CheckOnline());

  for (int i = 0; i < req->table_ids_size(); i++) {
    RETURN_NOT_OK(TruncateTable(req->table_ids(i), false /* is_index */, resp, rpc));       <<<<<<<<<<<<<<<<<<<<<< is_index == FALSE always
  }
```

**Comment by OlegLoginov** [comment] 2019-12-02 13:41
Note: original table was successfully truncated before. Then PgGate tried to truncate Index via TruncateTable API:
```
I1202 16:32:13.878113  1798 catalog_manager.cc:2589] Servicing TruncateTable request from 127.0.0.1:42311: table_ids: "000030a9000030008000000000004400"
I1202 16:32:13.878226  1798 catalog_manager.cc:2617] TABLE PB: name: "t4" version: 0 schema { columns { id: 10 name: "ybrowid" type { main: BINARY } is_key: true is_hash_key: true is_nullable: false is_static: false is_counter: false sorting_type: 0 order: -100 } columns { id: 11 name: "k" type { main: INT32 } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 1 } columns { id: 12 name: "v" type { main: INT32 } is_key: false is_nullable: true is_static: false is_counter: false sorting_type: 0 order: 2 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false } } state: RUNNING next_column_id: 13 partition_schema { range_schema { } hash_schema: PGSQL_HASH_SCHEMA } table_type: PGSQL_TABLE_TYPE namespace_id: "000030a9000030008000000000000000"
I1202 16:32:13.878283  1798 catalog_manager.cc:2646] T 00000000000000000000000000000000 P 6c089b357bfb4e4a9278865174c42d57: Truncating tablet f5dc41d5f1f14ef58908fdbc18f6efc8
I1202 16:32:13.878355  1798 catalog_manager.cc:2646] T 00000000000000000000000000000000 P 6c089b357bfb4e4a9278865174c42d57: Truncating tablet 7608e548b02349cea92fd7e9026ee111
I1202 16:32:13.878371  1798 catalog_manager.cc:2624] Successfully initiated TRUNCATE for t4 [id=000030a9000030008000000000004400] per request from 127.0.0.1:42311
I1202 16:32:13.878974  1924 catalog_manager.cc:2655] Servicing IsTruncateTableDone request for table id 000030a9000030008000000000004400
I1202 16:32:13.904620  1765 catalog_manager.cc:2655] Servicing IsTruncateTableDone request for table id 000030a9000030008000000000004400
I1202 16:32:13.933257  1798 catalog_manager.cc:2655] Servicing IsTruncateTableDone request for table id 000030a9000030008000000000004400
I1202 16:32:13.968488  1798 catalog_manager.cc:2589] Servicing TruncateTable request from 127.0.0.1:42311: table_ids: "000030a9000030008000000000004403"
I1202 16:32:13.968518  1798 catalog_manager.cc:2617] TABLE PB: name: "t4_k_idx" version: 0 schema { columns { id: 10 name: "k" type { main: INT32 } is_key: true is_hash_key: true is_nullable: false is_static: false is_counter: false sorting_type: 0 order: 1 } columns { id: 11 name: "ybidxbasectid" type { main: BINARY } is_key: true is_nullable: false is_static: false is_counter: false sorting_type: 1 order: -101 } table_properties { contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false } } state: RUNNING next_column_id: 12 partition_schema { range_schema { } hash_schema: PGSQL_HASH_SCHEMA } table_type: PGSQL_TABLE_TYPE namespace_id: "000030a9000030008000000000000000" indexed_table_id: "000030a9000030008000000000004400" is_local_index: false is_unique_index: false index_info { table_id: "000030a9000030008000000000004403" indexed_table_id: "000030a9000030008000000000004400" }
F1202 16:32:13.968559  1798 catalog_manager.cc:2618] Check failed: is_index == (l->data().pb.has_index_info() || !l->data().pb.indexed_table_id().empty()) 

```

**Comment by OlegLoginov** [comment] 2019-12-02 13:48
In fact the Postgres side truncate the main table and the indexes after that:
```
void
YBCTruncateTable(Relation rel) {
	YBCPgStatement handle;
	Oid relationId = RelationGetRelid(rel);

	/* Truncate the base table */
	HandleYBStatus(YBCPgNewTruncateTable(ybc_pg_session, MyDatabaseId, relationId, &handle));
	HandleYBStmtStatus(YBCPgExecTruncateTable(handle), handle);
	HandleYBStatus(YBCPgDeleteStatement(handle));

	if (!rel->rd_rel->relhasindex)
		return;

	/* Truncate the associated secondary indexes */
	List	 *indexlist = RelationGetIndexList(rel);
	ListCell *lc;

	foreach(lc, indexlist)
	{
		Oid indexId = lfirst_oid(lc);

		if (indexId == rel->rd_pkindex)
			continue;

		HandleYBStatus(YBCPgNewTruncateTable(ybc_pg_session, MyDatabaseId, indexId, &handle));
		HandleYBStmtStatus(YBCPgExecTruncateTable(handle), handle);
		HandleYBStatus(YBCPgDeleteStatement(handle));
	}

	list_free(indexlist);
}
```
But YB side should automatically delete related indexes if the table was truncated.
So, there are 2 options for the fix:
1) Let's try to truncate the index (from Postgres), even if it was truncated together with the tale.
2) Do not truncate indexes. (It must be automatically truncated by YB server before - via the TRUNCATE <table> request).

**Comment by OlegLoginov** [comment] 2019-12-06 13:03
The option (2) above is not applicable.
The CatalogManager::TruncateTable automatically truncates associated indexes, but PG table does not have the links in the table record, so the code does nothing for PG table (it truncates indexes for CQL table only at the moment):
```
for (const auto& index_info : l->data().pb.indexes()) {
  RETURN_NOT_OK(TruncateTable(index_info.table_id(), resp, rpc));
```
The links are NOT created for PG table in the CatalogManager::CreateTable():
```
// For index table, insert index info in the indexed table.
if ((req.has_index_info() || req.has_indexed_table_id()) && !is_pg_table) {     <<<<<<<<<<<< !is_pg_table
  s = AddIndexInfoToTable(indexed_table, index_info);
```

**Closed** 2019-12-07 09:12 UTC
Labels: area/sql, kind/bug
