### ISSUE TITLE
[YSQL] Distributed tables snapshots 

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#2084] opened 2019-08-16 15:00 UTC
Working on #1970 I expected multi-table snapshots.

If there are distributed-transactions, there need to be distributed-backups across tables.

**Comment by rkarthik007** [comment] 2020-03-31 21:17
This is tracked by https://github.com/yugabyte/yugabyte-db/issues/2620

Closing as a duplicate of the above.

**Closed by rkarthik007** 2020-03-31 21:17 UTC
Labels: area/docdb, community/request, kind/enhancement
