### ISSUE TITLE
[YSQL] ysqlsh fails to connect after universe upgrade

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#5856] opened 2020-09-28 18:34 UTC
As part of test_upgrade in iTest run, we deploy universe with "2.0.5.7" version build #b9. In a run with upgrade of universe to 2.3.2.0 branch build #b1, I notice that ysqlsh throws "ysqlsh: FATAL:  Query error: Bad schema: Cannot have both cotable ID and pgtable ID" exception. ysqlsh is able to successfully connect prior to the upgrade.

**Comment by jaki** [comment] 2020-09-28 18:38
The error is a duplicate of #5658.  Closing.

**Closed by jaki** 2020-09-28 18:38 UTC
