### ISSUE TITLE
[ybase] Creating an index and inserting data at the same time gives inconsistent results

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#9388] opened 2021-07-20 18:33 UTC
When a transaction is open on a session adding data to a table. (transaction A)

And another transaction is open in another session on the table to create an index i.e. ASC on the primary key (transaction B)
If the transaction to add the index (transaction B) is committed before the transaction to add data (transaction A).

On selecting, if the index is not used all the data is returned.
i.e. select * from table;

But if the index is used in the query, the data added in (Transaction A) is not displayed
i.e. select * from table order by column ASC;

Example 
Create Table t( k INT PRIMARY KEY)
Insert data to t ....
select k fro t;      -- All rows displayed

Transaction A
begin transaction;
insert more data to t
i.e. insert int t values (...)

Transaction B
begin transaction;
create an index
i.e. create index t_idx on t (k ASC);

Commit; Transaction B
Commit; Transaction A

select k from t;                               -- All rows displayed
select k from t order by k;             -- Rows from Transaction A not displayed

**Comment by jaki** [comment] 2021-07-20 19:28
We generally don't yet guarantee correctness of DDLs within transaction blocks.  Here, you have a CREATE INDEX inside transaction block.

**Comment by jaki** [comment] 2021-07-20 20:41
@m-iancu points out that, although the DDL in txn block problem exists, it doesn't really impact the behavior seen in this issue.

The true issue is with concurrent being false when in nested DDL, meaning that the index is not built using online schema changes.  This is then a duplicate of issue #6240.

**Comment by jaki** [comment] 2021-07-31 00:39
Closing as duplicate of issue #6240.  See also issue #9550.

**Closed by jaki** 2021-07-31 00:39 UTC
Labels: area/ysql, kind/bug
